### ISSUE TITLE
Is Aws::SQS::Client#send_message multithreaded?

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-ruby#1001]
> Like many other AWS services, SQS is accessed through HTTP request-response, and a typical SQS request-response takes a bit less than 20ms from EC2. This means that from a single thread you can, on average, issue 50+ API requests / sec.

https://aws.amazon.com/blogs/aws/scaling-with-amazon-sqs/

How Is Aws::SQS::Client#send_message works seems to be opaque to the user - I don't know whether my enqueueing actions are single-threaded or backed by a thread/http-connection pool.

Does Aws::SQS::Client#send_message offer any request parallelism as of today? Should I create a thread pool wrapping Client instances, or that work is done already?

Cheers - Victor

**Comment by awood45** [comment]
The client is thread-safe, so if you share a single client across threads you will get request parallelism. Within a single thread, the client will block on the request completing, so you should be using threads to get parallelism.

Feel free to let me know if you have more questions!

**Comment by vemv** [comment]
Thank you @awood45 for an accurate answer!

You might want to reflect that in the documentation.

Victor
