### ISSUE TITLE
Getting intermittent Aws::RDS::Errors::Http408Error after updating to 2.1.36

### ISSUE THREAD

**Issue by lardcanoe** [aws/aws-sdk-ruby#1002]
We had been pinned to 2.0.33 for 9+ months (afaik). We just updated to 2.1.36, and are now getting intermittent `Aws::RDS::Errors::Http408Error: Failed to read request bytes.` exceptions. A 408 wouldn't be an error I'd expect to start getting from an update like this. Can you think of any reason for it?

**Comment by awood45** [comment]
Can you give me a code snippet to recreate the issue?

**Comment by lardcanoe** [comment]
I'm going to collect data overnight to see if it is a certain region.

**Comment by awood45** [comment]
No problem! It will be helpful as well if you can provide a wire trace in case it is not reliably reproducible. You can do this by adding the `:http_wire_trace` parameter to client construction.
```ruby
client = Aws::RDS::Client.new(http_wire_trace: true)
```

**Comment by lardcanoe** [comment]
Over 95% of these errors are in ap-southeast-2. Now why 2.1.36 reports this whereas 2.0.33 doesn't is beyond me, but I'm not gonna worry about it. Just another one to consider retryable.

Thanks.

**Comment by awood45** [comment]
Let me know if you find any more info about this, I'd be curious to dig in to this more.
