### ISSUE TITLE
Unclear how to pass multiple securityGroupIds to Aws::DataPipeline::Client#put_pipeline_definition

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-ruby#1005]
`{key: 'securityGroupIds', string_value: "foo"}` works, foo being a single valid security group id.

It is unclear how to pass multiple ids. I tried `"foo, bar"`, `['foo', 'bar']`, etc. to no avail.

Looks like parameter_objects or parameter_values could help but no idea, the documentation is a little too succint. http://docs.aws.amazon.com/sdkforruby/api/Aws/DataPipeline/Client.html#put_pipeline_definition-instance_method

**Comment by trevorrowe** [comment]
I'm not very familiar with that particular API, but my guess is that you would simply pass that has multiple times, each time with the key `"securityGroupIds"` and then different string values:

```
[
  {key: 'securityGroupIds', string_value: "security-group-id-1"},
  {key: 'securityGroupIds', string_value: "security-group-id-2"},
]
```

**Comment by awood45** [comment]
What Trevor showed should work - if not, can you give a full reproducing call?

**Comment by vemv** [comment]
Confirming it works, feel free to close the issue.

Consider indicating this in the documentation, the syntax makes sense but it's perfectly possible to not figure it out.
