### ISSUE TITLE
Aws::CloudWatch::Client#describe_alarms_for_metric doesn't seem to work

### ISSUE THREAD

**Issue by dominikgrygiel** [aws/aws-sdk-ruby#1008]
I've tried to use #describe_alarms_for_metric with different parameters (changing unit, period, statistic) with no success. It always see to return empty response for me. Example:

```
[1] pry(main)> namespace = 'AWS/DynamoDB'
=> "AWS/DynamoDB"
[2] pry(main)> metric_name = 'ConsumedWriteCapacityUnits'
=> "ConsumedWriteCapacityUnits"
[3] pry(main)> $cloudwatch.describe_alarms_for_metric(namespace: namespace, metric_name: metric_name).metric_alarms.size
=> 0
[4] pry(main)> $cloudwatch.describe_alarms.metric_alarms.select { |a| a.namespace == namespace && a.metric_name == metric_name }.size
=> 10
```

**Comment by awood45** [comment]
Do you have any alarms configured for that metric, currently? What's an example of an alarm you're trying to see? (I'll try to recreate on my end.)

**Comment by dominikgrygiel** [comment]
Yes, I have. Please look at the snippet that I've pasted in my first comment. As you can see when I try go retrieve using `describe_alarms_for_metric` for `namespace = 'AWS/DynamoDB'` and `metric_name = 'ConsumedWriteCapacityUnits'` I get no results. However when I retrieve all of available alarms using `describe_alarms` I get a list, which then revelas to have 10 such alarms.

**Comment by awood45** [comment]
Can you include a wire trace for this? Try:

```ruby
client = Aws::CloudWatch::Client.new(http_wire_trace: true)
client..describe_alarms_for_metric(namespace: namespace, metric_name: metric_name)
client.describe_alarms
```

I'd like to separate service behavior from any SDK code.

**Comment by dominikgrygiel** [comment]
I've tried to debug more and it seems not to be a library related issue. I've tried to do same operations using AWS CLI with same result. Also I've found a thread with somebody having same issue as I am experiencing https://forums.aws.amazon.com/thread.jspa?messageID=372063 I'll post there. Sorry for confusion.

**Comment by awood45** [comment]
No problem - feel free to leave this open if there's anything else we can answer.
