### ISSUE TITLE
Errno::EHOSTUNREACH: No route to host - connect(2) for "dynamodb.us-east-1.amazonaws.com" port 80

### ISSUE THREAD

**Issue by IBazylchuk** [aws/aws-sdk-ruby#1011]
i get pretty much errors 
```
Errno::EHOSTUNREACH: No route to host - connect(2) for "dynamodb.us-east-1.amazonaws.com" port 80
```
or
``` 
Errno​::ENE​TUNRE​ACH: ​Netwo​rk is​ unre​achab​le - ​conne​ct(2)​ for ​"dyna​modb.​us-ea​st-1.​amazo​naws.​com" ​port ​80
```

trace

```
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879→ initialize
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879→ open
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879→ block in connect
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89→ block in timeout
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99→ call
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99→ timeout
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878→ connect
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1457→ begin_transport
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/patches.rb:25→ new_transport_request
/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1384→ request
rest-client-1.6.9/lib/restclient/net_http_ext.rb:51→ request
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/connection_pool.rb:337→ request
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/handler.rb:61→ block in transmit
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/handler.rb:110→ block in session
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/connection_pool.rb:108→ session_for
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/handler.rb:108→ session
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/handler.rb:60→ transmit
aws-sdk-core-2.2.1/lib/seahorse/client/net_http/handler.rb:34→ call
aws-sdk-core-2.2.1/lib/seahorse/client/plugins/content_length.rb:12→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/dynamodb_crc32_validation.rb:27→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/json/error_handler.rb:8→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/request_signer.rb:85→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/retry_errors.rb:87→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/json/handler.rb:11→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/user_agent.rb:12→ call
aws-sdk-core-2.2.1/lib/seahorse/client/plugins/endpoint.rb:41→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/param_validator.rb:21→ call
aws-sdk-core-2.2.1/lib/seahorse/client/plugins/raise_response_errors.rb:14→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:112→ call
aws-sdk-core-2.2.1/lib/aws-sdk-core/plugins/param_converter.rb:20→ call
aws-sdk-core-2.2.1/lib/seahorse/client/plugins/response_target.rb:21→ call
aws-sdk-core-2.2.1/lib/seahorse/client/request.rb:70→ send_request
aws-sdk-core-2.2.1/lib/seahorse/client/base.rb:207→ block (2 levels) in define_operation_methods
```

Errors gets on different events, get, update item, etc.

**Comment by awood45** [comment]
I'm unable to recreate this, is it possible that you're having transient network issues on your end? Where are you making this call from?

**Comment by IBazylchuk** [comment]
@awood45 for first i thought about network too, but when i ran shell script to ping dynamo host, all was fine. Seems something with sockets, i set today settings to ubuntu, but still get errors

```
net.core.somaxconn = 65535
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_keepalive_time = 1800
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 5
```

**Comment by trevorrowe** [comment]
The endpoint in your message above appears to contain some non-printable UTF-8 characters when I copied and pasted it. 

```
"dyna\U+FFE2\U+FF80\U+FF8Bmodb.\U+FFE2\U+FF80\U+FF8Bus-ea\U+FFE2\U+FF80\U+FF8Bst-1.\U+FFE2\U+FF80\U+FF8Bamazo\U+FFE2\U+FF80\U+FF8Bnaws.\U+FFE2\U+FF"
```
A few things to consider:

* If you have copied/pasted this endpoint, e.g. from a web-page or word doc this could introduce some issues. 
* Also, I notice that it is looking for port 80. The SDK will never use HTTP unless you've explicity configured an HTTP (not HTTPS) endpoint.

To connect to dynamodb you should only configure the region name, you should not need to configure the full endpoint:

```ruby
ddb = Aws::DynamoDB::Client.new(region: 'us-east-1')
ddb.list_tables
=> #<struct Aws::DynamoDB::Types::ListTablesOutput table_names=["aws-sdk", ...], last_evaluated_table_name=nil>
```

Hope this helps. Please feel free to re-open if you continue to run into issues.

**Comment by esilverberg** [comment]
Guys --

I have been plagued by this issue for several months now. I though it was just me, relieved to hear I am not crazy and this is a wider issue (just found this page by Googling EHOSTUNREACH)

You can see my AWS case number here: 1551135111

I appear to have a similar setup -- Ubuntu 14.04 LTS using aws-sdk. Identical stack:

/usr/local/lib/ruby/2.2.0/net/http.rb:879 in initialize
/usr/local/lib/ruby/2.2.0/net/http.rb:879 in open
/usr/local/lib/ruby/2.2.0/net/http.rb:879 in block in connect
/usr/local/lib/ruby/2.2.0/timeout.rb:88 in block in timeout
/usr/local/lib/ruby/2.2.0/timeout.rb:98 in call
/usr/local/lib/ruby/2.2.0/timeout.rb:98 in timeout
/usr/local/lib/ruby/2.2.0/net/http.rb:878 in connect
/usr/local/lib/ruby/2.2.0/net/http.rb:863 in do_start
/usr/local/lib/ruby/2.2.0/net/http.rb:858 in start
/gems/aws-sdk-v1-1.59.0/lib/aws/core/http/connection_pool.rb:327 in start_session
/gems/aws-sdk-v1-1.59.0/lib/aws/core/http/connection_pool.rb:127 in session_for
/gems/aws-sdk-v1-1.59.0/lib/aws/core/http/net_http_handler.rb:55 in handle
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:253 in block in make_sync_request
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:282 in retry_server_errors
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:249 in make_sync_request
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:511 in block (2 levels) in client_request
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:391 in log_client_request
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:477 in block in client_request
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:373 in return_or_raise
/gems/aws-sdk-v1-1.59.0/lib/aws/core/client.rb:476 in client_request


I can repro this issue if you give me about 1 hour, on any instance. It's clearly transient and appears to go away on subsequent calls.

In my case, the exception is: 

Errno::EHOSTUNREACH: No route to host - connect(2) for "dynamodb.us-east-1.amazonaws.com" port 443

(not port 80)

There are no special chars as I am using the aws-sdk. Would love to get to the bottom of this.
