### ISSUE TITLE
Presign url at given time

### ISSUE THREAD

**Issue by hakunin** [aws/aws-sdk-ruby#1013]
Hi, I am generating pre-signed urls so users can have access to S3 imagines for a limited time (say two days).

But, since the urls change (each is generated `now`), they are unique and I am not able to use browser cache.

So I need to be able to say that I want the url signed at a given time. I tried hacking it into the gem, but then the param is rejected by the validator :)

**Comment by awood45** [comment]
That's an interesting feature request. I'll add it to the feature request backlog, and would look at a pull request for this if you want to take a swing at it.

**Comment by awood45** [comment]
I've added the feature request, though as an alternative to consider, you could also save these URLs somewhere for reuse. Depends on what your use case is, exactly.

**Comment by hakunin** [comment]
Saving them would be awkward, since you have to watch them and re-generate them when old.
