### ISSUE TITLE
Elb client doesnt allow adding tags

### ISSUE THREAD

**Issue by AnuragRamdasan** [aws/aws-sdk-ruby#1016]
<img width="1145" alt="screen shot 2015-11-27 at 2 52 58 pm" src="https://cloud.githubusercontent.com/assets/1795026/11437771/5830797a-9516-11e5-92a3-bbe8415dffc8.png">

But when i try the code out, it errors

```ruby
irb(main):001:0> elb = AWS::ELB::Client.new
=> #<AWS::ELB::Client::V20120601>
irb(main):002:0> elb.add_tags
NoMethodError: undefined method `add_tags' for #<AWS::ELB::Client::V20120601>
	from (irb):2
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:4:in `require'
	from /app/bin/rails:4:in `<main>'
irb(main):003:0>
```

I've never tried this method before so I am not sure if it has been deprecated or just a regression.

**Comment by awood45** [comment]
What version of the SDK are you using? Most likely, you're on an older version of the SDK that doesn't have that part of the client model.

**Comment by AnuragRamdasan** [comment]
@awood45 I am actually using an older version but the docs state that this method is available there.
The client version in the above code snippet and in the aws docs is `V20120601` and the docs say that `add_tags` is available.
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client/V20120601.html

**Comment by awood45** [comment]
Which version, exactly, of the SDK are you using? If you run `gem list`, what does it show for the SDK? `#add-tags` support was added in version 1.51.0. You wouldn't see an API version bump for some services unless there was a breaking change, such as new required parameters.

**Comment by awood45** [comment]
Relevant Change: https://github.com/aws/aws-sdk-ruby/commit/40544cb7c826dafdd684634b44769edbfa86e069

**Comment by AnuragRamdasan** [comment]
I ran `gem list | grep aws`

and got this response
```
aws-sdk (2.0.47, 2.0.43, 1.64.0, 1.46.0, 1.39.0)
aws-sdk-core (2.1.35, 2.0.47, 2.0.43)
aws-sdk-resources (2.1.35, 2.0.47, 2.0.43)
aws-sdk-v1 (1.66.0, 1.64.0)
```

Looking at it, with 1.66 and 1.64, it should've had add_tags.

**Comment by awood45** [comment]
I can't recreate this on my own version of 1.64.0, which has the add_tags function. I did notice in your stack trace that you're running this in a Rails app - what is in your `Gemfile.lock` for that project? Are you possibly locked on an old version?

**Comment by AnuragRamdasan** [comment]
My gemfile.lock had one version locked on 1.46. I upgraded it to 1.64 but seems like the issue still persists.

Let me poke around a bit more and then get back to you.

**Comment by awood45** [comment]
I'll leave this open while you poke around, but I'm pretty confident that this is a problem with you gem bundling for that project.

Try, for example, running the `aws-rb` command, and then run:
```ruby
elb.client.add_tags
```

This should give you a parameter validation error, but will show that the API is present.

**Comment by trevorrowe** [comment]
I've verified the operation is present in the latest version of the SDK as well. It appears you have an issue with your application loading the older version of the gem. I would double check what version is in your Gemfile.lock.
