### ISSUE TITLE
NoMethodError: undefined method `call' for Aws::Log::Formatter

### ISSUE THREAD

**Issue by thoiberg** [aws/aws-sdk-ruby#1017]
Hi, 

I'm currently getting a `NoMethodError: undefined method call for Aws::LogFormatter` when I'm using a logger with a `Aws::Log::Formatter` formatter configured, I'm seeing this error currently using the CloudWatch#list_metrics method but with some testing I've found this has happened with some other endpoints such as listing EC2 instances. I am specifying a custom pattern but when I replace that with the `:default` pattern I get the same issue.

Current code:

      def initialise_aws_logger
        log_path = File.join(File.expand_path('../../logs', __FILE__), 'aws.log')
        unless File.exists? File.dirname(log_path)
          Dir.mkdir(File.dirname(log_path))
        end
        pattern = '[http_request_type=":http_request_method" http_response_status=":http_response_status_code"] aws_service=":client_class" ' \
                  'aws_operation=":operation" retry_count=":retries" operation_duration=":time"'
        aws_formatter = Aws::Log::Formatter.new(pattern)

        logger = Logger.new(log_path, 10, 10485760)
        logger.formatter = aws_formatter

        logger
      end

Current development environment:
Windows 7
Ruby 2.2.2p95
aws-sdk v2.2.3

**Comment by awood45** [comment]
Thanks for the report, I'll try and reproduce. What would also help is if you can provide a stack trace of the error you're seeing.

**Comment by thoiberg** [comment]
@awood45 Stack track is as follows:

    NoMethodError: undefined method `call' for #<Aws::Log::Formatter:0x00000005caa1c0>
    from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.2.3/lib/aws-sdk-core/log/formatter.rb:108:in `method_missing'

**Comment by trevorrowe** [comment]
Looking at your code example, I see what the issue is. I see how this would be confusing, but the `Aws::Log::Formatter` is not intended to be given as the formatter for the Ruby standard-lib logger. It is to be given to an client so that it knows how to format the message that it will send to the logger.

For example:

```ruby
s3 = Aws::S3::Client.new({
  logger: Logger.new($stdout),
  log_formatter:  Aws::Log::Formatter.new('[aws_operation=":operation"]')
})
s3.list_buckets
```

This will produce messages like:

```
I, [2015-12-09T11:37:11.897427 #99733]  INFO -- : [aws_operation="list_buckets"]
```

Notice all of the prefixed information on my log line that wasn't part of my pattern. That was being appended by the std-lib logger. I can change this with the `#logger`:

```ruby
logger = Logger.new($stdout)
logger.formatter =  proc do |severity, datetime, progname, msg|
  "LEVEL: #{severity} TIME: #{datetime} MSG: #{msg}\n"
end

s3 = Aws::S3::Client.new({
  logger: logger,
  log_formatter:  Aws::Log::Formatter.new('[aws_operation=":operation"]')
})
s3.list_buckets
```

This generates a log message like:

```
LEVEL: INFO TIME: 2015-12-09 11:41:48 -0800 MSG: [aws_operation="list_buckets"]
```

Hope this helps!
