### ISSUE TITLE
Listing top level objects in bucket

### ISSUE THREAD

**Issue by atul-shimpi** [aws/aws-sdk-ruby#1022]
Hello,
I want to list all top level objects in each bucket. Basically i want to implement file system like interface for s3 buckets and objects to exploring through them.

Below is my code
s3 = Aws::S3::Resource.new
@records = s3.bucket('src-ruby').objects(delimiter: '/')

src-ruby contains rest_pos.zip and blog directory.
However above code returns only rest_pos.zip.

I have read somewhere that there's something called as common prefix array. Which will contain
group keys.
However, i cant find that in the objectsummary.

**Comment by awood45** [comment]
The resource model doesn't have a way to do this within its current design.

You can use the low level API `Aws::S3::Client#list_objects`, which returns both the common prefix array and the first level objects in the response.

**Comment by atul-shimpi** [comment]
Thanks for quick reply.

**Comment by awood45** [comment]
For reference: [`Aws::S3::Client#list_objects`](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_objects-instance_method).
