### ISSUE TITLE
Aws::S3::Errors::MethodNotAllowed when calling put_bucket_logging on the client

### ISSUE THREAD

**Issue by bosskovic** [aws/aws-sdk-ruby#1024]
After I have updated from **2.0.39** to the most recent version (**2.2.5**), when I call `put_bucket_logging` on an instance of the `Aws::S3::Client` I get the `Aws::S3::Errors::MethodNotAllowed` exception.

This used to work with no problems with the earlier version of the gem.

I checked the [documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#put_bucket_logging-instance_method) and this seems to have remained the same.

What do I need to do in order to update to the new version?

**Comment by awood45** [comment]
I can't recreate this off-hand. Can you give me a repro example?

**Comment by bosskovic** [comment]
I noticed one thing while I was extracting the relevant code into a blank rails app, the class of the responses is now `Seahorse::Client::Response` instead of `Aws::PageableResponse`, and in the code I am checking the class of response in order to determine the success of the request.

Can you please tell me if the response class has changed for all responses? In other words, can I just substitute the old class with a new wherever I use it (it's not just logging, but also tagging, managing iam and cloudfront distros, etc)?

Here's a snippet how I am doing it:

```ruby
response = client.some_request({ ... })
success = response.is_a?(Aws::PageableResponse)
# log/report depending on success
```

**Comment by bosskovic** [comment]
ok, after some playing around, it seems that it would be better to do the check like this:
```
success = response.error.nil?
```
and this works for both versions. I will do some more testing and close the issue if it all turns ok.

**Comment by bosskovic** [comment]
It's all fine now. Thank you for your assistance :-)

**Comment by trevorrowe** [comment]
@bosskovic You do not need to check for an error code. The default behavior of the SDK is to raise an error if the request is not successful. Unless you have explicitly disable the raising response errors behavior, then you can simply call the `#put_bucket_logging` method and continue on, rescuing an error for failure cases.
