### ISSUE TITLE
iam_instance_profile fails to satisfy regular expression pattern: [\w+=,.@-]+

### ISSUE THREAD

**Issue by ErikDahlinghaus** [aws/aws-sdk-ruby#1025]
I am using chef-provisioning-aws to create an instance with an iam_instance_profile. I am getting the following error:

Aws::IAM::Errors::ValidationError: 1 validation error detected: Value '{:arn=>"arn:aws:iam::12194483xxxx:instance-profile/my-instance"}' at 'instanceProfileName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]+

and I get the same error when using name:

Aws::IAM::Errors::ValidationError: 1 validation error detected: Value '{:name=>"my-instance"}' at 'instanceProfileName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]+

No matter what I put, I get a failure to pass the expression pattern.

I've already inquired with the chef-provisioning-aws team, and they tell me this is probably an error with the aws-sdk, and my inclination says the same. Please let me know if you need more info, or if you know what is going on here.

**Comment by awood45** [comment]
When I try to recreate this, the request appears to go over the wire, rather than this being a client side validation. I'm looking in to this more.

**Comment by ErikDahlinghaus** [comment]
Yes, I did some grepping of this repo and didn't find that regex pattern anywhere, so I kind of thought that it was the AWS API returning this. But I couldn't be sure. Thanks.

**Comment by awood45** [comment]
I can tell you that this does work when I pass just the name, rather than a full ARN. For example:
```ruby
client.get_instance_profile(instance_profile_name:"aws-opsworks-ec2-role")
```
...works, while this doesn't:
```ruby
client.get_instance_profile(instance_profile_name: "arn:aws:iam::123456789000:instance-profile/aws-opsworks-ec2-role")
```

What operation are you calling? I can attempt to repro there and see if there is a doc issue.

**Comment by ErikDahlinghaus** [comment]
http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#create_instances-instance_method

Passing an options hash that includes `{iam_instance_profile: {name: "my-instance-profile"}}` or `{iam_instance_profile: {arn: "arn:aws:iam::12194483xxxx:instance-profile/my-instance-profile"}}`

Neither one works.

**Comment by awood45** [comment]
Next thing would be to provide a stack trace, if you can.
```ruby
ec2 = Aws::EC2::Resource.new(http_wire_trace: true)
ec2.create_instances(opts)
```
Let's see what this generates. I'm mainly interested in confirming that we craft the client request correctly with your particular options, and then we can try to recreate at the client level.

**Comment by ErikDahlinghaus** [comment]
Alright I'll craft up an example and provide that information here in a bit.

**Comment by awood45** [comment]
Feel free to redact anything you need to, the structure is more important than the exact content (probably).

**Comment by ErikDahlinghaus** [comment]
Well, I've written a test and it seems to work. It now seems to be a problem with chef-provisioning-aws, and I've taken it back up with them. For posterity, here is my test.

```
require 'aws-sdk'

client = Aws::EC2::Client.new(region: 'us-east-1', http_wire_trace: true)

resp = client.run_instances({
  # dry_run: true,
  image_id: "ami-61bbf104", # required
  min_count: 1, # required
  max_count: 1, # required
  key_name: "my_keypair",
  security_group_ids: ["sg-21d3xxxx"],
  instance_type: "m4.large",
  subnet_id: "subnet-08c8xxxx",
  iam_instance_profile: {
    # arn: "arn:aws:iam::12194483xxxx:instance-profile/my-instance-profile",
    name: "my-instance-profile",
  },
})
```

Output is happy, creates instance with the proper instance profile. Thanks for your help.

**Comment by awood45** [comment]
No problem - can you please link to the issue you've filed with chef-provisioning-aws? I'd be interested to see where the confusion might be to see if there is something we can do better. Thanks!

**Comment by ErikDahlinghaus** [comment]
https://github.com/chef/chef-provisioning-aws/issues/413

**Comment by awood45** [comment]
Thanks for the link - if down the road it looks like there may be an SDK issue here, or even maybe a service issue, feel free to reach out again.

**Comment by ErikDahlinghaus** [comment]
Will do. Thanks again for your help.
