### ISSUE TITLE
"Maximum number of simultaneous requests reached" during an RDS waiter

### ISSUE THREAD

**Issue by djcp** [aws/aws-sdk-ruby#1029]
This is super weird - over the last couple days, I've seen:

```
Aws::Waiters::Errors::UnexpectedError: stopped waiting due to an unexpected error: Maximum number of simultaneous requests reached. Please consider adding a retry mechanism or increasing the queue size.
```

pop up a couple times, but only when I'm running a waiter related to an RDS database. I'm pretty sure it's been "db_instance_deleted" but it might've been "db_instance_available" as well.

Is this just the fickle AWS gods striking me down or is there something else I should look at? It's odd that it's only occurred during RDS wait operations.

**Comment by djcp** [comment]
yep, happens during ":db_instance_available" too.

**Comment by awood45** [comment]
Any update on this? Is this still happening for you?

**Comment by djcp** [comment]
I think you're right that this was the service. I've not see it occur in quite a while. Thanks for checking in, I'll close.

**Comment by fuzzyami** [comment]
just FYI: I got the same error message from AWS last night (on my Sensu client). sorted itself out in a minute, but still weird.

**Comment by djcp** [comment]
Yeah, we saw it last night too for RDS.
