### ISSUE TITLE
SDK V2 does not respect ENV['no_proxy']

### ISSUE THREAD

**Issue by tyler-ball** [aws/aws-sdk-ruby#1031]
My setup is this:  I _do not_ have a proxy server running locally.  I setup `ENV['http_proxy'] = 'http://localhost:3128'`, `ENV['https_proxy']  = 'http://localhost:3128'` and `ENV['no_proxy'] = '.amazonaws.com'`.  My expectation is that the Ruby process would send all HTTP/S requests to the proxy _except_ ones to *.amazonaws.com.

Instead, I get the error `Class: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 3128` trying to [connect](https://github.com/aws/aws-sdk-ruby/blob/282f9719cf7c6389bee935ab17360e6dd29956d3/aws-sdk-core/lib/seahorse/client/plugins/endpoint.rb#L34) to `ec2.us-west-2.amazonaws.com`.

If I start a local Squid proxy (setup to forward all requests) on port 3128, then I do not see this error.  Ruby can successfully communicate with AWS through the proxy.

In our testing we have discovered that `Net::HTTP.new` will respect `ENV['http_proxy']`, `ENV['https_proxy']` _and_ `ENV['no_proxy']` if you don't try [passing](https://github.com/aws/aws-sdk-ruby/blob/282f9719cf7c6389bee935ab17360e6dd29956d3/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L274) proxy config as arguments.  We observed this behavior even though the [documentation](http://ruby-doc.org/stdlib-2.2.3/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new) only mentions `http_proxy`.

**Comment by awood45** [comment]
Thanks for the report, I see what you're getting at.

I'm going to work on a reproducing case so that I can test a proposed fix.

**Comment by trevorrowe** [comment]
I did some digging on this today. It appears that the SDK is doing the correct thing. Notice that it compacts the args list before splatting them into the `HTTP.new` call. This causes Net::HTTP to default p_addr to `:ENV`.

I was able to change your example to working by removing the leading dot from the `no_proxy` environment variable:

```
ENV['no_proxy'] = 'amazonaws.com'
```

Hope this helps.

**Comment by tyler-ball** [comment]
Thanks for the research @trevorrowe - I'll update the tests on our side
