### ISSUE TITLE
Caught Seahorse::Client::NetworkingError: execution expired

### ISSUE THREAD

**Issue by spark13** [aws/aws-sdk-ruby#1034]
Hi everyone, 

I'm trying to download files from s3.

After downloading a couple of files, it threw following exception:
"Caught Seahorse::Client::NetworkingError: execution expired”

Following is the code:

      Aws.use_bundled_cert! // I ran into SSL issue and found this solution on stackoverflow
      client = Aws::S3::Client.new(
          :region => us-west-2,
          :access_key_id => ACCESS_KEY,
          :secret_access_key => SECRET_KEY
      )

      Aws.config[:ssl_verify_peer] = false // also the solution for SSL issue 

      resource = Aws::S3::Resource.new(client:client)

      bucket = resource.bucket(bucketName)
      bucket.objects.each do |obj|
          resp = client.get_object(response_target:target, bucket:bucketName, key:obj.key)
       end

What causes above exception? Does s3 connection expire after some time? What are some ways to get around this? Implement retry and try to re-establish the connection if this happens?

Thank you for your help in advance!

**Comment by awood45** [comment]
Are you trying to download a very large object? I am not sure about all the timeouts your connection could be exposed to, but you may want to take an alternative approach if you're downloading a very large object.

**Comment by awood45** [comment]
This has been inactive for three weeks, so I'm going to close this.

If you'd like to discuss, happy to talk about possible causes of this and ways to work around them. We also have an open feature request to support multipart downloads.

**Comment by pauldraper** [comment]
I had this error when downloading from S3.

```/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Seahorse::Client::NetworkingError)
from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
from /usr/lib/ruby/2.3.0/net/http.rb:858:in `start'
from /usr/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:119:in `session'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/net_http/handler.rb:45:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/content_length.rb:12:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_request_signer.rb:88:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_request_signer.rb:23:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_host_id.rb:14:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_request_signer.rb:65:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_redirects.rb:15:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:120:in `retry_request'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:103:in `retry_if_possible'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/retry_errors.rb:91:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_dualstack.rb:32:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_accelerate.rb:49:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_md5s.rb:31:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_expect_100_continue.rb:21:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb:12:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_bucket_dns.rb:31:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/rest/handler.rb:7:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/s3_accelerate.rb:34:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/plugins/response_target.rb:21:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/request.rb:70:in `send_request'
from /var/lib/gems/2.3.0/gems/aws-sdk-core-2.10.21/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
from /var/lib/gems/2.3.0/gems/aws-sdk-resources-2.10.21/lib/aws-sdk-resources/request.rb:24:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-resources-2.10.21/lib/aws-sdk-resources/operations.rb:41:in `call'
from /var/lib/gems/2.3.0/gems/aws-sdk-resources-2.10.21/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'```

> all the timeouts your connection could be exposed to

If you don't know, then I certainly don't know :)
