### ISSUE TITLE
APIGateway::Client#put_integration does not support "LAMBDA" type.

### ISSUE THREAD

**Issue by jsgarvin** [aws/aws-sdk-ruby#1036]
It's currently not possible to create lambda integration for a resource method via the ruby sdk.

Raises the error, `1 validation error detected: Value 'LAMBDA' at 'putIntegrationInput.type' failed to satisfy constraint: Member must satisfy enum value set: [HTTP, MOCK, AWS] (Aws::APIGateway::Errors::ValidationException)`

which appears to be tied to https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/apigateway/2015-07-09/api-2.json#L3099-L3106

I believe `#put_integration` would also need to accept `:lambda_region` and `:lambda_function` options if `'LAMBDA'` was passed as a type.

Same probably goes for `#update_integration` all around.

**Comment by awood45** [comment]
Thanks for the report, I'll take a look at the mismatch.

**Comment by awood45** [comment]
It looks like this error is coming from the service, based on a test with `http_wire_trace: true` on the client. Investigating.

**Comment by awood45** [comment]
Sorry, I think I see the confusion now. I believe that the `AWS` enum value represents AWS Lambda, based on reading around the documentation. I'll pass on the feedback that this isn't very clear.

Let me know if this fixes the issue for you.

**Comment by jsgarvin** [comment]
Thanks Alex,

However, I'm not seeing in the documentation how to pass in the region and lambda function name, both required fields if I build a lambda integration through the browser UI, so it seems I should need them here, too.

If I call...

    api_client.put_integration(
      rest_api_id: rest_api.id,
      resource_id: resource.id,
      http_method: 'GET',
      type: 'MOCK'
    )

that works to create a MOCK integration.  My (probably wrong) interpretation of your response above is to change `type: 'MOCK'` to `type: 'AWS'`) , however, just doing that results in a `Enumeration value for HttpMethod must be non-empty (Aws::APIGateway::Errors::BadRequestException)` error, but it looks like I am sending `http_method: 'GET'`, so....  I must be overlooking something.

**Comment by awood45** [comment]
Honestly, I don't see that documentation either. I'll try and get an answer from the service team about how to do what you're trying to do.

**Comment by awood45** [comment]
I'd also encourage you to contact AWS Support about that.

**Comment by abubics** [comment]
Hopefully not too stale to help ;)

I've gotten Lambda integration working today with the `AWS` type, using this forum post for hints: [Does aws-cli support creating methods calling Lambda?](https://forums.aws.amazon.com/thread.jspa?messageID=685551)

Sample:
```ruby
def lambda_arn_uri
  service = 'lambda'
  acc = '12xxxxxxxxxx'
  function_name = 'awesome-lambda-function'
  lambda_arn = "arn:aws:lambda:#{REGION}:#{acc}:function:#{function_name}" # can copy this from Lambda console
  path_or_action = "path/2015-03-31/functions/#{lambda_arn}"
  service_api = 'invocations'
  "arn:aws:apigateway:#{REGION}:#{service}:#{path_or_action}/#{service_api}"
end

method = 'GET'
api_gateway.put_integration(
  rest_api_id: rest_api.id,
  resource_id: resource.id,
  http_method: method,
  type: 'AWS',
  integration_http_method: method,
  uri: lambda_arn_uri
)
```

Needs templates, etc, but should get you started. It'd be cool if the API supported it in a more friendly way, but that isn't a Ruby SDK issue.

**Comment by awood45** [comment]
Thanks for sharing! We are looking at developer guides, so sharing this is definitely useful!

**Comment by natemacinnes** [comment]
This is still very unclear in the guides in 2018.
