### ISSUE TITLE
Aws::S3::Encryption: AES/GCM/NoPadding encryption not supported

### ISSUE THREAD

**Issue by DanielRedOak** [aws/aws-sdk-ruby#1037]
AWS SES  + KMS encryption seems to use 'AES/GCM/NoPadding' which does not appear to be supported when using Aws::S3::Encryption::Client as it throws Aws::S3::Encryption::Errors::DecryptionError: unsupported content encrypting key (cek) format: "AES/GCM/NoPadding"

**Comment by awood45** [comment]
Thanks for the report - just to help me reproduce, can you give me some code snippets of how you're attempting to decrypt?

**Comment by DanielRedOak** [comment]
Absolutely.  Using SES to plop messages into S3 using KMS with the default aws/ses encryption keys.  Here is a little snippet for decrypting and putting to disk.  Pretty simple. kms_key_id in this case is 'aws/ses'

```
    def decrypt(kms_key_id, object_key, bucket, target)
      s3encrypt = Aws::S3::Encryption::Client.new(kms_key_id: kms_key_id)
      s3encrypt.get_object(bucket:bucket, key:object_key, response_target: target)
    end
```

**Comment by DanielRedOak** [comment]
I think we can add support pretty easily by modifying the kms_cipher_provider to include a case check for supported methods and setting GCM as the cipher when 'AES/GCM/NoPadding' is detected

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/encryption/kms_cipher_provider.rb#L16
https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/encryption/kms_cipher_provider.rb#L37

**Comment by awood45** [comment]
Thanks for the info - I'm working on a reproduction now so that I can properly test a fix.

**Comment by awood45** [comment]
Will revisit this after the holidays, the full fix seems to be somewhat involved. Thanks again for the report!

If you end up patching this in the meantime and want to start a pull request, happy to help on that route as well.

**Comment by DanielRedOak** [comment]
Yea, I headed down the rabbit hole and ended up with a rather generic Cipher error after all the monkey patching I was working on.  Might re-visit, but atm I have higher priority projects to complete.  Thanks!

**Comment by awood45** [comment]
100% understood, of course.

**Comment by DanielRedOak** [comment]
Worked on it a bit more and from what I can tell things should be working, but I am still hitting that cipher error so something is wrong with the data, key, or iv used.  I wrote up a quick decrypt test to see if I could do the work manually, see below.  I'm thinking that the key is incorrect, but it's hard to say.

```ruby
awskey = decode64(<stolen from the kms_client decrypt in the sdk>)
awsiv = decode64(<from x-amz-iv>)
file = File.open(<downloaded file from s3>, "rb")
awsdata = file.read
decipher = OpenSSL::Cipher.new('aes-256-gcm')
decipher.decrypt
decipher.key = awskey
decipher.iv = awsiv

plain = decipher.update(awsdata) + decipher.final
```

**Comment by awood45** [comment]
I'm able to reproduce this, so your key is fine. I'm working on a fix, and I'll be able to confirm against my own setup once I can get that working as well.

**Comment by DanielRedOak** [comment]
Sounds good.  I do see that things are being decrypted, but there is either padding at the end of the decryption (even with AES/GCM/NoPadding?) or it contains further data like an auth_tag or something.  Using the header 'x-amz-meta-x-amz-unencrypted-content-length' to select the original content works, but .finalize is still broken.  Just thought I'd share my findings.

**Comment by DanielRedOak** [comment]
Yep, was the tag hanging out at the end, I just needed to read up a bit more on GCM.  I now have a working implementation and will be able to submit a clean PR yet today.

**Comment by DanielRedOak** [comment]
PR https://github.com/aws/aws-sdk-ruby/pull/1043, needs further tests

**Comment by trevorrowe** [comment]
Support for AES/GCM/NoPadding should be in the public SDK now.
