### ISSUE TITLE
EC2::Instance resource missing availability_zone

### ISSUE THREAD

**Issue by jqr** [aws/aws-sdk-ruby#1040]
I would think the `EC2::Instance` resource would include `availability_zone`, but it doesn't seem to. My current fix is to look at the first volume's `availability_zone` but its  a hack and requires another API call.

Did I miss something, is this available?

**Comment by awood45** [comment]
It is there, under placement.

For example, this is what I see:
```ruby
ec2 = Aws::EC2::Resource.new
ec2.instances.first.placement.availability_zone #=> "us-east-1c"
```
So, if you have an instance resource, run this to get the availability zone:
```ruby
instance.placement.availability_zone
```
