### ISSUE TITLE
SDK doesn't use AWS_REGION environment variable

### ISSUE THREAD

**Issue by marr** [aws/aws-sdk-ruby#1042]
I put together a spec here to test if the sdk supports the environment variables like the docs mention: https://github.com/marr/aws-test/blob/master/spec/models/listing_spec.rb

It seems that the configuration section here needs updating: http://docs.aws.amazon.com/sdkforruby/api/index.html#Configuration

Running the spec with `AWS_REGION=us-west-2 rake spec` for example, fails with:
```

  1) Listing AWS loads env
     Failure/Error: expect(Aws.config[:region]).to eql(ENV['AWS_REGION'])

       expected: "us-west-2"
            got: nil

       (compared using eql?)
     # ./spec/models/listing_spec.rb:6:in `block (3 levels) in <top (required)>
```

**Comment by awood45** [comment]
I think there is some clarity that can be added to the documentation here.

That hash allows you to *set* the region globally, but the region you pass as an ENV variable is bound until a client is created. For example, I see this in my local environment:
```ruby
ENV['AWS_REGION'] # => "us-east-1"
Aws.config[:region] # => nil
Aws::S3::Client.new.config.region # => "us-east-1"
```
I can see where, if you expect the global config to be write *and read*, that this could be confusing.

**Comment by trevorrowe** [comment]
I've added a note to the README to clarify the use `Aws.config`.
