### ISSUE TITLE
Aws::SharedCredentials doesn't work seamlessly with config files as configured for the official AWS CLI

### ISSUE THREAD

**Issue by jimcroft** [aws/aws-sdk-ruby#1045]
I'm trying to use Aws::SharedCredentials to run a Ruby script using the credentials files as configured for the CLI tools. Shared credentials aren't defined as part of an AWS API so a "spec" doesn't really exist except as implemented in the various SDKs and the CLI itself.

There are a couple of problems I'm having with this at the moment:

The CLI supports splitting configurations across the ~/.aws/config and ~/.aws/credentials files. Roles being defined in the ~/.aws/config file (http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html) rather than ~/.aws/credentials. The Ruby SDK doesn't handle this.

Similarly, when using roles and/or MFA the Ruby SDK doesn't lookup the STS creds cached in ~/.aws/cli/cache/ by the CLI.

Should the Ruby SDK integrate more fully with the CLI ~/.aws/config and ~/.aws/cli/cache files? 

I kinda take the CLI as a defacto spec for shared credentials so think this should be addressed. I'm happy to work on this but would like a steer as to whether a PR that addresses these points would be merged (assuming it passed review, feedback, etc).

**Comment by awood45** [comment]
We're discussing this on our end. Some of these configuration files were meant to be CLI-only, but we are looking to what we can and should support above and beyond just shared credentials (which was the original intention).

**Comment by mfischer-zd** [comment]
+1 - having the APIs and CLI behave identically with respect to default configuration would reduce a lot of confusion and surprise.

**Comment by awood45** [comment]
Additional configuration supported in #1178

**Comment by awood45** [comment]
#1178 has been merged, this will be supported with the next release, which will be version `2.4.0`.
