### ISSUE TITLE
make it easy to add custom waiters

### ISSUE THREAD

**Issue by danp** [aws/aws-sdk-ruby#1047]
Until #1039 is merged I'm implementing the waiter myself, like this:

``` ruby
poller = Aws::Waiters::Poller.new(
  "operation" => "DescribeNatGateways",
  "acceptors" => [
    { "expected" => "available", "matcher" => "pathAll", "state" => "success", "argument" => "NatGateways[].State" },
    { "expected" => "InvalidNatGatewayIDNotFound", "matcher" => "error", "state" => "retry" },
    { "expected" => "failed", "matcher" => "pathAny", "state" => "failure", "argument" => "NatGateways[].State" },
    { "expected" => "deleting", "matcher" => "pathAny", "state" => "failure", "argument" => "NatGateways[].State" },
    { "expected" => "deleted", "matcher" => "pathAny", "state" => "failure", "argument" => "NatGateways[].State" },
  ],
)
waiter = Aws::Waiters::Waiter.new(poller: poller, max_attempts: 40, delay: 15)
waiter.wait(client: ec2, params: { nat_gateway_ids: [nat_gateway_id] })
```

As best I can tell there is no public way to inject custom waiters. It would be nice if I could add to the default set on a per-client or per-service basis, so I could use something like `ec2.wait_until(:nat_gateway_available, ...)` regardless of where the waiter is defined.

**Comment by basex** [comment]
is there a way to have a waiter for a Aws::Route53::Client instance create_hosted_zone ?

The waiter_names list is empty on the documentation: http://docs.aws.amazon.com/sdkforruby/api/Aws/Route53/Client.html#waiter_names-instance_method

**Comment by awood45** [comment]
Adding to feature request backlog. Will also take a PR for this if you want to take a crack at it.

**Comment by awood45** [comment]
@basex A lack of waiters just means that none have been created yet, and that there is no waiters JSON file. We can still take PRs, for example, to add Route53 waiters. You'd just need to create the file in the pattern of other waiter files.

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.

**Comment by mullermp** [comment]
We don't have plans to implement this. We add all waiters (if any are missing) upon request.
