### ISSUE TITLE
Documentation not Up-To-Date on RubyDoc and Dash

### ISSUE THREAD

**Issue by vdaubry** [aws/aws-sdk-ruby#1061]
Hi,

Documentation for the Ruby AWS SDK is incomplete on RubyDoc and tools such as [Dash](https://kapeli.com/dash)

Documentation for Aws::S3::Object on official Aws docs :
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html

Documentation for Aws::S3::Object on ruby doc  :
http://www.rubydoc.info/github/aws/aws-sdk-core-ruby/Aws/S3/Object

The official doc is great but cannot be used offline (as far as i know)
It would great to be able to import the AWS SDK documentation in a tool such as Dash and browse it offline.

Would it be possible to distribute the latest doc with the gem ?

**Comment by Kapeli** [comment]
Note: RubyDoc and Dash generate the docs by unpacking the gem and using [yard](http://yardoc.org/) over the source. You don't need to include the actual HTML docs with the gem, but ensure that running yard over the unpacked gem produces the same docs.

**Comment by awood45** [comment]
On the first point, you can generate the docs from source by checking out the repo and running:
```
bundle install
rake docs
```
That will produce the same documentation, offline.

As for rubydoc.info, unfortunately that process doesn't support plugins, and so they will be unable to generate matching documentation.

**Comment by awood45** [comment]
Going to close this - feel free to let me know if you have any other questions about this.
