### ISSUE TITLE
NoMethodError: undefined method 'exists?' for Aws::S3::Object

### ISSUE THREAD

**Issue by radhikamalik** [aws/aws-sdk-ruby#1066]
I'm having some trouble accessing the `#exists?` method for an `Aws::S3::Object`. I referred to the docs at http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#exists%3F-instance_method and am accessing the method as follows:

```
  Aws::S3::Object.new(key: 'k', bucket_name: 'my_bucket').exists?
``` 

But I get an error:
```
  NoMethodError: undefined method `exists?' for #<Aws::S3::Object bucket_name="my_bucket", key="k">
```

I am able to read from and write to the object without any trouble. Is there an alternate way in which I should be accessing the `exists?` method?

**Comment by radhikamalik** [comment]
Actually turns out I was using an older release before the method was added!

**Comment by awood45** [comment]
Thanks for checking back on that! Glad things worked themselves out quickly.
