### ISSUE TITLE
Does upload_file perform data integrity checks?

### ISSUE THREAD

**Issue by bpourriahi** [aws/aws-sdk-ruby#1074]
It's not stated in the docs if upload_file does that.

**Comment by bpourriahi** [comment]
I see in the code that it does inject Content-Md5 into the body.

Would be good to have this in the docs.

**Comment by awood45** [comment]
Good callout!

**Comment by awood45** [comment]
I'm not going to add this to upload_file, reason being that the functionality comes from an S3 plugin provided in core. I am looking at upgrading the S3 main docs to explain that this occurs across the service, for any request that includes a body.
