### ISSUE TITLE
Indefinite wait while uploading_archive and file read pointer is at eof

### ISSUE THREAD

**Issue by dhunnapotha** [aws/aws-sdk-ruby#1076]
**How to reproduce**

```
glacier  = ::Aws::Glacier::Client.new :region => 'us-east-1'
fp = File.open '/tmp/archive.txt'
fp.read 1000

glacier.upload_archive ({
        vault_name: 'test',
        account_id: '-',
        archive_description: 'sample description',
        body: fp
      })
```

/tmp/archive.txt is a small text file with 1 word in it
fp.read 1000 puts the read pointer of fp at the end of file

The upload_archive hangs indefinitely.

Please note that this might not be a valid usecase, but in my case, this happened, as fp has been moved to eof by some other library, which was not entirely obvious

**Comment by awood45** [comment]
Thanks for the report, will take a look at the pull request.

**Comment by awood45** [comment]
Working on a fix within the Glacier Checksum plugin that rewinds the body before attempting calculation. That would prevent this code path from being triggered.

**Comment by awood45** [comment]
Thanks for the report!
