### ISSUE TITLE
uninitialized constant Overclock::Aws::RDS::AWS

### ISSUE THREAD

**Issue by abhimj** [aws/aws-sdk-ruby#1078]
Using version 2.2.13 of aws-sdk.

But the code was written for version 1 as follows -
AWS::RDS.new(access_key_id: key, secret_access_key: secret, region: region)

So used require 'aws-sdk-v1' as mentioned on 
http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2
https://github.com/aws/aws-sdk-ruby/blob/master/MIGRATING.md
So the new code is 
def rds(key = new_resource.aws_access_key, secret = new_resource.aws_secret_access_key)
        begin 
          require 'aws-sdk-v1'
        rescue LoadError
          Chef::Log.error("Missing gem 'aws-sdk'. Use the default aws-rds recipe to install it first.")
        end
        @rds ||= AWS::RDS.new(access_key_id: key, secret_access_key: secret, region: region)
      end

Inspite of that receiving the same error.

 ============================================================================ ====
    Error executing action `create` on resource 'aws_rds[myappdb]'
    ============================================================================ ====
 
    NameError
    ---------
    uninitialized constant Overclock::Aws::RDS::AWS
 
Please suggest if I should be doing it in a different way.

**Comment by awood45** [comment]
This sounds like an issue with the library depending the SDK.

There is possibly another way you can arrange your gems, since it appears (without being able to see the code) that it assumes 'aws-sdk' means V1.

You can lock aws-sdk to V1 in your gemfile, and then depend on 'aws-sdk-resources'.
```ruby
gem 'aws-sdk', '~> 1.0'
gem 'aws-sdk-resources'
```

**Comment by awood45** [comment]
No response in two weeks, closing. If the gemfile tweaks didn't fix the issue, and you have more information, please feel free to reopen or to open a new issue.

**Comment by simarpreetgujral** [comment]
Hi @awood45 ,

I am facing the similar issue. I am trying to configure aws-rds instance using Chef cookbook. When I wrote
 gem 'aws-sdk' 
in the Gemfile , I am facing error  " had an error: NameError: uninitialized constant Overclock::Aws::RDS::AWS"

When I wrote 
gem 'aws-sdk', '~> 1.0'
gem 'aws-sdk-resources'
in the Gemfile, it gave error related to gem json.

Can you please help.
