### ISSUE TITLE
SDK should not attempt to paginate responses that do not respond to #each or #each_page

### ISSUE THREAD

**Issue by iamrohitbanga** [aws/aws-sdk-ruby#1079]
For unit testing, I am trying to stub s3 client methods with responses generated using #stub_data. Then I try to use the S3 Resource APIs and expect the correct responses. 

Example:
`s3 = Aws::S3::Client.new :region => 'us-east-1', :stub_data => true`
 s3.stubs(:list_objects).returns(s3.stub_data(:list_objects, contents: [{:key=> 'obj-1'}]))`.

If I use Aws::S3::Resource.new(:client => s3).bucket('my-bucket').objects.to_a, I get the following error: NoMethodError: undefined method `each' for #<Aws::S3::Types::ListObjectsOutput:0x1efdadd9>.

Based on gitter chat with @trevorrowe, the best fix is to patch the SDK to not attempt to paginate responses that do not respond to #each_page or #each.

**Comment by awood45** [comment]
Thanks for raising this to an issue, will discuss with Trevor.

**Comment by trevorrowe** [comment]
Thanks for reporting the issue. This has now been fixed and should be part of our next release.
