### ISSUE TITLE
Elastic Beanstalk response does not include deployed_to information

### ISSUE THREAD

**Issue by nrodriguez** [aws/aws-sdk-ruby#1081]
When call the ```describe_application_versions``` method I noticed the response does not include the deployed_to information.

```#<struct Aws::ElasticBeanstalk::Types::ApplicationVersionDescription
  application_name="APP",
  description="DESCRIPTION",
  version_label="LABEL",
  source_bundle=
   #<struct Aws::ElasticBeanstalk::Types::S3Location
    s3_bucket="S3BUCKET",
    s3_key="S3KEY">,
  date_created=2016-02-01 15:59:22 UTC,
  date_updated=2016-02-01 15:59:22 UTC,
  status="UNPROCESSED"```

Is there any plan to add that information to the response?

**Comment by awood45** [comment]
This isn't a part of their API for that method, but can you describe what you're trying to do? May be able to help, and if not, will have more precise feedback to send to the Beanstalk team.

**Comment by nrodriguez** [comment]
@aw I'm currently looking to automate the cleanup of old application versions. Since we deploy often, I wanted to just delete whatever versions were not deployed to a beanstalk instance

**Comment by awood45** [comment]
I understand what you're getting at.

It's been pointed out to me that the Elastic Beanstalk CLI does this:
```bash
eb labs cleanup-versions
```
If you'd like to go the API route, you can combine the output of [#describe_application_versions](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticBeanstalk/Client.html#describe_application_versions-instance_method) with the version labels in [#describe_environments](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticBeanstalk/Client.html#describe_environments-instance_method) to determine which versions are not in use.

Does this help?

**Comment by nrodriguez** [comment]
@awood45 That solution seemed to work using the application versions and the describe environments methods. I do wish that there was just an endpoint for it but thank you.

**Comment by awood45** [comment]
I'll pass on that feedback. Let me know if you have any more questions!
