### ISSUE TITLE
The multipart upload initiate requested encryption.

### ISSUE THREAD

**Issue by rokka-n** [aws/aws-sdk-ruby#1084]
Am I doing something stupid?

```
creds = Aws::SharedCredentials.new(region: 'us-east-1')
s3 = Aws::S3::Resource.new(creds, :region => 'us-east-1')

cipher = OpenSSL::Cipher::AES256.new(:CBC)
key = cipher.random_key
obj = s3.bucket('some-backups').object('key')

obj.upload_file('large.txt', :sse_customer_key => key, :sse_customer_algorithm=>'AES256')

/Library/Ruby/Gems/2.0.0/gems/aws-sdk-resources-2.2.14/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:72:in `abort_upload': multipart upload failed: The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters

from aws-sdk-ruby/aws-sdk-resources/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:72:in `abort_upload'
```

It repeats the message for all parts  of upload.

**Comment by rokka-n** [comment]
Hi,

Looks like a bug. 

There is a bunch of options missing in the compute_parts method at 
https://github.com/aws/aws-sdk-ruby/blob/282f9719cf7c6389bee935ab17360e6dd29956d3/aws-sdk-resources/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb#L87

Adding this two, for example fixes problem with sse with customer keys. 
```
           sse_customer_key: options[:sse_customer_key],
           sse_customer_algorithm: options[:sse_customer_algorithm]
```

**Comment by awood45** [comment]
Thanks for the report, will reproduce and investigate.

**Comment by trevorrowe** [comment]
Thanks for reporting the issue. I've put together a fix that will work for the SSE CPK options and any other future options by inspecting the API model for S3 to know what options the call accepts. I've also added an integration test to ensure this continues to work.

**Comment by rokka-n** [comment]
Nice, thank you for fixing.
