### ISSUE TITLE
MD5 digest verification for SQS message attributes

### ISSUE THREAD

**Issue by tawan** [aws/aws-sdk-ruby#1085]
I implemented the calculation MD5 digests for message attributes in a [gem of mine](https://github.com/tawan/active-elastic-job/blob/v1.3.0/lib/active_elastic_job/md5_message_digest_calculation.rb)

Now I wonder if this is actually already done in this client, but I couldn't find it, or if it's still necessary to check the md5 digests at all.

Cheers,

tawan

**Comment by awood45** [comment]
It's not currently done, but we would certainly take a pull request to do it, or add it as a feature request.

If you want to take a crack at the PR, I'd recommend writing such a validation as a plugin, similar to our S3 MD5 checker.

**Comment by tawan** [comment]
Ok, I'll have a look at the S3 MD5 checker and wrap it in a PR. In case of questions, I'll drop them here.
