### ISSUE TITLE
Allow me to set connection_draining when creating an elb

### ISSUE THREAD

**Issue by grosser** [aws/aws-sdk-ruby#1094]
atm I need to do this, which is a bit annoying ... 
ideally keep all attributes in sync ...
works fine on the cli

```
      elb_client.create_load_balancer(config)
      elb_client.modify_load_balancer_attributes(
        load_balancer_name: elb_name,
        load_balancer_attributes: {
          connection_draining: {enabled: true, timeout: 300}
        }
      )
```

error:

```
ArgumentError: unexpected value at params[:connection_draining]
```

version: aws-sdk (2.2.15)

**Comment by awood45** [comment]
Sorry, help me understand. Are you getting that ArgumentError from the code above?

**Comment by grosser** [comment]
no, from doing a create_load_balancer with `:connection_draining` set

**Comment by awood45** [comment]
It does not appear that the `#create_load_balancer` API supports that parameter: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancer.html

There's not much I can do here, I would suspect that the CLI is just providing a wrapper around running those two commands.

**Comment by awood45** [comment]
Actually, for clarity, what CLI command are you running that allows this?

**Comment by grosser** [comment]
ahhh ... I was using `aws elb create-load-balancer` with `--cli-input-json` but cli-input-json was not supported in the ruby wrapper, so I was thinking it was possible to do it directly ... 

let's close this, I understand that this is not easy/possible ... but maybe supporting cli-input-json is ... not sure ... thx for the reply!
