### ISSUE TITLE
Aws::ElasticLoadBalancing::Client#delete_load_balancer should raise when missing

### ISSUE THREAD

**Issue by grosser** [aws/aws-sdk-ruby#1095]
`Aws::IAM::Client#delete_server_certificate` raises `Aws::IAM::Errors::NoSuchEntity` when the certificate is missing, I was surprised to see that `Aws::ElasticLoadBalancing::Client#delete_load_balancer` does not do that, but simply ignores this ... a consistent behavior would be nice (either always raise or always ignore)

version: aws-sdk (2.2.15)

**Comment by awood45** [comment]
I can pass that feedback on to the service team. The errors you're getting are from the service level, so there's no way for our client to alter this behavior.
