### ISSUE TITLE
Aws::AutoScaling::Resource#activities fails with NoMethodError

### ISSUE THREAD

**Issue by mdub** [aws/aws-sdk-ruby#1101]
I'm having problems using `Aws::AutoScaling::Resource#activities`, and `Aws::AutoScaling::Group#activities`, both of which are failing in `Aws::Resources::Builder#build_batch`, like this:

```
Aws> Aws.autoscaling.resource.activities(auto_scaling_group_name:"asg").first
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/mike_williams/.gem/ruby/2.2.3/gems/aws-sdk-resources-2.2.19/lib/aws-sdk-resources/builder.rb:52:in `block (2 levels) in build_batch'
```

whereas, the corresponding client call works fine:

```
Aws> Aws.autoscaling.describe_scaling_activities(auto_scaling_group_name:"asg")
=> #<struct Aws::AutoScaling::Types::ActivitiesType
```

I'm using version `2.2.19` of `aws-sdk-resources`

**Comment by awood45** [comment]
Thanks for the report - I'll reproduce and see what can be done about this.

**Comment by awood45** [comment]
The issue is a typo in the resource definition. Going to make a fix for this and test.

**Comment by awood45** [comment]
Fix is pushed and will go out with the next release.
