### ISSUE TITLE
Table Not Found

### ISSUE THREAD

**Issue by nathantechie9** [aws/aws-sdk-ruby#1102]
The aws sdk dynamo client isn't finding any of my tables on aws dynamo.

[1] pry(main)> d = Aws::DynamoDB::Client.new
=> #<Aws::DynamoDB::Client>
[2] pry(main)> d
=> #<Aws::DynamoDB::Client>
[3] pry(main)> d.list_tables
 
    <struct Aws::DynamoDB::Types::ListTablesOutput table_names=[], last_evaluated_table_name=nil>

**Comment by nathantechie9** [comment]
I verified the aws keys are correct. I was able to insert data from the aws cli.

**Comment by nathantechie9** [comment]
I found the problem. I have to set the region when creating the dynamo client.

**Comment by trevorrowe** [comment]
Normally the `Aws::DynamoDB::Client.new` method would raise an argument error indicating that a `:region` has not been specified. I suspect your environment has exported a region environment variable. Here is the list of ENV keys it searches:

* `ENV['AWS_REGION']`
* `ENV['AMAZON_REGION']`
* `ENV['AWS_DEFAULT_REGION']`

Hope this helps.
