### ISSUE TITLE
v2.2.19 nil to integer TypeError in md5_of_message_attributes(message_attributes)

### ISSUE THREAD

**Issue by zwang80** [aws/aws-sdk-ruby#1103]
aws-sdk-core v2.2.19

Aws::SQS::Client.send_message returns exception
sending message using option: {:queue_url=>"https://sqs.us-west-2.amazonaws.com/1234567890/aws-sqs-test", :message_body=>"{\"mirror\":true}", :message_attributes=>{"att_string"=>{:data_type=>"String.test", :string_value=>"String value"}}}
name: "att_string", attribute: {:data_type=>"String.test", :string_value=>"String value"}

in md5_of_message_attributes(message_attributes)
[TRANSPORT_TYPE_ENCODINGS[attribute[:data_type]]] turns out to be [nil]

TypeError: no implicit conversion of nil into Integer
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:111:in `pack'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:111:in `block in md5_of_message_attributes'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:92:in `each'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:92:in `md5_of_message_attributes'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:74:in `validate_attributes'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:57:in `validate_single_message'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:40:in `validate_send_message'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:20:in `block in call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/response.rb:43:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/response.rb:43:in `block in on'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:139:in `block in on_success'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:166:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:166:in `block in listener'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:130:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:130:in `on_done'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/http/response.rb:137:in `on_success'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/response.rb:42:in `on'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/response.rb:51:in `on_success'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/sqs_md5s.rb:17:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/request.rb:70:in `send_request'
    /home/dummydir/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-2.2.19/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    /home/dummydir/my-test/tc_sqs.rb:523:in `send_message'

**Comment by awood45** [comment]
Thanks for the report - will take a look at the PR as well.

**Comment by trevorrowe** [comment]
I've merged the PR. This should go out with tomorrows release. Thank you for the thorough bug report and PR.
