### ISSUE TITLE
standard_ia storage class not honored on multi-part upload

### ISSUE THREAD

**Issue by jaypatrickhoward** [aws/aws-sdk-ruby#1106]
Using aws-sdk 2.2.0 with ruby 2.1.5  on CentOS6.

The following code:

```
object = bucket.object("#{prefix}/#{object_name}")
object.upload_file("#{object_name}", storage_class: "STANDARD_IA")

```
...creates objects with storage class "STANDARD_IA" for files smaller than 15 MB but storage class "STANDARD" for files 15 MB or larger, i.e. the default threshold for triggering a multi-part upload.

Is that by design?

**Comment by jaypatrickhoward** [comment]
Verified that "storage_class" isn't being passed on the "create_multipart_upload", "upload_part" or "complete_multipart_upload" calls when those are provoked by a call to "upload_file".

**Comment by mirceal** [comment]
+1

**Comment by mirceal** [comment]
:+1:

**Comment by awood45** [comment]
This would not be by design for any reason I can think of, thanks for the report.

**Comment by jaypatrickhoward** [comment]
Happy to oblige.  Let me know if there's anything else I can do to expedite the process of this getting into an official release.  Update the test cases, etc.  (Will require me to figure out how the test cases work, though...)

**Comment by awood45** [comment]
Certainly happy to see a PR for this. The unit tests would likely just confirm that the relevant headers are being lifted to the request (which would, at this point, be a failing test).

**Comment by trevorrowe** [comment]
Thanks for the PR.
