### ISSUE TITLE
2.2.16 - 2.2.20 - Stubbing repeats responses (head_object)

### ISSUE THREAD

**Issue by Optimiza** [aws/aws-sdk-ruby#1107]
**2.2.16 - 2.2.20**

Hi everybody.

I found some kind of strange behavior stubbing responses. 

Doing something like this on my before(:each) block:

```ruby
  Aws.config[:s3] = {
    stub_responses: {
      list_objects: {
        contents: [
          { key: "#{s3_prefix}template-a/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}template-b/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}template-c/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}not-a-template/docker-compose.xml", last_modified: Time.now.utc }
        ]
      },
      head_object: [
        { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
        { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } } ,
        { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } }
      ]
    }
  }
```

The first time the response received calling s3.list_objects & head_object(3 times) is OK:

> template-a  my-prefix/template-a/docker-compose.yml  2016-02-27 18:34:58 UTC  t1.tiny  art1:art2:art3
> template-b  my-prefix/template-b/docker-compose.yml  2016-02-27 18:34:58 UTC  t2.tiny  art2:art1
> template-c  my-prefix/template-c/docker-compose.yml  2016-02-27 18:34:58 UTC  t3.tiny  art3:art2

Then in the next iteration, running the next :example, I'm resetting Aws.config[:s3] and placing again the same data.

I dumped and traced it and the data is right on place but when I call again the s3.list_objects and head_object(3 times) I got the following result:

> template-a  my-prefix/template-a/docker-compose.yml  2016-02-27 18:34:58 UTC  **t3.tiny  art3:art2**
> template-b  my-prefix/template-b/docker-compose.yml  2016-02-27 18:34:58 UTC  **t3.tiny  art3:art2**
> template-c  my-prefix/template-c/docker-compose.yml  2016-02-27 18:34:58 UTC  **t3.tiny  art3:art2**

Maybe I'm missing something but I think that head_object stub is not reseting some kind of counter and the second time I stubbed it, it just returns the third row of metadata.

Many thanks for your help.

**Comment by Optimiza** [comment]
Just confirmed is something related to a pointer which is in charge of the **head_object** row.

If I repeat data rows like this:

```ruby
  Aws.config[:s3] = {
    stub_responses: {
      list_objects: {
        contents: [
          { key: "#{s3_prefix}template-a/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}template-b/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}template-c/docker-compose.yml", last_modified: Time.now.utc },
          { key: "#{s3_prefix}not-a-template/docker-compose.xml", last_modified: Time.now.utc }
        ]
      },
      head_object: [
        { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
        { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } },
        { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } },
        { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
        { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } },
        { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } },
        { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
        { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } },
        { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } },
        { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
        { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } },
        { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } }
      ]
    }
  }
```

It returns the right rows till the last one.

**Comment by awood45** [comment]
Thanks for the report, will take a look at this.

**Comment by trevorrowe** [comment]
As far as I can tell, this feature is working as expected. Client response stubbing will always returns the next element in the response stub list for an operation on subsequent calls. If the final response has been returned, it will continue to return the final response. For example:

```ruby
s3_prefix = ''

Aws.config[:s3] = {
  stub_responses: {
    list_objects: {
      contents: [
        { key: "#{s3_prefix}template-a/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}template-b/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}template-c/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}not-a-template/docker-compose.xml", last_modified: Time.now.utc }
      ]
    },
    head_object: [
      { metadata: { "instance" => "t1.tiny", "artifacts" => "art1:art2:art3" } },
      { metadata: { "instance" => "t2.tiny", "artifacts" => "art2:art1" } } ,
      { metadata: { "instance" => "t3.tiny", "artifacts" => "art3:art2" } }
    ]
  }
}

s3 = Aws::S3::Client.new

# produces what you expect
s3.list_objects(bucket:'aws-sdk').contents.each do |obj|
  key = obj.key
  metadata = s3.head_object(bucket:'aws-sdk', key:key).metadata
  puts "#{key} : #{metadata.inspect}"
end

# every HEAD object request replays the last element
s3.list_objects(bucket:'aws-sdk').contents.each do |obj|
  key = obj.key
  metadata = s3.head_object(bucket:'aws-sdk', key:key).metadata
  puts "#{key} : #{metadata.inspect}"
end

# start over with a new client, produces what you expect
s3 = Aws::S3::Client.new
s3.list_objects(bucket:'aws-sdk').contents.each do |obj|
  key = obj.key
  metadata = s3.head_object(bucket:'aws-sdk', key:key).metadata
  puts "#{key} : #{metadata.inspect}"
end
```

Also worth noting, If you are making a HEAD request for each element in your list objects response, you have 1 more key than you have stubbed responses. It may be that you are sharing a client instance between each test execution and are therefore leaking state. If your code is public, I'd be happy to take a look at it for you.

**Comment by Optimiza** [comment]
You are absolutely right, the problem is on my side due I wanted to reuse the Client once it's configured.

But this is not a very good idea for testing.

Many thanks for your help and time.

+1

**Comment by Buuntu** [comment]
From your code
```
list_objects: {
      contents: [
        { key: "#{s3_prefix}template-a/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}template-b/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}template-c/docker-compose.yml", last_modified: Time.now.utc },
        { key: "#{s3_prefix}not-a-template/docker-compose.xml", last_modified: Time.now.utc }
      ]
    },
```

Is this the correct way to assign prefixes to stubs?  As part of the key name?  Sorry I can't find any documentation on that and I've tried using `prefix: some_prefix` to no avail.
