### ISSUE TITLE
NoMethodError: undefined method `copy_to'

### ISSUE THREAD

**Issue by Manju244** [aws/aws-sdk-ruby#1110]
Installed Gem
```
aws-sdk (2.2.20, 2.1.2)
aws-sdk-core (2.2.20, 2.1.2)
aws-sdk-resources (2.2.20, 2.1.2)
```

Defined in Gemfile as,
gem 'aws-sdk'

Using Rails4 and Ruby2.1.2

I am going to copy a file from a bucket to another bucket.
```
bucket = Aws::S3::Bucket.new('source-bucket', :region => 'region')
obj = bucket.object('source-key')
obj.copy_to(target_bucket, 'target-key')
```

When running the code giving the error as follows,
NoMethodError: undefined method `copy_to' for #<Aws::S3::Object bucket_name="source-bucket", key="source-key">
  
How to achieve this?

**Comment by jaypatrickhoward** [comment]
If you're using bundler, does your Gemfile.lock specify version 2.1.2 of aws-sdk? If so, do "bundle update aws-sdk" then commit the new Gemfile.lock, which should now specify aws-sdk 2.2.20.

**Comment by Manju244** [comment]
Nice working. My bad.

Thanks for your valuable response.
