### ISSUE TITLE
Make presigned url available in core

### ISSUE THREAD

**Issue by grosser** [aws/aws-sdk-ruby#1113]
I'm trying to use only core everywhere for consistency/simplicity, but to get presigned urls (for a get request) it looks like I have to use resource ... which feels dirty :(

http://docs.aws.amazon.com/AmazonS3/latest/dev/UploadObjectPreSignedURLRubySDK.html#UploadObjectPreSignedURLRubySDKV2

Can this be made available inside of core instead with something like `Xyz.presigned_url(:get, client.get_object(bucket: xyz, key: foo))`

**Comment by awood45** [comment]
In general, higher level abstractions including Presigning and Object Upload were put into the resources gem. Is there a particular reason you don't want to or can't pull in the resources gem?

**Comment by grosser** [comment]
I can, but I'd prefer not to pull it in, to not have an additional gem /
not make other apis available and keep the app consistent.
I was assuming the design philosophy is to have everything in core and
resources is just a fancy wrapper.

**Comment by trevorrowe** [comment]
@grosser The linked documentation uses on method to generate a presigned URL. The actual implementation relies on `Aws::S3::Presigner` which is part of aws-sdk-core. You can construct a presigner directly:

```ruby
presigner = Aws::S3::Presigner.new(client: Aws::S3::Client.new(...))
url = presigner.presigned_url(:get, bucket:'bucket_name', key:'object-key', expires_in:3600)
```

@awood45 Is correct that most of our higher level abstractions live in the resources gem, but this feature is essential enough for S3 that it lives in core. Hope this helps.
