### ISSUE TITLE
delete with empty list raises xml error

### ISSUE THREAD

**Issue by grosser** [aws/aws-sdk-ruby#1114]
already ran into this twice, kind of annoying/cryptic ...

```
keys = ... some method that returns empty array ...
client.delete_objects(bucket: bucket, delete: {objects: keys})

Aws::S3::Errors::MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
```

so ideally raise a nice error like `Cannot delete empty list` ... or simplify don't make the request ...

**Comment by awood45** [comment]
I can bring this up with the service team, and see if there is a model enhancement that can be made. I wouldn't be inclined to make this a client-side customization since it's making a validation assertion that, in theory, could change server side.

**Comment by grosser** [comment]
I was thinking, if there is nothing to delete, then ideally the client
would not make a call.
Alternatively a nice api error message would also work ... but avoiding
network calls is always great :)

**Comment by awood45** [comment]
I agree and will look in to if a model-level validation is possible here. I don't want to go down the customization route, however.
