### ISSUE TITLE
Since 2.2.21: cannot load such file -- kramdown (LoadError)

### ISSUE THREAD

**Issue by pndurette** [aws/aws-sdk-ruby#1115]
Hi,

Since upgrading to `aws-sdk` version `2.2.21`, I get a `LoadError` on missing gem `kramdown`. I see this was added in `2.2.21` and is in the `:docs, :test` groups of the `Gemfile`, but somehow the released gem requires it and of course can't find it. All I did was:

```
ec2 = Aws::EC2::Client.new(region:'us-east-1')
```

(Had to stick with `2.2.20`)

Thanks! I can provide more info if required.
Pierre

**Comment by awood45** [comment]
I've pushed a fix, releasing shortly.

**Comment by pndurette** [comment]
Thanks :+1:
