### ISSUE TITLE
Failure to due `kramdown` gem not being installed

### ISSUE THREAD

**Issue by shortdudey123** [aws/aws-sdk-ruby#1116]
With the release of version `2.2.21` creating a new client (`Aws::CloudWatch::Client.new(access_key_id: '1234', secret_access_key: 'abcd', region: 'us-east-1')`) bombs out with the following
```
 cannot load such file -- kramdown
```

It was added [here](https://github.com/aws/aws-sdk-ruby/commit/e3a69768db7b78ddc07c130803beb5bdc9090ddc#diff-cfa553c98a307894b03b02a0921dafb2) and it looks like https://github.com/aws/aws-sdk-ruby/commit/39675824196054919125e3173e5568ab74228969 might have broken it

**Comment by nickchappell** [comment]
+1

**Comment by jasonschulte** [comment]
+1

The immediate workaround is to install the kramdown gem.

**Comment by awood45** [comment]
Working on the fix now, will push a new patch release afterwards.

**Comment by pndurette** [comment]
Same as #1115. Thanks @awood45.

**Comment by awood45** [comment]
@jasonschulte is correct, but we're going to push a fix to make that unnecessary (otherwise should be added as a gemspec dependency).

**Comment by darkarnium** [comment]
+1

**Comment by awood45** [comment]
I've pushed a fix, verifying and releasing shortly.

**Comment by awood45** [comment]
Release is in progress. I'll close this issue once I confirm that 2.2.22 resolves the issue.

**Comment by warandpeace** [comment]
@awood45 Thanks for being so on top of this. :100:

**Comment by shortdudey123** [comment]
@awood45 thanks for the very quick response!

**Comment by pndurette** [comment]
Thanks! :+1: !

**Comment by awood45** [comment]
Gem version 2.2.22 is out. I have to wait a few minutes to test (uninstalling kramdown mid-release would not be my smartest move today). Can someone help confirm the problem is gone?

**Comment by darkarnium** [comment]
@awood45 thanks for the quick fix, I'm just running a test on my end to confirm for ya :)

**Comment by darkarnium** [comment]
@awood45 I can confirm that from at least Amazon EC2 version 2.2.22 is being installed from Ruby gems and is no longer raising this exception.

**Comment by awood45** [comment]
I can also now confirm no issues on my end. Closing this, but feel free to reopen if anyone is seeing this with 2.2.22.

Thanks everyone for the flood of reports - and I apologize for the mental mistake on this one. We'll do better.
