### ISSUE TITLE
Route53 change-resource-record-sets DELETE requests fail with Invalid request exception

### ISSUE THREAD

**Issue by robzr** [aws/aws-sdk-ruby#1119]
Here is a pp dump of what I'm passing (sensitive information scrubbed):

{:hosted_zone_id=>"/hostedzone/XXXXXXXXXXX",
 :change_batch=>
  {:comment=>"Updating zone example.com",
   :changes=>
    [{:action=>"DELETE",
      :resource_record_set=>
       {:name=>"test.example.com", :type=>"TXT", :ttl=>300}}]}}

As per the documentation, I'm only including what is necessary to delete a simple record.  Using the same credentials/zone/data structure while doing an UPSERT works as expected (only difference in the UPSERT is that I also include resource_record: [ { value: "rdata" } ]).

I've read and re-read both the gem and REST API docs for change-resource-record-sets, I hope this is not a false report on my part.

Rob

**Comment by awood45** [comment]
Can you try this again with a wire trace?

```ruby
client = Aws::Route53::Client.new(http_wire_trace: true)
# run your calls
```

You can scrub sensitive data of course, mainly interesting in seeing if the request is well formed by the client. Usage issue versus potential bug.

**Comment by robzr** [comment]
Thanks Alex, I did that, and am attaching the output from a working change_resource_record_sets call (UPSERT) and the non-working call (DELETE).

Rob

[trace_bad_DELETE.txt](https://github.com/aws/aws-sdk-ruby/files/155904/trace_bad_DELETE.txt)
[trace_good_UPSERT.txt](https://github.com/aws/aws-sdk-ruby/files/155905/trace_good_UPSERT.txt)

**Comment by robzr** [comment]
If it helps, I used an inline proxy to sniff out the XML.  Here is the request and response.  Again, authentication works, ChangeResourceRecordSetsRequest works for an UPSERT, but fails on a DELETE.  I have verified that the Name/Type/TTL all match what is in R53 and is consistent with the UPSERT requests that do work.

[request.txt](https://github.com/aws/aws-sdk-ruby/files/190196/request.txt)
[response.txt](https://github.com/aws/aws-sdk-ruby/files/190197/response.txt)

**Comment by awood45** [comment]
I agree this isn't a helpful error message. I'm reaching out to the service team for help on this, because as far as I can tell we're sending a well-formed request. I'll update this space.

**Comment by awood45** [comment]
For the non-working call, I'm hearing that `:resource_records` is required. A best practice shared from the service team is to take the result of `#list_resource_record_sets` and use that for the call into `#change_resource_record_sets` with whatever changes you want to make.

Let me know if this resolves your issue.

**Comment by jtopper** [comment]
I hit this bug today too, but can confirm that passing the resulting record set object from `#list_resource_record_sets` into the deletion call resolves the problem.

**Comment by robzr** [comment]
Got it!  Yah guys, I scoured the docs for the API as well as the Ruby API stuff and my reading of it suggests it does not need this, and to get it to work I had to do some rewriting - but you're right, that was it, and it is now working.  

Thanks,

Rob

**Comment by alanwds** [comment]
Just to know.. i used ChangeBatch based on [AWS union.py](https://github.com/aws-samples/aws-lambda-ddns-function/blob/master/union.py) and work's well:

```
 route53.change_resource_record_sets(
                HostedZoneId=zone_id,
                ChangeBatch={
                    "Comment": "Updated by Lambda DDNS",
                    "Changes": [
                        {
                            "Action": "DELETE",
                            "ResourceRecordSet": {
                                "Name": host_name + hosted_zone_name,
                                "Type": type,
                                "TTL": 60,
                                "ResourceRecords": [
                                    {
                                        "Value": value
                                    },
                                ]
                            }
                        },
                    ]
                }
            )
```
