### ISSUE TITLE
Programmable stubs

### ISSUE THREAD

**Issue by dpiddy** [aws/aws-sdk-ruby#1120]
It would be great if I could use a callback to determine how to respond to a stubbed request. For example, I want to return an error if a server certificate named `foo` is deleted but return a successful response for anything else.

**Comment by trevorrowe** [comment]
Thanks for the feature request. Depending on what testing framework you use, there are methods to achieve this. For example, using RSpec, you can do the following:

```ruby
client = Aws::S3::Client.new(stub_responses: true)

# success
allow(client).to receive(:delete_bucket).with(bucket:'aws-sdk').and_return(client.stub_data(:delete_bucket))

# error
allow(client).to receive(:delete_bucket).with(bucket:'aws-sdk-not-empty').and_raise(Aws::S3::Errors::BucketNotEmptyError)

# all other requests will hit the default stubs
```

Moving this sort of functionality into the client stubbing interface could be helpful as well. The above example can be a bit verbose, and depends on using a mocking/stubbing library. Just sharing it in case it can help.

**Comment by dpiddy** [comment]
Thanks for the tip. `client.stub_data` could help.

A downside to that approach is you lose validation on the names of methods you've stubbed (with `allow`) and the provided args. For example, I could use that to make `delete_buckets(bucket_names: ...)` or `delete_bucket(bucket_name: ...)` work but neither of those are valid for real use.

There are probably ways to use rspec/etc to help prevent that but takes care.

**Comment by trevorrowe** [comment]
I agree. It also prevents the SDK from executing the request stack. Response stubbing very carefully only by-passes the network request. This ensures any handlers or plugins still trigger. The rspec `#allow` method will short-circuit all of these.

**Comment by awood45** [comment]
Moved to the feature request backlog.

**Comment by janko-m** [comment]
I *think* this is already possible by passing a `Proc` as a stub value. I discovered this feature when reading tests for aws-sdk itself, and I just made a PR to document this: https://github.com/aws/aws-sdk-ruby/pull/1539.

To take your original example, you should be able to do something like this:

```rb
client.stub_responses(:delete_certificate, -> (context) {
  context.params[:certificate_arn] == "foo" ? "YourError" : {...}
})
```
