### ISSUE TITLE
NoMethodError: undefined method `require_credentials' for #<Aws::Plugins::S3RequestSigner::SigningHandler:0x007fa34c5cf5c0>

### ISSUE THREAD

**Issue by mparramont** [aws/aws-sdk-ruby#1124]
Hi!

Our app just had a 5 minute brownout because we couldn't access our S3 resources due to the following error:
```ruby
NoMethodError: undefined method `require_credentials' for #<Aws::Plugins::S3RequestSigner::SigningHandler:0x007fa34c5cf5c0>
```

Restarting the server instances solved the problem.

Is there any information about what may have caused this? Thanks!

**Comment by awood45** [comment]
Can you provide a full stack trace for this? Will take a look.

**Comment by mparramont** [comment]
![screen shot 2016-03-11 at 10 26 58](https://cloud.githubusercontent.com/assets/636075/13698526/d25d06cc-e774-11e5-95d6-ae86f63b67aa.png)

Sorry about giving you a screenshot instead of a textual stack trace, our error logging tool does not support exporting it :/

Thanks for your time!

**Comment by awood45** [comment]
This is interesting...I'm unable to recreate the issue on my end. Can you tell me which SDK version you were using at the time of the failure?

**Comment by awood45** [comment]
...and, by chance, if restarting your servers would potentially involve rebuilding your bundle, and therefore silently upgrading?

**Comment by mparramont** [comment]
We're using `aws-sdk 2.2.7`. Our bundle is only rebuilt on every deploy (we use Heroku), so it's not rebuilt when restarting AFAIK.

**Comment by trevorrowe** [comment]
@mparramont Are you multithreading or using some other form of concurrency with the SDK? The AWS SDK for Ruby does rely on Ruby's `#autoload` which has been known to break down under certain scenarios. It can happen that a class is defined and accessed before it's methods have been added to the class.

If you see this error again in the future, you may consider adding something like this to your app and see if this resolves the issue:

```ruby
require 'aws-sdk'

Aws.eager_autoload!(services: ['S3'])
```

**Comment by awood45** [comment]
Given the fact that this error was happening transiently, I think eager autoloading should solve the issue. If it doesn't, please feel free to reopen or to cut a new issue.

**Comment by mparramont** [comment]
Will try that, thanks a lot for your support!

**Comment by magec** [comment]
I came across this 'today' (6 years later after last comment), and in my case the issue was due to the fact that ruby 3 does not include `webrick` anymore. To fix it I simply added:

```
gem 'webrick', '1.7.0'
```
In the Gemfile.
