### ISSUE TITLE
Can't upload object to S3 bucket with dots in name

### ISSUE THREAD

**Issue by peterkinmond** [aws/aws-sdk-ruby#1125]
`S3::Client#put_object` works for S3 buckets with letters/dashes in their name but doesn't seem to work for buckets with dots in their name. I don't see this addressed in any open issues or anywhere in the docs - is this a known problem?

**Comment by awood45** [comment]
I'm unable to recreate this - I am able to call `#put_object` successfully on a dotted bucket. Can you tell me more about your use case?

* What region are you calling?
* What version of the SDK are you using?
* Can you give me a failing example? Similar but not exactly the same bucket name is fine.

**Comment by peterkinmond** [comment]
Thanks for the quick reply. After more investigation, you're right, it wasn't the dotted bucket name, it was IAM policy that needed updating. I'm now able to call `#put_object` successfully on a dotted bucket.
