### ISSUE TITLE
Image does not define exists?

### ISSUE THREAD

**Issue by joaogbcravo** [aws/aws-sdk-ruby#1127]
Whould you implement this method?

(rdb:1) result = driver.ec2_resource.image('ami-30bd5151')
#<Aws::EC2::Image id="ami-30bd5151">

(rdb:1) result.methods
[:id, :create_tags, ...,  :wait_until, :data, :data_loaded?, :**exists?**, :load, :reload, :inspect, ...]

(rdb:1) result.exists?
/opt/chefdk/embedded/lib/ruby/2.1.0/debug.rb:290:in `eval':#exists? is not implemented for Aws::EC2::Image

**Comment by awood45** [comment]
Thanks for being proactive on this!

**Comment by joaogbcravo** [comment]
Thanks to be so quickly in accepting it :)
