### ISSUE TITLE
Quotes in response etag value

### ISSUE THREAD

**Issue by kdstew** [aws/aws-sdk-ruby#1134]
When making a request PUT request to S3 using the following
```
file = File.open('README.md', 'r')
client = Aws::S3::Client.new
response = client.put_object(
  body: file.read,
  bucket: 'somebucket',
  content_type: 'text/html',
  key: 'somekey'
)
```
the `etag` value returned has unnecessary parenthesis wrapping the value.
```
response.etag
=> "\"85a3d101ba8eab8d0fcdffd29c1f7e85\""
```

It would be nice if the quotes were removed from the etag value.

**Comment by trevorrowe** [comment]
The quotes are actually part of the return value as given by S3. I agree they are awkward, but the etag does contain them. Removing them now would also be a breaking change for anyone who is attempting to remove them, so we can not do that.

Are you accessing the etag to compare it against the md5 of the object you PUT? If so, you might be interested to know that the SDK automatically generates the MD5 and sends it with the object as a header which ensures the object was uploaded correctly.

**Comment by kdstew** [comment]
Thanks for the info.
