### ISSUE TITLE
Documentation for RDS::Resource#db_engine_version has missing parameter

### ISSUE THREAD

**Issue by kayvonghaffari** [aws/aws-sdk-ruby#1138]
In the AWS Rub SDK (version 2) docs, it states that the only parameter needed for RDS::Resource#db_engine_version are:
```
Parameters:
engine_name (String) — The DBEngineVersion#engine_name identifier.
```
[RDS::Resource#db_engine_version](http://docs.aws.amazon.com/sdkforruby/api/Aws/RDS/Resource.html#db_engine_version-instance_method)

After running the command, it looks like a second parameter is needed in the docs: `version (String) -- The DBEngineVersion#engine_version identifier`

**Comment by awood45** [comment]
Indeed, I can see where the docs aren't showing everything, despite it being in the resource description. Going to look more in to this, see how this is happening.

**Comment by awood45** [comment]
I'm even seeing, early on, that the resource call isn't working properly. This may not be a documentation issue.

**Comment by trevorrowe** [comment]
I've just pushed a commit that fixes both the documentation issue and the resource model issue for this method. This should go out with our next release tomorrow.
