### ISSUE TITLE
aws-sdk v2 breaks when detecting oj < 1.4.0

### ISSUE THREAD

**Issue by thomasdziedzic** [aws/aws-sdk-ruby#1139]
Before oj 1.4.0, Oj::ParseError didn't exist:
https://github.com/ohler55/oj/commit/e3a04e82c6fc8a4309c216e759d01f81e8786357#diff-48ffcd1fecb1a5376d043afe4ffa41cdR8

If I try to run the latest aws sdk with an old version of oj, I get:
/usr/local/bundle/gems/aws-sdk-core-2.2.29/lib/aws-sdk-core/json.rb:43:in `oj_engine': uninitialized constant Oj::ParseError (NameError)

We could add a `rescue NameError` in addition to:
https://github.com/aws/aws-sdk-ruby/blob/2839098102122d9f93a01a7af706734fb944a0ab/aws-sdk-core/lib/aws-sdk-core/json.rb#L44

**Comment by awood45** [comment]
Going to try and replicate this, then will work on an update. Also happy to take a pull request if you like.

**Comment by thomasdziedzic** [comment]
I was able to fix this issue by upgrading our oj version.

It might still be worth fixing this for others though, since there is an implicit dependency on oj here.

**Comment by awood45** [comment]
Thanks for the report, I've added a compatibility fix for older `Oj` versions.
