### ISSUE TITLE
Allow filtering of AutoScalingGroups and Launch Configurations

### ISSUE THREAD

**Issue by kayvonghaffari** [aws/aws-sdk-ruby#1142]
It would be helpful if the interface of searching for AutoScaling Groups and Launch Configurations could be expanded to accept filters. I ultimately want to filter ASGs + Launch Configurations by tags.

**Comment by awood45** [comment]
Thanks for the feature request! I'll pass it on to the service team for you as feedback.

**Comment by awood45** [comment]
I'd also consider leaving feedback to the team directly, which you can do through the [console](https://console.aws.amazon.com/ec2/autoscaling/home?region=us-east-1). Click "Feedback" in the lower left hand corner. This is also helpful because they may reach out to you directly.

**Comment by kayvonghaffari** [comment]
Great - thanks @awood45!
