### ISSUE TITLE
Aws::S3::Errors::NotFound when calling delete_marker property on an Object 

### ISSUE THREAD

**Issue by benwells** [aws/aws-sdk-ruby#1153]
I'm trying to loop through object versions and determine which version is the delete marker, but every time I try to call `delete_marker` on an object I get a "Not Found" error.   I see the delete_marker method in the documentation on the S3 Object class (http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#delete_marker-instance_method) but it always throws the error below.  See code snippet and stack trace below.  Am I doing something wrong?  Any advice would be much appreciated, thank you.

```
  versions = bucket.object_versions({prefix: "#{key}"})

  versions.each do |ver|
    puts ver.object #  #<Aws::S3::Object:0x007febda36b938>
    puts ver.object.delete_marker
  end
```

Full trace:

/Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Aws::S3::Errors::NotFound
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/request.rb:24:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/operations.rb:41:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/operations.rb:61:in `call'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/resource.rb:147:in `load'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/resource.rb:120:in `data'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
	from main.rb:53:in `block (2 levels) in run!'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/batch.rb:75:in `each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/collection.rb:18:in `block in each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/operations.rb:130:in `block in all_batches'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-core-2.2.31/lib/aws-sdk-core/pageable_response.rb:75:in `each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/operations.rb:129:in `all_batches'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/collection.rb:18:in `each'
	from /Users/wrb/.rvm/gems/ruby-2.1.2/gems/aws-sdk-resources-2.2.31/lib/aws-sdk-resources/collection.rb:18:in `each'
	from main.rb:52:in `block in run!'
	from main.rb:44:in `each'
	from main.rb:44:in `run!'
	from main.rb:220:in `<main>'

**Comment by awood45** [comment]
I'm not able to replicate your error through creating a fresh bucket/objects and running your code snippet. Can you tell me anything else about these objects that might be different?

**Comment by benwells** [comment]
Thanks for the reply @awood45.   These objects have actually already been deleted, which could be the problem.   For each object, there are 2 versions.  generally version 1 is the point at which the file is uploaded, and version 2 is the delete marker.   I can see both versions when viewing the objects in the AWS console, and I can retrieve both versions using the SDK.  [Here is a screenshot.](https://drive.google.com/file/d/0B5KFWhyJbexKcTRaMFc1eVlFX2c/view?usp=sharing)

My goal here is to detect all objects that were deleted on a certain date and download their most recent, "non delete marker" version.    For these objects, I can retrieve the property last_modified on each object, as well as many other object properties, but I need to determine which object version is a delete_marker and which one isn't.  However, I can't seem to be able to call delete_marker without an error. 

Thanks again and let me know if there is anymore info I can provide.

**Comment by awood45** [comment]
That makes sense, and yes I can replicate the issue now. When we call `#head_object` to pull object data, we're getting a 404. I'll dig in to this a bit more.

**Comment by awood45** [comment]
So there is an issue here, but I'm not sure that there is a way to get your example above to work as-is.

What's happening now, which appears to be wrong, is when you ask for the delete marker we're simply calling `#head_object` without a version ID. For example, my replicating case makes the following calls:

```ruby
[Aws::S3::Client 200 0.745526 0 retries] list_object_versions(prefix:"test-versioned",bucket:"alexwood-versioned-test",encoding_type:"url")
[Aws::S3::Client 404 0.079272 0 retries] head_object(bucket:"alexwood-versioned-test",key:"test-versioned") Aws::S3::Errors::NotFound
```

However, I can craft `#head_object` calls, with the version ID, that give me a more useful result for non-delete-marker versions:

```ruby
s3.head_object(bucket: "alexwood-versioned-test", key: "test-versioned", version_id: "b71KNmKTx7kcMnaZQQK_9gglXpPdpJoQ")
[Aws::S3::Client 200 0.646074 0 retries] head_object(bucket:"alexwood-versioned-test",key:"test-versioned",version_id:"b71KNmKTx7kcMnaZQQK_9gglXpPdpJoQ")
```

Calling `#head_object` on a version with the delete marker will give me a `405` coded error. So, I don't think you'll be able to get an `Aws::S3::Object` resource with `delete_marker: true`.

I am looking in to what the best way is to do this, and if there's an improvement that could be made to the resource abstraction.

**Comment by benwells** [comment]
Thank you for that detail, that definitely sheds some more light on what's going on behind the scenes. 

Just in case someone else out there is battling with this and waiting in suspense for an answer, I wanted to throw out a really bad workaround that at least got me through the task I was working on.  This is horrible for a number of reasons, but:

Loop through versions. For each version, call `version.delete_marker`.  If an exception is thrown, you _probably_ found a delete marker! ;)

```rb
versions.each do | version |
  puts version.object #  #<Aws::S3::Object:0x007febda36b938>

  begin
    puts ver.object.delete_marker  # prints false for all non-delete marker versions
  rescue
    puts "You may have just found a delete marker"
  end
end
```

**Comment by awood45** [comment]
I think part of the issue is that there might be a limitation in the resource model - it could be hard to fix this in a complete and backwards compatible way.

I'd suggest as a workaround that you use the `#list_object_versions` client API instead:

```ruby
client = Aws::S3::Client.new
resp = client.list_object_versions(bucket: bucket, prefix: key)
resp.delete_markers # Has what you want.
```

**Comment by benwells** [comment]
That's a MUCH better workaround, thank you!  I will give that a shot.

**Comment by awood45** [comment]
I haven't heard back, so assuming that this workaround was helpful. Feel free to comment or reopen if you're still having issues.
