### ISSUE TITLE
 DynamoDB raise_response_errors: false BatchWriteItem response: undefined method `unprocessed_items' for nil:Seahorse::Client::Response (NoMethodError)

### ISSUE THREAD

**Issue by anthony-battaglia** [aws/aws-sdk-ruby#1154]
I'm trying to test DyanmoDB BatchWriteItem request error handling and am running into an unexpected issue.  As per the SDK documentation (http://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html#batch_write_item-instance_method), I'm expecting to be able to inspect the return value of Aws::DynamoDB::Client#batch_write_item, specifically the unprocessed_items Hash, however it appears by including config   raise_response_errors: false leads to a NoMethodError.  Here is the full script:

```ruby
STDOUT.sync = true

require 'logger'
require 'aws-sdk-core'

logger = Logger.new(STDOUT)

client = Aws::DynamoDB::Client.new({
  logger: logger,
  raise_response_errors: false,
  region: 'us-east-1'
})

id = 0
response = nil
loop do
  id += 1
  response = client.batch_write_item({
    request_items: {
      "test" => [{put_request: {item: {id: id.to_s, data: "a"*4096}}}]
    }
  })
  break if !(response.unprocessed_items.empty?())
end

puts response.unprocessed_items
```
Testing against a DynamoDB table with read and write capacity set to 1 (deliberately trying to exceed provisioned capacity).  It looks like by default DynamoDB requests are retryed when possible up to 10 times.  ProvisionedThroughputExceeded (throttling error) is a candidate for retry.

Eventually, after exhausting all possible attempts, the script bottoms out with this error, instead of outputting unprocessed items:
```ruby
I, [2016-04-06T14:37:19.636312 #10841]  INFO -- : [Aws::DynamoDB::Client 400 25.891204 10 retries] batch_write_item(request_items:{"trash"=>[{put_request:{item:{"id"=>{s:"7"},"data"=>{"..."}}}}]}) Aws::DynamoDB::Errors::ProvisionedThroughputExceededException The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API

aws-sdk-core-2.1.18/lib/seahorse/client/response.rb:87:in `method_missing': undefined method `unprocessed_items' for nil:Seahorse::Client::Response (NoMethodError)
```

Is there a better way to address this case?  Ultimately looking to not fail silently in the event Provisioned Throughput is exceeded, and be able to identify what records failed to be written.

Thanks.

Versions:
Ruby: 2.1.2
aws-sdk-core: 2.1.18

**Comment by awood45** [comment]
Based on wire tracing, I don't believe unprocessed items is returned when the whole call comes as a `ProvisionedThroughputExceededException` error.

Rather, if you used `#batch_write_items` with an array of many items, and you get a partial success, you'll get a `200` response and `unprocessed_items` will include any items that were not written.

If you get a 400, you can assume all items were not written. All of this is server-side behavior.

Does this help?

**Comment by anthony-battaglia** [comment]
Thanks Alex.  I think I understand a little better now. In the case of raise_response_errors: false like the above example, `response.error` needs to be checked before `response.unprocessed_items`.  If `response.error` is not `nil`, then the whole batch failed.  Otherwise, the request (partially) succeeded and `response.unprocessed_items` can be inspected for any unwritten records.

**Comment by awood45** [comment]
That's correct, yes.

**Comment by awood45** [comment]
Going to close this, since it seems like we have a resolution here. Feel free to ask any follow up questions you have, or to open another issue if there are other issues you run in to.
