### ISSUE TITLE
Get a method "group" not found for AutoScaling::Resource

### ISSUE THREAD

**Issue by WaldynB** [aws/aws-sdk-ruby#1155]
I am getting an error saying that "group" is a bad name for a autoscaling resource instance.

Here is the code.
    asgr=Aws::AutoScaling::Resource.new(region: "us-east-1")
    asg=asgr.group(asgname)

Here is the error I get.
undefined method `group' for #<Aws::AutoScaling::Resource>

My Gemfile sets the leve at at 2.2.32:
 gem 'aws-sdk','~>2.2.32'

Thanks

**Comment by awood45** [comment]
I'm not seeing this error. Are you sure that the gem version is correct?

```ruby
resource = Aws::AutoScaling::Resource.new(region: "us-east-1")
resource.group("Foo") #=> #<Aws::AutoScaling::AutoScalingGroup name="Foo">
```

Try checking the output of the following within your own code:

```ruby
Aws::AutoScaling::Resource.new(region: "us-east-1").methods.sort - Object.new.methods
```

Does that include `:group`?

**Comment by WaldynB** [comment]
No it does not have group or groups.  How do I find out what level I of the aws-sdk I am actually running?  It does not seem to support Aws::AutoScaling::AutoScalingGroup  either.

**Comment by awood45** [comment]
The `Aws::VERSION` variable will tell you the version you have. I'd postulate that you are running an old version, given the missing method.

**Comment by WaldynB** [comment]
The version is 2.0.48.  What version do I need to support AutoScaling::AutoScalingGroup and the group method from Resource?

**Comment by awood45** [comment]
At least 2.2.21, but I'd recommend updating to the most recent version of the SDK in general - we do keep things backwards compatible.

**Comment by awood45** [comment]
Upgrading will resolve your issue, let me know if you have any further questions.
