### ISSUE TITLE
undefined method `stop_run' for #<Aws::DeviceFarm::Client>

### ISSUE THREAD

**Issue by marianafranco** [aws/aws-sdk-ruby#1156]
Hi, I'm trying to stop a run on device farm but I'm having the following error when I try to run `Aws::DeviceFarm::Client.stop_run()`

```ruby
device_farm = Aws::DeviceFarm::Client.new(region: region, credentials: Aws::Credentials.new(public_key, private_key))
device_farm.stop_run({arn: 'my_run_arn'})

Erro:
undefined method `stop_run' for #<Aws::DeviceFarm::Client>
```

I'm using `aws-sdk 2.2.9` and I followed this doc: http://docs.aws.amazon.com/sdkforruby/api/Aws/DeviceFarm/Client.html#stop_run-instance_method

**Comment by marianafranco** [comment]
Closing... moving to `aws-sdk 2.2.39` did the trick :+1:

**Comment by awood45** [comment]
Glad that worked out! We do keep a `CHANGELOG.md` file in the root directory (and publish these release notes [on the AWS web site](https://aws.amazon.com/releasenotes/Ruby?browse=1)) to help debug these kinds of things.

**Comment by marianafranco** [comment]
I think having the version in which the method was included direct in the api doc, something like `since: 2.2.x`, will do better to help users to debug this type of problem :wink:
