### ISSUE TITLE
AssumeRoleCredentials overrides other credentials

### ISSUE THREAD

**Issue by reist** [aws/aws-sdk-ruby#1160]
Hi,

After using the assume role steps from credential_management.md, the basic connections report the assumed role, even if they use the original role.
Is this the way the API is supposed to work?

This is very confusing in errors, as all errors say that arn:...:assumed_role/... is not authorized.

Example code running on a AWS instance:
```
basic_creds = Aws::InstanceProfileCredentials.new

sts = Aws::STS::Client.new(credentials: Aws::InstanceProfileCredentials.new)
creds = Aws::AssumeRoleCredentials.new(
  client: sts,
  role_arn: 'role-arn-to-assume',
  role_session_name: 'role-session-name',
)

sts = Aws::STS::Client.new(credentials: basic_creds)
sts.get_caller_identity # identity with assumed role
```

**Comment by awood45** [comment]
I can say that this would not be intended behavior. Trying to repro now.

**Comment by awood45** [comment]
I'm unable to recreate this on my end. Can you provide me with a detailed stack track of the eventual error, and the output of:

```ruby
basic_creds = Aws::InstanceProfileCredentials.new

sts = Aws::STS::Client.new(http_wire_trace: true, credentials: Aws::InstanceProfileCredentials.new)
creds = Aws::AssumeRoleCredentials.new(
  client: sts,
  role_arn: 'role-arn-to-assume',
  role_session_name: 'role-session-name',
)

sts = Aws::STS::Client.new(http_wire_trace: true, credentials: basic_creds)
sts.get_caller_identity # identity with assumed role
```

Please scrub any sensitive data from the wire logs, I mainly need to see what calls we are making over the wire.

**Comment by reist** [comment]
After trying the above and then trying to assume a role, looks like I wasn't careful enough reading every bit of the messages.
The errors and get_caller_identity did differ - exactly in the assumed role, with the instance credentials listing the IAM role set for the specific instance.

Really sorry for the bother.

**Comment by awood45** [comment]
Glad to hear it got worked out!
