### ISSUE TITLE
s3 bucket existence - unexpected behavior

### ISSUE THREAD

**Issue by Techbrunch** [aws/aws-sdk-ruby#1161]
Same issue as #796, looks like a regression (aws-sdk (2.2.34))

```ruby
require 'aws-sdk'

resource = Aws::S3::Resource.new(region: 'us-east-1')

bucket = resource.bucket('test-issue-s3')
if bucket.exists?
  puts "test"
end
```

```
/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-resources-2.2.34/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?': Aws::S3::Errors::BadRequest
	from /.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-sdk-resources-2.2.34/lib/aws-sdk-resources/resource.rb:131:in `exists?'
	from test.rb:6:in `<main>'
```

**Comment by awood45** [comment]
I am able to replicate the regression, taking a look.

**Comment by awood45** [comment]
Interestingly, the exact choice of bucket name here matters. The bucket 'test-issue-s3' is in the ap-northeast-1 region. So, for example, this code works:

```ruby
Aws::S3::Resource.new(region: "ap-northeast-1").bucket('test-issue-s3').exists? #=> true
```

The issue here comes from the `307 Temporary Redirect` we're getting.

**Comment by awood45** [comment]
Looking back at some previous versions, I don't think this is a regression, I don't think this particular case has ever worked. Looking at fix options. I don't think I want to add `400 Bad Request` as a successful waiter case, however.

**Comment by awood45** [comment]
So, the fix here (as Trevor is wrapping up) is to check for the bucket region in headers as well as the body. That will resolve this issue and similar. It's not often encountered because this particular failure modality was not hit by most client methods.

**Comment by awood45** [comment]
Thanks for the report!

**Comment by Techbrunch** [comment]
@awood45 Awesome thanks for the quick fix !

**Comment by ravsom** [comment]
I get this error for the region "ap-south-1" - 

`/home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.10.38/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?': Aws::S3::Errors::BadRequest
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/aws-sdk-resources-2.10.38/lib/aws-sdk-resources/resource.rb:131:in `exists?'
`

**Comment by raheel0452** [comment]
@ravsom did you ever get solution to above error ? i'm saving same issue

**Comment by ravsom** [comment]
Not really. I changed the workflow to use s3 directly for static web
hosting instead of directing it to eb.
