### ISSUE TITLE
Add support for transfer acceleration when uploading object

### ISSUE THREAD

**Issue by imouaddine** [aws/aws-sdk-ruby#1165]
I tried to `put_object` for a bucket having the feature enabled and it seems it's still using the regular endpoint. 

```ruby 
c = Aws::S3::Client.new(region: "ap-southeast-1")
result = c.put_object(upload_options)
puts result.context.http_request.endpoint.host
```
The used endpoint is:
`ut-acc-sing.s3-ap-southeast-1.amazonaws.com`
Instead of:
`ut-acc-sing.s3-accelerate.amazonaws.com`

When inspecting the gem's code, it seemed the feature is not implemented yet, understandably it is still new. Could you share any timeline for adding support of transfer acceleration?

**Comment by awood45** [comment]
That support does exist now if you set the endpoint manually. There are a couple of open pull requests we're finalizing with further improved support.

**Comment by trevorrowe** [comment]
See the following pull-request:
https://github.com/aws/aws-sdk-ruby/pull/1163

**Comment by awood45** [comment]
Version `2.3.0` is out with this support.

**Comment by imouaddine** [comment]
Thank you!
