### ISSUE TITLE
kms decrypt() is returning ArgumentError: missing required parameter params[:ciphertext_blob]

### ISSUE THREAD

**Issue by four2five** [aws/aws-sdk-ruby#1166]
I'm using version 2.2.28 of the ruby SDK.

This call:
resp = kms.decrypt({ ciphertext_blob: $encrypted_data,})
is generating this error:
ArgumentError: missing required parameter params[:ciphertext_blob]

I'm pretty new to Ruby so I'm guessing that this is a syntax issue. I modeled the structure of my code after this doc: http://docs.aws.amazon.com/sdkforruby/api/Aws/KMS/Client.html#decrypt-instance_method

**Comment by four2five** [comment]
I sorted it out and it was, indeed, a rookie ruby move. $encrypted_data should have simply been encrypted_data since it was a local variable and not a global.

**Comment by awood45** [comment]
Glad that was worked out quickly!

For reference (if others see this), if a hash value is `nil`, Ruby hashes will effectively treat that as the key not existing. That's what the validation is seeing.
