### ISSUE TITLE
What is the purpose of monkey patching global HTTP stack?

### ISSUE THREAD

**Issue by timanovsky** [aws/aws-sdk-ruby#1167]
https://github.com/aws/aws-sdk-ruby/blob/ef9f2d3655c4bacb3adff580a6b295df510f78fe/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L18

It affects all Net::HTTP clients, that's just crazy

**Comment by trevorrowe** [comment]
Have you run into an issue with these patches? They are a series of fixes for Net::HTTP bugs. The issues being patched:

* Net::HTTP retry of idempotent operations is broken when the request body is streaming.
* Net::HTTP retry of idempotent operations is broken when the response body is being yielded
* Net::HTTP's implementation of 100-continue causes runtime errors when a non-100 continue response is returned.

The first two issues are patched by simply disabling all retries at the transport error. Net::HTTP provides no facility to do this with modifying the constant is uses internally to track what http verbs are idempotent. I have an open pull request that does so more carefully by disabling retries only when streaming.

The third issue could only be patched by replacing the entire transport request method. The actual change is quite small to fix the bug. 

Relevant pull requests against ruby/ruby:

https://github.com/ruby/ruby/pull/951 (still open, but see also https://github.com/ruby/ruby/pull/1019)
https://github.com/ruby/ruby/pull/949 (merged)

I may need to revisit the range of Ruby versions to apply these patches to. It is possible some of these fixes made it into 2.3.0. The patches will need to continue to live with this library until all supported versions of ruby have been fixed.

**Comment by timanovsky** [comment]
@trevorrowe I apologize, I misunderstood the situation.  I was not aware of how original `Net::HTTP` code works, and particularly it's built in retry logic. So when I discovered this aws patch in my stack trace and saw retrying logic there I immediately thought it was wrong. Now I see the original `Net::HTTP` code and that your patch in fact disables this retry logic. Which makes sense. So apologies again. 

Anecdote: in my system `transport_request` is overridden three times: by aws lib, by newelic lib, by honeybadger lib.

**Comment by trevorrowe** [comment]
Also worth noting, we do not implement retries from Net::HTTP.

**Comment by carlhoerberg** [comment]
Ideally you should use [Refinements](https://ruby-doc.org/core-2.4.2/doc/syntax/refinements_rdoc.html) instead of open monkey-patching when patching core libraries.

**Comment by tyrauber** [comment]
Hi @trevorrowe, is it possible that these issues were fixed in Ruby 2.5.0, or the patch needs to be updated for Ruby 2.5.0?  I am seeing a whole string of failures related to a conflict between the fastly-rails gem and aws-sdk-core, over the shared use of net::http.  https://github.com/aws/aws-sdk-ruby/issues/1752 Any suggestion on how I resolve this conflict?

**Comment by trevorrowe** [comment]
Very likely. We will need to determine what version of Ruby that Net::HTTP has been patched and scope the patches down to the affected versions.

@cjyclaire and @awood45 would be the best individuals to work with on this.
