### ISSUE TITLE
Aws::S3::MultipartUploadError when uploading large files

### ISSUE THREAD

**Issue by stickerbush** [aws/aws-sdk-ruby#1168]
We are seeing the following error when uploading large (1.5-2.5 GB) files to an S3 bucket.

```
"event_name":"contribution.transfer_file_to_s3.failure",
   "exception_type":"Aws::S3::MultipartUploadError",
   "code":"#<Aws::S3::MultipartUploadError: multipart upload failed: wrong status line: \"HTTP/1.1 200 OK\">",
   "message":"\"multipart upload failed: wrong status line: \\\"HTTP/1.1 200 OK\\\"\"",
   "backtrace":[  
      "/home/ubuntu/apps/submission/vendor/bundle/jruby/2.2.0/gems/aws-sdk-resources-2.2.20/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:81:in `abort_upload'",
      "/home/ubuntu/apps/submission/vendor/bundle/jruby/2.2.0/gems/aws-sdk-resources-2.2.20/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:70:in `upload_parts'",
      "/home/ubuntu/apps/submission/vendor/bundle/jruby/2.2.0/gems/aws-sdk-resources-2.2.20/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:44:in `upload'"
```

Sometimes the wrong status line is reported as:

`wrong status line: \\\"HTTP/1.1 100 Continue\\\"\""`
or
`Resource temporarily unavailable`

We are currently using version aws-sdk version 2.2.20 in production and have tested with 2.2.36 in a test environment. We see the same error with the later version.

Looking at the source for MultipartFileUploader we see no retry mechanism when a part fails to upload. We attempted to monkey patch the upload_in_threads method to do retries but have not found any success with this approach. In observing log files it appears that the "part[:body].close" statement on line 132 of multipart_file_uploader.rb "hangs" for a substantial period of time (minutes) before completing execution.

We are using jruby 2.2.0.

**Comment by awood45** [comment]
Can you show me the context of how you're calling this? Having trouble reproducing this.

**Comment by trevorrowe** [comment]
The multipart uploader uses `Aws::S3::Client` under the covers. The client will, by default, retry specific errors up to 3 times. The `Aws::S3::MultipartUploadError` you are receiving has a `#errors` method which  provides access to an array of all of the errors rescued during upload. Can you try accessing these and giving more information about the specific errors/failures?

**Comment by stickerbush** [comment]
We have isolated our problem with large uploads to an issue with jruby 9.0.

https://github.com/jruby/jruby/issues/3435

**Comment by stickerbush** [comment]
We have isolated our problem with large uploads to an issue with jruby 9.0.

jruby/jruby#3435 <https://github.com/jruby/jruby/issues/3435>


Issue closed.
