### ISSUE TITLE
S3 Presigned_Post ignoring :content_type option

### ISSUE THREAD

**Issue by Dali13** [aws/aws-sdk-ruby#1170]
Hi, 
I was following the Heroku method to direct upload files to S3.

I define an instance variable with a content type option 'image/*':

```
`def set_s3_direct_post

@s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read', content_length_range: 0..5242880 )

@s3_direct_post.content_type('image/*')

end`
```

Here is the beginning of view code 

```
`<%= form_for(@user, :html => { :html => { :multipart => true }, class: 'directUpload form-group', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }}) do |f| %>

.......
<% end %>`
```

However, I am still able to upload other type of files (pdf, txt..), I think that the :content_type option is ignored.

**Comment by awood45** [comment]
What is the content type of one of those objects if you try the following?

```ruby
client = Aws::S3::Client.new(region: REGION)
o = client.get_object(bucket: BUCKET, key: key)
puts o.content_type
```
Keep in mind that S3 doesn't inspect the objects you're sending over the wire (for example, you could just as easily be encrypting them). I would suspect that the content type is set as you defined it.

**Comment by awood45** [comment]
Haven't seen any movement on this for a month, closing.

Feel free to reopen or to open a new issue if you have more information.
