### ISSUE TITLE
NotImplementedError: #load not defined for Aws::S3::ObjectSummary

### ISSUE THREAD

**Issue by sarboc** [aws/aws-sdk-ruby#1172]
Load is not implemented for Aws::S3::ObjectSummary, making it unusable.

```
client = Aws::S3::Client.new(region: "us-east-1")
bucket_name = "sample_bucket"
key = "actual_key_path"
summary = Aws::S3::ObjectSummary.new(client: client, bucket_name: bucket_name, key: key)
summary.size
```

In the above example. summary will instantiate properly as an `Aws::S3::ObjectSummary` object, but calling `size` (or `etag`, or any other method) will return `NotImplementedError: #load not defined for Aws::S3::ObjectSummary`

**Comment by awood45** [comment]
I see what you're saying about the fact that `Aws::S3::ObjectSummary` having a load method present but not implemented. Are you trying to use `ObjectSummary` as a resource equivalent to a `#head_object` call?

For example, I can see that a call like `s3.resource.bucket(b).objects.first` will return an ObjectSummary with the fields in question populated. Calling `summary.object.load` will populate all fields, but may not be desirable if the object in question is large.

I'll take a look at the resource model for this, will also help to understand the use case here.

**Comment by sarboc** [comment]
@awood45 Thanks for the prompt response! I am indeed using `ObjectSummary` as a resource equivalent to a `#head_object` call. You are also correct that I am working with large files (video source files), so loading the object is far from ideal.

**Comment by awood45** [comment]
So, this actually may be complex to do, but I have a workaround.

If you create an Object resource, note that `#load` actually calls `#head_object`. We only call `#get_object` on an explicit get.

For example:
```ruby
s3 = Aws::S3::Resource.new
object = s3.bucket(BUCKET).object(OBJECT)
object.load # calls #head_object

# Later, if you want...
object.get #calls #get_object
```
This will actually work for your use case. I agree that the semantics can be confusing, so I'll look in to how to best improve/clarify this.

**Comment by sarboc** [comment]
Thanks for that workaround. It's doing fine on my end. Here's another, which I've been using:

```
Aws::S3::Object.new(bucket_name: BUCKET, key: KEY)
```

I imagine this is working for the same reason you stated above - `#get_object` isn't being called on `#load`. I'm definitely not dead in the water here, but wanted to let you know that the method missing error was popping up.

**Comment by trevorrowe** [comment]
I'm going to close this as we don't currently have plans to change the behavior here. Certain resource objects can not be loaded because they are only available from the AWS APIs via enumeration. The `#load` method can not be removed for these resource classes because it is defined in the base class for every resource. That is why they raise NotImplementedError. The actual error could have been a NoMethodError, but that isn't what we are raising today.

We have received similar reports of this being confusing for other resource classes, so it is something we are aware of and are looking into.
