### ISSUE TITLE
Oxidized:SSL_connect returned=1 errno=0 state=SSLv3

### ISSUE THREAD

**Issue by brokerdavelhr** [aws/aws-sdk-ruby#1176]
Sorry if my methods are wrong - newbie here (you probably get that alot)!

Anyway - I have set up LIbrenms to use https only. Now that I have my cert etc done and that up and running, I then tried to install oxidized. All was going well until this step:
root@ubuntu:/opt/librenms# oxidized
I, [2016-05-03T01:07:20.004152 #122586] INFO -- : Oxidized starting, running as pid 122586
F, [2016-05-03T01:07:20.034261 #122586] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I understand both were written with http support mainly, but I needed https.
Is there anyway to point oxidized to where the crt and key are like I did in apache?
SSLEngine on
SSLCertificateFile "/etc/ssl/certs/server.crt"
SSLCertificateKeyFile "/etc/ssl/private/server.key"
?

Sorry if this is a stupid question...still getting used to the finer points in Linux...
I am running Ubuntu 14.04 lte with ruby=>2 etc already installed and running.

**Comment by awood45** [comment]
I'm not sure what this has to do with the SDK off hand - perhaps this was meant for the [Oxidized repo](https://github.com/ytti/oxidized)?

**Comment by awood45** [comment]
Closing this as I'm pretty sure it's unrelated to the SDK. Feel free to add a comment or reopen if one of us missed something about that.
