### ISSUE TITLE
Aws::CloudSearchDomain::Client limits expression size

### ISSUE THREAD

**Issue by joshuasiler** [aws/aws-sdk-ruby#1181]
An undocumented limit of CloudSearch is that expression size (shown here http://docs.aws.amazon.com/cloudsearch/latest/developerguide/limits.html) is limited by half or more of the stated limit when using GET requests. 

Gem should use POST by default, or at least have it as a configurable option. Any expression more than 4500 chars or so using this gem will fail with Aws::CloudSearchDomain::Errors::RequestEntityTooLarge, when the actual limit of the service is over 10K.

**Comment by awood45** [comment]
This is currently defined in the model itself, so default choices would come from that. It would be interesting to explore what it would take to allow configuration of HTTP verbs used by service calls.

**Comment by joshuasiler** [comment]
Is it possible to change the default setting and just use POST across the board?

**Comment by awood45** [comment]
Added to feature request backlog.

**Comment by ali-l** [comment]
It looks like the java sdk implemented POST for CloudSearchDomain search requests. Would a similar implementation work for ruby? https://github.com/aws/aws-sdk-java/blob/fb1d42ee0e00dccf8a3290e04c367989ae5664fc/aws-java-sdk-cloudsearch/src/main/java/com/amazonaws/services/cloudsearchdomain/SwitchToPostHandler.java

**Comment by joshuasiler** [comment]
Yes this is exactly what is needed.

**Comment by alexfarrill** [comment]
+1 for this feature

**Comment by cjyclaire** [comment]
Soft ping, the feature PR has been merged, and will be tagged in today's release : )

**Comment by joshuasiler** [comment]
Great to hear

**Comment by alexfarrill** [comment]
thanks!
