### ISSUE TITLE
Presigned urls expiring before set expires_in timeframe

### ISSUE THREAD

**Issue by darcy** [aws/aws-sdk-ruby#1182]
Hi,

I'm trying to set the expires_in to the maximum of one week, and it seems to create the url fine. However, the url is expiring right around 7hrs instead of the provided option of one week.

I'm using `obj.presigned_url(:get, expires_in: 3600 * 24 * 7)` which creates a url with a correct date in it `X-Amz-Date=20160510T063552Z` and the correct expires window also `X-Amz-Expires=604800` but the url expires right at 6hrs 45mins or so. This is happening consistently for us.

Is there an configuration issue I could be missing with the S3 bucket/object or is this an issue with the presigner?

Thanks in advance.

**Comment by trevorrowe** [comment]
If the x-amz-expires param is correct, then I suspect the credentials you are using to sign the request with are expiring. Are you using session based credentials that have an expiration?

**Comment by darcy** [comment]
Thanks for your response.

I'm using an ec2/beanstalk role with IAM.

When using a specified key/secret (on a user account, not a role) I didn't run into this issue and the expiration works fine. 

Is there something additional I need to set when using an IAM role? I am not clear how the session token is generated for these requests under the hood. Is there an expiration that needs to be set on that token as well that isn't getting set to match the expiration of the signed url?

**Comment by darcy** [comment]
I think I understand the problem a bit more now - the error I was getting was `ExpiredToken`, not that the content/url had expired.

If I am understanding it right, the session tokens provided to IAM via STS seem to have a maximum duration of 36hours, which means that the token will expire before before the URL, effectively making the maximum 36 hours for IAM users - is that correct?

**Comment by trevorrowe** [comment]
Thats correct. The credentials you used to sign the request expire. The presigned URL is valid only as long as the credentials used to sign it. The same thing would happen if you create a presigned URL using root account credentials, and then you rotate your account credentials.

**Comment by darcy** [comment]
Got it, thanks for the further clarification.

So if in normal use an IAM role would not able to set the expiration of the pre-signed URL to over the default session token expiration of 12 hours, then I'm thinking that might be useful to clarify in the documentation. Does the following seem reasonable?

```
      # @option params [Integer] :expires_in (900) Number of seconds before
      #   the pre-signed URL expires. This may not exceed one week (604800
      #   seconds). Note that the pre-signed URL is also only valid as long as the 
      #   credentials used to sign it are. For example, when using IAM roles, 
      #   temporary tokens generated for signing also have a default expiration 
      #   which will affect the effective expiration of the pre-signed URL.
```

**Comment by trevorrowe** [comment]
That looks great. Please submit the PR.

**Comment by trevorrowe** [comment]
Closed by https://github.com/aws/aws-sdk-ruby/pull/1187 -- Thanks @darcy!

**Comment by lssachin** [comment]
this can happen when your local system is behind AWS S3's time
