### ISSUE TITLE
Persisted object_value keys order won't match the order set before persistence

### ISSUE THREAD

**Issue by huoxito** [aws/aws-sdk-ruby#1186]
hi there

Is there any chance a persisted item `object_value` could have the same keys order we set before we persisted the object?

Example:
```ruby
client = Aws::DynamoDB::Client.new
client.create_table(
  table_name: 'local_products',
  key_schema: [
    { attribute_name: 'object_id', key_type: 'HASH' }
  ],
  attribute_definitions: [
    { attribute_name: 'object_id', attribute_type: 'S' }
  ],
  provisioned_throughput: {
    read_capacity_units: 1,
    write_capacity_units: 1
  }
)

item = {'object_id' => BSON::ObjectId.new.to_s, 'object_value' => { 'B' => '1', 'A' => '2' }}
client.put_item table_name: 'local_products', item: item, expected: {}

key_conditions = { object_id: { comparison_operator: 'EQ', attribute_value_list: [item[:object_id]] }}
persisted_item = client.query(table_name: 'local_products', key_conditions: key_conditions).items.first
=> {"object_id"=>"5734bc9b5869638b04080000", "object_value"=>{"A"=>"2", "B"=>"1"}}

item['object_value'].keys === persisted_item['object_value'].keys
=> false
```

I understand that the hash itself is the same in Ruby (item === persisted_item) but wonder if there is any setting / config we could use to ensure the keys order? Or it's just how it is in DynamoDB and we have to set up other data structure to ensure the items order on client side?

**Comment by trevorrowe** [comment]
As far as I know, you can not control the order of attribute value keys. The SDK uses Ruby hashes, which have ordered keys and will preserve the order as they are sent over the wire. The order they are serialized into the HTTP response is controlled by DynamoDB.
