### ISSUE TITLE
 NameError: uninitialized constant DEFAULT_PROVIDER

### ISSUE THREAD

**Issue by psienko** [aws/aws-sdk-ruby#1188]
This error occurs occasionally and appeared after upgrade aws-sdk gem from 2.2 to 2.3.2 version.
I'm using carrierwave-backgrounder gem for processing attachments in the background and uploading these to S3. After repeating the background job this error does not occur and job finish with success.

2016-05-19T07:24:54.424Z 2161 TID-24h5p2 WARN: {"class"=>"CarrierwaveWorker::ProcessWithCacheWorker", "args"=>["MyModel", "107", "file"], "queue"=>"carrierwave", "retry"=>true, "jid"=>"2773a9fbcf207b2c2aaff54f", "created_at"=>1463642664.564233, "enqueued_at"=>1463642664.564284, "error_message"=>"uninitialized constant DEFAULT_PROVIDER", "error_class"=>"NameError", "failed_at"=>1463642694.4118733, "retry_count"=>0}
2016-05-19T07:24:54.424Z 2161 TID-24h5p2 WARN: NameError: uninitialized constant DEFAULT_PROVIDER
2016-05-19T07:24:54.425Z 2161 TID-24h5p2 WARN: /home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:64:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:64:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:199:in `block in resolve_defaults'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:57:in `each'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:57:in `each'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:198:in `resolve_defaults'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:194:in `value_at'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:183:in `block in resolve'
/home/przemek/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
/home/przemek/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:183:in `resolve'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:171:in `apply_defaults'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/configuration.rb:144:in `build!'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/base.rb:68:in `build_config'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/base.rb:19:in `initialize'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-core-2.3.2/lib/seahorse/client/base.rb:105:in `new'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-resources-2.3.2/lib/aws-sdk-resources/resource.rb:169:in `extract_client'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/aws-sdk-resources-2.3.2/lib/aws-sdk-resources/resource.rb:15:in `initialize'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-aws-1.0.0/lib/carrierwave/storage/aws.rb:26:in `new'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-aws-1.0.0/lib/carrierwave/storage/aws.rb:26:in `connection'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-aws-1.0.0/lib/carrierwave/storage/aws.rb:21:in `retrieve!'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:95:in `block in retrieve_from_store!'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:94:in `retrieve_from_store!'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:323:in `uploader'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:159:in `itinerary_photo'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:147:in `itinerary_photo'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave_backgrounder-0.4.2/lib/backgrounder/workers/store_asset.rb:31:in `store_directories'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/carrierwave_backgrounder-0.4.2/lib/backgrounder/workers/store_asset.rb:14:in `perform'
/home/przemek/Workspace/Vamoos/vamoos-backend/app/workers/carrierwave_worker/process_with_cache_worker.rb:8:in `perform'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-superworker-1.2.0/lib/sidekiq/superworker/server/middleware.rb:11:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/przemek/.rvm/gems/ruby-2.2.3@ror4.2.4/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'

**Comment by awood45** [comment]
Looks like an autoloading concurrency issue - temporary workaround would be to add this when you initialize your code:

```ruby
Aws.eager_autoload!
```

We'll take a look.

**Comment by awood45** [comment]
Are you still seeing this? It looks like this was handled in the next version `2.3.3`. It was a threading issue, and we've been cleaning up a few of these. If you cannot upgrade, the workaround above should also fix the issue.

**Comment by psienko** [comment]
I didn't notice this error after adding `Aws.eager_autoload!`. Now, I'm not sure but it seems to me that before I reported this issue I also checked greater versions than 2.3.2 and this problem still existed.
