### ISSUE TITLE
AWS-SDK-v1 EMR resource does not support `release_label`

### ISSUE THREAD

**Issue by bmhatfield** [aws/aws-sdk-ruby#1190]
Hi,

AWS-SDK-v1 and AWS-SDK-v2 under the covers both use the same AWS API revision, but the descriptor for the API in v1 does not have the `release_label` field (see also: https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/api_config/EMR-2009-03-31.yml#L820-L942 )

Is it possible to update the aws-sdk-v1 client to support EMR 4+?

We'd prefer to continue using v1 if at all possible for this, as v2 does not have very strong EMR support (see also: https://github.com/aws/aws-sdk-ruby/issues/1189)

**Comment by awood45** [comment]
As per issue #924 V1 of the SDK is end of life, and we're not making further API updates to it. Happy to work through issues with the V2 experience, but V1 changes are around major bugs or security issues only, should those arise.
