### ISSUE TITLE
Lambda access error when updating VPC Config

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1192]
Updating the vpc config for a function returns an error about not having access to ec2 describe sec groups. I have complete admin access, and double checked by doing a separate describe sec groups. 

```Ruby
new_config = {
          function_name: func_name
      }
new_config[:vpc_config] = {subnet_ids: ["sub-131313"], security_group_ids: ["sg-5613863"]}
lambda.update_function_configuration(new_config)
```

`
Aws::Lambda::Errors::AccessDeniedException - Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSecurityGroups for sg-5613863. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.:
`

**Comment by awood45** [comment]
How are you setting your credentials at client creation time? It's possible that there is an issue with the service, but most commonly this issue would happen because you're not getting the role/user you expect when creating a client.

**Comment by pchaganti** [comment]
The client is being created by passing in the keys to the constructor. Interestingly enough, I can update everything else for a function configuration, including the IAM role. The issue seems to come up only when I try to update the vpc configuration.

thanks!

**Comment by pchaganti** [comment]
Also I can set the vpc configuration to the default Lambda managed vpc without any issue. To do that, I just pass in an empty list of subnet and security group ids. That works just fine. When I try to pass in a list of vpc sec group ids, I always seem to get back the error.

**Comment by pchaganti** [comment]
Does that require a support contract with AWS?

**Comment by awood45** [comment]
I can try to ask on your behalf, however debugging this with them will probably require sharing things that I wouldn't be comfortable posting in a GitHub issue, such as account IDs, access keys.

**Comment by pchaganti** [comment]
I understand. I can certainly provide any info they want over email perhaps if that works.

thanks!

**Comment by awood45** [comment]
I'll reach out to Lambda and see what I can find out about this. You could try posting a wire trace of your call, stripping out sensitive values. To do that, just add `http_wire_trace: true` to your client construction.

**Comment by pchaganti** [comment]
Removed security group id and credential info from this.

```
opening connection to lambda.us-east-1.amazonaws.com:443...
opened
starting SSL for lambda.us-east-1.amazonaws.com:443...
SSL established

<- "PUT /2015-03-31/functions/newnode/configuration HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.3.7 ruby/2.3.0 x86_64-darwin15\r\nX-Amz-Date: 20160523T174650Z\r\nHost: lambda.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: 40ca0a900d03f46da27d12fe528a36a6a6987430b783480977357d39c6dc11\r\nAuthorization: AWS4-HMAC-SHA256 Credential=CREDENTIAL/20160523/us-east-1/lambda/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1c0ec9c00e92d58d5e4f6f00e83e184ccc2d79df88e0ad358d4cf00fb8\r\nContent-Length: 82\r\nAccept: */*\r\n\r\n"

-> "HTTP/1.1 403 Forbidden\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Mon, 23 May 2016 17:46:50 GMT\r\n"
-> "x-amzn-ErrorType: AccessDeniedException:http://internal.amazon.com/coral/com.amazon.coral.service/\r\n"
-> "x-amzn-RequestId: 5413c850-210e-11e6-8a7a-651d6e763795\r\n"
-> "Content-Length: 258\r\n"
-> "Connection: keep-alive\r\n"
-> "\r\n"

reading 258 bytes...

-> "{\"Message\":\"Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSecurityGroups for sg-xxxxxxxx. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.\"}"

read 258 bytes
Conn keep-alive

```

**Comment by awood45** [comment]
I want to dig in a bit more to make sure you have the exact credentials needed for the call you're trying to make. Can you try the following two calls? Two choices, CLI or SDK.

CLI:
```shell
aws ec2 describe-security-groups --group-names sg-5613863 
aws ec2 describe-subnets --subnet-ids sub-131313 
```

SDK:
```ruby
opts = {} # However you construct your clients normally. Region, credentials, etc.
ec2 = Aws::EC2::Client.new(opts)
ec2.describe_security_groups(group_names: ["sg-5613863"])
ec2.describe_subnets(subnet_ids: ["sub-131313"])
```

Let me know what those return.

**Comment by pchaganti** [comment]
When describing sec groups, group_names option will not work, as these are vpc sec groups. I will need to use the group_ids instead. Made the corresponding change in my call. The actual sg and subnet ids have been changed in the log I am attaching.

thanks!



```
opening connection to ec2.us-east-1.amazonaws.com:443...
opened
starting SSL for ec2.us-east-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.3.7 ruby/2.3.0 x86_64-darwin15\r\nX-Amz-Date: 20160525T183519Z\r\nHost: ec2.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: e96826e2714f9df161d6dcd0b68a5c49180b14bae6ddf01a8c53814e803b\r\nAuthorization: AWS4-HMAC-SHA256 Credential=CRED/20160525/us-east-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=c67a547267707792b0cef70b76a3e17056164a887632c82fd2821b35d8dd\r\nContent-Length: 70\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Content-Type: text/xml;charset=UTF-8\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Vary: Accept-Encoding\r\n"
-> "Date: Wed, 25 May 2016 18:35:19 GMT\r\n"
-> "Server: AmazonEC2\r\n"
-> "\r\n"
-> "588\r\n"
reading 1416 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DescribeSecurityGroupsResponse xmlns=\"http://ec2.amazonaws.com/doc/2015-10-01/\">\n    <requestId>8ab187ba-48f4-42bd-a46b-d1eedf6dff05</requestId>\n    <securityGroupInfo>\n        <item>\n            <ownerId>6587193521</ownerId>\n            <groupId>sg-5613863 </groupId>\n            <groupName>default</groupName>\n            <groupDescription>default VPC security group</groupDescription>\n            <vpcId>vpc-16516512</vpcId>\n            <ipPermissions>\n                <item>\n                    <ipProtocol>-1</ipProtocol>\n                    <groups>\n                        <item>\n                            <userId>6587193521</userId>\n                            <groupId>sg-5613863</groupId>\n                        </item>\n                    </groups>\n                    <ipRanges/>\n                    <prefixListIds/>\n                </item>\n            </ipPermissions>\n            <ipPermissionsEgress>\n                <item>\n                    <ipProtocol>-1</ipProtocol>\n                    <groups/>\n                    <ipRanges>\n                        <item>\n                            <cidrIp>0.0.0.0/0</cidrIp>\n                        </item>\n                    </ipRanges>\n                    <prefixListIds/>\n                </item>\n            </ipPermissionsEgress>\n        </item>\n    </securityGroupInfo>\n</DescribeSecurityGroupsResponse>"
read 1416 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn keep-alive
opening connection to ec2.us-east-1.amazonaws.com:443...
opened
starting SSL for ec2.us-east-1.amazonaws.com:443...
SSL established
<- "POST / HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.3.7 ruby/2.3.0 x86_64-darwin15\r\nX-Amz-Date: 20160525T183520Z\r\nHost: ec2.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: ddd69d8825e07164f8394bfc4fa6053298f8642a82f4d0860d59d0bda10f2\r\nAuthorization: AWS4-HMAC-SHA256 Credential=CRED/20160525/us-east-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=d5f12626e9041ed8484b047a27dd2c032eaa34112cad4e8a5d6b163eb01144\r\nContent-Length: 68\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Content-Type: text/xml;charset=UTF-8\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Vary: Accept-Encoding\r\n"
-> "Date: Wed, 25 May 2016 18:35:19 GMT\r\n"
-> "Server: AmazonEC2\r\n"
-> "\r\n"
-> "355\r\n"
reading 853 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DescribeSubnetsResponse xmlns=\"http://ec2.amazonaws.com/doc/2015-10-01/\">\n    <requestId>e090247f-d5c8-440d-be31-a2020e3f306d</requestId>\n    <subnetSet>\n        <item>\n            <subnetId>subnet-131313 </subnetId>\n            <state>available</state>\n            <vpcId>vpc-16516165</vpcId>\n            <cidrBlock>10.0.0.0/24</cidrBlock>\n            <availableIpAddressCount>248</availableIpAddressCount>\n            <availabilityZone>us-east-1e</availabilityZone>\n            <defaultForAz>false</defaultForAz>\n            <mapPublicIpOnLaunch>false</mapPublicIpOnLaunch>\n            <tagSet>\n                <item>\n                    <key>Name</key>\n                    <value>socrates-subnet</value>\n                </item>\n            </tagSet>\n        </item>\n    </subnetSet>\n</DescribeSubnetsResponse>"
read 853 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn keep-alive
```

**Comment by awood45** [comment]
Changing the param is fine - I was mostly interested in seeing if you got 403 errors for either call. I have discussions ongoing with the Lambda and EC2 teams and will let you know as those progress.

**Comment by pchaganti** [comment]
**UPDATE**  Just for testing, updated the role assigned to the function whose vpc configuration is being updated to allow ALL ec2 ops. Still being returned the same access error.

```
{
  "Version": "2012-10-17",
  "Statement": [
  {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:*:*:*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:*"
      ],
      "Resource": "*"
    }
  ]
}
```

**Comment by awood45** [comment]
I've gotten some feedback from the service teams that you have two Lambda IAM roles, one of which has access to "DescribeSecurityGroups" and one that does not. You can email me at alexwood@amazon.com if you want to discuss details on that further.

I do also note your last bit of correspondence as well. Can you give me a request ID for something you ran with that role you pasted above?

**Comment by pchaganti** [comment]
I tried setting the vpc config from the AWS console and I was able to save the changes. I just cant seem to be able to do it via the API, even though I am using the same access keys for the user setting the same config via the API. I will go through and double check everything, and post back.

thanks for your help!

**Comment by pchaganti** [comment]
More debugging. Used the aws-cli as a sanity check. Getting the same error there. So this is definitely not an issue with the aws-sdk-ruby, but an issue with the credentials or how we are calling the API. Will get this tracked down. Closing this issue for now.

thanks again for your help with this!

**Comment by awood45** [comment]
Alright, feel free to comment or reach out by email if you need help
debugging. Checking your IAM Users/Roles is probably the best path from
what I've seen.

**Comment by Maerig** [comment]
Hi, I have the exact same problem using either the CLI or the web interface, and as suggested it doesn't come from the IAM policies for the Lambda function, but those of the user updating its configuration. In particular, there is a restriction on the IP addresses:

```
{
    ...
    "Statement": [
	 ...
        {
            "Effect": "Deny",
            "Action": "*",
            "Resource": "*",
            "Condition": {
                "NotIpAddress": {
                    "aws:SourceIp": [
                        <IP addresses used by the company>
                    ]
                }
            }
        }
    ]
}
```

Maybe you're using a similar policy? In my case, disabling this restriction allows me to update the VPC configuration normally, but I do wish there was a better way.

**Comment by pchaganti** [comment]
Using a similar policy, except that the IAM policy of the user allows * from the sourceIP.
