### ISSUE TITLE
ec2.describe_instances not returning all the instances!

### ISSUE THREAD

**Issue by EslamElHusseiny** [aws/aws-sdk-ruby#1193]
Hi,
I've tried to following snippet 
```
require 'aws-sdk'
client =  Aws::EC2::Client.new(region: 'us-east-1')
client.describe_instances.reservations.size
```
it returns 82 instances whereas the AWS console shows that there are 85 EC2 instances!

Any clue ?

**Comment by EslamElHusseiny** [comment]
my bad!
didn't notice that the reservation might have more than an instance.

**Comment by sjmiller609** [comment]
This one got me too. For the next guy: don't forget to iterate through both Reservations and Instances... don't just grab the first Reservation.
