### ISSUE TITLE
Question: Why is Seahorse in the global/toplevel namespace?

### ISSUE THREAD

**Issue by Kache** [aws/aws-sdk-ruby#1195]
Is there a particular reason Seahorse isn't namespaced inside `AWS`?

I was surprised to find `Seahorse` in my global namespace only to find that it was defined by the AWS SDK.

**Comment by trevorrowe** [comment]
There are legacy reasons why Seahorse is not namespaced under `Aws`.  Changing this now would be a backwards incompatible change.
