### ISSUE TITLE
EC2 Waiters and  Aws::EC2::Errors::InvalidInstanceIDNotFound

### ISSUE THREAD

**Issue by beanieboi** [aws/aws-sdk-ruby#1198]
hey,

first of all. thank you for your hard work, it makes our life much easier! :)

we are currently running this code

```
resp = ec2.run_instances(options)
_instances = resp.instances
_instances_ids = _instances.collect(&:instance_id)
ec2.wait_until(:instance_exists, instance_ids: _instances_ids)
ec2.create_tags({
  resources: _instances_ids,
  tags: [ { key: "billing", value: "infra1" },]
})
```

we frequently see `Aws::EC2::Errors::InvalidInstanceIDNotFound` being raised from the `ec2.create_tags` call.

looking at the waiter documentation, we would expect something like `Errors::FailureStateError`, 
`Errors::TooManyAttemptsError` or `Errors::UnexpectedError` from the waiter, but it's not raising any of those exceptions.

is there anything we can do to prevent that? we are setting a bunch of tags that are related to billing and failing to create the tags results in inaccurate accounting. 

thanks in advance
best,
ben

**Comment by trevorrowe** [comment]
I've run across this problem previously. The `:instance_exists` waiter is describing the instances by id and is getting a valid 200 response from EC2. It appears that EC2 will allow you to describe an instance some time before you are able to tag the instance. It would be helpful if the SDK could provide a `:wait_until_instances_are_taggable` waiter, but I do not know of a way to poll the EC2 API for this state.  Ideally, Amazon EC2 would allow you to provide the tags in the `#run_instances` call. 

You should be able to work around this limitation with a short sleep before the `#create_tags` call.

**Comment by beanieboi** [comment]
hey @trevorrowe 

thanks for the suggestion, i will add a retry logic around the tagging. since tagging is a idempotent operation, this should be save to retry.

it would be really great if there was a way to provide the tags with the `run_instances` call. this would avoid a lot of problems. but i guess this would just move the problem from my code to your code. not sure what the best is to solve this :)

thanks!
ben

**Comment by awood45** [comment]
I think it's fair feedback, and I'll pass it on to the service team.

Closing as it appears the question is answered. Feel free to add on any follow-up questions, or to create a new issue/reopen this if there's more information or concerns.
