### ISSUE TITLE
route53 change_resource_record_sets misleading

### ISSUE THREAD

**Issue by fdr** [aws/aws-sdk-ruby#1203]
It seems the combination of vague error messages from Route53 plus an error in documentation in `#change_resource_record_sets` makes it difficult to use Route53. The problem is `ttl`.

It would be much better one or more of the following were changed:

* the "ttl" presence being checked via schema
* the ruby sdk documentation improved
* route53 giving more informative http responses

Here's what the documentation says at http://docs.aws.amazon.com/sdkforruby/api/Aws/Route53/Client.html#change_resource_record_sets-instance_method:

```
# Request syntax with placeholder values

resp = client.change_resource_record_sets({
  hosted_zone_id: "ResourceId", # required
  change_batch: { # required
    comment: "ResourceDescription",
    changes: [ # required
      {
        action: "CREATE", # required, accepts CREATE, DELETE, UPSERT
        resource_record_set: { # required
          name: "DNSName", # required
          type: "SOA", # required, accepts SOA, A, TXT, NS, CNAME, MX, PTR, SRV, SPF, AAAA
          set_identifier: "ResourceRecordSetIdentifier",
          weight: 1,
          region: "us-east-1", # accepts us-east-1, us-west-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, ap-northeast-2, sa-east-1, cn-north-1
          geo_location: {
            continent_code: "GeoLocationContinentCode",
            country_code: "GeoLocationCountryCode",
            subdivision_code: "GeoLocationSubdivisionCode",
          },
          failover: "PRIMARY", # accepts PRIMARY, SECONDARY
          ttl: 1,
          resource_records: [
            {
              value: "RData", # required
            },
          ],
          alias_target: {
            hosted_zone_id: "ResourceId", # required
            dns_name: "DNSName", # required
            evaluate_target_health: false, # required
          },
          health_check_id: "HealthCheckId",
          traffic_policy_instance_id: "TrafficPolicyInstanceId",
        },
      },
    ],
  },
}
```

Note here `ttl: 1`, as it has no "# ...required..." like other required fields.  I read this as a non-required default.  However, without ttl explicitly set, I get an opaque error message. The only way I figured it out was by running `list_resource_record_sets` and noticing that TTL was the one non-nil value on default Route53 records/some examples I created in the console.  I show examples of broken and non-broken pseudo-input below.

```ruby
> f.rgn.r53.change_resource_record_sets(
   hosted_zone_id: 'ABCDEFGHIJKLMN',
   change_batch: {
     changes:
     [
       {
         action: 'CREATE',
         resource_record_set: {
           name: 'subdomain.example.com.',
           type: 'A',
           resource_records: [{ value: '127.0.0.1' }]
         }
       }
     ]
   }
 )

Aws::Route53::Errors::InvalidInput: Invalid request
from /home/fdr/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.11/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'

> _ex_.context.http_response.body.read
=> "<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>baa4dfe7-2d11-11e6-92d1-7bfd9211bc4d</RequestId></ErrorResponse>"
```

Adding the ttl makes everything work as expected:

```ruby
> f.rgn.r53.change_resource_record_sets(
   hosted_zone_id: 'ABCDEFGHIJKLMN',
   change_batch: {
     changes:
     [
       {
         action: 'CREATE',
         resource_record_set: {
           name: 'subdomain.example.com.',
           type: 'A',
           ttl: 300,
           resource_records: [{ value: '127.0.0.1' }]
         }
       }
     ]
   }
 )

=> #<struct Aws::Route53::Types::ChangeResourceRecordSetsResponse
 change_info=#<struct Aws::Route53::Types::ChangeInfo id="/change/OPQRSTUVWXY", status="PENDING", submitted_at=2016-06-08 00:43:32 UTC, comment=nil>
```

**Comment by awood45** [comment]
I understand the frustration with the fact that this API is large and has multiple use cases. I would agree that example beyond the auto-gen stubs in the docs would be especially helpful for this API.

One note is that `:ttl` cannot be marked as required, because it should be omitted for ALIAS records: [Relevant Documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/Route53/Types/ResourceRecordSet.html#ttl-instance_method).

**Comment by Doug-AWS** [comment]
I talked to the doc writer and he is going to update the docs to add more info that should help.

**Comment by trevorrowe** [comment]
I'm going to close this issue against the SDK. We consume the API reference documentation from Route53 when building SDK docs. Once the source docs have been updated, this will trickle into the SDK docs.
