### ISSUE TITLE
SQS::QueuePoller stopped polling

### ISSUE THREAD

**Issue by sarge** [aws/aws-sdk-ruby#1205]
Hi there,

I noticed a situation where the QueuePoller stopped polling. This occurred during the recent EC2 outage in sydney (the service was hosted in the US but polling SQS in Sydney).

Our system polls queues in various regions, inside a ruby process. Each poller is running in a separate thread.

```ruby
        poller = Aws::SQS::QueuePoller.new(queue[:url], { client: sqs })

        poller.before_request do |stats|
          logger.info("region: #{queue[:region]} requests: #{stats.request_count} - messages: #{stats.received_message_count} - last-timestamp: #{stats.last_message_received_at}")
        end

        poller.poll do |msg|
             begin
              process_message(msg, queue)
            rescue Exception => ex
              logger.error msg.inspect
              logger.error ex
              throw :skip_delete
            end
        end
```

The process message function puts the data in dynamodb.

The behaviour I was was that the messages on the sydney sqs queues were not being processed, all other regions were fine.

Restarting the process fixed the issue, messages were processed.

It is hard to say exactly what state the poller was in, but I would like to have the poller fix itself in these rare situations. 

The solution I am considering is to add a timeout inside the poll block.

```ruby

timedout = false

      sqs = Aws::SQS::Client.new(region: queue[:region])
      poller = Aws::SQS::QueuePoller.new(queue[:url], { client: sqs })

      poller.before_request do |stats|
        throw :stop_polling if timedout
        logger.info("region: #{queue[:region]} requests: #{stats.request_count} - messages: #{stats.received_message_count} - last-timestamp: #{stats.last_message_received_at}")
      end

      poller.poll do |msg|

        begin
          Timeout::timeout(10) {
            logger.info "processing..."
            # sleep 15
            process_message(msg, queue)
          }
        rescue Timeout::Error => ex
          logger.error msg.inspect
          logger.error ex
          timedout = true
          throw :skip_delete
        rescue Exception => ex
          logger.error msg.inspect
          logger.error ex
          throw :skip_delete
        end

      end

```

Or should this be something that the poller should be responsible for?

**Comment by awood45** [comment]
The [QueuePoller](http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/QueuePoller.html) class does provide the `:idle_timeout` option, which appears to handle your intended behavior. Is that sufficient?

**Comment by sarge** [comment]
The idle timeout as I understand it supports stopping polling if there are no more messages.

My situation is that polling or processing has stopped processing. Possibly due to something being hung inside the poll method, which my proposed code I think will fix. 

Or inside the poller internally which I have just realized my code won't fix.

Could this block indefinitely?
https://github.com/aws/aws-sdk-ruby/blob/ef9f2d3655c4bacb3adff580a6b295df510f78fe/aws-sdk-resources/lib/aws-sdk-resources/services/sqs/queue_poller.rb#L390

**Comment by awood45** [comment]
I get what you're saying, we're on the same page now. Looking in to it.

**Comment by awood45** [comment]
It's really hard to say without seeing the nature of the exceptions you got - which I can understand you may not have. Short answer is that shouldn't be able to block infinitely, though it could block for a while (a couple retry layers exist).

**Comment by sarge** [comment]
I understand, the network does throw a lot of non determinism into the equation. 

On the assumption that poll cannot block. I will test for a possible timeout from the message processing block. If it hangs again I will reopen.

Revised example

```ruby

 sqs = Aws::SQS::Client.new(region: queue[:region])
      poller = Aws::SQS::QueuePoller.new(queue[:url], { client: sqs })

      poller.before_request do |stats|
        logger.info("region: #{queue[:region]} requests: #{stats.request_count} - messages: #{stats.received_message_count} - last-timestamp: #{stats.last_message_received_at}")
      end

      poller.poll do |msg|

        begin
          Timeout::timeout(10) {
            logger.info "processing..."
            # sleep 15
            process_message(msg, queue)
          }
        rescue Timeout::Error => ex
          logger.error msg.inspect
          logger.error ex
          throw :skip_delete
        rescue Exception => ex
          logger.error msg.inspect
          logger.error ex
          throw :skip_delete
        end

      end

```

**Comment by awood45** [comment]
Absolutely, feel free to reopen if you have more information!

**Comment by vjagetiya-jeavio** [comment]
I am polling SQS using Aws::SQS::QueuePoller... and have poller written in config/initialiser.. when we run it locally on Puma server it works fine and on any message on Queue is processed. While when we run the same code on the Passenger server it work on initialisation but later it stops polling and is not able to poll/process any message received further once server is up.

poller = Aws::SQS::QueuePoller.new(queue_url)
    poller.poll do |msg|
      puts msg.body
        message = JSON.parse(msg.body)
          process_data(message)
        end
    end
