### ISSUE TITLE
Aws::S3::Errors::SignatureDoesNotMatch on list_objects

### ISSUE THREAD

**Issue by nickfrandsen** [aws/aws-sdk-ruby#1209]
I can't seem to list the bucket objects. It's complaining of SignatureDoesNotMatch 100% of the time. 

```
Aws.config.update({
  region: 'us-east-1',
  credentials: Aws::Credentials.new('my_akid', 'my_secret')
})

s3 = Aws::S3::Client.new
resp = s3.list_objects(bucket: 'bcteam-1b299a00-4ea3-2f92-b048-03f6ca07e7f0/15_minute_data')
```

Then it always returns

```
Aws::S3::Errors::SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/jessicabrown/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.12/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from (irb):35
```

One thing to note (not sure if useful or not). The secret contains a '+' (have seen that that is an issue for the aws-cli https://github.com/aws/aws-cli/issues/602).

Is anyone else experiencing this? Any ideas?

Thanks in advance!

**Comment by Doug-AWS** [comment]
I don't see any issue in your code. You might try using the console to create a new access key and secret access key (services, IAM, select the user, user action->manage access keys, create new access keys). I recommend saving them in your HOME/.aws/credentials file so you don't have the values in any source file, even by accident, as some day you might forget and expose the values. See http://docs.aws.amazon.com/sdk-for-ruby/latest/DeveloperGuide/aws-ruby-sdk-getting-started.html for more info.

**Comment by nickfrandsen** [comment]
I can connect to my own S3 account perfectly fine so I'm not saying that the ruby client isn't working but for some reason this particular clients S3 isn't working. I am wondering if it perhaps could be due to them having a forward slash in the bucket? It's allowed on us-east-1 but I can't think of what else it could be. Does anyone know why this particular bucket would fail with a signature error?

**Comment by Doug-AWS** [comment]
There's a known issue with us-east allowing bucket names that pose problems. See http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html. TL:DR => "bucket names can contain any combination of uppercase letters, lowercase letters, numbers, periods (.), hyphens (-), and underscores (_)". Note the absence of forward slash.

**Comment by awood45** [comment]
I'm able to recreate the signature issue with a bucket with slashed names (for e.g., `foo/bar`). Trivial recreation example:

```ruby
client = Aws::S3::Client.new
client.create_bucket(bucket: "awood45/foo/bar") # Raises 403 SignatureDoesNotMatch exception
```

Incidentally, the same issue exists for 'us-east-1' and 'us-west-2', so I do not believe this is region-dependent.

**Comment by awood45** [comment]
At this point, looking at this as a possible bug in the signer. Possibly URL encoding? Will take a look.

**Comment by trevorrowe** [comment]
@nickfrandsen Try removing the forward slash section from the bucket name and move it to the prefix:

```ruby
Aws.config.update({
  region: 'us-east-1',
  credentials: Aws::Credentials.new('my_akid', 'my_secret')
})

s3 = Aws::S3::Client.new
resp = s3.list_objects(bucket: 'bcteam-1b299a00-4ea3-2f92-b048-03f6ca07e7f0', prefix:'15_minute_data')
```

Bucket names are never permitted to contain a forward slash. Everything after the slash is actually part of the object key(s).

**Comment by awood45** [comment]
I think I can also see why you're getting the error you're getting - given that S3's different commands are, at times, aliases to different REST queries against the endpoint, it could treat a POST to /foo/bar as a malformed put object to bucket 'foo' of the key 'bar'. Or so it appears from an early investigation.

**Comment by trevorrowe** [comment]
I reproduced this issue locally and confirmed it is an issue with the forward slash in the bucket name. I've added code to raise a helpful error message in this scenario.

**Comment by nickfrandsen** [comment]
Thanks guys! 

Using 
```
resp = s3.list_objects(bucket: 'bcteam-1b299a00-4ea3-2f92-b048-03f6ca07e7f0', prefix:'15_minute_data')
```
Fixed my particular issue but probably a good idea with a helpful error message. 

Cheers
