### ISSUE TITLE
Create single instance environment on ElasticBeanstalk

### ISSUE THREAD

**Issue by thiagofelix** [aws/aws-sdk-ruby#1210]
Apparently it is not possible to [create single instance environment](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-types.html)

The EB CLI has the option [--single](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html) which makes me thing that somehow the REST API accept that param but it is just not exposed here.

Thanks!

**Comment by awood45** [comment]
I'll admit I'm a bit unfamiliar with some of this. Can you give me an example of the command you're trying to create, and where you feel like something is missing? If the EB CLI can do it, there should be a mapping with the API.

**Comment by thiagofelix** [comment]
After some research I found that the EB CLI that I mentioned is the [awsebcli](https://pypi.python.org/pypi/awsebcli/3.7.6). Which I believe might not mirror the AWS API based on this section on [EB documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html):
> Previously, Elastic Beanstalk supported a separate CLI that provided direct access to API operations called the Elastic Beanstalk API CLI. This has been replaced with the AWS CLI, which provides the same functionality but for all AWS services' APIs.

**Comment by awood45** [comment]
Anything the AWS CLI can do, the SDK can do as well. It's written over the same REST API description.

**Comment by awood45** [comment]
What is likely is that the `--single` parameter in the EB CLI is an alias for a package of parameters merged in to the resulting API call to the service itself, rather than a particular parameter itself. That's a good place to start looking, and I'm digging through the docs as well.

**Comment by thiagofelix** [comment]
In practice when you use `--single` in the EB CLI it doesn't create a load balancer for you environment
![image](https://cloud.githubusercontent.com/assets/117622/15978715/5958ad8a-2f36-11e6-8cb1-7fed12ab16fe.png)

I think what I am trying to understand is if it is possible to reproduce the same "Environment Type" with the `aws-cli` or the `aws-sdk-ruby`?

**Comment by awood45** [comment]
I'm sure it's possible, it's just a question of which API parameters need to be set. I'm going to try and get a hold of that team, or find the EB CLI's source code.

**Comment by awood45** [comment]
I think I found what you're looking for. The Elastic Beanstalk team keeps a list of option settings in their [documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkenvironment).

So, in the `#create_environment` call, you'd include the following in your options hash:

```ruby
opts = {
  # Other parameters relevant to your environment...
  option_settings: [
    {
      namespace: "aws:elasticbeanstalk:environment",
      option_name: "EnvironmentType",
      value: "SingleInstance"
    }
  ]
}
```

That is the relevant setting for what you're trying to do. I've passed this on as feedback to the Beanstalk team as well, to see if they can add a relevant example.

**Comment by awood45** [comment]
That should answer your question, feel free to follow up if you have any additional questions or issues. Thanks!

**Comment by thiagofelix** [comment]
Awesome.
Thanks @awood45, fantastic work!
