### ISSUE TITLE
List subscriptions for a specific endpoint ARN?

### ISSUE THREAD

**Issue by ecnepsnai** [aws/aws-sdk-ruby#1217]
Given the endpoint ARN, say for a specific APN token, how can I list the the topics that it is subscribed to?

I was hoping to do something like:

```ruby
response = @client.list_subscriptions({
    endpoint_arn: endpoint_arn
})
```

**Comment by trevorrowe** [comment]
Looking at the API reference documentation, it looks like you can list all subscriptions, or list them by topic arn:

* [#list_subscriptions](http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html#list_subscriptions-instance_method)
* [#list_subscriptions_by_topic](http://docs.aws.amazon.com/sdkforruby/api/Aws/SNS/Client.html#list_subscriptions_by_topic-instance_method)

**Comment by ecnepsnai** [comment]
Sorry I probably should've explained my structure before asking this question:

The app is a local transit app, and I would use SNS for service notifications.  For each service & severity of alert I have a topic, for example:

- bus_major
- bus_minor
- train_major
- train_minor

These topics are fixed, I.E.: I created then in the AWS control panel and not pragmatically.

Users can filter which service and severity they receive notifications for, but what I would like is to be able to query SNS to see which services & severities they are receiving so I don't have to rely on a local copy (which I can keep locally)

I could list all subscriptions then just map reduce them to the specific endpoint ARN, but that would be quick wasteful both on our side and mine.

Perhaps there is another way?  Or perhaps there is a better structure than what I am using right now?

**Comment by trevorrowe** [comment]
If the list of possible subscriptions is either large or unbounded, then listing all subscriptions to simply filter client-side would be a poor solution. I'm not extremely familiar with the SNS API, but I do know the SDK represents all of the possible inputs and outputs for the service. You may need to keep an index of subscriptions in your application or in another data source (such as DynamoDB).

**Comment by trevorrowe** [comment]
I'm going to close this question, as it does not appear to be an issue with the SDK. Please feel free to re-open if needed.
