### ISSUE TITLE
Support for KMS Key on encrypted EBS ephemeral disk

### ISSUE THREAD

**Issue by ljfranklin** [aws/aws-sdk-ruby#1219]
Hi all,

Just wondering whether it would be possible to add support for `block_device_mappings[].ebs.kms_key_id` in the `run_instances` call as you can with the `create_volume` call in the SDK. This option also seems to be missing from the AWS Console UI, so I understand if this is a server-side limitation.

Thanks!

- Lyle && Forrest, Pivotal Cloud Foundry

**Comment by trevorrowe** [comment]
Thanks for the feature request. You are correct, this is a service limitation. We update the SDK with each new service feature, so you can be certain if this functionality is added it will be made available through the SDK.

**Comment by palexvs** [comment]
Has this feature already added? It seems like I can't run new instances without it, I get error message "State transition reason: Server.InternalError: Internal error on launch" each time
