### ISSUE TITLE
Call to authorize_security_group_ingress does not accept source_security_group_id as a parameter

### ISSUE THREAD

**Issue by danhigham** [aws/aws-sdk-ruby#1220]
http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/SecurityGroup.html#authorize_ingress-instance_method suggests that you can specify the name of the source security group, when doing so I see the message "Aws::EC2::Errors::InvalidParameterValue: Invalid value 'xxxxxxx' for groupName. You may not reference Amazon VPC security groups by name." 

If I try and specify "source_security_group_id", I see 'ArgumentError: unexpected value at params[:source_security_group_id]'

**Comment by trevorrowe** [comment]
The AWS SDK for Ruby documentation for API operations are pulled directly from the service API docs. http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html 

It appears that specifying a source security group by name is only supported for EC2 classic (which is non-vpc) and for the default VPC in an account.

I think you will need to use the `:ip_permissions` option:

```ruby
resp = client.authorize_security_group_ingress({
  group_id: "...",
  # ...
  ip_permissions: [
    {
      user_id_group_pairs: [
        {
          group_id: "....",
          # ...
        }
      ],
    },
  ],
})
```

Hope this helps.

**Comment by jkiran307** [comment]
Hi trevorrowe,

This really helped me.

Regards,
Kiran307
