### ISSUE TITLE
Unhelpful error thrown by snapshot.wait_until_completion when request limit exceeded

### ISSUE THREAD

**Issue by griffint61** [aws/aws-sdk-ruby#1221]
Calling Aws::EC2::Snapshot#wait_until_completed throws Aws::Waiters::Errors::UnexpectedError when encountering an API Request Limit Exceeded condition. It should either (1) throw something more helpful, say Aws::EC2::Errors::RequestLimitExceeded, or (2) just retry after sleeping since the caller has already committed itself to waiting anyway.

**Comment by trevorrowe** [comment]
Throttling errors are already being retried inside the waiter. By default, every client request is retried up to three times. You can increase this limit if you are being throttled. These retries happen with exponential backoff (e.g. 0.3, 0.6, 1.2, seconds etc). 

```ruby
ec2 = Aws::EC2::Client.new(retry_limit: 6)
```

Unexpected errors returned by the service (after retries are exhausted for a single request) will stop the waiter from polling and will be wrapped in an `Aws::Waiters::Errors::UnexpectedErrror`. You can access the original error by calling `#error` on this object.

http://docs.aws.amazon.com/sdkforruby/api/Aws/Waiters/Errors/UnexpectedError.html

Hope this help.
