### ISSUE TITLE
APNS with loc-args

### ISSUE THREAD

**Issue by MaslovAnton** [aws/aws-sdk-ruby#1224]
Send this message 
{'APNS_SANDBOX' => { 'aps'=>{ 'alert'=> {"body": "hello world!", "loc-args": ["andy"], "loc-key": "FOLLOWER" } } }, 'default' => 'message'  } amazon return Aws::SNS::Errors::InvalidParameter: Invalid parameter: Message Structure - Failed to parse JSON

How send in loc-arg array? If i send empty array or string then all OK.

**Comment by awood45** [comment]
Can you show me the exact code you're using to call SNS? The hash above mixes Ruby hashrocket syntax with JSON hash syntax, so it's hard to tell where the error is coming from.

**Comment by awood45** [comment]
Haven't heard back, can you show me the code you're using, or a similar piece of code to reproduce your error?

**Comment by awood45** [comment]
Closing - feel free to reopen if you have more information.
