### ISSUE TITLE
Codedeploy 

### ISSUE THREAD

**Issue by adityajain21** [aws/aws-sdk-ruby#1225]
I wanted to deploy a peice of code.
Can I invoke code deploy from inside the instance?

**Comment by awood45** [comment]
You can absolutely call any API from an EC2 instance. A best practice for this would be to have an IAM role for the instance which gives you the permissions you need to make the API calls that you need to make.

The SDKs (Ruby and the others) will look for credentials from the EC2 Instance Metadata service, so [credentials configured in this manner](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) will be picked up automatically.

Does this cover what you need?

**Comment by adityajain21** [comment]
I need to use a command which will trigger a code deploy, and use that command from inside the EC2 instance(I am logged into the instance). Is it possible?

**Comment by awood45** [comment]
That's possible so long as the EC2 instance has routing/security group permissions to hit the CodeDeploy API endpoint, and you have credentials configured.

Are you trying to run a particular piece of code and having problems, or looking for advice to get started?

**Comment by awood45** [comment]
[The SDK documentation](http://docs.aws.amazon.com/sdkforruby/api/index.html#Configuration_Options) goes through configuration options for getting credentials for your client, including from EC2 Instance Metadata. Closing, feel free to add on any follow-up questions you have.
