### ISSUE TITLE
Documentation: Aws::S3::Object#storage_class possible values list inaccurate

### ISSUE THREAD

**Issue by dtakahas** [aws/aws-sdk-ruby#1227]
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#storage_class-instance_method lists possible return values of 

-     STANDARD
-     REDUCED_REDUNDANCY
-     STANDARD_IA

and does not include `GLACIER` which also seems to be a possible return value using `aws-sdk-core v. 2.2.37`. Tested from a Rails console on an object that had been moved to glacier storage via object lifecycle prefix config.

**Comment by awood45** [comment]
Thanks for raising this, will check with the doc team.

**Comment by trevorrowe** [comment]
I did some digging into this. The modeled enumeration is correct. If you HEAD and object it will not return a storage class of GLACIER. You may not specify this either when making a PUT Object call. This is only valid when configuring a transition lifecycle policy. Once the object has transitioned to glacier, you will not be able to HEAD the object, unless you restore from glacier first. During restoration it will receive one of the storage classes above.

Hope this helps.
