### ISSUE TITLE
Random uninitialized constant errors with multiple threads

### ISSUE THREAD

**Issue by abhi-patel** [aws/aws-sdk-ruby#1229]
I am trying to use DynamoDb Parallel scan with multiple threads. For past few days, Its throwing random uninitialized constant errors.

On digging more, I found a possible work around to use Aws.eager_load! 

Have added that in an initializer as  (config/initializers/aws.rb)

```
Rails.application.config.before_eager_load do
  Aws.eager_autoload!(services: %w(S3 DynamoDB))
end
```

Still its throwing exceptions. 
below are the 2 most frequent exceptions
```
  1) uninitialized constant Aws::Plugins::UserAgent::Handler::VERSION
  /usr/local/rvm/gems/ruby-2.3.0@abc_gemset/gems/aws-sdk-core-2.3.2/lib/aws-sdk-core/plugins/user_agent.rb:16:in `set_user_agent'
```

and 

```
2) uninitialized constant Seahorse::Client::Http::Request
  /usr/local/rvm/gems/ruby-2.3.0@abc_gemset/gems/aws-sdk-core-2.3.2/lib/seahorse/client/request_context.rb:20:in `initialize'
```

I think its related to autoload not being threadsafe.

**Comment by awood45** [comment]
Looking at this as a probable bug. You're likely correct about the nature of the bug as well, and we've made fixes to similar issues recently.

A full `Aws.eager_autoload!` should serve as a workaround if needed in the meantime.

**Comment by trevorrowe** [comment]
Still looking at this, but I'm not sure its a bug. Locally I can verify that VERSION is being loaded when calling `.eager_autoload!` with or without a service filter. @abhi-patel Are you confident that `.eager_autoload!` is being called prior to entering concurrency? Also, are those two common errors the same after calling eager autoload or do the constants that cause errors change?

Its worth noting that we are investigating removing the use of autoload completely from the SDK. It may happen in stages. The first thing we would need to do is modularize the SDK into service specific gems.

**Comment by abhi-patel** [comment]
@awood45 : Wouldn't it be too much to load on startup by adding `Aws.eager_autoload!` considering we need s3 and Dynamodb only.

@trevorrowe 
Have added .eager_autoload! in initializer and have checked that its requiring correct files. 

There is one more such error
```
1) uninitialized constant Aws::Json::Handler::Parser
  /usr/local/rvm/gems/ruby-2.3.0@abc_gemset/gems/aws-sdk-core-2.3.2/lib/aws-sdk-core/json/handler.rb:44:in `parse_body'
```

One more point I am not able to get is `Aws::Plugins::UserAgent::Handler::VERSION` should resolve to `Aws::VERSION` according to rails autoload mechanism, Any Idea why its not being found correctly?

**Comment by awood45** [comment]
Can try to reproduce, but it would be strange if this is happening despite `Aws.eager_autoload!` being run ahead of entering concurrency. If it was run after threads had been generated, then the error is possible.

I did check and you shouldn't be having a problem with the partial autoload.

**Comment by ge1st** [comment]
Hi guys, I just wanted to notify you that I saw similar behavior using the latest of the Version 1 line. I was also using multiple threads. Adding `eager_autoload!` to my `initialize` looks to have corrected it.

**Comment by abhi-patel** [comment]
Opps. My bad. The issue is solved now. Basically [Resque](https://github.com/resque/resque) does not run before_eager_load hooks on setup and hence AWS eager load was not working for resque workers.

The same code was working fine for web/console requests, but was randomly failing for resque workers.
Have opened a pull request for the same. resque/resque#1481
