### ISSUE TITLE
Higher UTF-8 characters cause Aws::S3::Errors::SignatureDoesNotMatch for Content-Disposition

### ISSUE THREAD

**Issue by csuhta** [aws/aws-sdk-ruby#1230]
In aws-sdk 2.3.19, `Aws::S3::Client#put_object`, `Aws::S3::Object#copy_from`, `copy_to`, and friends fail to sign requests correctly when you have a `Content-Disposition` header that contains UTF-8 characters outside of the ASCII-ish ranges. Sample code:

``` ruby
client = Aws::S3::Client.new({
  region: "us-east-1",
  access_key_id: "YOUR_ID",
  secret_access_key: "YOUR_KEY",
})

client.put_object({
  bucket: "your-bucket",
  key: "test-object",
  content_disposition: %{attachment; filename="😬.pdf"},
  body: nil,
})

# Aws::S3::Errors::SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
# from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/seahorse/client/plugins/response_target.rb:21:in `call'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/seahorse/client/request.rb:70:in `send_request'
#   from /Users/You/.gem/ruby/2.3.1/gems/aws-sdk-core-2.3.19/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
#   from (irb):18
```

I'm aware that putting non-ASCII in Content-Disposition headers might cause strange browser behavior. The emoji above is a somewhat more extreme example. The original character I discovered this issue with was `í`. 

This is on Ruby 2.3.1 and OS X 10.11.15. I'm happy to get additional information if needed. 🤔

**Comment by awood45** [comment]
I am able to recreate this, checking if this is an invalid input or if we should be able to handle it.

**Comment by trevorrowe** [comment]
We are still investigating this issue for now. As a work-around, I was able to send that failing request by URI encoding filename in the example above. Some browsers, like Chrome, automatically decode the filename when downloading the object. Other browsers, like Safari, appear not to. I haven't tested other browsers.

**Comment by csuhta** [comment]
The RFCs are really vague about this header (surprising absolutely no-one). No mention is made about percent-encoding though.

My workaround so far has been to transliterate characters: removing accents and replacing emoji with substitutes, etc.

**Comment by trevorrowe** [comment]
There has been some ongoing discussion. In short this is a limitation of signature version 4 and header values. There isn't anything that can be done in the SDK. The best work-arounds are url encoding the values, or transliterating/pruning non-ascii characters. I'll be sure to update this issue if we hear anything else.

**Comment by janko** [comment]
For future reference, there is now a [content_disposition](https://github.com/shrinerb/content_disposition) gem that correctly formats the value for the `Content-Disposition` header. Having UTF-8 characters in the `Content-Disposition` header is not allowed anyway according to the HTTP spec, and this gem correctly escapes them, and adds both `filename` (ASCII) and `filename*` (UTF-8) media parameters:

```rb
require "content_disposition"
ContentDisposition.attachment("😬.pdf")
# => "attachment; filename=\"%3F.pdf\"; filename*=UTF-8''%F0%9F%98%AC.pdf"
```
