### ISSUE TITLE
SWF concurrent workflows

### ISSUE THREAD

**Issue by adityajain21** [aws/aws-sdk-ruby#1231]
Is there a way we can execute several workflows concurrently? I want to run a set of tasks repeatedly and in isolation from every other set of task.

One way I can think of it is, if we can execute workflows concurrently, then I will assign those tasks inside a workflow and run those workflows concurrently (100-200 workflows at one time, each having the same tasks).
Other thing which I thought could help, is creating tasks dynamically, but the whole set of tasks (A->B->C) should execute in isolation. (Task A occurs, initiates task B and creates another task A, but every flow starting with task A should occur in isolation with other tasks)

Is there a way we can do this?
I would ideally love to do the first thing. While trying, whenever I initiate a new workflow, it only starts execution after the previous workflow has completed.

**Comment by awood45** [comment]
You can execute concurrent workflows with SWF, check out their [documentation](http://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dg-intro-to-swf.html). I'm not an expert on SWF itself, so if you get stuck you can also reach out to them via support or perhaps the AWS forums.

If you have questions about SDK interaction with SWF, feel free to follow up with those questions.
