### ISSUE TITLE
Missing documentation for `S3::Client::get_bucket_replication_configuration()` method

### ISSUE THREAD

**Issue by arimbun** [aws/aws-sdk-ruby#1235]
Ruby AWS SDK V2.

According to the documentation for `get_bucket_replication()`

```
Deprecated, see the GetBucketReplicationConfiguration operation.
```

However, `get_bucket_replication_configuration()` does not seem to exist.

**Comment by awood45** [comment]
I'll reach out to the S3 doc team to check the documentation consistency. Thanks for the report!

**Comment by trevorrowe** [comment]
This has been resolved up-stream now. The docs will be corrected on our next release.
