### ISSUE TITLE
undefined method `match' for nil:NilClass (NoMethodError) when opening encryptionClient

### ISSUE THREAD

**Issue by blondowski** [aws/aws-sdk-ruby#1240]
1. Install

gem install aws-sdk
Successfully installed aws-sdk-2.3.21
Parsing documentation for aws-sdk-2.3.21
Done installing documentation for aws-sdk after 0 seconds
1 gem installed

2. code
more DS3.rb 
require 'aws-sdk'
require 'openssl'

key = OpenSSL::PKey::RSA.new(1024)
s3 = Aws::S3::Encryption::Client.new(encryption_key: key)

3. execute
ruby DS3.rb 
/usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:70:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:57:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:57:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:200:in `value_at'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:189:in `block in resolve'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:189:in `resolve'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/configuration.rb:150:in `build!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/base.rb:68:in `build_config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/base.rb:19:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.21/lib/seahorse/client/base.rb:105:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.3.21/lib/aws-sdk-resources/services/s3/encryption/client.rb:298:in `extract_client'
	from /usr/local/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.3.21/lib/aws-sdk-resources/services/s3/encryption/client.rb:221:in `initialize'
	from DS3.rb:5:in `new'
	from DS3.rb:5:in `<main>'

**Comment by awood45** [comment]
Related to #1237

This means you haven't configured a region. To configure a region, set the `AWS_REGION` environment variable, or pass it in as a parameter. For example:

```ruby
key = OpenSSL::PKey::RSA.new(1024)
s3 = Aws::S3::Encryption::Client.new(encryption_key: key, region: "us-east-1") # or the region you are using
```

**Comment by blondowski** [comment]
Thanks a a lot.  Didn't see that in the documentation.

Daniel Blondowski

Big Data Architecture/Engineering
DHI Group, Inc.

dan.blondowski@dice.com
515-313-2137

**Comment by awood45** [comment]
It's an unhelpful error that I'm aiming to fix, though it's something I can't consistently reproduce either so it's been slightly elusive. Sorry about the unhelpful error message.
