### ISSUE TITLE
syntax error using aws-sdk-resources-2.3.22

### ISSUE THREAD

**Issue by dpmanoso** [aws/aws-sdk-ruby#1244]
Hello, I'm trying to create a custom puppet fact using aws ruby sdk version 2 but I'm having the following error

`Error loading fact /var/lib/puppet/lib/facter/spot_instance0.rb: /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources.rb:29: syntax error, unexpected ':', expecting ')'
...file(definition), source_path: definition)
                              ^
/usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources.rb:69: odd number list for Hash
            resource_class: EC2::Instance,
                           ^`

`/usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources.rb:69: syntax error, unexpected ':', expecting '}'
            resource_class: EC2::Instance,
                           ^
/usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources.rb:70: syntax error, unexpected ':', expecting '='
            deprecated_name: deprecated_name,
                            ^ ...`

Here is my gem list 

*** LOCAL GEMS ***

aws-sdk (2.3.22)
aws-sdk-core (2.3.22)
aws-sdk-resources (2.3.22)
bigdecimal (1.2.8)
bundler (1.12.5)
bundler-unload (1.0.2)
did_you_mean (1.0.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.5)
jmespath (1.3.0)
json (1.8.3)
mini_portile2 (2.1.0)
minitest (5.8.3)
net-telnet (0.1.1)
nokogiri (1.6.8)
pkg-config (1.1.7)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)

**Comment by awood45** [comment]
I think there's missing context here, because I don't see syntax errors in the Resources code itself. Do you have any context about the code calling this, or reproduction steps for the `aws-sdk-resources` gem?

**Comment by trevorrowe** [comment]
I am unable to reproduce this error using v2.3.22 of the SDK or the most recent v2.4.0. Have you been able to resolve this issue?

**Comment by dpmanoso** [comment]
Hello, thank you for your time. Tried using `aws-sdk (1.40.3)` and my custom puppet fact now works fine. Though I'm not really sure why does it says syntax in `aws-sdk-resources` gem

**Comment by trevorrowe** [comment]
Thanks for the update.
