### ISSUE TITLE
search s3 files (glob pattern)

### ISSUE THREAD

**Issue by nqtien310** [aws/aws-sdk-ruby#1245]
Hi, 

I'm working on a command line that will download S3 files by giving a Glob pattern
`fetch-s3 "/path/to/**/*.gz"`

I'm planning on using aws cli for this task but I wonder if it's feasible with our library ?

**Comment by awood45** [comment]
It's absolutely feasible, though you have to use a couple steps. For a command line tool, you probably want to look at libraries like `optparser` to cleanly handle arguments.

For your use case, keep in mind that the S3 API supports prefixes only for a filter, so the rest you'd have to do yourself as an enumeration block. For example:

```ruby
bucket = Aws::S3::Resource.new.bucket(BUCKET_NAME)
selection = bucket.objects(prefix: "path/to/").select do |obj|
  # Do your code-style filtering here - for example:
  obj.key.match(/[.]gz$/)
end
```

**Comment by awood45** [comment]
One last note is that the above code essentially uses `Aws::S3::Client#list_objects` and the `:prefix` parameter therein. The resource abstraction was used to simplify. What you do with the `selection` return set above is up to you depending on what you want your application to do.

Let me know if you have any other questions!
