### ISSUE TITLE
2.4.1 Aws::AutoScaling::AutoScaleGroup.wait_until_in_service not functional

### ISSUE THREAD

**Issue by johnbarney** [aws/aws-sdk-ruby#1252]
How to replicate:

Create Launch Configuration
Create Autoscale group (ELB attached or not)
Poll Autoscale group with .wait_until_in_service or .wait_until(:autoscale_group_in_service {})

Regardless of the health or the instances in the ASG or ELB (if associated) the method will never return success.

Within a .before_attempt block, the yielded method 'response' returns an empty response.

Example code:
```
          Aws::AutoScaling::AutoScalingGroup.new("example-asg").wait_until_in_service do |w|
            w.before_attempt do |attempts, response|
              puts "#{attempts} attempts made"
              puts response
            end
          end
```

**Comment by trevorrowe** [comment]
If the response is empty, then the wait should not return. This indicates that the autoscaling group is being omitted from the response for some reason. Invalid id? Not created yet, eventual consistency? The waiter definition explicitly requires the number of autoscaling groups in the response to match those in the request:

```
contains(AutoScalingGroups[].[length(Instances[?LifecycleState=='InService']) >= MinSize][], `false`)
```

**Comment by johnbarney** [comment]
If I do .describe_auto_scaling_groups(auto_scaling_group_names: ["example-asg"]) I receive one asg back and it's the correct one. I have verified the console reflects all instances are InService and Healthy, but the waiter still returns empty.

**Comment by trevorrowe** [comment]
I've found the issue. This is related to how the jmespath expression from the shared waiter is translated into snake_case to work against the Ruby data structures. I'll be looking at this today.

**Comment by trevorrowe** [comment]
I've submitted a pull-request to address this issue. We will likely have this merged in time for tomorrow's release. Thanks for reporting the issue!

**Comment by johnbarney** [comment]
+1

Thank you Trevor
