### ISSUE TITLE
obtaining Set-Cookie values for setting signed cookies using custom policy

### ISSUE THREAD

**Issue by hamadata** [aws/aws-sdk-ruby#1255]
I want to add a method to obtain Set-Cookie values for setting signed cookies using cutom policy.

Currntly,  UrlSigner#signature returns the values, but the type of them is concatenated string. Hash type is preferred, I think.
signature is now a private method, I appreciate if you have a suggestion for creating appropriate public method of it.

This is a sample code:
https://github.com/hamadata/aws-sdk-ruby/commit/8196ab130398ed838416ee0867ed2c605d1f2874

about cookie custom policy:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html

**Comment by awood45** [comment]
Thanks for the PR, we will take a look!

**Comment by hamadata** [comment]
@cjyclaire 
May I close this issue?

**Comment by awood45** [comment]
Yep, it will go out with the next release. Thanks!
