### ISSUE TITLE
Retry S3 transfers on BadDigest error

### ISSUE THREAD

**Issue by nate** [aws/aws-sdk-ruby#1264]
I have run into issues with BadDigest errors while running `upload_file` and `put_object` where somehow, inexplicably, the MD5 of the content is incorrect. It would be nice if the SDK retried uploads with a BadDigest and while retrying recalculated the digest.

Thanks!

**Comment by awood45** [comment]
It sounds like you've had a discussion with Trevor about this, we'll take the retry on as a feature request.

**Comment by nate** [comment]
Yup, thanks!

**Comment by awood45** [comment]
Added to feature request backlog.

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.

**Comment by mullermp** [comment]
I haven't heard any reports of this still happening. By chance were you using a tempfile and not rewinding it? At the worst case, this error [can be added to the list here](https://github.com/aws/aws-sdk-ruby/blob/01c148e8cfa2a32beba4e13a1ff6c0685e87914c/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb#L39). I am going to close this.

**Comment by mullermp** [comment]
As of recently, checksums are handled here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/http_checksum.rb
