### ISSUE TITLE
Uninitialized constant Aws::Rest::Response::Parser::Headers

### ISSUE THREAD

**Issue by assembler** [aws/aws-sdk-ruby#1271]
From time to time I get the following error:

NameError: uninitialized constant Aws::Rest::Response::Parser::Headers Did you mean? Aws::Rest::Response::Headers

Here is the stack trace:
https://gist.github.com/assembler/b0022e9a30282b25903f52774d35bea1

**Comment by trevorrowe** [comment]
Are you using the SDK in a multithreaded processes perhaps? The SDK makes heavy use of Ruby's `autoload` function which is not thread safe. When it fails, it is often with a name error like the one above. 

Can you try adding one of the following lines to your application after you've loaded the SDK?

```ruby
# this loads every service
Aws.eager_autoload!

# cherry pick the service modules to load
Aws.eager_autoload!(services: ['S3', 'EC2'])
```

**Comment by assembler** [comment]
Thanks for your help. Yes, we're using the multithreaded environment (thread/pool). We'll try with eager_autoload and see how it goes. Thanks!
