### ISSUE TITLE
Inconsistent trailing slash on S3 bucket url

### ISSUE THREAD

**Issue by soulcutter** [aws/aws-sdk-ruby#1275]
Seems like it should either always have a trailing slash, or never have one. But not both.

```ruby
Aws::S3::Bucket.new(name: '').url # => "https://s3.amazonaws.com/"

Aws::S3::Bucket.new(name: 'asdf').url # => "https://asdf.s3.amazonaws.com"
```

Ruby Version: 2.1.7
Gem Version: 2.5.6

**Comment by awood45** [comment]
In this case, the first example is failing the "DNS Compatible" check (to see if we can subdomain it), giving the trailing slash - we added the "bucket" after the base domain. The example, for that reason, is a bit difficult to make much of.

Are there any issues this is causing for you?

**Comment by soulcutter** [comment]
Well, the issue is my test suite doesn't require a bucket name, but the code generates what a URL would look like. Is there a way to ask for a URL via `Aws::S3::Object` ? Alternately can `Aws::S3::Presigner` generate an unsigned URL? Or is there some other way to get a public URL?

Or really, I could require a bucket name even in the test suite. It's not like I don't expect one normally outside of tests…

Thanks for explaining why it does this - the non-subdomain thing hadn't occurred to me in the heat of the moment.

**Comment by soulcutter** [comment]
Having `//` in the URL makes sense with empty bucket names given it really represents `/<bucket_name>/`

**Comment by awood45** [comment]
Why not do a URI comparison if you're having issues with the trailing slash? For example, I think this would work (it works locally):

```ruby
u1 = URI.parse("https://s3.amazonaws.com/")
u2 = URI.parse("https://s3.amazonaws.com")
u1 == u2 # => true
```

**Comment by soulcutter** [comment]
Ah, that's a nice thought! I came around to the realization that an empty bucket name was just bad anyway. I appreciate your rapid response and taking the time to think about this :100:
