### ISSUE TITLE
BCC with SES

### ISSUE THREAD

**Issue by snyff** [aws/aws-sdk-ruby#1279]
Hi,

It looks like BCC are not working with SES. It was working perfectly with a traditional SMTP server but moving to SES broke it.

Thanks,

**Comment by trevorrowe** [comment]
Is this using `aws-sdk-rails`?

**Comment by snyff** [comment]
No only 
gem 'aws-sdk'
gem 'aws-ses', '~> 0.4.4', require: 'aws/ses'

**Comment by trevorrowe** [comment]
Can you provide a code example of how you are calling the SDK with a bcc where it is getting dropped?

**Comment by snyff** [comment]
Yes sure.
% grep aws Gemfile.lock 
    aws-sdk (2.5.3)
      aws-sdk-resources (= 2.5.3)
    aws-sdk-core (2.5.3)
    aws-sdk-resources (2.5.3)
      aws-sdk-core (= 2.5.3)
    aws-ses (0.4.4)
  aws-sdk
  aws-ses (~> 0.4.4)

% cat app/mailers/customer_mailer.rb
  def ask_for_details(user, cert)
    mail( to: @user.email,
          subject: "[XXX] TEST" ,
          bcc: ['address1@domain'])
  end

I also tried with  bcc: 'address1@domain') and it didn't work

**Comment by awood45** [comment]
Looking at the [aws-ses gem source](https://github.com/drewblas/aws-ses/), they don't actually appear to use the SDK at all, it's all custom-rolled by them. I'd recommend reaching out to the maintainer of that package if you want to figure out why it's having issues with BCC - I couldn't see at a cursory glance at their package what the issue might be, but I do see BCC issues discussed in their closed issue history - it's possible upgrading the `aws-ses` gem will help, but I can't be sure.

You could also take a look at the [aws-sdk-rails gem](https://github.com/aws/aws-sdk-rails), which should work. If you see issues with that delivery method, feel free to add a note here, and to open an issue there.

**Comment by awood45** [comment]
As an aside, I'd be curious if the `to:` email address received the email. I'm aware that Rails by default will drop delivery errors, which means that if you saw a failure for a permissions/configuration issue it may not be immediately obvious unless you change your Rails configuration to raise delivery errors.

If you did receive the email to the `to:` address, this thought doesn't apply.
