### ISSUE TITLE
Aws::EC2::Instance.network_interfaces returns incomplete NetworkInterface objects.

### ISSUE THREAD

**Issue by DanielRedOak** [aws/aws-sdk-ruby#1281]
Specifically tag_set is not present in the struct and will throw the following error if used:
```NameError: no member 'tag_set' in struct```

Showing the data for a network interface returned by Aws::EC2::Resource #network_interfaces shows the tag_set present:
```
ec2 = Aws::EC2::Resource.new
ec2.network_interfaces.first.data
```

Checking the data on the object that is returned by selecting a network interface from and instance object shows that tag_set is indeed missing.
```
ec2 = Aws::EC2::Resource.new
ec2.instances.first.network_interfaces.first.data
```

**Comment by awood45** [comment]
This is looking at first glance like a bug somewhere in the resource definition - when I add wire tracing, the tag set does appear to be present in both calls. I'm looking deeper in to this now.

**Comment by awood45** [comment]
Okay, I take it back - it's a bit more complicated than that, it appears.

Your first call maps to `describe_network_interfaces()`, which includes the tag set in the [response](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/NetworkInterface.html).

Your second call maps to `describe_instances()`, from which we extract the network interfaces in the [response](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/InstanceNetworkInterface.html).

It doesn't look like there's an easy way for us to rewrite the resource interface to support this member being looked up in this manner. I can do to the EC2 team and see if this can be added to their response shape.

**Comment by awood45** [comment]
Okay, so a workaround does exist, involving an additional call:

```ruby
ni = ec2.resource.instances.first.network_interfaces.first
ni.load # Calls describe_network_interfaces
ni.tag_set # Now present in the object
```

Closing this, I'll send up feedback to see if they can include this in the initial response. Sorry for the bad experience with this.
