### ISSUE TITLE
Update bucket owner name fails

### ISSUE THREAD

**Issue by yuktikhurana** [aws/aws-sdk-ruby#1282]
When a bucket is created through the api
bucket = resource.create_bucket(bucket: 'bucket_name')
The owner property is set to the the id of the owner as per bucket.acl.owner (Aws::S3:Owner)

Now, updating the display_name on the newly created bucket fails

bucket.acl.put({access_control_policy: { grants: {}, owner: {display_name: 'some name', id: 'owner id'}})

The display name doesn't get updated.

I want the owner to be the display_name of my account.
How can I update it ?

**Comment by Doug-AWS** [comment]
You can't. The owner property is read-only. If you want some other means of identifying the bucket, such as a friendly name that you can display, you could use **tagging.put** on the bucket object and add a tag.
