### ISSUE TITLE
Gem index appears out of sync

### ISSUE THREAD

**Issue by mfischer-zd** [aws/aws-sdk-ruby#1285]
The index shows 2.5.9 is available, but trying to download it fails:

```
$ gem list --remote aws-sdk

*** REMOTE GEMS ***

aws-sdk (2.5.9)

$ gem update aws-sdk
Updating installed gems
Updating aws-sdk
ERROR:  Error installing aws-sdk:
	Unable to resolve dependency: user requested 'aws-sdk (= 2.5.9)'
Nothing to update
```

**Comment by trevorrowe** [comment]
Thanks for reporting this. I was releasing the SDK about an hour ago, and ran into multiple problems uploading the gem to rubygems.org. I was getting 504 errors from the API.  It eventually succeeded, but it appears that their index is broken.

I'm going to try to yank the gem and re-upload.

**Comment by trevorrowe** [comment]
The gem yank "succeeded" but then subsequent pushes fail. That said, gem installs should work now:

```
$ gem list --remote aws-sdk

*** REMOTE GEMS ***

aws-sdk (2.5.8 ruby)
```

I'm going to try in a few minutes again to push v2.5.9.

**Comment by awood45** [comment]
We've pushed `2.5.10` and later `2.5.11`, as there were issues fixing the `2.5.9` version. The fix here is to upgrade, sorry for the inconvenience!
