### ISSUE TITLE
PresignedPost url wrong when bucket has cloudfront enabled

### ISSUE THREAD

**Issue by ibussieres** [aws/aws-sdk-ruby#1287]
PresignedPost url is in the format `https://s3.amazonaws.com/my-bucket/`, which is fine for standard buckets, but when cloudfront is enabled, format should be `https://my-bucket-s3.amazonaws.com/`.

**Comment by awood45** [comment]
Can you tell me how this problem is manifesting for you? If you're referring to CloudFront fetching from your bucket as the origin, it shouldn't have any effect.

If you're having a different issue, perhaps with headers, knowing exactly what problem you're having would help me debug this.

**Comment by trevorrowe** [comment]
@ibussieres Does your bucket name contain dots? The Ruby SDK will put the bucket name in the url path when it is not DNS compatible, or  if it contains dots. As @awood45 has indicated, this should work fine.

**Comment by ibussieres** [comment]
Well, as a temporary fix I had switched (back) to a bucket without cloudfront. Now switching back again, the problem does not occur anymore.

For what it's worth, it was not when I was fetching, but when I was POSTing with a S3 presigned post. I'll close this for now, as it seems I cannot replicate myself.
