### ISSUE TITLE
When using non dns safe s3 bucket name s3_object returns invalid url

### ISSUE THREAD

**Issue by anark** [aws/aws-sdk-ruby#1292]
When using a bucket name that contains a . such as bucket.name
 
bucket.url returns an invalid url
`    bucket.url => 's3.s3-us-west-2.amazonaws.com/bucket.name/.....'`

when the url should be
`    's3-us-west-2.amazonaws.com/bucket.name'`

**Comment by awood45** [comment]
Can you give me a reproducing example of this? I'm unable to replicate this based on what you've given me. What version of the SDK are you using?

**Comment by anark** [comment]
Oh, Turns out this had to do with passing in a region of 's3-us-west-2' instead of just 'us-west-2'.  Changing this fixed the issue

**Comment by awood45** [comment]
That makes sense, glad you got things working!
