### ISSUE TITLE
 #<NameError: undefined method `to_hash' for class `#<Class:#<Seahorse::Client::Response:0x007fa1fa198450>>'

### ISSUE THREAD

**Issue by rayway30419** [aws/aws-sdk-ruby#1295]
Hi 

I meet some problem with aws-sdk-ruby client's response.

I create an SNS client instance 

`client = Aws::SNS::Client.new`

and try to list all my sns apps

`client.list_platform_applications`

The result

`#<NameError: undefined method `to_hash' for class `#<Class:#<Seahorse::Client::Response:0x007fe8962fa1f8>>'`

This section of code works with my EC2 instance, but error occurs on my development environment.

FYR
Rails 5.0.0.1
aws-sdk 2.6.1 
ruby 2.3.0
OS X 10.11.6

**Comment by awood45** [comment]
Do you have a more extensive stack trace for this? I can't reproduce this (running the same code in a substantially similar environment works fine).

**Comment by rayway30419** [comment]
Hi @awood45 

I find whats wrong with my app, but thanks for your response.

I use this gem, rails_awesome_console, with my development enviroment, and it seems that modify the default output with rails console.
(https://github.com/ascendbruce/awesome_rails_console)

However, the class `Seahorse::Client::Response` does not have `to_hash` method.

I disable this gem and print the standard result with aws-sdk is correct.
