### ISSUE TITLE
Aws::Kinesis::Errors::InternalFailure: <empty error message>

### ISSUE THREAD

**Issue by benoittgt** [aws/aws-sdk-ruby#1296]
Hello 

I have an issue like : 

````
vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.1.19/lib/seahorse/client/plugins/raise_response_errors.rb:15 in call
vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.1.19/lib/aws-sdk-core/plugins/param_converter.rb:21 in call
vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.1.19/lib/seahorse/client/plugins/response_target.rb:21 in call
vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.1.19/lib/seahorse/client/request.rb:70 in send_request
vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.1.19/lib/seahorse/client/base.rb:207 in block (2 levels) in define_operation_methods
lib/aws_stats/kinesis_sender.rb:17 in put_kinesis_record
```

I do a simple, and sometimes I get this error.
```ruby
formated_data = "298700|2016-09-20 11:41:02|125788|19|native|606|com.octo.aposa696|91145|114020006"
kinesis.put_record(stream_name: active_stream, data: formated_data, partition_key: partition_key)
```

This code run properly 10 thousands times per days, but sometimes I get this error. Any idea?

**Comment by benoittgt** [comment]
I had unusual latency on my kinesis stream apparently 
![capture d ecran 2016-09-20 a 14 00 41](https://cloud.githubusercontent.com/assets/8417720/18671252/b164065c-7f43-11e6-86a7-a52fb79d707c.png)
Don't know if it is related.

Can this commit can help me to identify the issue ? https://github.com/aws/aws-sdk-ruby/pull/1250

**Comment by awood45** [comment]
I don't actually see the error you're getting in the stack trace, but I'm guessing that this is a 500 error of some sort, and we exhausted retries. Your unusual latency probably is related, as a 500 error would indicate some sort of issue on the service side.

**Comment by awood45** [comment]
Is there anything different about your system at the point where latency spiked? Were you at a higher load?

**Comment by awood45** [comment]
That's interesting - I'd be curious to see a wire trace, because errors with the `Aws::Kinesis` namespace should be associated with a 500 error response from the service itself. They could be related, but that's not certain. If you want to go this route:

```ruby
client = Aws::Kinesis::Client.new(http_wire_trace: true)
```

**Comment by benoittgt** [comment]
For the moment the wire trace show me a nice 200. I need to find a way to raise the wire trace in case of `InternalFailure`. I think it's the best idea no? 🤔

**Comment by awood45** [comment]
You could catch the error and inspect the HTTP response details, but there isn't necessarily an easy way to do this for rare+transient errors.

Given that this looks like either a networking issue on your end, a service issue, or some combination of the two, reaching out to support is also still an option.

**Comment by benoittgt** [comment]
Ok thanks @awood45. Thanks for your help. Closing the issue for the moment.
