### ISSUE TITLE
Question about forward slack

### ISSUE THREAD

**Issue by javierhonduco** [aws/aws-sdk-ruby#1300]
Hi,

We just updated one of our Shopify project's gem to the latest version and saw that the exception defined [here](https://github.com/aws/aws-sdk-ruby/blob/772f1c3f6d18d5657b88d782a88798c6ec9a879c/aws-sdk-core/lib/aws-sdk-core/plugins/s3_bucket_name_restrictions.rb#L8-L11) with the following [spec](https://github.com/aws/aws-sdk-ruby/blob/a3a442e0824318dcd95021a1f6057309518bf2a5/aws-sdk-core/spec/aws/s3/client_spec.rb#L292-L297) was being raised.

We have a bucket with a forward slash 😢  and was wondering why was this requirement introduced as I cannot find anything in the docs.

Thank you in advance!

@trevorrowe

**Comment by trevorrowe** [comment]
I'm guessing you were able to resolve this issue. I'm responding in case others come across this issue.

Amazon S3 does not allow you to create a bucket with a slash in their names. Often users will consider the bucket name to contain some portion of a key prefix. As they can often be run-together as part of a URI, this seems to make sense.  Unfortunately this will cause signature version 4 errors, it breaks DNS compatibility, and causes other issues. Bucket names do not contain slashes, it is simply not possible.
