### ISSUE TITLE
Aws::Errors::MissingCredentialsError: unable to sign request without credentials set

### ISSUE THREAD

**Issue by rayway30419** [aws/aws-sdk-ruby#1301]
Hi

I use IAM-role to assign policy to my EC2 instance, but sometimes it raise missing credential error.

`Aws::Errors::MissingCredentialsError: unable to sign request without credentials set`

Does anyone have same problem?

**Comment by awood45** [comment]
So you're saying that on an EC2 instance, you're seeing this periodically? How is your environment set up?

**Comment by rayway30419** [comment]
Hi @awood45 

It happens randomly, 

What kind of enviroment setting?
--

Ruby 2.3.0
Rails 5.0.0.1
aws-sdk 2.6.3
Ubuntu 14.04 Trusty (3.13.0-63-generic)

**Comment by awood45** [comment]
Is the Ubuntu version you listed your development environment, or an EC2 AMI? How are you configuring your clients in code?

**Comment by rayway30419** [comment]
It's on the EC2 AMI.
```
# region in configuration file
client = Aws::DynamoDB::Client.new(
  region: Aws.config[:region]
)
# do sth.
client.put_item params
```

**Comment by rayway30419** [comment]
BTW, I found a clue.....it's running on my sidekiq worker, it may happen to mult-ithreading?

**Comment by rayway30419** [comment]
Another error message when initialize DynamoDB client
`NameError: uninitialized constant Aws::CredentialProviderChain::InstanceProfileCredentials`

**Comment by awood45** [comment]
Okay, it looks like this may be related to how Sidekiq initializes - you might need to do eager_autoload within your Sidekiq workers, rather than only in the Rails initialization. Can you try that?

**Comment by awood45** [comment]
For what it's worth, we're working on an overhaul of the SDK which should reduce or eliminate these autoload issues - message definitely received that they cause problems when threading.

**Comment by rayway30419** [comment]
@awood45 
With my understand, the sidekiq process will execute the procedures within rails initializer, too.

I am glad to hear this new.

**Comment by glennpratt** [comment]
https://bugs.ruby-lang.org/issues/12688

**Comment by trevorrowe** [comment]
Just chiming in here. The preview release of the modularized SDK is coming shortly. With modularization, we have eliminated the use of `autoload`.

**Comment by trevorrowe** [comment]
@rayway30419 Are you still experiencing the intermittent missing credential errors? Commonly this is caused by the aggressive defaults in attempting to load credentials from the instance metadata service. Once credentials expire, they must be refreshed, but if the metadata service fails to respond, a missing credentials error is raised. I've just push a small change that will go out with the next release where you can configure expanded retries and timeouts:

```ruby
client = Aws::DynamoDB::Client.new(
  region: Aws.config[:region],
  instance_profile_credentials_timeout: 5, # defaults to 1 second
  instance_profile_credentials_retries: 5, # defaults to 0 retries
)
```

This change will be available in the next release.

**Comment by rayway30419** [comment]
hi @trevorrowe,
It still happens, I am looking forward to it!

**Comment by awood45** [comment]
It looks like this went out with a previous release. Let me know/reopen if you see this again after looking at configured retries/timeouts. Thanks!

**Comment by jammerful** [comment]
I'm still seeing this issue on (actually coming from fluentd which uses the SDK):

Ruby               2.3.4
AWS SDK       2.7.0
Linux Kernel  4.9.41

Is this expected? Could this be eventual consistency, instead of code?

**Comment by rahul-yadav-1** [comment]
We're also getting the same error.
I'm trying the adding retry & timeout configuration fix, and will see if it fixes anything.

For more context, we're facing this issue in a Sidekiq worker, where multiple threads are involved and are all relying on a single shared S3 client.
