### ISSUE TITLE
Please update the "source code" link on rubygems.org

### ISSUE THREAD

**Issue by jaredbeck** [aws/aws-sdk-ruby#1304]
On your rubygems.org gem profile

https://rubygems.org/gems/aws-sdk

the "source code" link currently points to 

https://github.com/amazonwebservices/aws-sdk-for-ruby

but should (obviously) point to

https://github.com/aws/aws-sdk-ruby

Thanks!

**Comment by awood45** [comment]
I followed the link to RubyGems and the Source Code link appears to point to this repo.

Is this possibly for an older version?

**Comment by jaredbeck** [comment]
It looks like this has been fixed since I opened this issue 23 hours ago. Perhaps one of your colleagues fixed it. I will close. Thanks.

**Comment by trevorrowe** [comment]
Sorry, I made the change this afternoon, got distracted and failed to update this issue.
