### ISSUE TITLE
AWS Ruby gem 'aws-sdk', '~> 2.5', '>= 2.5.10' snapshots issue

### ISSUE THREAD

**Issue by gabayliran** [aws/aws-sdk-ruby#1305]
I changed the setting on my root account to longer IDs, all snapshots on eu-central-1 with longer IDs.
The result of the below code will print a lot of snapshot IDs which does not appear in my account,
Perhaps they old snapshots that I removed already, even snapshots with shorter IDs.
Is it a bug?
Thanks!

```
require 'aws-sdk'
regions_list = [ "eu-central-1" ]
regions_list.each do  |region|

  Aws.config[:credentials] = Aws::Credentials.new(ENV_YML['access_key_id'], ENV_YML['secret_access_key'])
  ec2 = Aws::EC2::Resource.new(region:"#{region}", credentials: Aws.config[:credentials])
  logger.info(region)
  snapshot_id = ec2.snapshots.each do |snapshot|
    puts snapshot.id
 end 
end
```

**Comment by awood45** [comment]
It is unlikely to be a bug, it is more likely that they are older snapshots. The client is just making a request to the service and translating the response, so if you're concerned that you're getting an invalid response, it could be worth reaching out to the EC2 team via a support ticket.

**Comment by gabayliran** [comment]
@awood45 please kindly see below AWS support answer 
```
I've reviewed and reproduced the results you're seeing - I also get a long list of unrelated snapshot IDs. Instead I think you should use describe_snapshots and specify owner_ids:
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EC2/Client.html#describe_snapshots-instance_method
```
but I got an exception with describe_snapshots

```
regions_list = [ "eu-central-1" ]
regions_list.each do  |region|
Aws.config[:credentials] = Aws::Credentials.new(ENV_YML['access_key_id'], ENV_YML['secret_access_key'])
ec2 = Aws::EC2::Client.new(region:"#{region}", credentials: Aws.config[:credentials])
  ec2.describe_snapshots(owner_ids:['123456']).each do |snapshot|
 p snapshot # works but it give all the snapshot details 
 p snapshot.snapshot_id # undefined method `snapshot_id'
  end
end 
```
in `method_missing': undefined method `snapshot_id' for #<Seahorse::Client::Response:0x00000002bb9340> (NoMethodError)

Could you please kindly suggest how to get the snapshot id ?

**Comment by awood45** [comment]
The response isn't directly the collection of snapshots. You want to do this:

```ruby
resp = ec2.describe_snapshots.(owner_ids:['123456'])
resp.snapshots.each do |snapshot|
  p snapshot.snapshot_id
end
```

**Comment by awood45** [comment]
Let me know if you have any further issues or questions!

**Comment by awood45** [comment]
For some clarification (I forgot this), the list of snapshots includes shared snapshots (notice the `"amazon"` value for `:owner_id` in those snapshots. That's where the other snapshots were coming from.

**Comment by gabayliran** [comment]
Thank you @awood45, but I still got an error:

```
/var/lib/gems/2.3.0/gems/aws-sdk-core-2.6.4/lib/seahorse/client/response.rb:87:in `method_missing': undefined method `call' for #<Seahorse::Client::Response:0x00000002d5f668> (NoMethodError)
Did you mean?  caller

```
I will try to search over the internet what is wrong. 

I used ` :owner_id` because that is what AWS support recommend, in order to get only the snapshots that are belong to my account.

Thanks again for your help!

**Comment by gabayliran** [comment]
@awood45  yay its working !!! just needed to remove the dot
```
resp = ec2.describe_snapshots(owner_ids:['123456'])
resp.snapshots.each do |snapshot|
  p snapshot.snapshot_id
end
```

thanks!!
