### ISSUE TITLE
Rate Limit Error

### ISSUE THREAD

**Issue by 141984** [aws/aws-sdk-ruby#1308]
I am getting this error while running API calls in parallel, but not when I run them sequentially.

Where is the rate limit set ? And how can I increase this?

```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Rate exceeded (Aws::ElasticLoadBalancing::Errors::Throttling)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /var/lib/jenkins/jobs/prod_adminWebApp_deploy/workspace/lib/deployer/aws_tasks.rb:158:in `check_instance_state'
	from /var/lib/jenkins/jobs/prod_adminWebApp_deploy/workspace/lib/deployer/rotate.rb:101:in `block in check_instance_state_in_elb'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
	from /var/lib/jenkins/jobs/prod_aApp_deploy/workspace/lib/deployer/rotate.rb:99:in `check_instance_state_in_elb'
	from /var/lib/jenkins/jobs/prod_aApp_deploy/workspace/lib/deployer/rotate.rb:17:in `remove_from_elb'
	from lib/deployer.rb:120:in `<module:Deployer>'
	from lib/deployer.rb:1:in `<main>'
```

**Comment by awood45** [comment]
You can cut a ticket via AWS Support to see if a rate limit increase is possible.

As far as managing this, you can have your code rescue this exception, add a backoff period, and retry.

**Comment by awood45** [comment]
It's also worth noting that if you see a throttling error, it's also already been retried by the client. If you need to hit that API in parallel, you could modify the default `:retry_limit` in the client options: http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancing/Client.html#initialize-instance_method

**Comment by awood45** [comment]
Closing this for now, feel free to add a comment if you have any further questions on this.

**Comment by kirhgoff** [comment]
We are also hitting maximum rate limit using Ruby gem. I noticed there is an article about RateLimiter class to be used in Java library, does Ruby version has anything like that?
https://aws.amazon.com/blogs/messaging-and-targeting/how-to-handle-a-throttling-maximum-sending-rate-exceeded-error/
Or only way to get that issue solved is to increase the limit?

**Comment by awood45** [comment]
We don't have a built in rate limiter class - if you get a throttling error after retries, it's recommended to have backoff logic in your app as appropriate. You can also increase your limits with AWS Support.

**Comment by nish-acquia** [comment]
Do we still not have a built-in rate limiter class ?
