### ISSUE TITLE
Access denied when using ECS task IAM role

### ISSUE THREAD

**Issue by malekascha** [aws/aws-sdk-ruby#1309]
I'm using the sdk to interact with s3. I have my application running in a container on ECS. When I assign an IAM role directly to the task that my ruby app is running on, it fails to detect the credentials and I get an access denied whenever I try to use the s3 client. It works fine when I bind the role to the EC2 instance that it's running on.

**Comment by awood45** [comment]
The default credential provider chain forks between the ECS Credential Provider and the EC2 Credential Provider. If putting credentials on the instance fixed the issue, my suspicion is that the ENV variable isn't present in the container.

Can you double check that the credential provider feature flag is on?

**Comment by malekascha** [comment]
How would I make sure that the flag is on? Is that something I would configure from the AWS console, or would it be in my Ruby code?

**Comment by awood45** [comment]
[Documentation is here.](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)

The SDK is looking for the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable. If you're able to use EC2 instance metadata credentials, then that ENV variable is not present.

**Comment by awood45** [comment]
Did this resolve your issue, or does the issue persist?

**Comment by malekascha** [comment]
Yes, it did. Thanks!
