### ISSUE TITLE
DynamoDB :retry_limit and ProvisionedThroughputExceededExceptions

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-ruby#1310]
I have code where DynamoDB throttling errors are self implemented by catching `Aws::DynamoDB::Errors::ProvisionedThroughputExceededException` and retrying (with exponential backoff).

I didn't realize that there was a `:retry_limit` config option on the DynamoDB client. Based on the docs, it seems that it is on by default, and I'm assuming that it doesn't matter that I have one configuration set on the client (`simple_attributes`) -- i.e. configuring one attribute doesn't override defaults for other config attributes. Is that correct?

So, assuming that retries are on by default in the SDK, **when** would my code see a `Aws::DynamoDB::Errors::ProvisionedThroughputExceededException`? After 10 retries have been taken care of by the SDK?

Also, I am testing my current retry code by stubbing DynamoDB responses in rspec: `Aws.config[:dynamodb][:stub_responses] = {get_item: 'ProvisionedThroughputExceededException'}`. Is there a way to test out the SDK retry code or see it in action (aside from in production)?

Thanks!

**Comment by awood45** [comment]
You're correct that `:retry_limit` exists with a default of 10, and is only overridden if you override it manually. I believe you are correct that the throughput error is only surfaced after retries have been exhausted.

**Comment by awood45** [comment]
Is your issue that you're having difficulty with testing the code, or just that you want to verify the behavior in the `Aws::Plugins::RetryErrors` plugin?

**Comment by kalpitad** [comment]
The latter. I guess since the retries happen internally, I can't test them or monitor them. Am I missing something?

Also, if I wanted to completely handle retries myself (so that I could increment a statsd monitor, for example), how would I turn off the auto retries built into the SDK?

**Comment by awood45** [comment]
You can turn off retries entirely by setting `:retry_limit` to `0`. The [https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb](RetryErrors) plugin source code shows the types of errors that we retry, and you may have to consider how you would handle those cases.

You can also get the number of retries from the response context of any call, much like the logger class does. See [https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/log/formatter.rb#L134](the log formatter source) for how we pull that out of a client response.

**Comment by awood45** [comment]
Closing as it seems the question is answered. Feel free to reopen or add a comment if you have more questions!
