### ISSUE TITLE
aws-sdk incompatible with awesome_print

### ISSUE THREAD

**Issue by iainelder** [aws/aws-sdk-ruby#1316]
I installed [awesome_print](https://github.com/awesome-print/awesome_print) as the default formatter in irb, and now I can't view responses from the API. Formatting the response fails with an error like this:

```
NameError: undefined method `to_hash' for class `Seahorse::Client::Response'
```

My .irbrc file looks like this:

```
require 'awesome_print'
AwesomePrint.irb!
```

To reproduce the issue and see the expected behavior:
- start irb without reading .irbrc
- print an API response using the default formatter (expected behavior, but less pretty)
- Set awesome_print as the formatter
- print the same API response (fails)

```
$ irb -f
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> iam = Aws::IAM::Client.new
=> #<Aws::IAM::Client>
irb(main):003:0> iam.list_users
=> #<struct Aws::IAM::Types::ListUsersResponse users=[...], is_truncated=false, marker=nil>
irb(main):004:0> require 'awesome_print'
=> true
irb(main):006:0> AwesomePrint.irb!
nil
irb(main):007:0> iam.list_users
NameError: undefined method `to_hash' for class `Seahorse::Client::Response'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:122:in `method'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:122:in `convert_to_hash'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:55:in `awesome_self'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:36:in `format'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:148:in `unnested'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:115:in `awesome'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:33:in `output_value'
    from /usr/bin/irb:12:in `<main>'
```

As a workaround in this example you can access the users property to get the most important information:

```
irb(main):004:0> iam.list_users.users
[
    [ 0] #<Aws::IAM::Types::User:0x7ff71cbf55e8
        arn = ...,
        create_date = ...,
        password_last_used = nil,
        path = ...,
        user_id = ...,
        user_name = ...
    >,
    ...
```

But the workaround in the general case depends on the content of the response, so this is not a great solution.

**Comment by awood45** [comment]
So, I had some interesting results when trying to replicate this. `:to_hash` is definitely implemented for the response object, but it may be doing something clever which doesn't work. For example:

```ruby
resp = iam.list_users # gives the error NameError: undefined method `to_hash' for class `#<Class:#<Seahorse::Client::Response:0x007fc8832b5400>>'
resp.to_hash # does return a valid hash
```

Have you raised an issue with the awesome_print maintainers?

**Comment by iainelder** [comment]
Just now yes 😄 . I've added your observations to [awesome_print issue 275](https://github.com/awesome-print/awesome_print/issues/275).

**Comment by lsegal** [comment]
This actually seems like an issue with the AWS SDK. You can reproduce this without awesome_print:

```sh
$ ruby -raws-sdk -e 'r=Aws::IAM::Client.new.list_users; p r.respond_to?(:to_hash); r.method(:to_hash)'
true
-e:1:in `method': undefined method `to_hash' for class `#<Class:#<Seahorse::Client::Response:0x007fdc8ba8c770>>' (NameError)
Did you mean?  to_s
	from -e:1:in `<main>'
```

It looks like aws-sdk does actually delegate `respond_to?` and `method_missing`, so maybe it's doing something wrong here? https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/seahorse/client/response.rb#L77-L89

The other interesting part is the `#<Class:#...` prefix. It looks like `r` is a metaclass object? That could explain why `respond_to?` returns `true` but `method` cannot resolve the method object for an instance.

**Comment by gerrywastaken** [comment]
> I would expect that if r.respond_to?(X) == true then I can call r.method(X) to get the associated Method object.

@lsegal thanks for tracking that down. 

@awood45 did you see this?

**Comment by trevorrowe** [comment]
> I would expect that if r.respond_to?(X) == true then I can call r.method(X) to get the associated Method object.

I disagree. The purpose of `#method_missing` is to provide behavior exactly when a method does not exist, hence, the method is missing. The purpose of `#respond_to?` is to indicate if an object will respond to a method/message, not if there is a concrete method.

**Comment by trevorrowe** [comment]
I did some digging in the awesome_print code. Before simply calling inspect, it checks to see if an object responds to `#to_hash`. It does a bunch of sanity checks on the object, even as far as checking the interface of the object returned from `#to_hash` responds to certain hash methods. Failure from any of these checks causes it to return `nil` and fallback on inspecting the object. One of these is getting the `#to_hash` method and ensuring the arity of the method is 0 (it can be called without arguments).

One options would be to replace `#respond_to?` with calling `#public_methods` and checking to see if the returned list includes `:to_hash`. I can go add this to the issue on awesome_print.

Separately, I modified the response class to use the Ruby stdlib `Delegator` to provide access to the response data. This resolves the issue immediately with awesome_print, and it provides better formatting. It results in awesome printed structure data, instead of down-casting it to a hash.

**Comment by trevorrowe** [comment]
I've submitted a pull-request to awesome_print that fixes the root issue there. It includes a test case demonstrating the issue along with the fix.

https://github.com/awesome-print/awesome_print/pull/285

Either way, we are now working around the issue by using `Delegator` in this SDK.

**Comment by lsegal** [comment]
Just FYI you could [also have used `respond_to_missing?`](http://stackoverflow.com/questions/13793060/respond-to-vs-respond-to-missing), which resolves the expectation about `method()`-- in fact, you should *always* be using that callback when overriding method_missing to get correct expectations. Ruby will fill in the details for you if you do this:

```ruby
class Foo
  def method_missing(sym, *args) sym == :bar ? 'hello' : super end
  def respond_to_missing?(sym, *args) sym == :bar end
end

Foo.new.method(:bar)
#=> #<Method: Foo#bar> 
Foo.new.method(:bar).call
#=> "hello"
```

**Comment by gerrywastaken** [comment]
My response is here: https://github.com/awesome-print/awesome_print/pull/285#issuecomment-263048237

Very similar to what @lsegal said. But either way, looking into this alerted me to a different issue in the awesome_print arity checking code.
