### ISSUE TITLE
SSL_write:: shutdown while in init

### ISSUE THREAD

**Issue by iroller** [aws/aws-sdk-ruby#1319]
We're having intermittent openssl exceptions when trying to upload files to S3 after upgrading to a newer OS version (Ubuntu 12.04 -> 16.04) and openssl (1.0.1-4ubuntu5.31 -> 1.0.2g-1ubuntu4.5). Re-trying works fine in most of the cases.

Versions used:
* aws-sdk 1.42 (for ruby 1.8 support)
* openssl 1.0.2g-1ubuntu4.5 on ubuntu xenial

Exception:
```
OpenSSL::SSL::SSLError (SSL_write:: shutdown while in init):
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/openssl/buffering.rb:179:in `syswrite'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/openssl/buffering.rb:179:in `do_write'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/openssl/buffering.rb:193:in `write'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/protocol.rb:177:in `write0'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/protocol.rb:153:in `write'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/protocol.rb:168:in `writing'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/protocol.rb:152:in `write'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/http.rb:1565:in `send_request_with_body_stream'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/http.rb:1535:in `exec'
  /opt/ree-1.8.7-2012.02/lib/ruby/1.8/net/http.rb:1049:in `__request__'
  /usr/local/bundle/ruby/1.8/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/http/connection_pool.rb:350:in `request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/http/net_http_handler.rb:61:in `handle'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/http/connection_pool.rb:129:in `session_for'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/http/net_http_handler.rb:55:in `handle'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:256:in `make_sync_request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:289:in `retry_server_errors'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:249:in `make_sync_request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:511:in `client_request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:391:in `log_client_request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:477:in `client_request'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:373:in `return_or_raise'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/core/client.rb:476:in `client_request'
  (eval):3:in `put_object'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/s3/s3_object.rb:1752:in `write_with_put_object'
  /usr/local/bundle/ruby/1.8/gems/aws-sdk-1.42.0/lib/aws/s3/s3_object.rb:607:in `write'
```

Any suggestions?

Thanks

**Comment by iroller** [comment]
Here's what I see in wireshark:
<img width="905" alt="screen shot 2016-10-20 at 13 06 21" src="https://cloud.githubusercontent.com/assets/338294/19576228/0834e7ae-96c7-11e6-98a8-bc7e45888fbc.png">

It's only happening when I'm uploading large files (5-10Mb) and never seem to be happening when I'm using smaller files.

**Comment by awood45** [comment]
This sounds like it may be related to your networking settings. Have you tried switching to multipart uploads for larger files?

**Comment by iroller** [comment]
Hi @awood45, thanks for your response. This is definitely related to openssl version and apparently to how old ruby is using it. Networking shouldn't be an issue, since it's aws ec2 hosts uploading data into aws s3 buckets.

Going forward I've downgraded our containers from [Ubuntu Xenial](https://launchpad.net/ubuntu/+source/openssl/1.0.2g-1ubuntu4.5) to [Ubuntu Trusty](https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.21) and the problem is gone while using all the same ruby 1.8 and aws-sdk 1.42.0.

**Comment by awood45** [comment]
Well, if you can't upgrade Ruby and the AWS SDK (V1 is end of life), I'd recommend looking at multipart uploads for larger files, since the threshold seems to be important.

Closing this as it seems like it's been resolved/nothing we can do. Feel free to comment if you have any other questions.
