### ISSUE TITLE
s3 upload when the file size isn't known in advance

### ISSUE THREAD

**Issue by codekitchen** [aws/aws-sdk-ruby#1320]
`FileUploader` and `MultipartFileUploader` both call `File.size` on the IO object passed in, which fails if the IO object is a stream that doesn't know the file size. Is there an upload method available that works when the file size is not known up front?

For some background, we're currently using fog in our application but are working to convert it to using the ruby aws-sdk directly. We have currently-working code that has fog upload a multipart HTTP form request to S3 as we stream it from the browser and parse the request, without staging it to the server's local disk at any point. But because it comes from a multipart form POST we don't know the total file size until we're read the whole request.

**Comment by awood45** [comment]
This is similar to #602 - you can directly call the [#create_multipart_upload](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#create_multipart_upload-instance_method) client method, and upload parts one by one with [#upload_part](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#upload_part-instance_method) (you will need to know the part size at each stage), and conclude with [#complete_multipart_upload](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#complete_multipart_upload-instance_method).

**Comment by codekitchen** [comment]
Ah, I searched for existing issues but I guess I didn't pick the right keywords to find that one. Thanks, that's a bit lower level but definitely will work.
