### ISSUE TITLE
Redundant calls to "describe_stacks" from Aws::CloudFormation::Stack#data

### ISSUE THREAD

**Issue by mdub** [aws/aws-sdk-ruby#1322]
This is a reappearance of #1265.  

It was fixed in bbad4d97, which patched `cloudformation/2010-05-15/resources-1.json`, but then reintroduced in 990c5be206, which (I assume) pulled a fresh copy of that file from upstream.

**Comment by awood45** [comment]
Sorry, you're right about this. I've made a fix such that the next release will re-introduce the fix (as well as a second PR that was also squashed upstream).

**Comment by mdub** [comment]
Looks all good in `2.6.14`; thanks!
