### ISSUE TITLE
Lack of `nat_gateways` method for `Aws::EC2::Vpc` makes deletion cumbersome.

### ISSUE THREAD

**Issue by colstrom** [aws/aws-sdk-ruby#1323]
When deleting a VPC, dependent resources must be removed first. `nat_gateways` is the only dependency _not_ identifiable from an `Aws::EC2::Vpc` object.

I'm curious about the reasons for this.
- Is it simply a "not implemented yet" scenario?
- Have I overlooked an existing method somewhere?
- Is there a reason (documented or not) why this does not or should not exist?

Alternatively, is there a simpler approach to deleting a VPC?

**Comment by trevorrowe** [comment]
It has simply not been implemented yet. I'm going to mark this as a feature request so we can add it to our backlog.

**Comment by awood45** [comment]
Added to feature request backlog.

**Comment by mullermp** [comment]
Hey @colstrom - I dug out this feature request and added a NAT gateway resource model. Per my testing, I was able to successfully delete a NAT gateway. The changes were pushed to an internal package. When I get the opportunity, I will be sure to push this change out for all of the SDKs.

```
Aws> r.nat_gateways.first.delete
[Aws::EC2::Client 200 0.136147 0 retries] describe_nat_gateways()  
[Aws::EC2::Client 200 0.048603 0 retries] delete_nat_gateway(nat_gateway_id:"nat-0050e741ba6dbc9c7")  
=> #<struct Aws::EC2::Types::DeleteNatGatewayResult nat_gateway_id="nat-0050e741ba6dbc9c7">
```
