### ISSUE TITLE
S3 API assumes IO object is seekable beacause it has #rewind

### ISSUE THREAD

**Issue by bittrance** [aws/aws-sdk-ruby#1324]
Consider this streamed download of S3 object:

```
require 'aws-sdk'
require 'csv'

def s3_reader(region, bucket, file)
  bucket = Aws::S3::Resource.new(region: region).bucket(bucket)
  reader, writer = IO.pipe
  t = Thread.new do
    bucket.object(file).get(response_target: writer)
    writer.close
  end
  t.abort_on_exception = true

  CSV.new(reader, headers: true).each_with_index do |_, n|
    print '.' if (n % 1000).zero?
  end
end
```

This fails with ESPIPE because pipes are not searchable:

```
./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/http/response.rb:103:in `rewind': Illegal seek (Errno::ESPIPE)
from ./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/http/response.rb:103:in `signal_done'
from ./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/http/response.rb:116:in `signal_error'
from ./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/net_http/handler.rb:90:in `rescue in transmit'
from ./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/net_http/handler.rb:68:in `transmit'
from ./vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-2.6.12/lib/seahorse/client/net_http/handler.rb:42:in `call'
```

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/seahorse/client/http/response.rb#L103:

``` ruby
          elsif options.empty?
            @body.rewind if @body.respond_to?(:rewind)
            @done = true
            emit(:done)
          else
```

IO.pipe, filesystem fifos (and BSD sockets?) all have rewind() but can't be seek'd. 

My opinion would be that the API should not assume that you want the IO object rewound even if that is possible, but I suppose that that would be a breaking change. The next best thing might be to eat seek errors?

(For those who are landed here by Google, you can work around this issue by `writer.instance_eval('undef :rewind')`.)

**Comment by awood45** [comment]
It's interesting that the object implements, but cannot handle, `#rewind`. I appreciate the issue here. This comes up in retry scenarios mainly, so I'm going to look in to if we can just surface errors as a non-retryable exception.

Do you see this intermittently, or constantly?

**Comment by bfolkens** [comment]
We just got bitten by this one too.  I'm going to look for a workaround and will post if I find something, but otherwise +1 here as well.

**Comment by tilo** [comment]
is there any update on this? @cjyclaire do you know who might be the right person to look at this?

**Comment by srchase** [comment]
@mujz 

Did you try the suggestion from bittrance?

**Comment by mullermp** [comment]
Going to close this issue for now. Please reopen if this is still any concern. This change is a breaking change.
