### ISSUE TITLE
Can not specify security groups with restore_db_instance_from_db_snapshot

### ISSUE THREAD

**Issue by daveseff** [aws/aws-sdk-ruby#1325]
I would expect to see the 

    vpc_security_group_ids: ["String"],

attribute with this function like all of the other functions, but currently it is not available.

**Comment by awood45** [comment]
It looks like our docs failed to refresh. It does appear to be there now: [Doc Link](http://docs.aws.amazon.com/sdkforruby/api/Aws/RDS/Client.html#restore_db_cluster_from_snapshot-instance_method)

**Comment by daveseff** [comment]
Nope. This issue was for restore_db_instance_from_db_snapshot, not db cluster.
