### ISSUE TITLE
Can not specify security groups with restore_db_instance_from_db_snapshot

### ISSUE THREAD

**Issue by daveseff** [aws/aws-sdk-ruby#1327]
Issue #1325 was for restore_db_instance_from_db_snapshot, not db cluster.

I would expect to see the

```
vpc_security_group_ids: ["String"],
```

attribute with this function like all of the other functions, but currently it is not available.

**Comment by trevorrowe** [comment]
RDS does not accept a group of VPC security group ids to this operation. The API documentation is here: 

http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromDBSnapshot.html

**Comment by jospas** [comment]
This doesn't seem to be resolved, customer notes that this still leaves restored snapshots with the default security group
