### ISSUE TITLE
Error creating SNS Platform Application: iOS

### ISSUE THREAD

**Issue by gregk8288** [aws/aws-sdk-ruby#1328]
For the last three weeks, we've had an issue creating SNS Platform Applications for iOS. For some reason when passing the `pkey` as the `PlatformPrincipal` we get an error stating that *Invalid parameter: Attributes Reason: Platform credentials are invalid*

Now, the issue is that the `pkey` contains both the -----BEGIN / END CERTIFICATE----- value followed by the  -----BEGIN / END RSA PRIVATE KEY----- value. If I remove the -----BEGIN / END RSA PRIVATE KEY----- value from the `pkey` file and resubmit the task it creates the Platform Application without issue.   

The `pkey` file is submitted as it is created by Apple, no changes have been made the the file and this is exactly the same format that Apple has provided `pkey` files for as long as I have records. Therefore, I can only assume that this is an error in the Ruby SDK.

**Comment by awood45** [comment]
It sounds like this could actually be a question for the service team, as we're almost certainly not touching the pkey itself for a client call. I'm going to reach out to them.

**Comment by gregk8288** [comment]
Thanks Alex, yes that does seem like the most likely cause.

**Comment by awood45** [comment]
I've talked to the SNS team, and they confirm that you will need to strip those parts of the pkey file out to get a successful API response. http://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformApplication.html

I have shared your concerns with them as feedback.

**Comment by gregk8288** [comment]
It seems really counter intuitive to break something that was working perfectly well for so long. But thanks for raising it none the less.

**Comment by awood45** [comment]
I hear you and I've pointed them to this issue. Nothing we can really do on the SDK side, as mentioned above this operation doesn't touch your inputs beyond wire protocol changes.
