### ISSUE TITLE
Presigned POST should be supported

### ISSUE THREAD

**Issue by bikegriffith** [aws/aws-sdk-ruby#1329]
I see that https://github.com/aws/aws-sdk-ruby/issues/743 was closed, suggesting that you should use the v1 and v2 SDK together if you want to pre-sign a POST (rather than just GET and PUT).

Currently

```
    s3_resource = Aws::S3::Resource::new(region: S3_REGION)
    object = s3_resource.bucket(S3_BUCKET_NAME).object(S3_PATH)
    object.presigned_url(:post)
```

fails with `ArgumentError (unknown operation "post_object")`

I would like to suggest that this feature is added to the v2 SDK directly.

**Comment by trevorrowe** [comment]
Good news, this was added a while back to v2. You can read the docs on the pre-signed post utility here:

http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/PresignedPost.html
