### ISSUE TITLE
Aws::S3::Resource#bucket returns nil when bucket name is nil

### ISSUE THREAD

**Issue by janko-m** [aws/aws-sdk-ruby#1332]
```rb
resource = Aws::S3::Resource.new(region: "eu-west-1")
resource.bucket("name") #=> #<Aws::S3::Bucket name="name">
resource.bucket(nil)    #=> nil
```

The S3 bucket name is often passed in via an ENV variable, and if the ENV variable is accidentally missing, it causes `undefined method for nil:NilClass` errors only later.

I think it would be great if `Aws::S3::Resource#bucket` would immediately raise an error if `nil` was passed in, since that's not a valid bucket name.

**Comment by Doug-AWS** [comment]
We recommend you always try the client head_bucket method to verify whether a bucket exists and you have access. See http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#head_bucket-instance_method.

**Comment by janko-m** [comment]
Thanks, but this is executed when app is initializing, so it would be ideal that we don't execute any HTTP requests there. I'm suggesting to make the above method also throw an ArgumentError.

**Comment by Doug-AWS** [comment]
Except it would likely break a ton of other developer's code.

**Comment by janko-m** [comment]
I agree. Would at least adding a warning that `nil` was passed make sense?

**Comment by trevorrowe** [comment]
@janko-m Constructing any resource with a `nil` identifier now raises an `ArgumentError`. This was originally the intention, but the code was checking if the options has contained the identifiers key, but not if it had a non-empty value. Thanks for reporting the issue!
