### ISSUE TITLE
get_object returning small chunks of data (16kb - 1kb)

### ISSUE THREAD

**Issue by rubemz** [aws/aws-sdk-ruby#1339]
I've an implementation that looks like this

```ruby
s3_client.get_object(bucket: 'bucket', key: 'key', version_id: 'version') do |chunk|
  IO.copy_stream(StringIO(chunk), io_object)
end
```

but the chunk size is really small, always around 1kb - 16kb. 

**Is there a way to specify the chunk size?**

Unfortunately I couldn't find anything in the docs. And I'd like to increase the chunk size to make the streaming process faster since reading chunks of 16kb is not optimal in my case, since we're dealing with large files.

**Comment by trevorrowe** [comment]
The SDK uses `Net::HTTPResponse#read_body` which does not allow us to control the chunk sizes. I'm not familiar with a way to tune the chunk sizes that Net::HTTP returns.

**Comment by mihairadulescu** [comment]
@rubemz did you find a way to make the chunks bigger ?

**Comment by mihairadulescu** [comment]
` def download_chunk(bucket, file_key)
        @client.get_object(bucket: bucket, key: file_key) do |chunk|
          yield chunk
        end
      end

      def download_chunk_of_size(bucket, file_key, size)
        content = ''
        download_chunk(bucket, file_key) do |chunk|
          p 'merging chunks'
          p size
          if content.length < size && !chunk.empty?
            p content.length
            content += chunk
          else
            p 'yielding chunk`s of size`'
            yield content
            content = ''
          end
        end
        yield content unless content.empty?
      end
`
