### ISSUE TITLE
Slow SQS receive of JSON msgs when bundler/setup present

### ISSUE THREAD

**Issue by penntaylor** [aws/aws-sdk-ruby#1344]
OS: Ubuntu 14.04
SDK version: 2.6.19

Description of problem:

Receive operation in SQS is *significantly* slower (factor of 3 to 30) when queue messages are structured as JSON and `bundler/setup` is required by the program. Take `bundler/setup` out and receive operation speed goes back to normal. Issue also has the following characteristics:

* Slowdown factor increases as message body size increases.
* Less severe when message body is YAML.
* No detectable slowdown when message body is random chars.

My real-world use case involves 85 kB JSON body payloads. I'm seeing receive rates drop from ~25msg/s to ~1msg/s at this size when toggling between `bundler/setup` absent and present.

Complete example is attached. Usage instructions are in the README included in the archive.
[bundler_sqs_issue.zip](https://github.com/aws/aws-sdk-ruby/files/587081/bundler_sqs_issue.zip)

**Comment by penntaylor** [comment]
This issue is not present in the 1.x versions of aws-sdk-ruby. We've been seeing this issue's symptoms since switching to aws-sdk-ruby 2.x in February 2016, but hadn't been able to isolate the exact circumstances until now.

**Comment by trevorrowe** [comment]
Can you share a copy of your Gemfile? Also, have you attempted to see where the time is spent? Is it time waiting for the response bytes (slow HTTP?) or perhaps in parsing/loading the JSON?

**Comment by penntaylor** [comment]
Gemfile as well as lock are both in the zip attached to the issue. Duplicating here:

Gemfile:
```
source "https://rubygems.org"

gem 'aws-sdk'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    aws-sdk (2.6.19)
      aws-sdk-resources (= 2.6.19)
    aws-sdk-core (2.6.19)
      jmespath (~> 1.0)
    aws-sdk-resources (2.6.19)
      aws-sdk-core (= 2.6.19)
    jmespath (1.3.1)

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk
```

**Comment by penntaylor** [comment]
After looking into this more, I figured it out. The difference between the two cases comes down to REXML vs. Nokogiri. No `bundler/setup` means existing Nokogiri installation (from aws-sdk-ruby v1 !) gets picked up and used for parsing XML. Adding `bundler/setup` cuts out Nokogiri and forces use of *significantly* slower REXML. Adding Nokogiri to Gemfile brings performance of with-bundler/setup case up to same speed as no-bundler/setup case.

I don't recall seeing this mentioned in the documentation anywhere, and a quick search doesn't turn anything up. Not mentioned in the v1->v2 migration guide either, and migration is how we originally encountered this problem.

**Comment by trevorrowe** [comment]
We ran into significant problems with a hard dependency on nokogiri and opted to make this optional. There are other optional XML parsers. If the `ox` gem is present, that will also be used and runs even faster than nokogiri. 

There is a blog post, but it warrants adding this to the documentation in a few more places to aid in discovery.

**Comment by trevorrowe** [comment]
I'm going to close this as there doesn't appear to be an issue. I've reached out to someone internally about getting the developer guide updated to add content about performance tuning. Thanks for the heads up.

**Comment by penntaylor** [comment]
@trevorrowe, two quick questions on this issue: Is there documentation anywhere of other external dependencies aws-sdk can silently pull in as it does Nokogiri and Ox? Is there a config setting or environment variable that controls this behavior?
