### ISSUE TITLE
Is the limit in S3::Presigner::ONE_WEEK... flexible?

### ISSUE THREAD

**Issue by xmjw** [aws/aws-sdk-ruby#1345]
Sorry, this is a question but I'm not sure where else to put it:

I need to generate links to S3 objects that last for quite a bit longer than 1 week (1 month would be good). It seems I can do this with the v1 SDK, but I'm a touch worried about deprecation etc. Is there some specific technical reason this limit is imposed? Or is this more a matter of good security hygiene such that I could work my way around it? Suggestions welcomed!

**Comment by trevorrowe** [comment]
The limit in the v2 SDK is not flexible. The version 2 SDK uses AWS signature version 4. Sigv4 has the hard requirement that signatures are never valid for longer than 1 week. The v1 SDK uses an older signature version that does not have this limitation. While it still works in many circumstances, there are more and more operations, regions, and parameters are invalid/unusable unless you use signature version 4. Choosing to use an older version may come back to bite you in the future.

**Comment by trevorrowe** [comment]
Closing as a question, but please feel free to re-open if you have additional questions.
