### ISSUE TITLE
ECR describe_images no longer seems to exist

### ISSUE THREAD

**Issue by thattommyhall** [aws/aws-sdk-ruby#1349]
http://docs.aws.amazon.com/sdkforruby/api/Aws/ECR/Client.html#describe_images-instance_method

How can I get a list of the images, with push date now?

**Comment by Doug-AWS** [comment]
Try just **describe_images**. The response object should contain an array, **image_details**, from which you can get the push date from each entry's **image_pushed_at** property.

**Comment by awood45** [comment]
I'm actually noticing as well that the method appears to be missing, despite it being present in the API model. I'm investigating, but since your comment implied "no longer exists", can you tell me what version you used where it *did* exist? In either case, investigating.

**Comment by awood45** [comment]
Okay, something else interesting is that this varied across machines for me, so that's another thing to check. I do see this method on a new install of the gem.

What version of the gem are you using, and if you're in a Gemfile, what is your full set of current gems?

**Comment by thattommyhall** [comment]
@awood45 By "no longer" I am comparing to docs on the assumption that they are out of date (though on further thought I suppose they may have been auto-generated)

I was using 2.5.3, now updated to 2.6.28 and it does seem to work now. Sorry, I thought I had only just installed the gem so didnt think to upgrade it. Sorry for wasting your time!

Bests,
Tom

**Comment by awood45** [comment]
Docs are indeed generated/updated with each release. No worries, glad you got what you needed.
