### ISSUE TITLE
SQS - get_queue_attributes raises errors for FIFO attributes on non-FIFO queues

### ISSUE THREAD

**Issue by richseviora** [aws/aws-sdk-ruby#1350]
The FIFO queue attributes (FifoQueue, ContentBasedDeduplication) are only available on FIFO queue resources. Attempting to access them specifically raises an error. Given that `FifoQueue` has a value of `true` for FIFO queues, I expected that it would be `false` for standard/non-FIFO queues instead of not being available at all.

I think it'd be more intuitive if `FifoQueue` was `false` for non-FIFO queues. Is this a feasible change?

### Details

Asking SQS for FIFO queue attributes on non-FIFO queues raises the following error:

`Aws::SQS::Errors::InvalidAttributeName: Unknown Attribute FifoQueue.`

Steps to reproduce:

1. Create SQS FIFO queue.
2. Create SQS client object.
2. `sqs_client.get_queue_attributes(queue_url: 'URLHERE', attribute_names: ['FifoQueue'])`

**Comment by awood45** [comment]
Okay, I see what's going on here after some investigation. The service is the source of these errors, and will throw this error if you provide that attribute name to a queue that does not have FIFO enabled.

I'll pass your feedback on to the service team, but there isn't anything we can do from the SDK side (and indeed, we may not be able to change this now as it may be a breaking change to move from exceptions to returning `false`).

**Comment by mig281** [comment]
Hi, This is Mike K. the docs guy for SQS. Just trying to get some clarity. Currently, all API/SDK docs for the attribute are already prefixed with "The following attributes apply only to FIFO (first-in-first-out) queues"--why would anyone want to use the attribute with a non-FIFO queue? Or is the warning missing in a particular instance? Please clarify.

**Comment by mig281** [comment]
Currently, the documentation will not be changed. The service team is considering changing the API behavior right now.

**Comment by richseviora** [comment]
Howdy!

I wanted to get the FifoQueue attribute with a non-FIFO queue because I
needed to know whether the queue was FIFO, as that changes the message
attributes required.
We ran into this during testing for a PR I submitted
<https://github.com/phstc/shoryuken/pull/273> for the Shoryuken gem to
enable the use of FIFO queues within Rails and its ActiveJob integration.
