### ISSUE TITLE
NonExistentQueue could show the queue name

### ISSUE THREAD

**Issue by phstc** [aws/aws-sdk-ruby#1352]
When trying to lookup for a non existent queue, the SDK raises a generic message, which does not show the queue name, and depending on the setup, it isn't straighforward to find which queue is not found. For example: shoryuken tries to load all queues specified in the `shoryuken.yml`, and raising a generic error message, would require to investigate queue by queue to find which one is not found. 

Currently, [shoryuken rescues NonExistentQueue to give a specific message](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/queue.rb#L10), but it would be great to have it in the SDK instead.

```ruby
client.get_queue_url(queue_name: 'super_queue').queue_url

Aws::SQS::Errors::NonExistentQueue: The specified queue does not exist for this wsdl version.
```

**Comment by pchaganti** [comment]
👍

**Comment by trevorrowe** [comment]
The error message is written by the service, and is simply returned and raised by the SDK. That said, the error object should respond to the method `#context`. The context object contains the request parameters.

```ruby
begin
  client.get_queue_url(queue_name: 'q-name')
rescue Aws::SQS::Errors::NonExistentQueue => error
  puts "Queue #{error.context.params[:queue_name]} not found"
end
```

**Comment by phstc** [comment]
@trevorrowe I understand that, but I was wondering if the sdk could abstract that and raise up a more explicit message, so the clients don't need to rescue, in order to raise a more descriptive error message.

**Comment by awood45** [comment]
Added to feature request backlog.
