### ISSUE TITLE
3.0.0.rc1 release requires non-existent aws-sdk-cloudwatch release (1.0.0.rc1)

### ISSUE THREAD

**Issue by BanzaiMan** [aws/aws-sdk-ruby#1356]
https://rubygems.org/gems/aws-sdk/versions/3.0.0.rc1 requires aws-sdk-cloudwatch 1.0.0.rc1, but this version does not exist. https://rubygems.org/gems/aws-sdk-cloudwatch/versions

**Comment by BanzaiMan** [comment]
I have not checked all the other dependent gems, so aws-sdk-cloudwatch may not be the only one.

**Comment by awood45** [comment]
We're working on this, there was a gem name collision.

**Comment by awood45** [comment]
This has been resolved, we have that gem now, and you should be able to install the RC gems. Please let us know if you see more issues!
