### ISSUE TITLE
v2.6.33 and v2.6.34 are identical.

### ISSUE THREAD

**Issue by chottoda** [aws/aws-sdk-ruby#1357]
v2.6.34 was tagged to wrong comit?

**Comment by awood45** [comment]
That is a good callout - I see that the commits are there, but the tag as you say is in the wrong place. I'll fix this tomorrow with another release for the new features in `2.6.34`, thanks for letting me know.

**Comment by awood45** [comment]
Version 2.6.35 is being released now and will resolve this issue. Thanks for the report!
