### ISSUE TITLE
Custom user agent per client?

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1363]
Is there any way to set the user-agent at client construction time? We use the SDK for many different functions, and it would be great if we can set the user-agent per the functionality. 

We currently register a custom user agent plugin, but that is used for all the clients.

thanks!

**Comment by awood45** [comment]
Use the `:user_agent_suffix` option, like so:

```
s3 = Aws::S3::Client.new(user_agent_suffix: "example1")
ec2 = Aws::EC2::Client.new(user_agent_suffix: "example2")
```

It will add your suffix to the end of the user agent string.
