### ISSUE TITLE
uninitialized constant Aws::CognitoIdentityProvider

### ISSUE THREAD

**Issue by rayson1223** [aws/aws-sdk-ruby#1364]
Hi,

I had download the latest version of aws-sdk-ruby, v2.6.35 in my Rails.

However when I try to initialise Aws::CognitoIdentityProvider class, it throw me. 
`uninitialized constant Aws::CognitoIdentityProvider`

And when I try to list down all possible Cognito Class, it just doesn't have CognitoIdentityProvider this class support. 

![screen shot 2016-12-14 at 8 47 44 pm](https://cloud.githubusercontent.com/assets/2102067/21182544/ad5a1216-c23e-11e6-975c-19c5cca4c39c.png)

Any help will do.

Thanks

**Comment by awood45** [comment]
I can't reproduce this, the class definitely exists when I run this version of the SDK.

How are you trying to create a client?

**Comment by rayson1223** [comment]
Sorry, I delete and reinstall again no more issues.
