### ISSUE TITLE
Aws::S3::Errors::InvalidArgument#message Should Fallback to #code if There's No Message

### ISSUE THREAD

**Issue by sshaw** [aws/aws-sdk-ruby#1376]
In my case the value given to the `:acl` option was invalid. The above exception was raised but its `#message` was blank (S3 returned an empty `Message` element). 

In this case the message should be derived from the code and maybe something else. This will make error handling a bit easier. 

Example:

```rb
require "aws-sdk"

c = Aws::S3::Client.new(:region => "us-east-1")

begin
  c.put_object(
    :key => "some-key",
    :bucket => "some-bucket",
    :acl => "bad",
    :body => "foo foo"
  )
rescue => e
  p e.message
  p e.code
  puts e.context.http_response.body.read 
end
```

Output:

```
""
"InvalidArgument"
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message></Message><ArgumentName>x-amz-acl</ArgumentName><ArgumentValue>bad</ArgumentValue><RequestId>4100B0D27DA794CB</RequestId><HostId>WJRcejt0hMF9bjHjqoA7CdzNXTr0cGf7VapGSjllI1ced0wr/7ZkfWoZN6xjoidffQ6PqQ7nQvI=</HostId></Error>
```

**Comment by awood45** [comment]
Thanks for the suggestion - we need to look at if there would be any complications with other services, but I agree that experience isn't optimal.

**Comment by awood45** [comment]
Added this as a second reference to an existing Feature Request.
