### ISSUE TITLE
Resource objects are too big in memory

### ISSUE THREAD

**Issue by Ladas** [aws/aws-sdk-ruby#1379]
Hello,

when I call:

client.describe_images(:executable_users => [:all])

on east-us region, there is around 76k of images. The actual JSON should be not that big, it should be max 50MB. But the call actually takes around 600 mb in memory.

So I am reading that EC2 doesn't support pagination, otherwise the best would be to return enumerable like in S3, right?

But could we at least return enumerable that would only instantiate (and not store) 1 resource at the time?

We do need to fetch all the images, in some cases. But I assume the same issue is for the whole EC2, so having 10000s of instances will also bloat memory a lot.

**Comment by awood45** [comment]
You have the right understanding, and optimizing resource memory usage is something we could take a look at. I'd recommend for the [#describe_images](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_images-instance_method) API that you use the `:filters` parameter to keep the response size down. The [#images](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#images-instance_method) method on the resource supports these same params.

**Comment by Ladas** [comment]
@awood45 it would also help if there would be a call returning just an array of hashes

I see it in the docs for stacks, cfm.stack_summaries, so something similar? But weirdly enough cfm.stack_summaries method doesn't exist when I try it.

**Comment by awood45** [comment]
Added to the feature request backlog.

**Comment by Ladas** [comment]
@awood45 thank you :-)
