### ISSUE TITLE
[AWS::S3] Support for custom query parameters in presigned URLs

### ISSUE THREAD

**Issue by dougal** [aws/aws-sdk-ruby#1384]
# Proposal for Feature

I would propose to allow, and to add to the signed parameters, any parameter which begins with an `x-`, but not `x-aws`. This allows custom parameters, while preventing collision with any of the AWS parameters.

Example:

    signer = Aws::S3::Presigner.new
    url = signer.presigned_url(:get_object, bucket: "bucket", key: "key", { 'x-foo' => 'bar' })

 # Use Case

I wish to add a custom parameter to those which are used to create the signature. This would allow the identification of individual URLs in the S3 access logs, allowing us to assert whether or not a user has successfully completed download of a file.

# What We've Tried

We tried adding various keys to the `params` argument of the `Aws::S3::Presigner#presigned_url`, all of which cause the parameter checking to raise an error.

It appears that only the following keys are allowed by the parameter checking:

    bucket
    if_match
    if_modified_since
    if_none_match
    if_unmodified_since
    key
    range
    response_cache_control
    response_content_disposition
    response_content_encoding
    response_content_language
    response_content_type
    response_expires
    version_id
    sse_customer_algorithm
    sse_customer_key
    sse_customer_key_md5
    request_payer
    part_number

# Notes

I had a look at `types.rb` in the `aws-sdk-core` gem. It appears that the definition of `GetObjectRequest` would not allow such custom fields to be defined. I am therefor not sure how such a feature would be implemented. Perhaps someone more familiar with the code could suggest an implementation.

**Comment by awood45** [comment]
So, this sounds like this boils down to adding custom signed headers to a presigned URL, that are unrelated to the S3 call itself, is that right?

**Comment by dougal** [comment]
Custom signed query parameters, as opposed to headers, but yes.

Example:

    "https://examplebucket.s3.amazonaws.com/test.txt"\
    "?x-foo=bar"\
    "&X-Amz-Algorithm=AWS4-HMAC-SHA256"\
    "&X-Amz-Credential=AKIAIOSFODNN7EXAMPLE%2F20130524%2F"\
    "us-east-1%2Fs3%2Faws4_request"\
    "&X-Amz-Date=20130524T000000Z&X-Amz-Expires=86400"\
    "&X-Amz-SignedHeaders=host"\
    "&X-Amz-Signature=aeeed9bbccd4d02ee5c0109b86d86835f995330da4c26595"\
    "7d157751f604d404"

**Comment by cjyclaire** [comment]
PR #1477 is opened that supports this feature, tracking this feature request in that PR : )
Closing, feel free to chime in that PR with comments : )

**Comment by gotoAndBliss** [comment]
That PR request looked like it was for JS. Is there anything for Ruby on this?

We create URL's that lead to applets that use the parameter data to seed their responses ( such as the user_id, endpoint, etc. ).

Since we've upgraded to V3, this breaks with `AuthorizationQueryParametersError` as we are augmenting the presigner URL after initialization. Is there any way to seed this data into the URL upon creation?
