### ISSUE TITLE
Missing `message_group_id` from Aws::SQS::Message

### ISSUE THREAD

**Issue by atedja** [aws/aws-sdk-ruby#1385]
We now have SQS FIFO queues, so I think `Aws::SQS::Message` needs `message_group_id` now.

[Documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Message.html)

**Comment by awood45** [comment]
Thanks for bringing this up - happy to take a PR, otherwise will look at altering the resource definition and passing that up to the other SDKs.

**Comment by cjyclaire** [comment]
Tracked in [backlog](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#add-message_group_id-to-sqs-message-resource-object-definition), meanwhile happy to take a PR for review and pull upstream : )
