### ISSUE TITLE
Aws::CloudFront::UrlSigner fails with more than one query parameter

### ISSUE THREAD

**Issue by dobrite** [aws/aws-sdk-ruby#1386]
Using the following code I am able to successfully access a file from Cloudfront pointed at S3. All query parameters are forwarded in the Cloudfront distribution.

```ruby
signer = Aws::CloudFront::UrlSigner.new(key_pair_id: '...', private_key: '...')
signer.signed_url("https://abc.cloudfront.net/test.txt?one=red", expires: 5.minutes.from_now)
```

However, when using 2 query parameters I get the standard XML "Access Denied":

```ruby
signer.signed_url("https://abc.cloudfront.net/test.txt?one=red&two=blue", expires: 5.minutes.from_now)
```

I poked at the code, but didn't turn up anything obvious.

Thank you for any insight on this.

**Comment by dobrite** [comment]
I was able to get it to work with the aws cli using `aws cloudfront sign`. This points to a bug in this library. I'll work on providing a failing spec.

**Comment by dobrite** [comment]
I was able to generate valid signatures using the test case, but not in my development environment. This points to an issue with my development environment (open ssl?), and not this library. I'll reopen this issue if I find something otherwise, but for now I don't want you to waste any (more) time on this.

**Comment by awood45** [comment]
Please do also update us if you find something that fixes your local environment, in case this comes up again. Thanks!

**Comment by dobrite** [comment]
Ok, I figured it out!

Rails has a [default](http://stackoverflow.com/questions/27379432/prevent-rails-from-encoding-the-ampersands-in-a-url-when-outputting-json/27460529#27460529) setting that encodes `&` as `\\u0026` which explains why the signatures didn't match when an ampersand was involved. It also explains why the test case produced valid signatures and my dev environment didn't (Rails was loaded).

As a workaround `JSON.dump(json_hash)` can be used [here](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/cloudfront/url_signer.rb#L141). This will fix cloud front url signer for vanilla Rails apps when an ampersand is involved.

Does that sound like a reasonable fix?

```
# Rails irb
[35] pry(main)> JSON.generate(json_hash)
=> "{\"Statement\":[{\"Resource\":\"http://www.google.com?q=blah&a=yo\",\"Condition\":{\"DateLessThan\":{\"AWS:EpochTime\":191981981981}}}]}"

# Ruby irb
[36] pry(main)> json_hash.to_json
=> "{\"Statement\":[{\"Resource\":\"http://www.google.com?q=blah\\u0026a=yo\",\"Condition\":{\"DateLessThan\":{\"AWS:EpochTime\":191981981981}}}]}"
```

**Comment by awood45** [comment]
Great catch! Would you like to open a PR, or would you like me to apply the fix? I think your fix is sound (though my PR review would be to check if there's any meaningful difference between `#dump` and `#generate` just to be safe).

**Comment by dobrite** [comment]
I opened PR #1390 to address this issue.

**Comment by awood45** [comment]
Thanks for the PR, I've merged and this will go out with our next release.
