### ISSUE TITLE
change-set-create-complete waiter not supported for CloudFormation

### ISSUE THREAD

**Issue by krishnan-mani** [aws/aws-sdk-ruby#1388]
On version 2.6.44, attempting to wait on ```change-set-create-complete``` throws an error:

```
client.wait_until(:change_set_create_complete, stack_name: stack_name)
```
throws error
```
Aws::Waiters::Errors::NoSuchWaiterError: no such waiter :change_set_create_complete; valid waiter names are: :stack_exists, :stack_create_complete, :stack_delete_complete, :stack_update_complete
```

**Comment by awood45** [comment]
Indeed, that does not appear to be a waiter we have implemented. Adding as a Feature Request.

**Comment by cjyclaire** [comment]
@krishnan-mani  The waiter files in SDK are automatically generated. And this waiter has been added from root, will be included and tagged in release soon! Closing, I'll ping the SIM once it gets out : )
