### ISSUE TITLE
Access object from client class

### ISSUE THREAD

**Issue by papadeltasierra** [aws/aws-sdk-ruby#1392]
I can create objects from the Aws::S3::Client class e.g. with put_object() but having done this there is no way to get access to them so that I can, for example, run Aws::S3::Object.public_url().
Similarly, it's not possible to get from Aws::S3::Client to Aws::S3::Bucket.  In fact providing the access from client to bucket would solve both issues since I can get from bucket to object.

**Comment by cjyclaire** [comment]
@papadeltasierra Thank you for the feedback! So to clarify first, it's true that `s3_client.put_object(..)` is returning the response for `put_object` API call, it has nothing to do with resource objects. 

Meanwhile, it might appear easy to make the `client` accessible from resource object, yet taking a second thought, it's kind of mixing and chaining the OO style for the resource concept. Also, now it's quite easy to have an S3 resource object like `Aws::S3::Object.new(bucket_name: 'a-fancy-bucket', key: 'wow')` :), could you explain more about why it could be a pain when the conversion is not available?

**Comment by papadeltasierra** [comment]
cjyclaire, perhaps the problem I'm trying to solve will explain.  I'm using S3 storage from a Rails application and for upload (user => S3 => Rails) that's easy because the user uploads a file of a known size.  The download is more difficult because normally Rails is creating the file 'on the fly (streaming until I reach the end effectively)' so I can't just create an obect because I don't know the size and I don't want to be storing <insert some totally unknown value> of bytes in memory until I have created the entire file.  So I'm using a trick that others seem to use, namely to write a Rails IO-like class that creates a series of 6MB (>5MB) S3 objects, and then uses a multipart upload to merge them (if there are >= 2 of the original objects).  Now I can create the objects from either S3:Bucket or S3:Client APIs but the multipart can only be created using S3:Client API calls.  Having done this, I would then like to return the public_url of the final object to the user, but there is no way to get from S3:Client => new multipart object => public_url because the only  public_url API call I can find is on the S3:Object.
I don't know the manner in which you've designed the various classes (is there a nice picture somewhere? I like pictures ;-) ) and I really don't care what the final solution is providing I can start from a single S3:Xxxx class and do all the stuff I need from this one point.  As you will see, I'm currently stuck with having to do the multipart stuff from S3:Client which produces an S3:Object, that I can't access,  whose public_url  I can only access via S3:Bucket -> S3:Object.
I hope that explains my dilemma.

**Comment by cjyclaire** [comment]
@papadeltasierra Thank you for the description above, appreciate that!

There is a lot going on, so before providing solutions or tag this as feature request, just quick clarify to see if I understand the situation correctly : ) 

You are using S3 Multipart upload and would like to have an `S3::Object` as result output to utilize the `public_url()` method. There is something I'm still a bit confused, since you could already to upload with resources like 
``` ruby
  obj = Aws::S3::Object.new(..)
 # reference: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/object.rb#L217
  obj.upload_file( ... ) # This integrates with Multipart with configuration options
```
Why are you suggesting the object is not available? Maybe as you have mentioned, you are managing multipart upload all by yourself with client api calls? (If this is the case, parameters like `bucket` or `key` could be accessed from `resp.context.params`. )

Also, a quick note for download, we do have PR #1213 under review, which will introduce the multipart downloader :)

Appreciate your patience on this :)

**Comment by trevorrowe** [comment]
@papadeltasierra A couple of thoughts or suggestions.

* It sounds like you are receiving an upload stream from the user which you are buffering into 6MB parts, so that you can upload using the multipart upload interface. This avoids the need to know the total size of the object and/or buffering the entire object into memory. Have you considered having the user upload directly to S3 and not pass the bytes through your rails stack? There are a handful of mechanisms to do this. If they are using a browser, you can create a pre-signed POST form that will upload directly to S3. If not using a browser, you can use a presigned URL and have then put the object to s3. Both of these mechanisms allow you to apply constraints on the object.

* Given an Aws::S3::Client object you can use this to initialize any S3 resource class. For example:

```ruby
client = Aws::S3::Client.new(...)

# using the class constructors directly
b = Aws::S3::Bucket.new('bucket-name', client: client)
o = Aws::S3::Object.new('bucket-name', 'object-key', client: client)

# using the Aws::S3::Resource class
s3 = Aws::S3::Resource.new(client: client)
b = s3.bucket('bucket-name')
o = s3.bucket('bucket-name').object('object-key')
```

**Comment by papadeltasierra** [comment]
Sorry for the tardy response; I missed some posts earlier.  I'm not having an enduser upload a file rather the Rails application is generating a file on-the-fly ready for the enduser to download it later.  For example, think of a list of clients in a CSV file - the enduser (via a webpage) asks 'I need an address list for all my north American clients', the Rails application makes a filtered query to its database and then creates a CSV file 'line/address by line/address'.  This sort of streamed write ot an S3 object of unknown size is not possible so I'm doing the following to work around this.

- Rails buffers up to 6MB of addresses into memory
- Rails then writes this memory data into a single S3 object of 6MB
- Rails repeats this, building up a list of 6MB S3 objects, plus a final (probably smaller) S3 object
- Now Rails uses the S3 multipart upload to create a single 'big object' from the many 6MB+smaller objects; the 6MB S3 objects are the input and the final big object is the output and the enduser is not involved in this step at all.

This much works fine but at the very end, how do I tell me end user (probably via an e-mail) how to download the address list?  I want to know the public_url of the final large S3 (multipart) object.  And I want all of the processing above to ideally be wrappable into a single S3/Rails class so that my Rails application treats this hoop-jumping as 'just writing to a file' as much as possible.

It seems I need to do all the buffer, write, merge to multipart via the S3::Client class but then there is no way to find the public_url of the final object and I need to switch to the S3::Bucket class to find the final S3 object and get it's public_url.

I appreciate that this is probably not an intended use of the interface but a quick Google implies that there are many people out there making use of this 'loophole' and it would be nice (at least for me :-) ) if the last bit of the process were that tiny bit simpler and integrated.

I hope that clarifies what I'm doing.
Thanks,
Papadeltasierra.

**Comment by awood45** [comment]
So, keep in mind here that `#public_url` is a method we provide in the resource interfaces, as a convenience. Implementation is like so:

```ruby
def public_url(options = {})
  url = URI.parse(bucket.url(options))
  url.path += '/' unless url.path[-1] == '/'
  url.path += key.gsub(/[^\/]+/) { |s| Seahorse::Util.uri_escape(s) }
  url.to_s
end
```

The thing to illustrate here being that there's no magic in constructing the URL, you could build this behavior yourself over client responses. There are two choices here:

First, you could just create a resource object and use the method there:

```ruby
# This is the client operation you can that completed the multipart upload described above
client.complete_multipart_upload(bucket: bucket, key: key, upload_id: upload_id)
obj = Aws::S3::Resource.new(region: region).bucket(bucket).object(key)
obj.public_url # Use this
```

Second, you could use the fact that you know your exact bucket name to do it yourself. Note that with this approach you may need to be aware of things like URI escaping:

```ruby
client.complete_multipart_upload(bucket: bucket, key: key, upload_id: upload_id)
url = "https://#{bucket}.s3.amazonaws.com/#{key}"
```

The first approach might be cleaner if you're worried about edge cases, the second approach is mainly shown as an example of what is going on at a high level.

**Comment by awood45** [comment]
Does this help you get what you need? If not, I can adapt this approach based on how your code works. Adding this to the client directly seems potentially problematic.
