### ISSUE TITLE
Aws::S3::PresignedPost does not allow for extra headers

### ISSUE THREAD

**Issue by desheikh** [aws/aws-sdk-ruby#1399]
S3 presigned posts allow for arbitrary headers if they are included in the policy but Aws::S3::PresignedPost does not allow for it.

For example when trying to allow for an arbitrary  "x-requested-with" header.

This seems to be a regression from:
https://github.com/aws/aws-sdk-ruby/pull/297

**Comment by awood45** [comment]
Good point, it does look like we had this in V1. Taking this as a feature request, I'll take a look at copying over the old solution.

**Comment by cjyclaire** [comment]
This has been tracked in [backlog](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#port-over-the-ability-for-extra-headers-in-presignpost) to be prioritized : )

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.
