### ISSUE TITLE
Explicit port :80 on presigned_url with virtual_host set to true causes problems

### ISSUE THREAD

**Issue by kjwierenga** [aws/aws-sdk-ruby#1401]
**Problem statement**
`Presigner#presigned_url` with `virtual_host` set to `true` returns a URL where the port (for http) is explicitly set to `:80`. Some HTTP clients (in my case `ffprobe`) pass on this port in the `Host` header (`Host: files.mydomain.dom:80`) which invalidates the signature resulting in a `403 Forbidden` response.

**TL;DR**
It would be nice if `Presigner#presigned_url` didn't have `:80` in the URL so all HTTP clients can use the URL without problems.

**Full explanation**

First we show that `:80` is indeed included in the presigned URL.
```ruby
> params = { bucket: 'files.mydomain.com', key: 'song.mp3', virtual_host: true }
 => {:bucket=>"files.mydomain.com", :key=>"song.mp3", :virtual_host=>true} 
> Aws::S3::Presigner.new.presigned_url(:get_object, params)
[Aws::S3::Client 0 0.000621 0 retries] get_object(bucket:"files.mydomain.com",key:"song.mp3")  

 => "http://files.mydomain.com:80/song.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170127%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20170127T165250Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=5ce3411e5b4016a670c159c62e72563be1a4aa256d332185a9d7570b866c8b66" 
```

If we use this URL with curl everything we get a `HTTP/1.1 200 OK`.
```bash
$ curl -s -v "http://files.mydomain.com/song.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170128%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20170128T104954Z&X-Amz-Expires=10800&X-Amz-SignedHeaders=host&X-Amz-Signature=c620db0d8e3615eb6e5fa6bc5027c1ccee5472c00b11b505de7af801328b75d4" -o /dev/null
*   Trying 52.218.64.40...
* TCP_NODELAY set
* Connected to files.mydomain.com (52.218.64.40) port 80 (#0)
> GET /song.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170128%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20170128T104954Z&X-Amz-Expires=10800&X-Amz-SignedHeaders=host&X-Amz-Signature=c620db0d8e3615eb6e5fa6bc5027c1ccee5472c00b11b505de7af801328b75d4 HTTP/1.1
> Host: media.kerkdienstgemist.nl
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
```

BUT, some HTTP clients will pass the `:80` port in `Host` header of the HTTP request which will result in a `403 Forbidden` (which we show with an explicit Host header to curl).

```bash
$ curl -s -v -H "Host: media.kerkdienstgemist.nl:80" "http://files.mydomain.com/song.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170128%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20170128T104954Z&X-Amz-Expires=10800&X-Amz-SignedHeaders=host&X-Amz-Signature=c620db0d8e3615eb6e5fa6bc5027c1ccee5472c00b11b505de7af801328b75d4" -o /dev/null
*   Trying 54.231.131.1...
* TCP_NODELAY set
* Connected to files.mydomain.com (54.231.131.1) port 80 (#0)
> GET /song.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2F20170128%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20170128T104954Z&X-Amz-Expires=10800&X-Amz-SignedHeaders=host&X-Amz-Signature=c620db0d8e3615eb6e5fa6bc5027c1ccee5472c00b11b505de7af801328b75d4 HTTP/1.1
> Host: files.mydomain.com:80
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
```

**Workaround**
My current workaround is to strip the `:80` from the URL returned by `presigned_url`.

```ruby
URI.parse(signer.presigned_url(:get_object, params)).to_s
```

**Conclusion**
It would be nice if `Presigner#presigned_url` didn't have `:80` in the URL in the first place (when virtual_host is set to true).

**Comment by awood45** [comment]
Thanks for already making the PR for this, will look at that.

**Comment by awood45** [comment]
#938 was the source of the line in question - making a note here as part of the regression testing.

**Comment by awood45** [comment]
Looking at the [relevant commit](https://github.com/aws/aws-sdk-ruby/commit/cc5300e71c0d4a4d286aa6b199cf9ec824716e31) and the current state of the code, it's possible that the setting of port 80 and the setting of the scheme to `http` may be redundant, which would mean the PR is ok. Still setting up a test environment.

**Comment by awood45** [comment]
[This commit](https://github.com/aws/aws-sdk-ruby/commit/29c60b9c5191230bbe3c29ffdc01c80828292ced) added the `http` scheme to the code.

**Comment by awood45** [comment]
Okay, there does appear to be a problem which makes this issue a bit more complicated than the included PR. Consider the original purpose of this code snippet, which is to switch the URI to http. For your use case of a non-standard port, your PR is fine:

```ruby
uri = URI("https://foo.bar:3000") #=> #<URI::HTTPS https://foo.bar:3000>
uri.port #=> 3000
uri.scheme = "http"
uri #=> #<URI::HTTPS http://foo.bar:3000>
uri.port #=> 3000
```

However, it doesn't work for the standard HTTP/HTTPS ports - that explicit setter is needed:

```ruby
uri = URI("https://foo.bar") #=> #<URI::HTTPS https://foo.bar>
uri.port #=> 443
uri.scheme = "http"
uri #=> #<URI::HTTPS http://foo.bar>
uri.port #=> 443 - wrong
```

That doesn't mean we can't fix this issue - I'd like to support your ability to set ports, but we need to do a bit more. I'll copy this comment to the PR.

**Comment by cjyclaire** [comment]
Closing, tracking this feature with PR #1477 instead : )
