### ISSUE TITLE
Explicitly set API Version

### ISSUE THREAD

**Issue by thomasv314** [aws/aws-sdk-ruby#1404]
Hi,

I'm trying to explicitly lock down the AWS API version used for specific endpoints.

Here's a list of everything I've tried:

            ::Aws.config = { ec2: { api: { version: '2016-09-15' } } 
            ::Aws.config[:ec2][:version] = '2016-09-15'
            ::Aws::EC2::Client.new(apiVersion: '2016-09-15')
            ::Aws::EC2::Client.new(api_version: '2016-09-15')
            ::Aws::EC2::Client.new(api: '2016-09-15')

I've scanned the docs and source code with to no avail, what am I missing?

Thanks!

**Comment by thomasv314** [comment]
Nevermind, it appears `::Aws::EC2::Client.api.version = '2016-09-15'` does the trick. 

Is this documented anywhere? I swear I've seen it before, though where exactly currently escapes me. It could have been in the aws-sdk docs for another language.

**Comment by awood45** [comment]
I actually don't see this clearly documented, and I'm not sure we would want to expose it that way.

Can you tell me a bit more about your use case here? What API version are you trying to lock to and why?

**Comment by thomasv314** [comment]
Thanks for the quick reply

In terms of use case: I have a number of API interactions that are recorded with VCR and they started breaking when I upgraded the latest version of the gem. 

I wanted to lock the API down as there were cassettes I didn't want to be forced to re-record. 

I was thinking I had seen this API locking functionality in the ruby sdk, but it turns it out was the [JS sdk](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html) (under 'Locking API Version')

**Comment by cjyclaire** [comment]
Thanks for getting back! Could you also elaborate a bit more on
> they started breaking when I upgraded the latest version of the gem

Are you noticing any breaking changes that is not backwards compatible?

**Comment by thomasv314** [comment]
Ah, apologies for not being clearer. I've not noticed any breaking API/backwards incompatible changes. 

The breaking aspect was strictly that the VCR cassettes include the API version in the request body, which meant previously recorded cassettes did not match the requests from the updated gem.

```yaml
- request:
    method: post
    uri: https://ec2.us-east-1.amazonaws.com/
    body:
      encoding: UTF-8
      string: Action=RebootInstances&InstanceId.1=i-3332f203&Version=2016-09-15
```

**Comment by awood45** [comment]
So, this would be a somewhat substantial feature request, as our current approach is to not keep older API versions around unless a breaking change exists (in which case there is a proper version update, such as what we did with `ElasticLoadBalancingV2`).

I'd recommend a review of your testing approach to not be reliant on the API version value in the request body being consistent, if at all possible.

I do appreciate the challenge here, so if you can tell me a bit more about your testing approach I may be able to provide advice or alternative approaches.
