### ISSUE TITLE
Documentation for describe_spot_price_history is misleading

### ISSUE THREAD

**Issue by Undo1** [aws/aws-sdk-ruby#1409]
[The documentation for `Aws::EC2::Client#describe_spot_price_history`](https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_spot_price_history-instance_method) gives this example:

```
resp = client.describe_spot_price_history({
  end_time: Time.parse("2014-01-06T08:09:10"), 
  instance_types: [
    "m1.xlarge", 
  ], 
  product_descriptions: [
    "Linux/UNIX (Amazon VPC)", 
  ], 
  start_time: Time.parse("2014-01-06T07:08:09"), 
})
```

After adjusting the timestamps to be within the last 90 days, it throws this error:

```
[AWS EC2 400 0.580757 0 retries] describe_spot_price_history(:end_time=>2017-02-01 13:40:45 -0700,:instance_types=>["m1.small"],:start_time=>2017-02-01 12:40:45 -0700) 

AWS::EC2::Errors::InvalidRequest The request received was invalid.
````

I was able to make it work by calling `iso8601` on the `Time` objects:

```
resp = client.describe_spot_price_history({
  end_time: Time.parse("2017-01-06T08:09:10").iso8601, 
  instance_types: [
    "m1.xlarge", 
  ], 
  product_descriptions: [
    "Linux/UNIX (Amazon VPC)", 
  ], 
  start_time: Time.parse("2017-01-06T07:08:09").iso8601, 
})
```

I'm having difficulties finding the source of the documentation, or I'd change it mysql.

Additionally, I might suggest automatically transforming `Date`s and `Time`s into the proper format.

**Comment by cjyclaire** [comment]
@Undo1 Ah interesting, I tried the example and it works for me actually (without using `. iso8601 `).
So I'm curious about what's going on, could you also tell me your OS environment, ruby version and SDK version? Also, we just updated our [`Getting Help`](https://github.com/aws/aws-sdk-ruby#getting-help) section in `README.md`, free feel to get engaged in other channel as well :).

**Comment by Undo1** [comment]
@cjyclaire Bah, was on `1.66.0`. Bundler probably snagged an ancient local version without telling me about it (or without me noticing, which is just as bad). 

It works as described now. Thank you for your time!
