### ISSUE TITLE
Aws::CloudFormation::create_stack not allowing EC2 t2.xlarge instance type

### ISSUE THREAD

**Issue by jaydee864** [aws/aws-sdk-ruby#1414]
Hello,

I'm trying to create a new CloudFormation stack using an EC2 t2.xlarge instance, and I am getting a ValidationError from the CloudFormation API:

```
/home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Parameter 'InstanceType' must be one of AllowedValues (Aws::CloudFormation::Errors::ValidationError)
        from /home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from /home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/seahorse/client/request.rb:70:in `send_request'
        from /home/jdestefano/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.7.4/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /mnt/c/Users/jdestefano/Documents/sandbox/aws/bin/cloudformation.rb:76:in `create_stack'
```

I am using the latest version of the Ruby SDK (2.7.4 at the time of this writing), though I saw the two new EC2 instance types were added to the EC2 API in 2.6.33. Is the validation for the CloudFormation templates separate from the resources themselves?

Please let me know if you need me to provide any further information.

Thanks,
Joe DeStefano

**Comment by awood45** [comment]
This appears to be an error from the service, not from the SDK. It isn't immediately clear to me from [CloudFormation's documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html) if there's a distinction.

If you're stuck, it may be worth raising a ticket with [AWS Support](https://console.aws.amazon.com/support/home) or asking a [StackOverflow question](http://stackoverflow.com/questions/tagged/aws-sdk-ruby). But as far as I can tell, this is a question for the service teams.

**Comment by jaydee864** [comment]
Thank you, I'll open a support case with AWS.
