### ISSUE TITLE
Aws::CloudFront::Client.list_distribution returns http_version=nil

### ISSUE THREAD

**Issue by herebebogans** [aws/aws-sdk-ruby#1421]
CLI for a cloudfront distribution with httpversion2 enabled

> aws cloudfront get-distribution --id XXXXX | grep -C 1 HttpVersion
> ....
> },
> "HttpVersion": "http2",
> "Restrictions": {
> ...

From the SDK ..

> [1] pry(#Awspec::Type::CloudfrontDistribution)> @resource_via_client
> => #<struct Aws::CloudFront::Types::DistributionSummary
> ....
> .....
> geo_restriction=#<struct Aws::CloudFront::Types::GeoRestriction restriction_type="none", quantity=0, items=[]>>,
> web_acl_id="f3238192-2d0e-431c-bf7b-ba2645dc74c6",
> http_version=nil>
> ....

....

**Comment by cjyclaire** [comment]
@herebebogans Thanks for the information, could you provide some code snippets that helps reproduce this `http_version=nil` issue? Also may I ask the SDK version used?

Interestingly, when I create a distribution with HTTP2 enabled, and get the distribution
``` ruby
resp = cloudfront.get_distribution(id: 'MY_ID')
resp.distribution.distribution_config.http_version # => this gives "http2"
```
I can get `http2` in the response.

**Comment by awood45** [comment]
I think what would be useful here is a wire trace. For example:

```ruby
cloudfront = Aws::CloudFront::Client.new(http_wire_trace: true) # plus other options
```

My suspicion if you're getting `nil` is that the service itself isn't returning the value, which becomes a different question.

**Comment by herebebogans** [comment]
Hi thanks for the quick response.

Using

$ bundle list | grep -i aws-sdk
  * aws-sdk (2.5.11)
  * aws-sdk-core (2.5.11)
  * aws-sdk-resources (2.5.11)

get_distribution returns as http_version=2
list_distribution returns as http_version=nil

Quick Example.

```
cf = Aws::CloudFront::Client.new
resp = cf.get_distribution(id: 'XXXXX')
puts resp.distribution.distribution_config.http_version
resp = cf.list_distributions.distribution_list.items.select{ | item | item.id == 'XXXXX'}.first
puts resp.http_version
puts resp.http_version.nil?
```
Output

> http2
> <blank line>
> true

**Comment by herebebogans** [comment]
Hi - the wire trace output is to verboe to paste but shows the <httpversion></httpversion> tag for the get_distibution API call but NOT for the list_distributions API call.

Seems to be the only DistributuonConfig property not present - I think the http_version option was recently added to Cloudfront and possibly the API hasn't been updated??

Sorry - the whole reason this comes up is that the [awspec](https://github.com/k1LoW/awspec) gem uses list_distributiions and I'd like to be able to check this property

**Comment by cjyclaire** [comment]
@herebebogans Oh you are suggesting `list_distributions`, I saw your cli command is using `get_distribution` that why I tried that.

I could reproduce this with our SDK, yet I just tested, if you try cli with `list_distributions`, you will find that they don't have response for "HttpVersion" as well. I wonder it might not be a bug specific bounds to our SDK, rather an API behavior, I'll dig more into that and try to verify that with service team, will keep updating

**Comment by herebebogans** [comment]
OK thanks - sorry for the get/list confusion.

**Comment by cjyclaire** [comment]
@herebebogans Just quick update, service team is investigating the issue and working on fix : )

**Comment by herebebogans** [comment]
Would it be to late to mention the logging property doesn't come through list_distributions either 😄

**Comment by cjyclaire** [comment]
@herebebogans Thanks, I'll pass this to service team : )

**Comment by cjyclaire** [comment]
@herebebogans The fix has been delivered : ) feel free to reopen with further question or comments
