### ISSUE TITLE
How do you specify stack_id at Aws::CloudFormation::Client.wait_until

### ISSUE THREAD

**Issue by 141984** [aws/aws-sdk-ruby#1428]
How do you specify stack_id at Aws::CloudFormation::Client.wait_until?

It works with stack_name as
`aws_cf_client.wait_until(:stack_create_complete, stack_name: "testStack")` 

But not with 
`aws_cf_client.wait_until(:stack_create_complete, stack_id: resp.stack_id)` 
gives:

> /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.3.4/lib/aws-sdk-core/param_validator.rb:26:in `validate!': unexpected value at params[:stack_id] (ArgumentError)

What is the correct param for stack_id?

**Comment by awood45** [comment]
The waiter is built on top of [#describe_stacks](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#describe_stacks-instance_method). It only accepts the `:stack_name` parameter, but you should be able to use `stack_id` as the value for that parameter per documentation.

If you still have problems, feel free to reopen.

**Comment by 141984** [comment]
Thanks, 
`aws_cf_client.wait_until(:stack_create_complete, stack_name: resp.stack_id)` works
