### ISSUE TITLE
AWS Ruby SDK Issue

### ISSUE THREAD

**Issue by agconstantin** [aws/aws-sdk-ruby#1431]
Hello,
I am trying to run the following Ruby code towards an AWS Linux AMI in order to patch it:
https://gist.github.com/agconstantin/740d7b829f0f1c8654698e5274af4d21

I have installed the required gem dependencies: 'aws-sdk' and 'cucloud'.
When I run the code, the following error in shown:
/usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/param_validator.rb:28:in `validate!': expected params[:filters][0][:values] to be an Array, got value "1" (class: String) instead. (ArgumentError)
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/share/ruby/gems/2.0/gems/aws-sdk-core-2.7.9/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /usr/local/share/ruby/gems/2.0/gems/cucloud-0.7.1/lib/cucloud/ec2_utils.rb:93:in `get_instances_by_tag'
	from ./aws_patch.rb:10:in `<main>'

Not been a proficiency Ruby developer, is this only a syntax error or?
Thanks.

**Comment by cjyclaire** [comment]
@agconstantin The error message suggests invalid parameter inputs in using our APIs, taking a look at their source code, it looks like a [bug](https://github.com/CU-CloudCollab/cucloud_ruby/blob/master/lib/cucloud/ec2_utils.rb#L96) in their repo, it's using a string, while our API requires [array](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_instances-instance_method).

This is something that needs to be fixed in `'cucloud'` : )
