### ISSUE TITLE
Timing out version 2.8

### ISSUE THREAD

**Issue by aledustet** [aws/aws-sdk-ruby#1434]
On the latest update with rails 4.2.8 the communication with the paperclip gem is timing out all the time.

Seahorse::Client::NetworkingError: execution expired

**Comment by awood45** [comment]
This isn't an SDK issue, Amazon S3 is seeing increased error rates in US-EAST-1, which is no doubt why you're seeing paperclip issues. https://status.aws.amazon.com/

I'll leave this open until the issue is resolved in case others come to report the same thing.

**Comment by blimmer** [comment]
That said, it would be nice if this were an `Aws::S3::Errors` namespaced exception so authors could catch it and handle it appropriately.

**Comment by awood45** [comment]
This issue is resolved, so closing this. The related issue will be a separate discussion.
