### ISSUE TITLE
source_profile key in shared_config not used to determine shared credentials

### ISSUE THREAD

**Issue by vStone** [aws/aws-sdk-ruby#1439]
Having
```ini
#~/.aws/config
[profile base-profile]
region = eu-west-1

[profile other-profile]
source_profile = base-profile
```

```ini
#~/.aws/credentials
[base-profile]
aws_access_key_id = FOOBAR
aws_secret_access_key = F00B4R
```

```ruby
require 'aws-sdk-core'
shared = Aws.shared_config
shared.credentials(profile: 'other-profile')
=> nil
```

Expected to return the base-profile credentials.

**Comment by vStone** [comment]
Looks like this should be done with the assume role credentials..

**Comment by cjyclaire** [comment]
@vStone Correct, `source_profile` is the parameter needs to be included part of assume role credentials,  yet `source_profile` alone won't work, you should also provide `role_arn`.

**Comment by cjyclaire** [comment]
Closing due to ages, feel free to reopen with further details or questions : )
