### ISSUE TITLE
No pre-rolled waiters for creating ALBs

### ISSUE THREAD

**Issue by kreynolds** [aws/aws-sdk-ruby#1440]

**Comment by awood45** [comment]
I'm not sure what this question refers to, can you elaborate?

**Comment by cjyclaire** [comment]
Adding to @awood45 's last comment, perhaps you are suggesting a waiter for [#create_load_balancer](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html#create_load_balancer-instance_method) of `elbv2`?

**Comment by kreynolds** [comment]
Yes, apologies for the vagueness. Many of the other operations (elasticache, rds, auto_scale_groups, etc) have populated #waiter_names to watch when they are in_service or not_exists or any number of other things. ElasticLoadBalancingV2 does not appear to even though it takes some time for it to become ready: http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html#waiter_names-instance_method

**Comment by cjyclaire** [comment]
@kreynolds Thanks for the clarify! Appreciate the information. So our waiters are automatically generate, I'll add the feature from root and have it in future release once it gets through. : )

**Comment by cjyclaire** [comment]
This feature will be delivered in today's release, closing : )

**Comment by cjyclaire** [comment]
Looks the the waiters doesn't get through in this release, yet it's merged from root, I'll fix the problem and have it pulled in at following release.
