### ISSUE TITLE
Presigned urls: Motivation for a maximum expiration of 1 week 

### ISSUE THREAD

**Issue by alfonsoperez** [aws/aws-sdk-ruby#1442]
Hi, I am aware of the maximum time a presigned url can be valid for since creation (1 week), but I struggle to find any explanation of this in the documentation.

Is there an specific reason for this?.

Thanks

**Comment by awood45** [comment]
#927 and #983 talk more about this. SigV4 signatures can't go beyond 1 week. I have added a note to the relevant documentation.
