### ISSUE TITLE
Ruby SDK ignores AWS_DEFAULT_PROFILE environment variable

### ISSUE THREAD

**Issue by leggiero** [aws/aws-sdk-ruby#1452]
The AWS_DEFAULT_PROFILE environment variable used by AWS CLI is ignored by AWS Ruby SDK.
Will be nice to have this feature on the Ruby SDK the same way that works on CLI.

See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html (Using Profiles with the AWS CLI)

**Comment by awood45** [comment]
We are considering supporting this, it may also be worth noting that `AWS_PROFILE` works similarly and I believe is also supported by the CLI.

**Comment by leggiero** [comment]
Thanks for considering the feature.
I'm using the AWS_PROFILE as alternative.

**Comment by awood45** [comment]
Adding to feature request backlog.
