### ISSUE TITLE
No way to add CloudTrail permission to SNS topic

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1454]
Sometime recently, AWS changed the way you add permissions to SNS topic to enable CloudTrail notifications. In the earlier version, you could add AWS account ids of the principals (which were accounts provided by the AWS docs).

Now that has changed, and you need to specify the service **_cloudtrail.amazonaws.com_** as the principal.

The SNS client does not seem to have a way to do this. If I use the **add_permission** method, it is looking for account ids. How can I add a permission like below to a topic?

```
{
	"Version": "2012-10-17",
	"Statement": [{   
		"Sid": "AWSCloudTrailSNSPolicy20131101",
		"Effect": "Allow",   
		"Principal": {
			"Service": "cloudtrail.amazonaws.com"
		},
		"Action": "SNS:Publish",   
		"Resource": "arn:aws:sns:Region:SNSTopicOwnerAccountId:SNSTopicName"
	}]
}
```

thanks

**Comment by awood45** [comment]
I'll reach out to the service team about this and get back to you. If you have an AWS Support account, I recommend opening an issue there as well.

**Comment by awood45** [comment]
It may also help if you can provide a code snippet showing what you used to do (feel free to anonymize details), and of what you're trying to do now. Thanks!

**Comment by pchaganti** [comment]
Sure. This is how we used to add a perm to allow trail notifications to new or existing topic previously. The AWS account ids are from the trail docs.

```Ruby
sns.add_permission(topic_arn: topic_arn, 
label: "CloudTrail Policy to publish Notifications of API Activity", 
aws_account_id: ["903692715234", "859597730677", "814480443879",
                                                                                                                                                               "216624486486", "086441151436", "388731089494", "284668455005", "113285607260", "035351147821"],  
action_name: ["Publish"])

```

This still works, but CloudTrail will not deliver notifications with this perm. The new way apparently is to provide the service cloudtrail.amazonaws.com as the principal. The [trail docs](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-permissions-for-sns-notifications.html) have also changed to show this - 

```
{
	"Version": "2012-10-17",
	"Statement": [{   
		"Sid": "AWSCloudTrailSNSPolicy20131101",
		"Effect": "Allow",   
		"Principal": {
			"Service": "cloudtrail.amazonaws.com"
		},
		"Action": "SNS:Publish",   
		"Resource": "arn:aws:sns:Region:SNSTopicOwnerAccountId:SNSTopicName"
	}]
}

```

There does not seem to be a way to do this from the API.

**Comment by pgollucci** [comment]
Agreed.  I have the same issue

aws sns add-permission --topic-arn arn:aws:sns:us-east-1:X:name --label StmtLabel --aws-account-id NOTHINGWORKSHEREFORCLOUDTRAIL  --action-name publish

**Comment by pchaganti** [comment]
Any further info on this?

thanks

**Comment by awood45** [comment]
So the `Aws::SNS::Client#set_topic_attributes` method seems to be the only way I can see - especially where the CLI has the same issue. This is a feature request for SNS, and I'll let them know but you should also contact support.

I would advise some caution about using `#set_topic_attributes`, in that it would make it pretty easy for you to mangle your "Policy" attribute and leave it unusable.
