### ISSUE TITLE
returns Aws::EC2::Resource.create_snapshot returns Aws::EmptyStructure

### ISSUE THREAD

**Issue by dElogics** [aws/aws-sdk-ruby#1458]
Sample code -- 

puts "creating snapshot"
bdsnap = resource.create_snapshot( { :volume_id => aGvolume.id, :description => "Programically created snapshot" } ).modify_attribute( { :attribute => "createVolumePermission", :operation_type => "add", :group_names => ["all"] } )
puts "waiting till snapshot completion..."
puts bdsnap.description
bdsnap.wait_until {
	|ashapshot|
	ashapshot.state != "pending"
}

Running this code results in -- 
creating snapshot
waiting till snapshot completion...
./aws.rb:36:in `<main>': undefined method `description' for #<struct Aws::EmptyStructure> (NoMethodError)

**Comment by cjyclaire** [comment]
@dElogics [#modify_snapshot_attribute](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#modify_snapshot_attribute-instance_method) is expected to return an empty structure in response. When using waiters, you could use waiters like:
``` ruby
ec2.wait_until(:snapshot_completed, snapshot_ids: ['snap-IDabcd123'])
 # OR
ec2.wait_until(:volume_available, volume_ids: ['volumes_IDabc123'])
# Complete Ec2 waiters list:
# https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/ec2/2016-11-15/waiters-2.json
```

**Comment by dElogics** [comment]
But as per this documentation it must not return a struct -- 

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#create_snapshot-instance_method

Requesting documentation update.
