### ISSUE TITLE
Stub resource in advance of creating it

### ISSUE THREAD

**Issue by AlexMorreale** [aws/aws-sdk-ruby#1459]
Basically I have created an object around an Aws::AutoScaling::AutoScalingGroup object and I am looking to stub out the calls to the AutoScalingGroup object in advance. 

I essentially want to have the AutoScalingGroup object "exist" without having the object actually exists in AWS? Is this possible

``` 
  def initialize(name)
    @name = name

    Aws::AutoScaling::AutoScalingGroup.new(name).tap do |asg|
      if asg.exists?
        @auto_scaling_group = asg
        @expire_on = asg.tags.detect { |t| t.key == "expire-on" }.value
        @role = asg.tags.detect { |t| t.key == "role" }.value
      end
    end
  end
```

**Comment by cjyclaire** [comment]
@AlexMorreale That's definitely possible, you might be interested in [`ClientStubs`](http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html), here are some quick example snippets, basically, you could stub responses for `#describe_auto_scaling_groups` with a mocking "exist" response
``` ruby
autoscaling = Aws::AutoScaling::Client.new(stub_responses: {
   describe_auto_scaling_groups: {
     auto_scaling_groups: [
        # Mock referencing : http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/Client.html#describe_auto_scaling_groups-instance_method
     ]
   }
})

# Then use this client whatever you want, even in resources
# Then whenever #describe_auto_scaling_groups is called, it's returning the stub responses
```

Hope this helps : )

**Comment by AlexMorreale** [comment]
@cjyclaire thank you very much, i will try this and get back to you.

**Comment by AlexMorreale** [comment]
hmm so I ended up doing this 

```
def stubbed_asg
  opts = [ # mocked calls ]

  Aws.config[:autoscaling] = {
    stub_responses: {
      describe_auto_scaling_groups: {
        auto_scaling_groups: opts
      }
    }
  }
end

and just calling this where ever i need the ASG stubbed. I suppose this will work.
```

**Comment by AlexMorreale** [comment]
It's not exactly what I wanted. I wanted to be able to make calls to non-existent ASGs and it return false for `asg_resource.exists?`

**Comment by cjyclaire** [comment]
@AlexMorreale Thanks for getting back, so `asg.exists` is actually using [`GroupExists`](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/autoscaling/2011-01-01/waiters-2.json#L4) waiter, it's making `describe_auto_scaling_groups` API call and evaluate the response for you. If you want it return false, you could have an empty array in the mocking response.

When you initializing a resource object, could you pass in [`:client`](http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/AutoScalingGroup.html#initialize-instance_method) option?

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further comments or questions : )
