### ISSUE TITLE
Ruby 2.4 Support

### ISSUE THREAD

**Issue by Kaelten** [aws/aws-sdk-ruby#1461]
I've checked out the test suite under ruby 2.4.  Unless I'm missing some it seems that there's at least some potential issues.   Find the results attached.
[test_failures.txt](https://github.com/aws/aws-sdk-ruby/files/859555/test_failures.txt)

**Comment by cjyclaire** [comment]
@Kaelten Thanks! Adding PR#1382 for tracking :)

**Comment by cjyclaire** [comment]
PR #1505 has been merged and will be tagged in the next release, closing, yet feel free to reopen with further questions or comments : )
