### ISSUE TITLE
next_token vs. token error ELB describe_load_balancers?

### ISSUE THREAD

**Issue by bingomanatee** [aws/aws-sdk-ruby#1481]
When I have the following code

       params = {page_size: max.clamp(20, ELB_DESCRIBE_MAX), next_marker: marker}
    begin
      response = elb_client.describe_load_balancers(params)
    rescue => err
      event.child_event("elbs_for_marker #{marker}: #{err.inspect}", 'error')
      return nil #stops future execution
    end

..and process the code I get the following error thrown:
ArgumentError: unexpected value at params[:next_marker]

However I noticed the underlying API parameter definition seems to require "marker" not "next_marker" so I tried again with 

       params = {page_size: max.clamp(20, ELB_DESCRIBE_MAX), marker: marker}

and got no errors. 

Is this an error in your code? the 'next_' convention seems to work in other contexts but not ELBs.

Thanks in advance.

**Comment by awood45** [comment]
Looking at the API definition, the input shape for the next token is `:marker`, and the output token from the service is `:next_marker`. This does break the usual convention, but our pagination definitions seem to handle this:
* [ElasticLoadBalancing Paginator](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/elasticloadbalancing/2012-06-01/paginators-1.json)
* [ElasticLoadBalancingV2 Paginator](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/elasticloadbalancingv2/2015-12-01/paginators-1.json)

You should be set if you change the code above to:

```ruby
   params = {page_size: max.clamp(20, ELB_DESCRIBE_MAX), marker: marker}
begin
  response = elb_client.describe_load_balancers(params)
rescue => err
  event.child_event("elbs_for_marker #{marker}: #{err.inspect}", 'error')
  return nil #stops future execution
end
```

**Comment by awood45** [comment]
You could also use the [built-in pagination functionality](http://docs.aws.amazon.com/sdkforruby/api/index.html#Paging_Responses).

Closing as I think we've got the answer here, feel free to reopen if that doesn't fix things for you.
