### ISSUE TITLE
Aws::SQS::QueuePoller randomly pauses and then starts again.

### ISSUE THREAD

**Issue by mhussain** [aws/aws-sdk-ruby#1484]
OS = Linux ip-10-0-34-87 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ruby = ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]
gem = 2.5.2
aws-sdk  = aws-sdk (2.9.7), aws-sdk-core (2.9.7). aws-sdk-resources (2.9.7)
region = ap-southeast-2

```ruby
client = Aws::SQS::Client.new(region: REGION)
queue_poller = Aws::SQS::QueuePoller.new(QUEUE_URL, client: client)

queue_poller.poll(
  max_number_of_messages: 10,
  wait_time_seconds: 3,
  skip_delete: true
) do |messages, stats|

  begin
    process(messages)
    queue_poller.delete_messages(messages)
  rescue SomeException => e
    logger.error "Could not process #{messages.size} documents"
  end

end
```

When I start the above process as an upstart job on an AWS instance, it starts fine, processes fine and then without fail, will stop after processing a random amount of messages. It will then stall for a random amount of time, and then start again :( 

Please help :(

**Comment by awood45** [comment]
I think we need some more information to help with this - there's nothing in the poller code inherently that would seem to be vulnerable to unplanned pauses.

In what stage is the poller stalling? Are you just not seeing processed messages over a period of time? How do you know it is stalling instead of just a period of time where no messages are received by the poll call?

**Comment by mhussain** [comment]
@awood45 Apologies if the initial issue seemed sparse on details as I was myself not sure what else to put in there because the code is simple enough and no errors/exceptions are being thrown at all.

> In what stage is the poller stalling?

Based on the debug messages, its always at the end of the polling loop. E.g. given the following code 

```ruby
poller.poll(....) do |m,s|
  logger.debug 'Starting poll...'

  SOME AMAZING CODE

  logger.debug 'End of poll'
end
```
It always pauses right after showing `End of poll`. 

> Are you just not seeing processed messages over a period of time?

Whatever it processes, I see immediately! The stall is that the code simply refuses to pull any new messages out of the queue, even though there are 100's.

> How do you know it is stalling instead of just a period of time where no messages are received by the poll call?

That's a fair point. I guess what I am seeing is that there are 100's of messages in the queue which this poller is polling. It processes a number, then simply stops even though there are more messages in it, and then after a random interval starts again. 

Hope this helps and thanks for your help 😄

**Comment by awood45** [comment]
I see what's going on here. The block is only triggered when messages are received. If you think that messages should be received but aren't, you could add wire tracing to your client. See the [Aws::SQS::QueuePoller#initialize](http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/QueuePoller.html#initialize-instance_method) method.

For example, you could make your QueuePoller like so:
```ruby
client = Aws::SQS::Client.new(region: REGION, http_wire_trace: true)
queue_poller = Aws::SQS::QueuePoller.new(QUEUE_URL, client: client)
```

If you're getting wire trace output during the "down" period, then SQS isn't receiving messages. If you're not getting wire trace output at all, that's more interesting. Try that and see which it is. But at a glance, there may not be an issue here.

**Comment by mhussain** [comment]
@awood45 Thanks for that tip. :) 

I put that option in and I can definitely see that the poller is talking to the queue. However, when the down period happens, nothing comes back, not even the http_wire_trace output.

**Comment by cjyclaire** [comment]
@mhussain Is this still happening frequently for you? I couldn't reproduce this with a sample poller usage from SDK side, you can also cut a support TT to [AWS Support](https://console.aws.amazon.com/support/home) that can help look into the request as well.

**Comment by cjyclaire** [comment]
Closing due to inactiveness, feel free to reopen with further questions or comments : )
