### ISSUE TITLE
No pre-rolled waiters for destroying ALBs

### ISSUE THREAD

**Issue by kreynolds** [aws/aws-sdk-ruby#1485]
Inverse of #1440, there are no pre-rolled waiters for destroying an ALB.

**Comment by awood45** [comment]
We're happy to take a PR, but in any case this would be a helpful feature request to take on.

**Comment by cjyclaire** [comment]
Soft update, changes have been merged, should be out in tomorrow's release  : )

**Comment by kreynolds** [comment]
excellent!

**Comment by cjyclaire** [comment]
This is tagged in the latest release, closing : )
