### ISSUE TITLE
NameError: uninitialized constant Aws::Organizations AWS Ruby-SDK

### ISSUE THREAD

**Issue by toshitapandey** [aws/aws-sdk-ruby#1491]
Able to create IAM, S3, EC2 clients but while trying same for Organizations, getting following error.

`pry(main)> Aws::Organizations::Client`
`NameError: uninitialized constant Aws::Organizations`
`from (pry):1: in __pry__'`

**Comment by awood45** [comment]
Just to check, what do you get from calling `Aws::VERSION` in the same pry instance?

**Comment by cjyclaire** [comment]
Adding to Alex's comments, `Aws::Organizations` is alive since [`v2.7.16`](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.7.16)

**Comment by toshitapandey** [comment]
Thanks @cjyclaire, I was using `v2.6` and that's why this issue.
