### ISSUE TITLE
CloudFormation::Client missing client_request_token support for create_stack/update_stack/delete_stack operations

### ISSUE THREAD

**Issue by bobziuchkovski** [aws/aws-sdk-ruby#1497]
The upstream CloudFormation API supports the `ClientRequestToken` param for the [CreateStack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html), [UpdateStack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html), and [DeleteStack](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DeleteStack.html) operations.

However, the latest published version of the aws-sdk for ruby (2.9.12) doesn't support the param for any of these operations.  Oddly enough, it _does_ support `client_token` for the [create_change_set](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#create_change_set-instance_method) operation, though.

Supporting `client_request_token` for `create_stack`, `update_stack`, and `delete_stack` would be incredibly helpful for us.  We use the CloudFormation NotificationArn support to log all of the stack operations that occur on our CloudFormation stacks.  These notification SNS messages include the corresponding `ClientRequestToken` value when it is specified.  If we could pass it from the ruby sdk, we would be able to correlate our API requests with the corresponding stack events.

**Comment by bobziuchkovski** [comment]
Hmm...it looks like I can make it work by editing `aws-sdk-core/apis/cloudformation/2010-05-15/api-2.json` and adding the `ClientRequestToken` shape and member definitions for those operations.  Is there anything else I'd need to update, or could I just submit those changes via a pull request?

**Comment by cjyclaire** [comment]
@bobziuchkovski Thanks for reporting and appreciate that! This API update is definitely in our radar and will be delivered through all SDKs soon : ) Stay tuned : )

**Comment by cjyclaire** [comment]
The API update has been included in the latest release, closing : ) Thank you for the patience.

**Comment by bobziuchkovski** [comment]
@cjyclaire Thank you very much for updating that so quickly!!
