### ISSUE TITLE
Wrong example on batch_write_item

### ISSUE THREAD

**Issue by omnibs** [aws/aws-sdk-ruby#1501]
Just wasted a couple of hours trying to figure out why I was getting a `Invalid attribute value type (Aws::DynamoDB::Errors::ValidationException)` after reading the example [here](http://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html#batch_write_item-instance_method).

The code shown there doesn't work, `batch_write_item` is apparently smart enough to figure out the data types and the `context.params` of my call was looking like this:

```ruby
{:request_items=>
  {"answers_development"=>
    [{:put_request=>
       {:item=>
         {"id"=>{:m=>{"n"=>{:n=>"123"}}},
          "some_field"=>{:m=>{"n"=>{:n=>"321"}}}
         }
       }
    }]
  }
}
```

It turned my attribute types from `:n` into `:m` with hashes as the values.

The "Request syntax with placeholder values" below is what hinted me at the correct input.

I'm not sure I can just go ahead and edit [this](https://github.com/aws/aws-sdk-ruby/blob/1fc503bd9d37a3456e09b28cce95e2eb083c373f/aws-sdk-core/apis/dynamodb/2012-08-10/examples-1.json#L77-L119) json file and it will be ok, so I'm opening an issue.

Incorrect format given in the example:

```ruby
...
      {
        put_request: {
          item: {
            "AlbumTitle" => {
              s: "Songs About Life", 
            }, 
            "Artist" => {
              s: "Acme Band", 
            }, 
            "SongTitle" => {
              s: "Happy Day", 
            }, 
          }, 
        }, 
      },
...
```

Format that worked:

```ruby
...
      {
        put_request: {
          item: {
            "AlbumTitle" => "Songs About Life", 
            "Artist" => "Acme Band", 
            "SongTitle" => "Happy Day", 
          }, 
        }, 
      },
...
```

**Comment by awood45** [comment]
Shared examples are written in a cross-SDK way, which wouldn't take simple attributes into account. We'll need to see how we can adapt those examples to look like they would in a call with the `:simple_attributes` setting on.

Thanks for the report!

**Comment by cjyclaire** [comment]
This has been tracked in our backlog, closing.

**Comment by brianolson** [comment]
This bug exists in the current documentation for put_item.
http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/DynamoDB/Client.html#put_item-instance_method
item => {"Field" => {s: "value"}} # does not work, doc example is wrong
item => {"Field" => "value}} # does work

**Comment by SatkarEE** [comment]
@cjyclaire is this issue fixed now or still exist?

**Comment by xzyfer** [comment]
It's 2024 and I just lost hours on this same issue.
