### ISSUE TITLE
Describe what characters are valid in service descriptions (ElasticBeanstalk in particular)

### ISSUE THREAD

**Issue by BanzaiMan** [aws/aws-sdk-ruby#1502]
# Problem

Some characters are rejected when used in Description in ElasticBeanstalk's `UpdateApplicationVersion` call, but what characters trip the error is not documented.

It would be great if we can have a list of valid characters for the description.

# Background

As reported in https://github.com/travis-ci/dpl/issues/462 and https://github.com/travis-ci/dpl/issues/604, some emoji characters are bad, but http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateApplicationVersion.html#API_UpdateApplicationVersion_RequestParameters only has this to say about the Description parameter:

<pre>
Description
  A new description for this version.

  Type: String

  Length Constraints: Maximum length of 200.

  Required: No
</pre>

https://github.com/aws/aws-sdk-ruby/blob/ae2f24ce8d444a9579154e187a7e203dbca2cd15/aws-sdk-core/apis/elasticbeanstalk/2010-12-01/api-2.json does not appear to be doing anything special (please correct me if I'm wrong), so I am guessing that the validation happens on the backend, and SDK is simply passing the exception back.

**Comment by cjyclaire** [comment]
@BanzaiMan Thanks for the information, appreciate that. Correct, SDK doesn't do anything special with that operation, I'll reach out to service team and let them know about this situation : ) Meanwhile, feel free to open a ticket to [AWS Support](https://console.aws.amazon.com/support/home) to get direct attention as well.

**Comment by cjyclaire** [comment]
This has been added to service team backlog and they are working on it, closing.
Yet feel free to reopen with further comments or requests : )
Thanks again for bringing this up.

**Comment by BanzaiMan** [comment]
From this, I take it to mean that the documentation would be updated to show the valid characters in version description in the near future.

Thank you very much for the quick turnaround!

**Comment by cjyclaire** [comment]
@BanzaiMan Exactly : )

**Comment by BanzaiMan** [comment]
@cjyclaire Hello. It's a bit over a month now, but the documentation has not been updated. Perhaps I'm a little impatient, but I'd appreciate some updates. Thank you!

**Comment by cjyclaire** [comment]
@BanzaiMan No worries, I'll follow up with service team with this : ) appreciate your patience!

**Comment by BanzaiMan** [comment]
@cjyclaire The documentation is still unclear. Could you check the documentation back log, if you can? Thank you!

**Comment by cjyclaire** [comment]
@BanzaiMan Apologies, I have pinged them again, will update

**Comment by BanzaiMan** [comment]
Hello there. I am sorry to ping again, but the documentation remains unclear. :-(
