### ISSUE TITLE
Add support for DynamoDB Accelerator (DAX)

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-ruby#1503]
Amazon DynamoDB Accelerator (DAX) was recently released in preview mode. Currently, only a Java client is available. Are there plans to include this in the Ruby SDK?

https://s3.amazonaws.com/dynamodb-preview-dax/DAX.html
http://dax-sdk.s3-website-us-west-2.amazonaws.com

**Comment by awood45** [comment]
Stay tuned on this one. I don't have a release date for this, but I'll pass on the request.

**Comment by kalpitad** [comment]
@awood45 -- Thanks for passing this along. Did you mean to close the issue?
