### ISSUE TITLE
Aws::EC2::RouteTable#routes has nil entry when IPv6 route exists

### ISSUE THREAD

**Issue by cunnie** [aws/aws-sdk-ruby#1510]
Behavior: Aws::EC2::RouteTable#routes has nil entry instead of IPv6 route. IPv4 route is present & accounted for.

Output from `pry-byebug` session:
```
[9] pry(#<Bosh::AwsCloud::Instance>)> table
=> #<Aws::EC2::RouteTable id="rtb-52235b36">
[10] pry(#<Bosh::AwsCloud::Instance>)> table.routes
=> #<Aws::Resources::Batch resources=[#<Aws::EC2::Route route_table_id="rtb-52235b36", destination_cidr_block="10.0.0.0/16">, nil]>
```
Screenshot of Route Table via GUI

<img width="614" alt="routes" src="https://cloud.githubusercontent.com/assets/1020675/25768517/594765de-31ba-11e7-8a92-65f4ac0cde6e.png">

Expected value of `table.routes`:
```
=> #<Aws::Resources::Batch resources=[#<Aws::EC2::Route route_table_id="rtb-52235b36", destination_cidr_block="10.0.0.0/16">, #<Aws::EC2::Route route_table_id="rtb-52235b36", destination_ipv_6_cidr_block="2600:1f1c:591:f000::/56"]>
```
Version of SDK **2.9.15**, from `Gemfile.lock`:
```
    aws-sdk (2.9.15)
      aws-sdk-resources (= 2.9.15)
    aws-sdk-core (2.9.15)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.9.15)
      aws-sdk-core (= 2.9.15)
    aws-sigv4 (1.0.0)
```

**Comment by awood45** [comment]
Can you provide a wire trace of your call? When you create a client or resource, just add a new parameter:

```ruby
client = Aws::S3::Client.new(http_wire_trace: true)
resource = Aws::S3::Resource.new(http_wire_trace: true)
```

That will help us diagnose the discrepancy.

**Comment by cunnie** [comment]
Hi @awood45 ,

I've posted a gist of the trace [here](https://gist.github.com/cunnie/1aa747751aa68aaab97932df38883677#file-route_table_trace-txt-L409). Line 409 seems to be the point of interest, and it seems to have the proper information.

I've redacted it to remove our rspec debugging lines and to anonymize our AWS KEY.  **please let me know if I have left any creds in the trace that may compromise the security of our AWS account**. Thanks.

**Comment by cjyclaire** [comment]
@cunnie Soft update, I can reproduce this, working on investigating

**Comment by cjyclaire** [comment]
@cunnie Quick update, the problem might has to do with resource models, it could be possible that our resource model is outdated. If using ec2 client directly, it works fine without problem:
```
ec2.describe_route_tables(route_table_ids:["rtb-11111111"])
# => both IPv4 and IPv6 are available
```

**Comment by cjyclaire** [comment]
@cunnie Soft update, this is caused by our resource model definition doesn't include `DestinationIpv6CidrBlock` in the [model](https://github.com/aws/aws-sdk-ruby/blob/code-generation/apis/ec2/2016-11-15/resources-1.json#L1445), it only includes `DestinationCidrBlock`.

I'll open a PR to address the fix shortly. Thanks for your patience

**Comment by cjyclaire** [comment]
PR #1513 is opened, which is under review.

**Comment by cunnie** [comment]
Thanks @cjyclaire — that's big help!

**Comment by cunnie** [comment]
@cjyclaire : I'm closing this issue because there's an open PR to fix and, on our end, we've inserted a nil-check in our code to get past this particular error. Thanks again for all your help.
