### ISSUE TITLE
Branch for v3

### ISSUE THREAD

**Issue by rhymes** [aws/aws-sdk-ruby#1512]
Where do I find the code and changelogs for V3?

Thanks

**Comment by cjyclaire** [comment]
@rhymes Thank you for the interest : )
The branch is [`code-generation`](https://github.com/aws/aws-sdk-ruby/tree/code-generation)
As for the changelog, each gem has it's own changelog, such as: [S3 Changelog](https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-s3/CHANGELOG.md). There is also `aws-sdk` [changelog](https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk/CHANGELOG.md) and `aws-sdk-core` [changelog](https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-core/CHANGELOG.md) as well.

**Comment by cjyclaire** [comment]
Closing, yet feel free to reopen with further questions : )
