### ISSUE TITLE
Relax v3 gems version of aws-sdk-core

### ISSUE THREAD

**Issue by rhymes** [aws/aws-sdk-ruby#1514]
Hi,

I'm using aws-sdk-s3 1.0.0.rc3 and aws-sdk-sns 1.0.0.rc1 succesfully without a problem.

I was trying to upgrade both to the latest rc version so I started with upgrading aws-sdk-sns to 1.0.0.rc2.

When I launch the tests though I've encountered this error:

> rake aborted!
LoadError: cannot load such file -- aws-sdk-core/plugins/jsonvalue_converter.rb
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/rhymes/.rvm/gems/ruby-2.3.4/gems/aws-sdk-sns-1.0.0.rc2/lib/aws-sdk-sns/client.rb:21:in `<top (required)>'

I've investigated a bit and found the following issue:

The file https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-core/lib/aws-sdk-core/plugins/jsonvalue_converter.rb was introduced the 21st of Aprile, I reckon for version 3.0.0.rc8 of aws-sdk-core https://github.com/aws/aws-sdk-ruby/blob/code-generation/gems/aws-sdk-core/CHANGELOG.md#300rc8-2017-04-21

The issue though is that the gemspec of aws-sdk-sns 1.0.0.rc2 requires aws-sdk-core 3.0.0.rc1 which does not contain that file. 

> spec.add_dependency('aws-sdk-core', '3.0.0.rc1')

The same goes with the other gem I use aws-sdk-s3:

> spec.add_dependency('aws-sdk-core', '3.0.0.rc1')

The same goes with its dependency aws-sdk-kms:

> spec.add_dependency('aws-sdk-core', '3.0.0.rc1')

Technically aws-sdk-sns 1.0.0.rc2 (latest release) is broken. Also aws-sdk-s3 1.0.0.rc4 and aws-sdk-s3 1.0.0.rc5 are broken

**Comment by cjyclaire** [comment]
@rhymes Thanks for reporting, appreciate that!

I suspect that we failed to automatically bump version when core gem introduce changes to all service gems, I'm working on the fix and update shortly. The temporary work-around for this is that specifying the `aws-sdk-core` version directly in service gems.

**Comment by cjyclaire** [comment]
@rhymes Soft update, this is a bug with `.rc` version locking only, I have merged the fix in [build](https://github.com/aws/aws-sdk-ruby/commit/4d837df5dedf0740c1e113ec81b7dbb8570b5c83) and did a new [release](https://github.com/aws/aws-sdk-ruby/commit/c71bb3b9294c52a61cad8c3ddade502604c4d969) including generated fixes just now.  After the gem publishing process is done, I'll update and close the issue.

Thanks again for your patience : )

**Comment by rhymes** [comment]
@cjyclaire thank you for the swift response and fix!

**Comment by cjyclaire** [comment]
@rhymes Both gems are out: [`s3`](https://rubygems.org/gems/aws-sdk-s3/versions/1.0.0.rc7) and [`sns`](https://rubygems.org/gems/aws-sdk-sns/versions/1.0.0.rc4). And I have tested locally, closing, feel free to reopen with further questions or problems : )
