### ISSUE TITLE
How to sign urls for longer than a week using aws-sdk V2 for Ruby?

### ISSUE THREAD

**Issue by rpradhi** [aws/aws-sdk-ruby#1517]
Hi,

I want to sign URL's for longer than a week with AWS-SDK V2 in Ruby. Now i am using SDK V1 for URL Signing and for other purposes using V2. If V2 does this url signing which dont expire for a long term I can universally use V2 alone in my application.
 
Use case for having Long expiry of signed URL's: I am saving the URL in the database which is been accessed by the webservice.

Is that possible in V2 for Long expiry for signed url's can anyone confirm the same? If not , will at some point of time V1 will get deprecated so that I may not use signing url for Longer expiry?

**Comment by cjyclaire** [comment]
@rpradhi You can, there is an [`expires_in`](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Presigner.html) parameter available for setting expiration.

**Comment by awood45** [comment]
This is a limitation of Signature Version 4, you can't extend the signature expiration time out further than that. Here's the comment on this from an earlier issue #1345 

"The limit in the v2 SDK is not flexible. The version 2 SDK uses AWS signature version 4. Sigv4 has the hard requirement that signatures are never valid for longer than 1 week. The v1 SDK uses an older signature version that does not have this limitation. While it still works in many circumstances, there are more and more operations, regions, and parameters are invalid/unusable unless you use signature version 4. Choosing to use an older version may come back to bite you in the future."

See also #927

**Comment by rpradhi** [comment]
@awood45 Thanks for you for the detailed explanation. It helped

Between from my use case will AWS CloudFront signing URL serves the purpose of Long time expiry?
