### ISSUE TITLE
Unable to get tags on elasticbeanstalk environments

### ISSUE THREAD

**Issue by cconstantine** [aws/aws-sdk-ruby#1519]
Hello,

I've been scouring the docs for the better part of the day, and I can't figure out how to get the tags assigned to an elastic beanstalk environment.  I can see the tags on the web UI, but I would like to programmatically get them.

Thanks!

**Comment by cjyclaire** [comment]
@cconstantine Thanks for the information, looks like from public doc right now, it doesn't has a `describe` or `list` operation that contains tag information. I'll reach out to service team for some lights. Also, feel free to cut ticket to [`Aws Support`](https://console.aws.amazon.com/support/home) to make your voice heard as well : )

**Comment by cconstantine** [comment]
Oh wow, yeah.  Not having a public API for getting beanstalk tags seems like a decent reason for this gem not having a method for getting those tags.  Thanks for reaching out internally.  

It appears that we don't have a high enough support contract to make a support request :(

**Comment by cjyclaire** [comment]
@cconstantine No problem at all, all feedback are highly valued, I'll keep updating : ) Appreciate your patience!

**Comment by cjyclaire** [comment]
@cconstantine Appreciate your feedback and patience, this feature is tracked in ELB's backlog now : )
