### ISSUE TITLE
Extending Signed-URL implementation with AWS Cloud Front

### ISSUE THREAD

**Issue by rpradhi** [aws/aws-sdk-ruby#1520]
With respect to issue #1517  @awood45  Thanks for you for the detailed explanation. It helped

Between from my use case will AWS CloudFront signing URL serves the purpose of Long time expiry as AWS SDK V2 dont support Long time expiry? Please confirm

**Comment by awood45** [comment]
Possibly? I think it depends on what you're trying to do, but I haven't spent a lot of time around that side of CloudFront personally. I'd recommend some of the resources in our [Getting Help](https://github.com/aws/aws-sdk-ruby#getting-help) guide to answer this question.
