### ISSUE TITLE
\\n does not properly parse in send_raw_email (SES)

### ISSUE THREAD

**Issue by deepeeess** [aws/aws-sdk-ruby#1526]
I am unable to use `\n` to specify a newline character in a string for send_raw_email as specified here:

http://docs.aws.amazon.com/sdkforruby/api/Aws/SES/Client.html#send_raw_email-instance_method

For example, the following code fails with the stacktrace below:

    resp = @ses.send_raw_email({
    raw_message: {
        data: "From: user@domain.com\\nTo: user@domain.com"
      }
    })

Stack trace:

    gems/2.3.0/gems/aws-sdk-core-2.9.24/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Missing required header
    'To'. (Aws::SES::Errors::InvalidParameterValue)
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/dansullivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aws-sdk-core-
    2.9.24/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from ./take_photos.rb:35:in `send_m'
	from ./take_photos.rb:41:in `<main>'

However, the following code works and will successfully deliver email.

    mailtext =<<EOF
    From: user@domain.com
    To: user@domain.com
    EOF

    resp = @ses.send_raw_email({
        raw_message: {
            data: "#{mailtext}"
        }
    })

I am using `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]` (rbenv)

With:

*** LOCAL GEMS ***

    aws-sdk (2.9.24)
    aws-sdk-core (2.9.24)
    aws-sdk-resources (2.9.24)
    aws-sigv4 (1.0.0)
    bigdecimal (1.2.8)
    did_you_mean (1.0.0)
    io-console (0.4.5)
    jmespath (1.3.1)
    json (1.8.3)
    minitest (5.8.3)
    net-telnet (0.1.1)
    power_assert (0.2.6)
    psych (2.0.17)
    rake (10.4.2)
    rdoc (4.2.1)
    test-unit (3.1.5)

I receive a different error while transposing `From:` and `To:`, although mail still fails to deliver.

**Comment by cjyclaire** [comment]
Taking a look

**Comment by awood45** [comment]
Curious why you're double-escaping the `\n` character - I haven't looked at email protocols in a while but if you're looking for a newline why not do this?

```ruby
resp = @ses.send_raw_email({
raw_message: {
    data: "From: user@domain.com\nTo: user@domain.com"
  }
})
```

I think your blockstring variant would encode that way.

**Comment by deepeeess** [comment]
The example link in the official AWS doc I posted double escapes it, I've tried it single escaped, still still bombs out.

**Comment by awood45** [comment]
Well if they're both bombing out, that's definitely interesting. Your `mailtext` string above just renders as `"From: user@domain.com\nTo: user@domain.com\n"`.

**Comment by deepeeess** [comment]
I'll verify it again, but I'm almost certain both ` data: "From: user@domain.com\\nTo: user@domain.com"`  and  data: "From: user@domain.com\nTo: user@domain.com" will fail.  It could be that I need a trailing `\n` after the `To:` field.  Give me a few minutes and I'll test.

**Comment by deepeeess** [comment]
Ok. I was wrong.  The double escaped `\\n` [as specified in the documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/SES/Client.html#send_raw_email-instance_method) is what causes the failure.  It will work with or without a single escaped `\n` without a trailing slash after the `To:` field. Thank you 👍

**Comment by awood45** [comment]
Ok - glad that fix worked. Also, thanks for reporting because the documentation shouldn't be steering you wrong like that.

**Comment by deepeeess** [comment]
Yeah I agree the documentation should be updated.  Thank you again for your help.

**Comment by cjyclaire** [comment]
I reached out to service team about this documentation confusion, it's in they backlog : )
Appreciate your reporting, closing. Yet feel free to reopen with further question or comments.
