### ISSUE TITLE
Aws::DynamoDB::Client reads items with some UTF-8 chars in string properties incorrectly

### ISSUE THREAD

**Issue by ohTHATaaronbrown** [aws/aws-sdk-ruby#1527]
I have an item in a DynamoDb table that has a string property storing YAML markup, which contains this:

```yaml
  EmployeeMigratorSettings.CsvFileDelimiter: "¬"
```

I can store that value, and confirm that it's stored correctly by viewing it using the AWS DynamoDb console.

When I read the value back out, using code similar to this: 

```ruby
            client = Aws::DynamoDB::Client.new
            params = {
                table_name: table_name,
                projection_expression: 'Tenant, TenantConfig',
                filter_expression: 'attribute_exists(TenantConfig)'

            }

            output = client.scan(params)
            output.items.map do |item|
              config_string = item['TenantConfig']
              puts "Tenant Config: #{config_string}"
            end
```

What I get is this: 

```yaml
  EmployeeMigratorSettings.CsvFileDelimiter: "┬¼"
```

In https://stackoverflow.com/questions/41756526/cannot-delete-dynamodb-record-containing-special-characters there is a suggested fix to the json handler in the aws ruby sdk (`lib\aws-sdk-core\json\handler.rb`): 

```ruby
def parse_body(context)
    if simple_json?(context)
        Json.load(context.http_response.body_contents)
    else
        rules = context.operation.output
        json = context.http_response.body_contents.bytes.pack('c*').force_encoding('utf-8')
        #below line is the original code
        #json = context.http_response.body_contents
        Parser.new(rules).parse(json == '' ? '{}' : json)
    end
end
```

I have confirmed via local testing on my machine that the change to the json encoding handling does, indeed fix the broken read coming back out of the DynamoDb table.

Relevant config info for the machine where I'm seeing this:
* Windows 10 x64 Creator's Edition (fully patched)
* Ruby 2.3.1p112 
* aws sdk 2.8.7

**Comment by cjyclaire** [comment]
@ohTHATaaronbrown Thanks for reporting! Taking a look to reproduce and test the proposed fix. Meanwhile, happy to take a PR to review as well.

**Comment by cjyclaire** [comment]
Soft update, unable to reproduce with my local Mac environment with ruby 2.3.3p222, will try to reproduce in a similar environment instead.

**Comment by cjyclaire** [comment]
Update, I tried with an newly launch EC2 windows instance and still couldn't reproduce. Happy to take a PR with the fix if you can reproduce that in your environment. Just heads up, make sure you have spec test in your PR with this issue : )

**Comment by ohTHATaaronbrown** [comment]
Hmm... That's odd. I wonder if the ambient default encoding for the Ruby install might have something to do with it. I noticed yesterday that mine was set to `IBM437` for some unknown reason.

```bash
$ irb
Switch to inspect mode.


Encoding.default_internal
Encoding.default_internal
nil
Encoding.default_external
Encoding.default_external
#<Encoding:IBM437>
```

I'll investigate further in my environment, and if I can come up with a solid set of reproduction steps that I can codify into a test, I'll look into making up a PR for it.

Thanks for examining"

**Comment by cjyclaire** [comment]
Closing due to inactiveness, yet feel free to reopen with further information or questions : )
