### ISSUE TITLE
"Could not find EC2 instance" error in ELB instance_in_service waiter

### ISSUE THREAD

**Issue by mdub** [aws/aws-sdk-ruby#1538]
I'm using the `instance_in_service` waiter, as follows:

```ruby
elb_client.wait_until(
  :instance_in_service,
  :load_balancer_name => elb,
  :instances => [
    :instance_id => instance_id
  ]
)
```

I'm seeing occasional failures, of the form:

```
/usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:111:in `block in poll': stopped waiting due to an unexpected error: Could not find EC2 instance i-0337e7c7bca85bc52. (Aws::Waiters::Errors::UnexpectedError)
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:101:in `loop'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:101:in `poll'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:91:in `block (2 levels) in wait'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:90:in `block in wait'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:89:in `catch'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/waiters/waiter.rb:89:in `wait'
	from /usr/local/bundle/gems/aws-sdk-core-2.9.17/lib/aws-sdk-core/client_waiters.rb:110:in `wait_until'
	from /app/bin/rea-shipper-utils:31:in `block in execute'
```

The intermittent nature suggests a race-condition.

**Comment by cjyclaire** [comment]
@mdub Thanks for the information, as you mentioned,
> I'm seeing occasional failures
Does this happens with a newly launched Ec2 instance? Or a instance just removed and terminated? 

I'm trying to reproduce this scenario to see what we can do to make that waiter more robust. Interestingly, the only situation that I can reproduce the error is when I used a wrong instance id, so I'm guessing this is happening when an instance has been terminated for a while?

**Comment by mdub** [comment]
@cjyclaire: It's happening for newly launched instances. I'm running it (the waiter) on the new instance itself – waiting for ELBs to mark it healthy, before sending a success signal to CloudFormation.

I think an "error" matcher needs to be added to the definition of the "InstanceInService" waiter. I'll send you a PR ... but imagine you'll need to get it fixed upstream (the waiter definitions are elsewhere, right)?

Anyway, I've managed to work around it in the meantime, using a custom matcher definition:

```ruby
POLLER_CONFIG = {
  "operation" => "DescribeInstanceHealth",
  "acceptors" => [
    {
      "argument" => "InstanceStates[].State",
      "expected" => "InService",
      "matcher" => "pathAll",
      "state" => "success"
    },
    {
      "matcher" => "error",
      "expected" => "InvalidInstance",
      "state" => "retry"
    }
  ]
}
```

**Comment by cjyclaire** [comment]
@mdub Makes sense, thanks for your contribution all the same! I'll pull this PR upstream : )

**Comment by cjyclaire** [comment]
This will lands in v2.10.2 release, which will be out in an hour, closing.
