### ISSUE TITLE
CredentialProviderChain does not read ENV['AWS_PROFILE']

### ISSUE THREAD

**Issue by toaster** [aws/aws-sdk-ruby#1540]
Best explained by code:
```
[1] pry(main)> require 'aws-sdk'
=> true
[2] pry(main)> ENV['AWS_PROFILE']
=> "dev"
[3] pry(main)> Aws::CredentialProviderChain.new.resolve
=> #<Aws::SharedCredentials profile_name="default" path="<me>/.aws/credentials">
[4] pry(main)> Aws::SharedCredentials.new
=> #<Aws::SharedCredentials profile_name="dev" path="<me>/.aws/credentials">
[5] pry(main)> Aws::S3::Client.new.config.credentials
=> #<Aws::SharedCredentials profile_name="dev" path="<me>/.aws/credentials">
```

This should be easily solvable by omitting the `profile` when creating `SharedCredentials` without config instead of explicitly use `default`.

**Comment by cjyclaire** [comment]
Thanks for reporting, PR #1541 has opened to address the fix

**Comment by toaster** [comment]
Thanks for the fast fix. Out of curiosity I had a look at the PR and wondered why you looked into `ENV` in the `CredentialProviderChain` instead of letting the `SharedCredentials` do its already existing lookup logic.
Digging even further I found out, that `SharedCredentials` duplicates (and therefore hides) the logic of `SharedConfig` which has the same fallback chain but only gets called for the default profile name.

Could you please explain to me why it has to be this way?

**Comment by awood45** [comment]
At first glance, looks like an oversight when adding the `SharedConfig` layer. Hence the bug-nature of this.

**Comment by cjyclaire** [comment]
@toaster The reason for that is because for `SharedCredentials`, it allows `:profile_name` overwrite . Making `ENV` goes first there will lose the overwrite behavior there.

**Comment by awood45** [comment]
Releasing this fix as `2.10.0`. It's a minor version bump since it has an effect on the default behavior for some customers, potentially.

**Comment by toaster** [comment]
I'm not convinced regarding the necessity of evaluating `ENV['AWS_PROFILE']` in `CredentialProviderChain`. Please see my simplified patch which leaves the specs (`rake test`) green.

**Comment by cjyclaire** [comment]
@toaster Yes, it's true, it's feasible to let the `SharedCredentials` have the default logic. That's why I edited my response ; )

The reason is, first I'd like to `CredentialProviderChain` deciding those default behavior, making `SharedCredentials` class as clean as possible : )

**Comment by toaster** [comment]
@cjyclaire I understand. But at the moment, you have two (with `SharedConfig` three) implementations of the “explicit profile -> AWS_PROFILE -> default” fallback chain.

**Comment by awood45** [comment]
A refactor is reasonable, can review as a PR.

**Comment by toaster** [comment]
The refactor should happen in the context that @cjyclaire gave regarding the responsibility for the fallback. I have not enough knowledge to decide this and leave it to you guys :).
