### ISSUE TITLE
continue_update_rollback missing from Aws::CloudFormation::Stack

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#1550]
I would expect this method to exist alongside #cancel_update and #delete for an existing stack.

**Comment by cjyclaire** [comment]
@lwoggardner  Thanks for reporting! Marking this as a resource model update task.

**Comment by cjyclaire** [comment]
Tracked in [backlog](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#add-continue_update_rollback-to-the-cloudformation-stack-resource-object), meanwhile happy to take a PR for review and share with other SDKs
