### ISSUE TITLE
Issues using Multipart Donwload #1213

### ISSUE THREAD

**Issue by aquexata** [aws/aws-sdk-ruby#1552]
hi All,

I've just tested the Multipart Download #1213 and I've found some issues downloading big files from S3:

1) Parts are stored within /tmp and that fills the disk causing the download to fail
2) The current implementation downloads the file in many parts and then all parts are put together. That means that to download a 100GB file you need at least 200GB of free disk space. Also, the operation of putting parts together takes a long time due to the I/O required
3) The current implementation consumes a lot of resources: CPU, I/O and RAM. Compared to AWS CLI (boto3) is too far to have the same level of performance

**Comment by cjyclaire** [comment]
@aquexata Thanks for the feedback!

I'll do some benchmarking first and then try to make this better, I'll check cli/boto transfer and do some comparison as well. Any further comments and thoughts are welcome.

A bit clarification for Multipart download helper, it's a higher level abstraction providing customizable usage for S3 multipart APIs. It's true that it works in the way you describe, in terms of I/O required, you could configure the range size per request and concurrent thread in used. I agreed that it will be great if it can do better jobs in terms of streaming.

**Comment by cjyclaire** [comment]
A soft update, talked to the boto team offline, enhancement could be made to make Ruby multipart downloader functionality better. Also, to make IO usage better, max IO parameter could also be added. Tracking this as a backlog item to be prioritized.

**Comment by cjyclaire** [comment]
Tracked in [backlog](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#s3-multipart)
