### ISSUE TITLE
Route53 retry issue

### ISSUE THREAD

**Issue by fabiokr** [aws/aws-sdk-ruby#1554]
SDK version: 2.6.50

Scenario: I noticed that sometimes our system was calling the Route53 `create_hosted_zone` api method, and getting a `HostedZoneAlreadyExistsError`. I'm pretty sure that that was a new zone, so I started investigating further.

I looked at CloudTrail at the time the error happened, and noticed that there were actually 4 API calls to create_hosted_zone, on the following order and with the following results:

```
1: ServiceUnavailableException
2: Success
3: ServiceUnavailableException
4: HostedZoneAlreadyExists
```

We generate a callerReference using the current timestamp. All those requests have the same callerReference, which makes me think there might be some weird behavior with how the api client is doing auto retries (and there were also 4 of them, 1 original request + 3 retries, which is the default `retry_limit`).

For now I have set `retry_limit` on the Route53 client to `0` to observe more closely, but it would be nice if someone more familiar with the code could give some input.

Let me know if there is any other detail that could help with this. Thanks!

**Comment by cjyclaire** [comment]
@fabiokr Thanks for the information, so you can set `:http_wire_trace` to true at client to see the http raw wire log, you can also use [log formatter](http://docs.aws.amazon.com/sdkforruby/api/Aws/Log/Formatter.html) to keep track if wire trace is too much for you. 

If you find something unexpected from SDK side, happy to take a close look if you could provide some reproducing code snippets . Also, if some request is behaving weirdly, feel free to contact [`AWS Support`](https://console.aws.amazon.com/support/home) to look into that as well ; )

**Comment by awood45** [comment]
This has been inactive - closing, feel free to reopen if you have wire trace info.
