### ISSUE TITLE
undefined method `use_bundled_cert!' for Aws:Module

### ISSUE THREAD

**Issue by Reechee88** [aws/aws-sdk-ruby#1555]
`gem "aws-sdk", "~> 2.0.0"`

`module Api
  require 'aws-sdk'

  class ProfileController < ApplicationController
  .......

   def method1
    ....
    Aws.use_bundled_cert!
    ....
   end`

`NoMethodError (undefined method `use_bundled_cert!' for Aws:Module):`

Any idea?

**Comment by cjyclaire** [comment]
@Reechee88 The `use_bundled_cert!` is introduce since [`v2.1.0`](https://github.com/aws/aws-sdk-ruby/commit/c7434229b4274cb710bacf06ec26730260b571b8), if you update your gem dependency, that will work : )
