### ISSUE TITLE
Trying to verify a SNS message fails

### ISSUE THREAD

**Issue by Chocksy** [aws/aws-sdk-ruby#1558]
I'm using rails 5 and i'm trying to verify a SNS message but i get this error https://sentry.io/share/issue/3133343238302e333138323235343431/

I'm doing the check by sending an email to `bounce@simulator.amazonses.com` 
I'm trying to check bounces and complains into my app.

Is this a bug or am i missing something? 

This is the code
```ruby
  def verify_message_authenticity
    verifier = Aws::SNS::MessageVerifier.new
    unless verifier.authentic?(request.raw_post)
      Rails.logger.info 'Not an authentic SNS message - exiting'
      head :not_acceptable
    end
  end
```

Thanks <3

**Comment by cjyclaire** [comment]
@Chocksy Just double check, did you verified that `request.raw_post` is valid?

**Comment by Chocksy** [comment]
@cjyclaire i managed to get the info from the request.raw_post and this is what it looks like:
```
{"notificationType":"Bounce","bounce":{"bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"bounce@simulator.amazonses.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550 5.1.1 user unknown"}],"timestamp":"2017-07-27T17:59:38.077Z","feedbackId":"0100015d853436fd-0f40b4c1-ff25-45be-ab20-xxxxxxxx-000000","remoteMtaIp":"205.251.242.49","reportingMTA":"dsn; a8-88.smtp-out.amazonses.com"},"mail":{"timestamp":"2017-07-27T17:59:37.000Z","source":"support@epicpxls.com","sourceArn":"arn:aws:ses:us-east-1:xxxxxxxxx:identity/support@epicpxls.com","sourceIp":"54.147.166.110","sendingAccountId":"xxxxxxxxxxxxx","messageId":"0100015d85343569-2d17ae37-d6df-4e50-afec-9d8f38d3a3ce-000000","destination":["bounce@simulator.amazonses.com"]}}
--
```
It seems fine to me.
_Note: i changed a few of the ids to xxx_

**Comment by cjyclaire** [comment]
@Chocksy Apologies for getting back late, from your response, looks like you are using SES [notification](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#top-level-json-object) for SNS? However, the [`MessageVerifier`](http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.verify.signature.html) is used in verifying signature in this [format](https://github.com/aws/aws-sdk-ruby/blob/082ea490f63225c159cce9639ccd293d2433044a/aws-sdk-resources/spec/services/sns/message_verifier_spec.rb#L11), that's why it throws irrelevant errors.

**Comment by Chocksy** [comment]
Hmm so i should not very the message then? 
I actually took most of the inspiration from this blog post that seems to be doing what i have in my code https://www.downrightlies.net/posts/2015/05/19/setting-up-ses-on-aws-to-send-emails-from-rails.html
So i don't understand. Did you guys change the notification?

**Comment by cjyclaire** [comment]
@Chocksy I don't think so, we won't introduce breaking changes in the response. In the blog post you linked, in the controller test part, it's actually following the correct message format.

**Comment by Chocksy** [comment]
Ok thanks @cjyclaire for your help. :D

**Comment by cjyclaire** [comment]
@Chocksy I didn't deep dive into the whole blog, yet I think if you revisit your flow that might help uncover something, the MessageVerifier is used for :
> verify the authenticity of a notification, subscription confirmation, or unsubscribe confirmation message sent by Amazon SNS

**Comment by Chocksy** [comment]
So only for that and not the bounces and complains etc. I guess that would answer it as the initial subscription confirmation works fine but the bounce calls raise the error. I think i can live with it turned off for now.
