### ISSUE TITLE
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI ignored?

### ISSUE THREAD

**Issue by llibicpep** [aws/aws-sdk-ruby#1560]
I'm wondering if there's a chances of regression in picking up ECS task role vs EC2 cluster role. I am using latest kitchen-ec2 together with latest aws-sdk. I also tried a few recent versions for both. `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is present in my container and available to the process that running kitchen. I reported issue there as well https://github.com/test-kitchen/kitchen-ec2/issues/333 though unsure where it really belongs to. I also seen this two issues https://github.com/aws/aws-sdk-ruby/issues/1337 and https://github.com/aws/aws-sdk-ruby/issues/1309.

**Comment by awood45** [comment]
There is a chance of regression depending on how the roles are configured. If an ECS container role is present, we will use it and not use EC2 instance role, even if the EC2 instance ECS is running on has a role.

If the roles are the same, the outcome will be the same. If the roles differ in permissions, then it is possible switching could introduce auth errors for operations you don't have permissions for in the ECS role.

Does that answer your question?

**Comment by awood45** [comment]
The other question, of course, would be which version of the `aws-sdk` gems you're using. The ECS container role feature would have to be present in your version of the SDK to be picked up.

**Comment by llibicpep** [comment]
@awood45 thanks for quick response. Seems that I've found the root cause and it belongs to kitchen-ec2. https://github.com/test-kitchen/kitchen-ec2/blob/v1.3.2/lib/kitchen/driver/aws/client.rb#L77 looks like as the last resort they are trying to pick up `InstanceProfileCredentials` directly not looking at AWS_CONTAINER_CREDENTIALS_RELATIVE_URI and not using chain resolve. So I am closing this issue.

**Comment by awood45** [comment]
Yup, I can't speak to the behavior of a custom credential provider chain. Thanks for following up!
