### ISSUE TITLE
Method Aws::S3::Object#presigned_url not working properly with buckets from different region than the API Keys

### ISSUE THREAD

**Issue by thegreyfellow** [aws/aws-sdk-ruby#1563]
Hi, I had a weird case happening in my app, tried to make a presigned url for objects so that they could be downloaded from the Frontend, but apparently, it did not work for all the buckets but only for those in the same region as the api key/secret key :confused: No worries tried to make a `Aws::S3::client.new (region: <bucket-specific-region>)`, but still I get the same behavior and that's really weird since I instantiated the `Aws::S3::Bucket.new` with the new S3 client and having the same behavior as with the old S3 client.

I went throught the `Aws::S3::Object` file, and found out that the #presigned_url method, instantiates an instance of the `Aws::S3::Presigner` with an S3 client instance that I'm not sure where it's coming from :confounded:. I did override the method with one in my code by putting the new S3 client inside the Presigner and voila, presigned_url is working for buckets from different region than the region default region.

```ruby
# object.rb
def presigned_url(client, http_method, params = {})
        presigner = Aws::S3::Presigner.new(client: client)
        presigner.presigned_url("#{http_method.downcase}_object", params.merge(
          bucket: bucket_name,
          key: key,
        ))
end

...

# your_script.rb
file_name = 'somefile'
bucket_name = 'your_bucket_here'

# bucket with object that you need presigned_url to download it is from 'eu-west-1'
client = Aws::S3::Client.new(
  access_api_key: '...',
  secret_key:         '...',
  region:                'eu-west-1'
)

bucket = Aws::S3::Bucket.new(bucket: bucket_name, client)  # at this leve we don't care about client region.
object = bucket.objects.select { |object| object.key == file_name }
object.presigned_url(client, :get)
```

I hope this helps someone on the future I stayed stuck in it for more than 4 hours :disappointed:

**Comment by cjyclaire** [comment]
@thegreyfellow Sorry to know that this behavior blocks you for a while. First of all, what you have observed is the correct behavior of SDK. The presigner creates a default s3 client by default if client is not provided to overwrite, that's helpful when `:client` is not required for creating a presign url.

**Comment by thegreyfellow** [comment]
Okay :disappointed:, thanks for the clarifications.
