### ISSUE TITLE
Presigned URLs not working with Edge or IE

### ISSUE THREAD

**Issue by jasonperrone** [aws/aws-sdk-ruby#1565]
Hi, I created a Presigned URL with the Presigner: 
Aws::S3::Presigner.new.presigned_url(:get_object, bucket: 'my_bucket_name', key: 'my_key')

The resulting link works perfectly in Chrome. Clicking it results in a file download. In Edge and IE, S3 just never responds. The browser activity wheel keeps spinning, nothing appears in the console.

Anybody else see something like this?

**Comment by jasonperrone** [comment]
Now this is interesting. I can't even download a file from S3 using Edge right in the S3 console!

**Comment by cjyclaire** [comment]
@jasonperrone SDK has no control over browsers, since Chrome works fine, the url should be correct. If the problem exists with console still, feel free to cut support tickets to [`AWS`](https://console.aws.amazon.com/support/home) for console team or S3.

**Comment by jasonperrone** [comment]
Agreed, thank you for the response.
