### ISSUE TITLE
S3 Object `download_file` method options

### ISSUE THREAD

**Issue by tpett** [aws/aws-sdk-ruby#1570]
From the documentation and the [error message][2] it would seem that you are to pass symbols to the `:mode` configuration option. However, the `FileDownloader` class counts on this config being a string. It looks like a simple `to_s` on [this line][1] would take care of it.

Thanks!

[1]: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/file_downloader.rb#L30
[2]: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/file_downloader.rb#L43

**Comment by cjyclaire** [comment]
@tpett I can see that it's a small change which is easy to make, the error message appears misleading, however it's documented as [`string`](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#download_file-instance_method) or in [code](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/object.rb#L269), could you lead me to the documentation that caused confusion for you?

**Comment by awood45** [comment]
Just to be clear, are we seeing a particular failing case, or is this just a concern that the error message implies that only symbols are accepted? Want to make sure we are fixing the right thing.

**Comment by tpett** [comment]
Ah yes, I was looking at [this documentation][1] and you are correct it does say String. I missed that. I don't think there's any documentation that needs to be updated. It seems like it would be low cost to simply allow either symbol or string here and no compatibility will be broken, but it will be less surprising for discovery.

Now switching over to just my opinion: I think that symbols would be a more idiomatic Ruby representation of the `:mode` value in this case. Especially since the keys of the `options` hash are symbols as well. That being said it's not very important what you do under the hood or in documentation as long as both work and it appears consistent from the outside.

Thanks for all your work on this gem!

[1]:http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#download_file-instance_method

**Comment by awood45** [comment]
Thanks - if we don't have a behavior issue (as I believe Strings work as well as Symbols in this case), I'm going to prefer not making a code change. Feel free to reopen if there is an issue.
