### ISSUE TITLE
Error class changed recently?

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1574]
Earlier versions of SDK used to return **Aws::EC2::Errors::SnapshotCreationPerVolumeRateExceeded** when we hit AWS limits on snapshots. The current SDK is returning **Aws::EC2::Errors::SnapshotCreationPerVolumeRateExceededException** instead. We catch the specific exception in our code as this is a retryable one. 

Was there a change made to suffix errors with the string **_Exception_**?

thanks

**Comment by awood45** [comment]
Thanks for the report on this, I'll investigate with the service team. I'd catch both exceptions as a workaround, sorry about this issue.

**Comment by awood45** [comment]
For some background, do you know when the exception type changed for you? It wouldn't be tied to an SDK version, it would be a particular date. Do you know how often (for example, through logging) you caught the previous exception type?

I just want to be super clear that the exception we're getting has changed, and eliminate the possibility that you're encountering this exception for the first time.

**Comment by pchaganti** [comment]
Not sure of the exact date when it changed. It is definitely in the last week or so that we have been seeing this exception. The errors raised previously have never had the Exception suffix. We have had this code running for the last several years and the error handling has not changed.

**Comment by awood45** [comment]
Thank you, that's helpful.

**Comment by awood45** [comment]
Additionally, can you capture the exception(s) you're seeing currently using a wire trace? When we tried to reproduce we got `Aws::EC2::Errors::SnapshotCreationPerVolumeRateExceeded`, so if you're still seeing a different exception, that is very interesting indeed. To get a wire trace:

```ruby
ec2 = Aws::EC2::Client.new(http_wire_trace: true, region: REGION)
```

With that setting, you'll output the wire logs, which we can use to see the response the service provided and in turn see how we generated the exception. If you're still seeing the new exception type, this will be super helpful. Thanks!

**Comment by awood45** [comment]
Of course, when posting wire logs, feel free to strip anything sensitive (we shouldn't need any of that to actually diagnose the issue). But, please *do* keep any request ID values, which we can use to directly see what happened on the service side.

**Comment by awood45** [comment]
Thank you for reporting this. The issue has been resolved on the service end. The correct exception is `Aws::EC2::Errors::SnapshotCreationPerVolumeRateExceeded`.

Sorry for the trouble, taking steps to help prevent it from happening again.
