### ISSUE TITLE
AWS Ruby SDK for DAX API needs updates

### ISSUE THREAD

**Issue by TDA** [aws/aws-sdk-ruby#1575]
Looking at the blog post for AWS DAX (https://aws.amazon.com/blogs/aws/amazon-dynamodb-accelerator-dax-in-memory-caching-for-read-intensive-workloads/), it is specified that DAX supports all operations that DynamoDB does, however, this is not reflected in the DAX API (https://github.com/aws/aws-sdk-ruby/tree/master/aws-sdk-core/apis/dax/2017-04-19), and the files there look like they need to be updated.  `examples.json` is empty, and the API file itself does not describe the supported DynamoDB calls.

It is unclear if this is because it is not supported or because the docs are not updated. Could you please clarify? If it is not supported yet, is there an ETA for the ruby sdk for DAX?

**Comment by awood45** [comment]
The `Aws::Dax::Client` documentation is correct, the SDKs broadly support the control plane APIs. Support for DAX as a database client to my knowledge only exists in Java today. I'll pass this on to that team as a feature request.

**Comment by TDA** [comment]
@awood45 Is there a place where I can track that feature request?

**Comment by awood45** [comment]
I don't know - the Dax team would certainly announce any new SDK launches, however.
