### ISSUE TITLE
Aws::SNS::MessageVerifier fails due to mismatched case on signing cert url

### ISSUE THREAD

**Issue by stormbeta** [aws/aws-sdk-ruby#1578]
The JSON key for the signing cert url isn't matched between the SDK code and what's actually being returned by AWS. This appears to be an error on the AWS side as this line hasn't changed since 2015 and a stored copy of an SNS message from Aug 15 has the expected upper case version of the field.

`aws-sdk-resources-2.10.32/lib/aws-sdk-resources/services/sns/message_verifier.rb:93`:  `x509_url = URI.parse(message['SigningCertURL'])`

But the field in actual SNS messages that I received today is `SigningCertUrl` (note the lowered case on Url).

This causes an InvalidURIError to be thrown even on valid messages:

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?):  (URI::InvalidURIError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:15:in `split'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.32/lib/aws-sdk-resources/services/sns/message_verifier.rb:93:in `public_key'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.32/lib/aws-sdk-resources/services/sns/message_verifier.rb:62:in `authenticate!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.32/lib/aws-sdk-resources/services/sns/message_verifier.rb:50:in `authentic?'
	from test.rb:10:in `<main>'
```

**Comment by cjyclaire** [comment]
Thanks for reporting! taking a look ...

**Comment by cjyclaire** [comment]
@stormbeta Quick question, is this happening with message from Lambda only?

**Comment by stormbeta** [comment]
@cjyclaire This is coming through a lambda, yes. The messages I was looking at before were sent via email-json subscriptions, if that makes a difference.

**Comment by cjyclaire** [comment]
@stormbeta Thank you for your patience! the workaround PR fix has been merged will be out in the next release. A quick summary is that this is cause by Lamdba message formatting issue in SNS. I'll ping the thread once the release is out : )

**Comment by cjyclaire** [comment]
The [release](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.10.33) is out, thanks
