### ISSUE TITLE
Allow for in-memroy multipart upload

### ISSUE THREAD

**Issue by arianf** [aws/aws-sdk-ruby#1580]
Allow for in-memroy multipart upload.

`Client#put_object` doesn't seem to upload an object with multipart, and `Object#upload_file` does multipart uploading, but it requires the file to be on disk.

**Comment by cjyclaire** [comment]
Thanks for the feedback! tracked in our backlog under S3 Multipart enhancement.

**Comment by janko-m** [comment]
@cjyclaire I think this is a duplicate of https://github.com/aws/aws-sdk-ruby/issues/1351, which was already added as a feature request.

**Comment by kstratis** [comment]
Does #1351 offer any options for any sort of progress callbacks..?
