### ISSUE TITLE
Require source code for AWS SigV4 release 1.0.1

### ISSUE THREAD

**Issue by kailasdp2000** [aws/aws-sdk-ruby#1582]
Hello,

I need source code for AWS SigV4 release 1.0.1. Was not able to find it on github. Can you please help?

Thanks,
Kailas

**Comment by menno** [comment]
It's here: https://github.com/aws/aws-sdk-ruby/tree/code-generation/gems/aws-sigv4

Appears that the `code-generation` branch has not yet been merged to master following the SDK V3 release.

**Comment by awood45** [comment]
Correct, that will be in master soon, and it lives in this repo.
