### ISSUE TITLE
No Changelog for version 3

### ISSUE THREAD

**Issue by greysteil** [aws/aws-sdk-ruby#1583]
Version 3.0.0 was released on [Rubygems](https://rubygems.org/gems/aws-sdk) yesterday, but there's no changelog entry for it and `master` on this repo still points to [v2.10.35](https://github.com/aws/aws-sdk-ruby/blob/master/VERSION). Can we get an update on what's going on, and where the code for version 3.0.0 is?

**Comment by menno** [comment]
After checking some branches it seems to be located in this branch: https://github.com/aws/aws-sdk-ruby/tree/code-generation

**Comment by awood45** [comment]
We're moving V3 to the master branch soon, we have to coordinate that change with some internal tooling. For now V3 lives in code-generation, correct.

**Comment by jamtur01** [comment]
No release tag either.

**Comment by greysteil** [comment]
Thanks for the update. Would be awesome if you could add the above details to the changelog, or a GitHub release - at the moment anyone doing a bundle update without a pinned version will be getting V3 but won't be able to find details of what's changed / currently happening easily.

(My particular interest is that I run [Dependabot](https://dependabot.com) which automatically creates PRs to bump dependencies - we've had a few people ask if there's been an error on our side because they haven't been able to find any details of the new version in this repo!)

**Comment by awood45** [comment]
Release tags are a more interesting issue now that we have modularized into 100+ gems. `aws-sdk` will probably be on `3.0.0` for a long time, it's the underlying service gems which will be updating. I'm open to ideas about how to add dozens of new GitHub releases/tags to this repo without it getting overwhelming.

The CHANGELOGs in the `code-generation` branch are current and will soon be in `master`. Similarly, the V2 CHANGELOG will continue to update once it has moved to a branch.

**Comment by greysteil** [comment]
Interesting. Release notes aren't going to work for you with the above setup, but you should be able to get Rubygems to point to the right changelogs, which will help a lot - I'll create a PR for that now.

**Comment by awood45** [comment]
The use case you have will be interesting with V3. We actually will be having hundreds of CHANGELOGs, and users will be migrating to only using a subset of service gems relevant to their use cases. It's unfortunately impractical for us to create repos for each gem, so a "single" CHANGELOG doesn't fit well going forward. Happy to discuss what we do have, or if there are ways to make our multiple changelogs easier to consume.

**Comment by greysteil** [comment]
Got a solution for you on that one: https://github.com/aws/aws-sdk-ruby/pull/1585

**Comment by awood45** [comment]
Yep, that looks great. We're going to take on a task to add this to our generation process.

**Comment by awood45** [comment]
Version 3 is now on the `master` branch. Leaving open while we work on your PR.

**Comment by cjyclaire** [comment]
The PR #1586 update is merged, will be out in the next release : ), closing

**Comment by greysteil** [comment]
Nice, thanks!
