### ISSUE TITLE
Regression: S3 object streaming is not working anymore

### ISSUE THREAD

**Issue by janko-m** [aws/aws-sdk-ruby#1588]
### Issue description

In aws-sdk V2 you could stream an object from S3 by passing a block:

```rb
object.get { |chunk| puts chunk }
# or
client.get_object({...}) { |chunk| puts chunk }
```

In aws-sdk-s3 this doesn't work anymore, even though it's still [documented](https://github.com/aws/aws-sdk-ruby/blob/dad6433b6c4940442b2eeda431c15f3cc576e94f/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L2526-L2532). It doesn't work because [`Aws::S3::Object#get`](https://github.com/aws/aws-sdk-ruby/blob/dad6433b6c4940442b2eeda431c15f3cc576e94f/gems/aws-sdk-s3/lib/aws-sdk-s3/object.rb#L557-L564) and [`Aws::S3::Client#get_object`](https://github.com/aws/aws-sdk-ruby/blob/dad6433b6c4940442b2eeda431c15f3cc576e94f/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L2595-L2598) don't handle a given block anymore.

### Gem name

The problem is occurring on `aws-sdk-s3` 1.0.0.

### Version of Ruby, OS environment

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ uname -a
Darwin Jankos-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

### Code snippets / steps to reproduce

```rb
require "aws-sdk-s3"

resource = Aws::S3::Resource.new(
  access_key_id:     "...",
  secret_access_key: "...",
  region:            "...",
)
client = resource.client
bucket = resource.bucket("my-bucket")

object = bucket.object("foo")
object.put(body: "content")

# Both of these versions yield chunks in aws-sdk V2, but not in aws-sdk-s3
object.get { |chunk| puts chunk }
client.get_object(bucket: "my-bucket", key: "foo") { |chunk| puts chunk }
```

**Comment by awood45** [comment]
I am able to reproduce this error. Taking a look.

**Comment by cjyclaire** [comment]
Thank you for your patience, the fix PR was merged, will be out in the next release. I'll ping the thread again once next release is out.

**Comment by janko-m** [comment]
@cjyclaire I've noticed that https://github.com/aws/aws-sdk-ruby/pull/1591 has brought back streaming support via blocks to `Aws::S3::Client#get_object`, but **not** to `Aws::S3::Object#get` ([which I'm using in Shrine](https://github.com/janko-m/shrine/blob/edc627a87923d8d38842c480bca6805339be936f/lib/shrine/storage/s3.rb#L243)). If we check the `Aws::S3::Object#get` source code, we can see that no block is forwarded to `Aws::S3::Client#get_object`. https://github.com/aws/aws-sdk-ruby/blob/83ab2ee52b434ef89cad0e0a3caf9c94fcf63e89/gems/aws-sdk-s3/lib/aws-sdk-s3/object.rb#L557-L564

**Comment by cjyclaire** [comment]
@janko-m Thanks for the ping! taking a look ...

**Comment by cjyclaire** [comment]
@janko-m Just opened another PR for resource object fix, will ping the thread once it got merged and released

**Comment by cjyclaire** [comment]
Sorry for the late ping, the latest version is [out](https://rubygems.org/gems/aws-sdk-s3/versions/1.2.0)

**Comment by janko-m** [comment]
@cjyclaire Awesome, thank you! Shrine tests are passing now 👌
