### ISSUE TITLE
Cannot find UpdateSecurityGroupRuleDescriptionsIngress in API

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1589]
Please fill out the sections below to help us address your issue

### Issue description
The current EC2 API supports **UpdateSecurityGroupRuleDescriptionsEgress** and **UpdateSecurityGroupRuleDescriptionsIngress**. I dont see them in the API for the current release of the SDK (3.0)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-ec2

### Version of Ruby, OS environment
Any

### Code snippets / steps to reproduce
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_UpdateSecurityGroupRuleDescriptionsEgress.html

**Comment by cjyclaire** [comment]
@pchaganti Thanks for the attention! This will be included in next release across all SDKs very soon! I can ping the thread once it's out : ) (likely today)

**Comment by cjyclaire** [comment]
The [release](https://rubygems.org/gems/aws-sdk-ec2/versions/1.1.0) is out, closing
