### ISSUE TITLE
presigned s3 urls with an explicit signing time

### ISSUE THREAD

**Issue by fledman** [aws/aws-sdk-ruby#1598]
### Issue description
The `Aws::Sigv4::Signer` method `presign_url` supports the `:time` option to pass in a specific signing time.

However, the `Aws::S3::Presigner` method `presigned_url` does not expose this option, and as such, neither does the equivalently named `Aws::S3::Object` method.

Is it possible to pass the `:time` option all the way through the callstack?

### Code snippets / steps to reproduce
https://github.com/aws/aws-sdk-ruby/blob/5361c0cf4aefcd0dbb7317d404e57363f801be87/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L325

https://github.com/aws/aws-sdk-ruby/blob/5361c0cf4aefcd0dbb7317d404e57363f801be87/gems/aws-sdk-s3/lib/aws-sdk-s3/presigner.rb#L122-L128

https://github.com/aws/aws-sdk-ruby/blob/5361c0cf4aefcd0dbb7317d404e57363f801be87/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L187-L193

### Gem name and its version
`aws-sdk-s3` and `aws-sigv4` at HEAD

### Version of Ruby, OS environment
Not applicable

**Comment by cjyclaire** [comment]
@fledman Thanks for noticing! This is true that `aws-sigv4` gem make it more flexible and easy to test and use. However, the `:time` option is mainly used for testing purpose. We intentionally didn't expose all field though S3 interfaces initially.

May I ask why you would like to see this from S3 interface? Some use cases explanation would be great! Then I can see if I can provide workaround or tag this as a feature request.

**Comment by fledman** [comment]
@cjyclaire 
The signing api operates on a seconds until expiration basis, as opposed to an explicit expiration timestamp. In most cases, emulating the later by subtracting the current timestamp is good enough.

However, signed urls produced in this way are not stable; the signature for a <url,expiration_timestamp> pair depends on the time of signing.

Unfortunately, my use case requires stable signatures (and I cannot use some sort of caching scheme). Fortunately, this can be achieved by explicitly setting the signing timestamp.

As an example, say I want to produce stable urls that are valid for a particular day. I can set the signing timestamp to midnight, expires_in to 86400, and produce the same signed url for a given input deterministically.

**Comment by cjyclaire** [comment]
Thanks! Tracking this under feature backlog.
