### ISSUE TITLE
Can't call as_json method  of struct Aws::EC2::Types::Snapshot

### ISSUE THREAD

**Issue by Rigel89** [aws/aws-sdk-ruby#1600]
### Issue description
I didn't encounter this issue for other EC2 types (doing a similar thing for EC2 Volumes).
Can't call as_json method  of struct Aws::EC2::Types::Snapshot

### Gem name
aws-sdk 3.0.1

### Version of Ruby, OS environment
Ruby 2.3.3
Ubuntu 16.04

### Code snippets / steps to reproduce
snapshot = ec2_client.create_snapshot(volume_id: "my_volume_id")
snapshot.as_json

### Resolution
Had to change to => snapshot.to_h.as_json

**Comment by cjyclaire** [comment]
@Rigel89 Hmm, I don't think we do something special for that api call or type, are you using rails that causes this problem? Noticed that you mentioned
> I didn't encounter this issue for other EC2 types (doing a similar thing for EC2 Volumes).

Could you provide an example that `as_json` worked? I tried `:create_volume` API, as the same with `create_snapshot `, both returned `Seahorse::Client::Response`.

**Comment by Rigel89** [comment]
Yes i'm using the API calls in Rails. I'll leave an example as soon as possible.

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further information : )
