### ISSUE TITLE
XRay instrumentation

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1602]
Please fill out the sections below to help us address your issue

### Issue description
AWS provides official SDK clients for Xray for Java, Python, Go, Node, etc, which have the ability to automatically instrument AWS SDK clients and send that data to Xray. This would be awesome to have in the Ruby SDK. Are there any plans to do this?

P.S: There is an [unofficial Ruby tracing SDK](https://github.com/taiki45/aws-xray). 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk

### Version of Ruby, OS environment
Any

**Comment by cjyclaire** [comment]
@pchaganti Q, are you suggesting our [`aws-sdk-xray`](https://rubygems.org/gems/aws-sdk-xray) gem? [Source code here](https://github.com/aws/aws-sdk-ruby/tree/master/gems/aws-sdk-xray) : )

**Comment by awood45** [comment]
In the case of the X-Ray clients doing automatic instrumentation, our team doesn't handle that. I'll pass on this feature request.
