### ISSUE TITLE
Undefined method `wait_until' in v3 SDK

### ISSUE THREAD

**Issue by ajkerr** [aws/aws-sdk-ruby#1610]
Please fill out the sections below to help us address your issue

### Issue description

We have uncovered a backwards-compatibility problem after attempting to upgrade from the v2 SDK to the v3 version.

Methods such as wait_until no longer exist on classes such as Volume. This issue appears to be related to the fact that classes such as Volume extended Resource in v2, and now extend Object in v3.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk 3.0.1

### Version of Ruby, OS environment

ruby 2.4.1p111 on macOS (via Homebrew)

### Code snippets / steps to reproduce

This code works in v2, but fails in v3 with the following message:

```
ruby-sdk-3-test.rb:13:in `<main>': undefined method `wait_until' for #<Aws::EC2::Volume:0x007f96f834a378> (NoMethodError)
```

```ruby
require "aws-sdk"

ec2 = Aws::EC2::Resource.new(region: 'us-west-2')

volume = ec2.create_volume({
  size: 1,
  availability_zone: 'us-west-2a',
  volume_type: 'gp2'
})
puts "Created new volume: #{volume.id}"

volume.wait_until() {|volume| volume.state == 'available' }
puts "Volume #{volume.id} is now available."
```

**Comment by cjyclaire** [comment]
@ajkerr Thanks for reporting, taking a look

**Comment by cjyclaire** [comment]
Soft update, I can reproduce this, working on fixing the regression, in the meantime, you can use ec2 client waiters as work around like:
```ruby
client.wait_until(:volume_available, volume_ids:['vol-0b123323123123'])
```

**Comment by cjyclaire** [comment]
The fix PR has been merged, will ping the thread once release is out : )

**Comment by cjyclaire** [comment]
The release is [out](https://rubygems.org/gems/aws-sdk-ec2/versions/1.6.0), closing : )
