### ISSUE TITLE
Uncommented documentation lines in nested aws-sdk-snowball gem

### ISSUE THREAD

**Issue by jeffpereira** [aws/aws-sdk-ruby#1611]
Please fill out the sections below to help us address your issue

### Issue description
There are some uncommented documentation lines in the nested aws-sdk-snowball gem.  This causes syntax errors to occur if you have the current version (3.0.1) of aws-sdk gem installed.  

`.../aws-sdk-snowball-1.0.0/lib/aws-sdk-snowball/client.rb:1204: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
ou've created for AWS Snowball`

This bug makes the gem completely unusable if you have eager loading enabled and you are including all of the aws-sdk service gems or including the aws-sdk-snowball service in your application.

I believe the issue could be in the text generation for the documentation, but I took a look there and did not see anything blatantly wrong with the text that was in the template.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk (3.0.1), aws-sdk-snowball (1.0)

### Version of Ruby, OS environment
2.4, macOS Sierra

### Code snippets / steps to reproduce
`Aws.eager_autoload!`

**Comment by cjyclaire** [comment]
@jeffpereira Thanks for reporting, working on the fix

**Comment by cjyclaire** [comment]
The fix PR has been merged, will be out in next release, will ping the thread once that is out : )

**Comment by jeffpereira** [comment]
thanks for the super fast fix and update.

**Comment by cjyclaire** [comment]
The release is [out](https://rubygems.org/gems/aws-sdk-snowball/versions/1.1.0), closing : )
