### ISSUE TITLE
stack.stack_status caches the the info after the first call and won't refresh

### ISSUE THREAD

**Issue by infinityminglei** [aws/aws-sdk-ruby#1613]
Please fill out the sections below to help us address your issue

### Issue description
I am trying to use instance method stack_status method for Aws::CloudFormation::Stack class. I am expecting every time I call it , it will return the current stack_status. But after the first call, it will just cache the initial stack_status, in order to get latest stack_status, I have to initialize the Stack Object again and call the method.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
Using aws-sdk-core 3.2.0
Using aws-sdk-cloudformation 1.0.0
Using aws-sdk-ec2 1.1.0
Using aws-sdk-kms 1.0.0

### Version of Ruby, OS environment
ruby 2.3.0
### Code snippets / steps to reproduce
current_stack = Aws::CloudFormation::Stack.new("Stack1")
loop do
   puts current_stack.stack_status
end

above command will always puts CREATE_IN_PROGRESS status even the real stack_status is CREATE_COMPLETE

**Comment by cjyclaire** [comment]
Taking a look

**Comment by cjyclaire** [comment]
@infinityminglei The behavior looks like is expected in SDK (both V2 or V3). The data attribute for the resource object is fetched once.

In terms of polling the stack status, we recommend using [waiters](https://aws.amazon.com/blogs/developer/waiters/) instead. In your use case, you can try [`#wait_until_exists`](http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFormation/Stack.html#wait_until_exists-instance_method) for the stack object, or try [`#wait_until`](http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFormation/Client.html#wait_until-instance_method) at client.

**Comment by infinityminglei** [comment]
@cjyclaire the description for wait_until_exists method is not very clear. Does it mean it will wait until the stack CREATE_COMPLETE?

**Comment by cjyclaire** [comment]
@infinityminglei It just checks existence of the stack, if you want to check the complete state, you can use `:stack_create_complete` waiter, scroll down the client `#wait_until` method, you will see
![image](https://user-images.githubusercontent.com/10790394/30399901-05dc9f0e-988a-11e7-860d-779a6e39d6f5.png)

**Comment by cjyclaire** [comment]
Questions have been answered, closing.
Feel free to reopen with further discussion : )
