### ISSUE TITLE
Connect to non-amazon object storage services that support the S3 API?

### ISSUE THREAD

**Issue by sam0x17** [aws/aws-sdk-ruby#1616]
Please fill out the sections below to help us address your issue

### Issue description

For example, Digital Ocean supports the S3 API. It would be nice to be able to connect to these sorts of services as they typically don't provide their own gem. This might already be possible but I haven't been able to find anything in the docs.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-s3`

### Version of Ruby, OS environment

NA

### Code snippets / steps to reproduce

NA

**Comment by awood45** [comment]
Aside: If you're actually referring to the [aws-s3 gem](https://rubygems.org/gems/aws-s3), we don't maintain that. The `aws-sdk-s3` gem is the official S3 gem we maintain.

With that gem, you can specify custom endpoints at your discretion, for example:

```ruby
s3 = Aws::S3::Client.new(endpoint: "https://my.custom.endpoint")
s3.list_buckets # Or whichever operations you want to run.
```

If your endpoint is S3 API compatible, it will work.

**Comment by sam0x17** [comment]
thanks -- this helps!
