### ISSUE TITLE
aws-sdk-resources 2.10.56 gem missing

### ISSUE THREAD

**Issue by cotsog** [aws/aws-sdk-ruby#1622]
### Issue description

It seems that version 2.10.56 of the aws-sdk-resources isn't available on Rubygems but is a dependency of aws-sdk.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk 2.10.56 => https://rubygems.org/gems/aws-sdk/versions
aws-sdk-resources 2.10.56 missing => https://rubygems.org/gems/aws-sdk-resources/versions

Thanks!

**Comment by cjyclaire** [comment]
@cotsog Thanks for reporting, it just takes a while :) after our github push. now you can see it.

**Comment by cotsog** [comment]
@cjyclaire: Thanks so much for handling this quickly! 👍
