### ISSUE TITLE
#get_queue_attributes not working and returns Unknown Attribute Error

### ISSUE THREAD

**Issue by dimitrovmaksim** [aws/aws-sdk-ruby#1632]
### Issue description
#get_queue_attributes not working and now returns `Aws::SQS::Errors::InvalidAttributeName (Unknown Attribute 'ApproximateNumberOfMessages.):`, even when requesting 'All' attributes. It was working fine a week or two ago. We have been using it in production for some time now for queue statistics and it just stopped working. Tried it on couple AWS accounts and the result is the same.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk', '~> 2'

### Version of Ruby, OS environment
Version: ruby 2.3.1p112 
OS: MacOS Sierra 10.12.6 / 64bit Amazon Linux 2017.03 v2.5.0 running Ruby 2.3 

### Code snippets / steps to reproduce

**Comment by cjyclaire** [comment]
@dimitrovmaksim Sorry to hear that, yet I couldn't reproduce the issue with both V2 and V3 SDK, could you try contact [AwsSupport](https://console.aws.amazon.com/support/home) here to get help? They could help look into request IDs to see if anything went wrong. They will engage us as well if this has to do with SDK.

**Comment by dimitrovmaksim** [comment]
@cjyclaire thanks for the reply. Rewrote the code to be 100% sure and it works now. It seems it was something In our code, that I could not locate earlier. Sorry for the inconvenience!

**Comment by dev-afzy** [comment]
@dimitrovmaksim  if you don't mind will please drop a example here. I am also getting the same error Unable to figure out

**Comment by dimitrovmaksim** [comment]
@dev-afzy I can't remember now where it was and if it's still used. Can you show me a code snippet?
