### ISSUE TITLE
Changelog link in README is broken

### ISSUE THREAD

**Issue by Throne3d** [aws/aws-sdk-ruby#1633]
### Issue description

In [the README](https://github.com/aws/aws-sdk-ruby/blob/0b2eb82f1a20b02fc768e8095655b5464c7feb81/README.md), the "Change Log" link is broken. This currently points to <https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md>, which provides a 404 from GitHub.

I tried looking elsewhere for this changelog, such as [on the Amazon AWS website](https://aws.amazon.com/releasenotes/Ruby?browse=1), but [the latest note published](https://aws.amazon.com/releasenotes/Ruby/3909343562340729) also links to this GitHub's CHANGELOG (see the text "[GitHub ](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md)" (including the space as a link) which links to the master branch's CHANGELOG.md).

(Is there a better place to find this?)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

The `aws-sdk-ruby` repository, as of commit 8dbd53c2a234886dadee3e38f001a5ce808fb3d1. The gem I am using locally is `aws-sdk-s3` (now version 1.5.0 – so, version 3 of the SDK). I was looking for the changelog of this gem between versions 1.4.0 and 1.5.0.

### Version of Ruby, OS environment

N/A, Arch Linux.

I am using Google Chrome to view GitHub's platform and accordingly the source code / documentation. For context, I am using Ruby 2.4.2 (again on an Arch Linux machine running the KDE Plasma desktop environment) for the project with the gem I want to find the changelog of, but this does not seem relevant to the actual issue as it seems to be a documentation issue.

### Code snippets / steps to reproduce

- Go to the above link for the README at commit 0b2eb82f1a20b02fc768e8095655b5464c7feb81 (latest as of this issue) – that is, <https://github.com/aws/aws-sdk-ruby/blob/0b2eb82f1a20b02fc768e8095655b5464c7feb81/README.md>
- Locate the "Change Log" link under "Links of Interest", which links to the above-linked problematic Change Log link – that is, <https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md>
- Note that when the link is followed it produces a 404 error

**Comment by cjyclaire** [comment]
PR #1634 is opened to address this issue, thanks for reporting!

**Comment by cjyclaire** [comment]
Just merged, closing : )

**Comment by Throne3d** [comment]
Thanks!
