### ISSUE TITLE
EC2::Client#associate_iam_instance_profile is returning with an InvalidAction exception

### ISSUE THREAD

**Issue by MMartyn** [aws/aws-sdk-ruby#1636]
Please fill out the sections below to help us address your issue

### Issue description
I am creating a role, instance profile, and associating the role to the profile through the SDK. Then I am attempting to associate that profile with a running EC2 instance. According to the docs I am calling it correctly: http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#associate_iam_instance_profile-instance_method

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk (2.10.61)

### Version of Ruby, OS environment
Ruby 2.3

### Code snippets / steps to reproduce
```
ec2_client = Aws::EC2::Client.new
ec2_client.associate_iam_instance_profile({
  iam_instance_profile: {
    arn: {profile_arn},
    name: {profile_name}
  },
  instance_id: {instance_id}
})
```

**Comment by cjyclaire** [comment]
@MMartyn Sorry for the late reply, yet I couldn't reproduce the error for the API. Feel free to contact [Aws Support](https://console.aws.amazon.com/support/home) as well, they can help look into request Ids. Or other channels listed at [Geting Help section](https://github.com/aws/aws-sdk-ruby#getting-help)

**Comment by MMartyn** [comment]
Weird. Not sure why you are unable to reproduce. I just tested it again and got the same error:

```Aws::EC2::Errors::InvalidAction: The action AssociateIamInstanceProfile is not valid for this web service.```

**Comment by MMartyn** [comment]
@cjyclaire I am going to go ahead and close. It turned out to be an issue on our side where we were locking down the api version higher up in our code. Thanks for your time.
