### ISSUE TITLE
Typo: Should be 'skip_final_snapshot'

### ISSUE THREAD

**Issue by gatopan** [aws/aws-sdk-ruby#1640]
https://github.com/aws/aws-sdk-ruby/blob/09cc03cfbe45f69a61a0a45b80b5e738888ab956/gems/aws-sdk-rds/lib/aws-sdk-rds/db_cluster.rb#L722

**Comment by cjyclaire** [comment]
Thanks for reporting, have reached out to doc team about this :)

**Comment by cjyclaire** [comment]
This is tracked by doc team, docs updates will be auto include in SDK release once it's fixed.
Closing, free feel to reopen with further comments : )
