### ISSUE TITLE
SSM client returns unexpected data from stubbed methods

### ISSUE THREAD

**Issue by brianknight10** [aws/aws-sdk-ruby#1641]
### Issue description
When stubbing the response for `get_parameter` on the SSM client, I am not getting the expected data returned. See code snippet below. I have used this way of stubbing with other Client methods in the SSM client (such as `get_parameters_by_path`) with no issues.

### Gem name and its version
`aws-sdk-ssm` version 1.2.0

### Version of Ruby, OS environment
Mac OSX Sierra, version 10.12.6
Ruby 2.4.2

### Code snippets / steps to reproduce
```
param = OpenStruct.new(name: '/foo/bar/baz', type: 'String', value: 'test')
client = Aws::SSM::Client.new(stub_responses: { 
               get_parameter: OpenStruct.new(parameter: param) })

resp = new_client.get_parameter({
              path: path,
              with_decryption: false
            })

resp.parameter
```
returns
```
#<struct Aws::SSM::Types::Parameter name="PSParameterName", type="ParameterType", value="PSParameterValue">
```

Thank you for your help.

**Comment by cjyclaire** [comment]
@brianknight10 Hmm I'm guessing  "path ..." is a mis-paste in your code snippet, yet I cannot reproduce the error with your code snippet:
![image](https://user-images.githubusercontent.com/10790394/31639961-797084ce-b290-11e7-922c-e50e99b22654.png)

**Comment by brianknight10** [comment]
I sincerely apologize. I had a threading issue happening and that was the cause of my problem. Everything looks good!
