### ISSUE TITLE
API Definition for CloudFormation#describe_stack_events should mark `stack_name` as required.

### ISSUE THREAD

**Issue by supersam654** [aws/aws-sdk-ruby#1642]
### Issue description

According to the official docs at http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#describe_stack_events-instance_method, `describe_stack_events` has no required arguments. I've confirmed that the api definitions included on the `master` branch of this repo also don't mark any arguments as required:

https://github.com/aws/aws-sdk-ruby/blob/master/apis/cloudformation/2010-05-15/api-2.json#L998

```
"DescribeStackEventsInput":{
  "type":"structure",
  "members":{
    "StackName":{"shape":"StackName"},
    "NextToken":{"shape":"NextToken"}
  },
```

However, calling `describe_stack_events`  without passing in a `stack_name` creates a `ValidationError` about `stackName` being `null`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk v2.10.65

### Version of Ruby, OS environment

ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

### Code snippets / steps to reproduce

```
irb(main):001:0> client = Aws::CloudFormation::Client.new
=> #<Aws::CloudFormation::Client>
irb(main):002:0> client.describe_stack_events
Aws::CloudFormation::Errors::ValidationError: 1 validation error detected: Value null at 'stackName' failed to satisfy constraint: Member must not be null
...
```

**Comment by cjyclaire** [comment]
Thanks for reporting, I can reproduce this, reaching out to service team

**Comment by cjyclaire** [comment]
Soft update, service team is aware of this and this is tracked.

**Comment by supersam654** [comment]
Thanks for the update. I found another 6 API calls that I think should have a parameter marked as required (just like this one). What's the best way for me to report those (separate issues, just comment here, something else.)?

**Comment by cjyclaire** [comment]
Wow sorry to hear that, sure, there are several channel, you can contact [`Aws Support`](https://console.aws.amazon.com/support/home) if you want direct conversations with service team, and they will reach out to us if they need our help. You can open an issue with us as well. Also you can also open stackoverflow questions with tags, service team will help out as well. Further more, there is "Provide feedback" button sits at bottom for documentation page, like [cloudformation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html).

**Comment by supersam654** [comment]
Thanks. I contacted Support and they're handling them.

**Comment by cjyclaire** [comment]
Closing, once service team have this updated, it will flow into our release automatically : )
