### ISSUE TITLE
Deprecation of Resource#wait_until methods

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#1648]
### Issue description

Why is #wait_until for Resource deprecated?

Documentation suggests that waiters on the equivalent Client are to be used instead but those methods only support pre-defined waiters.

The Resource#wait_until methods allow an arbitrary evaluation of the resource which can be used to produce custom waiters, which is not possible with the Client methods.

eg This is from code that manages version level restores of S3 (from before S3 supported tags)
```ruby
       # Wait until tags are updated on an S3 object indicating the restore is complete
        s3_object.wait_until(max_attempts: status_attempts, delay: 10, before_wait: before_wait) do |object|
          status = object.exists? && (object.metadata['restore_status'] )
          ! finish_statuses.include?(status)
        end
```

**Comment by cjyclaire** [comment]
Good to know! So resource `#wait_until` is marked as deprecated mainly to due the fact that the shared resource model is easy to be outdated when compared with client API models, we would not remove it to introduce breaking changes : ) And we have a backlog feature to support custom waiters as well : )

Closing, feel free to reopen with further comments or questions, I'll also add a  "+1" for custom waiters in our feature backlog : )
