### ISSUE TITLE
Aws::EC2::Image#create_tags no longer accepts Symbols in tag entries

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#1650]
### Issue description

Errors using V3 to create tags from code previously working in V2

### Code snippets / steps to reproduce

```ruby

tags_as_hash = { 'mytag' => 'myvalue' }
aws_tags = tags_as_hash.map { |(k, v)| {key: k, value: v} }

image.create_tags(tags: aws_tags)
# => ArgumentError: expected :key to be a String, got Symbol at
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/tag.rb:264:in `extract_key'
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/tag.rb:26:in `initialize'
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:372:in `new'
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:372:in `block in create_tags'
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:371:in `each'
#  /opt/bambooagent/.gem/ruby/2.3/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:371:in `create_tags'
```

**Comment by cjyclaire** [comment]
Hmmm, tag [does](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-ec2/lib/aws-sdk-ec2/tag.rb#L258) check `:key`, the key value should be a string type instead of symbol type. 

Weird, from your code snippet, it's a string, taking a look to reproduce.

**Comment by cjyclaire** [comment]
Hmmm I copy paste your snippet and tried with a newly created image and succeed for me.

**Comment by lwoggardner** [comment]
Apologies.  I misinterpreted the error message - it means the value of :key is a Symbol not that the inner tag entry is :key rather than "key".

So a proper sample would be
```ruby
>> tags_as_hash = { mytag: 'myvalue' } #=> {:mytag=>"myvalue"}
>> aws_tags = tags_as_hash.map { |(k, v)| {key: k, value: v} } #=> [{:key=>:mytag, :value=>"myvalue"}]
>> image.create_tags(tags: aws_tags)
#ArgumentError: expected :key to be a String, got Symbol
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/tag.rb:264:in `extract_key'
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/tag.rb:26:in `initialize'
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:372:in `new'
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:372:in `block in create_tags'
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:371:in `each'
#	from C:/tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/aws-sdk-ec2-1.13.0/lib/aws-sdk-ec2/image.rb:371:in `create_tags'
```

Although this does work on V2 I can understand if it was just an accident that V2 accepted symbols here while V3 has stricter validation but it is a backwards compatibility issue nonetheless.

For me it is ok, I can just change my utility code (and move on to whatever fails next :-) )

**Comment by cjyclaire** [comment]
I see, yeah, it's true that we would prefer stronger validations since they are string types.
Sorry to hear and appreciate that! Feel free to open issues with us with any problems you have in migrating, always happy to take a look : )

**Comment by lwoggardner** [comment]
Thanks (BTW  I finished my migration - no further V2 - V3 issues)
