### ISSUE TITLE
Calls to rds resource.create_db_cluster always throws an exception

### ISSUE THREAD

**Issue by parsley42** [aws/aws-sdk-ruby#1652]
Please fill out the sections below to help us address your issue

### Calling resource.create_db_cluster(option) always throws an exception:
code:
```ruby
    def create_db_cluster(options = {})
      resp = @client.create_db_cluster(options)
      DBCluster.new(
        id: options[:db_cluster][:db_cluster_identifier],
        data: resp.data.db_cluster,
        client: @client
      )
    end
```
The  problem is in the 4th line in the reference to options[:db_cluster] - which not only isn't a key, but if you call the method with the key set you get an exception in the option validator.

### Gem name: aws-sdk-rds v. 1.6.0, aws-sdk 3.0.1

**Comment by cjyclaire** [comment]
Thanks for reporting, you are right, this looks like cause by shared resource model definition [here](https://github.com/aws/aws-sdk-ruby/blob/master/apis/rds/2014-10-31/resources-1.json#L12), marking this as resource models issue.

**Comment by cjyclaire** [comment]
Tracked in [feature backlog](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#rds-resource-createdbcluster-path-issue) as a shared resource model issue, closing.
