### ISSUE TITLE
Installing version 2 of aws-sdk gem fails

### ISSUE THREAD

**Issue by patrobinson** [aws/aws-sdk-ruby#1663]
### Issue description

When running `gem install aws-sdk -v '~>2'` the installation fails with:

```
ERROR:  Could not find a valid gem 'aws-sdk-resources' (= 2.10.88) in any repository
ERROR:  Possible alternatives: aws-sdk-resources
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk version 2.10.88. Installing version 2.10.87 works

### Version of Ruby, OS environment

Ruby 2.2.4, debian running the docker image `ruby:2.2.4-slim`

### Code snippets / steps to reproduce

```
gem install aws-sdk -v '2.10.88'
```

**Comment by cjyclaire** [comment]
@patrobinson This has been [fixed](https://rubygems.org/gems/aws-sdk-resources/versions/2.10.88), RubyGem yelled at us at the first time :)
