### ISSUE TITLE
More detailed changelog entries?

### ISSUE THREAD

**Issue by oyeanuj** [aws/aws-sdk-ruby#1666]
Hi folks! Firstly, thank you for all of your work in these gems. One suggestion - would it be possible to add more details to the changelog in the individual gems so that developers know what to expect?

Right now, most entries look like this:
> Feature - API update.

This doesn't give enough information on what to expect, thus creating uncertainty and needing a developer to first look through commits in history, narrow down to the gem in question and go file by file.

I am sure there is already a lot on your plate, but this would really help the DX a lot.

Thank you!

**Comment by cjyclaire** [comment]
Thanks for the feedback! Tracking this in feature backlog.
At same time, while the release note will be few sentences, you can always find detail intro of each feature release at AWS [what's new](https://aws.amazon.com/new/) : )

**Comment by chevinbrown** [comment]
@cjyclaire, Thanks for your work on this gem. I'm in agreement with @oyeanuj on this one. Maintaining OSS is difficult, but updating dependencies with vague descriptions is too. 😸 
Having a simple explanation would save everyone that uses this gem some time and make the upgrade process smoother. 
❤️

**Comment by truongnmt** [comment]
Sorry to bring those back but I agree with @oyeanuj 
Some of the Changelog is like below:

> (aws-sdk-sqs)
> 1.26.0 (2020-05-28)
> Feature - Code Generated Changes, see ./build_tools or aws-sdk-core's CHANGELOG.md for details.

The message is not really helpful I think. Looking at [build_tools](https://github.com/aws/aws-sdk-ruby/blob/master/build_tools/build_tools.rb) (I suppose this file) does not bring much helpful details.

I'm wondering `aws-sdk-core's CHANGELOG.md` is this? 🤔 
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md

For example, the above sqs changelog on version 1.26.0 at 2020-05-28, to see more "details" I have to look for [release changelog on the same day](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md#3970-2020-05-28).
