### ISSUE TITLE
Please publish aws-sdk-resources 2.10.97

### ISSUE THREAD

**Issue by alexbecker** [aws/aws-sdk-ruby#1667]
You have published a aws-sdk 2.10.97 to rubygems.org, which depends on aws-sdk-resources 2.10.97, but you have not yet published that. All packages depending on aws-sdk <3 not pinned to a specific patch version are now broken. Unfortunately this includes https://github.com/travis-ci/dpl, so all Travis CI deploys to AWS are currently broken.

**Comment by alexbecker** [comment]
It's been published, and deploys on Travis are working again. Thanks.

**Comment by cjyclaire** [comment]
Thanks for the patience! Ruby Gems yelled at us when we are publishing too many gems :( I'll enhance our release with better retry for Ruby Gems.
