### ISSUE TITLE
CostExplorer API Issue

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#1669]
Please fill out the sections below to help us address your issue

### Issue description
[The SDK docs](http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CostExplorer/Client.html#get_cost_and_usage-instance_method) indicate that REGION is one of the values that can be used as a dimension when querying the CostExplorer.

Specifying REGION as a dimension is returning this error:

```Ruby
Dimension not valid. Valid values are AZ, INSTANCE_TYPE, LINKED_ACCOUNT, OPERATION, PURCHASE_TYPE, SERVICE, USAGE_TYPE, USAGE_TYPE_GROUP, PLATFORM, TENANCY, RECORD_TYPE (Aws::CostExplorer::Errors::ValidationException)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-costexplorer-1.0.0

### Version of Ruby, OS environment
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]

### Code snippets / steps to reproduce
```Ruby
options = {
        time_period: {
            start: "2017-11-01",
            end: "2017-12-30"
        },
        granularity: "MONTHLY",
        filter: {
            and: [
                {
                    dimensions: {
                        key: "LINKED_ACCOUNT",
                        values: [aws]
                    }
                },
                {
                    dimensions: {
                        key: "REGION",
                        values: ['us-east-1']
                    }
                }
            ]
        },
        metrics: ["UnblendedCost"],
        group_by: [
            {
                type: "DIMENSION",
                key: "USAGE_TYPE"
            }
        ]
    }

     response = explorer.get_cost_and_usage(options)
```

**Comment by cjyclaire** [comment]
Thanks for the info, taking a look to reproduce

**Comment by cjyclaire** [comment]
I can reproduce this, I reached out to service team about this, will update.

**Comment by cjyclaire** [comment]
A quick update, 'REGION' is not supported for this API for now(but is supported for some other APIs), the error message is correct.
Since SDK is generating the hint for the enum shape, it listed all enums [available](https://github.com/aws/aws-sdk-ruby/blob/master/apis/ce/2017-10-25/api-2.json#L92).

Sorry for the confusion right now, we have recommended service team to have different enum shapes for situations like this in the future.

**Comment by pchaganti** [comment]
Got it. Thanks for the update!
