### ISSUE TITLE
AWS::S3::Client#delete_objects: validate number of keys

### ISSUE THREAD

**Issue by dadah89** [aws/aws-sdk-ruby#1670]
### Issue description
Recently I spent some time tracking this exception: `Aws::S3::Errors::MalformedXML: The XML you provided was not well-formed or did not validate against our published schema` (while executing `AWS::S3::Client#delete_objects`). Turns out I was going over the 1000 keys limit, but the error message made me spent way more time than I should have.

Instead, would be good if the method itself validated the number of keys, raising a nice error message and preventing a request to the AWS S3 api.

I'm also trying to post a message in the AWS discussion forums to improve their error message (trying because my account seems to be too new to post messages...).

Feel free to just close this if the latest gem version (I'm still using v2) already does something similar.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-core (2.10.96)

### Version of Ruby, OS environment
Ruby 2.4.1, Linux.

### Code snippets / steps to reproduce
```rb
client = Aws::S3::Client.new( ... )
path = [ ... array with more than 1000 keys ... ]
client.delete_objects(
  delete: { objects: paths } },
  request_payer: 'requester',
  bucket: 'bucket-name'
)
```

**Comment by cjyclaire** [comment]
Thanks, appreciate the information, just forwarded the message to S3 service team as well.

**Comment by awood45** [comment]
The correct answer would probably be for the service to raise a more friendly error message, though we will work with them on that. The problem with adding this validation on the client level in general tends to be that if service limits change, you'd have invalid behavior, though given the limit size of 1000, we might be able to consider an exception in this case.

**Comment by awood45** [comment]
On further review, I think this is a case where the service needs to pass on more user-friendly errors, and we've given them feedback in that regard, especially due to related issues we've seen. Closing this as the action isn't something we can control, and when it happens, the SDK will behave differently automatically.
