### ISSUE TITLE
Where do I find the aws.rb REPL mentioned in the documentation?

### ISSUE THREAD

**Issue by richardkmichael** [aws/aws-sdk-ruby#1672]
I am following documentation about using the REPL, here:

http://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/repl.html

It refers to the REPL in the file `aws.rb`, as part of the `aws-sdk-core` gem.  However, my just-installed `aws-sdk-core` gem contains no such file:

```
$ bundle show aws-sdk-core
/Users/testuser/project/vendor/bundle/ruby/2.4.0/gems/aws-sdk-core-3.11.0
$ find $(bundle show aws-sdk-core) -iname aws.rb
$
```
(Actually, none of the `aws-sdk-*` gems installed contain `aws.rb`.)

What have I misunderstood?  Thank you!

**Comment by cjyclaire** [comment]
@richardkmichael Ah sorry about the confusion! It should be [`aws-v3.rb`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-resources/bin/aws-v3.rb) for V3 SDK instead, it's available at `aws-sdk-resources` gem and [`aws-sdk`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk/aws-sdk.gemspec#L14) gem. I'll reach out to doc team to update the page. And I'll create a PR to address this in our README.md as well.

**Comment by cjyclaire** [comment]
Some quick background there, `aws.rb` is the name of V2 SDK REPL file : )

**Comment by richardkmichael** [comment]
@cjyclaire Great, I'm using it now.  Thank you!
