### ISSUE TITLE
Is there a way to show http_wire_trace after an error occurs?

### ISSUE THREAD

**Issue by arianf** [aws/aws-sdk-ruby#1678]
I'm currently using v2.

I know you can enable the `http_wire_trace: true` option new you create a client. But let's say if it's off by default, and I make a `object.upload_file('/tmp/test')` and for example I get back something like a `Aws::S3::Errors::Http500Error` error and I want to see the `http_wire_trace` after that came back as error, is that possible?

```ruby
Aws::S3::Client.new(
      ...,
      http_wire_trace: true
)
```

**Comment by cjyclaire** [comment]
@arianf We use `http_wire_trace` to set `:set_debug_output` in Ruby `net/http`. We don't have much control over there. Curious about what information are you trying to see there?

**Comment by awood45** [comment]
Basically, that setting will tell you what we are sending over the wire in real time - we aren't keeping it for later display. However, you COULD inspect the HTTP request and responses after the fact. Consider:

```ruby
s3 = Aws::S3::Client.new
begin
  s3.list_objects(bucket: "nosuchbucket12345")
rescue Aws::S3::Errors::NoSuchBucketError => e
  # You could look at the raw HTTP Request with:
  e.http_request # This is a hash with body, headers, etc.
  # And the raw HTTP Response with:
  e.http_response # Again, a hash
end
```

This should give you the ability to look in to a request which failed. If you want to change the http_wire_trace setting after the fact, for future requests, you can do so simply:

```ruby
s3 = Aws::S3::Client.new
s3.list_buckets # No wire tracing
s3.config.http_wire_trace = true
s3.list_buckets # Will include wire tracing
s3.config.http_wire_trace = false
s3.list_buckets # Will not have wire tracing
```

**Comment by awood45** [comment]
This should cover what you're trying to do, and works the same in V3. Closing, let me know if you have any other questions.
