### ISSUE TITLE
Inconsistent presigned urls when using AWS CLI and aws-sdk-s3 gem version 1.8.0.

### ISSUE THREAD

**Issue by LaithAzer** [aws/aws-sdk-ruby#1682]
### Issue description

Inconsistent presigned urls when using AWS CLI and `aws-sdk-s3` gem version 1.8.0.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-s3`, version 1.8.0

### Version of Ruby, OS environment

Ruby 2.4.2, Ubuntu 14.04.3

### Code snippets / steps to reproduce

When using the AWS CLI to generate a presigned_url, it returns a url in the following format:

`<ENDPOINT>/<BUCKET>/<OBJECT_NAME>?X-Amz-Algorithm=...`

This url works when trying to read the object.

However, when using the `aws-sdk-s3` gem, generating the presigned_url returns the following format:

`<BUCKET>.<ENDPOINT>/<OBJECT_NAME>?X-Amz-Algorithm=...`

As you can see using the gem the bucket name is in the host while using the CLI the bucket name is in the path. Is there any reason why there is a difference and why the url with bucket in the path works but the other doesn't?

Thank you.

**Comment by cjyclaire** [comment]
Amazon S3 supports both virtual-hosted–style and path-style URLs to access a bucket. And Ruby support both, Ruby S3 gem default to [virtual-host style](https://github.com/aws/aws-sdk-ruby/blob/9ea447b7e9e57e27bb7924aca40a5bf0c3265a94/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L140), you can set `: force_path_style` to `true` at client constructor to get the path style pattern (in your CLI example).

**Comment by LaithAzer** [comment]
That resolved it, thank you!
