### ISSUE TITLE
ECS register_task_definition validation bug (log_driver)

### ISSUE THREAD

**Issue by comjf** [aws/aws-sdk-ruby#1685]
### Issue description
I'm taking an existing valid task definition in json format, converting it to the proper casing and then resubmitting via the SDK. Only 1 validation error on submission: 
```
2017-12-29T15:34:58.285Z 79621 TID-oumh4as1o WARN: ArgumentError: missing required parameter params[:container_definitions][0]["log_configuration"][:log_driver]
```

I can hack around this by either doing ```task['container_definitions'].first['log_configuration'][:log_driver] = 'awslogs'``` to explicitly set the log_driver to be a symbol or it also works if I disable validation entirely ``` Aws::ECS::Client.new(region: 'us-east-1', validate_params: false)```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
    aws-sdk (2.10.105)
      aws-sdk-resources (= 2.10.105)
    aws-sdk-core (2.10.105)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.10.105)
      aws-sdk-core (= 2.10.105)
    aws-sigv4 (1.0.2)
```
### Version of Ruby, OS environment
2.3.1  on OSX 
### Code snippets / steps to reproduce
- Logging definition in json
```
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "awslogs-some-service",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "some-service"
        }
      },
```
- Main code body
```
    ecs = Aws::ECS::Client.new(region: 'us-east-1')
    task = JSON.parse(File.read(task_file))
    task['containerDefinitions'].first['image'] = publish_image

    skip_transform = task['containerDefinitions'].first['logConfiguration'].delete('options')
    task.deep_transform_keys!(&:underscore).with_indifferent_access
    task['container_definitions'].first['log_configuration']['options'] = skip_transform
   
    task_revision = ecs.register_task_definition(
        {container_definitions: task['container_definitions'], family: task['family'], task_role_arn: task['task_role_arn']}
    )['task_definition']['revision']
```

**Comment by awood45** [comment]
The request needs to be of the format shown in the [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#register_task_definition-instance_method).

It looks like some of your request does follow the documented format, and other portions do not. In fact, I suspect as written your options would be ignored. Use symbolized, snake-case keys where called upon in the documentation (for known shapes - the arbitrary hash within "options" should use the format you already have).

**Comment by awood45** [comment]
Let me know if this helps, or if you have follow-up questions after reading the documentation.

**Comment by comjf** [comment]
@awood45 Thanks for your response, but I'm a little confused... Shouldn't you be able to convert between the ```--cli-input-json``` referenced all over the place in AWS documentation and 
the gem input?

To be clear, all I'm doing to reproduce is:
- Taking a valid configuration in json format (I know it's valid as I can upload via: ```aws ecs register-task-definition --cli-input-json```)
- My transformation is simply changing the hash keys to be the correct format and ignoring the "options" key (as those contain dashes)
- I expect to be able to upload this via the aws-sdk gem, but the gem validation gives me an error for just the log_driver field. 

I know it's a problem with the gem and not AWS since:
1. The CLI accepts my input
2. The gem accepts my input as long as I initialize the client with ```validate_params: false```

**Comment by pizzaops** [comment]
I'm also experiencing this bug (exposed via the puppetlabs-aws puppet module).

**Comment by awood45** [comment]
It does look like, when I look at this on some other services as well, that the issue is `validate_params` expecting symbolized keys. It triggers on `log_driver` since that's a required param.

Turning off `validate_params` is a valid workaround for the moment, will look at a fix.

**Comment by awood45** [comment]
Just for a quick update, turning off `validate_params` is NOT a valid workaround per my testing. Essentially, the gem requires symbolized keys for parameters in both Versions 2 and 3. This does help with avoiding issues like duplicate keys for the same param, so figuring out a good way to work around this is not a quick fix.

I'd be curious to know if you're actually getting a valid result when you're sending your requests over the wire with `validate_params: false`, or if the gem is accepting the input but the service is either missing your input or returning an error.

To do what the CLI is doing, we would likely need to create an explicit way to pass JSON parameters, rather than implying a non-symbolized hash which came from JSON is valid input to the client (which then opens us up to other issues since `:log_driver != "log_driver"`).

**Comment by pizzaops** [comment]
Also not much help to folks like me who are using a piece of software that depends on the gem, not working with it directly. I guess we could carry a custom patch to that software since it's Ruby, but yeah.

We have the power to upgrade the gem and test, but not the power to easily change how it's being used.

**Comment by awood45** [comment]
What patch did you have in mind, if you were able to do that patching? I'd encourage them to symbolize keys which align with API parameters, since that's required behavior (and has been for the life of the SDK).

I think the feature request to explore safe ways to make that more permissive is valid, but it's going to take some time to do safely.

**Comment by awood45** [comment]
There is a way we can do this, and it may work without param validation in some services, but not others, today. Depends on protocol. It's not yet something we support and validate with tests, so I'd use caution with turning off `validate_params`, or with using non-symbolized keys (using the JSON parser's ability to symbolize keys for you may be handy if consuming JSON).

We're looking at this as a feature request to look at how we could systematically support non-symbolized keys.

**Comment by pizzaops** [comment]
Do subkeys need to be symbolized? 

For example:

```
  {
    'log_driver' => 'syslog',
    'options' => {
        'tag' =>  '{{.ImageName}}\{{.Name}}\{{.ID}}'
    }
  }
```

Does `tag` need to be symbolized here? Or just `options` and `log_driver`?

**Comment by awood45** [comment]
Yes, it should be.

**Comment by awood45** [comment]
To give some background, we have a task to investigate a safe way to consistently handle both symbolized and non-symbolized keys in our backlog. Likely, this would involve validation exceptions if the same key is provided twice.

**Comment by comjf** [comment]
@awood45 Thanks mate! When you have a test candidate please let me know (even if it requires me building from source).

I did get around my issue with ```validate_params: false ``` but I'd love to turn that on the moment this bug is fixed and have a backlog issue tracking it.

**Comment by pizzaops** [comment]
I'm leaving validate_params on, and carrying a patch to `puppetlabs-aws` (yes, lol, i know) that symbolizes the keys for logging configuration (the rest seems to work so I'm leaving it alone).

To answer your earlier question about what kind of patch I was thinking about: https://github.com/OtoAnalytics/puppetlabs-aws/commit/2f948e83d8e812d5fc958630fa24d5724e64f7d5

(This isn't confirmed working yet, just trying things)

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.
