### ISSUE TITLE
Question: How to search in specific folders when results are more than 1000?

### ISSUE THREAD

**Issue by kjenney** [aws/aws-sdk-ruby#1688]
Please fill out the sections below to help us address your issue

### Issue description
I'm trying to gather a list of files inside of a prefix with a very large number of objects (+1000). For instance:

```
mydata/logs/2007-08-09/backup.gz
...
mydata/logs/2010-05-03/backup.gz
...
mydata/logs/2015-08-14/backup.gz
...
mydata/logs/2017-08-09/backup.gz
```

The ...'s are EVERY single date between each timestamp. I'm searching under mydata/logs and it has 1000's of objects in it. I only want to return those prefixes from 2017, i.e.

```
mydata/logs/2017-**-**/*
```

Is this possible? If not, would it be possible to search backwards from the latest date(i.e. 2018-01-05)?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3 1.8.0

### Version of Ruby, OS environment
Ruby 2.4.1
### Code snippets / steps to reproduce
Output of search only returns the first 1000 results from a prefix.

**Comment by buildadmin** [comment]
My workaround now is to use the AWS CLI, dump the output of ALL objects into a file and then run Regex matches on the lines of the file:

```
    basefolder = File.basename folder
    system("aws s3 ls s3://#{@bucket}/#{folder} --recursive | awk '{print $4}' > /tmp/#{basefolder} 2>&1")
    File.readlines("/tmp/#{basefolder}").each do |line|
      @searches.each do |search|
        puts line if line.match(search)
      end
    end
    system("rm /tmp/#{basefolder}")
```

I would really like a more elegant (and correct) way of accomplishing this :) Thanks!

**Comment by kjenney** [comment]
My workaround now is to use the AWS CLI, dump the output of ALL objects into a file and then run Regex matches on the lines of the file:

```
    basefolder = File.basename folder
    system("aws s3 ls s3://#{@bucket}/#{folder} --recursive | awk '{print $4}' > /tmp/#{basefolder} 2>&1")
    File.readlines("/tmp/#{basefolder}").each do |line|
      @searches.each do |search|
        puts line if line.match(search)
      end
    end
    system("rm /tmp/#{basefolder}")
```

I would really like a more elegant (and correct) way of accomplishing this :) Thanks!

**Comment by awood45** [comment]
This is a pagination/prefix selection question. Do you have a snippet of Ruby code for what you're doing now?

**Comment by kjenney** [comment]
Here's the code that I'm working off of right now:

```
class S3Find
  def initialize(bucket, searches, prefix)
    @s3 = Aws::S3::Client.new
    @bucket = bucket
    @searches = searches
    @prefix = prefix
  end

  # Returns an array of S3 bucket folders
  def sub_folders
    array = []
    resp = @s3.list_objects_v2(bucket: @bucket, prefix: @prefix, delimiter: '/')
    resp.common_prefixes.each do |folder|
      array.push(folder.prefix)
    end
    array
  end

  # Returns a list of files from an S3 folder
  # PATCH: For now we don't know how to search past 1000 objects, so just
  # use the local AWS CLI to pull in ALL of the results and filter from there
  # TODO: Get this working
  def list_matches_in_folder(folder)
    #resp = @s3.list_objects_v2(bucket: @bucket, prefix: folder)  ## TODO
    basefolder = File.basename folder
    system("aws s3 ls s3://#{@bucket}/#{folder} --recursive | awk '{print $4}' > /tmp/#{basefolder} 2>&1")
    File.readlines("/tmp/#{basefolder}").each do |line|
      @searches.each do |search|
        puts line if line.match(search)
      end
    end
    #system("rm /tmp/#{basefolder}")
    #resp.contents.each do |object|
    #  puts object.key
      #@searches.each do |search|
      #  puts object.key if object.key.match(search)
      #end
    #end
  end
end

s3 = S3Find.new(bucket, searches, prefix)
subs = s3.sub_folders
subs.each do |folder|
    s3.list_matches_in_folder(folder)
  end
end
```

bucket is the bucket that you want to query.
searches is an array of Regular Expressions
prefix is the prefix within the bucket that would to query under.

list_matches_in_folder is where i'm getting stuck. I'm only getting back 1000 results from a query where there are more than 1000 objects. So I never get to the prefixes that I actually want to search (i.e. 2017-01-01).

**Comment by kjenney** [comment]
I did a little searching and found some documentation on pagination here:
https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/paging-responses.html

I've adjusted the code in my class and it works perfectly:

```
class S3Find
  def initialize(bucket, searches, prefix)
    @s3 = Aws::S3::Client.new
    @bucket = bucket
    @searches = searches
    @prefix = prefix
  end

  # Returns an array of S3 bucket folders
  def sub_folders
    array = []
    resp = @s3.list_objects_v2(bucket: @bucket, prefix: @prefix, delimiter: '/')
    resp.common_prefixes.each do |folder|
      array.push(folder.prefix)
    end
    array
  end

  # Returns a list of files from an S3 folder matching one regex search
  # from @searches array
  def list_matches_in_folder(folder)
    @s3.list_objects_v2(bucket: @bucket, prefix: folder).each do |resp|
      s3objpaths = resp.contents.map(&:key)
      s3objpaths.each do |str|
        puts str if search_string(str)
      end
    end
  end

  # Search a string using the search array
  def search_string(str)
    @searches.each do |search|
      return true if str.match(search)
    end
    false
  end
end

s3 = S3Find.new(bucket, searches, prefix)
subs = s3.sub_folders
subs.each do |folder|
    s3.list_matches_in_folder(folder)
end
```

Thanks for the hint!
