### ISSUE TITLE
Support for AWS Transcribe

### ISSUE THREAD

**Issue by CpuID** [aws/aws-sdk-ruby#1689]
Please fill out the sections below to help us address your issue

### Issue description

Can we please get support for AWS Transcribe in the AWS SDK for Ruby packages? I know it's beta, but would still be useful as we are a participant. Thanks!

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-transcribe`

### Version of Ruby, OS environment

All

### Code snippets / steps to reproduce

N/A

**Comment by awood45** [comment]
We don't currently have a mechanism for including beta services in our SDK, we currently only support GA launches. Consider reaching out to the service team to see if they can provide you with anything for the preview.
