### ISSUE TITLE
Stubbing Errors Results in ArgumentError

### ISSUE THREAD

**Issue by davidcpell** [aws/aws-sdk-ruby#1697]
### Issue description

This is related to the SDK stubbing feature: https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/stubbing.html

At the bottom, the documentation indicates that the user should pass the error class name to `#stub_responses`. However, when doing this, we ran into an ArgumentError:

```ruby
client = Aws::IAM::Client.new(stub_responses: true)
client.stub_responses(:get_role, Aws::IAM::Errors::NoSuchEntity)
client.get_role(role_name: "foo")
ArgumentError: wrong number of arguments (given 0, expected 2)
from /Users/davidpell/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/errors.rb:16:in `initialize'
```

Following the error shows that it's happening because two arguments (context and message) are needed to initialize an error. So it seems like there's either a documentation error and it should have something like:

> s3.stub_responses(:head_bucket, Timeout::Error.new("context", "message"))

...or there's a bug in the SDK stubbing code and it should be providing those args automatically somewhere when the user supplies the error class name. (edited)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk` 3.0.1

```
➜ bundle show aws-sdk
/Users/davidpell/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-3.0.1
```

### Version of Ruby, OS environment

MacOSX 10.12.16
Ruby 2.4.2

### Code snippets / steps to reproduce

See above

**Comment by awood45** [comment]
You can do this:

```ruby
client = Aws::IAM::Client.new(stub_responses: true)
client.stub_responses(:get_role, 'NoSuchEntity')
client.get_role(role_name: "foo")
```

I'll leave this open while reviewing the documentation, but this should get you unstuck.

**Comment by awood45** [comment]
@Doug-AWS this could be a developer guide candidate (testing, stubbing, and error stubbing).

**Comment by Doug-AWS** [comment]
Thanks Alex, I'll add it to my list.

**Comment by davidcpell** [comment]
Thanks @awood45! Really love the built-in stubbing feature by the way.
