### ISSUE TITLE
aws-sdk-resources (2.10.128) needs published 

### ISSUE THREAD

**Issue by jessepiccolo** [aws/aws-sdk-ruby#1708]
Please fill out the sections below to help us address your issue

### Issue description

aws-sdk-resources (2.10.128) needs published to rubygems.org

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-resources (2.10.128)

### Version of Ruby, OS environment

Windows

### Code snippets / steps to reproduce

My chef converges result in this:
---- Begin output of bundle install ----
STDOUT: Fetching gem metadata from https://rubygems.org/.............

Fetching version metadata from https://rubygems.org/..

Resolving dependencies...

Using aws-sigv4 1.0.2

Using jmespath 1.3.1

Using chef-rewind 0.0.9

Using chef-sugar 4.0.0

Using bundler 1.12.5

Using aws-sdk-core 2.10.128

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org/gems/aws-sdk-resources-2.10.128.gem)

An error occurred while installing aws-sdk-resources (2.10.128), and Bundler

cannot continue.

Make sure that `gem install aws-sdk-resources -v '2.10.128'` succeeds before

bundling.
STDERR: 
---- End output of bundle install ----
Ran bundle install returned 5

**Comment by cjyclaire** [comment]
It's [there](https://rubygems.org/gems/aws-sdk-resources/versions/2.10.128) already? 
Closing, feel free to reopen with further questions.
