### ISSUE TITLE
invalid configuration option bucket in Aws.config hash object

### ISSUE THREAD

**Issue by jcamejo** [aws/aws-sdk-ruby#1721]
Hi!

I was setting up Aws object on my rails project using aws-sdk 2.6.5 in rails 5.1.2 with paperclip 5.2.1. And i've had some troubles trying to upload my file due to this error in 

`aws-sdk-core-2.6.50/lib/seahorse/client/configuration.rb:165`
`invalid configuration option :bucket`

After some debugging I found out the problem, i was adding the bucket name into my configuration hash, causing the global configuration to add the "bucket" key as a configuration value, but when the S3 client base was trying to add it as a configuration option. It was not possible because the value 'bucket' was not in the configuration struct.

This is my first time digging into and new into this source code, i don't know the whole picture and at first it was my mistake to not correctly read the documentation for the configuration object. But i think adding the bucket name in the configuration hash of the Aws object should not raise an exception and break the execution, maybe a warning or just bypass the value would be ok.

More than an issue is more like a thought on this particular topic, maybe there's another solution that i do not know, or is solved in version 3. Sorry if this comment is out of context. Either way, i have learned a lot digging and debugging.

Thanks!

**Comment by awood45** [comment]
`:bucket` is an option you'd pass into individual API calls, it isn't a client option either globally or for individual clients. What are you trying to do? Do you have a code snippet that explains at a high level what you're trying to run?

**Comment by jcamejo** [comment]
Hi sorry for the delayed answer.

I was trying to set up my bucket for my S3 integration, i've managed it to accomplish it, but i was thinking that maybe it would be nice to set up the default bucket name in the initial global object. But seeing a little bit more on how it works, maybe is not the best idea. Either way, i appreciate the response.

**Comment by awood45** [comment]
No worries, glad you were able to get to a working solution. Indeed it has some potential issues to treat that as global configuration, and we aren't wired for that, but there's nothing stopping you from building abstractions over your own client calls in your code which injects a bucket into calls that require one.
