### ISSUE TITLE
http_open_timeout is not working

### ISSUE THREAD

**Issue by kchsieh** [aws/aws-sdk-ruby#1722]
According to this document:  (https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/timeout-duration.html), when using **http_open_timeout**, the default between retries is 15 seconds.  And it appears this is not the case.

I know there is a request limit for **DeleteRestApi** which is at 2 requests per minute per account, so I set my http_open_timeout to 60, like below:
```bash
client = Aws::APIGateway::Client.new(credentials: role_credentials, retry_limit: 4, http_open_timeout: 60)
```
Then try to delete 3 APIs:
```bash
resp = client.delete_rest_api({
  rest_api_id: 'first',
})
resp = client.delete_rest_api({
  rest_api_id: 'second',
})
resp = client.delete_rest_api({
  rest_api_id: 'third',
})
```
I am getting the following result, I see there are 4 retries, but only about 6 seconds for all the retries:
```bash
I, [2018-03-02T11:10:49.452815 #51588]  INFO -- : [Aws::APIGateway::Client 202 1.613522 0 retries] delete_rest_api(rest_api_id:"first")  

I, [2018-03-02T11:10:49.932882 #51588]  INFO -- : [Aws::APIGateway::Client 202 0.47858 0 retries] delete_rest_api(rest_api_id:"second")  

I, [2018-03-02T11:10:55.493805 #51588]  INFO -- : [Aws::APIGateway::Client 429 5.560033 4 retries] delete_rest_api(rest_api_id:"third") Aws::APIGateway::Errors::TooManyRequestsException Too Many Requests
```

**Comment by awood45** [comment]
`:http_open_timeout` is related to how long we'll attempt to keep a connection open, it is not related to retry logic. @Doug-AWS will look at updating the wording of that example to be more clear.

If you want to expand time between retries, the current way to do that is by modifying the `:retry_backoff` option. So if you wanted a fixed retry spacing of 60 seconds, you could do the following:

```ruby
client = Aws::APIGateway::Client.new(
  credentials: role_credentials,
  retry_limit: 4,
  retry_backoff: lambda { |c| 60 }
)
```

Note that `:retry_backoff` is treated like a lambda, so even though you're looking for a fixed value, you still need to accept the input variable. Try this and let me know if it fixes your issue.

**Comment by kchsieh** [comment]
I added the parameter: **retry_backoff: lambda { |c| 60 }** but it didn't help, all retries happened within 2 seconds.

Fyi, I am using aws-sdk-apigateway v1.9.0 and ruby-2.5.0

**Comment by awood45** [comment]
This is why I shouldn't try to answer issues late at night, yes, I missed the `Kernel.sleep` part. Thank you for catching that.

**Comment by awood45** [comment]
Closing as I think we've resolved this, and the example has been updated. Feel free to reach out if you have more questions/issues.
