### ISSUE TITLE
problems with the gem aws-sdk when deployed Ruby on Rails on localhost

### ISSUE THREAD

**Issue by Gusarov2k** [aws/aws-sdk-ruby#1724]
Hello everyone, and thank you for noticing my problem!
when you create a migration command: bundle exec rake db:setup

Missing Credentials.

Unable to find AWS credentials.  You can configure your AWS credentials
a few different ways:

* Call AWS.config with :access_key_id and :secret_access_key

* Export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to ENV

* On EC2 you can run instances with an IAM instance profile and credentials
  will be auto loaded from the instance metadata service on those
  instances.

* Call AWS.config with :credential_provider.  A credential provider should
  either include AWS::Core::CredentialProviders::Provider or respond to
  the same public methods.

= Ruby on Rails

In a Ruby on Rails application you may also specify your credentials in
the following ways:

* Via a config initializer script using any of the methods mentioned above
  (e.g. RAILS_ROOT/config/initializers/aws-sdk.rb).

* Via a yaml configuration file located at RAILS_ROOT/config/aws.yml.
  This file should be formated like the default RAILS_ROOT/config/database.yml
  file.

That it is necessary to make what the project on the local machine would earn, I am already struggling for 5 day above the given problem, please help.

my system: ubuntu 14, rails 3.2.17, ruby 1.9.3, mysql 5.5

**Comment by awood45** [comment]
How are you providing credentials for this project?

**Comment by Gusarov2k** [comment]
1. I tried to install AWS CLI, then ran aws configure and set the attributes:
AWS Acccess Key ID: key
AWS Secret Access Key: secret
Region: None
Format: None

In the file ~ / My_progect / config / aws-sample.yml replaced the data on
development:
  access_key_id: key
  secret_access_key: secret
test:
  access_key_id: key
  secret_access_key: secret
production:
  access_key_id: key
  secret_access_key: secret

2. In the file, aws-sdk-1.25.0 / lib / aws / core / configuration.rb undocumented

AWS.config (: access_key_id => 'key',: secret_access_key => 'secret')

but instead received a new error:
uninitialized constant AWS :: Core :: Configuration

3. Created variables
ACCESS_KEY_ID = "key"
SECRET_ACCESS_KEY = "secret" in the .bashrc file

**Comment by awood45** [comment]
You're using a version of the SDK that predates support for shared credentials, and it's also an end of life version. Is this a new project or an old one?

If it's a new project, I'd recommend upgrading to V3 of the SDK, in which case a shared credential file created by the CLI is one valid option. Though if you're deploying to EC2 instances, I'd recommend using EC2 Instance Roles which the SDK with automatically pick up.

If it's an old project, I'd at very minimum recommend upgrading first to the latest version of V1 of the SDK, and coming up with a migration plan to V3. End of life means that even bug fixes are no longer considered for V1.

**Comment by Gusarov2k** [comment]
It's old project ((

**Comment by awood45** [comment]
Best path forward is to upgrade. First to try and upgrade your V1 SDK version, then to V2/V3. https://github.com/aws/aws-sdk-ruby/blob/master/MIGRATING.md

**Comment by Gusarov2k** [comment]
Thank you so much for your great work! I will try to update.
Tell me please this question if I download the database from the production server and install it on the local machine, will my application work or will it still produce an aws error?

**Comment by awood45** [comment]
I don't think that is related, if the code is triggered that creates a client and you don't have credentials in place, you'll receive that error.

**Comment by awood45** [comment]
Closing this, I think the question has been answered. Feel free to update with any questions you have.
