### ISSUE TITLE
s3_client.get_bucket_acl doesn't follow 301 redirect

### ISSUE THREAD

**Issue by vbichov** [aws/aws-sdk-ruby#1725]
### Issue description

when trying the following:
bucket location: "us-west-1"

    s3 = Aws::S3::Client.new ({:region => "us-east-1"})
    s3.get_bucket_acl ({:bucket => "some-bucket-name"})

you will get Aws::S3::Errors::PermanentRedirect exception

the exception will contain the correct region.

python api follows that redirect and retrieves the acl

**Comment by vbichov** [comment]
boilerplate workaround:
def getBucketACL(bucketName)
  begin
    return @s3.get_bucket_acl ( {:bucket => bucketName})
  rescue Aws::S3::Errors::PermanentRedirect => e
    Aws.config.update ({region: e.context.http_response.headers['x-amz-bucket-region']})
    @s3 = Aws::S3::Client.new
    return getBucketACL(bucketName)
    
  end
end

**Comment by cjyclaire** [comment]
@vbichov Interestingly, I cannot reproduce this. I tried the script and it worked for me.
Some quick questions, is `some-bucket-name` in the `us-east-1` region for you? Did you provide `region` from other places? like Aws.Config, `AWS_REGION` parameters? For credentials, are you using `/.aws/credentials` file or `/.aws/config` file?

**Comment by awood45** [comment]
Which version of the SDK are you using, also?

**Comment by vbichov** [comment]
aws-sdk-s3 (1.8.2)

Out of 143 buckets I'm getting this error only on 2.

Those 1 is located in us-west-1 and the other is in us-east-1

credentials are passed as a hash.

I will try to understand what's different in those buckets

**Comment by cjyclaire** [comment]
@vbichov Does this still happening for you? SDK does support fetching region from `'x-amz-bucket-region'` [here](https://github.com/aws/aws-sdk-ruby/blob/9ea447b7e9e57e27bb7924aca40a5bf0c3265a94/gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/s3_signer.rb#L124).

I also tried with a client in `us-east-1` and fetching `us-west-1` bucket, it succeed without an issue for me, also, it sounds weird when you mentioned a `us-east-1` client failed to fetch `us-east-1` bucket with this error. Could you provide more debugging info by setting `http_wire_trace` to true for the client? This would provide the wire trace, then you can identify which endpoint/region it's trying to hitting and whether SDK is functioning properly.

**Comment by cjyclaire** [comment]
Happy to hear that you have worked around the issue! closing.
Feel free to reopen if it happens again or with further questions : )

**Comment by dvogel** [comment]
I believe I'm experiencing the same issue. I have a handful of buckets that were created in us-east-1. It shows as much in the AWS web console. The SDK returns an empty location constraint for these buckets. Attempting to get the tags or ACL yields the same permanent redirect exception, which includes the correct region in the response header. This repro script:

```
require 'aws-sdk-s3'

bucket_name = ARGV.first
client = Aws::S3::Client.new(region: 'us-west-2')
puts client.get_bucket_location(bucket: bucket_name)

begin
  puts client.get_bucket_tagging(bucket: bucket_name)
rescue Aws::S3::Errors::PermanentRedirect => ex
  expected_region = ex.context.http_response.headers['x-amz-bucket-region']
  puts "Expected request to region: #{expected_region}"
end
```

Outputs:
```
{:location_constraint=>""}
Expected request to region: us-east-1
```

This is using aws-sdk-core 3.115.0 and aws-sdk-s3 1.96.1.

Is the empty location constrain perhaps meaningful in a way I'm just failing to find in the docs?

**Comment by dvogel** [comment]
> Buckets in Region us-east-1 have a LocationConstraint of null. 

I found that guidance [in the service docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html).
