### ISSUE TITLE
Aws::S3::Errors::RequestTimeTooSkewed

### ISSUE THREAD

**Issue by abarrak** [aws/aws-sdk-ruby#1727]
### Issue description

```
Aws::S3::Errors::RequestTimeTooSkewed: 
The difference between the request time and the current time is too large.
```

Encounter this error -sometimes- while working in development and testing.
The uploaded files are small _(< 1 MB)_.

I tried setting the timezone to Ireland `Dublin` to match my bucket zone `eu-west-1` but it didn't work.

I found some helpful configuration that can[be set in other SDKs ([.NET](https://aws.amazon.com/blogs/developer/clock-skew-correction/), [JS)](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html):

- `correctClockSkew`
- `systemClockOffset`

I didn't found them in ruby aws sdk or the repository.
Trying to set them in `AWS.config` raises not known configuration exception.

### Gem name and its version

gem 'aws-sdk', and version: `2.10.125`

### Version of Ruby, OS environment

Ruby 2.4.1, Mac OS X 10.11.6

### Code snippets / steps to reproduce

Upload file to AWS S3 bucket in development environment. 
Happens for me in new Rails application with default time zone unchanged:

```ruby
Aws::S3::Resource.new(client: @client).bucket(@bucket_name)
obj = get_bucket.object("my object")
obj.put({ body: content, acl: 'public-read' })
obj.public_url
```

**Comment by juanignaciosl** [comment]
@abarrak how did you fix this? 😅

**Comment by abarrak** [comment]
My case was in the test context.
I was stubbing `Time` in other test cases without returning it back to `current`.

@juanignaciosl Ensure you're not using time stubbing helpers.

If you didn't encounter this tests, then:

- This is in most cases  a [system,](https://stackoverflow.com/questions/38295058/awss3errorsrequesttimetooskewed-the-difference-between-the-request-time-a) [clock,](https://www.allcloud.io/how-to-fix-amazon-s3-requesttimetooskewed/) [issue](https://stackoverflow.com/questions/25964491/aws-s3-upload-fails-requesttimetooskewed).
- Some SDKs have extra options to handle it (e.g: `correctClockSkew`), but not ruby unfortunately.
- Delayed Request in S3 queue that caused request time to increase.
