### ISSUE TITLE
Copy Launch Configuration

### ISSUE THREAD

**Issue by povils** [aws/aws-sdk-ruby#1729]
It would be nice to have LaunchConfiguration method which will copy current settings. This feature currently exists in AWS console.
Use case:
I want to update just AMI in Launch Configuration. Because there is no possibility to update Launch Configuration, it would be much easier just copy all settings and update just AMI.

Regards

**Comment by awood45** [comment]
Can you elaborate a little more on what you're trying to do?

Are these updates to `:user_data` values on an EC2 instance? Or are you referring to Launch Configurations for Auto Scaling?

**Comment by povils** [comment]
Sorry for the not complete question. Yes, I am referring to Auto Scaling :)

**Comment by awood45** [comment]
I see what you're getting at. I think you can actually get pretty close to this today. Consider this example:

```ruby
require 'aws-sdk-autoscaling'

client = Aws::AutoScaling::Client.new

copy_from_lc = Aws::AutoScaling::LaunchConfiguration.new(name: OLD_LC_NAME)
opts = copy_from_lc.data.to_h
opts[:launch_configuration_name] = "NewLaunchConfigName"
opts[:image_id] = "NewAMI"
opts.delete(:created_time) # Cleanup
opts.delete(:launch_configuration_arn) # Cleanup

client.create_launch_configuration(opts)
```

This should be pretty close to what you need - you may need to fill in a few extra values depending on the details, but give this a try and see if that gives you a useful head start to build around.

**Comment by povils** [comment]
Thank for response. Yes it's pretty much what I'm doing now. As I see aws-cli also doesnt have this feature, thus maybe it doesnt make sense to expect it in this SDK.

**Comment by cjyclaire** [comment]
Closing, free feel to reopen with further comments or questions : )
