### ISSUE TITLE
Aws::ACM::Client.describe_certificate response does not correspond to document

### ISSUE THREAD

**Issue by limitusus** [aws/aws-sdk-ruby#1737]
### Issue description

In `describe_certificate` response `validation_method` is `nil` when the actual validation method is email, whereas it's documented `"EMAIL"`.

From [SDK document](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ACM/Client.html#describe_certificate-instance_method)

```
resp.certificate.domain_validation_options[0].validation_method #=> String, one of "EMAIL", "DNS"
```

and it's correct for DNS-validated certificates, but it's incorrect for Email-validated ones.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-acm (1.3.0)

### Version of Ruby, OS environment

Ruby 2.4.2, AmazonLinux

### Code snippets / steps to reproduce

With email-validated certificate existence:

```ruby
cert_detail = acm.describe_certificate(certificate_arn: cert.certificate_arn)
cert_detail.certificate.domain_validation_options.each do |v_opts|
  puts "[#{v_opts.validation_status}] #{v_opts.domain_name} => #{v_opts.validation_method}"
end
```

Email-validated certificates prints empty on the right side of the arrows.

**Comment by awood45** [comment]
Can you show (feel free to redact sensitive information) the output of this call with wire tracing on?

```ruby
acm = Aws::ACM::Client.new(http_wire_trace: true)
cert_detail = acm.describe_certificate(certificate_arn: cert.certificate_arn)
cert_detail.certificate.domain_validation_options.each do |v_opts|
  puts "[#{v_opts.validation_status}] #{v_opts.domain_name} => #{v_opts.validation_method}"
end
```

It is most likely that this is a difference in what the service itself returns, but if I am wrong, wire tracing will reveal the issue.

**Comment by limitusus** [comment]
Forgot important info: the previous comment was for Email-validation certs. Wire trace log for DNS-validated ones include `ValidationMethod` in JSON response.
`\"ValidationMethod\":\"DNS\"`

**Comment by cjyclaire** [comment]
@limitusus From the wire log, there is no `ValidationMethod`, this means it's not provided from server response, thus it failed to be fetched from client side.

I've reached out to service team for whether this is an allowable behavior. For documentations, those documents all possible responses, it doesn't guarantee that all response fields would be available with values anytime.

Will update! : )

**Comment by limitusus** [comment]
I contacted AWS and they know this issue. We need to distinguish the validation method only by the key's existence...

**Comment by cjyclaire** [comment]
Closing as the question has been answered by AWS Support, I have reached out to service team to improve their documentation on this behavior.
