### ISSUE TITLE
CloudSearch API Definition is Missing ListTags Method

### ISSUE THREAD

**Issue by corbanmailloux** [aws/aws-sdk-ruby#1741]
### Issue description
[`aws-sdk-ruby` service API definitions for CloudSearch](https://github.com/aws/aws-sdk-ruby/blob/master/apis/cloudsearch/2013-01-01/api-2.json) are missing the `ListTags` API. According to the [AWS Developer Guide for CloudSearch](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/API_ListTags.html), this API exists in version `2013-01-01`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`aws-sdk-ruby` service API definitions

### Version of Ruby, OS environment
N/A

### Code snippets / steps to reproduce
1. Review [CloudSearch JSON Definitions](https://github.com/aws/aws-sdk-ruby/blob/master/apis/cloudsearch/2013-01-01/api-2.json) and note the missing block.
2. Note the method is also missing in the [`sdk-for-ruby` v3 docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudSearch/Client.html).
3. Attempt to call `::Aws::CloudSearch::Client.new(...).list_tags` and note the `NoMethodError`.

**Comment by cjyclaire** [comment]
Thanks for the report, since this API is missing from JSON models SDK consumed, it means it hasn't been released through SDKs and CLI yet. I'm reaching out to service team about this and update with their comments. Likely it might be released in the near future.

**Comment by corbanmailloux** [comment]
I'd like to follow up on why this was closed. Is there a different place I should report the issue for the API to be included in the SDKs?

**Comment by awood45** [comment]
I'd raise this with AWS Support or as feedback to the service teams. We consume the API definitions provided by services. We will also follow up on our end. It's only closed here because there's nothing we can do directly in the SDK (this issue would exist across SDKs and be resolved across them together).

**Comment by corbanmailloux** [comment]
Thanks for following up.
