### ISSUE TITLE
AWS::S3::Object#upload_file lengthy upload time if the file pointer is at the end of file

### ISSUE THREAD

**Issue by sergio-bobillier** [aws/aws-sdk-ruby#1747]
### Issue description

This issue occurs when `AWS::S3::Object#upload_file` is called with a `File` or `Tempfile` as a parameter and the pointer on the file is at the end of file. The file is successfully uploaded to S3 but the time it takes to upload the file is absurdly large (around 1 minute). for a file less than 1 KB in length. 

To be totally honest with you I'm not sure if this can be considered a bug or is just a product of the way the upload method is implemented. I just wanted to show it to you so that you are aware of it. Please take a look at the **Code snippets / steps to reproduce** section for an example.

In my use case the application is writing a report to a `Tempfile` and then trying to upload said `Tempfile` to an S3 bucket.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 (1.8.2)

### Version of Ruby, OS environment

Ruby 2.5.0
Tested on Mac OSX and Linux (CentOS 7) with the same results.

### Code snippets / steps to reproduce

This is the code I used to test this:

```ruby
f = Tempfile.new('test-upload.txt')
f.write "Lorem ipsum dolor amet..."    # Text truncated, it was a 500 characters string,
s3_client = Aws::S3::Client.new(region: 'sa-east-1', credentials: Aws::Credentials.new('XXXXX', 'YYYYY'))
s3_resource = Aws::S3::Resource.new(client: s3_client)
object = s3_resource.bucket('bucket-name').object('test-upload.txt')
puts Benchmark.measure { object.upload_file(f) }
```

The output is:

```
0.011649   0.005037   0.016686 ( 48.284769)
```

Took 48 seconds to upload a file 500 bytes in length.

If I do a `aws s3 ls` in the terminal I can see that the file is on the bucket and has the right size:

```
$ aws s3 ls s3://bucket-name/
2018-04-03 08:37:08        500 test-upload.txt
```

This doesn't happens if I seek the file to 0 (move the pointer to the beginning of the file) and then do the upload, like this:

```
f.seek(0)
puts Benchmark.measure { object.upload_file(f) }
```

The output in this case:

```
0.004101   0.001167   0.005268 (  4.531165)
```

Only 4 seconds.

I get a similar result when I pass the file path instead but that is because in that case the AWS SDK gem is re-opening the file with a new File object and in that object the pointer is, of course, at the beginning of the file:

```
puts Benchmark.measure { object.upload_file(f.path) }
```

Output:

```
0.004597   0.001238   0.005835 (  3.648069)
```

**Comment by cjyclaire** [comment]
Sorry for the delays, first of all, I can reproduce the scenario with your code snippet, the code line we take in a file/tempfile is [here](https://github.com/aws/aws-sdk-ruby/blob/44b231aae58be29f75b6ee47090b781658a2c9e8/gems/aws-sdk-s3/lib/aws-sdk-s3/file_uploader.rb#L52), nothing special.  

I think this has to do with the fact that you created a Tempfile, wrote contents but didn't to close the file. Thus that data from write still lived in the buffer not flushed in, so when SDK call `read` on the file, it actually returns nothing. Then first request attempt will failed with error message like `Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`. 

SDK has build-in default retry for 3 times, at [`retry_request`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L167), you will see that we rewind request body before resend the request. Thus, the second request succeed this time.

You can see what I described by setting `http_wire_trace` to true at the client, then wire log will be visible. In summary, the long hanging time is for the failed first request attempt, not SDK serializing delays.

Closing, feel free to re-open with further concerns or questions :D
