### ISSUE TITLE
Add support for credential_process

### ISSUE THREAD

**Issue by jnewbigin** [aws/aws-sdk-ruby#1749]
Please fill out the sections below to help us address your issue

### Issue description
Since botocore 1.8.0 there is an option to obtain credentials from a helper process
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes
It would be great to use that for ruby too

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
"aws-sdk-resources", "~> 2.0"

### Version of Ruby, OS environment
Any

### Code snippets / steps to reproduce
```[bash]
$ cat ~/.aws/config 
[default]
region = ap-southeast-2
credential_process = ./get_aws_credentials.sh
```
```[bash]
$ aws sts get-caller-identity
{
... success...
}
```
```[bash]
$ ruby tool.rb
ERROR: No AWS credentials provided

```

**Comment by jnewbigin** [comment]
```
  rescue Aws::Errors::MissingCredentialsError
    signal_error "no credentials provided"
```

**Comment by awood45** [comment]
This feature request is being tracked elsewhere. Counting this as a +1 for that support.

**Comment by Cinderhaze** [comment]
Where is this being tracked, is there anywhere that we can +1 it?

**Comment by mullermp** [comment]
It was originally added to a `FEATURE_REQUESTS.md` file which I eventually removed (and re-opened relevant issues) for tracking. I believe this feature is actually already implemented ([changelog](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md#3680-2019-09-16)).

```
# ~/.aws/config
credential_process = echo '{ "Version": 1, "AccessKeyId": "AK_PROC1", "SecretAccessKey": "SECRET_AK_PROC1", "SessionToken": "TOKEN_PROC1" }'

# code
Aws> s3.config.credentials.credentials
=> #<Aws::Credentials access_key_id="AK_PROC1">
```
