### ISSUE TITLE
Aws::S3::Resource.new crashes app 

### ISSUE THREAD

**Issue by nunofmendes** [aws/aws-sdk-ruby#1755]
Please fill out the sections below to help us address your issue

### Issue description
Everything was working and today we detected that it worked no more with no code change gem update.
AWS S3 Resource stopped working. Crashes app when initialises.
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-3
### Version of Ruby, OS environment
Ruby 2.4.2p198 / OS X High Sierra but this also happens on Heroku
### Code snippets / steps to reproduce
Whenever I call "Aws::S3::Resource.new" the app crashes:

**-- Trace ---**
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-5.2.0/lib/action_view/helpers/controller_helper.rb:27:in `logger' (this line is repeated multiple times)
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/logging.rb:26:in `block in <class:Logging>'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:70:in `call'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:57:in `each'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:57:in `each'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:200:in `value_at'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:189:in `block in resolve'
/.rbenv/versions/2.4.2/lib/ruby/2.4.0/set.rb:324:in `each_key'
/.rbenv/versions/2.4.2/lib/ruby/2.4.0/set.rb:324:in `each'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:189:in `resolve'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/configuration.rb:150:in `build!'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/base.rb:62:in `build_config'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/base.rb:19:in `initialize'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/client.rb:197:in `initialize'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/base.rb:99:in `new'
/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/resource.rb:14:in `initialize'

I've initialised AWS through the following. code:

```
Aws.config.update({
      credentials: Aws::Credentials.new('XXXXXXX', 'XXXXXXX')
    })
```

And call the the S3 new resource the following way:

`s3 = Aws::S3::Resource.new(region: "XXXXX")  <--- Crashes`

Has the update change any procedure or code that I am not aware of? 

I've rechecked the docs and everything seems ok with my code. I've move region to the config, but same problem occurs. I've injected the tokens directly in new but same problem occurs.

Thank you

**Comment by cjyclaire** [comment]
Hmmm, so first I cannot reproduce this at my Mac environment, and I tried few s3 resource usage they both work fine. Since no code update, there is no way that newly release code might break your app. The resource object won't make http calls until fetching attributes associations etc. So crash at initialization step is irrelevant to server side.

From the error trace, it failed at actionview `controller_helper` originally, could you check those third-party dependencies? Also, is the issue still reproducible if you use `aws-sdk-s3` gem solo?

**Comment by nunofmendes** [comment]
@cjyclaire  Thank you for your reply.

So, If I run in a separated ruby file everything checkouts ok
If I call the function with that code as HTTP POST everything checkouts ok
If I call the function (which is a task in the scheduler) with rake, it gives that crash.

**Comment by nunofmendes** [comment]
Ok. Fixed. Was related with double call requiring ActionView.
