### ISSUE TITLE
Impossible to configure port with aws-sdk-ses

### ISSUE THREAD

**Issue by rpbaptist** [aws/aws-sdk-ruby#1767]
### Issue description

Our application is being throttled by AWS. [As described here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/limits.html) I would like to change the port to 587 or 2587.

This is not possible to configure the port using the `aws-sdk-ses` gem. [Aws::SES::Client.new](http://docs.aws.amazon.com/sdkforruby/api/Aws/SES/Client.html#initialize-instance_method) does not take a `port` option.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-ses`

### Version of Ruby, OS environment

Ruby:`2.5.1`
OS: `Linux 4.4.0-1044-aws #53-Ubuntu`

### Code snippets / steps to reproduce

See above.

**Comment by cjyclaire** [comment]
@rpbaptist You can provide `:endpoint` parameter with port number, and that port number will be used for making request. e.g. `Aws::SES::Client.new(endpoint: 'https://email.us-west-2.amazonaws.com:1234')`

**Comment by rpbaptist** [comment]
Alright, thanks very much!
