### ISSUE TITLE
ObjectVersion could benefit from convenience methods like download_file

### ISSUE THREAD

**Issue by patrickvinograd** [aws/aws-sdk-ruby#1770]
Please fill out the sections below to help us address your issue

### Issue description
`Aws::S3::Object` has a convenience method `download_file` to retrieve the object contents to a given path. It would be handy to have the same for `ObjectVersion` as well, to retrieve a prior version of an object while taking advantage of the sequential/parallel download capability that the download_file method provides.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3

### Version of Ruby, OS environment
n/a

### Code snippets / steps to reproduce
n/a

**Comment by cjyclaire** [comment]
Thanks for the feedback and sorry for the delays!
PR #1812 addressing this feature request is opened and under review

**Comment by cjyclaire** [comment]
The PR has been merged, will be include in the next release :D (likely `aws-sdk-s3, v1.16.0`) closing
