### ISSUE TITLE
Can not specify protocol as names when calling create_network_acl_entry()

### ISSUE THREAD

**Issue by daveseff** [aws/aws-sdk-ruby#1771]
Please fill out the sections below to help us address your issue

### Issue description
The documentation for create_network_acl_entry() indicates that I can use the protocol names ( i.e. 'tcp', 'udp', 'icmp' as opposed to '6', '17', and '1'). Trying this throws the error:
`Invalid value 'tcp' for IP protocol. Unknown protocol.`
    
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk version 3.0.1

### Version of Ruby, OS environment
ruby 2.0 on Redhat Linux

### Code snippets / steps to reproduce
n/a

**Comment by cjyclaire** [comment]
Soft updates, for 'tcp', it should be number string '6' instead, service team is working on updating documentation.

**Comment by cjyclaire** [comment]
EC2 Doc team is actively working on fixing the confusion there and new contents will be pushed soon : )

Resolving since there is nothing more we can do here, once their doc is updated, SDK will auto pickup those changes : ) Feel free to reopen/ let me know if you see no updates for a while
