### ISSUE TITLE
not able to revoke_ingress with AWS Ruby sdk V3 Ec2

### ISSUE THREAD

**Issue by equivalent** [aws/aws-sdk-ruby#1772]
Given AWS user access token has Full Ec2 permission
And my application uses `aws-sdk-ec2 (1.30.0)` and `aws-sdk-core (3.20.2)`
And my security group `sg-12345678` has firewall rule on port `22` for `127.0.0.1/32`
When:

```
    def security_group_id
        'sg-12345678'
    end

    def security_group
      Aws::EC2::SecurityGroup.new(security_group_id, client)
    end

    def client
      @client ||= Aws::EC2::Client.new(
        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        region: 'eu-west-1')
    end

client.revoke_security_group_ingress({
        cidr_ip: '127.0.0.1/32',
        group_id: security_group_id,
        ip_protocol: '-1'
      }) # not worknig, returning Aws::Empty

```
Or:
```
      security_group.revoke_ingress(
       cidr_ip: '127.0.0.1/32',
        from_port: 0,
        to_port: 60000,
        ip_protocol: 'tcp')
```

Or:
```
      security_group.revoke_ingress(
       cidr_ip: '127.0.0.1/32',
        from_port: 22,
        to_port: 22,
        ip_protocol: 'tcp')
```

Or

```ruby
      options = {
        ip_permissions: [
          {
            ip_ranges: [{cidr_ip: '127.0.0.1/32'}],
            from_port: 22,
            to_port: 443,
            ip_protocol: 'tcp'
          }
        ]
      }
      security_group.revoke_ingress(options)
```

Then I receive AWS::Empty response with no error
But the rule was not removed from security group

I tried it with multiple IPs and different port rules. I'm able to add rules with `authorize_ingress` but not remove rules

**Comment by equivalent** [comment]
Ruby 2.5.0

**Comment by cjyclaire** [comment]
@equivalent For using the first snippet, I couldn't reproduce the issue. I was able to authorize and revoke ingress rule successfully for a security group (though the response is empty). 

Could you provide a wire log for the request that failed to remove the rules? Make sure double check not to include sensitive informations : ) And I'll pass that to service team to take a look the request. Also, if you have an AWS support account, feel free to contact them directly, it would open a direct conversation with service team : )

**Comment by equivalent** [comment]
Thank you for response

:thinking: 

Interesting, I've refactor all my code from:

```ruby
sg_client = Aws::EC2::SecurityGroup.new(security_group_id, client)....)
sg_client.re voke_ingress(...)
```
to just

```ruby 
ec2_client =  Aws::EC2::Client.new(region: '.....', credentials: credentials)
ec2_client.revoke_security_group_ingress(....)
```

and everything works now

> plus instead `group_id` (`sg-xxxxxx`) I now usepoh  `group_name` 

and everything works now. Don't know why. It seems there is some WooDoo magic goving on with ` Aws::EC2::SecurityGroup` instances 

> I didn't change any permissions around those credential tokens at all just refactor the code

Works form me, I hope it will help some googling devs
