### ISSUE TITLE
Support additional FIPS endpoints

### ISSUE THREAD

**Issue by Zlender** [aws/aws-sdk-ruby#1777]
Please fill out the sections below to help us address your issue

### Issue description
Looking at gems/aws-partitions/partitions.json I can see that some FIPS endpoints are supported but in a very limited fashion. https://aws.amazon.com/compliance/fips/ now lists numerous additional services that have FIPS endpoints that we would have to manually specify endpoint for if we want to use them. It would be great to have all of these support and documented how to use them in SDK without manually specifying endpoints for different services.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk

**Comment by awood45** [comment]
I'll pass this on to the owners of the endpoint file. Are you finding that, for regions we currently support in the `aws-partitions` gem, that the experience works well? (To help me scope the request)

**Comment by awood45** [comment]
This is actively being tracked and worked on.
