### ISSUE TITLE
Aws::STS::Errors::Http500Error: ruby aws-sdk

### ISSUE THREAD

**Issue by msuzoagu** [aws/aws-sdk-ruby#1780]
Please fill out the sections below to help us address your issue

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

- aws-sdk

### Version of Ruby, OS environment 

- ruby 2.5.1p57
- macOS High Sierra (10.13.4) 

### Code snippets / steps to reproduce 

Basically following [this tutorial](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Ruby.html) while running  DynamoDB on local computer (therefore no need for credentials). 

- error `Aws::STS::Errors::Http500Error` occurs while attempting to run `ruby MoviesCreateTable.rb`, which is supposed to create `Movies` table locally

- error occurs when attempting to initialize the client on line 9 - `dynamodb = Aws::DynamoDB::Client.new` , producing this 

``` 
from /Users/mine/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-
3.20.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
```  

- [Gist w/Complete Error Output](https://gist.github.com/msuzoagu/6e0302a4e60077f7583031f02cf5b0b9)

**Comment by msuzoagu** [comment]
So credentials are needed for this tutorial. I am closing this issue but think that docs need to be updated.

**Comment by Doug-AWS** [comment]
We already have instructions on creating credentials. Under Tutorial Prerequisites:

Set up an AWS access key to use the AWS SDKs. For more information, see Setting Up DynamoDB (Web Service).
