### ISSUE TITLE
No error message for malformed policy statement in KMS create_key

### ISSUE THREAD

**Issue by beaglebets** [aws/aws-sdk-ruby#1784]
I'm using 'aws-sdk' v3 on ruby 2.4. When trying to create a KMS key, if the policy statement malformed an empty string is returned as the error message. It would be really helpful if you could improve the messaging here. The error object has a stack trace, but nothing pointing towards the policy portion of the statement being the incorrect aspect. To recreate simply, send a string such as "not a real policy statement". I think this is worth improving, since my initial assumption while developing was that the policy portion would accept the string Id of an existing policy, rather than requiring the full policy json each time.

**Comment by awood45** [comment]
Happy to pass this feedback on to the service team. You can also pass this feedback on to the service team via [AWS Feedback channels](https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/).

Unfortunately, there isn't a way for the SDK itself to get this extra information from the error type of `Aws::KMS::Errors::MalformedPolicyDocumentException` received from the service. If a message is added, it will be included automatically.
