### ISSUE TITLE
S3 SDK: Failed to Open TCP Connection Errors due to Invalid URIs

### ISSUE THREAD

**Issue by aryeh-looker** [aws/aws-sdk-ruby#1785]
### Issue description

The S3 SDK occasionally produces invalid URIs where gibberish (possibly from the key name or possibly from the key from a different call) is being provided in lieu of the region in the URI. For example:

```
Seahorse::Client::NetworkingError : Failed to open TCP connection to my-bucket.s3.invalid-gibberish.amazonaws.com:443 (initialize: name or service not known) 
```

### Gem name

From our `Gemfile.lock`:

```
    aws-sdk-core (3.11.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-kms (1.3.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.8.0)
      aws-sdk-core (~> 3)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
```

### Version of Ruby, OS environment

`jruby-9.1.13.0` on Ubuntu 14 with Java 8

### Code snippets / steps to reproduce

We do not have a reproducible case. This shows up occasionally after several days of making various calls throughout the day and goes away when we restart the process. 

It is possible to reproduce something similar by providing an invalid region. For example (same result with a valid access key/secret/bucket):

```
jruby-9.1.13.0 :027 > s3 = Aws::S3::Client.new({access_key_id: 'doesnt', secret_access_key: 'matter', region: 's3HUzzahLALALA'})
 => #<Aws::S3::Client> 
jruby-9.1.13.0 :028 > s3.create_multipart_upload({bucket: "aryeh-is-cool", key: 'a/b/c/d/e/f/g'}).upload_id
Seahorse::Client::NetworkingError: Failed to open TCP connection to aryeh-is-cool.s3.s3HUzzahLALALA.amazonaws.com:443 (initialize: name or service not known)
```

Because of this, we always log the parameters that we are passing to `Aws::S3::Client.new` to ensure that we are providing a valid region — and we see invalid URIs being produced in production even when we are providing valid regions.

**Comment by awood45** [comment]
To help me track down an initial suspicion, does your application use threads heavily?

**Comment by aryeh-looker** [comment]
@awood45 — to some degree, yes. There are maybe 3-5 different threads that could be using the S3 library at any given time. Occasionally, more than one thread might be using the library at the same time.

**Comment by awood45** [comment]
As a possible workaround, you could consider throwing a Mutex around that call. I'm not aware of a concurrency issue _per se_ that would manifest in this manner, but it smells like I might find one.

See if that workaround helps you, we'll investigate in the meantime.

**Comment by awood45** [comment]
So far I've been unable to reproduce this. For some additional information, is this tied to any particular API call, or many different APIs?

How do you initialize and maintain threads in your application?

**Comment by awood45** [comment]
Any updates on the workaround or on my other questions?

**Comment by aryeh-looker** [comment]
@awood45 apologies for the long reply. It is in fact hard to reproduce.

> For some additional information, is this tied to any particular API call, or many different APIs?

We use two API calls, both which put files. Our code roughly looks like:

```
s3 = Aws::S3::Client.new(...)

# We either do this
s3.create_multipart_upload(...).upload_id
s3.upload_part(...)
s3.complete_multipart_upload(upload_id: upload_id, ...)

# Or we do this
s3.put_object(...)
```

> How do you initialize and maintain threads in your application?

There are a several threads that are dedicated to doing work around sending data _out_ of our application. They might do S3 work, SFTP work, HTTPS, etc. These threads are re-used.

As an aside, I noticed that in the Java library that while the `S3Client` is marked thread-safe (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html), the `S3ClientBuilder` is not considered to be thread-safe (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3ClientBuilder.html#defaultClient--). I doubt that documentation applies here, but I'm not sure. 

Also, we don't ever retain S3 client objects between calls to S3. We always create a new S3 client before making calls to S3. We could cache these objects, but we don't because the bucket names and regions can differ between calls. Said differently, we don't just have one S3 credential/bucket/region combo that we re-use every time.
