### ISSUE TITLE
undefined method `describe_launch_templates'

### ISSUE THREAD

**Issue by vincentdasari** [aws/aws-sdk-ruby#1796]
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
Using ruby aws-sdk v2

### Version of Ruby, OS environment
ruby 2.4.0p0 on MAC OSX

### Code snippets / steps to reproduce
require 'aws-sdk'

ec2_client = Aws::EC2::Client.new({region: aws_region})
ec2_client.describe_launch_templates

**Comment by awood45** [comment]
What version of the SDK are you using? It works for me using V2 of the SDK. If you're using a version older than `2.10.91`, that API wouldn't exist yet and you should upgrade.

**Comment by vincentdasari** [comment]
Yep. I'm on 2.9.5. I just updated to 3.0.1 and that seems to have done the trick. Thank you!
