### ISSUE TITLE
ec2.describe_instance_status sometimes returns nil

### ISSUE THREAD

**Issue by Ryuujinx** [aws/aws-sdk-ruby#1797]
Occasionally the describe_instance_status will return nil. It seems to occur if called shortly after starting a new instance. I was able to work around this by catching the NoMethodError produced by trying to access nil[], but not having to do this would be a better solution. 

Environment:
aws-sdk (3.0.1)
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux-gnu]
Amazon Linux AMI release 2017.09

The code in question simply looks to see that the status is 'ok', as shown here:

`if ec2.describe_instance_status({instance_ids: [extra_instance_id]})['instance_statuses'][0]['instance_status']['status'] == 'ok'`

I found #1449 when trying to research this, but that has to do with deletion and not creation so I'm not sure they're related.

**Comment by cjyclaire** [comment]
You might be interested in [`EC2 waiters`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#wait_until-instance_method), there is `instance_status_ok` available.

Basically, waiters are helping you polling until reach a target state, and polling behavior is configurable.
related [Blog Post](https://aws.amazon.com/blogs/developer/waiters/)
