### ISSUE TITLE
Unable to request persistent spot instance

### ISSUE THREAD

**Issue by duncaan** [aws/aws-sdk-ruby#1798]
### Issue description
I'm attempting to request a spot instance with the persistent type and I'm getting an error stating that the API cannot process my request because the InstanceInterruptionBehavior is not supported with this type of spot.  I believe that the requstType is being set somewhere by default, but this spot type does not seem to even like the value being present.  Per the documentation per the docs https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/SpotMarketOptions.html, we're omitting the termination behavior, but it's defaulting to terminate no matter what we do.
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-2.11.50
### Version of Ruby, OS environment
ruby 2.5.1p57
### Code snippets / steps to reproduce
Aws::EC2::Errors::InvalidParameterCombination: The terminate InstanceInterruptionBehavior is not supported when requestType is set to persistent.

**Comment by awood45** [comment]
There isn't anything I know of which sets this without your knowledge. Can you run this with `http_wire_trace: true` set on your client, and paste the output from that? Feel free to redact anything sensitive.

**Comment by duncaan** [comment]
Sure - here's my output:
```
<- "POST / HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.11.50 ruby/2.5.1 x86_64-darwin15\r\nX-Amz-Date: 20180608T205641Z\r\nHost: ec2.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: blah\r\nAuthorization: AWS4-HMAC-SHA256 Credential=blah/20180608/us-east-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=blah\r\nContent-Length: 63\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Content-Type: text/xml;charset=UTF-8\r\n"
-> "Content-Length: 1229\r\n"
-> "Date: Fri, 08 Jun 2018 20:56:40 GMT\r\n"
-> "Server: AmazonEC2\r\n"
-> "\r\n"
reading 1229 bytes...
-> ""
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DescribeImagesResponse xmlns=\"http://ec2.amazonaws.com/doc/2016-11-15/\">\n    <requestId>867f9668-a70b-420a-99c8-73fba8a520b0</requestId>\n    <imagesSet>\n        <item>\n            <imageId>ami-c5cf55ba</imageId>\n            <imageLocation>ubuntu-images-us-east-1-release/xenial/20180522/hvm/instance-store/image.img.manifest.xml</imageLocation>\n            <imageState>available</imageState>\n            <imageOwnerId>099720109477</imageOwnerId>\n            <creationDate>2018-05-22T19:53:03.000Z</creationDate>\n            <isPublic>true</isPublic>\n            <architecture>x86_64</architecture>\n            <imageType>machine</imageType>\n            <sriovNetSupport>simple</sriovNetSupport>\n            <name>ubuntu/images/hvm-instance/ubuntu-xenial-16.04-amd64-server-20180522</name>\n            <description>Canonical, Ubuntu, 16.04 LTS, amd64 xenial image build on 2018-05-22</description>\n            <rootDeviceType>instance-store</rootDeviceType>\n            <blockDeviceMapping/>\n            <virtualizationType>hvm</virtualizationType>\n            <hypervisor>xen</hypervisor>\n            <enaSupport>true</enaSupport>\n        </item>\n    </imagesSet>\n</DescribeImagesResponse>"

<- "POST / HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.11.50 ruby/2.5.1 x86_64-darwin15\r\nX-Amz-Date: 20180608T205642Z\r\nHost: ec2.us-east-1.amazonaws.com\r\nX-Amz-Content-Sha256: blah\r\nAuthorization: AWS4-HMAC-SHA256 Credential=blah/20180608/us-east-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=blah\r\nContent-Length: 1497\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Date: Fri, 08 Jun 2018 20:56:43 GMT\r\n"
-> "Connection: close\r\n"
-> "Server: AmazonEC2\r\n"
-> "\r\n"
-> "134\r\n"
reading 308 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The terminate InstanceInterruptionBehavior is not supported when requestType is set to persistent.</Message></Error></Errors><RequestID>d596d9e9-6d3a-4fbf-a292-b7773d0a2897</RequestID></Response>"
read 308 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn close

```

**Comment by awood45** [comment]
What is the structure of your call that generates this?

**Comment by duncaan** [comment]
The spot data structure should look something like this, very simple:
```{
  max_price: ".50",
  spot_instance_type: "persistent"
}```

**Comment by awood45** [comment]
Can you give me an example of a reproducing API call? I'm trying to compare what was sent over the wire to the client params you set.

**Comment by duncaan** [comment]
Here is what we're sending to this method: https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#run_instances-instance_method
```
{:min_count=>1, :max_count=>1, :key_name=>"key_name", :instance_type=>"c3.large", :placement=>{:availability_zone=>"us-east-1d"}, :security_groups=>["default", "sg"], :image_id=>"ami-c5cf55ba", :user_data=>"some_user_data", :tag_specifications=>[{:resource_type=>"instance", :tags=>[{:key=>"LaunchedBy", :value=>"me"}, {:key=>"EnvironmentName", :value=>"env"}, {:key=>"Role", :value=>"role"}]}], :instance_market_options=>{:market_type=>"spot", :spot_options=>{:max_price=>"0.35", :spot_instance_type=>"persistent"}}}
```

**Comment by awood45** [comment]
I'm able to recreate the error, but the SDK itself isn't inserting anything you didn't specify. There's probably something different you need to do in your request, but I can see that it isn't immediately obvious. I'd recommend reaching out to AWS Support to get EC2's take on this.

**Comment by awood45** [comment]
With that said, I was able to get this working by explicitly setting the instance interruption behavior value explicitly, so I'd recommend that you go with that approach. My guess is (and it's only a guess) the implied default behavior is "terminate", and setting an explicit value is conditionally required when you're setting a persistent spot instance type. I'll flag down @Doug-AWS to encourage the EC2 team to improve their documentation around this, but my recommendation moving forward is that you explicitly set your termination behavior setting.

**Comment by duncaan** [comment]
I have attempted to set the termination attribute, this works with the 'one-time' attribute, but with the 'persistent' attribute, the request is still not functioning.  Here's my request and output from the API:
```
{:min_count=>1, :max_count=>1, :key_name=>"key", :instance_type=>"c3.large", :placement=>{:availability_zone=>"us-east-1d"}, :security_groups=>["default", "sg"], :image_id=>"ami-c5cf55ba", :user_data=>"user_data", :tag_specifications=>[{:resource_type=>"instance", :tags=>[{:key=>"LaunchedBy", :value=>"me"}, {:key=>"EnvironmentName", :value=>"env"}, {:key=>"Role", :value=>"some_role"}]}], :instance_market_options=>{:market_type=>"spot", :spot_options=>{:max_price=>"0.35", :spot_instance_type=>"persistent", :instance_interruption_behavior=>"terminate"}}}

ERROR: Aws::EC2::Errors::InvalidParameterCombination: The terminate InstanceInterruptionBehavior is not supported when requestType is set to persistent.
```

**Comment by awood45** [comment]
You'd have to set it to something other than terminate. As I understand it, the point of a "persistent" spot instance is to use behavior other than termination when the spot instance is dropped. [Announcement post.](https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-ec2-spot-can-now-stop-and-start-your-spot-instances/)

What you seem to need to do is choose whether you want the instance to `stop` or `hibernate`, and to make sure your instance's storage solution is compatible.

**Comment by duncaan** [comment]
The post you are referring to EBS-backed instances.  If we provision an instance-store type, there is no option that works appropriately.  I've opened a support case to address this issue.

**Comment by awood45** [comment]
I see - I think the support case is probably the best path forward then. From an SDK point of view, we're faithfully marshaling your request and parsing the service response.
