### ISSUE TITLE
Cannot pass nil value to `location_constraint` despite stated fallback

### ISSUE THREAD

**Issue by cjtafoya** [aws/aws-sdk-ruby#1799]
Please fill out the sections below to help us address your issue

### Issue description
When calling `create_bucket` on a valid `Client` instance with a nil value for location_constraint (which should default to 'us-standard' per docs, receive the following error. Works fine excluding this value. 

`Aws::S3::Errors::MalformedXML: The XML you provided was not well-formed or did not validate against our published schema`

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`aws-sdk`

### Version of Ruby, OS environment
All.

### Code snippets / steps to reproduce
`create_bucket_configuration: {
      location_constraint: nil,
}`

**Comment by awood45** [comment]
I think that if you provide the key, it's going to expect a valid location constraint.

Why not do this?

```ruby
s3_client.create_bucket(bucket: BUCKET)
```

Do you need to pass this configuration value at all?
