### ISSUE TITLE
cannot load such file -- aws-sdk-s3 (LoadError)

### ISSUE THREAD

**Issue by fabiohsl** [aws/aws-sdk-ruby#1800]
I am trying to use aws-sdk-s3 within my project. But I am getting the given error "cannot load such file -- aws-sdk-s3 (LoadError)"

I have tried a couple of gems and combination. Is there any current bug related to that?

**Comment by awood45** [comment]
You should install the `aws-sdk-s3` gem, or include the `aws-sdk-s3` gem in your Gemfile.

**Comment by delucas** [comment]
This is indeed the answer
