### ISSUE TITLE
invalid configuration option (upgrading from v2 --> v3)

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-ruby#1807]
Please fill out the sections below to help us address your issue

### Issue description
Hi there, it looks like this old autoloading issue is back: https://github.com/aws/aws-sdk-core-ruby/issues/153. Back then it was considered a regression and Trevor Rowe gave me a workaround which also works for the issue now.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`gem 'aws-sdk', '~> 3'`

I am seeing this issue after upgrading from v2 to v3.

### Version of Ruby, OS environment
`ruby 2.3.1p112`

### Code snippets / steps to reproduce
````
# aws.rb config file

if Rails.env.test? || Rails.env.development?
  Aws.config[:dynamodb] = {simple_attributes: false, endpoint: "http://localhost:8000"} #for dynamodblocal
  Aws.config[:s3] = {endpoint: "http://localhost:10001", force_path_style: true} #for fakes3
else
  Aws.config[:dynamodb] = {simple_attributes: false}
end

# workaround...
Aws::DynamoDB #force autoloading
Aws::S3 #force autoloading

**Comment by awood45** [comment]
There's something missing here to help me reproduce, because we don't have autoloading in V3 except at the per service level. Where are your `require` lines, and what are they?

**Comment by kalpitad** [comment]
Sure, this code is in a Rails app with a standard setup:

- myapp\Gemfile: `gem 'aws-sdk', '~> 3'`
- myapp\config\application.rb: `Bundler.require(*Rails.groups) #standard way to require all gems in the gemfile`
- myapp\config\initializers\aws.rb: contains the code above

Does this help?

**Comment by awood45** [comment]
Yes! I'd strongly recommend changing your dependencies to point to the specific gems you're using. For example, based off what you configured:

```ruby
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-dynamodb', '~> 1'
```

Or if you're using a data mapper library for DynamoDB like ActiveRecord:

```ruby
gem 'aws-sdk-s3', '~> 1'
gem 'aws-record', '~> 2' # DynamoDB gem included with this
```

With either of these approaches you're good to go. Otherwise, we autoload when the sub-gems are first referenced.

**Comment by cjyclaire** [comment]
Closing as suggestions are provided, feel free to reopen with further comments/issues : )
