### ISSUE TITLE
Unable to set the credentials

### ISSUE THREAD

**Issue by ilrock** [aws/aws-sdk-ruby#1810]
Please fill out the sections below to help us address your issue

### Issue description

Hey there guys. In a Rails 5.2 project (upgraded during development) I'm unable to set the credentials for my aws integration with rails credentials.

As per the guide I'm running the command

`EDITOR=vim bin/rails credentials:edit`

however, I get the following error:

```
gems/aws-sigv4-1.0.2/lib/aws-sigv4/signer.rb:517:in extract_credentials_provider': missing credentials, provide credentials with one of the following options: (Aws::Sigv4::Errors::MissingCredentialsError)
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider
```

Any idea?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 v. 1.15

### Version of Ruby, OS environment

Ruby 2.5.1/OSX 10.13.4

### Code snippets / steps to reproduce

N/A

**Comment by cjyclaire** [comment]
Have you tried any of the credential configuration at our [README](https://github.com/aws/aws-sdk-ruby#configuration)? If so, how did you provide credentials?

**Comment by ilrock** [comment]
Thanks for the answer @cjyclaire. I had the ENV vars set in my .env (used in the previous version of the gem). I've realized that the names of my variables were a tad different from what was expected. Sorry to have bothered.

Cheers!

**Comment by cjyclaire** [comment]
Happy to hear you figured it out : ) ! closing
