### ISSUE TITLE
require "aws-sdk" could be aggressively slow due to dependency traverse

### ISSUE THREAD

**Issue by sorah** [aws/aws-sdk-ruby#1811]
### Issue description

`require "aws-sdk"` could be aggressively slow due to Rubygem's dependency traverse on `require`.

The traverse could be slow when many gem dependencies are pending for resolution. My local machine takes 6 minutes at most to complete on the particular case.

The reason behind of the slowness becomes critical when an environment has installed many versions of SDK gems at the same time.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk`, `aws-sdk-resources`

### Version of Ruby, OS environment

`ruby 2.6.0dev (2018-06-28 trunk 63778) [x86_64-linux]`

Reproduces on 2.4, 2.5 and trunk. 
(The reason lives in Rubygems and reproduces on Rubygems 2.7.7 at least... I've confirmed repro on RubyGems bundled in Ruby 2.4 and 2.5 series)

### Code snippets / steps to reproduce

Real world case:

1. Run https://gist.github.com/sorah/dc2ea96f261ef42f0a6cae8bf68310bc (make sure to use correct `gem` command on your machine)
   - Key point is to have many versions of the `aws-*` service gem at the same time.
   - This gist is a snippet of `gem install` commands to install the same gems with my local environment which reproduces this issue.
2. Now `ruby -raws-sdk -e0` takes a few minutes to complete :coffee:

### Why is this happening?

A smaller case of the slowness happening above is the following:

``` ruby
# Activate the gem
gem 'aws-sdk-resources'
# There are a lot of gems pending for dependency resolution
p Gem::Specification.unresolved_deps.keys
# Trigger unresolved_deps traversal fallback
require 'json'
```

The dependencies of an activated gem remain in `unresolved_deps`. In this case, `aws-sdk-resources` has many dependencies [GH](https://github.com/aws/aws-sdk-ruby/blob/e5c7f50746344be61b166487f692303dd4f0a670/gems/aws-sdk-resources/aws-sdk-resources.gemspec).

And notice that  _the service gems which `resources` gem depends are not required_ at the timing of [`aws-sdk-resources.rb` load](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-resources/lib/aws-sdk-resources.rb#L3). The service gems are registered for autoloading.
This means `Gem::Specification.unresolved_deps` is kept to have all `aws-*` service gems for a while.

Rubygems version of `require` tries the several strategy to find the actual file. Some paths are slow, like this one:
https://github.com/rubygems/rubygems/blob/v2.7.7/lib/rubygems/core_ext/kernel_require.rb#L77-L88

This strategy tries to find a file from all `unresolved_deps` recursively. The targeted gems includes __all installed versions.__

Thus, the following gems are gonna have traversed and tried:

```
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["jmespath", "1.4.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-partitions", "1.94.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-partitions", "1.92.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-partitions", "1.91.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-partitions", "..."]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-sigv4", "1.0.2"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-sigv4", "1.0.1"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-sigv4", "..."]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-eventstream", "1.0.1"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.22.0"], ["aws-eventstream", "1.0.0"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.21.3"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "3.21.2"]]
[["aws-sdk-acm", "1.8.0"], ["aws-sdk-core", "..."]]
[["aws-sdk-acm", "1.7.0"], ["aws-sdk-core", "3.22.0"], ["jmespath", "1.4.0"]]
[["aws-sdk-acm", "..."], ...]
```

I'm tried to make this strategy fast, but looks like it's difficult. The alternate problem is `aws-sdk-resources` gem is letting many unresolved dependencies remain. So I've opened this issue.

### How to resolve

Activate the service gem before loading `aws-sdk-core` on `aws-sdk-resources.rb`. Calling `Kernel#gem` resolves the pending service gem dependencies and remove them from `unresolved_deps`.

``` ruby
gem "aws-sdk-s3"
gem "aws-sdk-ec2"
# (...snip...)

require 'aws-sdk-core'

module Aws
#...
```

I'm not familiar with `Kernel#gem` method, so I'm not sure this is safe. So I'm not opening a PR now.

### Does this situation really occur?

**Yes.** Unlike a server, developers don't isolate BUNDLE_PATH (`bundle install --path`) on their local machine for every project.

If the SDK versions vary on each project, a rubygem environment could have many versions of `aws-*` gems att the same time. At least, it's my case.

Since aws-sdk-ruby v3 series ships a new version often, so I'm guessing more people will see this issue soon, as people has many installations of the v3 series at the same time.

**Comment by awood45** [comment]
We'll take a look at this, but the recommended usage is to simply require the service gems you need directly. `aws-sdk-resources` and similar are provided as a migration convenience more than as a long term recommended path.

**Comment by awood45** [comment]
I would be open to mitigations to reduce this issue in `aws-sdk-resources`, it's not the intended behavior to cause load time pain. But I don't see how this one works, unfortunately.

**Comment by awood45** [comment]
I also could be missing something about what exactly `Kernel#gem` is doing, documentation around it for the use case you're describing is sparse, unfortunately.

**Comment by sorah** [comment]
> We'll take a look at this, but the recommended usage is to simply require the service gems you need directly.

I agree with this, but I was not sure this recommendation is correct.

We had several scripts remain that requires `aws-sdk` directly. After we notice this issue, we migrated such scripts to load the service gems directly.

But as you're saying, causing slow load pain with `require "aws-sdk"`  is not intentional behavior (I understand you're agreeing with this).

>That method does allow you to load a specific gem version, but it needs to be specified in code.

No. `Kernel#gem` is to _activate_ gems, and _optionally_ takes `requirements`. https://docs.ruby-lang.org/en/2.5.0/Kernel.html#method-i-gem
Version constraints are not required. 

The problem I've explained earlier is: Activating `aws-sdk` gem causes unresolved dependencies (`unresolved_deps`) to the service gems . But they remains unresolved because `aws-sdk-resources.rb` just registers service gems for autoloading.

Rubygems may try to find a file from `unresolved_deps` (with trying all possible gem version combinations) when requiring new files. `require "aws-sdk"` with this situation triggers that code path. (Actually, it happens when requiring standard libraries such as `cgi`, in inside of `aws-sdk-core.rb`)

The code path becomes slow when an environment has many `aws-*` gem versions.

The solution is to resolve gems in `unresolved_deps`. One is to `require` them (which activates a gem inside `require` method), and alternate one is to just activate them using `Kernel#gem` method.

-----

One more thing: As I explained `require "aws-sdk"` leds many `unresolved_deps` unresolved, any requiring standard libraries after `require "aws-sdk"` could be also slow.

```
$ irb -raws-sdk
(slow)
>> require 'cgi'
(slow!)
=> false
>> Gem::Specification.unresolved_deps
=> [... so many  aws-* gems ...]
```

**Comment by sorah** [comment]
I love writing `require "aws-sdk"` in my irbrc. That is one of my (small) use case.

**Comment by srchase** [comment]
Our suggested best practice is to utilize individual service gems in lieu using ```require "aws-sdk"```.

I'm going to close this issue now.  If there's additional information, we can revisit, but for now, we feel using individual service gems is the right approach for most users of the SDK.

**Comment by shibz** [comment]
Getting conflicting information.  You're suggesting here to use individual gems rather than "aws-sdk" however the official documentation seems to suggest the opposite:

https://aws.amazon.com/sdk-for-ruby/

```
Install the gem: 
gem install aws-sdk

or Add to Gemfile: 
gem 'aws-sdk', '~> 3'
```

**Comment by srchase** [comment]
@shibz 

See this migration page: [Migrating from Version 1 or 2 to Version 3 of the AWS SDK for Ruby](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/migrating-to-v3.html).

The top-level of the documentation gives the general use case and is the quickest way to get started with the SDK.  If you look at the developer guide, we offer documentation on more nuanced uses of the SDK, which include specifying specific versions, or using the gems independently if you are not utilizing all of the AWS services.

**Comment by awood45** [comment]
I think the feedback is well taken here that we should be putting the per-service gem caveat more prominently in front of the "get started" example there.

**Comment by awood45** [comment]
The README on this repo does have those warnings prominently, will queue up some work on the marketing page.
