### ISSUE TITLE
Aws::Route53::Client#change_resource_record_sets fails if passing instance of ChangeResourceRecordSetsRequest

### ISSUE THREAD

**Issue by AngelCantugr** [aws/aws-sdk-ruby#1813]
### Issue description
When calling Aws::Route53::Client#change_resource_record_sets passing an instance of Aws::Route53::Types::ChangeResourceRecordSetsRequest instead of a Hash, the following error is being thrown: `no member 'id' in struct`

The reason is that the line https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-route53/lib/aws-sdk-route53/plugins/id_fix.rb#L32 assumes that the method parameters are always going to be in a Hash.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk - 2.11.77
aws-sdk-route53 - 1.10.0 

### Version of Ruby, OS environment
Ruby 2.4
MacOS 10.13.5

### Code snippets / steps to reproduce
1. Initialize a client of Aws::Route53::Client
1. Call the instance method #change_resource_record_sets passing an instance of Aws::Route53::Types::ChangeResourceRecordSetsRequest instead of a Hash

**Comment by cjyclaire** [comment]
Thanks for the contribution, PR has been merged, will be out in the next release!
