### ISSUE TITLE
Region endpoint specs title doesn't follow implementation

### ISSUE THREAD

**Issue by chiting** [aws/aws-sdk-ruby#1816]
Please fill out the sections below to help us address your issue

### Issue description
The test https://github.com/aws/aws-sdk-ruby/blob/9ea447b7e9e57e27bb7924aca40a5bf0c3265a94/gems/aws-sdk-core/spec/aws/plugins/region_endpoint_spec.rb#L38-L43 has the following title: `        it 'prefers AWS_DEFAULT_REGION to AWS_REGION or AMAZON_REGION'`

According to the implementation in the tests, shouldn't it be `it 'prefers AWS_REGION to AWS_DEFAULT_REGION or AMAZON_REGION'` instead, as the expect is the `AWS_REGION` value?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
N.A.

### Version of Ruby, OS environment
N.A.

### Code snippets / steps to reproduce
N.A.

**Comment by cjyclaire** [comment]
Thanks, it's a description typo, we do resolve logic in `AWS_REGION AMAZON_REGION AWS_DEFAULT_REGION` [order](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/regional_endpoint.rb#L48)

**Comment by cjyclaire** [comment]
PR #1817 fixing this has been merged : ) closing
