### ISSUE TITLE
 Aws::RDS::Types::DBInstance does not appear to have tags

### ISSUE THREAD

**Issue by illegalnumbers** [aws/aws-sdk-ruby#1833]
Please fill out the sections below to help us address your issue

### Issue description
When calling Aws::RDS::Resource.db_instances the returned Aws::RDS::Types::DBInstance do not appear to have tags available on them.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk

### Version of Ruby, OS environment
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
osx 10.11.6

### Code snippets / steps to reproduce
```
   rds = Aws::RDS::Resource.new(client: client) # basic aws client
    rds.db_instances.each do |dbinstance|
      puts dbinstance.data # no tags
    end
```

**Comment by cjyclaire** [comment]
The underlying API call is [`#describe_db_instances`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#describe_db_instances-instance_method), which doesn't include tag information in response. You can try client API [`#list_tags_for_resource`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#list_tags_for_resource-instance_method) instead

**Comment by cjyclaire** [comment]
closing, free feel to reopen with further questions : )
