### ISSUE TITLE
Aws::MediastoreData::Client endpoint doesn't work

### ISSUE THREAD

**Issue by eniskonuk** [aws/aws-sdk-ruby#1834]
Please fill out the sections below to help us address your issue

### Issue description
Appears that the data.mediastore endpoint is incorrect. None of the supported regions work.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk version 2.11.87

### Version of Ruby, OS environment
Ruby 2.4.1, Linux 16.04

### Code snippets / steps to reproduce
mds = Aws::MediaStoreData::Client.new(credentials: c, region: 'us-east-1')
mds.list_items()
error: Seahorse::Client::NetworkingError Failed to open TCP connection to data.mediastore.us-east-1.amazonaws.com:443 (getaddrinfo: No address associated with hostname)

**Comment by awood45** [comment]
Investigating - I'm suspecting that this requires an endpoint to be provided manually and that we need to provide the proper error type for this. Stand by.

**Comment by awood45** [comment]
Okay, that's what is going on here. You need to provide an endpoint from the `#describe_container` call in the AWS Elemental MediaStore API.

**Comment by awood45** [comment]
For example:

```ruby
mediastore = Aws::MediaStore::Client.new
mediastore.create_container(container_name: CONTAINER_NAME)
# After a describe call shows the container is ACTIVE and has an endpoint...
endpoint = mediastore.describe_container(container_name: CONTAINER_NAME).container.endpoint
mediastore_data = Aws::MediaStoreData::Client.new(endpoint: endpoint)
# and then make your calls...
```

Leaving this open because in previous services like this we've removed the plugin which auto-fills the endpoint to make this requirement more clear, but hopefully this unblocks you :)

**Comment by eniskonuk** [comment]
Got it.... That fixed it. I think this makes it a documentation problem for the initializer as the endpoint is now a required field.

**Comment by awood45** [comment]
Right - this is true of one or two other services as well, just need to drive consistency of behavior here.

**Comment by mullermp** [comment]
Going to close this issue for now. Please reopen if this is still any concern.
