### ISSUE TITLE
Is there a way to list out all available AMIs?

### ISSUE THREAD

**Issue by designstuhl** [aws/aws-sdk-ruby#1835]
Please forgive me if this is low-hanging-fruit. I'd like to know if there is a way using the aws-sdk (or some flavor of the sdk IE aws-sdk-ec2) to list out all of the available AMIs in an availability region? From what I have found so far, I can find the AMI image ID on a particular instance and I can launch an EC2 instance from an AMI if I have the AMI image ID, but I'd like to be able to one day automate the process by having my app use the SDK to look up the most recent AMI with tag name 'Some-Example-Tag-Name' and fetch the ID for use in the next series of EC2 instances. 

aws-sdk-ec2 ~> 1

Ruby 2.2.5
Rails 4.1.4

### Code snippets / steps to reproduce
ec2 = Aws::EC2::Resource.new(region: 'us-east-1')
i1 = ec2.instances.first.data
i1.ami_launch_index // 0
i1.image_id // ami-123456abcdefg
i1.instance_id // I-qweasdzxc0987654

**Comment by cjyclaire** [comment]
Sounds like you can try API [`#describe_images`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_images-instance_method) ?

**Comment by designstuhl** [comment]
Thank you @cjyclaire !

That totally did it. calling the describe_images() api method on the instance.client allows me to find the list of AMI's so long as I enter in some type of filtering mechanism. 

In case anyone else is looking for this, calling .describe_images() on your instance.client will not yield anything, but if you know the owner ID of the AMI's you can filter by owners: ["string"] and return all of your AMI's that way. 

Also here is the link again that @cjyclaire provided:
[https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_images-instance_method](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#describe_images-instance_method)
