### ISSUE TITLE
glacier multipart uploads method has typo

### ISSUE THREAD

**Issue by nilesr** [aws/aws-sdk-ruby#1837]
### Issue description
According to the official documentation [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Glacier/Vault.html#multipart_uplaods-instance_method), the method for getting multipart uploads is `vault.multipart_uplaods()`

This matches the source code [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-glacier/lib/aws-sdk-glacier/vault.rb#L503)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-glacier 1.8.0, probably.

### Version of Ruby, OS environment
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu], Ubuntu 18.04 LTS, WSL

**Comment by cjyclaire** [comment]
Thanks for reporting! this is a typo in the resource model definition [here](https://github.com/aws/aws-sdk-ruby/blob/master/apis/glacier/2012-06-01/resources-1.json#L523), the glacier resource code you mentioned is auto generated from the typo in definition.

To unblock, you can use client API directly https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Glacier/Client.html

**Comment by srchase** [comment]
There's required work to figure out the right way to handle types in the resource models.

I'm closing this issue and we'll track it as a feature request.
