### ISSUE TITLE
Ses is not setting proper message id

### ISSUE THREAD

**Issue by philsmy** [aws/aws-sdk-ruby#1838]
We are trying to switch from drewblas/aws-ses to aws-sdk-ses. We are using an ActionMailer class. When we do deliver the message id is filled out, but NOT with the Amazon SES message id. This makes it impossible to track any further information coming from Amazon SES.

We're using aws-sdk-ses-1.8.0 under ruby 2.3

**Comment by srchase** [comment]
@philsmy 

Were you able to get this resolved?  This sounds like an issue on the ActionMailer side, and not with aws-sdk-ses.

**Comment by philsmy** [comment]
To be honest, no. We stuck with drewblas for mailing.

**Comment by srchase** [comment]
I'm going to go ahead and close this issue, since it likely pertains to an issue on the ActionMailer side.

We're happy to investigate further if you decide to take another look at it.
