### ISSUE TITLE
[dynamodb] Attributes defined as Number coming back mangled 

### ISSUE THREAD

**Issue by rromanchuk** [aws/aws-sdk-ruby#1841]
### Issue description

Most likely user error, it's late, probably missing something stupid. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
gem "aws-sdk-rails"
gem "aws-sdk-sns"
gem 'aws-sdk-dynamodb'

### Version of Ruby, OS environment

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

### Code snippets / steps to reproduce

```ruby
class FetchMessageService < Service
  attr_reader :challenge_id, :message_id, :client

  def initialize(challenge_id:, message_id:)
    @challenge_id = challenge_id
    @message_id = message_id
    @client = Aws::DynamoDB::Client.new(region: 'us-east-1')
  end

  def call
    client.get_item(item_attributes).item
  end

  def item_attributes
    {
      key: {
        challengeID: challenge_id, 
        messageID: message_id
      }, 
      table_name: "my-table"
    }
  end
end
```
```ruby
FetchMessageService.call(message_id: message_id, challenge_id: challenge_id)
# {"aws:rep:deleting"=>false, "challengeID"=>"258..", "messageID"=>"...",  "createdAt"=>0.1530673621e10, "aws:rep:updateregion"=>"us-east-1", "aws:rep:updatetime"=>0.1532060359524001e10"}
}
```

Here are the properties from the console

<img width="332" alt="screen shot 2018-07-26 at 12 16 50 am" src="https://user-images.githubusercontent.com/102188/43247362-59c32840-9069-11e8-8c25-e0c1cc2b2a53.png">

<img width="464" alt="screen shot 2018-07-26 at 12 16 58 am" src="https://user-images.githubusercontent.com/102188/43247371-63cdc228-9069-11e8-8074-76e99342421e.png">

**Comment by rromanchuk** [comment]
Actually, this looks like user error

```
irb(main):314:0> t["createdAt"].class
=> BigDecimal

irb(main):315:0> t["createdAt"].to_i
=> 1530673621
```

**Comment by awood45** [comment]
So for some background on this, since a DynamoDB numeric can be integers or float-type numbers, BigDecimal allows us to have a consistent return type for numeric attributes. Your solution for getting to the result you want is correct.

Libraries like aws-record will do this for you, if you define your attributes as specifically integer or float type.
