### ISSUE TITLE
How can I stub/mock Aws::S3::ObjectSummary

### ISSUE THREAD

**Issue by itmart** [aws/aws-sdk-ruby#1842]
Hi,

I'm trying to stub out a response for this code in my controller for testing purposes:
```
s3 = Aws::S3::Resource.new
bucket = s3.bucket("my-bucket")
@files = {}

bucket.objects.each do |item|
  @files[File.basename(item.key)] = item.presigned_url(:get)
end
```
The goal is to test `@files` will have the file and a presigned_url, which should work.

The problem I'm having is with `bucket.objects`. I tried a couple of things but it always return empty. Is there a way I can stub this? Here's what I tried:
```
Aws.config[:s3] = {
  stub_responses: {
    list_buckets: {
      buckets: [name: "my-bucket"]
    },
    get_object: {
      body: tempfile = file_fixture('file').read
    }
  }
}
```
Which resulted in bucket.objects being blank. I was able to get the bucket this way though:
```
s3.buckets.first
=> #<Aws::S3::Bucket:0x00007fe03160a400 @name="my-bucket", @data=#<struct Aws::S3::Types::Bucket name="my-bucket", creation_date=nil>, @client=#<Aws::S3::Client>>

s3.buckets.first.objects
=> #<Aws::S3::ObjectSummary::Collection:0x00007fe031633c10 @batches=#<Enumerator: #<Enumerator::Generator:0x00007fe031633d78>:each>, @limit=nil, @size=nil>

s3.buckets.first.objects.first
=> nil
```

I also tried stubbing with the `webmock` gem by doing:
```
tempfile = file_fixture('file').read
# tempfile = File.open(Rails.root.join('test','fixtures', 'files', 'master_tab_v1.csv'))
base_uri = Regexp.new "https://my-bucket.s3.us-west-1.amazonaws.com/"
stub_request(:get, base_uri).to_return(body: tempfile, status: 200)
```
This also returns empty when I tried `bucket.objects`

I'm using the `aws-sdk-s3` gem. My gemfile has this line for the gem: `gem 'aws-sdk-s3', '~> 1'`.

Running on ruby 2.5.1 and rails 5.1.6.

**Comment by awood45** [comment]
You need to stub out the `#list_objects` method. Your code as listed doesn't use `#list_buckets`, but assuming it's needed elsewhere, you could use a config line like this:

```ruby
Aws.config[:s3] = {
  stub_responses: {
    list_buckets: {
      buckets: [name: "my-bucket"]
    },
    list_objects: {
      contents: [{key: "mykey"}]
    },
    get_object: {
      body: tempfile = file_fixture('file').read
    }
  }
}
```

**Comment by itmart** [comment]
@awood45 Thank you for the quick reply!!! What you provided did indeed work, but do you know why `prefix` doesn't seem to be working anymore? I stubbed out a key like `folder1/file` and in my code, I called `bucket.objects(prefix: 'folder2')` but it still grabbed that object. Any ideas?

**Comment by itmart** [comment]
Also, will the `presigned_url` work? I don't think it's working but I'm not sure if there'd be a way to make it work if the request was stubbed out.
