### ISSUE TITLE
DAX get items support

### ISSUE THREAD

**Issue by fertobar** [aws/aws-sdk-ruby#1845]
I notice there is a client for DAX clusters : https://docs.aws.amazon.com/sdkforruby/api/Aws/DAX/Client.html

There is any client that support reads regular items using DAX, like **get_item** in Python client ?

**Comment by cjyclaire** [comment]
Could you help point me to the python feature for DAX? : )  I'm looking at their Docs for DAX https://boto3.readthedocs.io/en/latest/reference/services/dax.html#client  I don't see `#get_item there`?

**Comment by fertobar** [comment]
sure!
eg
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-python.03-getitem-test.html

`result = client.get_item(**params)`

**Comment by awood45** [comment]
The DAX team has, unfortunately, not provided an official Ruby client. We'll be happy to note this as a feature request and send your request on to them.

The AWS SDKs include support for the DynamoDB APIs, which includes control plane operations for DAX, but the data plane client is customized (note the `import amazondax` line, which relates to https://pypi.org/project/amazon-dax-client/ ).

**Comment by fertobar** [comment]
ok, thanks for the feedback!

**Comment by alejandromarcu** [comment]
Is this still not supported?
