### ISSUE TITLE
Check status code for 429 for throttling_error?

### ISSUE THREAD

**Issue by arianf** [aws/aws-sdk-ruby#1850]
https://github.com/aws/aws-sdk-ruby/blob/1a86b112d8c76f23a1f2be8ee3df1432ba821418/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L106-L108

`throttling_error?` should also check the status code for `429` to determine `throttling_error?` as well

Potential New Code:
```ruby
def throttling_error?
  !!(THROTTLING_ERRORS.include?(@name) || @name.match(/throttl/i) || @http_status_code == 429)
end
```

*Not a Contribution*

**Comment by srchase** [comment]
Hi @arianf,

Would you be interested in submitting a Pull Request for this change?

**Comment by arianf** [comment]
@srchase @awood45 I've created a pull request here: #1889
