### ISSUE TITLE
Getting a lot of "instance variable not initialized" warnings

### ISSUE THREAD

**Issue by alebian** [aws/aws-sdk-ruby#1858]
### Issue description

Using the gem throws a lot of warnings:

```
/Users/alebian/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.24.1/lib/seahorse/model/shapes.rb:62: warning: instance variable @location not initialized

/Users/alebian/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.24.1/lib/aws-sdk-core/shared_config.rb:129: warning: instance variable @parsed_config not initialized
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

Using `aws-sdk-s3` gem version `1.17`

### Version of Ruby, OS environment

Ruby version 2.5.1 and macOS 10.13.6

### Code snippets / steps to reproduce

Running tests in my app with RSpec

**Comment by awood45** [comment]
I think this is a known issue with our code and Ruby 2.5 - will take this as another note to clean some of these up.

**Comment by mullermp** [comment]
I think that these were fixed long ago... closing :)
