### ISSUE TITLE
Stubbing responses via Config still requires credentials?

### ISSUE THREAD

**Issue by softwaregravy** [aws/aws-sdk-ruby#1862]
Please fill out the sections below to help us address your issue

### Issue description
I am using the stubs for S3. I have stubbed using `Aws.config[:s3]` this is working, except that I seem to need credentials. Is this expected behavior?

```
    Aws.config[:s3] = {
      stub_responses: {
        get_object: {
          status_code: 200,
          headers: {},
          body: load_fixture('domain_data_set_string', 'csv')
        }
      }
    }
```

If it is expected that I still need credentials, then with my setup they will need to be stored somewhere. What I've done is created credentials which have no permissions attached. Are these safe to leave in my repository?

**Comment by awood45** [comment]
That should work, you do NOT need credentials. I have questions:

1: What version of the SDK are you using?

2: What happens if you create a client in the following way?

```ruby
    Aws::S3::Client.new(
      stub_responses: {
        get_object: {
          status_code: 200,
          headers: {},
          body: load_fixture('domain_data_set_string', 'csv')
        }
      }
    )
```

3: How are you creating your client that is asking for credentials?

**Comment by softwaregravy** [comment]
Sorry for not responding sooner. I'll re-open when I'm ready to re-investigate.
