### ISSUE TITLE
The API request record also saves built-but-not-sent requests from aws-sdk-s3 presigning

### ISSUE THREAD

**Issue by janko-m** [aws/aws-sdk-ruby#1866]
### Issue description

I have been using the new API requests record, and I noticed that when I make a presigned URL, the corresponding API call is saved in the record, even though the request itself was not sent.

I assume the place which triggers the "fake" API request recording is here: https://github.com/aws/aws-sdk-ruby/blob/8dbe883f810271a2132b7a754ac79faf61a66a2b/gems/aws-sdk-s3/lib/aws-sdk-s3/presigner.rb#L51-L54

Since in my project I want to be diligent with how many API requests I'm actually sending, it would be ideal if `Aws::S3::Presigner#presigned_url` didn't add anything to the API request record.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

* aws-sdk-core 3.24.1
* aws-sdk-s3 1.17.0

### Version of Ruby, OS environment

* Ruby 2.5.1

### Code snippets / steps to reproduce

```rb
require "aws-sdk-s3"

client = Aws::S3::Client.new(stub_responses: true)
presigner = Aws::S3::Presigner.new(client: client)

presigner.presigned_url(:get_object, bucket: "my-bucket", key: "foo")

p client.api_requests[0][:operation_name]
```
```
:get_object
```

**Comment by awood45** [comment]
This is a good callout, I hadn't thought of this. I'm happy to take a pull request for this as well.

**Comment by cjyclaire** [comment]
PR #1867 is opened addressing this issue

**Comment by awood45** [comment]
So thinking about this, I'm a little concerned that changing this could break customers who have started to write test expectations against this. Would it meet your needs if we instead lifted whether or not the request was presigner based to the top level of the API requests object? Or, possibly, if we allowed you to filter them out with an optional param?

**Comment by cjyclaire** [comment]
PR has been merged, now you can try:
```ruby
client.api_requests(exclude_presign: true).size.zero?
# => true
```

This will be out in the next release, closing : )

**Comment by janko-m** [comment]
Thanks for the quick fix! Ok, the additional option makes sense to me for preserving backwards compatibility.
