### ISSUE TITLE
Bucket method doesnt accept options

### ISSUE THREAD

**Issue by antpaw** [aws/aws-sdk-ruby#1868]
I think i have found a bug in the documentation, it's not possible to pass in the virtual_host: option to the .bucket method. It would really great if that would work.

https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/bucket.rb#L64

**Comment by cjyclaire** [comment]
@antpaw Thanks for reporting! It's a typo in the doc, you can try
```
 bucket = s3.bucket('my.bucket.com')
 bucket.url(virtual_host: true)
```
instead :)

I'll update the doc

**Comment by cjyclaire** [comment]
PR #1867 covers this doc update.
Closing, feel free to reopen with further questions : )
