### ISSUE TITLE
Unable to set Content-Type metadata.

### ISSUE THREAD

**Issue by mark100net** [aws/aws-sdk-ruby#1873]
### Issue description
When I try to update metadata, the existing Content-Type value is turned into an empty string. If I try to include a Content-Type key in my update, a new key is created called 'x-amz-meta-content-type', and the existing Content-Type value is turned into an empty string as when I don't try to set it at all.
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
    aws-sdk, aws-sdk-s3

### Version of Ruby, OS environment
    ruby 2.5.1p57, macOS 10.13.6

### Code snippets / steps to reproduce

    client = Aws::S3::Client.new(
      :region => 'us-west-2',
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_KEY'], 
    )
    s3 = Aws::S3::Resource.new(:client => client)

    object = s3.bucket(ENV['AWS_BUCKET']).object('mypath/myfilename')

    new_metadata = object.metadata.merge("json" => { "name" => "afile.zip",
                                      "model_class" => "Course",
                                      "model_attachment" => "course_file" }.to_json)

     object.copy_to(object, :metadata => new_metadata,
     :metadata_directive => "REPLACE",
    )

Resulting metadata for this example:

Before:

    x-amz-meta-json: { "name": "some-old-name" }
    Content-Type: { "application/octet-stream" }

After:

    Content-Type:    # empty    
    x-amz-meta-json: { "name": "afile.zip", "model_class": "Course", "model_attachment": "course_file" }
 
So how can I remove or update the Content-Type key?

**Comment by srchase** [comment]
@mark100net 

You can update the Content-Type like this:

```
client = Aws::S3::Client.new(
  :region => 'us-west-2',
  :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
  :secret_access_key => ENV['AWS_SECRET_KEY'], 
)
s3 = Aws::S3::Resource.new(:client => client)

object = s3.bucket(ENV['AWS_BUCKET']).object('mypath/myfilename')

new_metadata = object.metadata.merge("json" => { "name" => "afile.zip",
                                  "model_class" => "Course",
                                  "model_attachment" => "course_file" }.to_json)

source = ENV['AWS_BUCKET'] + 'mypath/myfilename'

object.copy_from({acl: 'public-read', content_type: 'text/plain', metadata_directive: 'REPLACE', copy_source: source, metadata: new_metadata})

```

**Comment by mark100net** [comment]
@srchase That's perfect thanks a bunch. 

For anyone copying the code above from @srchase note that `source` variable needs a '/' before 'mypath'.
