### ISSUE TITLE
aws-sdk-cloudwatchlogs (Gem Not Found)

### ISSUE THREAD

**Issue by franciscopinheir** [aws/aws-sdk-ruby#1874]
Gem Not Found after update (on ubuntu machine)

### Gem name 'aws-sdk-cloudwatchlogs'

Any problems with the latest updates?

**Comment by cjyclaire** [comment]
Hmmm, interesting, could you provide info on how you install it?
You can see it's alive there at RubyGems https://rubygems.org/gems/aws-sdk-cloudwatchlogs

**Comment by franciscopinheir** [comment]
Solved. I had two different versions of Ruby installed. Sorry and thank you for the reply ;)
