### ISSUE TITLE
new_device_metadata is returning nil

### ISSUE THREAD

**Issue by maryshirl** [aws/aws-sdk-ruby#1875]
Please fill out the sections below to help us address your issue

### Issue description
I'm trying to implement the #update_device_status which needs a parameter of device_key. My understanding is that I can retrieve the device_key from the new_device_metadata  which is included in the response of InitiateAuth. However, the value I get for the new_device_metadata is nil. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
     aws-sdk-cognitoidentityprovider v1.6.0

### Version of Ruby, OS environment
    ruby 2.5.1, macOS 10.13.3

### Code snippets / steps to reproduce

     resp = client.initiate_auth({
          client_id: app_client_id, # required
          auth_flow: "USER_PASSWORD_AUTH", 
          auth_parameters: {
              "USERNAME" => username,
              "PASSWORD" => password,

            },
            client_metadata: {
                "StringType" => "StringType",
            },
            analytics_metadata: {
                 analytics_endpoint_id: "StringType",
            },
            user_context_data: {
                 encoded_data: "encoded_data",
            },
     })

#### returns new_device_metadata with value nil

     #<struct Aws::CognitoIdentityProvider::Types::InitiateAuthResponse challenge_name=nil, session=nil, challenge_parameters={}, authentication_result=#<struct Aws::CognitoIdentityProvider::Types::AuthenticationResultType access_token=<access_token> expires_in=3600, token_type="Bearer", refresh_token=<refresh_token>, id_token=<id_token>, new_device_metadata=nil>>

How do I get the device_key?

**Comment by srchase** [comment]
@maryshirl 

Was the device previously confirmed?

Are you able to get the list of devices by calling client.confirm_device?  Or can you see the device listed in the AWS Console?

**Comment by maryshirl** [comment]
Thank you for your response @srchase.

The device wasn't previously confirmed. How do I confirm a device?
I checked the device in the AWS console, and it's not listed. How do I add the device?

My understanding is that every time a user uses a new device, when the user signs in, the api returns a device key and I could use that device key to confirm the device.

**Comment by srchase** [comment]
We're working with the Cognito Identify Provider to clear up this issue.  They're looking into the documentation to provide clarity on when new_device_metadata should be returned with an auth call.

We'll pass along that information it is shared with us.

**Comment by maryshirl** [comment]
Okay, thank you! Is there a time frame for this? I'm asking so that I know when to check this out again. Thanks again.

**Comment by srchase** [comment]
@maryshirl 

The Service Team has indicated that their documentation is incorrect and needs to be updated.

Their explanation is that only auth flows that include RespondToAuthChallenge will return NewDeviceMetadata.

Are you able to change to an auth flow that includes RespondToAuthChallenge?

**Comment by srchase** [comment]
@maryshirl 

I'm going to close this issue for now.  Happy to re-open if you suspect the SDK is not working as expected.
