### ISSUE TITLE
SQS message attributes are not populated when receiving a message.

### ISSUE THREAD

**Issue by RUN-CMD** [aws/aws-sdk-ruby#1885]
### Issue description

SQS message attributes are not populated when receiving a message.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-sqs (1.4.0)`

### Version of Ruby, OS environment

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

### Code snippets / steps to reproduce

```
require 'aws-sdk-sqs'

sqs = Aws::SQS::Resource.new(region: 'us-east-1')
queue = sqs.get_queue_by_name(queue_name: '...')
queue.send_message({ message_body: '{"foo":20}', message_attributes: { "baz": { string_value: "qux", data_type: "String" } } })

# => #<struct Aws::SQS::Types::SendMessageResult md5_of_message_body="d6cf0f93237ada70daf9b6e75cfff2e6", md5_of_message_attributes="16bd0283a5b4962721ccd3efe4bc6257", message_id="07d250f8-8633-4103-bb0b-1a2075cabe64", sequence_number=nil>

queue.receive_messages({attribute_names: ["All"]})

# => #<Aws::SQS::Message::Collection:0x007ff1a911c9f0 @batches=[[#<Aws::SQS::Message:0x007ff1a911cb08 @queue_url="https://sqs.us-east-1.amazonaws.com/XXX/XXX", @receipt_handle="AQEBqciY9npfykvxdnFzJFPPrXmQeqEI0SlkCHb+sbiz8aa0eN3+EC8EukWQnL1f0AHj2fhUbe6xe0ManKN4rszO7flRdgSQ2Rfvz6eGQDhz6v1f7PYjM5oMgQt+fLy+V96Vg3sz82FMe1y6sc54hUocP0o+CvBLUw3TbqRAuLm/bkCD39bBV3+q35DWZOdP5KPwuCXCIMYe/MU6CWG7eOzrlfHexWENDHgrKxYhduhQiaCg4szkKVWQ47/NexEyF05pAs+vB4YLHf4CoiT5wKxgwXrQOVJXq8VMK/ftagcgos7dNNQTDX4sM26xC1t0qANipCFoaEW5z+M22y4QMeGVcVs5nc+SjtBSRkJyVtG0RmiORVOUqthuAnIB0MoaE4QvZ3vz6cdr+pu9XicJ5HExEy+wniyhY4C+/UCBZhME+Mg=", @data=#<struct Aws::SQS::Types::Message message_id="07d250f8-8633-4103-bb0b-1a2075cabe64", receipt_handle="AQEBqciY9npfykvxdnFzJFPPrXmQeqEI0SlkCHb+sbiz8aa0eN3+EC8EukWQnL1f0AHj2fhUbe6xe0ManKN4rszO7flRdgSQ2Rfvz6eGQDhz6v1f7PYjM5oMgQt+fLy+V96Vg3sz82FMe1y6sc54hUocP0o+CvBLUw3TbqRAuLm/bkCD39bBV3+q35DWZOdP5KPwuCXCIMYe/MU6CWG7eOzrlfHexWENDHgrKxYhduhQiaCg4szkKVWQ47/NexEyF05pAs+vB4YLHf4CoiT5wKxgwXrQOVJXq8VMK/ftagcgos7dNNQTDX4sM26xC1t0qANipCFoaEW5z+M22y4QMeGVcVs5nc+SjtBSRkJyVtG0RmiORVOUqthuAnIB0MoaE4QvZ3vz6cdr+pu9XicJ5HExEy+wniyhY4C+/UCBZhME+Mg=", md5_of_body="d6cf0f93237ada70daf9b6e75cfff2e6", body="{\"foo\":20}", attributes={"SenderId"=>"XXX", "ApproximateFirstReceiveTimestamp"=>"1538000336372", "ApproximateReceiveCount"=>"1", "SentTimestamp"=>"1538000323477"}, md5_of_message_attributes=nil, message_attributes={}>, @client=#<Aws::SQS::Client>>]], @limit=nil, @size=1>
```

Note specifically in message response:
```
md5_of_message_attributes=nil, message_attributes={}
```

**Comment by srchase** [comment]
Hello @RUN-CMD 

I apologize for the delayed response.

The service is not returning the md5 of message attributes.

If you enable the http_wire_trace when setting up the SQS client, like this:

```
sqs = Aws::SQS::Resource.new(region: 'us-west-2', http_wire_trace: true)
```

you can see the XML response and will see that the md5 you're looking for is not there.  When I ran the code, I did receive the message attributes though.

I've opened a request with the service team to have them look into the issue.  I'll update you as I hear a response from that team.

**Comment by srchase** [comment]
Hello @RUN-CMD,

Can you try this instead:
```
queue.receive_messages({message_attribute_names: ["All"]})
```

When message_attribute_names is set, either to "All" or specific message attribute names, it will return all or specific message attributes along with an MD5 hash of the returned attributes.

The documentation should be improved to make that clear that message_attribute_names can take "All".

**Comment by RUN-CMD** [comment]
> Can you try this instead:
> `queue.receive_messages({message_attribute_names: ["All"]})`

This worked for me, thank you !

This resolves my issue.
