### ISSUE TITLE
Add support for acceleration with presigned URLs

### ISSUE THREAD

**Issue by philippevezina** [aws/aws-sdk-ruby#1886]
### Issue description
It is currently not possible to create a presigned URL that uses transfer acceleration.
https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

Example
https://stackoverflow.com/questions/37437782/aws-transfer-acceleration-with-pre-signed-urls-using-javascript-sdk

### Gem name
aws-sdk-s3

**Comment by srchase** [comment]
Hello @philippevezina,

Acceleration is supported with the Presigner, but you need to pass in use_accelerate_endpoint on the presigned_url method:

```
require 'aws-sdk-s3'

signer = Aws::S3::Presigner.new()
url = signer.presigned_url(:put_object, bucket: 'my_bucket', key: 'my_key', use_accelerate_endpoint: true)
```

Is this what you were hoping to accomplish?

**Comment by philippevezina** [comment]
Yes, that's exactly what I was looking for! I couldn't find it in the source code. Thank!
