### ISSUE TITLE
Seahorse::Client::NetworkingError (execution expired)

### ISSUE THREAD

**Issue by bituinb** [aws/aws-sdk-ruby#1890]
### Uploading files to s3,  I'm getting error exception Seahorse::Client::NetworkingError (execution expired).
This happens on staging environment using kubernetes.

### Code snippets / steps to reproduce

require "aws-sdk-s3"

resource = Aws::S3::Resource.new(
  access_key_id:     my_key_value,
  secret_access_key: my_secret_value,
  region:    "ap-southeast-2"
)

File.open("tmp/test.txt", "w+") do |file|
   file.write("blahblah")
end

bucket = resource.bucket("my-bucket")
object = bucket.object("keyfoo")
object.upload_file("tmp/test.txt")

**Comment by srchase** [comment]
@bituinb 

Thanks for raising this issue.

Where is this error being returned?  On the object.upload_file?

**Comment by bituinb** [comment]
Hi,

Thanks for your reply, it's fixed now.
Changing the configuration for kubernetes deployment for our app-frontend fixes the pods that host our staging environment.

Thank you

**Comment by srchase** [comment]
Thanks for following up!  I'm going to close out this issue.

**Comment by victorboissiere** [comment]
@bituinb do you remember what the configuration change was?
