### ISSUE TITLE
Stubbing RDS Client Waiters

### ISSUE THREAD

**Issue by CESteinmetz** [aws/aws-sdk-ruby#1895]
### Issue description
Is it possible to stub RDS client waiters? I would like the waiter to return true that a DB instance state is available, but keep hitting the following error

```
Failure/Error:
       client.wait_until(:db_instance_available,
                         client.describe_db_instances(db_instance_identifier: 'my-db-nme']).db_instances[0].to_h)

     ArgumentError:
       unexpected value at params[:db_instance_status]
```

I created the following stubs:

```
description = {
      db_instance_identifier: 'test-db',
      db_instance_status: 'available'
    }

    client.stub_responses(
      :describe_db_instances, db_instances: [description]
    )

    client.stub_responses(
      :wait_until, true
    )
```

If I modify the line:

```
client.wait_until(:db_instance_available,
                         client.describe_db_instances(db_instance_identifier: 'my-db-name']).db_instances[0].to_h)
``` 

and remove the `.to_h`, the error message:

```
 ArgumentError:
       expected params to be a hash, got value #<struct Aws::RDS::Types::DBInstance db_instance_identifier="my-db-name", ..., db_instance_status="available"...> (class: Aws::RDS::Types::DBInstance) instead.
```

clearly indicates that the stubbed values are being carried over to the method result. However, once I transpose the struct into a Hash, the values appear to be lost as indicated from the 'unexpected value at param' error message.

### Gem name 
`aws-sdk (2.10.134)`

### Version of Ruby, OS environment
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]

**Comment by awood45** [comment]
You can't stub the waiters directly, only the underlying client calls.

**Comment by awood45** [comment]
This example worked for me:

```ruby
rds = Aws::RDS::Client.new(stub_responses: true)
rds.stub_responses(
  :describe_db_instances,
  db_instances: [
    {
      db_instance_identifier: "test-db",
      db_instance_status: "available"
    }
  ]
)
rds.wait_until(:db_instance_available)
```

Are you trying to do something beyond that?

**Comment by CESteinmetz** [comment]
Thank you so much for your response, Alex. 

I am using these stubs to write rspec tests for a wrapper method which modifies an RDS instance using the `modify_db_instance` method call, and then calls the waiter to ascertain that the db instance is available for use before returning.

The wrapper method looks like this:

```
def wrapper_method(client, params)
 ...
      client.modify_db_instance(
         ...
      )

      client.wait_until(:db_instance_available, client.describe_db_instances(db_instance_identifier: 'my-db-name']).db_instances[0].to_h)    
end
```
If I remove the `describe_db_instances` parameter from the waiter call, then the rspec test passes, as per your example.

In your example, because you stubbed `describe_db_instances`, does the rds client calling the waiter automatically "bind" the `:db_instance_available` to the rds instance defined in `describe_db_instances`? Would that hold true for a legitimate method call as well? Under what circumstances is it necessary to explicitly call the `describe_db_instances` method as a parameter to the waiter?

**Comment by srchase** [comment]
@CESteinmetz 

For a real wait_until call, you can supply parameters that will be used used for the describe_db_instances calls.  Those [parameters](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#describe_db_instances-instance_method) can help if you want to wait for a specific instance (or group of instances through filtering) to reach the available state.  If you don't supply those parameters, the underlying describe_db_instances call will return all db instances.

In @awood45's example, the stubbed response for describe_db_instances, used by the wait_until call, is set to return the single instance, so it is unnecessary to add any params.

**Comment by srchase** [comment]
Closing this issue.  Let us know if you have additional questions.
