### ISSUE TITLE
Lambda response wraps string in an extra set of quotes, triple escapes chars

### ISSUE THREAD

**Issue by lizdenhup** [aws/aws-sdk-ruby#1897]
Please fill out the sections below to help us address your issue

### Issue description
I am working on an aws lambda that takes in some data from a file and outputs html. The html that is outputted has two sets of double quotes around it, and other characters are triple-escaped. What is the proper way to avoid this, or sidestep this problem? Thanks. 

### Gem name
aws-sdk-lambda, v1.11

### Version of Ruby, OS environment
ruby 2.4.4
Mac OS 10.13.4

### Code snippets / steps to reproduce
Here is a simplified example of the lambda:
```
exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('<table class="foo"><tr><td></td></tr></table>')
    };
    return response;
};
```
Here is the response returned after successfully invoking the lambda:
```
{
  "statusCode": 200,
  "body": "\"<table class=\\\"foo\\\"><tr><td></td></tr></table>\""
}
```

**Comment by awood45** [comment]
To help debug this, can you show the response you received in wire trace? Turning on `http_wire_trace: true` on your `Aws::Lambda::Client` class should provide the wire trace. That will help us determine where the formatting is being applied.

**Comment by awood45** [comment]
The wire trace logs there show me that the triple-escaping happened before the response was sent to the Ruby SDK, we're faithfully returning what the service gave us.

What I'd recommend doing is looking at your Lambda handler's implementation, and possibly reaching out to AWS Support. I don't know which runtime you're invoking, so I may not have the expertise to help debug your Lambda handler.

Closing as there's nothing much we can do on the Ruby SDK end. Feel free to reach out if you have more questions or see further issues after the wire trace shows the output you want.
