### ISSUE TITLE
Access files in s3 using assume role, without having access to a specific bucket

### ISSUE THREAD

**Issue by alinavancea** [aws/aws-sdk-ruby#1905]
### ruby 2.3.1

We have set up a shared credentials with an amazon account cross account roles.
Following the docs here I managed to set up aws cli in command line and I'm able to use it without having any access to the bucket in which are the files.
https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

I received an external_id, role_arn which I use to get the temporary credentials. Then from here i set up set up as env variables then use them to get the temporary session token. 
After that I can successfully connect and ls or cp files.

I need to work in the same manner from ruby using aws-sdk-s3. 
I don't see a way to list objects without a bucket name, is that possible?
I have access according to the policy to a specific path: "s3://path/to/files"

```
role_credentials =  Aws::AssumeRoleCredentials.new(external_id: external_id, role_arn: role_arn, role_session_name: role_session_name) 
client = Aws::S3::Client.new(credentials: role_credentials)  
client.list_objects    # bucket is required here
```

Thank you!

**Comment by alinavancea** [comment]
@srchase thank you so much for your fast reply! 
The policy we have set up is not set up on a bucket, therefor we don't have access to list the buckets
Here is what I'm trying to do
```
role_credentials =  Aws::AssumeRoleCredentials.new(external_id: external_id, role_arn: role_arn, role_session_name: role_session_name) 
aws=Aws::S3::Client.new(credentials: role_credentials) 
aws.list_buckets                                                                                                                                                                            
Aws::S3::Errors::AccessDenied: Access Denied
```

**Comment by srchase** [comment]
@alinavancea 

The Access Denied error indicates that the assume role you are using does not have permissions to list the buckets of the account.

You can refer to this [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html) to make sure that your policy for that role is correct.

The [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) for S3 can be of help if you have further questions on configuring the correct permissions.

**Comment by alinavancea** [comment]
Thank you I will check that

**Comment by alinavancea** [comment]
I'm back with an update on how I manage to to the operations while having access to a specific path only.

From the path we received we figure out that we have the bucket name. Even though we don't have any permission to list the objects inside it, we can access the content for the given path only using the `prefix`option
`s3://bucket_name/our_folder`

I was stuck because I was keep trying to list the bucket content itself, which was obviously not working since we did not hat the permission. It did not crossed my mind that there can be a bucket object `bucket = s3.bucket(bucket_name)` even though no permission and later use it for getting the objects inside with `prefix` option.

```
      role_credentials = Aws::AssumeRoleCredentials.new(external_id: external_id, role_arn: role_arn, role_session_name: role_session_name)
      client = Aws::S3::Client.new(credentials: role_credentials, region: region)
      s3 = Aws::S3::Resource.new(client: client)
      bucket = s3.bucket(bucket_name)
      bucket.objects(prefix: "our_folder/").each do |aws_object|
        object_key = aws_object.key
        file = File.open("local_file.csv")
        client.get_object({ bucket: bucket_name, key: object_key }, target: file)
     end
```

**Comment by srchase** [comment]
@alinavancea 

Thanks for following up.

Does this accomplish everything you were needing?  Do you have any followup questions?

**Comment by alinavancea** [comment]
Everything is working ok :)
@srchase thank you for your time and help!
No other questions from me

Best,
Alina

**Comment by srchase** [comment]
@alinavancea 

You're welcome.  Closing out this issue.
