### ISSUE TITLE
CloudFormation dashboard name doesn't allow "-"

### ISSUE THREAD

**Issue by cgledezma1101** [aws/aws-sdk-ruby#1906]
Please fill out the sections below to help us address your issue

### Issue description

When invoking the `Seahorse` client, the `define_operations` method fails saying that the name of a CloudWatch dashboard needs to be alphanumeric. Unfortunately, there is not much code context that I can provide because I'm consuming your library through a third party, but it is this package that shows at the end of the stacktrace:

```
Template format error: Resource name CloudWatch-Default is non alphanumeric.
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/seahorse/client/request.rb:70:in `send_request'
/private/env/ruby2.3.x/ruby2.3.x/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.104/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
```

CloudFormation and CloudWatch both support hyphens in dashboard names, and there's no issue in creating dashboards with these names through the UI.

Is this an issue on your end, or on CFn's APIs?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Version of Ruby, OS environment

OS: MacOS Sierra (Version 10.12.6 (16G1618))
Ruby: 2.3.0

**Comment by srchase** [comment]
@cgledezma1101 

Thanks for opening this issue.

Are you able to share which third-party library you are using?

**Comment by cgledezma1101** [comment]
@srchase Unfortunately the package is an internal tool managed by another team at my company. I do not have access to the wire logs but can try finding it out.

From what I've been using the tool for, I would say the issue is somewhere where managing of creation of CloudFormation templates happen

**Comment by srchase** [comment]
This would be an error passed through from the CloudFormation API for template validation.  That validation would happen on the creation of a stack or change set, or on a call to validate_template.

The validation is performed by the service and not in the SDK itself.  As there isn't an issue with the SDK, I'm going to close this issue.  We'll assist the Service Team in getting this resolved.
