### ISSUE TITLE
doesn't yet use .aws/config ca_bundle

### ISSUE THREAD

**Issue by mmattice** [aws/aws-sdk-ruby#1907]
Please fill out the sections below to help us address your issue

### Issue description
aws-cli uses ca_bundle in `~/.aws/config` [aws-cli usage](https://github.com/aws/aws-cli/blob/69208fe970e2b9302e4ce157c68e98deeb6a9dd1/awscli/customizations/globalargs.py#L69)
aws-sdk-ruby does not

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-core 3.36.0

### Version of Ruby, OS environment
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

### Code snippets / steps to reproduce
Be behind corporate SSL MITM firewall.  Use `ca_bundle` in `~/.aws/config` to allow aws-cli to work.  Try to run something ruby based, get failures due to lack of use of configured bundle.

```
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.36.0/lib/seahorse/client/net_http/connection_pool.rb:96:in `session_for'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.36.0/lib/seahorse/client/net_http/connection_pool.rb:297:in `start_session'
	 5: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
	 4: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/net/http.rb:915:in `start'
	 3: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 2: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/net/http.rb:981:in `connect'
	 1: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (Seahorse::Client::NetworkingError)
```

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.

**Comment by mullermp** [comment]
I'm hesitant to support both a shared config value and AWS_CA_BUNDLE environments because no other SDK supports it other than cli/python. Go supports AWS_CA_BUNDLE but no shared config. I am wondering if we should do the same.

**Comment by mullermp** [comment]
I'm going to talk with other SDK teams about this.

**Comment by mullermp** [comment]
This is supported in core 3.106.0 as per #2361
