### ISSUE TITLE
Stubbing multiple responses using Aws.config

### ISSUE THREAD

**Issue by itmart** [aws/aws-sdk-ruby#1908]
I'm trying to stub multiple responses to simulate a connection error to S3 server. We are using the [retriable gem](https://github.com/kamui/retriable) to try again if an error occurred. I want to stub the `#list_objects` method to raise an `Errno::ECONNREFUSED` exception first, then return a valid file the next time to make sure our app is handling errors properly. However, it seems I got the exception both times in my test. My stub:
```
Aws.config[:s3] = {
  stub_responses: {
    list_objects: {
      contents: [Errno::ECONNREFUSED, { key: "key/aws_file.pdf" }]
    },
    get_object: [Errno::ECONNREFUSED, file_fixture('aws_file.pdf').read]
  }
}
```

The code to download the file from S3 (I want this to fail the first time, then retriable would try again and should work the 2nd time):
```
def self.download_file(bucket_name, object_key)
  s3 = Aws::S3::Resource.new
  bucket = s3.bucket(bucket_name)
  bucket_objects = bucket.objects.select do |item|
    item.key.start_with? object_key
  end

  latest_object = bucket_objects.last
  latest_object.presigned_url(:get)
end
```

**Comment by srchase** [comment]
@itmart 

Thanks for opening this issue.

Contents defines a single response.  Can you give this a try instead?

```
Aws.config[:s3] = {
  stub_responses: {
    list_objects: [
        'Errno::ECONNREFUSED', 
        { key: "key/aws_file.pdf" }
    ]
  }
}
```

Check out the [Advanced Client Stubbing](https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/) blog post.

**Comment by itmart** [comment]
@srchase 

Sorry for the late response, I recently moved on to something else and just now revisit this issue. I didn't realize the `contents` was for defining a single response. Your suggestion seems to correctly made the code run twice, but when it runs the second time, I'm getting this error:
```
ArgumentError Exception: unexpected value at params[:key]
```
when it's defining s3 resource:
```
Aws::S3::Resource.new
```
Do you have any ideas on how to resolve this issue?

**Comment by srchase** [comment]
@itmart 

Rather than define the s3 resource again, can you reuse it?  Or am I misunderstanding where you are having the issue?

**Comment by itmart** [comment]
I tried taking out the `key:` part and just have this:

```
Aws.config[:s3] = {
  stub_responses: {
    list_objects: [
      Errno::ECONNREFUSED,
      "key/aws_file.pdf"
    ],
    get_object: [Errno::ECONNREFUSED, file_fixture('aws_file.pdf').read]
  }
}
```

But I'm getting `Errno::ECONNREFUSED` on both tries when trying to download the file.

**Comment by srchase** [comment]
@itmart,

You're calling download_file twice?

If you call that twice, it will be setting up a new s3 resource each time.

If you want to advance to the second stubbed response, you'll need to re-use that s3 resource rather than creating a new one.

**Comment by itmart** [comment]
@srchase Ahhhhhh it never occurred to me that I was doing that. Let me refactor some stuff around and see what happens.

**Comment by itmart** [comment]
@srchase 

Okay, so this is my new setup:
```
# Stub
Aws.config[:s3] = {
  stub_responses: {
    list_objects: [
      Errno::ECONNREFUSED,
      "key/aws_file.pdf"
    ],
    get_object: [Errno::ECONNREFUSED, file_fixture('aws_file.pdf').read]
  }
}

def download_file(bucket_name, object_key, s3)
  bucket = s3.bucket(bucket_name)
  bucket_objects = bucket.objects.select do |item|
    item.key.start_with? object_key
  end

  latest_object = bucket_objects.last
  return nil if latest_object.blank?
  latest_object.presigned_url(:get)
end

# Test
test 'expects to retry to get AWS S3 file when service is temporarily down' do
  s3 = Aws::S3::Resource.new
  Retriable.retriable do
    download_file("bucket", "key/aws_file.pdf", s3)
  end
end
```

The retriable block is running twice and I got a connection error on the first try as expected. However, on the second try, `bucket.objects.select` threw this error: `Aws::S3::Errors::Keyawsfilepdf Exception: stubbed-response-error-message`. 

I tried using this stub instead:

```
Aws.config[:s3] = {
  stub_responses: {
    list_objects: [
      Errno::ECONNREFUSED,
      key: "key/aws_file.pdf" # using a hash here instead of just a string
    ],
    get_object: [Errno::ECONNREFUSED, file_fixture('aws_file.pdf').read]
  }
}
```
But that resulted in this error: `ArgumentError: unexpected value at params[:key]` when it's running `s3 = Aws::S3::Resource.new`. 

I feel like I'm very close to figuring this out but I can't figure out the right syntax. Can you help me look into what is it that I'm missing? Thank you so much for taking your time and helping me out with this!

**Comment by srchase** [comment]
This part:
```
bucket_objects = bucket.objects.select do |item|
    item.key.start_with? object_key
end
```

Is trying to iterate through the 'contents' returned in the list_objects call, where each item is a hash, with the key that you are trying to match on.  That error is being raised because it cannot find a key while attempting to iterate on the response you stubbed.

You can stub list_objects like this, so that the second list_objects call will get something that is meaningful to bucket.objects.select:

```
Aws.config[:s3] = {
  stub_responses: {
    list_objects: [
      Errno::ECONNREFUSED,
      { contents: [ {key: 'foo' }, {key: 'foobar'}, {key: 'bar'} ] }
    ]
  }
}
```

**Comment by itmart** [comment]
Thank you! I was able to make it pass. Thanks for all the help!
