### ISSUE TITLE
init script user_data issue

### ISSUE THREAD

**Issue by Vittly** [aws/aws-sdk-ruby#191]
Hello! I have run

ec2.client.request_spot_instances(
      :spot_price => '12', # $12
      :launch_specification => {
        :image_id => 'ami-1234,
        :key_name => 'abcd,
        :instance_type => 'c1.xlarge',
        :user_data =>
          <<-eos
          #!/bin/bash
          echo "`whoami` in `pwd`" >/tmp/loglog
          reboot
          eos
      }

and got state "failed" with "State Reason: Invalid BASE64 encoding of user data (400 response code)". If I write

:user_data => Base64.encode64(
          <<-eos
          #!/bin/bash
          echo "`whoami` in `pwd`" >/tmp/loglog
          reboot
          eos
)

I got empty /tmp/loglog and a message in /var/log/syslog about skipping user_data due to lack of "#!" at begin.

And there is no way in API to attach file-user-data. How should I use user_data for init scripts?

**Comment by chinshr** [comment]
So is this the correct way of doing it?

```ruby
ec2.instances.create(
:image_id => 'ami-1234',
:key_name => 'abcd',
:instance_type => 'm1.xlarge',
:user_data =>
<<-eos
#!/bin/bash
echo "whoami in pwd" >/tmp/loglog
reboot
eos
)
```
