### ISSUE TITLE
Feature request: Add Aws::S3::Object#head method

### ISSUE THREAD

**Issue by janko** [aws/aws-sdk-ruby#1912]
There is `Object#get`, `Object#put`, `Object#delete`, but no `Object#head` in `Aws::S3`. I think it would be a nice symmetry to add `Object#head`. Currently one has to call `Client#head_object`

```rb
client.head_object(
   bucket: "my-bucket",
   key: "my-key",
)
```

which repeats `:bucket` and `:key` parameters that could otherwise be inferred from the `Aws::S3::Object` object.

**Comment by srchase** [comment]
@janko-m,

The ```Aws::S3::Object#data``` will return the equivalent head of that object.

```
obj = Aws::S3::Object.new(bucket_name: 'foo', key: 'bar')
obj.data_loaded? # => false
obj.data # =>  #<struct Aws::S3::Types::HeadObjectOutput... with all read attributes of object
obj.data_loaded? # => true (following last obj.data call which required loading data)
obj.load # => reloads data, via head object call.
```

**Comment by janko-m** [comment]
It would also be useful if `Object#load` accepted additional options for `#head_object`.

**Comment by srchase** [comment]
Tracking as a feature request: [FEATURE_REQUESTS](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md)

**Comment by mullermp** [comment]
I'm not sure how relevant this feature request still is. It definitely dropped off our radar. But I think this would be easy to add.

The definition would be:

```
        "Head": {
          "request": {
            "operation": "HeadObject",
            "params": [
              { "target": "Bucket", "source": "identifier", "name": "BucketName" },
              { "target": "Key", "source": "identifier", "name": "Key" }
            ]
          }
        }
```

**Comment by mullermp** [comment]
This was added on March 24 - https://github.com/aws/aws-sdk-ruby/commit/45499f3876e02a3ad169d7730ad09d6564c6cc56#diff-5df294fbe99ec78b537fc91be8c3d04b866c530627c9ef2ff56b2330b7c6fbef

I forgot to close this!
