### ISSUE TITLE
Feature request: Retrieving data from response headers when streaming S3 objects

### ISSUE THREAD

**Issue by janko** [aws/aws-sdk-ruby#1913]
In my open source project I'm using `Aws::S3::Object#get` with a block to stream the S3 object on-demand:

```rb
chunks = object.enum_for(:get, **options)
chunks #=> #<Enumerator>
chunks.next # first chunk of data
chunks.next # next chunk of data
```

I'm wrapping this functionality into a custom IO-like object, so that people can stream using the `IO#read` semantics, which under the hood retrieves subsequent chunks of data when needed.

I'd like the content length to be known at the start of streaming, which would be returned when the user called `#size`. Currently I have to make an additional `#head_object` request to retrieve `Aws::S3::Object#content_length`. However, the `#get_object` request that `Object#get` makes already retrieves response headers before it starts streaming, which I think hold all the same information that response headers for a `#head_object` call would hold.

So, it would be convenient if `Object#content_length`, `#content_type` and other data was filled in on `Object#get` as soon as the response headers are received (before the response body is read). That way I could avoid the additional HEAD request to S3 for this use case, to retrieve data that we technically already have, but which can only be retrieved once the whole S3 object has been downloaded.

In code, I would like this behaviour:

```rb
object.get do |chunk|
  # this currently makes an additional HEAD request, but doesn't have to,
  # because it could fill this info in from the response headers of the
  # `#get_object` call that we already retrieved at this point
  object.content_length
end
```

I think it should be possible to somehow use the notification about response headers that Seahorse transmits: https://github.com/aws/aws-sdk-ruby/blob/e5ef6389dcf36ff23586f5891b0914458a50c5c7/gems/aws-sdk-core/lib/seahorse/client/net_http/handler.rb#L80

**Comment by srchase** [comment]
Tracking as a feature request: [FEATURE_REQUESTS](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md)

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.

**Comment by janko** [comment]
Thanks. FWIW, I've recently managed to get the desired behaviour with the following hack:

```rb
req = client.build_request(:get_object, **params, bucket: bucket.name, key: object.key)

body = req.enum_for(:send_request)
body.peek # start the request

content_length = Integer(req.context.http_response.headers["Content-Length"])
chunks         = Enumerator.new { |y| loop { y << body.next } }
```

**Comment by alextwoods** [comment]
I've been looking into how we might generically achieve this for streaming methods.  One option I see is to add an additional, optional parameter to the Proc that is being called which provides the headers, eg:

```ruby
client.get_object(bucket: bucket_name, key: key) do |chunk, headers|
  content_length = Integer(headers['content-length'])
  # do something with chunk
end
```

You  mention that you're wrapping this into a custom IO like object to provide `IO#read` - another option could be adding this behavior to the SDK (possibly as a third type of response_target) as it sounds like this could be useful for our users.
