### ISSUE TITLE
Regression: aws-sdk-* gems 1.56.0 → 1.57.0 have broken gem dependencies

### ISSUE THREAD

**Issue by valscion** [aws/aws-sdk-ruby#1917]
Please fill out the sections below to help us address your issue

### Issue description

Upgrading from `aws-sdk-ec2` v1.56.0 to v1.57.0 has errors due to bad dependency constraints.

```
bundle exec rake db:setup --trace
```

```
rake aborted!
LoadError: cannot load such file -- aws-sdk-core/plugins/endpoint_discovery.rb
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `block in require'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.7/lib/active_support/dependencies.rb:293:in `require'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/aws-sdk-ec2-1.57.0/lib/aws-sdk-ec2/client.rb:18:in `<top (required)>'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/aws-sdk-ec2-1.57.0/lib/aws-sdk-ec2.rb:13:in `require_relative'
/home/circleci/venuu/vendor/bundle/ruby/2.5.0/gems/aws-sdk-ec2-1.57.0/lib/aws-sdk-ec2.rb:13:in `<top (required)>'
```

It seems like https://github.com/aws/aws-sdk-ruby/pull/1901 would've required the `aws-sdk-ec2` gem to bump its dependency constraint on `aws-sdk-core` to `>= 3.37.0`. Currently the gemspec constraint is this:

https://github.com/aws/aws-sdk-ruby/blob/2a912680f8d3a1e6266fd7179980e0f643b61353/gems/aws-sdk-ec2/aws-sdk-ec2.gemspec#L27

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-X` related part from our `Gemfile.lock`:

```
    aws-eventstream (1.0.1)
    aws-partitions (1.102.0)
    aws-sdk-core (3.27.0)
      aws-eventstream (~> 1.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-ec2 (1.57.0)
      aws-sdk-core (~> 3, >= 3.26.0)
      aws-sigv4 (~> 1.0)
    aws-sdk-elasticloadbalancing (1.7.0)
      aws-sdk-core (~> 3, >= 3.26.0)
      aws-sigv4 (~> 1.0)
    aws-sdk-kms (1.11.0)
      aws-sdk-core (~> 3, >= 3.26.0)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.23.1)
      aws-sdk-core (~> 3, >= 3.26.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.3)
```

### Version of Ruby, OS environment

Ruby 2.5.3, running in CI as an automated dependency bump in a dockerized Debian-based container.

### Code snippets / steps to reproduce

Install `aws-sdk-ec2` v1.57.0 with the lowest allowed `aws-sdk-core` gem version (v3.27.0) and require `aws-sdk-ec2`

**Comment by awood45** [comment]
Thanks for reporting this. Will check scope (I would wager this is not the only impacted gem) and push out a fix.

**Comment by valscion** [comment]
Thanks for the quick reply. I also think this might unfortunately impact more gems

**Comment by valscion** [comment]
Also happening with `aws-sdk-rds` v1.38.0: https://github.com/aws/aws-sdk-ruby/issues/1918

**Comment by awood45** [comment]
First is the mitigation, which is also going to be the fix: If you're broken by this, upgrade your version of `aws-sdk-core` to at least `3.37.0`. That will unblock you. I'm going to be submitting a build fix which will update all `.gemspec` files to have that dependency scheme.

I'll then work on an emergency release to update any gems that have released since that time.

**Comment by awood45** [comment]
https://github.com/aws/aws-sdk-ruby/commit/695ecc61b398066d7e165ec5a2f1d0557282429d will fix this, going to trigger a build soon. 33 gems were impacted in total.

**Comment by awood45** [comment]
Release is in progress. If you are using an affected gem, you should be able to upgrade in less than an hour (though if you're reading this, you could work around it right now by updating core, so do that first, but this won't recur at least).

**Comment by awood45** [comment]
Releases of the affected gems are complete. You should no longer see issues after upgrading to the latest service gems - please re-open with the affected versions if you do.
