### ISSUE TITLE
Calls to RDSDataService client.execute_sql always throw an "invalid cluster id" exception

### ISSUE THREAD

**Issue by coreyaus** [aws/aws-sdk-ruby#1922]
### Issue description

I am attempting to execute an SQL statement on my RDS instance (Postgres) but I'm constantly seeing an "invalid cluster id" exception. Specifically I am following the instructions in this section of the documentation: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDSDataService/Client.html#execute_sql-instance_method. I am passing the correct ARN for my RDS instance in the parameter named `db_cluster_or_instance_arn`. This RDS instance is not in a cluster (i.e. `db_cluster_identifier` is nil when looking up this database using the `aws-sdk-rds` service gem).

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

- aws-sdk-rdsdataservice

### Version of Ruby, OS environment

- ruby 2.5.1p57
- macOS Mojave (v 10.14.1)

### Code snippets / steps to reproduce

I am retrieving the `aws_secret_arn` using the `get_secret` provided through the AWS console. I have tried setting the `db_cluster_or_instance_arn` option as a hardcoded string, and also by dynamically retrieving the `db_instance_arn` - the latter version is shown below (there is only 1 RDS instance in the AWS account I'm using, hence the use of `first` in the code below):

```
rds = Aws::RDS::Resource.new(region: 'us-east-1')
params = {
  aws_secret_store_arn: aws_secret_arn,
  database: "DB_NAME",
  db_cluster_or_instance_arn: rds.db_instances.first.db_instance_arn,
  sql_statements: "MY SQL STATEMENTS"
}
client = Aws::RDSDataService::Client.new(region: 'us-east-1')
res = client.execute_sql(params)
```

I have also tried passing an ExecuteSqlRequest object to execute_sql:
```
request = Aws::RDSDataService::Types::ExecuteSqlRequest.new(params)
client = Aws::RDSDataService::Client.new(region: 'us-east-1')
res = client.execute_sql(request)
```

Every variation I have tried has triggered an `Aws::RDSDataService::Errors::BadRequestException` with the "invalid cluster id" error message mentioned above. However, the ARN is definitely correct for the target RDS instance.

Thanks in advance for your help!

**Comment by srchase** [comment]
@coreyaus 

Thanks for opening this issue.

How are you configuring your Secret?  As an RDS Database? Or a generic Database?

**Comment by coreyaus** [comment]
Hey mate,

I originally created that secret using the "Credentials for RDS database" option, and entering the master username and password. As a test, I just tried creating a new secret with the "Credentials for other database" option and manually entering the DB details - however, I didn't have any success when running `client.execute_sql` with that new secret either. Let me know if there are any other tests you'd like me to try to help isolate the issue 👍 

Thanks for your help!

**Comment by srchase** [comment]
@coreyaus 

The Service Team has indicated that only Aurora Clusters and Serverless Aurora types are supported at this time.

Are you using an Aurora?

**Comment by srchase** [comment]
Please refer to this documentation:

[https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)

Note that the Data API is in beta for Aurora Serverless and is subject to change.

**Comment by coreyaus** [comment]
Thanks mate,

My RDS instance is running Postgres. I see there was also some confusion about this from others in the issue you referenced above: https://github.com/aws/aws-sdk-js/issues/2376. It could be worth updating the docs to make it clear which endpoints are limited by DB type. For example, there is no mention of any limitations here: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDSDataService.html. Anyway, just food for thought as the team works through the beta 👍Is the general plan to support all DB types in the long-run?

Cheers!

**Comment by srchase** [comment]
@coreyaus 

Check with the [AWS Developer Forums for RDS](https://forums.aws.amazon.com/forum.jspa?forumID=60).   That team would be better equipped to answer questions regarding their plans for the Data API.

I've opened a request with the Service Team to update the documentation to reflect which DB Types are supported and to make clear the limitations of the Data API at this point.

Since that needs handled on their end, I'm going to close this issue for now.   Appreciate you raising this issue and your feedback.

**Comment by markwinap** [comment]
Still no support for Postgres :(

**Comment by omarelsaid** [comment]
Any idea when this will be supported for MySQL? I would really like to use this for querying and obtaining data from a lambda function rather than using the boto3 rds client to establish a connection myself :)

**Comment by rahul-satal** [comment]
I am still getting the same error with MySQL - https://stackoverflow.com/questions/58376371/unable-to-run-sql-query-on-aws-rds-using-golang-sdk
