### ISSUE TITLE
CostExplorer granularity lists HOURLY support but does not work

### ISSUE THREAD

**Issue by mheffner** [aws/aws-sdk-ruby#1923]
### Issue description

The recently updated [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CostExplorer/Client.html#get_reservation_utilization-instance_method) for `CE::get_reservation_utilization` mentions that the `granularity` parameter accepts `DAILY, MONTHLY, HOURLY`. However, when testing with `HOURLY` it throws an error:

```
.bundle/gems/ruby/2.4.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Granularity should be either 'MONTHLY' or 'DAILY' (Aws::CostExplorer::Errors::ValidationException)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-costexplorer

### Version of Ruby, OS environment

1.14.0

### Code snippets / steps to reproduce

Call `get_reservation_utilization` with `granularity: 'HOURLY'` like:

```
  params = {
      time_period: {
          :start => time_period[0],
          :end => time_period[1]
      },
      granularity: 'HOURLY',
      filter: {
          dimensions: {
              key: 'SERVICE',
              values: ['Amazon Elastic Compute Cloud - Compute']
          }
      }
  }

  resp = costexplorer.get_reservation_utilization(params)
```

**Comment by srchase** [comment]
@mheffner 

Thanks for opening this issue.

The [API Reference](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ce-api.html) for the CostExplorer indicates that only MONTHLY and DAILY are supported for Granularity on GetCostAndUsage, GetReservationUtilization and GetReservationCoverage.

I'll followup with the Service Team to get this discrepancy resolved.

**Comment by srchase** [comment]
@mheffner 

The Service Team confirmed that HOURLY granularity is not supported at this time.

They are working to update the resource model, which will trigger an update on the SDK that will correct the documentation.

**Comment by srchase** [comment]
Closing this issue.  The Service Team is tracking resolving this issue on their end.
