### ISSUE TITLE
Can I rename an s3 folder and contents?

### ISSUE THREAD

**Issue by peterwake** [aws/aws-sdk-ruby#1933]
I am representing a standard folder and file structure in AWS S3. One action that users can do is rename a folder. At the moment we have to use `move_to` to move all the keys that match the prepended files:

`objects = client.list_objects_v2(bucket: bucket_name, prefix: old_key)`

.. for each object ..

`object.move_to(bucket: bucket_name, key: new_sub_key, multipart_copy: true)`

However we have found this to be slow. We introduced threading to accelerate this but my concern is that this might download a lot of data onto our server if the files involved are large.

I found a recursive move in the AWS CLI code

`aws s3 --recursive --debug mv s3://my-bucket/old-folder/ s3://my-bucket/new-folder/`

Which has got threading, multipart and all kinds of good stuff in it.

Any way of calling this via the Ruby SDK? Or can I do a low level call using the Ruby SDK to access this somehow, and if so, what would it be?  

Any help / suggestions much appreciated.

Gem name: aws-sdk-s3
Ruby version: 2.3.7

**Comment by srchase** [comment]
@peterwake 

Thanks for opening this issue.

The ```move_to``` operation does not download the data to your server.  That operation uses S3's [PUT Object - Copy](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html), or [Upload Part - Copy](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html) when multipart_copy is enabled, to copy the object within S3.  The body of the object is not actually downloaded.

The AWS CLI command you're invoking is less low-level.  It's using the same underlying S3 operations, but is doing more to abstract and actively manage moving (copying and deleting) objects from one folder to another.

You can add the ```http_wire_trace: true``` option when initializing your object (or S3 client) to see the underlying calls that are being made to S3.  That could help you compare what's happening with the AWS CLI vs the Ruby SDK.

**Comment by peterwake** [comment]
@srchase

Hi Chase,

Thanks for the quick response, and it's great to know that the `move_to` operation doesn't download data to our server. The `http_wire_trace: true` option isn't something I knew about.

Do you have any advice on a sensible number of concurrent threads to run to do the moves? And is the `multipart_copy: true` bit important?

I will create a gist at some point with the code we end up with.

Best regards,
Peter

**Comment by srchase** [comment]
@peterwake 

Using ```multipart_copy``` is required for objects 5GB and larger.  For files less than 5GB, you can do the move with one operation, but you could also test using ```multipart_copy``` and vary the ```chunk_size```.   The [AWS Developer Forum for S3](https://forums.aws.amazon.com/forum.jspa?forumID=24) may be able to provide better guidance on the right number of threads for moving multiple objects.

**Comment by srchase** [comment]
@peterwake 

I'm going to close this issue.  Let us know if there's anything further.

**Comment by peterwake** [comment]
Hi @srchase no problem. For anyone else hitting this issue I created a gist at https://gist.github.com/peterwake/49a829d2062ad3c5962435341692a680. 25 concurrent threads seemed to be the point where adding more threads didn't seem to make a tangible performance increase.

**Comment by srchase** [comment]
Thanks @peterwake!

Helpful gist and information for anyone else attempting to do the same thing.
