### ISSUE TITLE
stub_responses not stubbing

### ISSUE THREAD

**Issue by dudo** [aws/aws-sdk-ruby#1935]
Please fill out the sections below to help us address your issue

### Issue description
Use of `stub_responses` raises invalid token error.
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
gem 'aws-sdk-sqs' version 1.10.0
### Version of Ruby, OS environment
 Ruby 2.5.3, OS X
### Code snippets / steps to reproduce

    $ moto_server sqs -p 4000 -H localhost
     * Running on http://localhost:4000/ (Press CTRL+C to quit)

    options = { access_key_id: '',
      secret_access_key: '',
      region: us-west-2,
      endpoint: http://localhost:4000,
      verify_checksums: false,
      stub_responses: true }

    > sqs = Aws::SQS::Client.new(options)
    => #<Aws::SQS::Client>
    > sqs.get_queue_url(queue_name: 'q').queue_url
    Aws::SQS::Errors::InvalidClientTokenId: The security token included in the request is invalid.

**Comment by srchase** [comment]
@dudo 

Can you provide an example of how you are stubbing ```get_queue_url```?

Are you doing something like this:

```
sqs.stub_responses(:get_queue_url, { queue_url: 'foo' })
```

**Comment by dudo** [comment]
If it helps, I think I'm moving in the right direction.

    Aws::SQS::Client.new(**Rails.application.config.sqs.symbolize_keys)

2 things, I didn't expect:
- Giving the constructor a hash did not behave as expected - the double splat took care of that
- The constructor needs symbolized keys. The prior expectation explains why, honestly - you're using keyword arguments. An options hash could make this a bit more flexible.

Maybe you can hold my hand a bit here, though (please)

```
# frozen_string_literal: true

module Sqs
  class Base
    attr_reader :client

    QUEUE_NAME = 'undefined'

    def initialize
      Aws.config[:credentials] = Aws::Credentials.new('', '') unless Rails.env.production?
      @client = Aws::SQS::Client.new(**Rails.application.config.sqs.symbolize_keys)
    end

    def queue_url
      @queue_url ||= client.get_queue_url(queue_name: self.class::QUEUE_NAME).queue_url
    end

    def messages
      client.receive_message(
        queue_url: queue_url,
        message_attribute_names: ['All'], # Receive all custom attributes
        max_number_of_messages: 10, # 10 is the maximum number allowed by SQS
        wait_time_seconds: 0 # Do not wait to check for the message
      ).messages
    end

    def process_message(message)
      # message.body
      # message.message_attributes
    end

    def delete_message(message)
      client.delete_message(
        queue_url: queue_url,
        receipt_handle: message.receipt_handle
      )
    end
  end
end
```

With that very lightweight wrapper, I'm getting closer to my expectations:

    > sqs = Sqs::Base.new
    => #<Sqs::Base:0x00007f9413d89858 @client=#<Aws::SQS::Client>>
    > sqs.queue_url
    => "String"
    > sqs.messages
    ArgumentError: invalid endpoint, expected URI::HTTP, URI::HTTPS, or nil, got #<URI::Generic String>

Any help to get me over the hump of using this for basic calls is appreciated =)

**Comment by srchase** [comment]
@dudo 

Have you referred to this blog post on [Advanced client stubbing](https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/)?

That might give you a few patterns to use.

**Comment by dudo** [comment]
That helps. Thanks!
