### ISSUE TITLE
`Aws::DynamoDB::AttributeValue::Unmarshaler#format` failed when type is `s` or `ns` in Ruby 2.6

### ISSUE THREAD

**Issue by totem3** [aws/aws-sdk-ruby#1936]
### Issue description

In Ruby 2.6 `Aws::DynamoDB::AttributeValue::Unmarsha#format` failed when type is `s` or `ns`, since `BigDecimal.new` is removed.

see [2.6.0-rc1 NEWS](https://github.com/ruby/ruby/blob/v2_6_0_rc1/NEWS) Stdlib compatibility issues section.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-dynamodb

### Version of Ruby, OS environment

* Version of Ruby: 2.6.0-rc1
* OS environment
  * System Version: macOS 10.13.6 (17G3025)
  * Kernel Version: Darwin 17.7.0

### Code snippets / steps to reproduce

1. switch your Ruby version to 2.6.0-rc1

2. run specs for aws-sdk-dynamodb

```
bundle exec rake test:spec:aws-sdk-dynamodb
```

specs fails by the following error.

```
     NoMethodError:
       undefined method `new' for BigDecimal:Class
```

**Comment by srchase** [comment]
Thanks for opening this issue.  We'll review your PR.
