### ISSUE TITLE
cross-region RDS snapshot copying gives PreSignedUrl authentication error

### ISSUE THREAD

**Issue by mnacos** [aws/aws-sdk-ruby#1943]
### Issue description

I'm trying to copy a RDS snapshot from 'eu-west-1' to 'eu-west-2', using this code:

````
    Aws::RDS::Client.new(region: 'eu-west-2').copy_db_snapshot(
      source_db_snapshot_identifier: 'arn:.... for-source-snapshot',
      source_region: 'eu-west-1',
      target_db_snapshot_identifier: 'just-a-snapshot-name',
      destination_region: 'eu-west-2',
      kms_key_id: kms_key_id
    )
````
This results in a PreSignedUrl unable to authenticate error. I've seen similar issues reported and fixed in other languages e.g. https://github.com/aws/aws-sdk-php/issues/1462

See below for gem version information.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

GEM

    aws-eventstream (1.0.1)
    aws-partitions (1.126.0)
    aws-sdk-core (3.44.1)
      aws-eventstream (~> 1.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-rds (1.42.0)
      aws-sdk-core (~> 3, >= 3.39.0)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.3)
    jmespath (1.4.0)

### Version of Ruby, OS environment

   ruby 2.5.1p57, linux

### Code snippets / steps to reproduce

````
    Aws::RDS::Client.new(region: 'eu-west-2').copy_db_snapshot(
      source_db_snapshot_identifier: 'arn:.... for-source-snapshot',
      source_region: 'eu-west-1',
      target_db_snapshot_identifier: 'just-a-snapshot-name',
      destination_region: 'eu-west-2',
      kms_key_id: 'a-key-id-in-eu-west-2-region'
    )
````

**Comment by srchase** [comment]
@mnacos 

Thanks for opening this issue.

I've been unable to reproduce this issue as described.

Do you get the same behavior using the CLI?

**Comment by srchase** [comment]
Opting to close this issue for inactivity.  We're happy to re-open when you can reengage.
