### ISSUE TITLE
SQS client is not properly applying custom test endpoint

### ISSUE THREAD

**Issue by nikriek** [aws/aws-sdk-ruby#1950]
### Issue description
We use the AWS SQS SDK as part of the [Shoryuken](https://github.com/phstc/shoryuken) gem. For our dockerized test and dev environment we used to modify the SQS endpoint to use a local SQS (see snippets) e.g. `http://sqs:4100`. This worked fine until Dec 28. Since then, the custom endpoint gets changed to something like `http://sqs.eu-central-1.sqs:4100`. We also noticed that the path name starts with two slashes (`//active_storage`). 

Thank you!

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3 1.10.0

### Version of Ruby, OS environment
Docker: ruby:2.5.3-alpine

### Code snippets / steps to reproduce
```
Aws::SQS::Client.new(region: ENV["AWS_REGION"],
                                      access_key_id: ENV["AWS_ACCESS_KEY_ID"],
                                      secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
                                      endpoint: ENV['LOCAL_SQS_ENDPOINT'],
                                      verify_checksums: false)
```

**Comment by srchase** [comment]
@nikriek 

Was 'aws-sdk-s3 1.10.0' meant to be 'aws-sdk-sqs 1.10.0'?

Are you using a specific version of aws-sdk-core?

**Comment by nikriek** [comment]
Yes, aws-sdk-sqs 1.10.0 with aws-sdk-core 3.44.1.

**Comment by srchase** [comment]
@nikriek 

Thanks for following up.

I wasn't able to reproduce this issue using the SDK directly.   Are there any additional details that might help with a reliable repro?  Is there anything out of the ordinary going on with ENV?

**Comment by nikriek** [comment]
I used this https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server as a reference. The endpoint is passed using an ENV variable.

**Comment by nikriek** [comment]
I also wonder why it happened so randomly from one day to another. All dependency versions are locked.

**Comment by nikriek** [comment]
It is actually an issue with the docker dependency: https://github.com/p4tin/goaws/issues/187. I downgraded to an older version and it works now. Calling the mock server still works, but the `list_queues` endpoint was returning wrong urls.

**Comment by srchase** [comment]
@nikriek 

Thanks for following up with how you got this resolved.

**Comment by ramytamer** [comment]
@nikriek How did you solve this issue? I can't get `shoryuken sqs ls` to work on the defined endpoint in the initializer and I have to use the `--endpoint` I use a `shoryuken sqs` command; but when I start the `shoryuken -R -q queue-name` it uses the defined endpoint without any issue.

**Comment by ramytamer** [comment]
I just figured it out from the codebase [here](https://github.com/phstc/shoryuken/blob/master/bin/cli/sqs.rb#L8), looks like it's looking for an env var called `SHORYUKEN_SQS_ENDPOINT`; I just added this env to my docker container and it worked like a charm.
