### ISSUE TITLE
delete_stack returning the class INSTEAD of an instance of EmptyStruct

### ISSUE THREAD

**Issue by josvazg** [aws/aws-sdk-ruby#1955]
Please fill out the sections below to help us address your issue

### Issue description
When calling `.to_h` on the result from a `delete_stack`invocation, we get the following error:

```
ERROR -- : Something went wrong: NoMethodError undefined method `to_h' for Aws::EmptyStructure:Class
Did you mean?  to_s
ERROR -- :   .../gems/aws-sdk-core-3.44.1/lib/aws-sdk-core/pageable_response.rb:143:in `to_h'
```

The problem seems to be that **we got the EmptyStructure class object instead of the instance object**.

This workaround (where `r` is the result from `delete_stack`) seems to be doing the trick for us for now:
```
        r =
          if r.respond_to?(:data) && r.data == Aws::EmptyStructure
            ::Aws::EmptyStructure.new
          else
            r
          end

        r.respond_to?(:to_h) ? r.to_h : r
```

**Comment by awood45** [comment]
Given that the response to that API call is effectively an empty response, I don't think the class selection for the response is wrong, but I do think it's reasonable that the Aws::EmptyStructure class should respond to `#to_h`, even if the result would just be `{}`.

Is it your standard practice to call `#to_h` on all your service responses?

**Comment by awood45** [comment]
s/`Seahorse::Client::Response`/`Aws::EmptyStructure` on that last thought.

**Comment by josvazg** [comment]
Sorry but I still think this qualifies as a bug. The response we get is not directly the EmptyStructure class but a `PageableResponse`. Such response implements `to_h` this way:
https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/gems/aws-sdk-core/lib/aws-sdk-core/pageable_response.rb#L142-L144
```
  def to_h
    data.to_h
  end
```
^ Which means that `data` **must** implement `to_h`.

**Comment by awood45** [comment]
I'm able to see what you're saying here, looking at this as a bug.

**Comment by awood45** [comment]
Going to merge this in after we confirm tests are working.

**Comment by awood45** [comment]
This will go out with the next SDK release.
