### ISSUE TITLE
With which versions of Ruby is  aws-sdk-sqs compatible?

### ISSUE THREAD

**Issue by invader-move** [aws/aws-sdk-ruby#1959]
Hi

I need to know if aws-sdk-sqs is compatible with Ruby 2.6 ? and 2.5.1 ?

Thanks !

**Comment by invader-move** [comment]
Update : it's working with 2.6 (i make a little test)

**Comment by srchase** [comment]
https://github.com/aws/aws-sdk-ruby/pull/1960

We're getting 2.6 added to Travis CI.

**Comment by invader-move** [comment]
Thank you !
