### ISSUE TITLE
file integrity verification?

### ISSUE THREAD

**Issue by directionless** [aws/aws-sdk-ruby#196]
I'm not sure that this is the right place for this bug/FR, but I'd really like to verify the integrity of files I've uploaded to s3. I used to be able to do this by comparing the md5 checksum to the etag. But, this doesn't work with multipart uploads.

I could, of course, download the file and compare. But that's a bit painful for large files.

Is there a way to generate the multipart etag from the local file? Or some other way to verify the remote integrity?

**Comment by jkburges** [comment]
> The v2 SDK computes the Content-MD5 header by default on upload for calls to #put_object and #upload_part

What about [AWS::S3::Object#file_upload](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#upload_file-instance_method)?  Presumably this is just a convenience over `#put_object`, but I got lost in the code trying to confirm this.

**Comment by awood45** [comment]
Yes, you're correct that it's built on top of `#put_object` in the same manner.

**Comment by SGospodinov** [comment]
Hello, can someone please tell me with the what is expected behaviour if aws does not receive expected checksum. I mean is there is some kind which will be raised or how I can handle such a behaviour?
