### ISSUE TITLE
Custom headers provided to the sign_request method are not present in the signed output headers

### ISSUE THREAD

**Issue by JAndritsch** [aws/aws-sdk-ruby#1961]
### Issue description

The request headers provided to `Aws::Sigv4#sign_request` are not retained in the signed output headers. When a user supplies the request object and headers to this method, they get back a `Signature` object that has the correct `authorization` header, but lacks any of the custom headers that were part of the provided request.

You can see that the canonical request includes those custom headers in the "signed headers" section, but again those headers are not retained in the output headers that include authorization.

This means if the user issues a request with only the headers found in the output hash, they'll get a signature mismatch because the custom headers they provided were not present. A workaround would be to manually re-add those headers back into the returned `Signature` before executing a request.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sigv4 1.0.3

### Version of Ruby, OS environment

This is not a Ruby/OS specific issue.

### Code snippets / steps to reproduce

```ruby
signature = Signer.new(options).sign_request(
  http_method: 'PUT',
  url: 'https://domain.com',
  headers: {
    'Foo' => 'foo',
    'Bar' => 'bar  bar',
    'Bar2' => '"bar  bar"',
    'Content-Length' => 9,
    'X-Amz-Date' => '20120101T112233Z',
  }
)
# this fails
expect(signature.headers['foo']).to eq('foo')
```

**Comment by srchase** [comment]
Thanks for submitting this issue and PR.  We're reviewing.

**Comment by cjyclaire** [comment]
Thanks again for the PR, we did have commented on that one.
Is this still persist to be an issue for you? happy to review on the PR and make progress there together.

Currently tagging closing soon if no response

**Comment by mullermp** [comment]
Closing as we have not heard back. Reopen if needed!
