### ISSUE TITLE
Passing in a closed `Tempfile` to `Aws::S3::FileUploader#upload` raises

### ISSUE THREAD

**Issue by ice799** [aws/aws-sdk-ruby#1967]
### Issue description

`Aws::S3::FileUploader#upload` does not properly handle closed a closed `Tempfile`. I triggered this issue by passing a closed `Tempfile` to `Aws::S3::Object#upload_file`. Read the section below for more details.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 1.30.1

### Version of Ruby, OS environment

Ubuntu Linux, ruby 2.4.5p335

### Code snippets / steps to reproduce

The issue is a bit tricky and may actually be a bug in the Ruby VM itself, but should be relatively easy to work around in the S3 gem.

Before diving into the S3 gem itself, please note this behavior from Ruby:

```
[25] pry(main)> n=Tempfile.new('hi'); n.write('hi'); n.close; n.size
=> 2
[26] pry(main)> File.size(n)
IOError: closed stream
from (pry):26:in `size'
```

In other words: `Tempfile#size` works fine, but `File.size` raises. Why this happens is a bit tricky and may be a bug in the Ruby VM.

The issue is that internally in the Ruby VM a call to `File.size` will check if the file is open and raise if it is not. 

See the following pieces of code:
1.  First, the call to `File.size` (which calls `rb_stat`): https://github.com/ruby/ruby/blob/ruby_2_4/file.c#L1953-L1973
2.  Next, the call to `rb_stat` (which calls `GetOpenFile`): https://github.com/ruby/ruby/blob/ruby_2_4/file.c#L1007-L1022
3.  Next, the call to `GetOpenFile` (which calls `rb_io_check_closed`): https://github.com/ruby/ruby/blob/ruby_2_4/include/ruby/io.h#L120
4.  Finally the code in `rb_io_check_closed` which triggers the raise: https://github.com/ruby/ruby/blob/ruby_2_4/io.c#L638-L645

In contrast, the `Tempfile#size` method itself will first check if the file is open or closed and avoid the raise in `File.size` by passing in the `Tempfile#path` to `File.size` instead. See this code from `Tempfile#size`: https://github.com/ruby/ruby/blob/ruby_2_4/lib/tempfile.rb#L224-L232

Compare that code to the code in `Aws::S3::FileUploader`: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/file_uploader.rb#L26-L36

`Aws::S3::FileUploader#upload` triggers the raise because it does not do the same check that `Tempfile#size` is doing.

My suggestion on how to resolve this would be one of the following:
1.  If this behavior is desired, update the comment to indicate that only an open `Tempfile` can be passed to `upload_file`, or
2.  Update the code so that `Tempfile#size` is called in `Aws::S3::FileUploader#upload` which avoids this issue entirely

**Comment by srchase** [comment]
@ice799 

Thanks for raising this issue.

Are you interested in submitting a PR for this?

**Comment by ice799** [comment]
@srchase 

If that is the desired use case, may I suggest option 1 from my list above to modify the comments/documentation for `upload_file`?

The documentation here: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method generated from here https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/file_uploader.rb#L26 indicates that `upload_file` can accept a `Tempfile`.

If `upload_file` should only be given and/or only expects a path, I would suggest updating the documentation to clear that up for users.

**Comment by ice799** [comment]
@srchase 

The same comment appears in a few other places, all of which would need to be updated if all of these intend to only take a path:

1. https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb#L35-L48
2. https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/file_part.rb#L9
3. https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/file_uploader.rb#L26

Possibly others, as well.

**Comment by srchase** [comment]
@ice799 

Have you referred to this documentation? [upload_file](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method)

>  Parameters: source (String, Pathname, File, Tempfile) — A file or path to a file on the local file system that should be uploaded to this object. If you pass an open file object, then it is your responsibility to close the file object once the upload completes.

That line in the documentation is generated from this line: https://github.com/aws/aws-sdk-ruby/blob/708140b8f5777e05ec8acaaad7059a711e8b13e4/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L287

**Comment by ice799** [comment]
@srchase Up to you; I don't find the existing documentation to be sufficiently clear. It sounds like you might agree since we were both confused as to what this method expects (just a path vs a path or a File or Tempfile object that must not be closed) and what state the expected objects should be in, additional documentation can be added to make this more clear to all affected methods.

I would propose two paths forward here:

1.  If `upload_file` intends to take only a path as you mentioned [here](https://github.com/aws/aws-sdk-ruby/issues/1967#issuecomment-457786349) the documentation should be updated throughout to make this clear, and the method should raise an exception if something that isn't a `String` is passed in. This will break the API though and is probably not the best choice.
2. Or, if `upload_file` intends to take a path, `File`, or `Tempfile` (so long as neither the `File` or `Tempfile` objects are closed) the documentation should be updated to make this explicitly clear for all methods and an exception should be raised if the object is not in the correct state when passed in.

**Comment by mullermp** [comment]
Hi Joe - thanks for all the information. What do you think about an option 3)? I think that we could support adding a closed Tempfile. My thought is that if any temp file is provided, I could just get the path from it. Then `File.size(source)` will always be checking a tempfile's path. This would also mean the temp file is reopened. Is it best practice to have closed Tempfiles or to rewind an open one?

**Comment by mullermp** [comment]
I've decided to just update the documentation. Per my testing, open Tempfile and File objects (both small and large) will work correctly. Closed objects will continue raise IO errors.
