### ISSUE TITLE
Feature request: Adding warning or exception when user sets endpoint setting attribute to 'https://s3-%{ REGION }.amazonaws.com'

### ISSUE THREAD

**Issue by w00lf** [aws/aws-sdk-ruby#1968]
### Issue description
When a user sets `endpoint` settings attribute in value 'https://s3-%{ REGION }.amazonaws.com' the `region` setting is ignored and automatically set to `REGION` part of the url, because of that, the user can encounter hard to debug errors which is hard to pinpoint if you don't know this behavior. As i understand this is intentional as i have found specs for it in https://github.com/aws/aws-sdk-ruby/blob/783d5998914e5abedfcb952f751c60e1cc0c3bae/gems/aws-sdk-core/spec/aws/plugins/region_endpoint_spec.rb, but i think it will be better to show the user some warning message or event throw an exception so that he knows that this happened. 

### Gem name 
aws-sdk, 2.5.11

### Version of Ruby, OS environment
2.5.3, MacOs High Sierra

### Code snippets / steps to reproduce
```ruby
Aws.config.update({
  region: 'us-west-2',
  endpoint: 'https://s3-us-east-1.amazonaws.com'
})
```
This code will lead to situation when all requests to aws will be with `region` param seted to 'us-east-1' instead of 'us-west-2'

**Comment by srchase** [comment]
@w00lf 

Thanks for this feature-request and feedback.  We'll review and see if we can improve this area.

**Comment by mullermp** [comment]
Sorry for the delay on this - I looked into this and it appears the endpoint doesn't override the region at all. With or without the endpoint, a region must be provided. With an endpoint, the region would be used for signing, but if the endpoint is not in the same region, that could fail. We generally don't recommend using endpoint options unless you have to (for testing as an example). The SDK will generate the endpoint for you based on the region.
