### ISSUE TITLE
README: Clarify gem version tilde constraints (~>)

### ISSUE THREAD

**Issue by ms-ati** [aws/aws-sdk-ruby#1969]
Please fill out the sections below to help us address your issue

### Issue description

In `README.md`, the advice and examples for adding these gems to a `Gemfile` are using the [Rubygems tilde operator ~>](https://robots.thoughtbot.com/rubys-pessimistic-operator) followed by a single major version, e.g. `gem 'aws-sdk', '~> 3'`

Could a sentence be added to clarify the intent here, for example: "This will allow upgrading to the next major version whenever it is released"? Or, if that's not the intent, should this be changed to include a minor version as well, such as `'~> 3.1'`, and clarified as "This will allow upgrading to the next minor version (3.x) whenever it is released"?

It's also possible that I've completely misunderstood both the intent and how this operator works, so please clarify if so! :)

**Comment by srchase** [comment]
Hello @ms-ati,

Thanks for opening this issue.

The tilde operator sets the dependency to a major version, but will allow minor version upgrades.   It will not allow an upgrade to the next major version (in this case 4.0).

See this part of the [README](https://github.com/aws/aws-sdk-ruby#versioning):

> This project uses semantic versioning. You can safely express a dependency on a major version and expect all minor and patch versions to be backwards compatible.

Does that clarify the intent?

**Comment by ms-ati** [comment]
Ah -- yes thank you!

This is the context I was missing, which [did indeed surprise me](https://guides.rubygems.org/patterns/):

> It’s also important to know that if you specify a major version only, like this:
> ```
> # gemspec
> spec.add_runtime_dependency 'library', '~> 2'
> ```
> 
> It will only use the latest version from the 2.x series – so 2.3.0 – and not 3.0.0. This behaviour may surprise some people, but automatically allowing any major version past version 2 is more surprising behaviour.
