### ISSUE TITLE
API for getting COST of EC2 at an instance level

### ISSUE THREAD

**Issue by satyashanmuka** [aws/aws-sdk-ruby#1970]
Please fill out the sections below to help us address your issue

**Comment by srchase** [comment]
@satyashanmuka 

Thanks for submitting this issue.

You can use tagging to track resources at a more granular level.

Refer to this documentation on how that can be achieved: [Using Cost Allocation Tags](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html)

Once you've tagged resources, you can add ```tags``` to your ```get_cost_and_usage``` call to return only the cost and usage for the specific resource (a specific instance in your case).

**Comment by satyashanmuka** [comment]
@srchase Thanks for the quick response. 

So, if I add a user-defined tag for an EC2 instance like `instance_id:<instanceId of the instance which I assume is unique>`, the get_cost_and_usage call with the tag filter set will return cost only for the specific instance.

Is my understanding correct?

**Comment by srchase** [comment]
Yes, that is correct.

**Comment by satyashanmuka** [comment]
Able to add user-defined tags, but for them to show up in cost explorer dashboard, need to activate them as mentioned at https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html.

I don't have permission to do so, will get this done and test the scenario.

**Comment by srchase** [comment]
Good to hear.  I'll close out this issue as the SDK portion of this is working as intended.

If you end up having further questions, follow-up and we can re-open this issue if needed.
