### ISSUE TITLE
Aws::DynamoDB::Client documentation is outdated

### ISSUE THREAD

**Issue by postmodern** [aws/aws-sdk-ruby#1972]
### Summary

Documentation for many of the methods in [Aws::DynamoDB::Client](https://www.rubydoc.info/gems/aws-sdk-dynamodb/Aws/DynamoDB/Client#get_item-instance_method) do not match the current behavior. Mainly the examples which show how to specify attributes still use explicit type hints (ex: `foo: {s: "bar"}`), where as the current version of aws-sdk-dynamodb (1.20.0) will automatically infer the type of the data. Furthermore, if you specify the value of an attribute as `{type: value}` Hash, the library will raise a Schema Validation exception.

### Gem name

[aws-sdk-dynamodb](https://rubygems.org/gems/aws-sdk-dynamodb)

### Ruby Version

Ruby 2.3.8

### Steps to Reproduce

    require 'aws-sdk-dynamodb'
    client = Aws::DynamoDB::Client.new
    
    client.get_item(table_name: 'test', key: {Id: {s: 'test'}})
    # Aws::DynamoDB::Errors::ValidationException: The provided key element does not match the schema
    
    client.get_item(table_name: 'test', key: {Id: 'test'})
    # => #<struct Aws::DynamoDB::Types::GetItemOutput item={"Id"=>"test"} consumed_capacity=nil>

**Comment by awood45** [comment]
Definitely agree that the documentation example is not helpful, and I'm prioritizing a fix for this. The schema validation error is because  `{ s: 'test' }` is a valid DynamoDB value, it just so happens to be a hash which will be wrong for any key type.

In any case, totally agreed that this is an issue and unhelpful documentation.

**Comment by postmodern** [comment]
@awood45 if the solution is as simple as removing all `{s: ...}` examples from the documentation, I could submit a PR?

**Comment by awood45** [comment]
Unfortunately it is not quite that simple. The documentation files (and example files, the issue in this case) are autogenerated from a shared source. Simply put, the next release would overwrite such a change. I've taken on a work item in the next sprint to customize this example to fit the simple attributes behavior.

**Comment by awood45** [comment]
Leaving this issue open since I'd also like to fix these examples, but at minimum the broken examples are now removed. The "placeholder" examples are already correct.

**Comment by awood45** [comment]
This is now properly fixed. Examples should have been removed from the docs in today's release. The next release will restore the examples, this time in working form.

**Comment by postmodern** [comment]
:+1:
