### ISSUE TITLE
apply ruby bug fix to Net::HTTP patch

### ISSUE THREAD

**Issue by fledman** [aws/aws-sdk-ruby#1979]
### Issue description
[Ruby bug 12890](https://bugs.ruby-lang.org/issues/12890) fixes how `Net::HTTP` behaves for `1xx` status codes that are not exactly `100`. The change was merged in November 2016 for all rubies [>= 2.4](https://github.com/ruby/ruby/commit/8ec6fcb2f6cd9bc453173477eb237298a5e5bab5), and then backported for [2.2](https://github.com/ruby/ruby/commit/bb5114bc7e59c494af03f973ba89d7747325f371) and [2.3](https://github.com/ruby/ruby/commit/edf505a7e8d52970a2a1ae29ab450abf3819a63b).

Unfortunately, the bugfix was a one line change to the `#transport_request` method being patched by `Seahorse`. So users of `aws-sdk-core`with the patch (e.g. ruby < 2.5) still experience the bug.

I am hoping that you can apply the bug fix to the Ruby2 version of the patch.
e.g. change:
https://github.com/aws/aws-sdk-ruby/blob/e706839d56503436822246b804f5ec49715d9458/gems/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L33
to
```ruby
end while res.kind_of?(Net::HTTPInformation)
```

### Gem name
`aws-sdk-core`, all versions 

### Version of Ruby, OS environment
2 <= ruby < 2.5

**Comment by fledman** [comment]
additionally:

per #1167 the original purpose of the method patch was to fix:
1. streaming idempotent retry bug
2. yielding idempotent retry bug
3. original 100-continue bug

however, this line was later added:
https://github.com/aws/aws-sdk-ruby/blob/e706839d56503436822246b804f5ec49715d9458/gems/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L15

clearing the list of idempotent methods directly fixes 1 & 2 ; the method patch isn't doing anything because the `rewind` code is never reached.

furthermore, the fix for 3 was merged into core ruby >= 2.3: https://github.com/ruby/ruby/commit/f0002bd5a21bf091dfd0482fb7b0147b7d3703fb

so `2.5 > rubies >= 2.3` just need to clear `IDEMPOTENT_METHODS_`, they don't need the method patch

**Comment by fledman** [comment]
```diff
diff --git a/lib/seahorse/client/net_http/patches.rb b/lib/seahorse/client/net_http/patches.rb
index ca68e55..eccfcba 100644
--- a/lib/seahorse/client/net_http/patches.rb
+++ b/lib/seahorse/client/net_http/patches.rb
@@ -9,13 +9,20 @@ module Seahorse
       module Patches
 
         def self.apply!
-          return unless RUBY_VERSION < '2.5'
-          if RUBY_VERSION >= '2.0'
-            Net::HTTP.send(:include, Ruby_2)
+          if RUBY_VERSION >= '2.5'
+            # do nothing
+          elsif RUBY_VERSION >= '2.3'
             Net::HTTP::IDEMPOTENT_METHODS_.clear
+          elsif RUBY_VERSION >= '2.0'
+            Net::HTTP::IDEMPOTENT_METHODS_.clear
+            patch_transport_request!(Ruby_2)
           elsif RUBY_VERSION >= '1.9.3'
-            Net::HTTP.send(:include, Ruby_1_9_3)
+            patch_transport_request!(Ruby_1_9_3)
           end
+        end
+
+        def self.patch_transport_request!(patch)
+          Net::HTTP.send(:include, patch)
           Net::HTTP.send(:alias_method, :old_transport_request, :transport_request)
           Net::HTTP.send(:alias_method, :transport_request, :new_transport_request)
         end
@@ -30,7 +37,7 @@ module Seahorse
                 begin
                   res = Net::HTTPResponse.read_new(@socket)
                   res.decode_content = req.decode_content
-                end while res.kind_of?(Net::HTTPContinue)
+                end while res.kind_of?(Net::HTTPInformation)
 
                 res.uri = req.uri

```

**Comment by awood45** [comment]
Just to be clear, we have removed these patches for Ruby 2.5 - is the request here to narrow that exception for some other versions as well?

**Comment by fledman** [comment]
@awood45 
There are two separate points:

1) Ruby 2.3 & 2.4 do not need the patch, but they DO need the `IDEMPOTENT_METHODS_.clear` line

2) the patch (when applied) introduces back a bug that was fixed in mainland ruby >= 2.2

**Comment by cjyclaire** [comment]
PR #1980 opened under review

**Comment by cjyclaire** [comment]
release containing the fix is out https://rubygems.org/gems/aws-sdk-core/versions/3.46.2

**Comment by fledman** [comment]
great!
