### ISSUE TITLE
Incorrect return type documented for next_token

### ISSUE THREAD

**Issue by jfharden** [aws/aws-sdk-ruby#1981]
### Issue description

Documentation for next_token states when there are no more sets of items the value will be an empty string, the actual value is nil. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

Definitiely aws-sdk-autoscaling 1.13.0, maybe others too

### Version of Ruby, OS environment

Mac OSX 10.13.5
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

### Code snippets / steps to reproduce

```ruby
require "aws-sdk-autoscaling"

autoscaling_client = Aws::AutoScaling::Client.new(region: "eu-west-1")
response = autoscaling_client.describe_auto_scaling_groups(
  auto_scaling_group_names: ["my-asg"],
  max_records: 100
)

response.next_token.inspect
```

The next_token is nil, but the documentation says it will be an empty string.

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/AutoScaling/Types/AutoScalingGroupsType.html#next_token-instance_method

```
#next_token ⇒ String
The token to use when requesting the next set of items. If there are no additional items to return, the string is empty.

Returns:

(String)
```

**Comment by srchase** [comment]
@jfharden 

Thanks for raising this issue.

The AutoScaling service is not returning the next_token element in the response.  I've raised this issue internally with that team to resolve the discrepancy between the documentation and the API.

In case you're curious, you can add ```http_wire_trace: true``` in the client to see the underlying API calls:

```autoscaling_client = Aws::AutoScaling::Client.new(region: "eu-west-1", http_wire_trace: true)```

**Comment by mullermp** [comment]
This appears to have been fixed. Going to close this issue for now. Please reopen if this is still any concern.
