### ISSUE TITLE
TranscribeService: Add suppport for custom s3 object path as output location.

### ISSUE THREAD

**Issue by thapakazi** [aws/aws-sdk-ruby#1982]
> You might be plate full, ignore if so.
This is a feature request, pardon me if this thing already exists or this is wrong place to raise this concern.

### custom path support for transcribed files
I am unable to find the options on api [documentation](https://docs.aws.amazon.com/sdkforruby/api/Aws/TranscribeService/Client.html#start_transcription_job-instance_method) to set the custom output location for  transcribed files.

![screenshot-20190221-16 03 28](https://user-images.githubusercontent.com/1695906/53161576-5cfdb780-35f2-11e9-9ef3-cbaa04f7a136.png)
I want to organise the output location, right now its all cluttered in root of my s3 bucket :(
 

### feature request details: 
It would be nice if we can have something like this:
```ruby

resp = client.start_transcription_job({
  transcription_job_name: "TranscriptionJobName", # required
  ...
  media: { # required
    media_file_uri: "Uri",
  },
  output_bucket_name: "OutputBucketName",
  output_bucket_prefix: "/staging/transcripts/", # <<<< this wold be cool
  ...
})
```

**Comment by srchase** [comment]
@thapakazi 

Thanks for submitting this feature request.

This is a feature that would best be implemented by the Transcribe Service Team, and not in the SDK itself.

Have you reached out to the Transcribe Service with this request?

**Comment by srchase** [comment]
I'll go ahead and close this issue here, but let us know if you have followup questions.

**Comment by thapakazi** [comment]
Yeah, apologies I was feeling itchy to open this concern here. 

> Have you reached out to the Transcribe Service with this request?
How do I do that ??  Where though ??

**Comment by srchase** [comment]
@thapakazi,

You can engage the Transcribe Service through the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=278).
