### ISSUE TITLE
What happened with the `:encryption_key` option in the S3Object#write method?

### ISSUE THREAD

**Issue by rafaelfranca** [aws/aws-sdk-ruby#1983]
I'm trying to migrate from v1 to v2 and it is really hard to find information on how you are supposed to change your code to follow the v2 API.

For example, the [`:encryption_key` option in the `#write` method ](https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#write-instance_method), does not exists in the [`put` method in the v2](https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#put-instance_method).

What is the equivalent option? And is there any way we can document this in the migration guide?

**Comment by srchase** [comment]
@rafaelfranca 

Thanks for raising this issue.  Client-side encryption under v1 was a customization that was not carried forward to v2 and v3.

That behavior for v3 is noted here: [Client-Side Encryption ](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/s3-example-client-encryption.html)

I've tagged this as a documentation issue to add a note regarding client-side encryption for v2 and v3.

**Comment by mullermp** [comment]
Closing this issue.
