### ISSUE TITLE
DescribeSecurityGroupsResult doesn't have nextToken

### ISSUE THREAD

**Issue by nurse** [aws/aws-sdk-ruby#1987]
### Issue description

`Aws::EC2::Client#describe_security_groups` returns Types::DescribeSecurityGroupsResult,
and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Types/DescribeSecurityGroupsResult.html) says `DescribeSecurityGroupsResult` has `next_token` method.
But it doesn't have `next_token` method as below.

```
Traceback (most recent call last):
	7: from bin/traceroute53:223:in `<main>'
	6: from bin/traceroute53:217:in `main'
	5: from bin/traceroute53:217:in `each'
	4: from bin/traceroute53:219:in `block in main'
	3: from bin/traceroute53:107:in `describe_security_groups'
	2: from bin/traceroute53:107:in `loop'
	1: from bin/traceroute53:115:in `block in describe_security_groups'
/Users/naruse/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:87:in `method_missing': undefined method `next_token' for #<Seahorse::Client::Response:0x00007f98f1343d20> (NoMethodError)
```

[The definition of DescribeSecurityGroupsResult](https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/apis/ec2/2016-09-15/api-2.json#L5491-L5499) looks not have `nextToken`.
Moreover [AWS's EC2 doc](https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/APIReference/API_DescribeSecurityGroups.html) also says it has `nextToken` but its sample output doesn't contain `nextToken`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
aws-sdk (3.0.1)
aws-sdk-ec2 (1.72.0)
```

### Version of Ruby, OS environment

ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

**Comment by srchase** [comment]
@nurse 

The next_token is not required and will be returned from the EC2 Service if there are not additional pages of results.

It should be set to ```nil``` in this case.

Can you provide an example of your code?

**Comment by nurse** [comment]
Oops, my environment actually used aws-sdk-ec2 1.9.0, in which DescribeSecurityGroupsResult doesn't have `next_token`, on running the script.
Sorry for the noise and thank you for comment!
