### ISSUE TITLE
PresignedPost and as_json

### ISSUE THREAD

**Issue by PatrickKing** [aws/aws-sdk-ruby#1989]
### Issue description
I'm using `Bucket#presigned_post` to generate values to populate a browser form. I've found it convenient to simply add the result of `PresignedPost#fields` to the data I serialize for the client, this looks like it will work just fine.

But, while writing this code, I noticed that if I pass the [presigned post](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/PresignedPost.html) to my serializer instead, it will happily serialize my secret access key for me, among other things. `presigned_post.as_json` gives us a hash like:

```
{
             "credentials" => {
            "access_key_id" => "***",
        "secret_access_key" => "***,
            "session_token" => nil
    },
           "bucket_region" => "us-east-2",
             "bucket_name" => "***",
                     "url" => "https://***.s3.us-east-2.amazonaws.com",
                  "fields" => {
        "key" => "***"
    },
                 "key_set" => true,
    "signature_expiration" => "2019-03-07T17:30:14.995-07:00",
              "conditions" => [
        [0] {
            "bucket" => "***"
        },
        [1] {
            "key" => "***"
        }
    ]
}
```

This isn't a bug, but it seems like an easy way to accidentally leak your credentials. Should the secret access key be omitted from `PresignedPost#as_json`?

### Gem name
'aws-sdk-s3' 1.30.1

### Version of Ruby, OS environment
Ruby 2.6.0 / Macos 10.12.6

### Code snippets / steps to reproduce
```
    bucket = Aws::S3::Bucket.new 'a-bucket'
    post = bucket.presigned_post key: 'a-key'
    post.as_json
```

**Comment by srchase** [comment]
@PatrickKing 

Thanks for raising this issue.  Removing credentials from ```as_json``` would be a breaking change and would require a major version.

**Comment by mullermp** [comment]
`as_json` is implemented from Rails and not in the SDK.

```
Aws> bucket = Aws::S3::Bucket.new('mamuller-us-west-2')
=> #<Aws::S3::Bucket:0x00007f8261053710 @arn=nil, @client=#<Aws::S3::Client>, @data=nil, @name="mamuller-us-west-2", @waiter_block_warned=false>
Aws> post = bucket.presigned_post(key: 'file')
=> #<Aws::S3::PresignedPost:0x00007f8261c63230
 @bucket_name="mamuller-us-west-2",
 @bucket_region="us-west-2",
 @conditions=[{"bucket"=>"mamuller-us-west-2"}, {"key"=>"file"}],
 @credentials=#<Aws::Credentials access_key_id="<removed>">,
 @fields={"key"=>"file"},
 @key_set=true,
 @signature_expiration=2020-05-29 13:41:42 -0700,
 @url="https://mamuller-us-west-2.s3.us-west-2.amazonaws.com">
Aws> post.as_json
NoMethodError: undefined method `as_json' for #<Aws::S3::PresignedPost:0x00007f8261c63230>
from (pry):4:in `__binding__'
```

Once I require rails (or in particular, `ActiveModel::Serializers::JSON`)

```
Aws> require 'rails'
=> true


```
Aws> post.as_json
=> {"credentials"=>{ <sensitive> },
 "bucket_region"=>"us-west-2",
 "bucket_name"=>"mamuller-us-west-2",
 "url"=>"https://mamuller-us-west-2.s3.us-west-2.amazonaws.com",
 "fields"=>{"key"=>"file"},
 "key_set"=>true,
 "signature_expiration"=>"2020-05-29T13:41:42.029-07:00",
 "conditions"=>[{"bucket"=>"mamuller-us-west-2"}, {"key"=>"file"}]}
```

You can exclude them using the proper [options for as_json](https://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html#method-i-as_json):
```
Aws> post.as_json(except: 'credentials')
=> {"bucket_region"=>"us-west-2",
 "bucket_name"=>"mamuller-us-west-2",
 "url"=>"https://mamuller-us-west-2.s3.us-west-2.amazonaws.com",
 "fields"=>{"key"=>"file"},
 "key_set"=>true,
 "signature_expiration"=>"2020-05-29T13:41:42.029-07:00",
 "conditions"=>[{"bucket"=>"mamuller-us-west-2"}, {"key"=>"file"}]}
```
