### ISSUE TITLE
BigDecimal.new is deprecated warning

### ISSUE THREAD

**Issue by justinoue** [aws/aws-sdk-ruby#1996]
### Issue description
Using the current latest gem with ruby 3.6 throws a warning when converting dynamodb decimal values.

```
gems/aws-sdk-core-2.11.241/lib/aws-sdk-core/dynamodb/attribute_value.rb:79: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-core-2.11.241

### Version of Ruby, OS environment
Ruby 2.6.1p33

**Comment by awood45** [comment]
Looks like we just need to backport the relevant changes to V2. Adding to our backlog.

**Comment by cjyclaire** [comment]
https://github.com/aws/aws-sdk-ruby/pull/2042
already merged and release
