### ISSUE TITLE
Warning spam: `Unable to load the http/2 gem.`

### ISSUE THREAD

**Issue by viraptor** [aws/aws-sdk-ruby#1998]
### Version of Ruby, OS environment

Ruby 2.3, Ubuntu server

### Code snippets / steps to reproduce

Upgrading from `aws-sdk-core (3.47.0)` to `3.48.0` resulted in the following message:
```
Unable to load the http/2 gem.
```

While it doesn't seem to break anything specifically, it spams the output with this message, making it hard to (for example) use `cronic` or something else which expects a clean output.

**Comment by awood45** [comment]
This is a fair callout, we can narrow the scope of this warning.

**Comment by awood45** [comment]
This change will go out with the next release, after which upgrading `aws-sdk-core` to 3.48.1 will clean up the error message spam.

**Comment by phene** [comment]
This warning still exists in version 3.48.2

**Comment by awood45** [comment]
Can you show me the code you ran to trigger the warning? I did just notice that when requiring `aws-sdk-kinesis` it shows up once still which I can look at, but checking if it shows up in other cases.

**Comment by phene** [comment]
I see it in `aws-sdk-kinesis` (which you already identified) and `aws-sdk-transcribestreamingservice`
