### ISSUE TITLE
Unhelpful error when Client objects do not receive :region option in configuration hash

### ISSUE THREAD

**Issue by wjaspers** [aws/aws-sdk-ruby#2000]
### Issue description
No useful stack trace is generated when an AWS SDK Client is created and happens to be missing the `:region` option.
If a client omits it in the options hash, the user encounters the following error: 
```NoMethodError: undefined method `match' for nil:NilClass```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3

### Version of Ruby, OS environment
ruby-2.3.3 on OSX High Sierra

### Code snippets / steps to reproduce
```
require 'aws-sdk-s3'
res = Aws::S3::Resource.new({ credentials: Aws::Credentials.new('AKEYID','ASECRETKEY') })
```

**Comment by softwaregravy** [comment]
I hit this today. 

I am using `aws-sdk-s3`. S3 does not require a region. Still get this error without a region. I used the following command:

```
Aws::S3::Client.new
```

**Comment by cjyclaire** [comment]
@softwaregravy You have to provide `:region` when initializing a S3 client (or through envs), where your bucket located, SDK needs to know the region for making requests to the correct service endpoint with correct signature.

But, I agree that it's fair to make the error more self-explainable

**Comment by softwaregravy** [comment]
@cjyclaire you're right, of course, about needing a region for S3.

**Comment by wjaspers** [comment]
Almost every SDK client I've had to use requires a region. The sdk happens to behave differently when operating under the assumption of an IAM role, which is how i ran into this in the first place.

**Comment by nzifnab** [comment]
This seems to be a regression of https://github.com/aws/aws-sdk-ruby/issues/1237

This exact same error used to happen in 2016 when you didn't set a `region`, and now it's happening again.

**Comment by mullermp** [comment]
It looks like it depends on what type of client you initialize. Initializing an instance of `Aws::DynamoDB::Client.new` will throw a MissingRegionError correctly - because it doesn't use endpoint_provider.
