### ISSUE TITLE
Set idle_timeout via Aws.config

### ISSUE THREAD

**Issue by aaronbartell** [aws/aws-sdk-ruby#2006]
### Issue description
I am attempting to write an RSpec unit test for the SQS service. If I don't specify `idle_timeout: 0` on `Aws::SQS::QueuePoller.new` it will continuously poll. This is the expected behavior in production but poses a problem when stubbing for RSpec because I don't want to modify the production code to facilitate unit tests.

I am curious if there is a way to set a `Aws.config` setting for `idle_timeout` so that I don't have to set it on the `Aws::SQS::QueuePoller.new` API call?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
$ gem list aws-sdk -d

*** LOCAL GEMS ***

aws-sdk (2.11.142)
    Author: Amazon Web Services
    Homepage: http://github.com/aws/aws-sdk-ruby
    License: Apache 2.0
    Installed at: /bundle

    AWS SDK for Ruby

aws-sdk-core (2.11.142)
    Author: Amazon Web Services
    Homepage: http://github.com/aws/aws-sdk-ruby
    License: Apache 2.0
    Installed at: /bundle

    AWS SDK for Ruby - Core

aws-sdk-rails (1.0.1)
    Author: Amazon Web Services
    Homepage: http://github.com/awslabs/aws-sdk-rails
    License: Apache 2.0
    Installed at: /bundle

    AWS SDK for Ruby Rails Plugin

aws-sdk-resources (2.11.142)
    Author: Amazon Web Services
    Homepage: http://github.com/aws/aws-sdk-ruby
    License: Apache 2.0
    Installed at: /bundle

    AWS SDK for Ruby - Resources
```

### Version of Ruby, OS environment
```
$ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
```

### Code snippets / steps to reproduce
This is the working example.  Run as-is and it will stop after it reads the messages. Remove `idle_timeout: 0` and it will continuously loop.  

```
Aws.config[:sqs] = {
  stub_responses: {
    receive_message: [
      { messages: [ { message_id: 'id1', receipt_handle: 'rh1', body: '1234' } ] },
      { messages: [] }
    ]
  }
}

url = 'https://example.com'
poller = Aws::SQS::QueuePoller.new(url, idle_timeout: 0)
poller.poll do |message|
  puts "!!!!message:#{message}"
end
```

**Comment by awood45** [comment]
There is not - `Aws.config` keeps global configuration state for AWS clients, but the QueuePoller is a hand-written customization. I'd recommend stubbing your calls here, or having the test-specific configuration settings. Given your statement and without seeing your code, I'd presume that mocking the QueuePoller is appropriate for your use case.

**Comment by aaronbartell** [comment]
Thanks for the response.  We will take your feedback into consideration as we move forward.
