### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

### ISSUE THREAD

**Issue by matheusvetor** [aws/aws-sdk-ruby#2013]
### Issue description

Hello, i'm on a legacy project who runs on rails 4.2.8 and i'm trying to upload a file to s3.

I'm getting the the error `The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`. The error happens on `obj.acl = 'public-read'`. I tried do a google search, see the v1 documentation and search on project issues but no succeed. 

### Gem name
aws-sdk (1.66.0)

### Version of Ruby, OS environment
2.2.5, debian - jessie (running on docker)

### Code snippets / steps to reproduce
All the ENV variables are populated and the app can read them.

```
    require 'aws-sdk-v1'

    AWS.config({
      region: ENV['S3_REGION'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    })

    object_name = 'testfile.jpg'

    s3 = AWS::S3.new
    bucket = s3.buckets[ENV['S3_BUCKET_NAME']]

    obj = bucket.objects[object_name]
    obj.acl = 'public-read'
    obj.write(Pathname.new(File.join(Rails.root, "tmp/", object_name)))
```
I already try to put the endpoint on `AWS.config`:

```
    AWS.config({
      region: ENV['S3_REGION'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      endpoint: 's3.eu-central-1.amazonaws.com'
    })
```

**Comment by cjyclaire** [comment]
V1 of SDK has been end of life for years and no longer receive feature updates and bug fixes except security related. We recommend upgrade to V2(one for all) or V3(modularized) of SDK based on your needs https://github.com/aws/aws-sdk-ruby/blob/master/MIGRATING.md https://github.com/aws/aws-sdk-ruby/blob/master/V3_UPGRADING_GUIDE.md

(Not recommend for staying on V1) For debugging tips for V1, you can try set `:http_wire_trace` to true at client for viewing the wire log

**Comment by cjyclaire** [comment]
also, if it's cross region, for V2 and V3, we have `:copy_from` for cross region object copies

**Comment by matheusvetor** [comment]
@cjyclaire thanks for the response. I just found the problem. The bucket region was wrong. In the process i just updated to v2 an intent update to v3 asas.
