### ISSUE TITLE
How to get md5_of_message_body with stub_responses

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [aws/aws-sdk-ruby#2021]
I want to verify calculated MD5, which comes from `md5_of_message_body` function, and the result of MD5 that is given by SQS. However, when I use `stub_responses`, the SQS's `md5_of_message_body` is `nil`. So what should I do in this case to get correct MD5 value?

Also, I'm not sure that question is related with #1085, #1100, #1103 or #1885

**Gem name**: `aws-sdk-sqs` 1.13.0
**Version of Ruby**: 2.5.1p57 on Ubuntu 18.04

*P.S. I'm rewriting Rspecs of [`active_elastic_job`](https://github.com/tawan/active-elastic-job) library. The spec files are depended (and needed) to manual installation on AWS because there is no stubbing with `stub_responses`*

## Source code

```ruby
# lib/.../....rb
def md5_of_message_body(message_body)
  OpenSSL::Digest::MD5.hexdigest(message_body)
end

# spec/.../..._spec.rb
let(:base_class) { Class.new { extend ... } }
let(:sqs) { Aws::SQS::Client.new(stub_responses: true) }

it "should be valid" do
  sqs.stub_responses(:send_message, { message_id: 'id' })

  response = sqs.send_message(
    queue_url: "https://example.com", message_body: "Hello!"
  ).md5_of_message_body

  expect(response).to eq(base_class.md5_of_message_body(message_body))
end
```

```
Failure/Error: expect(response).to eq(base_class.md5_of_message_body(message_body))
    expected: "dd95b09bb62c853078a35697bbc85f39"
         got: nil

    (compared using ==)
```

**Comment by cjyclaire** [comment]
@BerkhanBerkdemir When you are stubbing client responses, you are expected to provide all stubbed values, or default value (nil, {}, '' etc) will be provided. SDK doesn't mock any service side behavior when returning stub responses. 

Though this can potentially be a feature request for mocking stub values for msg verifier, thoughts?

**Comment by BerkhanBerkdemir** [comment]
I can say that is probably a feature request since I want to see some dummy content (related to the parameters) without requiring a network connection. I know it seems weird for the concept of stubbing, but that would be great feature and usable.

**Comment by klausbadelt** [comment]
You can add a Proc to stub_responses, creating dynamic stubs, including calculating your md5.

**Comment by mullermp** [comment]
@klausbadelt Yes that will work. Do you have a working snippet to share?

**Comment by klausbadelt** [comment]
Here's one from the [AWS Blog](https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/)

**Comment by mullermp** [comment]
@BerkhanBerkdemir I'm going to close this feature request as there is very little interest. As @klausbadelt pointed out, you can use dynamic stubbing to verify the md5 content yourself.

Blog: https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/
