### ISSUE TITLE
SDK Releases

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#2022]
Is there anyway to know what actually changed in terms of the API as the SDK releases are done? 

The release notes/change doc mention API was updated, but no other details. Would it be possible to add the actual changes to the release notes?

That will make it a lot easier for users who are using multiple services(In our case, we use about 21) and we are having a hard time keeping track of the changes/updates to the SDK and the API.

Apologies if this information is already available and we just missed it.

Thanks!

**Comment by cjyclaire** [comment]
Thanks for the feedback, appreciate that! 
I'll prioritize works for adding details in changelog entries per service gems per release, will keep posted!

**Comment by pchaganti** [comment]
Checking back for any updates on this.

thanks!

**Comment by cjyclaire** [comment]
Soft updates, this is actively working on currently

**Comment by cjyclaire** [comment]
Done, now we have `CHANGELOG.md`s with detailed entries :p

Taking latest release as example:
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-apigateway/CHANGELOG.md
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-efs/CHANGELOG.md
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-devicefarm/CHANGELOG.md
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-servicecatalog/CHANGELOG.md
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-budgets/CHANGELOG.md
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-ec2/CHANGELOG.md

**Comment by pchaganti** [comment]
This works. Thanks!
