### ISSUE TITLE
wrong endpoint

### ISSUE THREAD

**Issue by lclemence** [aws/aws-sdk-ruby#2025]
### Issue description
I set an endpoint but the queue-url of the queue created is wrong, localhost instead of localstack. I am inside a docker.
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-sqs 1.10.0
### Version of Ruby, OS environment
<img width="431" alt="Screen Shot 2019-04-19 at 3 56 08 PM" src="https://user-images.githubusercontent.com/931424/56441609-a9e0d000-62bb-11e9-8213-17335e241989.png">
<img width="453" alt="Screen Shot 2019-04-19 at 3 57 08 PM" src="https://user-images.githubusercontent.com/931424/56441684-df85b900-62bb-11e9-9dc1-f6830efec8c2.png">

### Code snippets / steps to reproduce
<img width="669" alt="Screen Shot 2019-04-19 at 3 53 12 PM" src="https://user-images.githubusercontent.com/931424/56441490-4b1b5680-62bb-11e9-9df6-416411c5a61f.png">
<img width="396" alt="Screen Shot 2019-04-19 at 3 54 19 PM" src="https://user-images.githubusercontent.com/931424/56441539-71d98d00-62bb-11e9-95e4-5bc45b4ddd83.png">

**Comment by cjyclaire** [comment]
cannot reproduce locally:

![image](https://user-images.githubusercontent.com/10790394/56442294-0dabce80-62a5-11e9-8459-67f33de9d81f.png)

you can see that it's hitting the endpoint provided.

could you try set `:http_wire_trace` to `true` at client and see the wire log available?

**Comment by lclemence** [comment]
<img width="946" alt="Screen Shot 2019-04-19 at 6 55 46 PM" src="https://user-images.githubusercontent.com/931424/56447197-c9d0bd80-62d4-11e9-9eac-12055dacb2e5.png">

**Comment by cjyclaire** [comment]
you can see there, SDK is making request to `localstack:4576` correctly instead of `localhost:4576`, since you are not making request directly to public sqs endpoint I'm guessing it's related to your mocking service(?) or proxy(?) on `localstack:4576`

**Comment by lclemence** [comment]
Thank you <3, that means that it is not a problem with the sdk and I have a problem with my docker compose (using localstack). I close this issue and will reopen to write the solution when I found it.

**Comment by chenkita** [comment]
for future visitors of this page:

I was running localstack in a docker container and encountered the same issue.
Resolved by setting HOSTNAME_EXTERNAL env variable to 'localstack' (in the localstack container)
- HOSTNAME_EXTERNAL=localstack

**Comment by robinboening** [comment]
@chenkita thank you! I just spent two hours debugging this and you probably saved me from a sleepless night 🥇
