### ISSUE TITLE
Bad interpretation of params (Client aws)

### ISSUE THREAD

**Issue by lclemence** [aws/aws-sdk-ruby#2026]
### Issue description
I get a different interpretation of the params when I initialize the aws sqs client. First one I get an error "Invalid token client id" and the other one is working. It seems to not like the old ruby syntax which is used when we do a load from yml (as in gem shoryuken)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-sqs (1.10.0)
### Version of Ruby, OS environment
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
### Code snippets / steps to reproduce
<img width="950" alt="Screen Shot 2019-04-19 at 4 59 39 PM" src="https://user-images.githubusercontent.com/931424/56447928-38177f00-62d9-11e9-9e4d-3ee2a3679cfe.png">
(sorry for screenshot)

**Comment by cjyclaire** [comment]
Cannot reproduce this locally hitting SQS endpoint, are you seeing the same issue with public SQS endpoint?

**Comment by cjyclaire** [comment]
closing due to inactiveness, feel free to reopen with additional comments
