### ISSUE TITLE
Types for resource structure members are not reflected in the static structure of the classes so it's hard to build tools for resource traversal

### ISSUE THREAD

**Issue by davidk01** [aws/aws-sdk-ruby#2029]
### Issue description
I'm writing a tool for querying and managing remote AWS resources with Prolog. The main pipeline currently uses the Ruby SDK to gather the remote resources into Prolog facts and predicates. Bare facts can be a little tricky to handle so to simplify the end user experience I'm embedding type/shape information into the Prolog files so the end user knows where a piece of data came from and what type/shape it had.

The problem is that the shape information is not actually reflected in the auto-generated code even though when the code is generated all the shapes/types for all the fields are known. Ideally I could query this information at runtime by asking the class what it's shape is without having to do runtime traversal of the resource instances.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
aws-sdk (3.0.1)
```

### Version of Ruby, OS environment
```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```
```
$ uname -a
Linux 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Code snippets / steps to reproduce
There are no steps to reproduce. It's mostly an issue/missing feature. For concreteness sake I'm going to use `Aws::Route53::Types::HostedZone` as an example. Let's say I have an instance `zone` of `Aws::Route53::Types::HostedZone`.

If I look at its members then I get some parts of the shape
```
pry(main)> zone.class.members
=> [:id, :name, :caller_reference, :config, :resource_record_set_count, :linked_service]
```
This is very useful information to have because it means I can reflect this structure in the Prolog file as another set of facts. The problem is that I can't get the types/shapes of those members from the class even though in theory that information is available already in the comments for the Ruby class/type that represents the remote resource.

I can discover the types at runtime but only if I have a non-nil value and this is not guaranteed. Hosted zone resources are again a good example because `linked_service` field can be nil even though in the comment it is clear that there is an actual type/shape associated with the value of the field `linked_service`

```
    # @!attribute [rw] linked_service
    #   If the health check was created by another service, the service that
    #   created the health check. When a health check is created by another
    #   service, you can't edit or delete it using Amazon Route 53.
    #   @return [Types::LinkedService]
```

So ideally this information wouldn't just be in the comment and would be part of the class structure, e.g.
```
    class HostedZone < Struct.new(
      :id,
      :name,
      :caller_reference,
      :config,
      :resource_record_set_count,
      :linked_service)
      include Aws::Structure
      # Types/shapes for the fields that can be queried at runtime
      field_type(:id, String)
      field_type(:name, String)
      # ...
    end
```

The only workaround currently is to traverse the source files and parse the comments to generate the fields. It's extra work that I think could be solved at the SDK level. Happy to elaborate further if necessary.

**Comment by awood45** [comment]
For a use case like this, would it make sense for you to make use of the `api-2.json` files?

**Comment by davidk01** [comment]
I remember looking at the JSON but moving past them for some reason. I'll take another look. Maybe I can make better sense of it now after having fought with it for a few days.

I still think though it would be worthwhile to have that information reflected at runtime. The Ruby SDK is really nice to work with and would be even nicer with this data because it would allow interesting interop opportunities with tools like the one I'm trying to build.

**Comment by davidk01** [comment]
Still can't make sense of them. Is there a schema somewhere I can look at to understand the global structure of these JSON files?

**Comment by davidk01** [comment]
I got the pieces working on my end so this isn't a blocker for me at this point

```
[1] pry(Resource)> resource.class
=> Aws::EC2::Types::Instance
[2] pry(Resource)> resource.class.shape
=> {"ami_launch_index"=>"Integer",
 "image_id"=>"String",
 "instance_id"=>"String",
 "instance_type"=>"String",
 "kernel_id"=>"String",
 "key_name"=>"String",
 "launch_time"=>"Time",
 "monitoring"=>"Types::Monitoring",
 "placement"=>"Types::Placement",
 "platform"=>"String",
 "private_dns_name"=>"String",
 "private_ip_address"=>"String",
 "product_codes"=>"Array<Types::ProductCode>",
 "public_dns_name"=>"String",
 "public_ip_address"=>"String",
 "ramdisk_id"=>"String",
 "state"=>"Types::InstanceState",
 "state_transition_reason"=>"String",
 "subnet_id"=>"String",
 "vpc_id"=>"String",
 "architecture"=>"String",
 "block_device_mappings"=>"Array<Types::InstanceBlockDeviceMapping>",
 "client_token"=>"String",
 "ebs_optimized"=>"Boolean",
 "ena_support"=>"Boolean",
 "hypervisor"=>"String",
 "iam_instance_profile"=>"Types::IamInstanceProfile",
 "instance_lifecycle"=>"String",
 "elastic_gpu_associations"=>"Array<Types::ElasticGpuAssociation>",
 "elastic_inference_accelerator_associations"=>"Array<Types::ElasticInferenceAcceleratorAssociation>",
 "network_interfaces"=>"Array<Types::InstanceNetworkInterface>",
 "root_device_name"=>"String",
 "root_device_type"=>"String",
 "security_groups"=>"Array<Types::GroupIdentifier>",
 "source_dest_check"=>"Boolean",
 "spot_instance_request_id"=>"String",
 "sriov_net_support"=>"String",
 "state_reason"=>"Types::StateReason",
 "tags"=>"Array<Types::Tag>",
 "virtualization_type"=>"String",
 "cpu_options"=>"Types::CpuOptions",
 "capacity_reservation_id"=>"String",
 "capacity_reservation_specification"=>"Types::CapacityReservationSpecificationResponse",
 "hibernation_options"=>"Types::HibernationOptions",
 "licenses"=>"Array<Types::LicenseConfiguration>"}
```

If this does become a feature then I think the above representation is a good way to reflect the types into the runtime. Ideally the types themselves would also be runtime structures instead of strings but I think strings are good enough for most use cases.

**Comment by mullermp** [comment]
Hey - sorry for the late response here. Have you also looked at the client API for this? https://raw.githubusercontent.com/aws/aws-sdk-ruby/master/gems/aws-sdk-ec2/lib/aws-sdk-ec2/client_api.rb

Going to close this out as we have no plans to do this.. happy to look at any pull requests.
