### ISSUE TITLE
`function_error` is nil even when there is an error raised in lambda

### ISSUE THREAD

**Issue by invacuo** [aws/aws-sdk-ruby#2032]
Please fill out the sections below to help us address your issue

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-lambda (1.21.0)`

### Version of Ruby, OS environment
`ruby-2.5.1` MacOS Mojave

### Code snippets / steps to reproduce
I have a following simple lambda
```ruby
require 'json'

def lambda_handler(event:, context:)
  raise ArgumentError.new('Missing key error: foo') unless event.key?('foo')

  {
    message: "Hello #{event['foo']}!"
  }.to_json
rescue ArgumentError => e
  # we will log a honeybadger error here
  puts 'event value'
  puts event
  raise e
end
```

I am using rspec to test this.

This works fine
```ruby
        expect do
          lambda_handler(event: {}, context: '')
        end.to raise_error(ArgumentError)
```

The following invocation does not populate `function_error` or `log_result` in the response though

```ruby

def lambda_client
    @lambda_client ||= Aws::Lambda::Client.new(
      endpoint: 'http://127.0.0.1:3001/'
    )
end


.
.
.
.
.
.

# In my actual spec
          event = { 'boo' => 'far' }

          resp = lambda_client.invoke({
            function_name: "HelloWorldFunction",
            invocation_type: "RequestResponse",
            payload:  event.to_json
          })
```

Here is the output in the console after. Notice `resp.payload.string` is blank as well which is correct as I am raising an error as the first line.

```shell
[1] pry(#<RSpec::ExampleGroups::LambdaTest::LambdaHandler::CallingItViaLambdaInvoke::InvalidEventParamsPassed>)> resp
=> #<struct Aws::Lambda::Types::InvocationResponse status_code=200, function_error=nil, log_result=nil, payload=#<StringIO:0x00007fb28a0a74d8>, executed_version=nil>
[2] pry(#<RSpec::ExampleGroups::LambdaTest::LambdaHandler::CallingItViaLambdaInvoke::InvalidEventParamsPassed>)> resp.payload.string
=> ""
```

This positive test case passes

```ruby
          event = { 'foo' => 'bar' }

          resp = lambda_client.invoke({
            function_name: "HelloWorldFunction",
            invocation_type: "RequestResponse",
            log_type: "None",
            payload:  event.to_json
          })
          response_payload = JSON.parse(resp.payload.string)

          expect(resp.status_code).to eq 200
          expect(response_payload).to eq ({
            message: "Hello #{event['foo']}!"
          }.to_json)
```

**Comment by cjyclaire** [comment]
I tested with lambda service endpoint and cannot reproduce the issue, the response looks like:
```
=> #<struct Aws::Lambda::Types::InvocationResponse
 status_code=200,
 function_error="Unhandled",
 log_result=nil,
 payload=#<StringIO:0x007f8dd0da83a0>,
 executed_version="$LATEST">
```
with `payload`
```
"{\"errorMessage\":\"Missing key error: foo\",\"errorType\":\"Function<ArgumentError>\",\"stackTrace\":[\"/var/task/lambda_function.rb:4:in `lambda_handler'\"]}"
```

I saw you are using `http://127.0.0.1:3001/` as the client endpoint, may I ask is this something like local debugging? Are you seeing same issue with service endpoint?

**Comment by invacuo** [comment]
Yea this is for local debugging/ integration testing. I was following this article https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-automated-tests.html


I have not tested it with actual production endpoint. FWIW, I do see the request being processed where I have `sam local start-lambda` running. See the output below.


```bash
Fetching lambci/lambda:ruby2.5 Docker container image......
2019-04-23 16:51:44 Mounting /Users/chaitanya.kale/workspace/sam-app/hello_world as /var/task:ro,delegated inside runtime container
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
event value
{"boo"=>"far"}
Error raised from handler method
{
  "errorMessage": "Missing key error: foo",
  "errorType": "Function<ArgumentError>",
  "stackTrace": [
    "/var/task/app.rb:31:in `lambda_handler'"
  ]
}
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 2.96 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 18 MB
{
  "errorType": "Function\u003cArgumentError\u003e",
  "errorMessage": "Missing key error: foo",
  "stackTrace": [
    "/var/task/app.rb:31:in `lambda_handler'"
  ]
}
```

**Comment by cjyclaire** [comment]
@invacuo Thanks for the clarify! As this is related to SAM CLI, mind opening an issue there https://github.com/awslabs/aws-sam-cli instead? SAM team will help take a look as soon as possible :D

**Comment by invacuo** [comment]
Ah ok, I am not entirely sure if this is related to the CLI or SDK. I will try posting there. Appreciate your help.

**Comment by invacuo** [comment]
Just to clarify, you think this is happening because the `sam local start-lambda` is not returning the same response as the production endpoint invocation?

**Comment by cjyclaire** [comment]
Yeah, could be, as I couldn't reproduce by hitting service endpoint, if you are seeing the same behavior from service endpoint, let me know.

**Comment by cjyclaire** [comment]
closing due to inactiveness, feel free to reopen with further comments

**Comment by invacuo** [comment]
I have an issue open in aws-sam-cli repo but haven't heard anything about it https://github.com/awslabs/aws-sam-cli/issues/1148
