### ISSUE TITLE
AWS::Sigv4::Signer does not URI encode request parameters

### ISSUE THREAD

**Issue by kreynolds** [aws/aws-sdk-ruby#2035]
Please fill out the sections below to help us address your issue

### Issue description
When writing a utility that accepts incoming AWSv4 style signatures, I discovered that it does not URI encode the parameters when generating the string to sign.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sigv4 -> master

### Version of Ruby, OS environment
N/A

### Code snippets / steps to reproduce
Looking at the [following method](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L504-L523), it does a number of things such as sorting and adding an empty `=` if a value for a key was not specified but it does not encode the parameters. Some clients will encode the request URI, some don't, and if this function does not properly encode them as [specified here](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) then the signatures will not match.

I monkey patched the method in question to encode the request parameters and it fixed the problem. (For example, `delimiter=/` should look like `delimiter=%2F`. If desired I can create a PR for this issue.

**Comment by kreynolds** [comment]
Below is a script that will more clearly describe the problem and difference:

```ruby
#!/usr/bin/env ruby
require 'cgi'
require 'aws-sigv4'

querystring = "delimiter=/&max-keys=2&max-keys=1&pre%20fix=.localized/&foo"

def fixed_normalized_querystring(querystring)
  params = querystring.split('&').map { |p|
    CGI.parse(p).transform_values { |v|
      v.first || ''
    }
  }

  params = params.each.with_index.sort { |(a_hash, a_offset), (b_hash, b_offset)|
    a_name = a_hash.first[0]
    b_name = b_hash.first[0]
    if a_name == b_name
      a_offset <=> b_offset
    else
      a_name <=> b_name
    end
  }.map { |hash, _|
    URI.encode_www_form(hash.to_a)
  }.join('&')
end

# Changed version
puts fixed_normalized_querystring(querystring)
# => delimiter=%2F&foo=&max-keys=2&max-keys=1&pre+fix=.localized%2F

# Original version
puts Aws::Sigv4::Signer.new(
  service: :s3, region: 'us-east-1',
  access_key_id: 'key', secret_access_key: 'secret',
  uri_escape_path: false, # For every service except S3
).send(:normalized_querystring, querystring)
# => delimiter=/&foo=&max-keys=2&max-keys=1&pre%20fix=.localized/
```

The main difference here is that CGI.parse will decode the parameters _if they are encoded_ and then when the string is put back together, it will encode them appropriately, all using the ruby standard library.

The above code has been tested with s3fs, Cyberduck, and the Ruby aws-sdk itself for validating signatures.

**Comment by cjyclaire** [comment]
apologies for the delay, taking a look.
quick question, are you seeing issues with the signature with s3 only when parameters contains unescaped characters? (such as, `:put_object`?)

**Comment by kreynolds** [comment]
The place where I saw this was using the s3fs-fuse library. What happens there is that the query parameters it uses to sign are not the same that it sends over the wire, which is valid. The method I see this the most with is actually `:list_objects` but it would presumably happen any time parameters exist that require encoding (and does not happen when encoding is not required)

Detailed example using the s3fs-fuse library:

1. The query params are `delimiter=/&max-keys=2&prefix=.localized/`
2. When s3fs-fuse calculates the signature, [per the documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html), it escapes the query which looks like `delimiter=%2F&max-keys=2&prefix=._localized%2F` in the string to sign.
3. It then makes a request using the unescaped query with the format from item 1 .. ie `delimiter=/&max-keys=2&prefix=.localized/` instead of `delimiter=%2F&max-keys=2&prefix=._localized%2F`
4. When the AWS library calculates a signature (sending the raw request url into the url: parameter of Aws::Sigv4::Signer#sign_request), it _does not_ escape the parameters when normalizing, so the signatures do not match. Specifically, the string to sign generated by the AWS SDK has an unescaped version of the query. This is what I'm showing in the above sample code.

What my version does is use `CGI.parse` to parse/unescape everything, use the same sorting/normalization code that was already there, then encode it again and join the string. This hasn't shown up before because all of the following must be true:

* The AWS library must be used to receive and validate requests, not sign and send them to S3 (most people don't do this)
* The client used must encode parameters and make requests unencoded (many don't do this either)

**Comment by ajw725** [comment]
i'm not really sure whether this is the same issue, but i figured i'd put it here first. let me know if it should be a separate issue.

i'm seeing a similar problem where special characters in the object key are not being escaped. the regular AWS presigner **does** escape them. Pseudocode example:

```
region = 'us-east-1'
bucket = 'my-bucket'
key = '()!*_.pdf'
url = 'https://my-bucket.s3.amazonaws.com/()!*_.pdf'

Aws::S3::Object#presigned_url('PUT')
-> "https://my-bucket.s3.amazonaws.com/%28%29%21%2A_.pdf?X-Amz-Algorithm=[...]"

Aws::Sigv4::Signer#presign_url(http_method: 'PUT', url: url, body_digest: 'UNSIGNED-PAYLOAD')
-> "https://my-bucket.s3.amazonaws.com/()!*_.pdf?X-Amz-Algorithm=[...]"
```

Note that the v4 path is unescaped. If I do `CGI.escape` on the path myself before passing it to the v4 signer, it works fine.

The other problem here is that we **have** to use the sigv4 signer because the regular one[ doesn't correctly handle the server-side encryption header](https://github.com/aws/aws-sdk-ruby/issues/874) that we need.

**Comment by kreynolds** [comment]
It sounds like exactly the same thing. Monkeypath Aws::Sigv4::Signer#normalized_querystring with my function above and see if it fixes your issue.

**Comment by ajw725** [comment]
@kreynolds it does not. I think it's because the object key isn't actually one of the params here; the only things I see in params are the X-Amz-whatever headers, and the piece that's causing problems for me is the key itself, so patching the method as you described doesn't do anything to the key.

**Comment by mullermp** [comment]
I took the changes you proposed and inserted them into `normalized_querystring` but three of the cases for `get-vanilla-query-unreserved` will fail. It will encode tilde ~ but the [docs mention it](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) as a reserved character.

Is this actually a problem with s3fs-fuse? If it is using the Sigv4 gem, it will do all of the necessary encoding, so why is it done by them prior to signing?

Suite spec: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sigv4/spec/suite_spec.rb
