### ISSUE TITLE
DynamoDB returns Numbers as Float/String/Decimal

### ISSUE THREAD

**Issue by thomasedwards** [aws/aws-sdk-ruby#2037]
### Issue description

Ruby returns attributes stored as a Number in DynamoDB as a Float.

In DynamoDB:

    dateTimeCompleted Number : 1554138543

Expected response:

    "dateTimeCompleted"=>1554138543

Actual response:

    "dateTimeCompleted"=>0.1554376141e10

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk` (3.0.1)

### Version of Ruby, OS environment

Ruby 2.5 (Lambda)

### Code snippets / steps to reproduce

Create a DynamoDB table (I’ve called mine `Test`) and add an item:

    {
      "id": "1",
      "lovely": 123
    }

Then fetch it:

    require 'aws-sdk'

    def lambda_handler(event:, context:)
        dynamodb = Aws::DynamoDB::Client.new(region: 'eu-west-2')

        params = {
          table_name: 'Test',
          key: Hash['id', '1'],
        }

        response = dynamodb.get_item(params)
        response['item']
    end

Response when run:

    Response:
    {
      "lovely": "0.123e3",
      "id": "1"
    }

Expected response:

    Response:
    {
      "lovely": 123,
      "id": "1"
    }

If you instead return `response['item']['lovely'].class`:

    Response:
    "BigDecimal"

**Comment by srchase** [comment]
@thomasedwards 

Refer to the explanation [here](https://github.com/aws/aws-sdk-ruby/issues/1841#issuecomment-408161546):

> So for some background on this, since a DynamoDB numeric can be integers or float-type numbers, BigDecimal allows us to have a consistent return type for numeric attributes...
> 
> Libraries like aws-record will do this for you, if you define your attributes as specifically integer or float type.

**Comment by thomasedwards** [comment]
Ah! Feature not a bug 😉 Will take a look at aws-record, thanks.
