### ISSUE TITLE
Migrate DynamoDb attribute_value.rb BigDecimal fix to 2.11.x releases

### ISSUE THREAD

**Issue by esilverberg** [aws/aws-sdk-ruby#2038]
Please fill out the sections below to help us address your issue

### Issue description
dynamodb/attribute_value.rb is not ported to the latest 2.X releases

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
This file: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-dynamodb/lib/aws-sdk-dynamodb/attribute_value.rb

Should be here:
https://github.com/aws/aws-sdk-ruby/blob/v2.11.268/aws-sdk-core/lib/aws-sdk-core/dynamodb/attribute_value.rb

* * *

I just upgraded to Ruby 2.6, and it is causing my nginx error log to vomit warnings about mis-use of BigDecimal, because it is calling BigDecimal.new, which it does not like as of Ruby 2.6

### Version of Ruby, OS environment
Ruby 2.6

### Code snippets / steps to reproduce
https://github.com/aws/aws-sdk-ruby/blob/v2.11.268/aws-sdk-core/lib/aws-sdk-core/dynamodb/attribute_value.rb#L84

Should be BigDecimal(

**Comment by cjyclaire** [comment]
Thanks for the report! I'll work on port over the fix to v2

**Comment by cjyclaire** [comment]
PR has been merged, will be available in the next release
