### ISSUE TITLE
monkey patching `net:http` violates basic design principles

### ISSUE THREAD

**Issue by dayglojesus** [aws/aws-sdk-ruby#2039]
### Issue description

The following code patches Ruby core:

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/net_http/patches.rb#L11-L27

Patching Ruby core in an external gem violates some basic design principles and will inevitably lead to the kinds of situations described below.

### Gem name 

`aws-sdk-core`, all versions

### Version of Ruby

All versions, all platforms.

### Code snippets / steps to reproduce

Please see the issue filed here wherein the application of this patch has considerable consequences beyond the scope of the `aws-sdk`

https://github.com/chef/chef/issues/8466

### Related 

It would appear this has been a point of contention for some time...
aws/aws-sdk-ruby#1167
aws/aws-sdk-ruby#1752
aws/aws-sdk-ruby#1979

**Comment by cjyclaire** [comment]
@dayglojesus The reason for introducing the patch originally is for fixing Net:HTTP client bugs #1167 and we had submitted/contributed to Net:HTTP for the patch fix as well, with those fixes merged/released gradually, we keeps updating our patch only for old Ruby Versions requiring the fixes there #1752 #1979 (as fixes are not back portable to older versions).

Agreed that monkey patching is not an ideal/recommended approach in general, but at the time when the patches were introduced, it's for fixing critical functionalities that API requests rely on. As you can see there, with the patch updates #1725, #1979, Ruby version >= 2.5 no longer go through the patch, are we are keeping narrowing versions requires the patch.

If you notice any more versions that do not need the patch, happy to see references and keep narrowing our patched versions, thanks!

**Comment by cjyclaire** [comment]
closing due to inactiveness, feel free to reopen with further comments
