### ISSUE TITLE
cannot load such file -- aws-sdk-core/plugins/transfer_encoding.rb

### ISSUE THREAD

**Issue by raykov** [aws/aws-sdk-ruby#2046]
### Issue description
Wrong dependency in `aws-sdk-sqs.gemspec`. 

```bash
cannot load such file -- aws-sdk-core/plugins/transfer_encoding.rb
```

Guys, you recently updates `aws-sdk-core` and `aws-sdk-sqs`

* You have added a new plugin to `sdk-core` [transfer_encoding](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/transfer_encoding.rb)
* And used this plugin in new version of `sdk-sqs` [require 'aws-sdk-core/plugins/transfer_encoding.rb'](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-sqs/lib/aws-sdk-sqs/client.rb#L26)
* **BUT** you left old dependency in [aws-sdk-sqs.gemspec](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-sqs/aws-sdk-sqs.gemspec#L26) to `'aws-sdk-core', '~> 3', '>= 3.48.2'` (**This plugin was just added and doesn't exist in old versions**)
* **NOW** it should be `'aws-sdk-core', '~> 3', '>= 3.52.0'`
* And if someone updates to new version of sdk-sqs (with sdk-core locked to v3.48.2) -> he has troubles. 

### Gem name 

`aws-sdk-sqs` v1.14.0
probably other gems which are using `transfer_encoding` plugin from `sdk-core`

**Comment by cjyclaire** [comment]
Thanks for the contribution! PR has been merged will be out in the next release

**Comment by scottsuch** [comment]
Did this go out with the `v2.11.275` release?

**Comment by cjyclaire** [comment]
@scottsuch This should be affecting v3 only, not for v2.

Today's v3 release is out, all latest versions of service gems right now are with the change.
closing, feel free to reopen if you see further issues, thanks!

**Comment by gauravonekingslane** [comment]
hi 
I am getting the error - `cannot load such file ruby/2.3.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/log/formatter (LoadError)` when updating `aws-sdk` to version '~> 3'.
As recommend before gem 'aws-sdk', '~> 3', I set up the gem 'aws-sdk-core', '~> 3', '>= 3.52.0' but still same error `cannot load such file -- vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/log/formatter (LoadError)` . cc @cjyclaire

**Comment by cjyclaire** [comment]
@gauravonekingslane your issue is different, log formatter has been in v3 since day one.
if you are just using s3, your gemfile can be just
```
gem 'aws-sdk-s3'
```
