### ISSUE TITLE
Latest version of S3 client depends on latest version of kms

### ISSUE THREAD

**Issue by dnorth98** [aws/aws-sdk-ruby#2048]
Please fill out the sections below to help us address your issue

### Issue description

Since yesterday, we now get 

`/opt/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-kms-1.19.0/lib/aws-sdk-kms/client.rb:26:in `require': cannot load such file -- aws-sdk-core/plugins/transfer_encoding.rb (LoadError)`

We're including in our Gemfile:

```
 'aws-sdk-autoscaling', '~> 1.20.0'
 'aws-sdk-cloudwatch', '~> 1.19.0'
 'aws-sdk-core', '~> 3.48.3'
 'aws-sdk-ec2', '~> 1.78.0'
 'aws-sdk-s3', '~> 1.36.0'
 'aws-sdk-sns', '~> 1.12.0'
 'aws-sdk-sqs', '~> 1.13.0'
```
We've found that adding:

`'aws-sdk-kms', '~> 1.17.0'` to the spec seems to resolve the issue (I suspect that `'aws-sdk-kms', '~> 1.18.0'` would also work.

We think there may be some incompatability with the s3 client and the kms client since the s3 client just pulls in kms ~> 1.0.0

### Version of Ruby, OS environment

Ruby 2.6.3 on AWS Linux (actually Elastic Beanstalk's ruby container)

**Comment by cjyclaire** [comment]
This has been [fixed](https://github.com/aws/aws-sdk-ruby/commit/2d1543000b39063b135d1f96b5109f37bef828dd) in the latest version of [`aws-sdk-s3`](https://rubygems.org/gems/aws-sdk-s3/versions/1.38.0) (1.38.0), can you try the latest version and let me know if the issue persist?

**Comment by dnorth98** [comment]
Yep, that does it.  I also noticed this good nugget in the readme:

```
With version 3 modularization, you can also pick the specific AWS service gem to install. Please use a major version when expressing a dependency on service gems.

gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-ec2', '~> 1'
```

So we'll adjust our gemspec accordingly to not pin to a minor version anymore.

Thanks!
