### ISSUE TITLE
Plain text CloudFormation template validation

### ISSUE THREAD

**Issue by morganrowse** [aws/aws-sdk-ruby#2052]
### Issue description
Hi there,
Currently working on a script to validate a bunch of CloudFormation templates.
I am however unsure of the security of how the SDK interacts with the API for validating templates, I don’t wish to send templates without SSL and I cannot determine if that is the case.

I have seen [this doc](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html#why-requests-are-signed) on signing API requests as well as [this doc](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_query-requests.html#IAMHTTPSRequired) on using access keys to secure HTTPS requests. Also [this line of code](https://github.com/aws/aws-sdk-ruby/blob/527576e790d4d9e349373df21b03442af39ebc96/gems/aws-sdk-cloudformation/lib/aws-sdk-cloudformation/client_api.rb#L1562) on creating the validate template API call. I still cannot reach a conclusion on how templates are sent during these API calls.

### Gem name and version
`aws-sdk-cloudformation (1.21.0)`

### Version of Ruby, OS environment
`ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]`
`Ubuntu 16.04`

### Code snippets
Here is my snippet so far (It works, I just don't know if its secure)
```ruby
require 'find'
require 'aws-sdk-cloudformation'

def cloudformation
  @cloudformation ||= Aws::CloudFormation::Client.new(region: "us-west-1")
end

@cfnTemplates = []
Find.find('cfn-templates') do |path|
  @cfnTemplates << path if path =~ /.*\.json$/ || path =~ /.*\.template$/
end

@cfnTemplates.each do |path|
  @c = File.read(path)
  begin
    @r = cloudformation.validate_template({template_body: @c})
  rescue Aws::CloudFormation::Errors::ValidationError => e
    p "[Error] #{path} #{e.message}"
    exit (e.message == "Invalid Template.") ? 0 : 1
  end

  print "."
end
```
and here is an outgoing request picked up via `https://github.com/trusche/httplog` showing 443 over HTTP
```json
{
  "method": "POST",
  "url": "http://cloudformation.us-west-1.amazonaws.com:443/",
  "request_body": null,
  "request_headers": {
    "content-type": "application/x-www-form-urlencoded; charset=utf-8",
    "accept-encoding": "",
    "user-agent": "aws-sdk-ruby3/3.52.1 ruby/2.5.5 x86_64-linux-gnu aws-sdk-cloudformation/1.21.0",
    "host": "cloudformation.us-west-1.amazonaws.com",
    "x-amz-date": "<date_here>",
    "x-amz-content-sha256": "<sha_key_here>",
    "authorization": "<authorization_here>",
    "content-length": "<content_length_here>",
    "accept": "*/*"
  },
  "response_code": 200,
  "response_body": "(not available yet)",
  "response_headers": {
    "x-amzn-requestid": "<request_id>",
    "content-type": "text/xml",
    "content-length": "567",
    "date": "<date_here>"
  }
}
```
Does the `validate_template` function send CloudFormation templates over HTTP?

Thanks in advance.

**Comment by cjyclaire** [comment]
@morganrowse Every request is sigv4 signed by default unless service model told us not to (For the API you mentioned, it requires sigv4 signing as usual). Every request is HTTPS by default unless you turning it off when initializing the client by `:ssl_verify_peer => false`

**Comment by morganrowse** [comment]
I tried the `:http_wire_trace` setting and saw another HTTP request being logged however your mention of sigv4 lead me to the correct [docs on sigv4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) thank you for your assistance @cjyclaire
