### ISSUE TITLE
Structs containing a field called "members" break to_h

### ISSUE THREAD

**Issue by jeisen** [aws/aws-sdk-ruby#2053]
### Issue description
Due to the way the to_h method traverses a Struct, a Struct attribute that's named "members" (e.g. https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFront/Types/OriginGroup.html) ends up breaking, because `members` returns the sub-structure and not `Struct.members`.

https://github.com/aws/aws-sdk-ruby/blob/28a3e21975c0aa95063fffc5f4cfdc61fb0be7bd/gems/aws-sdk-core/lib/aws-sdk-core/structure.rb#L32

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk (3.0.1)
aws-sdk-core (3.52.1)
aws-sdk-cloudfront (1.17.0)

### Version of Ruby, OS environment
Ruby 2.3.8
macOS Mojave (10.14.3 (18D109))

### Code snippets / steps to reproduce
```
status_codes = Aws::CloudFront::Types::StatusCodes.new(
  quantity: 1,
  items: [1]
)

failover_criteria = Aws::CloudFront::Types::FailoverCriteria.new(
  status_codes: status_codes
)

origin_group_members = Aws::CloudFront::Types::OriginGroupMembers.new(
  quantity: 1,
  items: [{origin_id: 'origin-id'}]
)

origin_group = Aws::CloudFront::Types::OriginGroup.new(
  id: "ogroup-id",
  failover_criteria: failover_criteria,
  members: origin_group_members
)

origin_group.to_h
```

**Comment by cjyclaire** [comment]
I can reproduce this, taking a look

**Comment by cjyclaire** [comment]
PR addressing this issue has been opened and under review

**Comment by cjyclaire** [comment]
fix has been merged and released in latest version of core gem, [`aws-sdk-core 3.53.1`](https://rubygems.org/gems/aws-sdk-core/versions/3.53.1)
