### ISSUE TITLE
transcribestreamingservice Issue

### ISSUE THREAD

**Issue by SharmaBiswadev** [aws/aws-sdk-ruby#2062]
**Issue Description** 

I am getting below while using transcribestreamingservice

 4: from stt.rb:55:in `<main>'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-transcribestreamingservice-1.5.0/lib/aws-sdk-transcribestreamingservice/event_streams.rb:21:in `signal_audio_event_event'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-core/event_emitter.rb:41:in `emit'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-core/event_emitter.rb:56:in `_ready_for_events?'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-**core/event_emitter.rb:56:in `pop': No live threads left. Deadlock? (fatal)**
1 threads, 1 sleeps current:0x00000000034418e0 main thread:0x00000000006ad4b0
* #<Thread:0x0000000002b5e1c0 sleep_forever>
   rb_thread_t:0x00000000006ad4b0 native:0x000000000000026c int:1
   C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-core/event_emitter.rb:56:in `pop'
   C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-core/event_emitter.rb:56:in `_ready_for_events?'
   C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/aws-sdk-core/event_emitter.rb:41:in `emit'
   C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sdk-transcribestreamingservice-1.5.0/lib/aws-sdk-transcribestreamingservice/event_streams.rb:21:in `signal_audio_event_event'
   stt.rb:55:in `<main>' 

### Code snippets / steps to reproduce
```
require 'aws-sdk'
require 'wavefile'
include WaveFile

FILES_TO_APPEND = ['audio.wav']

Writer.new("myvoice.wav", Format.new(:stereo, :pcm_16, 44100)) do |writer|
  FILES_TO_APPEND.each do |file_name|
    Reader.new(file_name).each_buffer do |buffer|
      writer.write(buffer)
    end
  end
end

begin
async_client = Aws::TranscribeStreamingService::AsyncClient.new(
  region:'us-east-1',
  http_wire_trace:true
  )
 print async_client.operation_names
 output_stream = Aws::TranscribeStreamingService::EventStreams::TranscriptResultStream.new
 input_stream = Aws::TranscribeStreamingService::EventStreams::AudioStream.new
 audio_file = File.new('myvoice.wav','rb')

# Register callbacks
output_stream.on_transcript_event_event do |event|
  print event.transcript.results
    unless event.transcript.results.empty?
        event.transcript.results.each do |result|
            result.alternatives.each {|alter| puts alter.transcript.inspect }
        end
  end
end
output_stream.on_bad_request_exception_event do |exception|
    input_stream.signal_end_stream
end

# Make an async call
async_resp = async_client.start_stream_transcription(
    language_code: "en-US",
    media_encoding: "pcm",
    media_sample_rate_hertz: 8000,
    input_event_stream_handler: input_stream,
    output_event_stream_handler: output_stream
)

output_stream.on_event {|event| print event}

# output_stream.on_error_event {|error| print error}
# You can call #join! after some time passes, which would end the stream immediately
# => Aws::Seahorse:Client::Response
while !audio_file.eof? do
    input_stream.signal_audio_event_event(audio_chunk: audio_file.read(5000))
    sleep(1)
end
sleep(0.5)
input_stream.signal_end_stream
audio_file.close
  
sync_resp=async_resp.wait
sync_resp = async_resp.join!
print sync_resp

rescue Aws::TranscribeStreamingService::Errors::ServiceError
  # rescues all service API errors
end
```

**Comment by cjyclaire** [comment]
I'm guessing the `slience.wav` is from https://github.com/aws/aws-sdk-ruby/tree/master/gems/aws-sdk-transcribestreamingservice/features? I'm using the same script provided using latest transcribe streaming service gem and cannot reproduce the issue.

To help with further debugging , could you try set `:http_wire_trace` at the client to see wire logs? note, the log could be long, might consider have the log output to file. Also, mind sharing your ruby version, openssl version as well?

For the error message provided, seems like initial service 200 response is [never arrived](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/event_emitter.rb#L53), wire trace probably will shed some lights on that.

**Comment by SharmaBiswadev** [comment]
@cjyclaire , I have put http_wire_trace: true and got some issue related permission, so I tried the same silence.wav and also another audio converted to pc16kHz rate with 16-bit linear PCM encoding,
But got the `event.transcript.results.empty` [] i.e. empty array

**Output** of `output_stream.on_event {|event| print event}`

`{:transcript=>{:results=>[]}, :event_type=>:transcript_event}`

**Comment by cjyclaire** [comment]
Service may returning empty events,  it can be related to the audio file contents, this is more a service API behavior not something SDK can control, I'd suggest checking [`input parameters`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/TranscribeStreamingService/AsyncClient.html#start_stream_transcription-instance_method) make sure they are reflecting accurate audio file status, and you may seek for help from [AWS Support](https://console.aws.amazon.com/support/home) for direct contact from service team.

**Comment by SharmaBiswadev** [comment]
The audio was chrome recorded audio with 48khz, it must be downsampled to 16khz
I used the following code to downsample [reference](https://forums.aws.amazon.com/message.jspa?messageID=783294)
i have used [recorderjs](https://github.com/mattdiamond/Recorderjs) to record audio,then downsampled it
```
 function downsampleBuffer(buffer) {
          if (16000 === sampleRate) {
            return buffer;
          }
      var sampleRateRatio = sampleRate / 16000;
      var newLength = Math.round(buffer.length / sampleRateRatio);
      var result = new Float32Array(newLength);
      var offsetResult = 0;
      var offsetBuffer = 0;
      while (offsetResult < result.length) {
        var nextOffsetBuffer = Math.round((offsetResult + 1) * sampleRateRatio);
        var accum = 0,
          count = 0;
        for (var i = offsetBuffer; i < nextOffsetBuffer && i < buffer.length; i++) {
          accum += buffer[i];
          count++;
        }
        result[offsetResult] = accum / count;
        offsetResult++;
        offsetBuffer = nextOffsetBuffer;
      }
      return result;
    }
```
