### ISSUE TITLE
Spurious S3 client configuration warning

### ISSUE THREAD

**Issue by dduugg** [aws/aws-sdk-ruby#2063]
### Issue description
Including `use_accelerate_endpoint: true` in a `list_objects` request leads to spurious client configuration warnings:

S3 client configured for "us-west-2" but the bucket "my-bucket" is in "us-west-2"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`aws-sdk` 2.11.185

### Version of Ruby, OS environment
Ruby 2.4.3
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1083-aws x86_64)

### Code snippets / steps to reproduce
To reproduce:
```ruby
resp = Aws::S3::Resource.new(
  http_proxy: MY_PROXY,
  region: 'us-west-2'
)
.client
.list_objects(
  bucket: 'my-bucket',
  delimiter: '/',
  prefix: MY_PREFIX,
  use_accelerate_endpoint: true,
);
prefixes = resp.common_prefixes.map(&:prefix);
while !resp.last_page?
  resp = resp.next_page
  prefixes.concat(resp.common_prefixes.map(&:prefix));
end
```
Commenting out `use_accelerate_endpoint: true` will cause the warnings to disappear

**Comment by cjyclaire** [comment]
Interestingly, I cannot reproduce the warning locally, might need to test with proxy.
`use_accelerate_endpoint` does apply changes to request endpoint, but it does not touch region information at all. This warning is triggered only when retry is [happening](https://github.com/aws/aws-sdk-ruby/blob/version-2/aws-sdk-core/lib/aws-sdk-core/plugins/s3_request_signer.rb#L102) under wrong sigv4 region error.

To help further debugging with this, mind enabling `http_wire_trace` to `true` at client for wire log traces? It could contain information for every request attempt.

**Comment by dduugg** [comment]
Hi @cjyclaire, thanks for the reply. Is this enough to work with?
```
opening connection to myproxy.example.com:4750...
opened
<- "CONNECT my-bucket.s3-accelerate.amazonaws.com:443 HTTP/1.1\r\nHost: my-bucket.s3-accelerate.amazonaws.com:443\r\n\r\n"
-> "HTTP/1.0 200 OK\r\n"
-> "\r\n"
starting SSL for myproxy.example.com:4750...
SSL established
<- "GET /?delimiter=%2F&encoding-type=url&prefix= HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.11.185 ruby/2.4.3 x86_64-linux resources\r\nX-Amz-Date: 20190625T000851Z\r\nHost: my-bucket.s3-accelerate.amazonaws.com # etc.
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Content-Type: application/xml\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Connection: keep-alive\r\n"
-> "x-amz-bucket-region: us-west-2\r\n"
-> "x-amz-request-id: 1E6DDDA811CFC8B3\r\n"
-> "x-amz-id-2: zya3paD1T9+wxwTVPOnzP58cEpDme9i6pOYoVliIWK/6BXdd2isxNroNG6A9aCp5PAEXmdp9FN8=\r\n"
-> "Date: Tue, 25 Jun 2019 00:08:52 GMT\r\n"
-> "Server: AmazonS3\r\n"
-> "X-Cache: Error from cloudfront\r\n"
-> "Via: 1.1 5afc8eca980390e71a86518c6f90001a.cloudfront.net (CloudFront)\r\n"
-> "X-Amz-Cf-Pop: SEA19\r\n"
-> "X-Amz-Cf-Id: RY786O3XY-iYxlgineOUjhow5tDmrKY4zozru2BY4jqN8K0VaTAQJw==\r\n"
-> "\r\n"
-> "121\r\n"
reading 289 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>S3 Transfer Acceleration is not configured on this bucket</Message><RequestId>1E6DDDA811CFC8B3</RequestId><HostId>zya3paD1T9+wxwTVPOnzP58cEpDme9i6pOYoVliIWK/6BXdd2isxNroNG6A9aCp5PAEXmdp9FN8=</HostId></Error>"
read 289 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn keep-alive
S3 client configured for "us-west-2" but the bucket "my-bucket" is in "us-west-2"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts
```

**Comment by cjyclaire** [comment]
thanks for the wire log, you can see from there from the 400 response
```
-> "x-amz-bucket-region: us-west-2\r\n"
```
which is indicating the region that server side is expecting, (which is different from what detected)
Since proxy is playing the middle man there (even if SDK set the region correctly), SDK doesn't have control over it's communication to s3 service, you might need to check the proxy setup (any region hard code there?), also [AWS Support](https://console.aws.amazon.com/support/home) would help with server side behavior investigating.

**Comment by cjyclaire** [comment]
Closing due to inactiveness, feel free to reopen with further information : )
