### ISSUE TITLE
Unknown validation error response from mturk

### ISSUE THREAD

**Issue by railsvijay** [aws/aws-sdk-ruby#2065]
### Version of Ruby, ruby 2.3.7p456 

`[Aws::MTurk::Client 400 0.056615 0 retries] update_expiration_for_hit(hit_id:"3TX9T2ZCB9V8XRMJ7M3JT83CUQQWZ3",expire_at:2019-06-05 08:00:10 +0000)`
`Aws::MTurk::Errors::ParameterValidationError The value -380572 is invalid for ExpirationIncrementInSeconds. Valid values range from 60 to 31536000. (1559721610045) `

According to the [API Doc](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MTurk/Client.html#update_expiration_for_hit-instance_method) we can pass past time also for immediate expiry.

As mentioned in the Doc we just passed **Time.now**

`params = {hit_id: hit_id, expire_at: Time.now}`
`res = mturk_client.update_expiration_for_hit(params)` 

I need to help to solve this issue.

**Comment by railsvijay** [comment]
Above error response happening in random. Like 1/10 requests only. 

Now It is happening for all requests when I increase **expire_at** Like `Time.now + 30.seconds` 
And it is working fine When I decrease **expire_at** like `Time.now - 30.seconds`

**Comment by cjyclaire** [comment]
Sounds like a service API behavior question instead of specific SDK issue, feel free to cut ticket to [AWS Support](https://console.aws.amazon.com/support/home) with communicate with service team directly, they can help clarifying API behavior design and documentation updates from upstream
