### ISSUE TITLE
Passing no endpoint vs passing endpoint: nil behaves differently when initializing client

### ISSUE THREAD

**Issue by blowfishpro** [aws/aws-sdk-ruby#2066]
### Issue description

Passing no `endpoint` when initializing the S3 client (and likely others) causes it to correctly determine the endpoint based on the region.  Passing `endpoint: nil` causes an argument error that the endpoint is required.

### Gem name

aws-sdk-s3 version 1.42.0

### Version of Ruby, OS environment

Ruby Version: 2.6.3
OS: Mac OS X 10.14.5 (18F132)

### Code snippets / steps to reproduce

This works:
```
> Aws::S3::Client.new(credentials: Aws::Credentials.new('abc', 'def'), region: 'us-east-1')
 => #<Aws::S3::Client> 
```

This fails:
```
> Aws::S3::Client.new(credentials: Aws::Credentials.new('abc', 'def'), region: 'us-east-1', endpoint: nil)
ArgumentError (missing required option `:endpoint')
```

The reason we're doing it this way is that the client is being initialized from some configuration, so we're not actually passing `endpoint: nil`, but more like `endpoint: config.s3.endpoint` which may be `nil` or not depending on the environment.

The order of `region` and `endpoint` does not appear to matter.

**Comment by cjyclaire** [comment]
A bit background for this, `:endpoint` option is intended for overriding default endpoint resolving logic, thus SDK is validation whatever input provided to make sure it's a [valid input](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/plugins/endpoint.rb#L25).

So, once the `:endpoint` option is provided, it's already overridden, and the default pattern is no longer available.

Is the `nil` value checkable from your side when passing it?

**Comment by blowfishpro** [comment]
It's possible but additional code.  Instead of just building the client it requires building the options hash and conditionally adding the `endpoint` key.  Compare:
```ruby
client = Aws::S3::Client.new(
  credentials: config.s3.credentials,
  region: config.s3.region,
  endpoint: config.s3.endpoint,
  force_path_style: config.s3.force_path_style
)
```
vs
```ruby
client_options = {
  credentials: config.s3.credentials,
  region: config.s3.region,
  force_path_style: config.s3.force_path_style
}

client_options[:endpoint] = config.s3.endpoint if config.s3.endpoint

client = Aws::S3::Client.new(client_options)
```

It's definitely messier

**Comment by cjyclaire** [comment]
True, tagging this as an enhancement for SDK

**Comment by mullermp** [comment]
Have you tried using [Object#tap](https://ruby-doc.org/core-2.6.3/Object.html#method-i-tap)? You could build the hash conditionally.

```
client_options = Hash.new.tap do |hash|
  hash[:credentials] = config.s3.credentials,
  hash[:region] = config.s3.region,
  hash[:force_path_style] = config.s3.force_path_style,
  hash[:endpoint] = config.s3.endpoint if config.s3.endpoint
end

client = Aws::S3::Client.new(client_options)
```

**Comment by blowfishpro** [comment]
It can be reduced down to one extra statement yeah, so it's not that much of a burden

**Comment by mullermp** [comment]
Agreed. I am going to close this then.
