### ISSUE TITLE
cannot load such file -- vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/log/formatter

### ISSUE THREAD

**Issue by gauravonekingslane** [aws/aws-sdk-ruby#2069]
Could not spawn process for application /foo/rails/current: An error occurred while starting up the preloader.
Message from application: cannot load such file -- /foo/rails/releases/20190656789/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/log/formatter (LoadError)

Gemfile
```
gem 'aws-sdk-s3', '~> 1'
```

Gemfile.lock
```
aws-eventstream (1.0.3)
    aws-partitions (1.174.0)
    aws-sdk-core (3.54.2)
      aws-eventstream (~> 1.0, >= 1.0.2)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.21.0)
      aws-sdk-core (~> 3, >= 3.53.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.42.0)
      aws-sdk-core (~> 3, >= 3.53.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.1.0)
```
`aws-sdk-core ~> 3` is always creating a problem when application is loading in Production.

**Comment by cjyclaire** [comment]
taking dependency as:
```
gem 'aws-sdk-s3', '~> 1'
```
looks fine to me, as I cannot reproduce locally by just installing s3 gem, to double check, is the issue that you cannot use the gem in your code because of loading issue? (As a side note, the file loading error points to hasn't been touched for a while)

**Comment by gauravonekingslane** [comment]
@cjyclaire I am not using `gem 'aws-sdk-core' ~> 3` but `gem 'aws-sdk-s3'` have depdency on `aws-sdk-core`.  Application is working fine in development mode but on Production, gems are installed in `vendor/bundle` directory. 
Issue is that `cannot load such file -- vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/log/formatter`. (LoadError)
Rails application is not starting.

**Comment by cjyclaire** [comment]
still cannot reproduce the issue, might check if there is multiple version of SDK exists in your environment? Can you reproduce the issue with SDK gems alone (not in rails)?

**Comment by ulisescarreonalvarez** [comment]
I have the same problem i jus put 'aws-sdk-s3'  on my Gemfile and after user bundle install and restart my app it shows:

`**Could not spawn process for application /var/www/merci-admin: The application encountered the following error: Could not find aws-partitions-1.177.0 in any of the sources (Bundler::GemNotFound)**`

**Comment by cjyclaire** [comment]
Does the issue still persist? Do you have a small code script to reproduce the issue with SDK alone?

Tagging this as closing soon if no response

**Comment by AsfaMumtaz24** [comment]
Did anyone manage to solve this? I'm having the same issue.

**Comment by mullermp** [comment]
What versions are in your Gemfile.lock? Does the problem exist only in rails?

**Comment by AsfaMumtaz24** [comment]
> What versions are in your Gemfile.lock? Does the problem exist only in rails?

My Gemfile conatins **gem 'aws-sdk-s3', '~> 1'** and Gemfile.lock contains

    aws-eventstream (1.1.0)
    aws-partitions (1.323.0)
    aws-sdk-core (3.97.1)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.239.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.33.0)
      aws-sdk-core (~> 3, >= 3.71.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.67.1)
      aws-sdk-core (~> 3, >= 3.96.1)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
    aws-sigv4 (1.1.4)
      aws-eventstream (~> 1.0, >= 1.0.2)

Mine is a sinatra app that runs fine locally and throws error in production env.

**Comment by alextwoods** [comment]
I'm less familiar with Sinatra - but are you using anything like [Bootsnap](https://github.com/Shopify/bootsnap) that might affect gem loading?  Its interesting - log/formatter is far from the first file we require in [aws-sdk-core.rb ](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core.rb#L43).

Do you have any deeper stack trace?  Do you have any difference in config between development and production?

**Comment by AsfaMumtaz24** [comment]
I'm not using Bootsnap or any such thing.  Yes. Other files DO get loaded. It just throws my an error when it reaces this particular file. Which is very odd.

**Comment by AsfaMumtaz24** [comment]
Here's a deeper trace:
cannot load such file -- /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core/log/formatter (LoadError)
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core.rb:41:in `require_relative'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core.rb:41:in `<top (required)>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-kms-1.33.0/lib/aws-sdk-kms.rb:8:in `<top (required)>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3.rb:8:in `<top (required)>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
  config.ru:8:in `block in <main>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:96:in `eval'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:96:in `preload_app'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:142:in `<module:App>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:13:in `<module:PhusionPassenger>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:12:in `<main>'

**Comment by AsfaMumtaz24** [comment]
Here:

`cannot load such file -- /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core/log/formatter (LoadError)
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core.rb:41:in `require_relative'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-core-3.97.1/lib/aws-sdk-core.rb:41:in `<top (required)>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-kms-1.33.0/lib/aws-sdk-kms.rb:8:in `<top (required)>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3.rb:8:in `<top (required)>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
  config.ru:8:in `block in <main>'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/html/api/releases/2f18f490758b35697d9be6d62b731c1f/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:96:in `eval'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:96:in `preload_app'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:142:in `<module:App>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:13:in `<module:PhusionPassenger>'
  /opt/nginx-passenger-ruby/embedded/lib/ruby/gems/2.1.0/gems/passenger-enterprise-server-4.0.59/helper-scripts/rack-preloader.rb:12:in `<main>'

`

**Comment by mullermp** [comment]
It may also help to upgrade to the latest SDK version (and also upgrade from EOL ruby 2.1 to a newer version). If I had to guess, it's related to backports. We can take a closer look.
