### ISSUE TITLE
aws-federation login

### ISSUE THREAD

**Issue by shubhamsharma31** [aws/aws-sdk-ruby#2071]
how we do aws federation login with aws access keys? Can is it possible with this gem?

**Comment by cjyclaire** [comment]
> login with aws access keys

Are you looking for how to provide credentials for thre SDK client?
https://github.com/aws/aws-sdk-ruby#configuration
Beside default credential chain, you may provide assume role directly:
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/AssumeRoleCredentials.html

**Comment by shubhamsharma31** [comment]
@cjyclaire Thanks for your help. I have try this in different manner and facing once issue regarding policy so can you please tell us that what are the basic persmission required for policy that i used for getting the sts  get_federation_token. 
 I have try this code:- 
sts = Aws::STS::Client.new(
  region: "test-region",
  credentials: AwsClients::Credentials.client(
        "Access Key", "Secret Key"
      )
)

session = sts.get_federation_token({
  duration_seconds: 1800,
  name: "user_name",
  policy: "{\"Version\":\"2012-10-17\",\"Statement\":{\"Effect\":\"Allow\",\"Action\":\"sns:*\",\"Resource\":\"*\"}}",
})
 So here for this policy what basis permissions required can you please tell us.
