### ISSUE TITLE
AWS Batch fail to override environment variable

### ISSUE THREAD

**Issue by fifiteen82726** [aws/aws-sdk-ruby#2074]
### Issue description
Fail to set the environment variable via `Aws::Batch::Client`

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
```
aws-sdk 3.0
```

### Version of Ruby, OS environment
```
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

### Code snippets / steps to reproduce
The following works!

```ruby
resp = client.submit_job({
  job_name: "Test", # required
  job_queue: "queue2", # required
  job_definition: "push-to-s3:2", # required
  container_overrides: {
    environment: [
      {
        name: "String",
        value: "String"
      }
    ]
  }
})
```

However, if I changed the environment variable to a different name, it failed.
For example :

```ruby
resp = client.submit_job({
  job_name: "Test", # required
  job_queue: "queue2", # required
  job_definition: "push-to-s3:2", # required
  container_overrides: {
    environment: [
      {
        example: "fail"
      }
    ]
  }
})
```

Error Message

```bash
ArgumentError: unexpected value at params[:container_overrides][:environment][0][:example]
from /var/lib/gems/2.5.0/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/param_validator.rb:33:in `validate!'
```

Doc https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Batch/Client.html#submit_job-instance_method

>`:container_overrides` (Types::ContainerOverrides) — A list of container overrides in JSON format that specify the name of a container in the specified job definition and the overrides it should receive. You can override the default command for a container (that is specified in the job definition or the Docker image) with a command override. You can also override existing environment variables (that are specified in the job definition or Docker image) on a container or add new environment variables to it with an environment override.

**Comment by cjyclaire** [comment]
Could you try:
```
container_overrides: {
    environment: [
      {
        name: "example",
        value: "fail"
      }
    ]
  }
```

**Comment by fifiteen82726** [comment]
@cjyclaire 

It passed and submitted jobs successfully. For some reasons, it seems I can only submit the variable called `name` and `value`.

**Comment by fifiteen82726** [comment]
I just tried the latest version of `aws-sdk-batch` (1.21.0) and it still failed.

**Comment by cjyclaire** [comment]
Yeah, documentation should be more clearer about this,  `name` means environment variable name and `value` means environment variable value.

**Comment by cjyclaire** [comment]
@fifiteen82726 failed using which snippet? it's expected that
```
 {
        example: "fail"
      }
```
should be failing

**Comment by fifiteen82726** [comment]
Ok....I get it.  So if I have a bunch of variables. I need to pass as an array contains `{name: 'xxx', value: xxx}` for each of them

**Comment by cjyclaire** [comment]
Yep, correct.
Closing, feel free to reopen with further comments :D
