### ISSUE TITLE
`Aws::S3::Object#copy_to` error when providing `content_length` with `multipart_copy: false`

### ISSUE THREAD

**Issue by dduugg** [aws/aws-sdk-ruby#2077]
Please fill out the sections below to help us address your issue

### Issue description
Providing a `content_length` to `Aws::S3::Object#copy_to` with `multipart_copy: false` results in:
`ArgumentError: unexpected value at params[:content_length]`
Removing `content_length` or setting `multipart_copy` to `true` resolves the issue. 
According to the [docs](https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#copy_to-instance_method), `content_length` is "Only used when `:multipart_copy` is `true`". The wording here could better signal that an `ArgumentError` will be raised (or better yet, `aws-sdk-ruby` could handle the combination of `content_length` with `multipart_copy: false` without raising an error.)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk (2.11.185)

### Version of Ruby, OS environment
ruby/2.4.3 x86_64-linux

### Code snippets / steps to reproduce
```ruby
source_object.copy_to(dest_object, multipart_copy: false, content_length: source_object.content_length)
```
leads to:
```
ArgumentError: unexpected value at params[:content_length]
```
while:
```ruby
source_object.copy_to(dest_object, multipart_copy: true, content_length: source_object.content_length)
```
prints
```
=> #<struct Aws::S3::Types::CompleteMultipartUploadOutput
  location=…
```

**Comment by cjyclaire** [comment]
Thanks for the feedback! tagging this as an enhancement.

**Comment by mullermp** [comment]
I've fixed the documentation here - https://github.com/aws/aws-sdk-ruby/commit/6f09eb3fbd627a0c77c00bcac04649198989c027. I'd prefer not to remove/ignore `content_length` (or other "invalid" params) because it defeats the purpose of the param validator.
