### ISSUE TITLE
Aws::S3::Bucket#exists? always returns true when credentials are wrong

### ISSUE THREAD

**Issue by BanzaiMan** [aws/aws-sdk-ruby#2078]
### Issue description

`Aws::S3::Bucket#exists?` returns `true` no matter what, when the credentials are invalid.

Looks like #205 has returned at *some* point in the past 6 years.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk` (3.0.1), `aws-sdk-s3` (1.22.0)

### Version of Ruby, OS environment

```
$ pry
[1] pry(main)> RUBY_DESCRIPTION
=> "ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]"
```

### Code snippets / steps to reproduce
```
$ pry
[1] pry(main)> require 'aws-sdk'
=> true
[2] pry(main)> Aws.config.update( region: 'eu-west-1', credentials:
[2] pry(main)* Aws::Credentials.new( "foobarbaz", "badkey"))
=> {:region=>"eu-west-1", :credentials=>#<Aws::Credentials access_key_id="foobarbaz">}
[3] pry(main)> s3=Aws::S3::Resource.new
=> #<Aws::S3::Resource:0x00007f8488ecb8f0 @client=#<Aws::S3::Client>>
[4] pry(main)> s3.bucket('i-am-a-bad-bucket-kakdajjeqjeqjz').exists?
=> true
```

If the credentials are correct, it responds reasonably.

```
[5] pry(main)> Aws.config.update( region: 'eu-west-1', credentials:
[5] pry(main)* Aws::Credentials.new( "*****", "*****"))
=> {:region=>"eu-west-1", :credentials=>#<Aws::Credentials access_key_id="*****">}
[6] pry(main)> s3=Aws::S3::Resource.new
=> #<Aws::S3::Resource:0x00007f848a8c9928 @client=#<Aws::S3::Client>>
[7] pry(main)> s3.bucket('i-am-a-bad-bucket-kakdajjeqjeqjz').exists?
=> false
```

**Comment by cjyclaire** [comment]
taking a look

**Comment by cjyclaire** [comment]
Update.

So the reason for the behavior is, when credentials is valid, if bucket not exist, it would return
```
[Aws::S3::Client 404 0.175365 0 retries] head_bucket(bucket:"yayayayya") Aws::S3::Errors::NotFound
```
When credentials is wrong
```
[Aws::S3::Client 403 0.160686 0 retries] head_bucket(bucket:"yayayayya") Aws::S3::Errors::Forbidden
```
The `#exists?` method is using `BucketExist` [waiter](https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/waiters-2.json#L20) that defines `403` as successful

**Comment by mullermp** [comment]
I've changed the waiter file and pushed it upstream. I will try and include it with one of S3's planned releases. Closing for now, thanks for submitting this.

**Comment by mullermp** [comment]
I've actually reverted my internal change. As it turns out, s3 can return 403 meaning "exists, but you don't have access" or "your signature is invalid". If I were to flip this to a failure mode, then customers using `exists?` to determine if a bucket does not exist can be breaking.

```
Aws> s3 = Aws::S3::Resource.new(region: 'us-west-2')
=> #<Aws::S3::Resource:0x00007fa57621a2c8 @client=#<Aws::S3::Client>>
Aws> s3.bucket('aws-apig-error-c2j-us-west-2').exists? # we own this bucket but in a different account
[Aws::S3::Client 403 0.096858 0 retries] head_bucket(bucket:"aws-apig-error-c2j-us-west-2") Aws::S3::Errors::Forbidden 
=> false
```
