### ISSUE TITLE
Catch-all for stub_responses?

### ISSUE THREAD

**Issue by thbar** [aws/aws-sdk-ruby#2083]
In test suites, I'm commonly using `stub_responses` in dynamic fashion, e.g:

```ruby
Aws.config[:stub_responses] = {
  get_parameter: -> (context) { ... },
  list_objects_v2: -> (context) { ... },
  ...
```

It is very easy, though to forget a scenario here (e.g. I'd use `get_object` but would not record it).

Is there a way (for debugging or safeguarding purposes during tests) to add a catch-all route here (something with a block, which would provide the context but also the call name e.g. `get_parameter`, if it's not already in the context)?

If there's not, it would be a great addition!

I thought about a work-around, too, which would help: if there is a way to list all the possible calls (`list_objects_v2`) in cross-objects fashion, then I would be able to create a fuller-hash with a default handler.

Is that doable?

**Comment by pchaganti** [comment]
👍

**Comment by cjyclaire** [comment]
Apologies for the delay and thanks for the feedback!

Currently, SDK allows you to access all [API Requests](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html#api_requests-instance_method) made from a stub client:
```
s3 = Aws::S3::Client.new(stub_responses: true)
s3.create_bucket(bucket: "foo")
s3.list_buckets

s3.api_requests.size # => 2
s3.api_requests # array of requests 
# =>[{:operation_name=>:create_bucket,
  :params=>{:bucket=>"foo", :create_bucket_configuration=>{:location_constraint=>"us-stubbed-1"}},
  :context=>
   #<Seahorse::Client::RequestContext:0x007f84a9a48960
....},{:operation_name=>:list_buckets,
 :params=>{},
 :context=>
  #<Seahorse::Client::RequestContext:0x007f84a99f3f00

```

**Comment by thbar** [comment]
@cjyclaire no need to apologise! So what you mean is the way to implement the check I'm looking for would be to go over that list, after the test has run, and assert that no unsupported call is there, is that correct?

**Comment by thbar** [comment]
Sorry - hit reply too soon! I could either do what I describe, or build the fuller hash I mentioned earlier out of that.

That will do perfectly - thank you!

**Comment by cjyclaire** [comment]
Correct ;) the `.api_requests` contains all requests made from the client as hashes.
Every request hash will have `:operation_name`, `:params` and `:context` available

**Comment by cjyclaire** [comment]
Closing, feel free to re-open with further comments : )
