### ISSUE TITLE
Waiter for :stack_delete_complete does not handle UPDATE_ROLLBACK_COMPLETE

### ISSUE THREAD

**Issue by olbrich** [aws/aws-sdk-ruby#2084]
Please fill out the sections below to help us address your issue

### Issue description

When using the `wait_until` to monitor the deletion of a stack, the waiter fails to recognize when the stack goes into the `UPDATE_ROLLBACK_COMPLETE` state.  This can happen when attempting to delete a stack that has an export that another stack is using.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-cloudformation 1.24.0

### Version of Ruby, OS environment

Ruby 2.6.1, MacOS 10.14.5

### Code snippets / steps to reproduce

Delete a CF Stack that has an export that is used by another CF stack.

```
    cloudformation_client.delete_stack(stack_name: stack_name)
    cloudformation.wait_until(:stack_delete_complete, stack_name: stack_name) do |w|
      w.before_attempt do
        print '.'
      end
    end
```

**Comment by cjyclaire** [comment]
Thanks for the report! True, waiter definition for [`StackDeleteComplete `](https://github.com/aws/aws-sdk-ruby/blob/master/apis/cloudformation/2010-05-15/waiters-2.json#L70) needs to be updated to include the `UPDATE_ROLLBACK_COMPLETE ` scenario.

**Comment by mullermp** [comment]
Hi @olbrich -- I went and added an UPDATE_ROLLBACK_COMPLETE scenario for StackDeleteComplete. It's committed upstream in an internal repository. When CloudFormation makes an API update, I will be sure to try and include that change. I am going to close this ticket.
