### ISSUE TITLE
Fetching metadata throws an error `Aws::S3::Errors::NotFound ()`

### ISSUE THREAD

**Issue by iamrahulroy** [aws/aws-sdk-ruby#2089]
Please fill out the sections below to help us address your issue

### Issue description
The issue is only with the file name with spaces in it.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
gem 'aws-sdk-s3', '~> 1.5.0'

gem 'aws-sdk-sns', '~> 1.1.0'

### Version of Ruby, OS environment
Ruby ruby-2.6.3
OSX 10.12.6

### Code snippets / steps to reproduce
```
message = JSON.parse response[:Message]
key = message['Records'][0]['s3']['object']['key']

creds = Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
region = 'us-east-1'

client = Aws::S3::Client.new(credentials: creds, region: region)

bucket = Aws::S3::Bucket.new(name: ENV['S3_BUCKET'], client: client)
s3_object = bucket.object(key)

s3_object.metadata
```

`s3_object.metadata` throws `Aws::S3::Errors::NotFound ()` error. Object has the metadata. I have confirmed it by looking at S3 console  web UI.

**Comment by cjyclaire** [comment]
I cannot reproduce this locally, if this is an existed object, even if there is no metadata, and empty `{}` should be returned, mind double checking bucket and key and region info? you can set `:http_wire_trace` to `true` at the client to see wire trace for debugging as well.

**Comment by iamrahulroy** [comment]
@cjyclaire I have traced the issue. S3 bucket is setup to notify the server. When the filename has space in it e.g `file name with space.png`, SNS notification replaces spaces with `+` sign. 

Do you think encoding the object key name like this `URI.encode(key)` and decoding on SNS notification like this `URI.decode(key)` will help? What's the recommended approach?

**Comment by cjyclaire** [comment]
Thanks for the information! tracking as the same feature request her https://github.com/aws/aws-sdk-ruby/issues/2035
