### ISSUE TITLE
Calling #to_json on Aws::ElasticTranscoder::Types::ListPresetsResponse results in throttling

### ISSUE THREAD

**Issue by davidarmstronglewis** [aws/aws-sdk-ruby#2091]
### Issue description
If you call `#list_presets` on an `Aws::ElasticTranscoder::Client` and call `to_json` on the response, you will be throttled by AWS.

### Gem name
aws-sdk-elastictranscoder (1.16.0)
aws-sdk-core (3.59.0)

### Version of Ruby, OS environment
Ruby: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`
macOS Mojave 10.14.6: `Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64`

### Code snippets / steps to reproduce

```ruby
client = Aws::ElasticTranscoder::Client.new(region: 'us-east-1')
presets = client.list_presets

json_repr = presets.to_json

# Aws::ElasticTranscoder::Errors::ThrottlingException:
# Your application is submitting requests to Amazon Elastic Transcoder faster than
# the maximum request rate.
```

**Comment by cjyclaire** [comment]
SDK wraps a pageable response for you, however `.to_json` is trying to fetch every page to give you a full result. Alternatively, you may iterate through it like following instead of fetching all at once
```
resp = client.list_presets
resp.next_page?
	page = resp.next_page
    # process page
end
```

**Comment by davidarmstronglewis** [comment]
That’s fine, my issue isn’t so much that I can’t get a full listing, I’m just not 100% on whether `#to_json` should be making network calls and results in throttling in this particular case. I opened this ticket because I wanted to bring it to your attention in case this wasn’t intentional behavior.

**Comment by cjyclaire** [comment]
Understood, at least our documentation could be more clear about how to handle pageable response and avoid the surprise there.

**Comment by mullermp** [comment]
This doesn't appear to throttle anymore.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/commit/7dafa9a2129472a51d2b589fe9baf40d419d7db3
