### ISSUE TITLE
undefined method `instances' for nil:NilClass in aws-sdk-ec2 instance.rb:307:in `load'

### ISSUE THREAD

**Issue by videlov** [aws/aws-sdk-ruby#2094]
### Issue description

From BOSH debug task log:
```Rescued Unknown: undefined method `instances' for nil:NilClass. backtrace: /var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/vendor/bundle/ruby/2.4.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/instance.rb:307:in `load'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/lib/cloud/aws/resource_wait.rb:166:in `block in for_resource'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/lib/cloud/aws/resource_wait.rb:165:in `for_resource'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/lib/cloud/aws/resource_wait.rb:26:in `for_instance'
/var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/lib/cloud/aws/instance.rb:53:in `wait_for_running'````

Code:
https://github.com/aws/aws-sdk-ruby/blob/63594ea3a1582ed2f654edcf9b4caffe6ef1faf0/gems/aws-sdk-ec2/lib/aws-sdk-ec2/instance.rb#L307

it seems that the AWS returns empty `reservations` on the`describe_instances` call (edited)

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
gem: aws-sdk-ec2
version: 1.36 (but code still the same in master)

### Version of Ruby, OS environment
Ruby-2.4.0, Ubuntu Xenial

### Code snippets / steps to reproduce
See aws-sdk-ec2/lib/aws-sdk-ec2/instance.rb in `def load` method.

**Comment by cjyclaire** [comment]
I can see that error would happen if enters the path there.

Quick follow up question:
How did you encounter this error? I tried to just calling instances
```
Aws::EC2::Resource.new.instances
#=> #<Aws::EC2::Instance::Collection:0x007fb9492c5ee8 @batches=#<Enumerator: ...>, @limit=nil, @size=nil>

# if tries to iterate
Aws::EC2::Resource.new(region: 'us-west-1').instances.batches.each {|i| puts i.inspect}
# => nil
```
but cannot reproduce the error there.

**Comment by xtreme-conor-nosal** [comment]
We haven't been able to consistently reproduce the issue. Our use case is creating a new instance, and then immediately starting to poll describe_instance to see if the VM is ready.

**Comment by cjyclaire** [comment]
@xtreme-conor-nosal Ah, good to know, for your use case, sounds like [waiter](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Client.html#wait_until-instance_method) is what you are looking for.
https://aws.amazon.com/blogs/developer/waiters/

**Comment by friegger** [comment]
To provide some more context, in the scenario this error occours the SDK is called from the BOSH AWS CPI, where [instance.load](https://github.com/cloudfoundry/bosh-aws-cpi-release/issues/99) is triggered. While a `waiter` might be an appropriate solution, the `load` method is provided by the sdk and the expectation is that it handles all respsonse from the API correctly.

Additionally, this code is running without errors for a long time. We see this error only since a few days on different accounts and regions and only sporadically. This might indicate that this might be an issue on the API side. Can you elaborate a little whether it is a valid scenario that the reservations are zero?

**Comment by cjyclaire** [comment]
Thanks for the information!
> We see this error only since a few days on different accounts and regions and only sporadically. 

It could be related to API latency diff, happy to communicate this message to service team. Yet, this is also one of top reasons we introduce `waiters`, some APIs could take longer and waiter performs polling for you.

> Can you elaborate a little whether it is a valid scenario that the reservations are zero?

It's valid that a `reservations` can be an empty array `[]`, for this scenarios, `.instances` should just represent an empty enumerable and shouldn't be trying to create/produce a single `instance` resource.

Understood that you would be expecting `reload` for the `instance` itself should handle those edge cases, while a hot fix can be applied to workaround this, I was looking for the usage scenario that expose this to make sure that we are fixing the root cause there instead of just applying the hot-fix.

**Comment by friegger** [comment]
Meanwhile the BOSH CPI has adoptet `waiters`: https://github.com/cloudfoundry/bosh-aws-cpi-release/issues/99

**Comment by hallerm** [comment]
We have also intermittently seen this issue while creating instances with the first occurrence starting on July 24.

At one time, we used `instance.wait_util`, but then we found that they would rarely raise `::Aws::EC2::Errors::InvalidInstanceIDNotFound` even after previously having seen the instance. I see that the waiters code looks designed to avoid this, so we will give waiters a shot too.

**Comment by jfmyers9** [comment]
Hi all,

So after digging into this further we think we have a better idea of how to reproduce this issue.

Right now it seems to occur when creating `c4` instances in the `us-east-1` region. In a deployment with 10 VMs of type `c4.large`, we see this failure every other time we recreate all of the VMs.

For context, we have also tried adding the `wait_until_exists` waiter to mitigate this issue, but we still see this failure, even when that waiter succeeds.

Thoughts?

@jfmyers9 && @belinda-liu

**Comment by cjyclaire** [comment]
@jfmyers9 Thanks for the info!

> For context, we have also tried adding the wait_until_exists waiter to mitigate this issue, but we still see this failure, even when that waiter succeeds.

Minding providing a minimal code snippet that can reproduce this?

**Comment by DonBower** [comment]
We have seen this with m4.xlarge in us-east-1.  I am checking for all the other instance types and regions this has happened in.

**Comment by jfmyers9** [comment]
Hi @cjyclaire,

I haven't been able to find the time to get an small reproducible example. For reference we are seeing this in this [code path](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L38-L41). Broken down into calls to the SDK we see the following:
* [`run_instances`](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L138)
* [`instance`](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L139)
* [`wait_until_exists`](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L67) which calls through to the [SDK waiter](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/instance.rb#L51)
* [`instance.reload`](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/0275f5c26784d3d087fb852419f81d81f158e9b4/src/bosh_aws_cpi/lib/cloud/aws/resource_wait.rb#L166) which happens as part of our old custom watch logic waiting for the instance to be `running`.

We are still seeing the failure on `instance.reload` for specific instance classes in `us-east-1` when following the code path above.

Meanwhile, we have converted the above code path to rely on the `wait_until_running` waiter as well and we no longer see the issue. So it appears that this error only occurs when you only use the `wait_until_exists` waiter.

I'll see if we can throw together a reproducible example at some point, but hopefully the above provides some context on how this situation manifests itself.

Best,

@jfmyers9

**Comment by cjyclaire** [comment]
Apologies for the delay and appreciate those helpful information! : )

This could be an EC2 API behavior issue for those instance states, for an eventually consistency behavior, I'll try to confirm with service team on that. As you can see here `exist` waiter checks for [`non empty reservations`](https://github.com/aws/aws-sdk-ruby/blob/master/apis/ec2/2016-11-15/waiters-2.json#L12) while `running` waiter is checking for [`reservation content`](https://github.com/aws/aws-sdk-ruby/blob/master/apis/ec2/2016-11-15/waiters-2.json#L189).

Will update

**Comment by h4xnoodle** [comment]
Hi @cjyclaire,

Do you have an update for how to approach this? Do you need a reproduction script or other artifacts to help the investigation?

Thanks,
@h4xnoodle

**Comment by mullermp** [comment]
Just checking in - Is this still a problem with the service API?
