### ISSUE TITLE
Aws-sdk-s3 always returns 'missing credentials' when using EC2 IAM role auth on windows 2019

### ISSUE THREAD

**Issue by lewisgaines** [aws/aws-sdk-ruby#2101]
### Issue description
I am consistently receiving the following error when trying to get an object from S3 using the IAM role that is assigned to the Windows Server 2019 EC2 instance on which code is running.
 
> ruby : C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:612:in 'extract_credentials_provider': missing credentials, provide credentials with one of the following options: 
> (Aws::Sigv4::Errors::MissingCredentialsError)
> At line:1 char:1
>  ruby .\s3.rb
>      CategoryInfo          : NotSpecified: (C:/Ruby25-x64/l...edentialsError):String) [], > RemoteException
>      FullyQualifiedErrorId : NativeCommandError
> 
>  - :access_key_id and :secret_access_key
>  - :credentials
>  - :credentials_provider

### Gem name
aws-sdk-s3 v1.46.0

### Version of Ruby, OS environment
Ruby 2.5.0 on Windows Server 2019

### Code snippets / steps to reproduce
I originally came across this issue when trying to download a file from S3 in a Chef cookbook that was previously working on a Windows 2012R2 host, but stopped working when I tried to use it on a new Windows 2019 host.
I was able to reproduce the issue by 
- Installing the latest version of Ruby (v2.5.0) on a Windows Server 2019 with an appropriate IAM role attached to the instance
- Installing the aws-sdk gem (v1.46.0)
- Running this code:
`require 'aws-sdk-s3'`
`s3 = Aws::S3::Resource.new(region: 'us-east-1')`
`obj = s3.bucket('<my bucket>').object('file_I_want.zip')`
`obj.get(response_target: './file_I_want.zip')`

**Comment by lewisgaines** [comment]
My issue looks to be similar to what is mentioned in this issue: https://github.com/chef-cookbooks/aws/issues/338

**Comment by cjyclaire** [comment]
Sounds like the client failed to fetch EC2 `InstanceMetaData` credentials.
To help debugging with this, might try
```ruby
require 'aws-sdk-s3'
creds = Aws::InstanceProfileCredentials.new
```
on the same host with the role to see if it succeed?

**Comment by lewisgaines** [comment]
@cjyclaire You were spot-on about it being an issue with metadata. Everything worked correctly after I ran the InitializeInstance.ps1 script. My issue stemmed from Amazon's change from using EC2Config to EC2Launch starting with Windows 2016 and the way my AMIs were created. I will be changing my packer template to include InitializeInstance.ps1 -Schedule.
