### ISSUE TITLE
Transfer Acceleration support for presigned post

### ISSUE THREAD

**Issue by adrenalin23** [aws/aws-sdk-ruby#2103]
# Issue description
Hello,
I'm using Transfer Acceleration. It works well with `Aws::S3::Presigner` if we specify `use_accelerate_endpoint` option:
```ruby
require 'aws-sdk-s3'

signer = Aws::S3::Presigner.new()
url = signer.presigned_url(:put_object, bucket: 'my_bucket', key: 'my_key', use_accelerate_endpoint: true)
```
But I can not find the way how to use Transfer Acceleration with `Aws::S3::PresignedPost`:
```ruby
Aws::S3::PresignedPost.new(creds, bucket_region, bucket_name, key: object_key, signature_expiration: expires, expires: expires)
```
I didn't find any docs how to implement it. Is it possible to use Transfer Acceleration with presigned post?
### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3-1.36.0

### Version of Ruby
ruby 2.5.1

**Comment by cjyclaire** [comment]
Thanks for the feedback!
This is a known [feature request](https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#add-accelerate-endpoint-support-to-presigned-post-requests), tracking a a "+1" for the feature

**Comment by adrenalin23** [comment]
@cjyclaire Great, thanks a lot for your feedback!

**Comment by QMuncaster** [comment]
Also interested in this but `FEATURE_REQUESTS.md` 404s for me. Would be great to get another "+1" @cjyclaire .

**Comment by cjyclaire** [comment]
@QMuncaster Thanks for chime in! We removed the feature request file and keep issue open for better visibility now :D your comments here totally works!

**Comment by QMuncaster** [comment]
Great, thanks!

Could I also confirm that setting `use_accelerate_endpoint: true` on the S3 client isn't a workaround? The pre-signed POST url doesn't change, so I assumed not.

**Comment by mullermp** [comment]
Sorry for the radio silence on this issue. A workaround is to pass `url: mybucket.s3-accelerate.amazonaws.com` into the presigned post class.

**Comment by simonrussell** [comment]
I don't know if there's a documentation issue, but for me the behaviour hasn't been fixed -- creating a client with `use_accelerate_endpoint: true` still presigns POSTs with the non-accelerated endpoint.

**Comment by mullermp** [comment]
@simonrussell Are you using the latest s3 gem? If not, have you tried the workaround listed above?

**Comment by simonrussell** [comment]
@mullermp Yeah, 1.78.0.  The workaround works -- actually our workaround is a little different, we're setting the `endpoint` in the `AWS::S3::Client` constructor.  That gets passed correctly to the presigned POST, but if we set `use_accelerate_endpoint` there without `endpoint`, the post will be constructed without acceleration.  (The flag works properly for other requests though.)

**Comment by mullermp** [comment]
@simonrussell Could you share any code snippets for how you are constructing any clients and creating the presigned post?

**Comment by mullermp** [comment]
If you're using Resource models, the URL is passed to presigned post [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L139) and bucket_url is never called [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/presigned_post.rb#L240) so yes this is still broken depending on usage..

**Comment by mullermp** [comment]
Attempting to fix that here https://github.com/aws/aws-sdk-ruby/pull/2401
