### ISSUE TITLE
FILTERED showing up in yml export

### ISSUE THREAD

**Issue by brianbedard** [aws/aws-sdk-ruby#2105]
Please fill out the sections below to help us address your issue

### Issue description
When exporting job settings utilizing get_job https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MediaConvert/Client.html#get_job-instance_method, the word FILTERED is showing up in the output. It was originally HLS_GROUP_SETTINGS when the job ran successfully, but the export is replacing that when it's output through the api call. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
require 'aws-sdk-s3'
require 'aws-sdk-mediaconvert'
### Code snippets / steps to reproduce
output_groups:
- custom_name: HLSOutput
  name: **"[FILTERED]"**
  output_group_settings:
    cmaf_group_settings:
    dash_iso_group_settings:
    file_group_settings:
    hls_group_settings:
      ad_markers:
      base_url:
      caption_language_mappings:
      caption_language_setting: OMIT
      client_cache: ENABLED
      codec_specification: RFC_4281
      destination: s3://sample-video-output/HLS-Test-Video
      destination_settings:
      directory_structure: SINGLE_DIRECTORY
      encryption:
      manifest_compression: NONE
      manifest_duration_format: INTEGER
      min_final_segment_length: 0.0
      min_segment_length: 0
      output_selection: MANIFESTS_AND_SEGMENTS
      program_date_time: EXCLUDE
      program_date_time_period: 600
      segment_control: SEGMENTED_FILES
      segment_length: 3
      segments_per_subdirectory:
      stream_inf_resolution: INCLUDE
      timed_metadata_id_3_frame: PRIV
      timed_metadata_id_3_period: 10
      timestamp_delta_milliseconds:
    ms_smooth_group_settings:
    type: **"[FILTERED]"**
  outputs:

**Comment by cjyclaire** [comment]
Thanks for the report! this happened because SDK helps [filter out](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L14) sensitive parameters from logging, `to_s`, `to_hash` and wire traces to avoid those information exposed in public accidentally.

However, currently SDK is filtering those parameters across all services even if it's only consider to be sensitive for one specific service, similar issue: #2082

We are tracking this as an enhancement in our backlog: ideally performing sensitive information filtering per service definition and provide an client option to disable those filtering.

**Comment by apanzerj** [comment]
This was driving me nuts so you can monkey patch this if you need to:

```
module Aws
  module Log
    class ParamFilter

      SENSITIVE = []
    end
  end
end
```

Not pretty. Wouldn't use this in production, but for testing stuff on my own machine it did the trick.

**Comment by mullermp** [comment]
Hi @brianbedard and @apanzerj , this has been addressed in #2342!

**Comment by apanzerj** [comment]
Hi @mullermp anyway to turn off the filtering completely?

**Comment by mullermp** [comment]
@apanzerj If you'd like to do that (don't recommend it in all situations..) you can pass `filter_sensitive_params: false` into an `Aws::Log::Formatter` object. (https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Log/Formatter.html)

```
Aws::S3::Client.new(log_formatter: Aws::Log::Formatter.default(filter_sensitive_params: false))
```

**Comment by apanzerj** [comment]
Ahhh! Thanks. This is solely for terminal debugging and such. Thanks.

**Comment by mullermp** [comment]
No problem. And not entirely, because you can also pass an instance of `logger` and have it go wherever you want (blog post: https://aws.amazon.com/blogs/developer/logging-requests/)
