### ISSUE TITLE
Not able to use send_bounce on SES - gives verify failure for senders domain

### ISSUE THREAD

**Issue by erikaxel** [aws/aws-sdk-ruby#2111]
Please fill out the sections below to help us address your issue

### Issue description
We are not able to send a simple bounce for an incoming email.

NB: Below we will use sender as the outside sender trying to send us email, and recipient as our own domain we try to receive on. (this is opposite from the usual SES setup when you send) 

We are using incoming SES email, and need to bounce if the local part does not match our list of approved recipients.  We have an approved incoming domain which we also can use to send on. However, SES gives back an error message that the senders domain not verified. . Obviously we can not verify that we own the senders domain (in our case below outlook.com)

We have also tried sending an email from the domain via the SDK to the same (outlook.com) email and that works fine.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3

### Version of Ruby, OS environment
ruby 2.6.3, aws-sdk-s3 1.36.1

### Code snippets / steps to reproduce
    
```ruby
ses = Aws::SES::Client.new
ses.send_bounce(
      original_message_id: mail.fetch('messageId'),  # the incoming message id
      bounce_sender: 'bounce@my-verified-domain.com',
      bounced_recipient_info_list: [
        {
          recipient: 'invalid-sender@outlook.com',
          bounce_type: 'DoesNotExist'
        }
      ]
)
```
We get the following error
`Aws::SES::Errors::MessageRejected (Failed to generate a bounce for <askldfjaslfj>: The following identities are not verified: outlook.com):`

**Comment by cjyclaire** [comment]
Thanks for the information, the error message is a server side response, there is nothing for SDK which is a client side tool can do to help.
 For those server side API behavior question, could you try [open TT with AWS support or asking on stackoverflow with the service tag](https://github.com/aws/aws-sdk-ruby#getting-help)? Such that AWS service team can be notified and help : D

Some quick documentation links that might be helpful:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

**Comment by apavlenko69** [comment]
Hi @erikaxel 
Can you please share how you resolved the issue? I got stacked with similar problem.

Thanks

**Comment by aaronfagan** [comment]
Also hitting the same issue. Any guidance on a resolution?

@apavlenko69 @erikaxel

**Comment by erikaxel** [comment]
Sorry no, we migrated away from SES some time ago.
