### ISSUE TITLE
Invalid params error when querying task definition for tags.

### ISSUE THREAD

**Issue by NickDeClario** [aws/aws-sdk-ruby#2118]
### Issue description

When querying an ECS Task Definition I am unable to retrieve the tags.  More specifically, I make a call to `describe_task_definition`, as per the documentation (https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#describe_task_definition-instance_method), pass the `task_definition` parameter and I can retrieve everything specified in the document, except the tags.  The docs then state that to fetch the tags I need to add `include: ['TAGS']` to the parameters.  With that included I then receive `ArgumentError: unexpected value at params[:include]`.  I've included the full error at the end of this.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk 3.0.1`

### Version of Ruby, OS environment

`ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`
`Ubuntu 16.04.6 LTS`
`4.4.0-1090-aws`

### Code snippets / steps to reproduce

Running this will reproduce the issue:

```
#!/usr/bin/env ruby

require 'aws-sdk'

ecs_client = Aws::ECS::Client.new(region: 'us-east-1')
resp = ecs_client.describe_task_definition({
  task_definition: my_task_definition,
  include: ['TAGS'],
})

puts resp.tags
```
And the resulting error:
```
ArgumentError: unexpected value at params[:include]
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/param_validator.rb:32:in `validate!'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/param_validator.rb:23:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-core-3.17.0/lib/seahorse/client/request.rb:70:in `send_request'
  /var/lib/jenkins/.rvm/gems/ruby-2.6.3@environment/gems/aws-sdk-ecs-1.8.0/lib/aws-sdk-ecs/client.rb:1724:in `describe_task_definition'
  test_sdk.rb:9:in `<top (required)>'
```

Thanks!

**Comment by cjyclaire** [comment]
From your error log, the eks gem is still on `1.8.0`, while documentation is always reflecting the latest version https://rubygems.org/gems/aws-sdk-eks/versions could you try upgrade to latest service gems and try again?

Side node `aws-sdk` gem is the monolithic gem with all service gems (>200), if you are using only a few service gems, we highly recommend moving your dependency to modularized service gems(such as `aws-sdk-eks`).

**Comment by NickDeClario** [comment]
Yes, thank you.  I changed my gem to point directly to `aws-sdk-ecs` and updated it to the latest version `1.49.0` and voila, this worked perfectly.  Thank you again for clearing this up!
