### ISSUE TITLE
S3::Object::upload_file does not allow thread_count configuration 

### ISSUE THREAD

**Issue by gregpardo** [aws/aws-sdk-ruby#2120]
Please fill out the sections below to help us address your issue

### Issue description
Our system was configured to use 5 threads and was hanging on the default configuration of multipart uploads. The docs do not state that you can pass a thread_count option to the Object::upload_file method. Even after you do pass you will get a params validation error unless your Client has 'params_validation: false' passed to it.  Object::download_file does seem to support thread_count option without any issues. Seems like this would be a common thing you may need to configure for upload_file as well. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3    1.48.0

### Version of Ruby, OS environment
2.6.4  on Alpine Linux 3.10
Puma running Rails on 5 threads

### Code snippets / steps to reproduce

Causes error when running 5 threads
```ruby
client = Aws::S3::Client.new
bucket = Aws::S3::Resource.new(client: client).bucket(some_bucket)
obj = bucket.object(some_object)
obj.upload_file(file_path)
```

Causes error when passing thread_count
```ruby
client = Aws::S3::Client.new
bucket = Aws::S3::Resource.new(client: client).bucket(some_bucket)
obj = bucket.object(some_object)
obj.upload_file(file_path, thread_count: 5)
```

Does not cause error
```ruby
client = Aws::S3::Client.new(validate_params: false)
bucket = Aws::S3::Resource.new(client: client).bucket(some_bucket)
obj = bucket.object(some_object)
obj.upload_file(file_path, thread_count: 5)
```

**Comment by cjyclaire** [comment]
We do support `:thread_count` for `upload_file`,  we should make our parameter doc clearer on that, if your file is less than 15M (default), it won't trigger multipart uploader, this could be why you don't see the `:thread_count` working. This threshold value is also configurable by `: multipart_threshold `.
