### ISSUE TITLE
Does this SDK throttle requests automatically

### ISSUE THREAD

**Issue by JamesPlayer** [aws/aws-sdk-ruby#2123]
### Issue description
I can't find anywhere in the documentation stating whether this SDK automatically throttle's requests to stay inside AWS's rate limits.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk 2 and 3

A simple yes or no would be fine, or pointing to some documentation that I've missed would also be great.

Thanks!

**Comment by cjyclaire** [comment]
throttling happens at each AWS service side, different AWS service has different throttling schema, when you are using SDK as a client side tool, you would see a throttling error when it happens. SDK does have default retry logic built-in with exponential backoff with jitter.

**Comment by cjyclaire** [comment]
closing, feel free to reopen if you have more questions :)
