### ISSUE TITLE
ResourceGroupTaggingAPI examples in documentation

### ISSUE THREAD

**Issue by eyekelly** [aws/aws-sdk-ruby#2128]
Please fill out the sections below to help us address your issue

### Issue description
Hi, its not clear to me how to actually get information out of the response from calling get_resources()

the documentation doesn't give me an example of how to filter what comes back. 

because it comes back with an array of structs, how do I get specific information out of that?

### Version of Ruby, OS environment
debian, Ruby 2.5
### Code snippets / steps to reproduce
the response from 
`response.resource_tag_mapping_list`

here in this example is a single element. 

```
[#<struct Aws::ResourceGroupsTaggingAPI::Types::ResourceTagMapping
  resource_arn=
   "arn:aws:ec2:eu-west-2:01234567892034:instance/i-123455667778",
  tags=
   [#<struct Aws::ResourceGroupsTaggingAPI::Types::Tag
     key="Name",
     value="VTX-EU : Non-Prod : QA1 : CoreStack">,
    #<struct Aws::ResourceGroupsTaggingAPI::Types::Tag
     key="Qualys-CloudAgent",
     value="VTX-EU : Non-Prod : QA1">,
    #<struct Aws::ResourceGroupsTaggingAPI::Types::Tag
     key="app",
     value="corestack">,
    #<struct Aws::ResourceGroupsTaggingAPI::Types::Tag key="env", value="qa">,
    #<struct Aws::ResourceGroupsTaggingAPI::Types::Tag key="group", value="1">,
    #<struct Aws::ResourceGroupsTaggingAPI::Types::Tag
     key="os",
     value="windows">]>,
```
but its not clear in the documentation how to actually filter by one tag and return a list of text. 
that I may be able to use to query ec2 to check that states of instances or whatever. 
I don't want a list of all tags, all arns, just a text list of "Names" for example. 
This is almost certainly my lack of experience, but I still need help. so I'd appreciate a step-by-step as an example to us folks who aren't devs. 

If my thinking is fundamentally incorrect, please do say, and I know this is very likely to be my inexperience. 

so this works, but how do I make it loop through them all. 
```
[28] pry(List)> response.resource_tag_mapping_list[2].tags[0].value
=> "VTX-EU : Non-Prod : QA2 : FlashSeat"
```

because this
```
response.resource_tag_mapping_list.each { |e| e.tags[0][:value] }
```
returns the whole lot again. 

Many thanks

**Comment by mullermp** [comment]
I've personally never used the API before, but glancing at your response object, you've got nested lists. So try something like:

```
response.resource_tag_mapping_list.each do |tag_mapping_list|
  tag_mapping_list.tags.each do |tag|
    put tag.value
  end
end
```

**Comment by eyekelly** [comment]
Thanks @mullermp so, I got in touch with an ex colleague who's solved it for me. 
So for anyone who finds this. the secret is .map

what works here is. 

```
response.resource_tag_mapping_list.map { |e| e.tags[0][:value] }
```
replacing "each" with "map"

because map returns a value and each doesn't (or something like that)

**Comment by eyekelly** [comment]
As my issue is resolved, closing, however, I do feel in general that there could be more examples for newbies to this kind of stuff, because its likely to be sysops not devs doing it.

**Comment by mullermp** [comment]
That is correct - map will return a new list while each will only iterate. Your solution however will only ever grab the first tag from that api (because you are doing e.tags[0]) so be aware of that. This is not specific to the SDK though - do check out the [Enumerable](https://ruby-doc.org/core-2.6.4/Enumerable.html) Ruby documentation.
