### ISSUE TITLE
Can't set object or bucket acl on MinIO

### ISSUE THREAD

**Issue by ArthurLuisLimaBender** [aws/aws-sdk-ruby#2129]
I'm trying to grant public access to an object inside a private bucket using the Aws::S3::Client.put_<object/bucket>_acl, but i'm getting the error:
`Aws::S3::Errors::NotImplemented (A header you provided implies functionality that is not implemented)`

I'm using:
"aws-sdk-s3" 1.48.0 (latest version)
"ruby" 2.5.1
Linux 18.04 64-bits

I'm just initializing the client with:
```
config = {
  endpoint: 'http://192.168.1.138:9000',
  access_key_id: '<ID>',
  secret_access_key: '<PASSWORD>',
  region: 'us-east-1',
  force_path_style: true
}
client = Aws::S3::Client.new(config)
```
And then calling put_<object/bucket>_acl like:
`client.put_bucket_acl({bucket: "client-24", acl: "public-read"})`

But then i'm getting the error. The error is the same for both buckets and objects, and other methods using the client instance are working fine. I can even get the acl, but not set it.

By the way, i can use an equivalent method on mc(MinIO Client), so I guess that the problem is on the gem, or on the communication with MinIO.

I've already searched for it, but looks like i'm the only one getting this error.

**Comment by mullermp** [comment]
Hey Arthur, could you try reproducing this using the REPL console with wire tracing? (by running `aws-v3.rb -v`) I've never used (or even heard of..) MinIO - but perhaps MinIO is forwarding a header to S3 which it is not expecting. Is there a way for you to check the MinIO logs and output wire information too?

**Comment by ArthurLuisLimaBender** [comment]
Thanks for your reply! I'll try to do both and output it here as soon as possible

**Comment by cjyclaire** [comment]
This is an server side error, could you try

```ruby
begin
 # call API
rescue Aws::S3::Errors::NotImplemented => e
  puts e.context.http_request.headers.inspect
end
```

This should be providing an insight into what's are those request headers and whether some headers have been injected unintentionally.

**Comment by ArthurLuisLimaBender** [comment]
I did what you said and got:

{"user-agent"=>"aws-sdk-ruby3/3.68.0 ruby/2.5.1 x86_64-linux aws-sdk-s3/1.48.0", "x-amz-acl"=>"public-read", "host"=>"192.168.1.138:9000", "x-amz-content-sha256"=>"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "content-length"=>"0", "x-amz-date"=>"20191001T170335Z", "authorization"=>"AWS4-HMAC-SHA256 Credential=<ID>/20191001/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=a967c89cb8ad0fef1221dd84420636939c6853825c810e78cc49c957f2d01a93"}

**Comment by mullermp** [comment]
Do you have an issue open with MinIO. The host you are hitting must be missing something in the request. The only thing that looks fishy to me is `"content-length"=>"0"` so is anything actually being uploaded?

**Comment by ArthurLuisLimaBender** [comment]
I will try to open an issue on MinIO so.

**Comment by ArthurLuisLimaBender** [comment]
Well, I ended up using `put_bucket_policy` to reach what I wanted, and it works fine. I still don't know why `put_bucket_acl` doesn't work.

**Comment by mullermp** [comment]
Are you able to use the CLI for `put_bucket_acl` using your configuration?

**Comment by mullermp** [comment]
Going to assume that this issue solved?

**Comment by ArthurLuisLimaBender** [comment]
> Are you able to use the CLI for `put_bucket_acl` using your configuration?

No



> Going to assume that this issue solved? @ArthurLuisLimaBender

And yes

**Comment by mullermp** [comment]
Ah ok. If you aren't able to use put_bucket_acl using your configuration via the CLI, the the configuration must be wrong somewhere..
