### ISSUE TITLE
Aws::Pinpoint::Client#update_endpoint crashed and has no error message

### ISSUE THREAD

**Issue by Blue-Pix** [aws/aws-sdk-ruby#2138]
Please fill out the sections below to help us address your issue

### Issue description
when I call Aws::Pinpoint::Client#update_endpoint raises Exception and returns no message.
I would create an endpoint for apns channel.
I wondered the device token was wrong, but after some retry, the endpoint was successfully created.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk 3.0.1

### Version of Ruby, OS environment
ruby2.5.1, Amazon Linux2

### Code snippets / steps to reproduce
```ruby
@client = Aws::Pinpoint::Client.new(
  :region => "us-west-2"
)
@client.update_endpoint(
  :application_id => "xxxxxxxx",
  :endpoint_id => "APNS_PRD_123456abcdef",
  :endpoint_request => {
    :address => "3324fb9317xxxxxxxxxxxxxxxxxxxxx", # device token
    :channel_type => "APNS",
    :user => {
      :user_attributes => {},
      :user_id => "PRD_123456abcdef"
    }
  }
)
```

**Comment by mullermp** [comment]
Hey there. Do you happen to have any console output? I've personally never used pinpoint and I don't own an apple device (I see you're using APNs). It looks like you were able to retry successfully? Could you enable wire trace? Was there perhaps a network failure on your side?

**Comment by cjyclaire** [comment]
Thanks for reporting! This appears an API behavior question, could you open a support ticket with [AWS Support](https://console.aws.amazon.com/support/home)? This would be the fastest way to start direct communication with service team. For enabling wire trace, you can set `:http_wire_trace` to true for your client.

Let us know if you are having trouble for opening AWS Support ticket, we can help with the messaging as well, though it could take longer time comparatively. :)

**Comment by cjyclaire** [comment]
For enabling wire trace, you can set `:http_wire_trace` to true for your client, you can see all retry information there too.
