### ISSUE TITLE
Aws::Health.describe_events seems to ignore event_status_codes in filters

### ISSUE THREAD

**Issue by mattdoller** [aws/aws-sdk-ruby#2139]
Please fill out the sections below to help us address your issue

### Issue description

The Aws::Health::Client#describe_events method seems to be returning events without regard to the event_status_codes given to the filter passed to the method.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

Aws::CORE_GEM_VERSION - 3.68.1
Aws::Health::GEM_VERSION - 1.19.0

### Version of Ruby, OS environment
RUBY_VERSION - 2.5.3
env - osx, 10.13.6

### Code snippets / steps to reproduce
```ruby
require 'aws-sdk-health'
health = Aws::Health::Client.new(region: 'us-east-1')

events = health.describe_events(
  filter: {          
    event_status_codes: %w[open upcoming],              
    event_type_categories: %w[issue scheduledChange],              
  },              
).events          
```

This results in the following array of events being returned:

```
=> [#<struct Aws::Health::Types::Event
  arn=
   "arn:aws:health:us-east-1::event/EC2/AWS_EC2_INSTANCE_REBOOT_FLEXIBLE_MAINTENANCE_SCHEDULED/AWS_EC2_INSTANCE_REBOOT_FLEXIBLE_MAINTENANCE_SCHEDULED_...",
  service="EC2",
  event_type_code="AWS_EC2_INSTANCE_REBOOT_FLEXIBLE_MAINTENANCE_SCHEDULED",
  event_type_category="scheduledChange",
  region="us-east-1",
  availability_zone=nil,
  start_time=2019-10-24 10:00:00 -0400,
  end_time=2019-10-09 10:01:01 -0400,
  last_updated_time=2019-10-09 10:01:06 -0400,
  status_code="closed">]
```

Note that the single event returned has a status code of "closed", which is not in the initial filter.

**Comment by cjyclaire** [comment]
Thanks for reporting! This appears an API behavior question, could you open a support ticket with [AWS Support](https://console.aws.amazon.com/support/home)? This would be the fastest way to start direct communication with service team. 

Let me know if you are having trouble for opening AWS Support ticket, I can help with the messaging as well, though it could take longer time comparatively. :)

**Comment by mattdoller** [comment]
thanks @cjyclaire  - opened a support ticket w/ aws support.  going to close this issue here.

thanks again,
Matt
