### ISSUE TITLE
thread safety issues in endpoint_cache.rb

### ISSUE THREAD

**Issue by ioquatix** [aws/aws-sdk-ruby#2142]
```ruby
    # @param [String] key
    # @param [Hash] value
    def []=(key, value)
      @mutex.synchronize do
        # delete the least recent used endpoint when cache is full
        unless @entries.size < @max_entries
          old_key, _ = @entries.shift
          self.delete_polling_thread(old_key)
        end
        # delete old value if exists
        @entries.delete(key)
        @entries[key] = Endpoint.new(value.to_hash)
      end
    end

    # checking whether an unexpired endpoint key exists in cache
    # @param [String] key
    # @return [Boolean]
    def key?(key)
      if @entries.key?(key) && (@entries[key].nil? || @entries[key].expired?)
        self.delete(key)
      end
      @entries.key?(key)
    end
```

This does not look thread safe to me. If multiple threads are accessing @entries, `#key?` can be called without locking around `@entries`. I don't believe those are thread-safe operations.

**Comment by mullermp** [comment]
Thanks for opening the issue. Should the contents of `key?` be wrapped with `@mutex.synchronize`? Also happy to take a pull request.

**Comment by ioquatix** [comment]
Assuming that function is re-entrant and executed in parallel with modifications to the has table that is probably the easiest solution.

**Comment by mullermp** [comment]
@ioquatix Mutex is not re-entrant - One of our tests fails in the case where the key exists and it has expired; delete is called and that method is also synchronized, causing a deadlock. In the case where the key exists and not expired, I can get the test to pass. My inclination is to not remove `@mutex.synchronize` from delete - but I could be wrong. Is there a need for locking in the deletion case? If there is, we could consider using Monitor [as per this post](https://japgolly.blogspot.com/2012/04/ruby-mutex-reentrancy.html).

**Comment by ioquatix** [comment]
Monitor is almost double the overhead and you don't need to use it in this case because you are not invoking user code AFAIK. Because you fully control the code path, you can use `Mutex`, just avoid your synchronized methods calling other synchronized methods.

**Comment by mullermp** [comment]
Right - wrapping the contents of the `key?` method in synchronize could potentially call `delete` which is synchronized. So we would be unable to do that. Because `delete` is synchronized and called when the cache expires, would this be a non issue?

**Comment by ioquatix** [comment]
The PR I provided doesn't call `EndpointCache#delete`.

**Comment by mullermp** [comment]
Aha. Now I see. It sort of leaks implementation details but nothing major. Happy to approve and merge.
