### ISSUE TITLE
aws-sdk-core >= 3.71.0 breaks existing (EC2) code

### ISSUE THREAD

**Issue by dhs-rec** [aws/aws-sdk-ruby#2145]
### Issue description
After update of aws-sdk-ec2 to version 1.113.0, which pulls in aws-sdk-core >=3.71.0, client creation throws the following error:
> wrong number of arguments (given 3, expected 2)
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-partitions-1.213.0/lib/aws-partitions/endpoint_provider.rb:94:in `resolve'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/aws-sdk-core/plugins/regional_endpoint.rb:39:in `block in <class:RegionalEndpoint>'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:70:in `call'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:213:in `block in resolve_defaults'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:57:in `each'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:57:in `each'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:212:in `resolve_defaults'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:205:in `value_at'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:189:in `block in resolve'
/usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/set.rb:338:in `each_key'
/usr/local/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:189:in `resolve'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/configuration.rb:150:in `build!'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/base.rb:62:in `build_config'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/base.rb:19:in `initialize'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-ec2-1.113.0/lib/aws-sdk-ec2/client.rb:256:in `initialize'
/usr/local/rvm/gems/ruby-2.6.2@Test/gems/aws-sdk-core-3.71.0/lib/seahorse/client/base.rb:99:in `new'

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-ec2 1.113.0
aws-sdk-core 3.71.0

### Version of Ruby, OS environment
Ruby 2.6.2
Ubuntu 18.04 LTS

### Code snippets / steps to reproduce
```
ec2_client  = Aws::EC2::Client.new(
  region:      'eu-central-1',
  credentials: Aws::SharedCredentials.new(profile_name: 'myprofile'),
  logger:      (debug ? logger : nil),
  retry_limit: 20
)
```

**Comment by olexandrd** [comment]
I got similar mistake today with new version of aws-sdk-core, aws-sdk-elasticloadbalancingv2 in chef recipe (AWS Opsworks) 
```
================================================================================
Error executing action `run` on resource 'ruby_block[attach to ALB]'
================================================================================
 
ArgumentError
-------------
wrong number of arguments (given 3, expected 2)
```
### Gem name
aws-sdk-elasticloadbalancingv2 1.35.0
aws-sdk-core 3.71.0
### Version of Ruby, OS environment
Ubuntu 16.04
Ruby 2.3.0
### Code snippets
```
client = Aws::ElasticLoadBalancingV2::Client.new(region: stack_region)
```

**Comment by cjyclaire** [comment]
Thanks for the report! Apologies for the inconvenience, mind updating your `aws-partition` gem and try again? we have #2144 merged for updating the minimum requirement in core gem

**Comment by cjyclaire** [comment]
#2144 has been released https://rubygems.org/gems/aws-sdk-core/versions/3.72.0
As long as you are updating with latest core version, this should have been fixed

**Comment by dhs-rec** [comment]
Will check...

**Comment by dhs-rec** [comment]
Yep, looks good again.

**Comment by mullermp** [comment]
Going to close.
