### ISSUE TITLE
no implicit conversion of nil into String with @s3_direct_post.fields

### ISSUE THREAD

**Issue by Ruli-AlSe** [aws/aws-sdk-ruby#2146]
Hello guys, does someone can help me?

### Issue description
i'm developing a rails application and i got an issue when i tried to get the information from **@s3_direct_post.fields**. I'm trying to configure my application to upload image to a S3 Bucket and when render my view, it brakes on ```<%= form_for(@book, html: { class: "directUpload", data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>```

But when i print **@s3_direct_post** the **fields** field throws information, so i don't know what's happens :(

### Version of Ruby, OS environment
i'm using MacOS, Rails 6.0 and ruby 2.6.3

**Comment by cjyclaire** [comment]
Are you able to reproduce the issue with SDK alone? or isolate the SDK code triggering the issue with error trace?

**Comment by mullermp** [comment]
How are you initializing @s3_direct_post? What kind of object is it?
