### ISSUE TITLE
SDK wraps a pageable response for you, however `.to_json` is trying to fetch every page to give you a full result. Alternatively, you may iterate through it like following instead of fetching all at once

### ISSUE THREAD

**Issue by Idehsazan2030** [aws/aws-sdk-ruby#2147]
SDK wraps a pageable response for you, however `.to_json` is trying to fetch every page to give you a full result. Alternatively, you may iterate through it like following instead of fetching all at once
```
resp = client.list_presets
resp.next_page?
	page = resp.next_page
    # process page
end
```

_Originally posted by @cjyclaire in https://github.com/aws/aws-sdk-ruby/issues/2091#issuecomment-514825585_

**Comment by cjyclaire** [comment]
Quick follow-up question, may I ask are you trying to confirm this behavior or requesting a feature request or seeing an issue with this behavior? : )
