### ISSUE TITLE
Kinesis Analytics V2 Compatibility?

### ISSUE THREAD

**Issue by OBCENEIKON** [aws/aws-sdk-ruby#2151]
This is really more of a question than an issue, but I need a definite yes or no before proceeding.

Is `aws-kinesis-analyticsv2` backwards compatible with `aws-kinesis-analytics`?

We were using `aws-kinesis-analytics` when we received this error message: `us-east-1/AwsActors::KinesisAnalytics::ApplicationsActor | Aws::KinesisAnalytics::Errors::UnsupportedOperationException test was created/updated by kinesisanalyticsv2 SDK. Please use kinesisanalyticsv2 SDK to make changes to test.`

I switched to `aws-kinesis-analyticsv2` which fixed the problem, but I wanted to verify that v2 will handle any resources created using v1?

**Comment by ajredniwja** [comment]
Yes ```aws-kinesis-analyticsv2``` is backwards compatible. 

```aws-kinesis-analyticsv2``` created resources will handle the v1 created resources the same.

**Comment by OBCENEIKON** [comment]
Perfect! Thank you!
