### ISSUE TITLE
gem aws-sdk-apigatewaymanagementapi versions 1.10.0 and 1.11.0 not available from rubygems.org

### ISSUE THREAD

**Issue by acaeti** [aws/aws-sdk-ruby#2152]
### Issue description

https://rubygems.org/gems/aws-sdk-apigatewaymanagementapi does not list versions 1.10.0 or 1.11.0 - the latest available is 1.9.0 published in July.

Because of this, the documented methods introduced in later versions such as get_connection and delete_connection are not available for use without compiling the gem from github.  This is not a deal-breaker, but it is a bit inconvenient.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-apigatewaymanagementapi

### Version of Ruby, OS environment

Platform independent

### Code snippets / steps to reproduce

Visit https://rubygems.org/gems/aws-sdk-apigatewaymanagementapi, note the available versions.

Attempts to install more recent versions naturally fail, e.g. `gem install aws-sdk-apigatewaymanagementapi -v 1.11.0`

**Comment by cjyclaire** [comment]
Thanks for reporting, taking a look

**Comment by cjyclaire** [comment]
confirmed that this is a bug in our release tools, working on the fix.

**Comment by cjyclaire** [comment]
The issue has been fixed, issue will be resolved in the next SDK release, will update once the next release is out! Thanks so much for your patience :D

**Comment by cjyclaire** [comment]
SDK release is done, thanks so much for your patience!
https://rubygems.org/gems/aws-sdk-apigatewaymanagementapi
