### ISSUE TITLE
Could not find aws-sdk-cloudwatchlogs-1.26.0 in any of the sources

### ISSUE THREAD

**Issue by ChocoMilkTea** [aws/aws-sdk-ruby#2155]
I am trying to access cloudwatch logs to see the logs. When I included the gem
```
gem 'aws-sdk-cloudwatchlogs'
```

I've also tried
```
gem 'aws-sdk-cloudwatchlogs' '~> 1.26.0'
```

and when i bundle install, there is no issue. But when i tried to use rails console, i will encounter the problem
`Could not find aws-sdk-cloudwatchlogs-1.26.0 in any of the sources`

Can I know what am i doing wrong? How to make this work?

**Comment by mullermp** [comment]
With a new rails app, I'm able to add `gem 'aws-sdk-cloudwatchlogs'` to the Gemfile and run `bundle install` and it correctly fetches:

```
Fetching aws-sdk-cloudwatchlogs 1.26.0
Installing aws-sdk-cloudwatchlogs 1.26.0
```

When I run `rails console`, it looks like it's correctly loaded:

```
Running via Spring preloader in process 3449
Loading development environment (Rails 6.0.1)
irb(main):001:0> require 'aws-sdk-cloudwatchlogs'
=> false
irb(main):002:0> puts Aws::CloudWatchLogs::GEM_VERSION
1.26.0
=> nil
```

**Comment by ChocoMilkTea** [comment]
I just tried it again. When I run `bundle install`, it shows
```
Using aws-sdk-cloudwatchlogs 1.26.0
```

I am able to start the server with `rails start` command. Only when I tried using `rails console` then i have the following error:
```
Could not find aws-sdk-cloudwatchlogs-1.26.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by mullermp** [comment]
More generically, have you tried any of the solutions [here](https://stackoverflow.com/questions/11885398/is-there-a-fix-for-the-could-not-find-gem-in-any-of-the-sources-error-that-d)?

**Comment by ChocoMilkTea** [comment]
Tried the above solutions but none of it works. 

I have fixed the problem already. In the end, I have to reinstall the ruby version in my rvm and now i 
can access console.

**Comment by mullermp** [comment]
Ah ok. I am glad you found a solution. It sounds like it wasn't an issue on our end.
