### ISSUE TITLE
Downloading aws-sdk-resources-3.57.0 revealed dependencies not in the API or the lockfile (aws-sdk-sso (~> 1))

### ISSUE THREAD

**Issue by jamesncampbell** [aws/aws-sdk-ruby#2157]
### Issue description
While running bundle update in my project, I got the following error

```
Fetching aws-sdk-resources 3.57.0 (was 3.56.0)
Downloading aws-sdk-resources-3.57.0 revealed dependencies not in the API or the lockfile (aws-sdk-sso (~> 1)).
Either installing with `--full-index` or running `bundle update aws-sdk-resources` should fix the problem.
```

I ran the suggested commands but continue to get the same error. I also tried to install the missing gem `aws-sdk-sso` manually but got an error saying the gem couldn't be found.

Is there an issue with the availability of the `aws-sdk-sso` gem?

### Gem name  
'aws-sdk-resources'

### Version of Ruby, OS environment
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]

### Code snippets / steps to reproduce
Run a bundle update that brings in the `3.57.0` version of `aws-sdk-resources`

**Comment by cjyclaire** [comment]
This is a known issue, we are working with rubygems.org to allow us publishing `aws-sdk-sso` gem
https://github.com/rubygems/rubygems.org/issues/2161

**Comment by jamesncampbell** [comment]
Thank you! I'll lock my version to `3.56` for now and keep an eye on the progress of `aws-sdk-sso`.

**Comment by cflanny** [comment]
Came here to report the same - thanks for getting this fixed quickly!

**Comment by harshavardhana** [comment]
> Came here to report the same - thanks for getting this fixed quickly!

Thanks as well same issue here

**Comment by cjyclaire** [comment]
RubyGem just whitelisted us, we have published the gem https://rubygems.org/gems/aws-sdk-sso
the issue should have been fixed, anyone want to help check and confirm before I close the issue?

**Comment by kcrouch** [comment]
Confirmed!  Thanks for your work!

**Comment by cjyclaire** [comment]
Thanks to all for your patience! Appreciate that!
