### ISSUE TITLE
S3 list_objects next_marker is blank

### ISSUE THREAD

**Issue by Paxa** [aws/aws-sdk-ruby#2164]
```ruby
res = connection.list_objects(bucket: 'aaa', max_keys: 10)

if res.is_truncated
  p [:truncated, res.next_marker]
end

# => [:truncated, nil]
```

But it works with list_objects_v2 and continuation_token

**Comment by ajredniwja** [comment]
Hey @Paxa,

Thank-you for reaching out to us with your issue, the ```list_objects_v2``` is a revised model of ```list_objects```. It is highly recommended to use ```list_objects_v2``` for your new application development documented [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects_v2-instance_method). 

Please reach out if you have any additional questions.

**Comment by mullermp** [comment]
Building on @ajredniwja's response, IIRC v1 of the API was not correctly paginated, which is why v2 is a thing.

**Comment by Paxa** [comment]
Would it be nice to add depreciation warning for `list_objects`?
or rename `list_objects_v2` to `list_objects` and v1 as `list_objects_v1`?

**Comment by mullermp** [comment]
It would be nice, but it's beyond our control, because the clients are generated from S3's API. They're well aware of the situation. I can see about adding a deprecation warning via a monkey patch but that would be the best I could do.

**Comment by mullermp** [comment]
Soft update - I want to first find out how many customers are using `list_objects` instead of `list_objects_v2` and I want to also see if I can drive a cross-language SDK initiative for phasing that out before I implement something here.

**Comment by Paxa** [comment]
Everyone who potentially need to fetch more than 1000 objects will need to implement some code to fetch next pages. And that code is going to be same for almost everyone.

If we add it to library, it will help people to use correct api calls
example:
```ruby
def each_batch(options)
  continuation_token = nil
    loop do
      res = list_objects_v2(options.merge(continuation_token: continuation_token))
      yield(res)

      if res.is_truncated
        continuation_token = res.next_continuation_token
      else
        break
      end
    end
  end

  def each_object(options)
    each_batch(options) do |batch|
      batch.contents.each {|o| yield(o) }
    end
  end
end
```

btw is there a plan to fix s3 backend to respond with correct `NextMarker` as [documented](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html)?

**Comment by mullermp** [comment]
Have you looked at [paginated responses](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/paging-responses.html)? AFAIK S3 has no plans to fix `ListObjects` as they have improved the API with `ListObjectsV2`. Fixing `ListObjects` would involve changing the response object and thus break current customers still using it.

**Comment by Paxa** [comment]
No I didn't see it. Sorry I missed that we can use last key as marker for next page
Thanks!

**Comment by mullermp** [comment]
No problem! I will close this issue for now. Please let me know if you need any more guidance.

Regarding `ListObjects` deprecation, after talking with the other SDK teams, the consensus seems to be that any deprecations / warnings should be done together and with approval of S3. Post re:Invent, I will kick off that process, since right now they are busy delivering other upcoming features.
