### ISSUE TITLE
Remove Filename from `presigned_post` when the key doesn't contain `{filename}`

### ISSUE THREAD

**Issue by ignacio-chiazzo** [aws/aws-sdk-ruby#2178]
### Issue description

The metadata `filename` is only useful when the key contains `#{filename}` according to https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html. However, the method `presigned_post` does return the `filename` even  when the key doesn't contain it. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') 
`3`

### Code snippets / steps to reproduce

```ruby

> options = {
   key: '/products/nachochiazzo.png',        
   url: 'https://my-bucket.s3.amazonaws.com',        
   filename: "nachochiazzo.png"        
  }        
=> {:key=>"/products/nachochiazzo.png", :url=>"https://my-bucket.s3.amazonaws.com", :filename=>"nachochiazzo.png"}
> presigned_post = bucket.presigned_post(options)
=> <AWS::S3::PresignedPost>
> presigned_post.url
=> #<URI::HTTPS https://s3.amazonaws.com/>
> presigned_post.fields
=> {"AWSAccessKeyId"=>"myKey",
"key"=>"/products/nachochiazzo.png",
"policy"=>
"abcdefg==",
"signature"=>"123/Gx/abc=",
"Url"=>"https://my-bucket.s3.amazonaws.com",
"Filename"=>"nachochiazzo.png"}

```

### Expected behavior:
Ideally the `bucket.presigned_post(options)` returns no `filename` if the key doesn't contain `${filename}`. This is a problem when the filename is not sanitized/encoded but the key is, for example if you send `filename: $1234.png` and the key `pepe/_1234.png` and `filename:$1234.png` then S3 will return 400 errors.

**Comment by ajredniwja** [comment]
Hey @ignacio-chiazzo,

Thank-you for reaching out to us with your issue. 

However, I was not able to reproduce this behavior on my personal machine but I was not able to pass  ```filename``` as a param either. Can you please share if there are anymore relevant details for your use case?
