### ISSUE TITLE
X-Ray fails in sampling s3

### ISSUE THREAD

**Issue by himberjack** [aws/aws-sdk-ruby#2180]
Please fill out the sections below to help us address your issue

### Issue description
Our code yields:

Aws::Xml::Parser::ParsingError
XML declaration allowed only at the start of the document

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-core-3.82.0
aws-xray-sdk-0.10.2
aws-sdk-s3-1.57.0

### Version of Ruby, OS environment
2.5.1 ubuntu (Docker)

### Code snippets / steps to reproduce
client = Aws::S3::Client.new
client.copy_object(
          bucket: 'xxxxx',
          copy_source: "yyyyyyy.csv.gz",
          key: "zzzzz.csv.gz")

**Comment by mullermp** [comment]
Hi there.. could I get some extra steps to reproduce? It looks like you're using 'aws-xray-sdk' which is not related to 'aws-sdk-ruby', and your code snippets don't use XRay at all. I see that you're trying to do a `copy_object` call. Is that what is not working for you?
