### ISSUE TITLE
Fail to log :http_response_body when trying to get_object with a block given

### ISSUE THREAD

**Issue by RusHibaM** [aws/aws-sdk-ruby#2183]
### Issue description
When creating an S3 client using an `Aws::Log::Formatter` that has `:http_response_body` included, a get_object request will fail with:

    undefined method `rewind' for #<Seahorse::Client::BlockIO:0x00005580d3b49688>`

This only happens when calling get_object with a block given.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk, aws-sdk-core-2.11.408

### Version of Ruby, OS environment
Ruby 2.5.4p155.
OS: Ubuntu 18.04.3

### Code snippets / steps to reproduce
```ruby
# Probably the "pattern += 'response_body=>:http_response_body, ' "
# will be enough to reproduce this issue
pattern  = 'Aws::S3::Client(V2) took :time seconds. Request => {'
pattern += 'endpoint=>:http_request_scheme://:http_request_host::http_request_port, '
pattern += 'request_method=>:http_request_method, '
pattern += 'request_operation=>:operation, '
pattern += 'request_params=>{:request_params}, '
pattern += 'request_headers=>:http_request_headers}, Response => {'
pattern += 'response_status=>:http_response_status_code, '
pattern += 'response_headers=>:http_response_headers, '
pattern += 'response_body=>:http_response_body, '
pattern += '}'
formatter = Aws::Log::Formatter.new(pattern, :max_string_size => 200)

# Might need to define your own logger when running this code sample. 
# Provide a simple logger here to make it easier to run the code sample
class MyLogger
  def self.info(msg)
    puts msg
  end
  def self.debug(msg)
    puts msg
  end
  def self.warn(msg)
    puts msg
  end
  def self.error(msg)
    puts msg
  end
end

source = Aws::S3::Resource.new(options.merge({:logger => MyLogger, :log_formatter => formatter}))
client = source.client

# Ingest an object to start
client.put_object({:bucket => 'test-some-logging', :key => 'test-1', :body => '123'})

# This will succeed and print out the log with the specified format
client.get_object({:bucket => 'test-some-logging', :key => 'test-1'})

# This would fail with the 
# undefined method `rewind' for #<Seahorse::Client::BlockIO:0x00005580d3b49688>`

client.get_object({:bucket => 'test-some-logging', :key => 'test-1'}) {|chunk| puts chunk}

```

It looks like #1479 didn't go into the version-2 branch. Maybe we should do a cherry-pick here?

**Comment by mullermp** [comment]
@ajredniwja Can you confirm that this works in V3?

@RusHibaM If this is missing functionality in V2 it will not be addressed. Please upgrade to V3.

**Comment by RusHibaM** [comment]
@mullermp Thanks for the reply. To me, #1479 is more like a `bug fix`. I would be glad to see the change goes into the V2 branch since it doesn't seem to be a risky/big change.

**Comment by mullermp** [comment]
I've confirmed this as a bug in V3. I've created a PR to address this. This bug is not security related so I will not be porting it to V2. Please upgrade to V3.
