### ISSUE TITLE
aws-sdk does not work with delayed_job?

### ISSUE THREAD

**Issue by nagrgk** [aws/aws-sdk-ruby#2187]
issue is aws-sdk or aws-sdk-s3 does not load while job or script is executed via delayed_job

applies to aws-sdk, aws-sdk-s3

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

error is :
Job Delayed::PerformableMethod (id=55) (queue=default) FAILED permanently with Delayed::DeserializationError: Job failed to load: cannot load such file -- aws-sdk-s3. Handler: "--- !ruby/object:Delayed::PerformableMethod\nobject: !ruby/class 'Import'\nmethod_name: :import_without_delay\nargs:

![image](https://user-images.githubusercontent.com/2674815/70372372-eaf42600-1918-11ea-8e75-f02a15e40fe4.png)

this does work in page load but does not work only when delayed_job executes and ends up with this error.

Please help.

**Comment by mullermp** [comment]
Have you added `gem 'aws-sdk-s3', '~> 1'` to your Gemfile? Which version of Rails are you using? Is there a reason you are trying to do `require 'aws-sdk-s3'` inside your model? - that's typically not the best practice AFAIK.

**Comment by nagrgk** [comment]
hi @mullermp 

module is added in model but had to move to delayed_job. but delayed_job does not work with aws-sdk. I had made it worked by manual sdk installation. now it is started working.

manual
unpack gem <gemname>
and use it in project

**Comment by mullermp** [comment]
It should be working just like any other library. Can you use other 3rd party libraries in delayed_job? What version of Rails are you using? I don't recommend unpacking the gem and using it the way you did, but if it works for you, then I am going to close this issue.
