### ISSUE TITLE
StartMedicalStreamTranscription Missing

### ISSUE THREAD

**Issue by yasyf** [aws/aws-sdk-ruby#2189]
### Issue description

The [`StartMedicalStreamTranscription`](https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html) endpoint is missing in `Aws::TranscribeStreamingService`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`aws-sdk-transcribestreamingservice`, `1.10.0`

### Version of Ruby, OS environment

`2.6.5`, macOS

### Code snippets / steps to reproduce

N/A

**Comment by mullermp** [comment]
Which region are you trying to use? The endpoints for available regions should be listed here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-partitions/partitions.json#L3792

**Comment by yasyf** [comment]
@mullermp for any region, it doesn't appear to be possible to use the sdk for this endpoint, as there isn't even a generated method for it (you can see in the code there is a `start_stream_transcription` but no `start_medical_stream_transcription`)

**Comment by mullermp** [comment]
I see what you are asking now - An endpoint refers to the URL. All operations (such as StartStreamTranscription) will go to an endpoint (such as transcribestreaming.<region>.amazonaws.com). I will investigate and get back to you.

**Comment by mullermp** [comment]
It seems that the operation is a Websocket API which the SDK currently does not support.

**Comment by yasyf** [comment]
@mullermp there's one that's not a websocket API: https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html

**Comment by yasyf** [comment]
it's basically identical to the existing `start_stream_transcription`, the parameters are just named differently

**Comment by mullermp** [comment]
Soft update - I thought so, too, after I first talked with them, because there are docs for that API as well as StartMedicalStreamTranscriptionWebSocket. I talked with the service team again and they told me that their documentation is wrong. They are insisting that it's a Websocket only API, and if that's true, then all SDKs do not support it yet. Ruby/Java support http2 but that's about it right now. Expect to see the documentation to change some time soon.

**Comment by yasyf** [comment]
@mullermp got it, glad we didn't do the work of coding against the API in the docs then 😌

**Comment by yasyf** [comment]
is there a timeline for supporting the websocket in the ruby SDK? mostly just curious!

**Comment by mullermp** [comment]
No timeline right now unfortunately. It's a fairly big feature. Pull requests are certainly welcome.. Out of curiosity, does `start_stream_transcription` fit your use case at all?

**Comment by yasyf** [comment]
@mullermp potentially :) we're currently using Google Cloud for transcription and the only reason I could see us putting the work in to switch atm would be to take advantage of the medical-specific models AWS offers (we're a healthcare company)

**Comment by mullermp** [comment]
Ah ok. Sorry for the inconvenience, then. I am going to close the issue. I will make sure the transcribe team pushes changes to their docs. Given the holidays, it may take some time though.
