### ISSUE TITLE
aws.config check inside ECS container to use IAM role credentials

### ISSUE THREAD

**Issue by dayyehm** [aws/aws-sdk-ruby#2191]
Please fill out the sections below to help us address your issue

### Issue description
using Ruby SDK https://github.com/aws/aws-sdk-ruby with my ruby on rails app and deployed on ECS. But when I'm checking Aws.config inside container, it returns `{:execution_env=>"AWS_ECS_EC2", :region=>"eu-west-2"}`. execution_env creating problem when I try to create Dynamo client with `Aws::DynamoDB::Client.new`. it throw  error `ArgumentError: invalid configuration option `:execution_env'`. 
Is it default variable?
How can I fix this?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
      aws-sdk-dynamodb (~> 1)
      aws-sdk-dynamodbstreams (~> 1)

### Version of Ruby, OS environment
ruby:2.4.3-alpine
### Code snippets / steps to reproduce
I assume that  Ruby SDK checks credentials in the following order : 
static_credentials -> env_credentials -> shared_credentials -> instance_profile_credentials

Is there a way to populate the credentials to use the permissions granted to the container in ECS (IAM role). 

can you please advise

**Comment by mullermp** [comment]
As a work around, can you try deleting `:execution_env` from the Aws.config hash?

**Comment by dhakad-rakesh** [comment]
Yes, we tried after deleting :execution_env and it works, but why this value is present in Aws.config even not a configurable option.

**Comment by mullermp** [comment]
It looks like it's set in `ENV['AWS_EXECUTION_ENV']` but it's still unclear to me how that's been added to the Aws.config hash.

**Comment by mullermp** [comment]
How are you populating your credentials? Are they from the instance metadata?

**Comment by mullermp** [comment]
I tried to reproduce this; I logged into an EC2 host of mine, I started a docker container, I exported the environment variable with `export AWS_EXECUTION_ENV='AWS_ECS_EC2'`, I then checked out the latest code from `aws-sdk-ruby` and ran `gems/aws-sdk-resources/bin/aws-v3.rb`, then I was able to successfully create a DynamoDB client. I didn't see `execution_env` anywhere. Can you double check that you aren't doing it anywhere in any configurations?

**Comment by mullermp** [comment]
@dayyehm @dhakad-rakesh Are either of you using `aws-sdk-rails` by chance?

**Comment by dhakad-rakesh** [comment]
We attached Task IAM role for credential

**Comment by dhakad-rakesh** [comment]
> @dayyehm @dhakad-rakesh Are either of you using `aws-sdk-rails` by chance?

we follow the same steps described [here](https://github.com/aws/aws-sdk-ruby) and included `gem 'aws-sdk', '~> 3'` in Gemfile.

**Comment by dhakad-rakesh** [comment]
> I tried to reproduce this; I logged into an EC2 host of mine, I started a docker container, I exported the environment variable with `export AWS_EXECUTION_ENV='AWS_ECS_EC2'`, I then checked out the latest code from `aws-sdk-ruby` and ran `gems/aws-sdk-resources/bin/aws-v3.rb`, then I was able to successfully create a DynamoDB client. I didn't see `execution_env` anywhere. Can you double check that you aren't doing it anywhere in any configurations?

[here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/user_agent.rb#L17) is the code for setting execution_env

**Comment by dhakad-rakesh** [comment]
It also throws an error with `container_credentials_relative_uri` variable.

`irb(main):005:0> Aws.config
=> {:container_credentials_relative_uri=>"*******", :execution_env=>"AWS_ECS_EC2", :region=>"eu-west-2"}
irb(main):006:0> ddb_client = Aws::S3::Client.new
ArgumentError: invalid configuration option `:container_credentials_relative_uri'
	from (irb):6
`

**Comment by dhakad-rakesh** [comment]
According to [here](https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/gems/aws-sdk-core/lib/aws-sdk-core/plugins/global_configuration.rb#L32), It will through an error when we provide service-specific variable to global. But I think we can define  `execution_env` and `container_credentials_relative_uri` globally.

**Comment by mullermp** [comment]
> > I tried to reproduce this; I logged into an EC2 host of mine, I started a docker container, I exported the environment variable with `export AWS_EXECUTION_ENV='AWS_ECS_EC2'`, I then checked out the latest code from `aws-sdk-ruby` and ran `gems/aws-sdk-resources/bin/aws-v3.rb`, then I was able to successfully create a DynamoDB client. I didn't see `execution_env` anywhere. Can you double check that you aren't doing it anywhere in any configurations?
> 
> [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/user_agent.rb#L17) is the code for setting execution_env

This is for the user agent. It is not (and should not) be copied into the `Aws.config` hash. Check your initialization code to see what you are adding to `Aws.config`.

**Comment by dhakad-rakesh** [comment]
I initialize only with the region. `container_credentials_relative_uri` is set when I attach ECS task IAM role to task definition.

**Comment by mullermp** [comment]
Could you provide any code snippets for how you are doing that?

**Comment by mullermp** [comment]
I'm not sure how those are ending up in `Aws.config`. If would suggest that you delete them before initializing a client. If you need them for a particular client (which ones..?) you can put them in a specific service hash: `Aws.config[:\<service name\>]` just like you saw [here](https://github.com/aws/aws-sdk-ruby/blob/97b28ccf18558fc908fd56f52741cf3329de9869/gems/aws-sdk-core/lib/aws-sdk-core/plugins/global_configuration.rb#L32).

**Comment by dhakad-rakesh** [comment]
I'm initializing multiple clients on multiple places for different aws services in my app. So I think delete variable is not a better solution

**Comment by dhakad-rakesh** [comment]
> Could you provide any code snippets for how you are doing that?

I added in Gemfile and try to create client by following code:
`ddb_client = Aws::DynamoDB::Client.new`

**Comment by mullermp** [comment]
Were you able to resolve this?
