### ISSUE TITLE
SSO client BadRequests with access token from OIDC

### ISSUE THREAD

**Issue by MattRMcFarland** [aws/aws-sdk-ruby#2196]
### Issue description

When I attempt to use the `Aws::SSO::Client` authorized with an access token created from the `Aws::SSOOIDC::Client`, I receive `BadRequest` errors. These errors are unexpected given that an equivalent invocation with the `aws2 sso` cli produces the expected results

Also posted an AWS forum thread [here](https://forums.aws.amazon.com/thread.jspa?threadID=314482&tstart=0). Unanswered as of 12/20/2019.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
`aws-sdk-sso` version 1.0.0

### Version of Ruby, OS environment
Ruby 2.5.1, MacOS 10.15.2

### Code snippets / steps to reproduce

I'll first demonstrate how I obtain an SSO OIDC access token
```ruby
require 'aws-sdk-sso'
require 'aws-sdk-ssooidc'

client = Aws::SSOOIDC::Client.new(region: 'us-west-2')

register = client.register_client({
  client_name: "laptop",
  client_type: "public",
  scopes: [ "openid", "sso-portal:*" ] # Unclear if these scopes are the right scopes
})

auth = client.start_device_authorization({
  client_id: register.client_id,
  client_secret: register.client_secret,
  start_url: "https://ORGANIZATION.awsapps.com/start",
})

# you need to hit the uri in a browser from auth.verification_complete_uri
Kernel.system("open #{auth.verification_uri_complete}")

token = client.create_token({
  client_id: register.client_id,
  client_secret: register.client_secret,
  grant_type: "urn:ietf:params:oauth:grant-type:device_code",
  device_code: auth.device_code,
  code: auth.device_code,
  scope: [ "openid", "sso-portal:*" ]
})

# save results from this access token
puts token.access_token
```

I'll demonstrate that this access token does in fact allow me to retrieve role credentials with the `aws2 sso` cli tool.
```bash
>$ ACCOUNT='<ACCOUNT_ID>'
>$ ROLE='<ROLE_NAME>'
>$ SSO_OIDC_TOKEN='<TOKEN_PASTED_FROM_RUBY_SHELL>'
 
>$ aws2 sso get-role-credentials --region us-west-2 \
  --role-name $ROLE \
  --account-id $ACCOUNT \
  --access-token $SSO_OIDC_TOKEN \
  --output json

{
    "roleCredentials": {
        "accessKeyId": "[FILTERED]",
        "secretAccessKey": "[FILTERED]",
        "sessionToken": "[FILTERED]",
        "expiration": 1576861960000
    }
}
```

However, when I try to replicate this with the ruby SSO client, I receive `BadRequest`

```ruby
sso = Aws::SSO::Client.new(region: 'us-west-2')

credentials = sso.get_role_credentials({
  role_name: "[ROLE]",
  account_id: "[ACCOUNT_ID]",
  access_token: token.access_token # from token set in above ruby snippet
})

Traceback (most recent call last):
       10: from /Users/user/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        9: from (irb):28
        8: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-sso-1.0.0/lib/aws-sdk-sso/client.rb:299:in `get_role_credentials'
        7: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/seahorse/client/request.rb:70:in `send_request'
        6: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
        5: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        4: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
        3: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
        2: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        1: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.86.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
Aws::SSO::Errors::BadRequest ()
```

Note: I moved my `~/.aws/` directory to a different location (`~/.aws-diff/`) during these experiments to make sure that no credentials or profiles were getting loaded.

**Comment by mullermp** [comment]
Thanks for the detailed report. Would you mind also passing `http_wire_trace: true` into your client constructor to better debug this?

**Comment by MattRMcFarland** [comment]
```
irb(main):039:0> credentials = sso.get_role_credentials({
irb(main):040:2*   role_name: "[FILTERED]",
irb(main):041:2*   account_id: "[FILTERED]",
irb(main):042:2*   access_token: token.access_token
irb(main):043:2> })
opening connection to portal.sso.us-west-2.amazonaws.com:443...
opened
starting SSL for portal.sso.us-west-2.amazonaws.com:443...
SSL established
<- "GET /federation/credentials?role_name=AdministratorAccess&account_id=[FILTERED] HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.86.0 ruby/2.5.1 x86_64-darwin18 aws-sdk-sso/1.0.0\r\nX-Amz-Sso_bearer_token: [FILTERED]\r\nContent-Length: 0\r\nAccept: */*\r\nHost: portal.sso.us-west-2.amazonaws.com\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Date: Fri, 20 Dec 2019 23:00:01 GMT\r\n"
-> "Content-Type: text/html;charset=utf-8\r\n"
-> "Content-Length: 1064\r\n"
-> "Connection: keep-alive\r\n"
-> "Server: Apache-Coyote/1.1\r\n"
-> "Content-Language: en\r\n"
-> "\r\n"
reading 1064 bytes...
-> "<!doctype html><html lang=\"en\"><head><title>HTTP Status 400 \xE2\x80\x93 Bad Request</title><style type=\"text/css\">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 400 \xE2\x80\x93 Bad Request</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class=\"line\" /></body></html>"
read 1064 bytes
Conn keep-alive
```

**Comment by mullermp** [comment]
Thanks. Could you also try `--debug` or whatever other equivalent exists when using the AWS CLI to verify your token?

**Comment by MattRMcFarland** [comment]
Debug output from the awscli in the attached file.
[sso_debugging.txt](https://github.com/aws/aws-sdk-ruby/files/3990710/sso_debugging.txt)

**Comment by mullermp** [comment]
It appears that the empty `Content-Type:` header is breaking the SSO service. Python does not include this header, either. I verified this using `curl` against the portal with headers. I'm working with the service team on the appropriate fix here. We send empty `content-type` and `accept-encoding` headers by default to avoid breaking other services. My inclination is that the service team must handle the empty `content-type` header case -- It's not clear to me if that's "legal" from a request point of view, though, `content-length` is set to 0.

**Comment by MattRMcFarland** [comment]
Thanks @mullermp! Looking forward to the fix.

**Comment by mullermp** [comment]
To clarify further, we have two options. Option 1 is the SSO service should handle empty headers. This is the safest and easiest change (additive). Option 2 is from the Ruby side --  I'm not sure what I can do to avoid any potential breakage.

Way [deep in the HTTP handler](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/net_http/handler.rb#L166-L167) we add empty `content-type` and `accept-encoding` headers.

These were added a very long time ago and I'm not entirely certain what would happen if we were to remove these - 

https://github.com/aws/aws-sdk-ruby/commit/e0ea09b9d93f77575d8b4a93aa65a82134496dca#diff-659048b771f9e6005df3c3d00a27f32fR100

https://github.com/aws/aws-sdk-ruby/commit/fbc818a47df2ca00235a246df46265d945aba9d8

https://github.com/aws/aws-sdk-ruby/blame/version-1/lib/aws/core/http/net_http_handler.rb#L111-L118

I definitely know that tests (unit and integration) will need new signatures since the header woudl be removed. There are also some services that may break and I have no way of knowing what breaks! If I were to remove these, then services that do break would need a plugin to add an appropriate header.

**Comment by mullermp** [comment]
A workaround, for now, would be to use backticks to shell out to curl or CLI and parse the response in Ruby.

**Comment by MattRMcFarland** [comment]
@mullermp if other AWS services can handle empty `content-type` and `accept-encoding` headers, then it seems appropriate for the SSO service to also handle that.

But I understand that downstream service fixes are blocking and outside your control. I don't quite know how you measure the risk of breaking something against the importance of getting a fix out quickly but it seems that changing deep http handler behavior could be dangerous and hard to predict.

In my use case, I'm utilizing the workaround
```
role_credentials = JSON.parse(`aws2 sso get-role-credentials --account-id #{account} --role-name #{role} --access-token #{token} --region us-west-2 --output json`)
```
and that's working quite well.

The only gotcha is that I'll need to make sure my coworkers install `aws2` before running this command.

I'm checking the presence of the `aws2` cli with

```
if `which aws2`.blank?
  puts("Please install aws2!")
  exit(1)
end
```

**Comment by singku** [comment]
`  code: auth.device_code,` 
Should this `device_code`should be `user_code` got from `start_device_authorization`?

**Comment by MattRMcFarland** [comment]
@singku No I think I have the codes the right way around. When I tried in in the reverse ordering you're suggesting, I was getting errors. I can reproduce if you'd find that helpful, but I don't have that output on hand at the moment.

**Comment by singku** [comment]
Looking at the document,  it looks like the user code though

**Comment by MattRMcFarland** [comment]
@singku Are you stating the documentation is unclear? Or is there additional validation that you and the other maintainers would like me to do?

**Comment by MMartyn** [comment]
I also ran into this issue. My temp workaround until fixed was to freedom patch with:

```ruby
module Seahorse
  module Client
    module NetHttp
      class Handler
        def headers(request)
          # dont set for sso endpoint
          headers = if request.endpoint.host =~ /\.sso\./
                       {}
                    else
                      { 'content-type' => '', 'accept-encoding' => '' }
                    end
          request.headers.each_pair do |key, value|
            headers[key] = value
          end
          headers
        end
      end
    end
  end
end
```

**Comment by MMartyn** [comment]
I'll have to go back and double check but I think I was getting this error on the list_accounts calls, so likely you would need that plugin for all of those sso operations.

**Comment by mullermp** [comment]
@MMartyn Ah ok! Please double check and let me know.

**Comment by MMartyn** [comment]
> @MMartyn Ah ok! Please double check and let me know.

Confirmed, I was getting the BadRequest error on the list_account call as well, so I do think you will have to add the plugin to all calls to that endpoint.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/pull/2207

**Comment by fer1035** [comment]
Thank you. I've been searching everywhere for "urn:ietf:params:oauth:grant-type:device_code" to use with the Python SDK (boto3). It doesn't seem to be documented anywhere in the official AWS docset.
