### ISSUE TITLE
Chime Account provided is not an Enterprise Chime Account

### ISSUE THREAD

**Issue by OBCENEIKON** [aws/aws-sdk-ruby#2201]
Issue Description:
When attempting to `list_rooms` or `list_room_memberships` for team accounts I am getting the following error:
```
Aws::Chime::Errors::ForbiddenException Chime Account provided is not an Enterprise Chime Account[AWS Account ID: xxxxxxxxxxxx][Chime Account ID: 6153241f-5a0e-4c24-bd9b-0e91ac3adbd1]
```

Gem Name:
`aws-sdk-chime` `1.17.0`

Version of Ruby:
`2.5.0`
OS environment:
docker container running `Debian GNU/Linux 9 (stretch)`

Code Snippets / Steps to Reproduce:
```
client.list_accounts.accounts.each do |account|
  client.list_rooms(account_id: account.account_id).rooms.each do |room|
    client.list_room_memberships(account_id: account.account_id, room_id: room.room_id).room_memberships.each do |membership|
      puts "Account ID: #{account.account_id}, Room ID: #{room.room_id}, Member ID: #{membership.member[:account_id]}"
    end
  end
end
```

Changing `list_accounts` to the following will let me get past the error
```
client.list_accounts.accounts.select { |account| account.account_type != 'Team' }.each do |account|
```

Error Message:
```
Aws::Chime::Errors::ForbiddenException Chime Account provided is not an Enterprise Chime Account[AWS Account ID: xxxxxxxxxxxx][Chime Account ID: 6153241f-5a0e-4c24-bd9b-0e91ac3adbd1]
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.85.1/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/bundle/gems/aws-sdk-chime-1.17.0/lib/aws-sdk-chime/client.rb:2737:in `list_rooms'
```

**Comment by ajredniwja** [comment]
Hey @OBCENEIKON, thank-you for reaching out to us with your issue.

Can you please make sure your account is not a team account. 

You can make account as enterprise account using information at:
https://docs.aws.amazon.com/chime/latest/ag/getting-started.html#acct-settings

**Comment by OBCENEIKON** [comment]
Hello @ajredniwja - I guess that might be more of the question or issue here.

The application that I am working on will remove Chime components and configurations from an account. These can be mixed accounts, both Team or Enterprise. Does `list_rooms` and `list_room_memberships` both require an account to be an Enterprise account? Will I have to filter out Team accounts in order to run these API methods for both Team and Enterprise accounts?

**Comment by ajredniwja** [comment]
I was able to reproduce the behavior however the docs don't mention that it should be Enterprise account for any of the functions. I can go confirm with the service team what is the root cause of it. Will update you.

**Comment by ajredniwja** [comment]
Confirmed that it is a bug with the docs, the service team will update the docs soon.

**Comment by mullermp** [comment]
Docs have been fixed and is staging in a release sometime next week or so.

**Comment by Evvanz12** [comment]
[](url)

**Comment by mullermp** [comment]
The docs have been updated with these clarifications.
