### ISSUE TITLE
Chime - Optional Parameter is Required

### ISSUE THREAD

**Issue by OBCENEIKON** [aws/aws-sdk-ruby#2213]
Issue Description:
The only way I am able to get `delete_voice_connector_termintion_credentials` to work is to send both the `voice_connector_id` and `usernames`.
The documentation says that `usernames` is optional.

Gem Name:
`aws-sdk-chime` `1.18.0`

Version of Ruby:
`2.5.0`
OS environment:
docker container running `Debian GNU/Linux 9 (stretch)`

Code Snippets / Steps to Reproduce:
```
client.list_voice_connectors.voice_connectors.each do |voice_connector|
  client.delete_voice_connector_termination_credentials(voice_connector.voice_connector_id)
end
```

Error Message:
```
Aws::Chime::Errors::BadRequestException Service received a bad request
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/bundle/gems/aws-sdk-chime-1.18.0/lib/aws-sdk-chime/client.rb:1568:in `delete_voice_connector_termination_credentials'
/app/app/services/actors/aws_actors/chime/voice_connector_termination_credentials_actor.rb:14:in `delete!'
```

**Comment by mullermp** [comment]
Confirmed - I got a bad request error without providing usernames. @ajredniwja some clarification will be needed from the Chime service team, and likely their API will need to be updated to reflect this: https://github.com/aws/aws-sdk-ruby/blob/master/apis/chime/2018-05-01/api-2.json#L2569

**Comment by mullermp** [comment]
Hey - Just FYI this has been fixed (https://github.com/aws/aws-sdk-ruby/blob/master/apis/chime/2018-05-01/api-2.json#L3206-L3207)

**Comment by mullermp** [comment]
Sorry this took so long. We pushed on the Chime team to get these changes out faster but they lumped them into a recent feature launch.
