### ISSUE TITLE
Chime - Can't Delete Enterprise Account

### ISSUE THREAD

**Issue by OBCENEIKON** [aws/aws-sdk-ruby#2214]
Issue Description:
I am not able to delete an enterprise account, I believe that there is still a domain that needs to be released, but I don't see a way of doing that through the Chime API.
I've included the account produced from `list_accounts` that is causing the problem.
```
{:aws_account_id=>"245319550715", :account_id=>"4f61d710-c454-4761-b936-b5a799010005", :name=>"[FILTERED]", :account_type=>"EnterpriseDirectory", :created_timestamp=>2020-01-07 16:45:48 UTC, :default_license=>"Pro", :supported_licenses=>["Basic", "Pro"], :signin_delegate_groups=>[]}
```

Gem Name:
`aws-sdk-chime` `1.18.0`

Version of Ruby:
`2.5.0`
OS environment:
docker container running `Debian GNU/Linux 9 (stretch)`

Code Snippets / Steps to Reproduce:
```
client.list_accounts.accounts.each do |account|
  client.list_users(account_id: account.account_id).users
    .map(&:user_id)
    .in_groups_of(50, false) do |user_id|
      client.batch_suspend_user(account_id: account.account_id, user_id_list: user_id)
    end

  client.delete_account(account_id: account.account_id)
end
```

Error Message:
```
Aws::Chime::Errors::NotFoundException Unable to find the requested identifier
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/usr/local/bundle/gems/aws-sdk-core-3.89.1/lib/seahorse/client/request.rb:70:in `send_request'
/usr/local/bundle/gems/aws-sdk-chime-1.18.0/lib/aws-sdk-chime/client.rb:1250:in `delete_account'
/app/app/services/actors/aws_actors/chime/accounts_actor.rb:15:in `delete!'

```

**Comment by mullermp** [comment]
[This documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Chime/Client.html#delete_account-instance_method) suggests that you need to release the domain (I agree, I don't see any API options to do so). It also says it should suspend users on your behalf, then you can call delete. I verified `delete_account` works at least with a non-enterprise account. @ajredniwja Please forward this feedback to the service team and ask if there's any workaround or if they'll implement an API for releasing domains.

**Comment by mullermp** [comment]
Can confirm that on an enterprise account:

[Aws::Chime::Client 422 0.440194 0 retries] delete_account(account_id:"367b28da-979b-41b9-b533-aaaad801fda3") Aws::Chime::Errors::UnprocessableEntityException Request contains unprocessable entity

**Comment by mullermp** [comment]
I was able to delete the account once I removed the domain, though, there should be an API to do so?

**Comment by mullermp** [comment]
Soft update- Chime team is doing an AppSec review for this feature. No ETA.

**Comment by mullermp** [comment]
Chime is now tracking this feature request. We are closing this issue as it is no longer something we need to track.
