### ISSUE TITLE
Resources missing DeleteTags

### ISSUE THREAD

**Issue by sj26** [aws/aws-sdk-ruby#2215]
**Is your feature request related to a problem? Please describe.**
The "Resources" APIs have CreateTags operations which are great, but are missing DeleteTags.

For example, at [a top level](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Resource.html#create_tags-instance_method):

```ruby
ec2 = AWS::EC2::Resource.new
ec2.create_tags(resources: ["ami-abc123"], tags: [{key: "Foo", value: "bar"}])
```

or on [a resource like Image](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Image.html#create_tags-instance_method):

```ruby
ec2 = AWS::EC2::Resource.new
image = ec2.image("ami-abc123")
image.create_tags(tags: [{key: "Foo", value: "bar"}])
```

but is missing the equivalent `delete_tags` methods, which means resorting to a `Aws::EC2::Client`:

```ruby
client = AWS::EC2::Client.new
client.delete_tags(resources: ["ami-abc123"], tags: [{key: "Foo", value: "bar"}])
```

This is very awkward when one already has a resource object:

```ruby
ec2 = AWS::EC2::Resource.new
client = AWS::EC2::Client.new
ec2.images.each do |image|
  image.create_tags(tags: [{key: "Foo", value: "bar"}])
  client.delete_tags(resources: [image.id], tags: [{key: "Baz", value: "qux"}])
end
```

**Describe the solution you'd like**

```ruby
ec2 = AWS::EC2::Resource.new
ec2.delete_tags(resources: ["ami-abc123"], tags: [{key: "Foo", value: "bar"}])
```

```ruby
ec2 = AWS::EC2::Resource.new
image = ec2.image("ami-abc123")
image.delete_tags(tags: [{key: "Foo", value: "bar"}])
```

```ruby
ec2 = AWS::EC2::Resource.new
ec2.images.each do |image|
  image.create_tags(tags: [{key: "Foo", value: "bar"}])
  image.delete_tags(tags: [{key: "Baz", value: "qux"}])
end
```

**Describe alternatives you've considered**
The alternative is to use the Client API as above, but it's comparatively awkward, especially amongst code already using the Resource API.

**:wave: I may be able to implement this feature request**
It looks like this can be implemented by updating the resources json, then regenerating — but that looks pretty automated so I don't want to go poking around before confirming the approach.

**Additional context**
(n/a)

**Comment by mullermp** [comment]
Thanks for the feature request. Yes, you are correct that the resources file needs to be updated, but it must be committed to an upstream source internally, and then the changes are released to every SDK. Merging from GitHub into this repo would be overwritten.

**Comment by mullermp** [comment]
If you'd like to implement this feature, I can take the diff and patch it upstream.

**Comment by alextwoods** [comment]
Just as a quick update - I'm working on implementing this.

**Comment by sj26** [comment]
Amazing, thanks @alextwoods! I meant to come back to this, but never got around to ti.

**Comment by mullermp** [comment]
The changes for this have been merged. It's sitting in a future ec2 release.

**Comment by sj26** [comment]
Amazing, thank you!

**Comment by alextwoods** [comment]
The changes have been released and should be available in the latest gems.

**Comment by sj26** [comment]
Amazing, thanks!
