### ISSUE TITLE
MTurk API - re-publishing HITs.

### ISSUE THREAD

**Issue by t-romani** [aws/aws-sdk-ruby#2218]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**

Let's say I have an app that works with MTurk aws sdk. I will be creating HITs and approving/rejecting assignments. All of my HITs can have up to one assignment. 
When I do reject an assignment through the API, I would like the HIT to be re-published, allowing workers to take the HIT again, thing I can do on the website, but I cannot or haven't find out how to do on the API. 
Instead, the HIT status reminds as `Reviewable` 

Any tips? 😀

**Comment by mullermp** [comment]
Hey @t-romani, I've never used MTurk but I'll try my best here. My thought is that the console is creating a new HIT on your behalf. When you republish through the website, could you tell me if the HIT ID is the same after republishing? If not, I am thinking that, given the `assignment_id` you can call `get_assignment` to get the HIT ID, get additional details with `get_hit` and then call `create_hit`. It sounds round-a-bout. We can reach out to the service team to find out the best practice here.

**Comment by t-romani** [comment]
This makes a lot of sense. 
I’ll check out tomorrow if HITs IDs persist on republish and get back to this. 

That’s definitely a way through it tho, I just don’t find discarding a HIT and creating the exact same one due to a wrong assignment very efficient 🤷‍♀

**Comment by mullermp** [comment]
@t-romani I understand. It's not very efficient. If the HIT IDs persist, there must be a way.

**Comment by mullermp** [comment]
@t-romani One of our SDK team members worked on MTurk at one point and I talked with him about this issue. He says that the web console might be using the [additional assignments for HIT operation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MTurk/Client.html#create_additional_assignments_for_hit-instance_method). I noticed that you have 1 assignment per HIT. Using this API, I think that you can (and should) increase the assignments per HIT. When you reject one, you can assign the same person a new assignment on the same HIT.

**Comment by t-romani** [comment]
Amazing @mullermp, that should do it, 10 times failure probability sure is low enough.
