### ISSUE TITLE
Broken function

### ISSUE THREAD

**Issue by epinault** [aws/aws-sdk-ruby#2220]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Bucket.objects method not working as expected. It is broken when you use delimiter. Instead of parsing the common prefix, it uses the contents field which is incorrect per the documentation of the S3 API

check the source code https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Bucket.html#objects-instance_method

```
def objects(options = {})
  batches = Enumerator.new do |y|
    options = options.merge(bucket: @name)
    resp = @client.list_objects_v2(options)
    resp.each_page do |page|
      batch = []
      page.data.contents.each do |c|
        batch << ObjectSummary.new(
          bucket_name: @name,
          key: c.key,
          data: c,
          client: @client
        )
      end
      y.yield(batch)
    end
  end
  ObjectSummary::Collection.new(batches)
end
```
access to  page.data.contents is wrong if you pass a delimiter

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk 3.0.1

**Version of Ruby, OS environment**
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19] 

**To Reproduce (observed behavior)**
try to passe the following options

```
 s3 = Aws::S3::Resource.new(region: 'us-west-2')
bucket = s3.bucket("somebucket")
bucket.objects( delimiter: "/", prefix: "path/to/prefix/")
```

**Expected behavior**
I would expect it to return the list of common_prefixes since I am trying to get the list of folders under another folder (well at least aggregating the common keys)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ajredniwja** [comment]
Hey @epinault, thank-you for reaching out to us with your issue. 

Looking at the documentation https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Bucket.html#objects-instance_method I wasn't able to find a response structure that mentioned ```resp.common_prefixes```.

I would recommend you ti use ```list_objects``` as mentioned [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects-instance_method) and use ```resp.common_prefixes```.

**Comment by epinault** [comment]
hey you are missing my point. Your code does not look at the common prefixes. it should in the object version . You code is incoherent and not working if you use delimiter.

**Comment by mullermp** [comment]
Hi @epinault, it does look like the resource model is not working for your use case.

I was able to successfully use common prefixes using the client API following [these examples](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html) in the documentation:

`s3.list_objects(bucket: '<my bucket>', prefix: 'North America/Canada/', delimiter: '/').data.common_prefixes`

But for a resource model, only `ObjectSummary` objects are returned, which doesn't include common prefixes.

Regarding code changes for this, I don't think I can simply remove `data.contents` in that method without breaking current customers who are not relying on that delimiter. There may be a crafty way to fix it, happy to take a pull request on that. In general, resource models are not always ideal and implementation is a huge hack where functionality is added through monkey patching. I highly recommend that you use the client API for this kind of query.

**Comment by mullermp** [comment]
Closing this as the client api is a workaround in this particular case. The resource model code is generated and changing it (even to fix this) would break customers.

**Comment by epinault** [comment]
Sure the model work , the Object model is pretty useless to me then at this point.. not sure that would break someone since it does not function as expected anyway and return empty result.. But that seems to me that should be fix
