### ISSUE TITLE
Creating an EC2 client throws a fatal exception "Stack trace too deep"

### ISSUE THREAD

**Issue by Andrew-Max** [aws/aws-sdk-ruby#2230]
Confirm by changing [x ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When referencing the EC2 client a "Stack Trace Too Deep" exception is thrown
```
 ec2_client = Aws::EC2::Client.new(
    region: "us-west-1",
    credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV["AWS_SECRET_ACCESS_KEY"]),
 )
```

Edit, I have updated this to reflect that I can now reproduce this off of Heroku. It looks like a config issue but I cannot figure out any configuration setup that does not cause the error.

I have tried

- setting config in `~/.aws/credentials`
- setting config in `application.yml` with figaro
- setting the config directly in the method with 
```
    Aws.config.update({
      region: ENV['AWS_REGION'],
      credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV["AWS_SECRET_ACCESS_KEY"])
    })

```
A rails app that experiences this issue has been posted at: 
https://github.com/Andrew-Max/aws-example

Just visit the route `/aws`
The full stack trace thrown with the error is:

```
bootsnap (1.4.5) lib/bootsnap/compile_cache/iseq.rb:12:in `to_binary'
bootsnap (1.4.5) lib/bootsnap/compile_cache/iseq.rb:12:in `input_to_storage'
bootsnap (1.4.5) lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
bootsnap (1.4.5) lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
zeitwerk (2.2.2) lib/zeitwerk/kernel.rb:23:in `require'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
aws-sdk-ec2 (1.144.0) lib/aws-sdk-ec2.rb:12:in `<main>'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
bootsnap (1.4.5) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
zeitwerk (2.2.2) lib/zeitwerk/kernel.rb:23:in `require'
app/controllers/test_controller.rb:9:in `aws'
actionpack (6.0.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.2.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.2.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.2.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.2.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.2.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.2.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread' 
```
**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
('aws-sdk',

**Version of Ruby, OS environment**
-paste the output of ruby -v

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
`ruby '2.6.3'`, 

**Expected behavior**
No exception
**Screenshots**

**Additional context**

**Comment by alextwoods** [comment]
I wasn't able to reproduce locally (outside of Heroku) yet.  What type of credentials are you using?

**Comment by alextwoods** [comment]
We recently made a change to pass region from clients through to assume_role_web_identity_credentials.  (see: https://github.com/aws/aws-sdk-ruby/pull/2227)  This could be related, but shouldn't apply when you are manually passing in a credentials object to the client.

**Comment by Andrew-Max** [comment]
> I wasn't able to reproduce locally (outside of Heroku) yet. What type of credentials are you using?

This is consistent with my experience as well. This code runs fine for me off of heroku. I'm going to work on getting a public repo hosted that should reproduce the issue if deployed to Heroku.

I filed a support ticket with Heroku as well and they did prove that it is possible in at least some context to get this code to run on a heroku environment (they did it imperatively, line by line,  directly through the command line)

In terms of credentials, my setup is:  `@credentials = Aws::Credentials.new(access_key, secret_key)`

I will respond once I have the sample application up

**Comment by mullermp** [comment]
Are you able to pull a stack trace? If it's too deep, likely some recursion / infinite loop going on. I'm willing to bet it's some sort of configuration issue.

**Comment by Andrew-Max** [comment]
@mullermp stack trace posted in the issue as well as a link to a barebones rails app which reproduces the issue

**Comment by Andrew-Max** [comment]
Follow up on this:  keeping the code identical but changing my gem setup gets this passing. I changed from this

```
gem 'aws-sdk', '~> 3'
```

to 

```
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-ec2', '~> 1'

```

Not really sure how to interpret this but it does fix my short term problem and potentially indicates there is a real issue with the `aws-sdk` gem

**Comment by alextwoods** [comment]
@Andrew-Max  - glad you've got a workaround!  The primary difference between the 'aws-sdk' gem and the individual service gems is that the 'aws-sdk' gem will load the individual service gems for all services - so its possible there is some conflict there.

Thanks for providing an example - I'll dive into it tomorrow and see if I can get to a root cause on this error.

**Comment by alextwoods** [comment]
Was able to reproduce this using the provided example.  It looks like a potential issue with bootsnap and the autoload that is done in the aws-sdk-resources gem.   I'll keep investigating this and provide updates here.

Using the modular service gems (eg aws-sdk-s3, aws-sdk-ec2) is the preferred way to use them (reduces the overall application size and number of dependencies).

**Comment by mullermp** [comment]
With your provided example, trying to use a different service client such as SQS will succeed. It is a very strange error. We were able to get the example to work when removing bootsnap. It fails on loading the `client_api` module. It doesn't look to be a problem with `aws-sdk` (that gem only loads [`aws-sdk-resources`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk/lib/aws-sdk.rb#L1) which autoloads [all of the gems](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-resources/lib/aws-sdk-resources.rb). There's likely some conflict between some EC2 type/method/operation in `client_api` and bootsnap..?

As @alextwoods mentioned, we suggest using the modular dependency declaration anyway (`aws-sdk-ec2`, etc).

**Comment by alextwoods** [comment]
The failure is happening in bootsnap when calling to_binary on the compiled InstructionSequence.  see: [ Compile_Cache/iseq.rb](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/compile_cache/iseq.rb#L13)
```ruby
RubyVM::InstructionSequence.compile_file(path).to_binary
```

Its failing on the [client_api](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-ec2/lib/aws-sdk-ec2/client_api.rb) file of the EC2 gem.  

Notably, this seems to only be happening for Ruby 2.6 (tested with 2.6.3 and 2.6.5) but not for 2.5.7 or 2.7.0.  This is likely related to https://github.com/Shopify/bootsnap/issues/246

I'll follow up on that issue with the bootsnap team.

In the mean time, the following are ways to work around this (for anyone else running into this issue):
### Workarounds
* [Recommended] Use the Modular service gems (Eg: add the service gem for each aws service you're application uses).
* Do not use Bootsnap with the aws-sdk umbrella gem (If you're using rails, you can manually require the service gems you need in config/application.rb)
* Use either Ruby 2.5 or 2.7.

**Comment by Andrew-Max** [comment]
Hey sorry I never follow up on this but thanks for digging in and great work on the debugging. Thanks for all your work!
