### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by AlexeyBoldak** [aws/aws-sdk-ruby#2231]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  

**Describe the bug**
Sometimes we get JSON::ParserError, when we try to do lambda invoke request. Looks like this code in aws-sdk-core/lib/aws-sdk-core/json.rb#24 didn't catch JSON::ParserError

```
def load(json)
  ENGINE.load(json, *ENGINE_LOAD_OPTIONS)
rescue *ENGINE_ERRORS => e
  raise ParseError.new(e)
end 
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
bundle show aws-sdk-lambda
/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/aws-sdk-lambda-1.34.0

**Version of Ruby, OS environment**
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
MacOS

**Expected behavior**
I want to get correct response object with correct `function_error`

**Additional context**
Here is error backtrace

```
JSON::ParserError: Empty input () at line 1, column 1 [parse.c:988] in '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

  from aws-sdk-core/json.rb:25:in `load'
  from aws-sdk-core/json.rb:25:in `load'
  from aws-sdk-core/json/error_handler.rb:17:in `extract_error'
  from aws-sdk-core/xml/error_handler.rb:23:in `error'
  from aws-sdk-core/json/error_handler.rb:9:in `block in call'
  from seahorse/client/response.rb:45:in `block in on'
  from seahorse/client/http/response.rb:144:in `block in on_success'
  from seahorse/client/http/response.rb:171:in `block in listener'
  from seahorse/client/http/response.rb:135:in `on_done'
  from seahorse/client/http/response.rb:142:in `on_success'
  from seahorse/client/response.rb:44:in `on'
  from aws-sdk-core/json/error_handler.rb:8:in `call'
  from aws-sdk-core/plugins/signature_v4.rb:66:in `call'
  from aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
  from aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  from aws-sdk-core/plugins/retry_errors.rb:177:in `call'
  from aws-sdk-core/rest/handler.rb:8:in `call'
  from aws-sdk-core/plugins/user_agent.rb:13:in `call'
  from aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
  from aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
  from seahorse/client/plugins/endpoint.rb:45:in `call'
  from aws-sdk-core/plugins/param_validator.rb:24:in `call'
  from seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  from aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  from aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  from aws-sdk-core/plugins/param_converter.rb:24:in `call'
  from aws-sdk-core/plugins/response_paging.rb:10:in `call'
  from seahorse/client/plugins/response_target.rb:23:in `call'
  from seahorse/client/request.rb:70:in `send_request'
  from aws-sdk-lambda/client.rb:2351:in `invoke'
```

**Comment by mullermp** [comment]
Hey there, do you have any code snippets we can use to try and reproduce? It looks like you're getting a "502 Bad Gateway" response (as html) and the SDK is parsing it as JSON.. that will indeed throw an error.

**Comment by AlexeyBoldak** [comment]
@mullermp  Yes, you described our case. The question is it an expected error from your perspective? I mean JSON::ParserError or SDK should handle it and raise SDK error

We caught this error in Sentry, and as I see we send a really big payload to Lambda (because Sentry cut our request body)

**Comment by mullermp** [comment]
@AlexeyBoldak Do you see this error each time you make a call to Lambda or is this a one time error?

You mention a "really big payload" -- Lambda has a 1 MB limit (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html) are you exceeding that limit? It is possible you are seeing that error because of it. I tried to replicate this by sending a 1.1 MB payload and response but couldn't.

As per the error, either Lambda or EC2 is returning some HTML with 502 Bad Gateway and that *would* fail parsing as JSON, because it's not valid JSON.
