### ISSUE TITLE
No response when using DynamoDB from lambda

### ISSUE THREAD

**Issue by BenjaminRouge** [aws/aws-sdk-ruby#2233]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
Hello people

I have two use cases I'm using DynamoDB locally with nodejs and I can create/read/update/delete successfully, no problems

But when I'm using DynamoDB with a lambda configured with a template.yml and with ASW Policies to read create update etc, I can't get response from DynamoDB, I just didn't enter in the callback

Here is the code :
`  AWS.config.update({
      region: "eu-central-1",
    });

    var dynamo = new AWS.DynamoDB.DocumentClient();

    console.log(`[TDF-Rankings] - Trying to put datas in db`);

    dynamo.put({
      TableName: 'tdf-rankings-dev',
      Item: {
        id: uuid(`${Checkpoint.rank_type}.${Checkpoint.season}.${checkpoint.type}.${Checkpoint.number}`),
        ...Checkpoint
        }
    }, (err, res) => {
      console.log(`[TDF-Rankings] - in the callback`);
      if(err){
        console.log(err);
        return err
      }
      console.log(res);
      return res
    })`

I get this : 

`START RequestId: 1e4fb8f0-e081-106d-5c24-58fa931a5892 Version: $LATEST
2020-02-21T18:53:34.820Z        1e4fb8f0-e081-106d-5c24-58fa931a5892    INFO    [TDF-Rankings] - Trying to put datas in db
END RequestId: 1e4fb8f0-e081-106d-5c24-58fa931a5892
REPORT RequestId: 1e4fb8f0-e081-106d-5c24-58fa931a5892  Init Duration: 661.36 ms`

But if  i do this:
`   AWS.config.update({
      region: "eu-central-1",
    });

    var dynamo = new AWS.DynamoDB.DocumentClient();

    console.log(`[TDF-Rankings] - Trying to put datas in db`);

    const request = dynamo.put({
      TableName: 'tdf-rankings-dev',
      Item: {
        id: uuid(`${Checkpoint.rank_type}.${Checkpoint.season}.${checkpoint.type}.${Checkpoint.number}`),
        ...Checkpoint
        }
    }, (err, res) => {
      console.log(`[TDF-Rankings] - in the callback`);
      if(err){
        console.log(err);
        return err
      }
      console.log(res);
      return res
    })

    console.log(request);`

I get a big object
With lot of infos include my request

**Comment by mullermp** [comment]
Hey, can you open an issue in the Javascript SDK repo? This is for Ruby..

https://github.com/aws/aws-sdk-js
