### ISSUE TITLE
Support for RDS IAM authentication via generate_db_auth_token

### ISSUE THREAD

**Issue by md5** [aws/aws-sdk-ruby#2234]
**Is your feature request related to a problem? Please describe.**
It appears that the `generate_db_auth_token` call is not exposed in the Ruby API.

**Describe the solution you'd like**
I'd like to be able to call `Aws::RDS::Client#generate_db_auth_token` to generate a DB auth token.

**Describe alternatives you've considered**
It's unclear from my reading of the `aws-cli` code if `generate_db_auth_token` is a special case of some sort. It looks like there may be no documented `rds:GenerateDBAuthToken` call, so the corresponding client methods are not being generated?

**Additional context**
This call is useful for implementing IAM authentication with RDS.

**Comment by alextwoods** [comment]
You are right that the `generate_db_auth_token`  call in the AWS CLI is a custom command that they have added that isn't normally available from RDS: [AWS CLI Customizations for RDS](https://github.com/aws/aws-cli/blob/4ff0cbacbac69a21d4dd701921fe0759cf7852ed/awscli/customizations/rds.py).

We'll consider this a feature request to add a similar customization to the Ruby SDK.

**Comment by mullermp** [comment]
@md5 Is this what you were looking for? https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-rds/lib/aws-sdk-rds/customizations/auth_token_generator.rb

It's already been implemented

**Comment by md5** [comment]
@mullermp Thanks for pointing out that class. Hopefully this issue can help people find the right class in the future. Ideally, I could see the following improvements made to the class docs to further aid in documenting this solution:

1. Mention IAM Database Authentication
2. Link to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
3. Mention that this class is equivalent to `aws rds generate-db-auth-token`

Currently, the docs have only this extremely vague statement:

> The utility class helps generate an auth token that supports database login

Thanks again @mullermp!

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/commit/f85699927bd0ba09e81ae24b529e04caacf3a14c I didn't mention the CLI equivalent (typically we don't cross reference those)

**Comment by md5** [comment]
That's a great improvement! 🙇🏻‍♂️

>

**Comment by mullermp** [comment]
It's not my finest work, but thanks lol. Hope that helps.
