### ISSUE TITLE
aws sdk v3 upgrade - where did the Aws::S3::Errors::SlowDown exception get moved to?

### ISSUE THREAD

**Issue by sbsurf** [aws/aws-sdk-ruby#2237]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**

**Comment by mullermp** [comment]
Are you upgrading from V1 or V2?

https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/types.rb#L3478-L3484

In S3, they have a generic error class (`Aws::S3::Types::Error`) that will have the appropriate status code

**Comment by sbsurf** [comment]
I'm upgrading from v2. Currently, I rescue like this:

```
rescue Aws::S3::Errors::SlowDown
```
I also raise the exception in my specs to test the rescue logic. Any suggestions on how to do these things in v3?

**Comment by mullermp** [comment]
I couldn't find a reference to it in V2. In V1 it looks like it's generated dynamically here: https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/LazyErrorClasses.html#error_class-instance_method.

V2 S3 errors don't define it: https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Errors.html

In this case you'd probably want to rescue `Aws::S3::Types::Error` and check the status code for 503.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/types.rb#L3559 Here is that error definition line
