### ISSUE TITLE
Missing information in Aws::S3::Client#get_object

### ISSUE THREAD

**Issue by epistrephein** [aws/aws-sdk-ruby#2252]
**Describe the issue with documentation**
Some information are missing in the documentation for `Aws::S3::Client#get_object` regarding how to restore an object in GLACIER or DEEP_ARCHIVE storage classes.

The method documentation reads:

> If the object you are retrieving is stored in the GLACIER or DEEP_ARCHIVE storage classes, before you can retrieve the object you must first restore a copy using . Otherwise [...]

not specifying what needs to be used to restore a copy.

The involved file seems to be:
https://github.com/aws/aws-sdk-ruby/blob/49829e8aa34bf9651dc4836c502ddb9063a8e45a/apis/s3/2006-03-01/docs-2.json#L45

**Screenshots**
From https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#get_object-instance_method

![Screen-Shot-2020-03-09-08-25-31](https://user-images.githubusercontent.com/4941334/76191468-b1fd7300-61df-11ea-9979-dd69606a2af6.png)

**Comment by ajredniwja** [comment]
@epistrephein thank-you for reaching out to us with your issue, I have noticed something similar with the other SDKs documentation as well. I have reached out to the service team to fix their docs as they own the API reference. 

Will update you, once I hear back from them.

**Comment by mullermp** [comment]
Soft update, this appears to have been fixed but not deployed yet.

**Comment by mullermp** [comment]
This has been released today:

https://github.com/aws/aws-sdk-ruby/blob/d170c2c2a4885c0206ac74b7c0853c0006052a37/apis/s3/2006-03-01/docs-2.json#L45
