### ISSUE TITLE
How we can record a reference to the HTTP request and response

### ISSUE THREAD

**Issue by bsingh-taksatech** [aws/aws-sdk-ruby#2255]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**

**Comment by alextwoods** [comment]
The http_request and http_response are available on the context of response objects returned by clients for every operation.  Eg: 

```ruby
client = Aws::S3::Client.new
resp = client.list_buckets
puts resp.context.http_request.inspect
puts resp.context.http_response.inspect
```
