### ISSUE TITLE
MessageVerifier authentic? is very slow

### ISSUE THREAD

**Issue by annienero** [aws/aws-sdk-ruby#2258]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Our app has a 15 second timeout for all requests. MessageVerifier's authentic? is sporadically taking longer than 15 seconds and leading to timeout errors.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3 1.60.2

**Version of Ruby, OS environment**
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**To Reproduce (observed behavior)**
Our code:
```
  private def verify_aws_signature
    verifier = Aws::SNS::MessageVerifier.new
    render status: 401, json: {} unless verifier.authentic?(request.body.read)
  end
```

**Expected behavior**
Authentication is reasonably fast.

**Comment by alextwoods** [comment]
Sorry you're running into that.  I haven't been able to reproduce this yet.  

My guess would be that you're getting timeouts when the MessageVerifier tries to get the pem from the SigningCertURL.  What is the SigningCertURL when it times out?  One option may be to reuse the MessageVerifier between requests - it will cache the pems and avoid extra http calls.
