### ISSUE TITLE
Does Presigner#presigned_url` kick off HTTP requests?

### ISSUE THREAD

**Issue by morcoteg** [aws/aws-sdk-ruby#2259]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

In #Presigner#presigned_url, a call to `#sign_but_dont_send` is called, followed by a call to `req.send_request.data`.

```
def presigned_url(method, params = {})
      if params[:key].nil? or params[:key] == ''
         raise ArgumentError, ":key must not be blank"
       end
      virtual_host = !!params.delete(:virtual_host)
      scheme = http_scheme(params, virtual_host)
    
      req = @client.build_request(method, params)
      use_bucket_as_hostname(req) if virtual_host
      sign_but_dont_send(req, expires_in(params), scheme)
      req.send_request.data
  end
```

But in `Presigner#sign_but_dont_send`, it seems like it's overriding the `req` object's request sending capabilities, and making a Response object with the presigned_url as it's data.

```
def sign_but_dont_send(req, expires_in, scheme, time, unsigned_headers)
        http_req = req.context.http_request

        req.handlers.remove(Aws::S3::Plugins::S3Signer::LegacyHandler)
        req.handlers.remove(Aws::S3::Plugins::S3Signer::V4Handler)
        req.handlers.remove(Seahorse::Client::Plugins::ContentLength::Handler)

        signer = build_signer(req.context.config, unsigned_headers)

        req.context[:presigned_url] = true
        req.handle(step: :send) do |context|

          if scheme != http_req.endpoint.scheme
            endpoint = http_req.endpoint.dup
            endpoint.scheme = scheme
            endpoint.port = (scheme == 'http' ? 80 : 443)
            http_req.endpoint = URI.parse(endpoint.to_s)
          end

          # hoist x-amz-* headers to the querystring
          query = http_req.endpoint.query ? http_req.endpoint.query.split('&') : []
          http_req.headers.keys.each do |key|
            if key.match(/^x-amz/i)
              value = Aws::Sigv4::Signer.uri_escape(http_req.headers.delete(key))
              key = Aws::Sigv4::Signer.uri_escape(key)
              query << "#{key}=#{value}"
            end
          end
          http_req.endpoint.query = query.join('&') unless query.empty?

          url = signer.presign_url(
            http_method: http_req.http_method,
            url: http_req.endpoint,
            headers: http_req.headers,
            body_digest: 'UNSIGNED-PAYLOAD',
            expires_in: expires_in,
            time: time
          ).to_s

          Seahorse::Client::Response.new(context: context, data: url)
        end
      end
```

Does this mean that `Presigner#presigned_url` isn't kicking off http calls, and that the calls are almost mocked out in a way, by `#sign_but_dont_send`?

**Comment by alextwoods** [comment]
Correct - `Presigner#presigned_url` does not make any http calls.  The `#sign_but_dont_send` method applies some of the plugin stack to resuse that functionality, but then does not actually send a request.

**Comment by morcoteg** [comment]
@alextwoods Thank you, just wanted to be sure!

**Comment by fschwahn** [comment]
Quick follow-up question on this: when presigning URLs, I see entries in my logs such as:
```
[Aws::S3::Client 0 0.000841 0 retries] get_object(response_content_disposition:"attachment; filename=\"d4770d2c-93bf-4d13-8943-84d4f4ea287c.jpg\"; filename*=UTF-8''d4770d2c-93bf-4d13-8943-84d4f4ea287c.jpg",bucket:"my-bucket",key:"production/d4770d2c-93bf-4d13-8943-84d4f4ea287c.jpg")
```

Am I understanding correctly that this does not mean that a network request is happening, but the "mocked out" version of a request is happening instead (generating the log entry)?

**Comment by mullermp** [comment]
@fschwahn That looks like a request. How are you presigning your urls?

**Comment by fschwahn** [comment]
Something like this:

```ruby
connection = ::Aws::S3::Resource.new(*credentials)
bucket = connection.bucket(aws_bucket)
file = bucket.object(path)
file.presigned_url(:get, expires_in: 1.hour.to_i, response_content_disposition: content_disposition)
```

**Comment by mullermp** [comment]
Ok that looks good - that won't make network calls. I just checked and it looks like one of the request handlers/plugins will print that message.

**Comment by fschwahn** [comment]
Ok, that's good - `0.000841` would have been a hell of a time for a network roundtrip. That said, this actually sent me on a hunt to find where those supposed network requests are happening. Is there any way to suppress those fake request log entries?

**Comment by mullermp** [comment]
Yep just pass logger as nil for any client/resource: `Aws::S3::Resource.new(logger: nil)`
