### ISSUE TITLE
Use of aws-sdk-s3 throws a lot of "assigned but unused variable - resp"

### ISSUE THREAD

**Issue by alanyee** [aws/aws-sdk-ruby#2263]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Using the gem throws a lot of warnings:
```
warning: assigned but unused variable - resp
```
I have examined and found that the warnings are located at https://github.com/aws/aws-sdk-ruby/tree/master/gems/aws-sdk-s3/lib/aws-sdk-s3
```
  resp = @client.put_object(options)
  Object.new(
    bucket_name: @name,
    key: options[:key],
    client: @client
  )
end
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

`aws-sdk-s3` `1.60.2`
`aws-sdk-s3` `master` branch

**Version of Ruby, OS environment**
On WSL,
```
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
``` 
On macOS 10.15.3
```
ruby 2.6.5.p114 (2019-19091 revision 67821) [x86_64-darwin19]
```

**To Reproduce (observed behavior)**
1.  Have `main.rb` with a line `require aws-sdk-s3`
2. Run `ruby -w main.rb`

**Expected behavior**

**Comment by alextwoods** [comment]
Most of these warnings are in the generated code for service APIs.  We have a backlog item to apply rubocop and address warnings in the SDK.

**Comment by diasjorge** [comment]
We're still experiencing this issue. Is there still a plan to address this? An issue to follow up?

**Comment by mullermp** [comment]
@diasjorge What types of warnings do you see? Many of them that I see is in the aws-crt gem.

**Comment by mullermp** [comment]
https://github.com/awslabs/aws-crt-ruby/pull/49 This should address those warnings from requiring aws-sdk-s3.
