### ISSUE TITLE
Aws::CognitoIdentity::Types::Credentials doesn't work with Aws::Sigv4::Signer due to secret_access_key/secret_key attribute name mismatch

### ISSUE THREAD

**Issue by gradybarrett** [aws/aws-sdk-ruby#2267]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When using credentials obtained through the [enhanced (simplified) Cognito AuthFlow](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html), the Elasticsearch client throws the following error:
```
undefined method `secret_access_key' for #<Aws::CognitoIdentity::Types::Credentials:0x00007fc2b28802f8>
Did you mean?  secret_key
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-cognitoidentity (1.18.0)
[elasticsearch](https://github.com/elastic/elasticsearch-ruby) (6.8.1)
[faraday_middleware-aws-sigv4](https://github.com/winebarrel/faraday_middleware-aws-sigv4) (0.3.0)

**Version of Ruby, OS environment**
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

**To Reproduce (observed behavior)**
Here's a fragment from my script showing the major calls:

```ruby
# Get/Create & Get Identity ID for this app in our Identity Pool

cognito_client = Aws::CognitoIdentity::Client.new(
  region: @region
)

app_identity = cognito_client.get_id({
  account_id: sandbox_account_id,
  identity_pool_id: identity_pool_id,
  logins: {
    identity_provider_name => token
  }
})

# Use app Identity ID to assume appropriate role based on scopes

assumed_role_session = cognito_client.get_credentials_for_identity(
  identity_id: app_identity.identity_id,
  logins: {
    identity_provider_name => token
  }
)

# Call ES with assumed role credentials

assumed_role_client = ElasticsearchClient.new(
  credentials_provider: assumed_role_session,
  es_endpoint: @es_endpoint
)

assumed_role_results = assumed_role_client.cluster_health
```
And here's the instantiation of the Elasticsearch::Client:

```ruby
def initialize(**options)
    es_endpoint = options.fetch(:es_endpoint) { "https://vpc-workbench-es-sandbox-binwrzkohx6nuhcyetss4jdofe.us-east-1.es.amazonaws.com" }
    service = options.fetch(:service) { "es" }
    region = options.fetch(:region) { "us-east-1" }
    
    credentials_provider = options[:credentials_provider]

    @client = Elasticsearch::Client.new(url: es_endpoint) { |f|
      f.request :aws_sigv4,
        service: service,
        region: region,
        credentials_provider: credentials_provider

      f.adapter Faraday.default_adapter
    }
  end
```

I can extract a relevant example script and put it in a separate repo if needed.

**Expected behavior**
I expected the [Aws::Sigv4::Signer](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#initialize-instance_method) to be able to consume either the `Aws::CognitoIdentity::Types::GetCredentialsForIdentityResponse` object directly as a `:credentials_provider`, or the `Aws::CognitoIdentity::Types::GetCredentialsForIdentityResponse.credentials` object as a `:credentials` object. Both, however, result in the above error.

**Additional context**
This error occurs because the response [Aws::CognitoIdentity::Types::Credentials](https://github.com/aws/aws-sdk-ruby/blob/949907d33b40022d1e1f36d30b424a85ed26b717/gems/aws-sdk-cognitoidentity/lib/aws-sdk-cognitoidentity/types.rb#L183) cognito credentials object exposes the secret access key through an attribute called `secret_key`, rather than `secret_access_key`. The standard for this attribute elsewhere in the SDK (e.g. the top-level [Aws::Credentials](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Credentials.html) object) seems to be `secret_access_key`, which the [Aws::Sigv4::Signer](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#initialize-instance_method) consumes without issue.

I'm not sure if this is an interface inconsistency or if I'm misusing these objects.

**Comment by alextwoods** [comment]
I believe you will need to use AssumeRoleWebIdentityCredentials rather than directly using the Cognito Credentials, see: [STS Client#assume_role_with_web_identity](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/STS/Client.html#assume_role_with_web_identity-instance_method).  However I haven't been able to find or test a complete example that matches your case - I'll keep looking though.

**Comment by gradybarrett** [comment]
Hey @alextwoods!

I guess I should clarify that I can get a set of credentials successfully using the above enhanced authflow. I use those creds, later on, to successfully call Elasticsearch. Unfortunately, I have to pick the individual credential properties out of the Cognito response object, then pass them in as static credentials when constructing the Elasticsearch::Client to avoid this attribute naming mismatch.

The STS Client#assume_role_with_web_identity requires a role to be passed in, which doesn't quite fit my use-case. I'm federating AuthN through an OpenID IAM provider (Auth0), then relying on Cognito to do AuthZ via role mapping based on `scope` claim values in my OAuth token. Took me a while to figure it out but it works pretty slick.

I can pull all this out into a repo if it would help with the big picture.

**Comment by alextwoods** [comment]
Okay - I believe I understand the use case now (this looks like the newer cognito [enhanced flow](https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-authentication-part-4-enhanced-flow/) - which essentially ends up calling AssumeRoleWithWebIdentity on your behalf (server-side).   

Does the response you get back for credentials have an expiration time? I believe the correct thing for us to to would be to add a new refreshing credentials provider similar to what is done currently in the javascript SDK: [CognitoIdentityCredentials](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/cognito_identity_credentials.js)

**Comment by gradybarrett** [comment]
Indeed!


The credentials object has an expiration time property, as expected. Here's a sample response:
```
#<struct Aws::CognitoIdentity::Types::GetCredentialsForIdentityResponse
  identity_id="us-east-1:8cde3b1e-7bbf-467d-b24d-02e467d3e497",
  credentials=
    #<struct Aws::CognitoIdentity::Types::Credentials
     access_key_id="mystical_access_key_id",
     secret_key="super_secret_access_key",
     session_token="lengthy_session_token",
     expiration=2020-03-20 21:14:15 -0700>>
```

Having that facade would be fantastic.

The original problem, however, still remains. If someone chooses not to use that abstraction, then the credentials object isn't usable by other SDK services in its current form. Was that intentional?

**Comment by gradybarrett** [comment]
I'm a bit confused about auth token management in this abstraction. The documentation for CognitoIdentityCredentials clearly indicates that it does not own refreshing the auth token.

In a normal ruby client, I usually implement an authentication middleware that's responsible for this, where I can cache the token using it's expiration time, and refresh the token when needed before a request is made. But in this case, I own the responsibility of refreshing the token, but I don't own, and can't extend, the client. If I can't hook into the client, then there's no way for me to elegantly trigger a token refresh when needed, and provide that token to the credentials provider. I have to let a request with an expired token fail, and use that exception as control flow to refresh my token, which is not an ideal experience. Is there an intended pattern here that's eluding me?

**Comment by alextwoods** [comment]
Thanks for filing this - there is definitely a gap in the abstractions that the SDK is providing for credentials here.  I'm working on adding support for a credential provider that will handle the refreshing of the cognito credentials.  You'd still need to manage refreshing the auth tokens in the application, but this would at least abstract the cognito / AWS credentials management.

**Comment by gradybarrett** [comment]
Fantastic! Thanks Alex.

Would it be possible to include some sort of hook or allow a refreshing function to be injected as part of this abstraction? That would still put the onus of token management on the application, but allow us to do it more efficiently and elegantly.

**Comment by alextwoods** [comment]
What are you thinking for this refreshing function - that it would be called when the credential provider detects the aws credentials are close to expiration and the callback/hook function would then potentially run custom logic to refresh the auth tokens before a new call to get_credentials_for_identity is made?

**Comment by gradybarrett** [comment]
Yep, that's exactly what I was thinking. Done with simple dependency inversion via

1. A block
2. A token refresh class argument that responds to an expected message(s)
3. A proc/function that executes token refresh logic - basically #2 but just a first-class function.

Something like #2 would allow you to offload both checking the token for expiration and refreshing the token to the app.

```ruby
class MyAppsTokenClient
  def get_token
    ...
  end

  def token_expired?
    ...
  end
end
```

**Comment by alextwoods** [comment]
Heres an in progress PR that implements this: https://github.com/aws/aws-sdk-ruby/pull/2274  would love your feedback on it.
