### ISSUE TITLE
CloudWatchLogs#get_log_events Pagination Loops Forever (again) 

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2268]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution **I found #712 which claims this was fixed**
  
**Describe the bug**
When using Aws::CloudWatchLogs::Client#get_log_events with a single page of events, the pagination loops forever.

**Gem name aws-sdk-core, aws-sdk-cloudwatchlogs

**Version of Ruby, OS environment**
ruby-2.4.7p357

**To Reproduce (observed behavior)**
I created a CloudWatch Log Group called "test" with a single stream and a single event.

```
(byebug) resp = cwl_client.get_log_events(log_group_name: 'test, log_stream_name, 'test-stream', start_from_head: true)
(byebug) resp.next_forward_token
"f/35335487330260094046892927327964396928099501836697927680"
(byebug) resp.next_backward_token
"b/35335487330260094046892927327964396928099501836697927680"
(byebug) resp.next_page?
true
(byebug) resp2 = resp.next_page
#<struct Aws::CloudWatchLogs::Types::GetLogEventsResponse events=[], next_forward_token="f/35335487330260094046892927327964396928099501836697927680", next_backward_token="b/35335487330260094046892927327964396928099501836697927680">
(byebug) resp2.next_forward_token
"f/35335487330260094046892927327964396928099501836697927680"
(byebug) resp2.next_backward_token
"b/35335487330260094046892927327964396928099501836697927680"
```

To break out of this loop, I have to explicitly check if events is empty, just like the original reporter.

**Expected behavior**
`next_page?` should be false and it `next_page` should not return.

**Comment by ajredniwja** [comment]
Hey @phene thank-you for reaching out.

I was not able to reproduce this behavior. I used my existing log group and stream, which had 3 events, I used the code snippet provided in last similar issue

My results:
```
Page returned with 3 items.
back b/34961384980054252980325631130896839774254985614076477440 forward f/34961384999032187144275191425394692792061608353468973057
Last false
Next true
Page returned with 0 items.
back b/34961384999032187144275191425394692792061608353468973057 forward f/34961384999032187144275191425394692792061608353468973057
Last true
Next false
```

When ```resp``` has items or few items it doesn't consider it as a last page. So it returns ``` next_page?``` false for the second page.

**Comment by alextwoods** [comment]
I believe this working as expected - but its also very confusing and we may want to update documentation to clarify.   Between the first and second calls in your example, another event could be put into the log stream.  The next_page should then return that result.   Eg:

```ruby
resp = client.get_log_events(log_group_name: 'test', log_stream_name: 'test-stream', start_from_head: true)
resp.next_page?  # true
resp2 = resp.next_page  #gives an empty list. 
resp2.next_page? # false - as expected for this empty response, you will get false for the next page  

# send another log event
client.put_log_events(log_group_name: 'test', log_stream_name: 'test-stream', log_events: [ {timestamp: Time.now.utc.to_i * 1000, message: "TestMessage"} ], sequence_token: '49600251559534280322569874806152141827298157471935474690')

# now check the next_page from the orig response
resp2a = resp.next_page # contains the "TestMessage"
resp2a.next_page?  # true
resp2a.next_page.next_page? # false
```

**Comment by phene** [comment]
Thanks for the clarification! I tested it again and my results were consistent with yours, @alextwoods. A documentation update would be helpful.

**Comment by alextwoods** [comment]
I've updated documentation for the SDK to help clarify this.
