### ISSUE TITLE
setting of content-disposition in service_url params

### ISSUE THREAD

**Issue by Tenzin10** [aws/aws-sdk-ruby#2273]
Four days ago when I do .service_url in my project it generates a link, I could append `?response-content-disposition=attachment` like `s3link?response-content-disposition=attachment` and it would force download the file, now it's giving this error "Request specific response headers cannot be used for anonymous GET requests."

It would be greater if we could do something like .service_url(disposition: : attachment), 
Although this method is already there and it accepts the parameter as above, the file is always shown in the new tab. I even overrode the active storage engine and added all the files to be downloaded instead of showing in new tab.

**Comment by bonniesimon** [comment]
Why did you close this issue? I tried setting the content_disposition and it is not working for me

**Comment by mullermp** [comment]
Hello. I'm not sure why this was closed. I see your discussion on #2964. I think this was a feature request to make it easier to add content disposition, but it should already be possible by passing the option into the presigned url and request methods.
