### ISSUE TITLE
Is ap-northeast-3 region supported?

### ISSUE THREAD

**Issue by nbekirov** [aws/aws-sdk-ruby#2280]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
I'm using the following code to populate a drop-down menu with regions my customers can configure:
```ruby
Aws.partition('aws').service('S3').regions.to_a.sort
# => ["ap-east-1", "ap-northeast-1", "ap-northeast-2", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-north-1", "eu-west-1", "eu-west-2", "eu-west-3", "me-south-1", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
```

The list is missing `ap-northeast-3` which is described as a valid albeit special region in the [docs](https://docs.aws.amazon.com/general/latest/gr/s3.html):
> ****You can use the Asia Pacific (Osaka-Local) Region only in conjunction with the Asia Pacific (Tokyo) Region. To request access to the Asia Pacific (Osaka-Local) Region, contact your sales representative.

- I'm not sure what this "only in conjunction with the Asia Pacific (Tokyo) Region" should mean.
- I'm not able to contact a sales representative. It's up to my company's customers to contact sales and then just enter credentials and settings in our product.

So my questions are:
- Is `ap-northeast-3` supported?
- Is it possible for me to just append `ap-northeast-3` to the list the gem is returning to me, populate the drop-down, and assume it'll all work?
- Is there some developer access program (credentials) I can use to test such integration?

**Comment by mullermp** [comment]
As far as I understand, `ap-northeast-3` is intentionally excluded from the SDKs and requires special access to use. See this page too: https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/. I would not include it in your drop-down unless you request special access for it. According to some blog posts it looks like it may be opened up in the future? https://aws.amazon.com/about-aws/whats-new/2020/01/aws-to-launch-standard-aws-region-in-osaka-in-early-2021/

**Comment by nbekirov** [comment]
Thank you!

I guess until 2021 I won't try to make it work and push it in customers' hands. Maybe try to make it work in some ad-hoc manner if the need arises.
