### ISSUE TITLE
Provide better diagnostics when empty credentials are provided

### ISSUE THREAD

**Issue by p-mongo** [aws/aws-sdk-ruby#2281]
**Is your feature request related to a problem? Please describe.**

If a Client is created with empty credentials and subsequently used for an operation, the error produced is: `The security token included in the request is invalid. (Aws::STS::Errors::InvalidClientTokenId)`.

For example:

<pre>
credentials = Aws::Credentials.new('', '')
client = Aws::STS::Client.new(credentials: credentials, region: 'us-east-2')
p client.get_caller_identity
</pre>

The error message produced does not indicate the problem (empty credentials). It is actually misleading because it implies that some piece of information was supplied ("security token", which is not a terribly well defined term either) and was incorrect, but the user in this case did *not* provide any information.

To provide helpful diagnostics to users of my applications, I need to check that credentials are not empty.

**Describe the solution you'd like**

I would like the various AWS SDK clients to check whether the credentials are empty, and produce an error with a message stating so. If credentials are not changeable on an existing client, I would like this diagnostics to happen upon client instantiation, otherwise whenever a signature is calculated.

**Describe alternatives you've considered**

A client application can perform this validation. But this means every client application needs to perform it whenever user credentials are obtained, or whenever any Client is constructed.

[ ] :wave: I may be able to implement this feature request

**Additional context**

Reproduce code: https://github.com/p-mongo/tests/tree/master/aws-empty-credentials

**Comment by mullermp** [comment]
Thanks for the feature request. In general, the SDK prefers validation as late as possible (such as during signature signing). There are also many edge cases here for customers using other credential providers such as `AssumeRoleCredentials` and `InstanceProfileCredentials` where some service is being called before a `Credentials` object is created. I think also this might be a breaking change for users to raise errors earlier than they have expected? We will definitely consider this one, and I'm happy to look at any pull requests.

**Comment by p-mongo** [comment]
Between the contents of the message and when it is produced, to me the contents is much more important, i.e. having the signer fail with an error like "Credentials were not provided". I understand that later diagnostics can be desirable in various situations.
