### ISSUE TITLE
[aws-sdk-v1] The endpoints.json does not contain cn-northwest-1 related information, resulting in no way to create resources in cn-northwest-1

### ISSUE THREAD

**Issue by omg2hei** [aws/aws-sdk-ruby#2286]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The endpoints.json does not contain cn-northwest-1 related information, resulting in no way to create resources in cn-northwest-1.
You can refer to the content in this pr. [Add cn-northwest-1 endpoint. #2285](https://github.com/aws/aws-sdk-ruby/pull/2285)

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
```
aws-sdk-v1-1.67.0
```

**Version of Ruby, OS environment**
```
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
```

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```
require 'aws-sdk-v1'

AWS.config(access_key_id: 'AK...', secret_access_key: 'SK...', region: 'cn-northwest-1')
ec2 = AWS.ec2
ec2.client

volume = ec2.volumes.create(:size => 13,
                            :availability_zone => "cn-northwest-1b")
```

**Expected behavior**
There is no output, and an EBS volume is created in cn-northwest-1b.

**Screenshots**
```
Traceback (most recent call last):
        4: from hello.rb:7:in `<main>'
        3: from /var/lib/gems/2.5.0/gems/aws-sdk-v1-1.67.0/lib/aws/ec2/volume_collection.rb:89:in `create'
        2: from (eval):3:in `create_volume'
        1: from /var/lib/gems/2.5.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:476:in `client_request'
/var/lib/gems/2.5.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/client.rb:375:in `return_or_raise': The zone 'cn-northwest-1b' does not exist. (AWS::EC2::Errors::   InvalidZone::NotFound)
```

**Additional context**
- The current mitigation method is to supplement the endpoint information related to cn-northwest-1 in endpoints.json.
- Or use a higher version of the SDK (I did not test it.)
- I submitted a pr to alleviate this problem.[Add cn-northwest-1 endpoint. #2285](https://github.com/aws/aws-sdk-ruby/pull/2285)

**Comment by mullermp** [comment]
See: https://github.com/aws/aws-sdk-ruby/pull/2285#issuecomment-611613836
