### ISSUE TITLE
Make Aws::CredentialProviderChain part of the public API

### ISSUE THREAD

**Issue by Startouf** [aws/aws-sdk-ruby#2287]
**Is your feature request related to a problem? Please describe.**
On several occasions I've stumbled across the difficulty to retrieve credentials for use with libraries other than the Aws sdk. For example, initialising the Faraday middleware for Elasticsearch with Aws signature, which requires credentials to be provided. 

**Describe the solution you'd like**
It would be useful to have `Aws::CredentialProviderChain` (or some wrapper), as part of the public API (`CredentialProviderChain` is currently tagged as `@api private`) and include some example in the README so we can use it in our code in a more "official" way like

```ruby
# Example of configuring Elasticsearch with Faraday+sigv4 on AWS
Elasticsearch::Client.new(...) do |faraday|
  faraday.request(:aws_sigv4,
    service: 'es',
    credentials_provider: Aws::CredentialProviderChain.new.resolve,
    region: ENV['AWS_REGION'],
  )
end
```

**Describe alternatives you've considered**

- [ ] `credentials_provider = [Some Specific credentials] ; if !credentials.set? then [try other credentials]...`

**Comment by ajredniwja** [comment]
Hey @Startouf thank-you for reaching out, I am a little confused about the request, since you can already use it, is it about just making it public and documenting it? Using it in my code provides credentials using the SharedCredentials method. 
Am I missing anything?

**Comment by Startouf** [comment]
Sorry for the late reply, yes this is mostly because when I see `@api private` it means I'm not supposed to use this code in a production environment as this has no guarantee to stay in the next version, without even deprecation warnings right ? 

`Aws::CredentialProviderChain.new.resolve` has the advantage to provide flexibility of use, as it will for example automatically pick InstanceProfile credentials when running in a prod environment, and if you're working in development locally it will switch to other storage types

(as explained [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html)

**Comment by mullermp** [comment]
Which faraday library are you using? If it is using the latest SDK version, I don't see why it couldn't create an ElasticSearch client without credentials provided (which would then use the provider chain).

**Comment by Startouf** [comment]
I am using 

gem 'faraday_middleware-aws-sigv4'
gem 'elasticsearch-model', '~> 7'
gem 'elasticsearch-transport', '~> 7'
gem 'elasticsearch-rails', '~> 7'

In my Gemfile.lock they resolved `faraday-0.12.2`

For references
- https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations
- https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-ruby

**Comment by ajredniwja** [comment]
@Startouf can you share your code on how you are providing the credentials right now and what error message do you see if you don't pass access_key and secret_access_key to the client.
Ideally it should pick up the next available credential option, that is why the docs suggest to set the env vars if the credentials don't work. 

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-ruby

**Comment by charleseff** [comment]
@Startouf I'm dealing with the same conundrum. I see that the interface still hasn't changed in 2025 (almost 5 years from this ticket's opening). Did you end up just using `Aws::CredentialProviderChain` anyway?

**Comment by mullermp** [comment]
Can you be specific about your use case? You can create an elastic search client and retrieve the credentials with `client.config.credentials` which will be the resolved credentials from the chain.

**Comment by charleseff** [comment]
@mullermp i actually realized that myself just after commenting ( using a different service but same idea). Thank you

**Comment by justincy** [comment]
I'd also like for CredentialProviderChain to be public. We want to use the chain so that local dev and release environments can use different authentication methods. We want to customize the chain because it defaults to `retries: 0` for the InstanceProfileCredentials provider and in our experience this is problematic; we get occasional auth errors and a setting of `retries: 1` solves the problem (`retries: 1` is the default when using the class directly).

**Comment by mullermp** [comment]
You can configure your credentials differently per environment (if you are using rails, you can use rails.env). There is also a config option for instance profile retries when it is resolved: https://github.com/aws/aws-sdk-ruby/blob/version-3/gems%2Faws-sdk-core%2Flib%2Faws-sdk-core%2Fplugins%2Fcredentials_configuration.rb#L84
