### ISSUE TITLE
GetIceServerConfig call for Kinesis Video Signalling Channels is unsupported

### ISSUE THREAD

**Issue by jellybob** [aws/aws-sdk-ruby#2293]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The `GetIceServerConfig` API in Kinesis Video Signalling Channels requires an `EndpointUrl` argument to successfully return a list of ICE candidates, otherwise an `Aws::KinesisVideoSignalingChannels::Errors::Forbidden` is raised.

This argument is not supported by the Ruby SDK, and so it is impossible to get a list of ICE candidates to pass to the client.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

`aws-sdk-core`: 3.94.0
`aws-sdk-kinesisvideosignallingchannels`: 1.1.0

**Version of Ruby, OS environment**

`ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```
channel_arn = ENV.fetch("CHANNEL_ARN")
kvs_client = Aws::KinesisVideo::Client.new
rtc_client = Aws::KinesisVideoSignalingChannels::Client.new

endpoints = kvs_client.get_signaling_channel_endpoint(
  channel_arn: channel_arn,
  single_master_channel_endpoint_configuration: {
    protocols: %w[HTTPS],
    role: "VIEWER",
  },
)

ice_servers = rtc_client.get_ice_server_config(
  channel_arn: channel_arn,
  endpoint_url: endpoints.resource_endpoint_list[0].resource_endpoint,
)

puts ice_servers.to_json
```

Results in:

`ArgumentError - unexpected value at params[:endpoint_url]`

**Expected behavior**

```
{
    "IceServerList": [
        {
            "Uris": [
                "turn:3.249.251.19:443"
            ],
            "Username": "# REDACTED #",
            "Password": "# REDACTED #",
            "Ttl": 300
        },
        {
            "Uris": [
                "turn:54.154.3.214:443"
            ],
            "Username": "# REDACTED #",
            "Password": "# REDACTED #",
            "Ttl": 300
        }
    ]
}
```

**Additional context**

Discovery of the undocumented EndpointUrl argument was via AWS support case 6970985921.

**Comment by ajredniwja** [comment]
Hi @jellybob, thank-you for reaching out to us with your issue, the model of the APIs are designed by the service team, so to add an additional param which is undocumented would have to come from the service team and change in their model.

I am going to open a ticket with the service team and reach out to the respective support case team as well to work together with them to know more about the issue and request the suitable steps from the service team.

**Comment by jellybob** [comment]
Thanks, are you able to point me in the right direction to hack this together in a fork while that happens? I don't intend to try and get it merged, but this is blocking work on a project at the moment so it would be great if I could get a workaround in place until the actual solution is reached.

**Comment by mullermp** [comment]
When constructing the client, you can use  `validate_params: false` to get around option validation. I don't recommend this in general but if the operation is not allowing you to pass `endpoint_url` in any way then it could be a work around for now.

**Comment by ajredniwja** [comment]
Hey @jellybob 

The GetIceServerConfig API doesn't take endpoint URL as its parameters: [docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/KinesisVideoSignalingChannels/Client.html#get_ice_server_config-instance_method)

Can you try  to set the endpoint url on the rtc_client instead: [docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html#aws-ruby-sdk-setting-non-standard-endpoint)

Also see the constructor of the KinesisVideoSignalingChannels client: [docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/KinesisVideoSignalingChannels/Client.html#initialize-instance_method)

Something like:

`rtc_client = Aws::KinesisVideoSignalingChannels::Client.new(endpoint: endpoints.resource_endpoint_list[0].resource_endpoint)`
