### ISSUE TITLE
Aws::CodeBuild::Client does not implement response paging

### ISSUE THREAD

**Issue by jcarlson** [aws/aws-sdk-ruby#2296]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
CodeBuild operations do not implement `Aws::Pager` and therefore responses with greater than 100 results are not enumerable. This conflicts with [API documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/paging-responses.html).

**Gem name and its version**
Since at least aws-sdk-codebuild (1.30.0), probably all versions

**Version of Ruby, OS environment**
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

**To Reproduce (observed behavior)**
```rb
require 'test_helper'

class CodeBuildTest < ActiveSupport::TestCase
  setup do
    @client = Aws::CodeBuild::Client.new profile: 'awsAccountWith231CodeBuildProjects'
  end

  test 'has_pages' do
    response = @client.list_projects
    assert_not_nil response.next_token
    assert response.next_page? # FAIL
  end
end
```

**Expected behavior**
Multiple pages of results should be enumerable, such as:
```rb
@client.list_projects.each_page do |page|
  page.projects.each { |project| puts project.name }
end
```

**Additional context**
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-codebuild/lib/aws-sdk-codebuild/client_api.rb#L1089-L1096 does not set a `Aws::Pager` instance on the response context, the way [`Aws::SSM::Client`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-ssm/lib/aws-sdk-ssm/client_api.rb#L4907-L4925) does, for example.

**Comment by mullermp** [comment]
Hey there - this is actually a funny coincidence, CodeBuild is planning a new release tomorrow and we had already got the paginators for all of the APIs shipped along with it. Expect to see these soon.

**Comment by mullermp** [comment]
Bam! https://github.com/aws/aws-sdk-ruby/blob/master/apis/codebuild/2016-10-06/paginators-1.json

How about that.
