### ISSUE TITLE
Aws::S3::Client#delete_object deletes the bucket when key is set to empty string

### ISSUE THREAD

**Issue by cabnnt** [aws/aws-sdk-ruby#2304]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution

```
aws-sdk-s3 (1.61.1)
```  

**Describe the bug**
The documentation for `Aws::S3::Client#delete_object` specifies that [`:key` is a required parameter](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#delete_object-instance_method). However, if the `key` is an empty string (`""`) but the `bucket` name is provided, parameter validation passes and the client attempts to delete the bucket.

In my case, this occurred because the key was derived from a response from an external service. The field from which the key was derived happened to be an empty key in the response. Fortunately, the bucket was _not_ empty and an `Aws::S3::Errors::BucketNotEmpty` error was raised. However, a bucket that happened to be empty would have been inadvertently deleted.

**Version of Ruby, OS environment**
```
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
```

**To Reproduce (observed behavior)**
```ruby
client = AWS::S3::Client.new
client.delete_object(bucket: 'my-bucket', key: '')
#=> Aws::S3::Errors::BucketNotEmpty: The bucket you tried to delete is not empty
```

**Expected behavior**
`Aws::S3::Client#delete_object` should not attempt to the delete the bucket when the `key` is set to an empty string (`""`).

The following is what happens if you specify a `bucket` but pass a `key` that is `nil`:
```ruby
client = AWS::S3::Client.new
client.delete_object(bucket: 'my-bucket', key: nil)
#=> ArgumentError: missing required parameter params[:key]
```
Perhaps a similar parameter validation error could be raised when the key is an empty string.

**Additional context**
I realize there's some ambiguity as to what the behavior really _should_ be here based on how one interprets the word "required" in the docs. If nothing else, maybe the documentation could be updated to be clear that this could occur. That said, considering the alternative is accidentally deleting a bucket (even an empty one), I think raising an `ArgumentError` might be more appropriate.

**Comment by ajredniwja** [comment]
Hey @sivagollapalli thank-you for reaching out to us with your issue, I am able to reproduce the behavior and I think it is a genuine bug, if a bucket is empty then passing empty key will delete the bucket which can be problematic in some edge cases.

I checked the same with the JS-SDK which raises an error 
`Expected uri parameter to have length >= 1, but found "" for params.Key`

Found at: 

https://github.com/aws/aws-sdk-js/blob/cb1604ca89a077ffdb86127884292d3b18c8b4df/lib/param_validator.js#L162-L169

I see that you have a PR open, I will discuss it with the team and have some one look at the PR.

**Comment by mullermp** [comment]
S3 uses REST XML. This ends up happening because `DELETE /` against `bucket-name.s3.amazonaws.com` will attempt to delete the bucket. Providing an object will use `DELETE /object`.

**Comment by cabnnt** [comment]
thank you for the quick fix!
