### ISSUE TITLE
Organizations `list_children` operation can return empty `children` array when there are children

### ISSUE THREAD

**Issue by grothja** [aws/aws-sdk-ruby#2313]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Running the `list_children` API operation for Organizations will sometimes return an empty `children` array for `ORGANIZATIONAL_UNIT`, but will include a `next_token` which, when called, will return child OU's.  

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-organizations` (1.40.0)

**Version of Ruby, OS environment**
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**To Reproduce (observed behavior)**

```ruby
require 'aws-sdk-organizations'

client = Aws::Organizations::Client.new(region: 'us-east-1')

client.list_children(
  child_type: 'ORGANIZATIONAL_UNIT',
  parent_id:  'r-xxxx',
).each do |resp|
  puts resp
end
```

Returns the following when run against one of our Master accounts:

```
{:children=>[], :next_token=>"CAIS...=="}
{:children=>[{:id=>"[FILTERED]", :type=>"[FILTERED]"}, ..., :next_token=>nil}
```

**Expected behavior**
I would expect that the first response would not return an empty array if there are children available in the next request.

**Additional context**
This behavior was observed when the code was ran against the Master Org/billing account for an account that is 5 years old, but was not observed when run against a new/recent Master org account.  It was also not observed when the `child_type` was `ACCOUNT`

**Comment by alextwoods** [comment]
Sorry you're running into this - unfortunately, however,  its expected API behavior -  sometimes in order to ensure they are able to respond quickly, service operations will return empty (or with items < max) pages of data with the next_token set.  You are doing the correct thing an using `each` to ensure you get all of the data.

**Comment by grothja** [comment]
Thanks Alex, that makes sense.
