### ISSUE TITLE
Suggestion to bump up dependency version of aws-sdk-core in aws-sdk-ssm gem

### ISSUE THREAD

**Issue by sternik** [aws/aws-sdk-ruby#2327]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

The new version of `aws-sdk-ssm` should have `aws-sdk-core` dependency increase to at least 3.99.0 on RubyGems because you added a new plugin (http_checksum) to CORE.

**Gem name**

```
aws-sdk-ssm 1.81.0
aws-sdk-core 3.97.0
```

**To Reproduce (observed behavior)**

* install `aws-sdk-core` in the old version (<3.99.0)
* install `aws-sdk-ssm`
* after importing `aws-sdk-ssm` error occurs:
```
`require': cannot load such file -- aws-sdk-core/plugins/http_checksum.rb (LoadError)
```

**Expected behavior**

`aws-sdk-ssm` should have `aws-sdk-core` dependency >= 3.99.0

**Comment by anvox** [comment]
I found `aws-sdk-kms` version `1.34.0` has the same issue. Must upgrade core manually. 

```
        1: from /Users/anvo/.rvm/gems/ruby-2.5.3@tp_common/gems/aws-sdk-kms-1.34.0/lib/aws-sdk-kms/client.rb:27:in `require'
LoadError (cannot load such file -- aws-sdk-core/plugins/http_checksum.rb)
```

**Comment by doublecompile** [comment]
The same issue applies to the `aws-sdk-cloudwatchlogs` gem (I'm running 1.32.0), and I'm sure other gems as well.

**Comment by sternik** [comment]
#2329

**Comment by sufyanadam** [comment]
Same issue with `aws-sdk-secretsmanager` gem.

**Comment by mullermp** [comment]
We will yank gems. We have updated the minimum core version. We are very sorry about this.

**Comment by mullermp** [comment]
Currently getting throttled by rubygems, unfortunately we have to yank 223 gems..

**Comment by sufyanadam** [comment]
That is unfortunate. I suspect some people are blocked on deployments if they rely on things like `aws-sdk-secretsmanager`

**Comment by mullermp** [comment]
Merged minimum core change + changelog entries for all gems - https://github.com/aws/aws-sdk-ruby/pull/2329

New release will start at 11 am. Yanking gems is a slow process. I tried automating it and got throttled.

**Comment by alextwoods** [comment]
There are ~30 remaining gems to yank (in progress).  ETA for both removal of old gems and publishing of new gems is around 12pm PT.

**Comment by yshmarov** [comment]
looking forward

**Comment by japhillips87** [comment]
I just got the error `Could not find aws-sdk-kms-1.34.0 in any of the sources` when doing a ruby upgrade on an app. I got the message trying to run `bundle`. It was already pinned in my lockfile. I removed `Gemfile.lock`, ran `gem install aws-skd-core` (thanks @anvox) and the bundle succeeded. Just wanted to post here in case someone else runs into this issue.

**Comment by mullermp** [comment]
All offending service gems have been yanked. They are currently being republished with a new minor version. A new aws-sdk-core version has also been published.

Very sorry about this. Our automation verifies against the latest set of gems. We will correct this to include edge cases with older core gems.

**Comment by yshmarov** [comment]
Fantastic! I see the update `1.34.1` is rolled out and it is working for me. You guys are great!
![image](https://user-images.githubusercontent.com/13472945/84432942-d4af8580-ac2d-11ea-870a-da257afcf6f4.png)

**Comment by mullermp** [comment]
All new gems have been published.
