### ISSUE TITLE
aws-sdk-s3 depends on aws-sdk-kms-1.34.0 that can not be found

### ISSUE THREAD

**Issue by yshmarov** [aws/aws-sdk-ruby#2330]
When pushing to heroku, I get this error
![aws issue](https://user-images.githubusercontent.com/13472945/84423954-9d39dc80-ac1f-11ea-9937-d65b90ab2420.png)
![aws2](https://user-images.githubusercontent.com/13472945/84423970-a32fbd80-ac1f-11ea-899e-01a64befcf6f.png)
The gem depend on sdk-kms v 1.34 that is not released:
![aws3](https://user-images.githubusercontent.com/13472945/84423989-b04cac80-ac1f-11ea-8649-c984e08d6914.png)

**Comment by asad-ali-bhatti** [comment]
getting same error.

**Comment by mullermp** [comment]
KMS 1.34 was yanked. All other gems have been yanked because of a minimum core problem. Update your gemfile/gemfile.lock

**Comment by mullermp** [comment]
Related https://github.com/aws/aws-sdk-ruby/issues/2327

**Comment by mullermp** [comment]
Closing in favor of master ticket
