### ISSUE TITLE
AWS::Sigv4::Signer overwrites 'host' header

### ISSUE THREAD

**Issue by aphillips19** [aws/aws-sdk-ruby#2339]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
`AWS::Sigv4::Signer#sign_request`, when provided a `:headers` hash, overwrites the 'host' header. In my use case, I need to manually set the host in order to invoke a private API Gateway. Sending a request with a different host after creating the signature will invalidate the signature. I don't believe the `:unsigned_headers` option will help me here, because the 'host' header is [one of the ones that must be signed](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sigv4 (~> 1.0)`

**Version of Ruby, OS environment**
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```ruby
require 'aws-sigv4'

signed_request = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'us-east-1',
  access_key_id: '',
  secret_access_key: ''
).sign_request(
  http_method: 'POST',
  url: 'http://wwww.domain.com/path',
  headers: { 'host' => 'host-header-value' },
  body: ''
)

signed_request.headers['host']
# => "wwww.domain.com"
```
**Expected behavior**
Expected the signer to create a signature using use the given 'host' value, if it exists 

**Screenshots**
N/A

**Additional context**
I've solved this locally by monkey-patching the method at the offending line here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L222

```ruby
sigv4_headers['host'] = headers['host'] || host(url)
```

Will post a PR with a patch shortly too, but I wanted to post this issue first to confirm that it is actually a bug and not just a misunderstanding of this method.

**Comment by ajredniwja** [comment]
Hey @aphillips19 thank-you for reaching out to us with your issue, I was able to confirm this behavior and I agree with you that it should not be the case. The `host` header should be overwritten when one is provided. You can post a PR if you'd like to contribute. 

I can ask the team to make the necessary change according to their bandwidth.

**Comment by alextwoods** [comment]
@aphillips19 - Can you expand on the use case for creating a signature with a host that differs from what is computed from the url?  Is this an issue with pulling host off of the passed url or a case where the host used for the signature actually needs to differ from the url?

**Comment by aphillips19** [comment]
>  You can post a PR if you'd like to contribute.

 Done -- #2345 

> Can you expand on the use case for creating a signature with a host that differs from what is computed from the url?

In my case, I need to invoke a private API gateway but due to application constraints cannot enable private DNS. https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html -- see the "Invoking your private API using endpoint-specific public DNS hostnames" section. It looks like there's another way to do it, too.

**Comment by alextwoods** [comment]
That case makes sense.  The PR looks good - once tests are fixed I think we should be good to merge.
