### ISSUE TITLE
Update 1.71.0 has the error uninitialized constant Aws::S3::Plugins::RetryableBlockIO::Forwardable (NameError)

### ISSUE THREAD

**Issue by cheister** [aws/aws-sdk-ruby#2349]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
For version 1.71.0 we're seeing the following error when loading the aws-sdk-s3 gem.

                     ==== stderr ====
                     /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.71.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:10:in `<class:RetryableBlockIO>': uninitialized constant Aws::S3::Plugins::RetryableBlockIO::Forwardable (NameError)
                     	from /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.71.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:9:in `<module:Plugins>'
                     	from /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.71.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:5:in `<module:S3>'
                     	from /usr/local/rvm/gems/ruby-2.6.6/gems/aws-sdk-s3-1.71.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:4:in `<module:Aws>'

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3 1.71.0

**Version of Ruby, OS environment**
2.6.6

**To Reproduce (observed behavior)**
It's failing when `require 'aws-sdk-s3'` is called

**Expected behavior**
No error, this worked fine with 1.70.0

**Comment by mullermp** [comment]
Fixed here - https://github.com/aws/aws-sdk-ruby/pull/2348

Yanked 1.71.0. Republishing as 1.71.1
