### ISSUE TITLE
Aws::Lambda::Errors::HttpTimeoutException Should Be Considered a Retryable Networking Error

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2351]
I have seen instances of `Aws::Lambda::Errors::HttpTimeoutException`, which should be a retryable networking error

It should be added to `Aws::Plugins::Retries::ErrorInspector::NETWORKING_ERRORS`

[x] :wave: I may be able to implement this feature request

**Comment by mullermp** [comment]
Could you tell me more information about this error? What was the status code and what operation raised it?

**Comment by phene** [comment]
It happens very sporadically. This last case was in a `Aws::Lambda::Client#get_function` invocation.

> Aws::Lambda::Errors::HttpTimeoutException "Could not resolve DNS within remaining TTL of 499 ms"

**Comment by mullermp** [comment]
That error is not modeled, it is a dynamic error: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/errors.rb#L317 . My guess is that the status code is a 408? Could you confirm? If that's true, then I would agree that we should modify the list here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb#L45

**Comment by phene** [comment]
It's too sporadic to easily confirm, but I'll see what I can do.

**Comment by mullermp** [comment]
Any update to this @phene ? Are you still getting that error?

**Comment by phene** [comment]
I haven't seen it since. Still worth adding handling of it, though?

**Comment by mullermp** [comment]
I'm still waiting on the Lambda team for when this error happens and what status code. It would be very helpful if you have logging ready for when it happens again. Typically we standardize customizations and enhancements across all SDKs and we recently had one for retry modes (including which errors to retry). I'd like to confirm the case and have all SDKs handle it before I go and add it to our SDK. Other SDKs have different mechanisms for errors, and Ruby is one of the few that creates errors on the fly (like in this case).

**Comment by mullermp** [comment]
Closing for staleness, please reopen if you see this again. I haven't gotten much of a response from Lambda unfortunately :/
