### ISSUE TITLE
aws-sdk-secretsmanager `#list_secrets` errors for `filters` or `sort_order` params

### ISSUE THREAD

**Issue by cameron-gagnon** [aws/aws-sdk-ruby#2355]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Providing `filters` or `sort_order` parameters to a call of `#list_secrets` errors out during validation. According to the [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SecretsManager/Client.html#list_secrets-instance_method), this is allowed and expected, but the call always errors out.

**Gem name and its version**
From `Gemfile.lock`
```
aws-sdk-core (3.99.1)
  aws-eventstream (~> 1, >= 1.0.2
  aws-partitions (~> 1, >= 1.239.0)
  aws-sigv4 (~> 1.1)
  jmespath (~> 1.0)
aws-sdk-secretsmanager (1.37.1)
  aws-sdk-core (~> 3, >= 3.99.0)
 aws-sigv4 (~> 1.1)
```

**Version of Ruby, OS environment**
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin18]

**To Reproduce (observed behavior)**
Input:
```
client.list_secrets({
  filters: [
    {
      key: 'tag-key',
      values: ['foo']
    }
  ]
})
```
Output:
```
ArgumentError: unexpected value at params[:filters]
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/param_validator.rb:33:in `validate!'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/plugins/param_validator.rb:23:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-core-3.99.1/lib/seahorse/client/request.rb:70:in `send_request'
  /Users/cameron.gagnon/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/aws-sdk-secretsmanager-1.37.1/lib/aws-sdk-secretsmanager/client.rb:1707:in `list_secrets
```

Similar issues can be observed with including `sort_order` instead or in addition to the `filters` parameter.

**Expected behavior**
The call to `#list_secrets` does not error out.

**Comment by alextwoods** [comment]
Support for filters in list_secrets was added in 1.40.0 of the `aws-sdk-secretsmanager` gem.  Can you try upgrading?

**Comment by cameron-gagnon** [comment]
doh! Yeah, everything works. My apologies, although I found it hard to find documentation versioning for `aws-sdk-secretsmanager` specifically. I very well could've been looking in the wrong places, but does v1.37.0 documentation exist for `aws-sdk-secretsmanager`

**Comment by alextwoods** [comment]
We unfortunately don't have versioned documentation - if you need  documentation for a specific version you can run yardoc manually on the gem.  Or, if you're looking for changelogs, each service gem has its own changelog, eg the [aws-sdk-secretsmanager's changelog](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-secretsmanager/CHANGELOG.md)
