### ISSUE TITLE
Actually Implement Aws::CloudFront::Resource

### ISSUE THREAD

**Issue by BJClark** [aws/aws-sdk-ruby#2356]
**Is your feature request related to a problem? Please describe.**
Resource objects, according to your docs, are supposed to supply an object oriented interface to a service. For example: https://github.com/aws/aws-sdk-ruby#resource-interfaces

Aws::CloudFront::Resource returns an object with a single method: client.
Client is just the RPC interface. Why even have the Resource object if it's completely unimplimented?

**Describe the solution you'd like**
Implement Aws::CloudFront::Resource. I should be able to do (pseudo code like the docs linked above):
```
distribution = cf.distribution('<distribution-id>)
distribution.enabled = false
distribution.update
```

**Comment by mullermp** [comment]
Resources are hand maintained JSON implementations provided by the service teams. S3 example: https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/resources-1.json

I'm sorry to say that service teams haven't been maintaining or owning these so they've effectively deprecated for quite some time. They also have many limitations on what they can support and are tedious to create and maintain. We don't have plans to implement them. If you'd like to be the hero to implement them, I can help test and publish them upstream for all SDKs to use.
