### ISSUE TITLE
list_policies for AWS managed policies not returning description

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#2362]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
list_policies is not returning a description for the policy. Tried this out with listing AWS managed policies, which all have a description(that can be seen by accessing the AWS console).

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-iam

**Version of Ruby, OS environment**
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin19]

**To Reproduce (observed behavior)**
```
iam = Aws::IAM::Client.new

iam.list_policies({scope: 'AWS'}).each do |response|
  response.policies.each do |d|
    puts d
  end
end
```
```
#<struct Aws::IAM::Types::Policy 
policy_name="AWSDirectConnectReadOnlyAccess", 
policy_id="ANPAI23HZ27SI6FQMGNQ2",
arn="arn:aws:iam::aws:policy/AWSDirectConnectReadOnlyAccess", 
path="/", default_version_id="v4", 
attachment_count=0, 
permissions_boundary_usage_count=0, 
is_attachable=true, 
description=nil, 
create_date=2015-02-06 18:40:08 UTC, update_date=2020-05-18 18:48:22 UTC>
```

```

**Comment by ajredniwja** [comment]
@pchaganti Looks similar to #2360 will tag this as well in the original request to the service team.

**Comment by mullermp** [comment]
See response here https://github.com/aws/aws-sdk-ruby/issues/2360#issuecomment-661318169

Unfortunately I couldn't find an API that returned the description. If you are able to find one, please let me know.
