### ISSUE TITLE
Aws::S3::Client#put_object does not work with Ruby IO stream

### ISSUE THREAD

**Issue by sorendaugaard** [aws/aws-sdk-ruby#2364]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The `Aws::S3::Client#put_object` method documentation states that the body can be provided as a `string` or `IO` object.
 
![image](https://user-images.githubusercontent.com/42188781/87799538-58572600-c81b-11ea-8c82-51e74d8090a1.png)

However if we provide a Ruby IO object the upload fails with the error:
```
gems/aws-sdk-s3-1.74.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:18:in `call': undefined method `size' for #<IO:fd 9> (NoMethodError)
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-s3` version 1.74.0

**Version of Ruby, OS environment**

`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```
require 'aws-sdk-s3'

client = Aws::S3::Client.new(
  region: 'us-east-1',
  # add your own credentials 
)

fd = IO.sysopen('./file.txt')
io = IO.open(fd)

client.put_object(bucket: 'io-testing-bucket', key: 'test-key', body: io)
```
Results in:
```
gems/aws-sdk-s3-1.74.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:18:in `call': undefined method `size' for #<IO:fd 9> (NoMethodError)
```

**Expected behavior**
I would have expected the contents of the IO stream to be uploaded to the S3 object.
 
**Screenshots**
I don't think it applicable, but please reach out if you need any additional information. 

**Additional context**
Please reach out if you need any additional information.

**Comment by alextwoods** [comment]
I was able to reproduce this and am looking into it.  Is this new development or did you only encounter this after upgrading?

**Comment by sorendaugaard** [comment]
This was new development. Unfortunately I do not know if a specific version introduced this problem.

**Comment by alextwoods** [comment]
Thanks - that's useful.  Our code in multiple places relies on the request body responding to `size` (eg [setting](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/plugins/content_length.rb#L15) the `Content-Length` header).  The `Content-Length` header is required unless the request has `Transfer-Encoding` set to 'chunked' (which I believe is only supported for certain operations).  A few months ago we [changed our parameter validation](https://github.com/aws/aws-sdk-ruby/pull/2224) to remove a requirement that the request body respond to `size`.  

This still needs more investigation but I believe: 1) we have never fully supported IO objects (we require IO like objects that respond to: `read`, `rewind` and `size`) and this likely means we need to update our documentation.  and 2) The change that removed that validation needs some additional checks (it should require the object to respond to `size` unless the operation supports input streaming/transfer-encoding chunked).

**Comment by alextwoods** [comment]
I've pushed #2365, which should hopefully help to address some of the confusion here (changes to docs and param validation should be live after release tomorrow).

Ultimately our clients are not able to support generic IO objects for non-streaming (non chunked) requests because we need to be able to determine size and rewind the input (required for signing the body).  There are a few operations (eg [MediaStoreData#put_object](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MediaStoreData/Client.html#put_object-instance_method)) that support streaming input (through Http1.1 Transfer-encoding chunked).  

I've updated documentation to be more specific about what is supported as well as improving our parameter validation to catch unsupported inputs and provide a (hopefully) more useful error.

**Comment by ioquatix** [comment]
FYI, `rewind` is no longer a requirement of Rack 3's `rack.input`. So depending on that may be problematic for you (thinking of the signing mechanism). It would be better NOT to read the input body as part of the request signing. For example, maybe the request body is 100GiB...

**Comment by alextwoods** [comment]
Yeah - this is an unfortunate requirement of the current modeling on S3's `PutObject` operation.  However, for cases with input streams that don't support rewind (and/or may be very large), you can use the [Object#upload_stream](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_stream-instance_method).
