### ISSUE TITLE
Occur `FrozenError` when passed frozen hash to `DynamodbClient.resource.create_table`

### ISSUE THREAD

**Issue by y-yagi** [aws/aws-sdk-ruby#2366]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

When passed frozen hash to `DynamodbClient.resource.create_table`, be raised `FrozenError`.
This happened since aws-sdk-core v3.104.0 and it doesn't happen before v3.103.0.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-core (3.104.0) and aws-sdk-dynamodb (1.51.0).

**Version of Ruby, OS environment**

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**To Reproduce (observed behavior)**

```ruby 
TABLE_DEFINITION = {
  table_name: "test_table",
  key_schema: [
    {
      attribute_name: "activity_id",
      key_type: "HASH"
    }
  ],
  attribute_definitions: [
    {
      attribute_name: "activity_id",
      attribute_type: "S"
    }
  ]
}.freeze

DynamodbClient.resource.create_table(TABLE_DEFINITION)
# => /home/y-yagi/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/aws-sdk-core-3.104.0/lib/seahorse/client/plugins/request_callback.rb:67:in `delete': can't modify frozen Hash (FrozenError)

```

**Expected behavior**

The exception doesn't be raised.

**Additional context**

Maybe releated with #2353.

**Comment by alextwoods** [comment]
I'm looking into a solution for this.  While #2353 did introduce this issue, `params.delete` is a common pattern in a number of other plugins (eg [APIKey Plugin](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/api_key.rb#L27) and the [ResponseTarget Plugin](https://github.com/aws/aws-sdk-ruby/blob/ce9c394951fc12ce9f3ceddc5a9647af546aaf40/gems/aws-sdk-core/lib/seahorse/client/plugins/response_target.rb#L20) ).  

We may want to dup params when building the request to ensure we are not modify user provided values.

**Comment by alextwoods** [comment]
Update on this - #2367 needed to be rolled back as it caused issues in older versions of the s3 gem (presigner) which relied on modification of the provided params.  See: #2368

Unfortunately this means that we cannot fully support frozen params. However, I've added guards around delete for the plugins that did not have them (apikey and responsetarget) which should address your issue - you can still provide frozen parameters as long as they contain only parameters used by the client request and not by plugins.
