### ISSUE TITLE
After upgrade `aws-sdk-core (3.103.0)` -> `aws-sdk-core (3.104.0)` . Got `NoMethodError` with `down` gem.

### ISSUE THREAD

**Issue by kntmrkm** [aws/aws-sdk-ruby#2370]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

After upgrade `aws-sdk-core (3.103.0)` -> `aws-sdk-core (3.104.0)`

In `down` gem. https://github.com/janko/down

```
 NoMethodError: undefined method `bytesize' for #<Array:0x00007fb3407a3b90>
gems/down-5.1.1/lib/down/chunked_io.rb:173:in `readpartial'
```

The objects that caused the error are, depending on the version, as follows.

- ver 3.103.0 -> String like `"\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01......`
- ver 3.10.4.0 -> Array like below

```
["\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00H\x00H\x00\6\x05\x06\a\a\x06
 {"x-amz-id-2"=>"PwDDiyHVoR**/K9Q+jD**/agQo**IY/sua1vh2Ltclbq2DC6oOePhfogv**+v**ZS379QelKu7A=", "x-amz-request-id"=>"1CF9DCB70090093 ....
```

 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

`aws-sdk-core` ver. 3.10.4.0

**Version of Ruby, OS environment**

`ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`

**Comment by kntmrkm** [comment]
Sorry I found solution.

https://github.com/shrinerb/shrine/issues/492

**Comment by alextwoods** [comment]
Hey - sorry you ran into this, but glad you were able to get a fix!  @janko - thanks for the quick fix on that.
