### ISSUE TITLE
InvalidSignatureException -- Request to CodeGuru Profiler seems to be signed incorrectly by SDK

### ISSUE THREAD

**Issue by ivoanjo** [aws/aws-sdk-ruby#2376]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Hello there. I'm from the CodeGuru Profiler team, and was trying out the Ruby SDK with our API and discovered that it incorrectly signs requests when attempting to untag resources. We're pretty sure this is a bug on the Ruby SDK side, as the Java SDK and the CLI behave correctly for the same request.

Thanks for looking into this, and let me know if I can provide any more info!

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-codeguruprofiler` `1.9.0`

**Version of Ruby, OS environment**
`ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]`

**To Reproduce (observed behavior)**
Minimal repro:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'aws-sdk-codeguruprofiler'
  gem 'pry'
end

require 'securerandom'

def main
  puts "CodeGuru Profiler gem version is #{Aws::CodeGuruProfiler::GEM_VERSION}"

  client = Aws::CodeGuruProfiler::Client.new(region: "ap-southeast-2")
  profiling_group_name = "hello-ruby-#{SecureRandom.hex[0..10]}"
  puts "Attempting to create #{profiling_group_name}"

  begin
    profiling_group = client.create_profiling_group(profiling_group_name: profiling_group_name, tags: {"tag1" => "ruby", "hello" => "ruby", "foo" => "ruby"}).profiling_group
    puts "Created profiling group"

    puts "Attempting to untag one tag"
    client.untag_resource(resource_arn: profiling_group.arn, tag_keys: ["tag1"])
    puts "Successfully untagged one tag"

    puts "Attempting to untag more than one tag"
    client.untag_resource(resource_arn: profiling_group.arn, tag_keys: ["hello", "foo"])
    puts "Successfully untagged more than one tag"
  rescue Aws::CodeGuruProfiler::Errors::Forbidden => e
    puts "Ran into exception. Error headers are #{e.context.http_response.headers.inspect}"
    puts e.inspect
  end

  client.delete_profiling_group(profiling_group_name: profiling_group_name)
  puts "Successfully deleted profiling group"
end

main
```

**Expected behavior**
Untagging should work, as it does when using the CLI:

```bash
$ aws codeguruprofiler --region ap-southeast-2 untag-resource --resource-arn "some-profiling-group" --tag-keys hello foo && echo "success"
success
```

**Screenshots**
I get instead:

```
CodeGuru Profiler gem version is 1.9.0
Attempting to create hello-ruby-c84ab4e202c
Created profiling group
Attempting to untag one tag
Successfully untagged one tag
Attempting to untag more than one tag
Ran into exception. Error headers are {"content-type"=>"application/json", "content-length"=>"1663", "connection"=>"keep-alive", "date"=>"Tue, 28 Jul 2020 11:08:13 GMT", "x-amzn-requestid"=>"04fc20e9-cda2-44d1-a322-1952e87d40f2", "access-control-allow-origin"=>"*", "x-amzn-errortype"=>"InvalidSignatureException", "x-amz-apigw-id"=>"QYYMkGbKywMFYxg=", "x-amzn-trace-id"=>"Root=1-5f20071d-3d8801fe67ef673c02f7b31c", "x-cache"=>"Error from cloudfront", "via"=>"1.1 003bc9225f430357abb8eb4b34f6dc20.cloudfront.net (CloudFront)", "x-amz-cf-pop"=>"DUB2-C1", "x-amz-cf-id"=>"T_b9_Zq4-PVqzJftccMwUID_pqPl8o9I1yDeaRSqaXMzH_GsyBZoNw=="}
Aws::CodeGuruProfiler::Errors::Forbidden
Successfully deleted profiling group
```

**Comment by alextwoods** [comment]
Thanks for the great sample code - made reproducing this very easy.

It looks like the issue may be an issue with how the tag_keys parameters are ordered as url query parameters.  

```ruby
# fails
client.untag_resource(resource_arn: profiling_group.arn, tag_keys: ["foo", "hello"])

# tag_keys in alphabetical order - works
client.untag_resource(resource_arn: profiling_group.arn, tag_keys: ["foo", "hello"]) 

# generically:
client.untag_resource(resource_arn: profiling_group.arn, tag_keys: %w[a b c]) # in order - works
client.untag_resource(resource_arn: profiling_group.arn, tag_keys: %w[c b a]) # out of order - fails
```

I'm investigating where this needs to be fixed.

**Comment by mullermp** [comment]
@ivoanjo I can't find in the SigV4 spec where values should be ordered. Is this an issue with the service side?

**Comment by mullermp** [comment]
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

Ahh.. this is a bug then

```
Sort the parameter names by character code point in ascending order. Parameters with duplicate names should be sorted by value. For example, a parameter name that begins with the uppercase letter F precedes a parameter name that begins with a lowercase letter b.
```

**Comment by ivoanjo** [comment]
Ah! Wow that explains why in some other tests I saw that this worked -- I got lucky/unlucky with the ordering. Thank you so much for fixing this! :+1: :+1: :+1:
