### ISSUE TITLE
Aws::CloudWatch::Metric#put_data signals an odd error

### ISSUE THREAD

**Issue by ssugiyama** [aws/aws-sdk-ruby#2378]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Aws::CloudWatch::Metric#put_data signals an odd error.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-cloudwatch

**Version of Ruby, OS environment**
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin19]

**To Reproduce (observed behavior)**
```
irb(main):001:0> metric = Aws::CloudWatch::Metric.new('Custom', 'orb-status-develop')
=> #<Aws::CloudWatch::Metric:0x000055bebceb0c50 @namespace="Custom", @name="orb-status-develop", @data=nil, @client=#<Aws::CloudWatch::Client>, @waiter_block_warned=false>
irb(main):002:0> data = {metric_data: [{ metric_name: 'orb-status-develop', value: 1.0}] }
=> {:metric_data=>[{:metric_name=>"orb-status-develop", :value=>1.0}]}
irb(main):003:0> metric.put_data(data)
Traceback (most recent call last):
        1: from (irb):3
Aws::CloudWatch::Errors::InvalidParameterCombination (At least one of the parameters must be specified.)
```

**Expected behavior**
returns successfully and put the data to cloudwatch metric.

**Screenshots**
none

**Additional context**
none

**Comment by mullermp** [comment]
Hey @ssugiyama, I see you're using the resource interface model. Have you looked at the example in the documentation? 

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudWatch/Metric.html#put_data-instance_method
https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-cloudwatch/lib/aws-sdk-cloudwatch/metric.rb#L599-L623

My guess is that you need to be supplying the required `dimension` properties. There may be other required fields you need to supply.

Alternatively, there's also a way to do this with the client API (recommended over the resource model) https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudWatch/Client.html#put_metric_data-instance_method

**Comment by ssugiyama** [comment]
@mullermp 
 The client API works fine for me! 
I think the resource model has the problem I reported, but the client API meets my demand.
Thank you!

**Comment by ssugiyama** [comment]
P. S.
I had tried to add 'dimensions' in the request data, but the result is the same.
And looking at the examples, my understanding is that no other fields are required.

**Comment by mullermp** [comment]
That's great the Client API works for you. Resource models are hand maintained features and contain bugs/errors/limitations and most services do not maintain them anymore. The client API is always reliable and code generated around the back end service model. Thanks for reporting this.

**Comment by malcolm-pro** [comment]
I hit this error last week and relieved to have found this comment, or I would still be stuck trying to figure out why the official SDK doesn't seem to work. Perhaps the documentation could be clearer in the preference of the Client model over the resource models?

Fwiw, this seems to be the issue; this call to deep_merge is inserting a new metric with `metric_name` set to whatever namespace the Metric object is initialized with, but isn't using the passed-in data, ergo `Aws::CloudWatch::Errors::InvalidParameterCombination: At least one of the parameters must be specified`: https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-cloudwatch/lib/aws-sdk-cloudwatch/metric.rb#L645

**Comment by adibsaad** [comment]
Ran into this as well. Used the client API as per the comments, but if we're not supposed to be using the resource models, is there some documentation or deprecation notice? When I opened up the yard docs (https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudWatch.html) I saw nothing telling me to avoid the resource models.

**Comment by mullermp** [comment]
Resource models are "supported" but they're not maintained very well, because they are modified by hand by the service teams, and also have limitations. The Client API is far more reliable.

**Comment by adibsaad** [comment]
Fair enough, but none of this was made clear in the documentation. Would have been nice to see a warning somewhere.
If it's still supported, albeit loosely, how can I bring this issue to the service team's attention?

**Comment by mullermp** [comment]
The https://github.com/aws/aws-sdk repo has a collection of service team issues, you can reference this issue (and describe your issue) and mention that the resources.json model possibly needs update. I can't guarantee how quickly it would be fixed.
