### ISSUE TITLE
Missing information about Glacier retrieve process

### ISSUE THREAD

**Issue by CliveMillerTR** [aws/aws-sdk-ruby#2379]
In version 009292c of aws-sdk-ruby/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb
Line 836... says:
```
    # If the source object's storage class is GLACIER, you must restore a
    # copy of this object before you can use it as a source object for the
    # copy operation. For more information, see .
```
See... where?

Similarly, from line 4620:
```
    # If the object you are retrieving is stored in the GLACIER or
    # DEEP\_ARCHIVE storage classes, before you can retrieve the object you
    # must first restore a copy using . 
```
Using... what?
I think the documentation would greatly benefit from the missing information being found.

**Comment by mullermp** [comment]
This is related to https://github.com/aws/aws-sdk-ruby/issues/2252. I have actually confirmed with S3 docs team made the fixes and it will be deployed sometime (likely today, too).
