### ISSUE TITLE
Aws Log formatter option filter_sensitive_params redacting information even after passing explicit flag as false

### ISSUE THREAD

**Issue by jatindhankhar** [aws/aws-sdk-ruby#2381]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

#2342  added support to turn off filtering for sensitive paramters. 

Aws Log formatter provides an option to turn off filtering for output by using 

`Aws::Log::Formatter.default(filter_sensitive_params: false)` and passing it into a client object during initialisation. 

However it is still redacting information even if the flag is set to false.

To save the data to json without redacting information, only workaround is to first convert the object to a hash and then to a json.

It is happening with `to_s` and `to_json`, `to_h` works fine. 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

`aws-sdk-core` version 1.103.3

PLATFORMS
  ruby

DEPENDENCIES
  aws-sdk
  dotenv

BUNDLED WITH
   2.1.4

```

**Version of Ruby, OS environment**

**Ruby**

`ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]`


**OS**

```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**To Reproduce (observed behavior)**

I am using STS to fetch S3 bucket acl from multiple AWS accounts. 
Some of the details have been redacted

```ruby

require 'aws-sdk'

module AwsAccountUtils

  DEFAULT_PARTITION_NAME = 'aws'.freeze
  DEFAULT_REGION = 'ap-southeast-1'.freeze
  DEFAULT_ROLE = 'RoleName'.freeze # Redacted

  ACCOUNT_IDS = [XXXXXXXXX].freeze # Redacted

  def self.service_regions(service_name)
    region_data = Aws::Partitions.partition(DEFAULT_PARTITION_NAME).service(service_name)
    region_data.regionalized? ? region_data.regions : [DEFAULT_REGION]
  end

  def self.role_arns(role = nil)
    role ||= DEFAULT_ROLE
    ACCOUNT_IDS.map do |id|
      role_arn(id, role)
    end
  end

  def self.role_arn(account_id, role = nil)
    role ||= DEFAULT_ROLE
    "arn:aws:iam::#{account_id}:role/#{role}"
  end

  def self.assume_role(arn)
    sts_client = Aws::STS::Client.new(region: DEFAULT_REGION)
    Aws::AssumeRoleCredentials.new(client: sts_client, role_arn: arn, role_session_name: SecureRandom.alphanumeric)
  end
end

arn = AwsAccountUtils.role_arn(account_id)

attrs = {
        region: AwsAccountUtils::DEFAULT_REGION,
        credentials: AwsAccountUtils.assume_role(arn),
        log_formatter: Aws::Log::Formatter.default(filter_sensitive_params: false)
    }

s3_client = Aws::S3::Client.new(attrs)

data = s3_client.get_bucket_acl(bucket: 'bucket_name')

puts data.to_s

puts data.to_json

puts data.to_h
```

**Expected behavior**

With the filtering turned off, output should have contained all the fields. 

**Screenshots**

<img width="1440" alt="Screenshot 2020-08-07 at 11 31 20 AM" src="https://user-images.githubusercontent.com/2412081/89615420-342fb780-d8a4-11ea-9d6e-0ee4c1cd4131.png">
<img width="1440" alt="Screenshot 2020-08-07 at 11 33 50 AM" src="https://user-images.githubusercontent.com/2412081/89615433-3abe2f00-d8a4-11ea-966c-3ff8a238d6bb.png">

<img width="1439" alt="Screenshot 2020-08-07 at 11 43 30 AM" src="https://user-images.githubusercontent.com/2412081/89615505-6214fc00-d8a4-11ea-89f5-4bb9dcbc1bd3.png">

**Additional context**

None

**Comment by mullermp** [comment]
I'm not able to reproduce this using a minimal example of the latest aws-sdk-s3 with REPL console.

Strangely, [GetBucketAclOutput](https://github.com/aws/aws-sdk-ruby/blob/d170c2c2a4885c0206ac74b7c0853c0006052a37/gems/aws-sdk-s3/lib/aws-sdk-s3/types.rb#L3781) does not have any sensitive members, and neither does [Grantee](https://github.com/aws/aws-sdk-ruby/blob/d170c2c2a4885c0206ac74b7c0853c0006052a37/gems/aws-sdk-s3/lib/aws-sdk-s3/types.rb#L5286).

This is a silly question, but by chance and by accident, did you set any ACL values on the bucket to literally be [FILTERED]?

**Comment by jatindhankhar** [comment]
Yes, this is indeed strange. It looks like passing `log_formatter` parameter has no effect at all, redaction happens in either case. 

>This is a silly question, but by chance and by accident, did you set any ACL values on the bucket to literally be [FILTERED]?

Haha, no. The values are not "FILTERED". Even there is no `email_address` field in the `grantee` section in the hash ouput but in redaction, it shows up.

**Comment by mullermp** [comment]
> Yes, this is indeed strange. It looks like passing `log_formatter` parameter has no effect at all, redaction happens in either case.

It should work as intended. Here we set `@enabled` if the option is passed: https://github.com/aws/aws-sdk-ruby/blob/dc64350f5fd1a15f1ad04d5729da49036fc0f621/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L23

If using a newer gem, get the sensitive members from the Type, otherwise use the giant list: https://github.com/aws/aws-sdk-ruby/blob/dc64350f5fd1a15f1ad04d5729da49036fc0f621/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L38-L43

Here we check if enabled and check if the key is supposed to be filtered: https://github.com/aws/aws-sdk-ruby/blob/dc64350f5fd1a15f1ad04d5729da49036fc0f621/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L47

`:email_address` is something that is in the giant legacy list: https://github.com/aws/aws-sdk-ruby/blob/dc64350f5fd1a15f1ad04d5729da49036fc0f621/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L19 I have a hunch that you're using the old gem/old code (and thus the parameter is actually not being respected)

Could you try to do a new minimal repro example? Use just the aws-sdk-s3 gem (not aws-sdk) and verify printing the version of core and s3 with `puts Aws::S3::GEM_VERSION` and `puts Aws::CORE_GEM_VERSION`

**Comment by jatindhankhar** [comment]
Yes, as per master branch, latest one is 

https://github.com/aws/aws-sdk-ruby/blob/8288786eb7f3f6130c3f7f1f02d8c723efa8dcd5/gems/aws-sdk-s3/lib/aws-sdk-s3.rb#L71

As per my machine it is 

```ruby
puts Aws::S3::GEM_VERSION
1.75.0
=> nil
```

```ruby
pry(main)> puts Aws::CORE_GEM_VERSION
3.104.3
=> nil
```
<img width="504" alt="Screenshot 2020-08-11 at 9 33 56 AM" src="https://user-images.githubusercontent.com/2412081/89856035-c93cf400-dbb5-11ea-8824-a7372df73534.png">

**Comment by alextwoods** [comment]
Those versions look like they should be giving the new filtering.  I'm still not able to reproduce this locally...  Could you also try: `puts Aws::S3::Types::GetBucketAclOutput::SENSITIVE`

**Comment by jatindhankhar** [comment]
Tried, it gives `nil`

<img width="720" alt="Screenshot 2020-08-12 at 11 47 20 AM" src="https://user-images.githubusercontent.com/2412081/89981493-9700c480-dc91-11ea-880e-4e94680c65be.png">

```ruby
[1] pry(main)> require 'aws-sdk-s3'
=> true
[2] pry(main)> puts Aws::S3::Types::GetBucketAclOutput::SENSITIVE
=> nil
[3] pry(main)>
```

<img width="695" alt="Screenshot 2020-08-12 at 11 48 39 AM" src="https://user-images.githubusercontent.com/2412081/89981617-c7e0f980-dc91-11ea-8262-fb571af556b2.png">

**Comment by alextwoods** [comment]
> Tried, it gives `nil`

This was probably a bad test on my part - its actually an empty array, which `puts` prints as nothing (and returns nil): however the fact that you didn't get `NameError: uninitialized constant Aws::S3::Types::GetBucketAclOutput::SENSITIVE` means that the constant is defined (and empty) which is a good start.  

I had a suspicion that it could be related to the use of STS AssumeRoleCredentials, but that seems to work as well.  The following example works (does not filter parameters) for me:

```ruby
require 'aws-sdk-s3'
puts Aws::S3::GEM_VERSION
puts Aws::CORE_GEM_VERSION
creds = Aws::AssumeRoleCredentials.new(role_arn: role_arn, role_session_name: SecureRandom.alphanumeric)
attrs = {
  region: 'ap-southeast-1',
  credentials: creds,
  log_formatter: Aws::Log::Formatter.default(filter_sensitive_params: false)
}
s3 = Aws::S3::Client.new(credentials: creds)
puts s3.get_bucket_acl(bucket: bucket_name).to_s
```
This prints:
```
1.76.0
3.104.3
{:owner=>{:display_name=>"my_name", :id=>"1234567890abcdef"}, :grants=>[{:grantee=>{:display_name=>"my_name", :email_address=>nil, :id=>"1234567890abcdef", :type=>"CanonicalUser", :uri=>nil}, :permission=>"FULL_CONTROL"}]}
```

Does this match what you're doing?

**Comment by jatindhankhar** [comment]
Yes,
This matches the output. 

However, in the `grantee` section there is no `email_address` or `uri` field, not even nil

*Taken from my earlier comment* 
<img src="https://user-images.githubusercontent.com/2412081/89615433-3abe2f00-d8a4-11ea-966c-3ff8a238d6bb.png">

**Comment by mullermp** [comment]
Are you currently trying to reproduce with the installed gem? Could you try reproducing again after checking out the master branch and running `gems/aws-sdk-resources/bin/aws-v3.rb` from the repo root? Since we can't reproduce, I think something is wrong with your installation perhaps? Maybe a gem reinstall and/or gem pristine?

**Comment by jatindhankhar** [comment]
Let me try this out and update the thread.

**Comment by mullermp** [comment]
Any luck?

**Comment by jatindhankhar** [comment]
Hi, 

Sorry for the delay. 

I tested it on a clean install and surprisingly it is working now, so looks like it was an issue with bundler installation or something.

<img width="1106" alt="Screenshot 2020-08-18 at 11 55 04 AM" src="https://user-images.githubusercontent.com/2412081/90479005-a6798500-e14b-11ea-9113-0b4c229b0cab.png">



<img width="1440" alt="Screenshot 2020-08-18 at 12 03 26 PM" src="https://user-images.githubusercontent.com/2412081/90479016-aa0d0c00-e14b-11ea-8594-97eda5568861.png">


Thank you for your time :)
