### ISSUE TITLE
Aws::S3::Errors::PermanentRedirect on copy_to with specified region

### ISSUE THREAD

**Issue by alex3t** [aws/aws-sdk-ruby#2382]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ V] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [V ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [V ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The `copy_to` does not work for me.
The code:
```ruby
client = Aws::S3::Client.new(
        :region => ENV['AWS_REGION'],
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
      )
s3 = Aws::S3::Resource.new(:client => client)      
bucket = s3.bucket('mybucket')
obj = bucket.object('somefile')
obj.exists? # true
obj.copy_to(obj.key) # error
```
leads to:
```
Aws::S3::Errors::PermanentRedirect (The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.)
```

`ENV['AWS_REGION']` is correct 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk (3.0.1)

**Version of Ruby, OS environment**
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
Docker: ruby:2.7.1-slim-buster

**To Reproduce (observed behavior)**
see code above

**Expected behavior**
Copy without error

**Comment by ajredniwja** [comment]
Hey @alex3t, thank-you for reaching the issue, can you verify the that the region is same where the bucket was created and the region that you are using in your code?

**Comment by alex3t** [comment]
> Hey @alex3t, thank-you for reaching the issue, can you verify the that the region is same where the bucket was created and the region that you are using in your code?

Yes, I'm sure because I able to read the files in the bucket

**Comment by mullermp** [comment]
I'm a little confused on your usage. You're trying to use `copy_to` to copy a file from one bucket to the same bucket with the same key? What is your use case?

Check out the documentation here: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#copy_to-instance_method

**Comment by ajredniwja** [comment]
A little add on to what @mullermp commented, you would need to specify a bucket name as mentioned in the docs. 

I was only able to reproduce this error when both the buckets were in different regions, the once where you got the object from and the once where you are trying to copy to.

There is a open PR for that: https://github.com/aws/aws-sdk-ruby/issues/2014 

To work with something cross region you can use `:copy_from` as mentioned there.

**Comment by alex3t** [comment]
> Thanks for opening an issue. I'm a little confused on your usage. You're trying to use `copy_to` to copy a file from one bucket to the same bucket with the same key? Could you tell me what your use case is?

My use case is update metadata, I just simplified the example, but maybe I was wrong.

@ajredniwja No, I tried to copy to the same bucket but your comment  inspired me to check another syntax of `copy_to` (with `bucket` key).
In short words, this does not work for me:
```
obj.copy_to(obj.key, metadata_directive: "REPLACE", metadata: { 'new_key' => 'ok'}) # error
```
but this works without problems:
```
obj.copy_to(key: obj.key, bucket: obj.bucket_name, metadata_directive: "REPLACE", metadata: { 'new_key' => 'ok'}) 
```

**Comment by mullermp** [comment]
I'm glad you got a working solution. If you're just trying to update the metadata of an object, you can use #put on the Object resource instead of trying to copy the same object onto itself with new metadata.

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#put-instance_method

This should work:
```
s3 = Aws::S3::Resource.new(:client => client)      
object = s3.bucket('mybucket').object('somefile')
object.put(metadata: { 'new_key' => 'ok'})
```
