### ISSUE TITLE
Aws::MedaConvert::Client#create_job creating Invalid JSON

### ISSUE THREAD

**Issue by BJClark** [aws/aws-sdk-ruby#2385]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When calling Aws::MedaConvert::Client#create_job, the ruby code is creating a json key called "Audio selector 1". This causes MediaConvert to be unable to find a valid audio selector which results in an error message of "Invalid selector_sequence_id [0] specified for audio_description [1]."

The key should be called "Audio Selector 1".

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-mediaconvert

**Version of Ruby, OS environment**
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**To Reproduce (observed behavior)**

```
json = %Q({"Settings": {
                    "TimecodeConfig": {
                      "Source": "ZEROBASED"
                    },
                    "OutputGroups": [
                      {
                        "CustomName": "VOD",
                        "Name": "Apple HLS",
                        "Outputs": [
                          {
                            "ContainerSettings": {
                              "M3u8Settings": {
                                "Scte35Source": "NONE"
                              }
                            },
                            "Preset": "System-Avc_16x9_1080p_29_97fps_8500kbps",
                            "NameModifier": "1080p"
                          },
                          {
                            "Preset": "System-Avc_16x9_720p_29_97fps_5000kbps",
                            "NameModifier": "720p"
                          },
                          {
                            "Preset": "System-Avc_4x3_480p_29_97fps_600kbps",
                            "AudioDescriptions": [
                              {
                                "AudioSourceName": "Audio Selector 1"
                              }
                            ],
                            "NameModifier": "480p"
                          }
                        ],
                        "OutputGroupSettings": {
                          "Type": "HLS_GROUP_SETTINGS",
                          "HlsGroupSettings": {
                            "ManifestDurationFormat": "INTEGER",
                            "SegmentLength": 10,
                            "TimedMetadataId3Period": 10,
                            "CaptionLanguageSetting": "OMIT",
                            "Destination": "s3://#{ENV['AWS_S3_ASSET_BUCKET']}/#{output_path}",
                            "TimedMetadataId3Frame": "PRIV",
                            "CodecSpecification": "RFC_4281",
                            "OutputSelection": "MANIFESTS_AND_SEGMENTS",
                            "ProgramDateTimePeriod": 600,
                            "MinSegmentLength": 0,
                            "MinFinalSegmentLength": 0,
                            "DirectoryStructure": "SINGLE_DIRECTORY",
                            "ProgramDateTime": "EXCLUDE",
                            "SegmentControl": "SEGMENTED_FILES",
                            "ManifestCompression": "NONE",
                            "ClientCache": "ENABLED",
                            "StreamInfResolution": "INCLUDE"
                          }
                        }
                      }
                    ],
                    "AdAvailOffset": 0,
                    "Inputs": [
                      {
                        "AudioSelectors": {
                          "Audio Selector 1": {
                            "Offset": 0,
                            "DefaultSelection": "DEFAULT",
                            "ProgramSelection": 1
                          }
                        },
                        "VideoSelector": {
                          "ColorSpace": "FOLLOW",
                          "Rotate": "DEGREE_0",
                          "AlphaBehavior": "DISCARD"
                        },
                        "FilterEnable": "AUTO",
                        "PsiControl": "USE_PSI",
                        "FilterStrength": 0,
                        "DeblockFilter": "DISABLED",
                        "DenoiseFilter": "DISABLED",
                        "TimecodeSource": "ZEROBASED",
                        "FileInput": "s3://#{ENV['AWS_S3_ASSET_BUCKET']}/#{file_path}"
                      }
                    ]
                  }})

      settings = JSON.parse(json).deep_transform_keys do |k|
        k.underscore.gsub("timed_metadata_id3_period", "timed_metadata_id_3_period")
            .gsub("timed_metadata_id3_frame", "timed_metadata_id_3_frame")
            .gsub("m3u8_settings", "m3u_8_settings")
            .gsub("scte35_source", "scte_35_source")
            .to_sym
      end
      settings[:role] = ENV['AWS_MEDIA_CONVERT_ROLE']

      response = media_convert_client(true).create_job(settings)
```

**Expected behavior**
The correct JSON should be generated

**Screenshots**
![Screen Shot on 2020-08-07 at 23-58-56](https://user-images.githubusercontent.com/566/89704602-fd8c8800-d909-11ea-8c17-5c3c625dbef8.png)
![Screen Shot on 2020-08-07 at 23-59-31](https://user-images.githubusercontent.com/566/89704606-1006c180-d90a-11ea-97e4-7b7ecf6ce95c.png)

The 2nd screen shot shows the only diff in two jobs, one that works and one that doesn't work.

**Additional context**
Fwiw, in the sample code is a bunch of gsubs that need to exist because the generated code incorrectly underscore cases json. m3u_8 instead of m3u8? Come on...

**Comment by mullermp** [comment]
Hey, it seems like the approach you are taking may have some unintended consequences. From what I understand, you're taking JSON and attempting to "ruby-ify" it with symboled snake case keys. Unlike most APIs, the [`create_job` API documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MediaConvert/Client.html#create_job-instance_method) seems to expect some keys as strings (and not symbols) as well as be user defined (such as "Audio Selector 1"). So when you're running `deep_transform_keys` it's changing the request to something the service may not understand.

Could you try reproducing this by defining a vanilla Ruby hash without converting from JSON and transforming keys? It should look like this:

```
settings: {
  some_value: {
     foo: 'bar'
  }
  'Audio Selector 1': {
    # stuff...
  }
}
```

**Comment by BJClark** [comment]
Instead of pointing out how developer unfriendly it is to mix symbols and strings I'll just close this and move on.

**Comment by mullermp** [comment]
Feel free to re-open with more information, sorry we couldn't help further. We're also happy to take any pull requests if you feel this is still an issue with the SDK.
