### ISSUE TITLE
Fresh gem install, new key generated, "does not match the signature you provided" after login

### ISSUE THREAD

**Issue by quantumpotato** [aws/aws-sdk-ruby#2386]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution

Searched on https://forums.aws.amazon.com/thread.jspa?messageID=892653&#892653
and SO -- SO Suggestiosn
  
**Describe the bug**
I'm trying to login with the gem. Login fails `Aws::S3::Errors::SignatureDoesNotMatch (The request signature we calculated does not match the signature you provided. Check your key and signing method.):
  `

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

gem 'aws-sdk' - installed today, version 3
ruby 2.6.2p47
OSX 10.14.6

**Version of Ruby, OS environment**
-paste the output of ruby -v

**To Reproduce (observed behavior)**
```
Aws.config[:credentials] = Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
    puts ENV['AWS_ACCESS_KEY_ID']
    puts ENV['AWS_SECRET_ACCESS_KEY']

    # s3 = Aws::S3::Client.new(:access_key_id => ENV['AWS_ACCESS_KEY_ID'],:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'])
    puts Aws.config[:credentials]

    s3 = Aws::S3::Client.new
    resp = s3.list_buckets # ERRORS HERE
    my_buckets = resp.buckets.map(&:name)
    puts my_buckets
```

**Expected behavior**
I expected to get my buckets listed.

**Screenshots**

This is my bucket in S3
<img width="709" alt="Screen Shot 2020-08-09 at 1 23 17 PM" src="https://user-images.githubusercontent.com/433852/89738035-8529e200-da43-11ea-87c5-2a82cfa28827.png"> (Public read access)

**Additional context**
I clicked the username in top right of S3 -> credentials -> made a new key with secret. Those are what I put into my .env

**Comment by alextwoods** [comment]
This is often caused by incorrect credentials - or credentials that are copy/pasted with an extra space.  Are you able to call APIs on other services?

**Comment by quantumpotato** [comment]
@mullermp  no, I can try -- but when I copied these in I went to the iam credentials, made new ones, clicked the clipboard copy button, then pasted into my code, for both fields.
Does  that sample code look correct? I can try setting up a sample project.

**Comment by alextwoods** [comment]
If you're setting credentials in ENV you shouldn't need to set Aws.config[:credentials] or set them when creating a client - they will be automatically used.  A minimal example would be:

```ruby
require 'aws-sdk-s3'
s3 = Aws::S3::Client.new  # Assuming that both ENV['AWS_ACCESS_KEY_ID'] and ENV['AWS_SECRET_ACCESS_KEY'] are set
s3.list_buckets
```
Does this still fail for you?  If it does, can you try striping whitespace with something like:
```ruby
    # s3 = Aws::S3::Client.new(access_key_id: ENV['AWS_ACCESS_KEY_ID'].strip, secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'].strip) #call strip on the keys
s3.list_buckets
```

**Comment by quantumpotato** [comment]
@alextwoods stripping the whitespace fails

**Comment by quantumpotato** [comment]
For anyone reading this in the future - the bucket listed are types and don't have the "put_object" method
use
 s3Resource = Aws::S3::Resource.new

    # reference an existing bucket by name
    bucket = s3Resource.bucket('your-bucket-name') to get access to the put_object method
