### ISSUE TITLE
Elasticache Replication Group ARN appears missing on #describe_replication_groups

### ISSUE THREAD

**Issue by Bensign** [aws/aws-sdk-ruby#2393]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The Elasticache function `describe_replication_groups` states in the [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ElastiCache/Client.html#describe_replication_groups-instance_method) that each node group will have an arn returned. When calling this function, no arn is returned. 

I've run an equivalent function with the aws cli with the command `aws elasticache describe-replication-groups` and an arn is returned so this appears to be a bug with the ruby client. 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk 3.0.1 and aws-sdk-elasticache 1.32.0

**Version of Ruby, OS environment**
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**To Reproduce (observed behavior)**
Ensure you have an Elasticache Replication Group (type:redis) in your AWS account then do the following:

```
ec_client = Aws::ElastiCache::Client.new({
  region: "us-east-1",
  credentials: credentials 
})

# This should be returning an arn string value but it returns nil. 
ec_client.describe_replication_groups.to_h[:replication_groups][0][:arn] => nil
```

**Expected behavior**
Return the ARN of the elasticache replication group as the documentation states.

**Comment by mullermp** [comment]
Hey there, I'm not able to reproduce. I created a new Redis cluster with default settings and called `describe_replication_group` and I see a response with one item in `replication_groups` that has a populated ARN field.

I was able to get it with `elasticache.describe_replication_groups.replication_groups.first.arn`

Since you are using `to_h`, I was able to get it similarly with `elasticache.describe_replication_groups.to_h[:replication_groups][0][:arn]`

Can you check the console to see if the replication group you expect is existing and has an ARN populated?

**Comment by Bensign** [comment]
Confirmed correct region and confirmed presence on the console where I do see the resources and corresponding ARNs. Here is a redacted screenshot to prove the resources are there:

<img width="1662" alt="Screen Shot 2020-08-17 at 12 37 51 PM" src="https://user-images.githubusercontent.com/223348/90433921-9d7cab00-e09a-11ea-855b-8392c4409db3.png">

I should also mention - the credentials I'm using for the ruby client are leveraging a cross account IAM role using the permission of "ReadOnlyAccess" that is managed by AWS. I don't think this should impact anything but I should have included this in the original bug report. I use this gem extensively and don't believe ARNs should be restricted by using this as I get them included in API responses from multiple other APIs no problem...it seems to only be an issue with Elasticache. 

The odd thing is that all other attributes of the replication groups are returned via the client using the describe_replication_groups - but not the ARN and it is always nil.

**Comment by mullermp** [comment]
Interesting.. so for the CLI, when you were able to retrieve the ARN, were you using different credentials than the ones with the Ruby SDK? Try using the same credentials to see if the cross-account permissions have an impact. For Ruby, credentials are loaded with the [credential_provider_chain](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb) if that helps narrow down how your credentials are loaded.

It sounds like ReadOnlyAccess wouldn't prevent an ARN from being returned, but it might be. In my test I was using full administrator access. In any case, this looks to potentially be a service API issue and not a Ruby SDK issue.

**Comment by mullermp** [comment]
I created a new role that used the default ReadOnlyAccess policy and assumed it, but I'm still able to see the ARN.

**Comment by Bensign** [comment]
Very bizarre. I'm trying to think of what can be going awry. I just confirmed I'm using the assumed role on the aws cli and it is properly returning the arn in the terminal output. When I use the same credentials with the ruby client, all attributes are returned but not the arn still. The ARN attribute isn't even present in the hash that the ruby client returns. 

However if its working for you then I really have no idea. I'm going to continue digging. I appreciate the help...I'm flying a bit blind from my end on this. If I determine what's happening, I'll be sure to report back here.

**Comment by mullermp** [comment]
Ah, I'm pretty sure I know what's going on. You should use the latest `aws-sdk-elasticache` gem. I'm willing to bet that if you don't call `to_h` on the response, you won't seen an ARN member, so after converting to a Hash, you're doing a normal key check and Ruby will return nil. Returning the ARN seems to be a newish output member. I installed aws-sdk-elasticache 1.32.0 and I was able to reproduce. Sorry about that! Definitely upgrade and it should solve your problem.

**Comment by mullermp** [comment]
Please reopen if that doesn't work for you.

**Comment by Bensign** [comment]
@mullermp Oh man, that was it - we are all good now. Thank goodness - I was really questioning my sanity there for a bit. Thank you so much for hanging in there with me - this really helped out a lot and unblocks me to get some stuff done!
