### ISSUE TITLE
Request signing fails with AWS SSO profiles

### ISSUE THREAD

**Issue by danleyden** [aws/aws-sdk-ruby#2396]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When running as a real person logged in using AWS SSO service, the credentials are handled by the SSO client and do not include the normal ACCESS_KEY/SECRET_KEY combination. This means that users using SSO are not able to use the ruby SDK because they essentially have no access key or secret in the `~/.aws/config` file and do not use `~/.aws/credentials`.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
Manifests via all clients using `aws-sdk-core`
Tested with `aws-sdk-core 3.104.3`

**Version of Ruby, OS environment**
tested on OSX, 2.7.0, but looking at the code this is will occur on all ruby versions / platforms.

**To Reproduce (observed behavior)**
Given an account configured to use AWS SSO with a third party SSO provider, no AWS environment variables, no ~/.aws/config
1. Set up a local profile using the AWS cli command `aws configure sso` and following the prompts
2. Export the environment variable `AWS_PROFILE` with a value of the profile name just created
3. Use the command `aws sso login` to obtain the temporary credentials required
4. Run a ruby script that uses the V3 SDK to perform some operations that require authentication, creating a client without providing any credentials, e.g. `Aws::DynamoDB::Client.new(profile: ''my-profile).list_tables` 
5. Error raised `NoMethodError: undefined method `credentials' for nil:NilClass from aws-sdk-core-3.104.3/lib/aws-sdk-core/endpoint_cache.rb:112:in 'extract_key'`

**Expected behavior**

1. current profile identified as an `sso` profile (keys in `~/.aws/config` clearly identify this)
2. cached SSO token checked for validity (i.e. not expired)
3. cached SSO details used for authentication
4. token expiry handled

Given that the SSO service is a user-interactive service and the SDK is not (directly) the best option for (4) might be to try re-obtaining cached credentials simply raise an exception reporting "credentials expired"

**Additional context**

This is a substantial issue when testing and developing locally. When code is deployed to production, the credentials provider chain will automatically pull in the credentials needed from the environment / instance profile / etc. so isn't an issue.

I was able to partially resolve this issue with an unpleasant hack. This is not something that could be used "for real" but it may provide  some of a way forward:
```ruby
# load role_name and account_id from ~/.aws/config for profile (sso_role_name, sso_account_id)

sso =  Aws::SSO::Client.new

# cache_file is generated consistently by the CLI... I'm not sure how it is generated, so I looked in my file system
sso_cache = JSON.parse(File.read(File.expand_path("~/.aws/sso/cache/#{cache_file}.json"

creds = sso.get_role_credentials(access_token: sso_cache['accessToken'], role_name: role_name, account_id: account_id).role_credentials

Aws::DynamoDB::Client.new(session_token: creds.session_token, access_key_id: creds.access_key_id, secret_access_key: creds.secret_access_key).list_tables
```

**Comment by alextwoods** [comment]
Good timing - I'm actually actively working on implementing an SSO Credential provider!   I'll consider this a feature request and track progress here.

**Comment by danleyden** [comment]
great, thanks @alextwoods let me know if more info needed. Happy to do some testing etc.

**Comment by alextwoods** [comment]
The `SSOCredentials` provider went out yesterday in aws-sdk-core 3.105.0 with support for loading from profiles through the default credential resolution chain and assume role credentials through the `source_profile `option.  @danleyden - thanks for opening this and for your contribution!
