### ISSUE TITLE
Dualstack for S3 accelerated endpoint

### ISSUE THREAD

**Issue by sandstrom** [aws/aws-sdk-ruby#2404]
This page in your docs state that support for the S3 dualstack endpoint is coming to the SDK.

https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

Just curious if this is planned? Right now it's really easy to end up in a trap where most of your system work on IPv6 but these generated URLs don't.

**Comment by mullermp** [comment]
This is currently supported but the documentation is incorrect.

```
 s3 = Aws::S3::Client.new(use_dualstack_endpoint: true, use_accelerate_endpoint: true)
s3.list_objects(bucket: my_bucket)
```

**Comment by mullermp** [comment]
@ajredniwja can you get in touch with S3 and have them revise that documentation? I think it's dated. Other SDKs should have this implemented. Double check with JS and others.

**Comment by sandstrom** [comment]
@mullermp Thanks!

**Comment by ajredniwja** [comment]
The documentation was altered, closing this issue now.
