### ISSUE TITLE
Circular require

### ISSUE THREAD

**Issue by sj26** [aws/aws-sdk-ruby#2405]
**Describe the bug**
Circular require generates a warning:

```
.../aws-sdk-core-3.105.0/lib/aws-sdk-sso.rb:10: warning: .../aws-sdk-core-3.105.0/lib/aws-sdk-sso.rb:10: warning: loading in progress, circular require considered harmful - .../gems/aws-sdk-core-3.105.0/lib/aws-sdk-core.rb
...
	from .../aws-sdk-s3-1.79.1/lib/aws-sdk-s3.rb:10:in  `<top (required)>'
	from .../aws-sdk-s3-1.79.1/lib/aws-sdk-s3.rb:10:in  `require'
	from .../aws-sdk-kms-1.37.0/lib/aws-sdk-kms.rb:10:in  `<top (required)>'
	from .../aws-sdk-kms-1.37.0/lib/aws-sdk-kms.rb:10:in  `require'
	from .../aws-sdk-core-3.105.0/lib/aws-sdk-core.rb:93:in  `<top (required)>'
	from .../aws-sdk-core-3.105.0/lib/aws-sdk-core.rb:93:in  `require'
	from .../aws-sdk-core-3.105.0/lib/aws-sdk-sso.rb:10:in  `<top (required)>'
	from .../aws-sdk-core-3.105.0/lib/aws-sdk-sso.rb:10:in  `require'
```

aws-sdk-core requires aws-sdk-sso:

https://github.com/aws/aws-sdk-ruby/blob/ec647e8a600a54442777200acf476583abcea4f5/gems/aws-sdk-core/lib/aws-sdk-core.rb#L93

which requires aws-sdk-core:

https://github.com/aws/aws-sdk-ruby/blob/ec647e8a600a54442777200acf476583abcea4f5/gems/aws-sdk-core/lib/aws-sdk-sso.rb#L10

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-core 3.105.0, and on [current master](https://github.com/aws/aws-sdk-ruby/blob/ec647e8a600a54442777200acf476583abcea4f5).

**Version of Ruby, OS environment**
```
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

**To Reproduce (observed behavior)**
```ruby
require "aws-sdk-core"
```

**Comment by mullermp** [comment]
This was by design. Adding @alextwoods but he's on vacation this week.
