### ISSUE TITLE
Use RuboCop more noticably?

### ISSUE THREAD

**Issue by utkarsh2102** [aws/aws-sdk-ruby#2407]
Hey,

Thanks for your work on this! 🚀 

However, I see that whilst there's `.rubocop.yml`, this doesn't really "use" RuboCop actually.
Perhaps, it's nice to use RuboCop (for at least RUBY_VERSION > 2.4) and mention the same in the Gemfile?

If you think it's a good idea, I'll be happy to raise a PR! 😄

**Comment by mullermp** [comment]
Using Rubocop throughout the SDK is a huge task, there are many files to cover. Rubocop 0.50.0 must be used because it's the last version that supports Ruby 1.9 (the oldest version the SDK supports). If you'd be interested in doing that work (warning: it's a big task) then I'd be happy to review. We could start with fixing infractions in code generated clients which would cover most cases, then maybe some exclusions (rubocop TODO) on handwritten code in aws-sdk-core that can be addressed in pieces.

**Comment by alextwoods** [comment]
One option I had considered was adding [pronto-rubocop](https://github.com/prontolabs/pronto-rubocop) as a github action on PR to ensure that new code we're writing passes rubocop.

**Comment by mullermp** [comment]
Pronto looks pretty dated.. wouldn't a native github action work?

**Comment by alextwoods** [comment]
The advantage of pronto is that it lets you run on only the diff rather than the entire project.

**Comment by mullermp** [comment]
There are a few other alternatives here that do the same thing: https://github.com/marketplace?query=rubocop but ultimately rubocop on the entire project would be best I would think. Checking against PRs before we've established usage might be a bad idea - in example what if you are modifying a small bit of code that is part of a larger infraction? - the action would fail but it would be a valid change to carry forward an existing pattern.

**Comment by utkarsh2102** [comment]
Hey,

So I'd agree with @mullermp and think it's best to use `rubocop` on the entire project.

There are 3403 files atm and a lot of offenses. And there are 238 gems inside `gems/`.
I think we can use the newer versions of RuboCop (by using `if RUBY_VERSION > '2.4.0'`).

The best way forward, according to me, is by:
a) Defining a rough `.rubocop.yml` initially to start with.
b) Fix offenses one-by-one in each of the gems (or maybe 2 at a time or whatever).
c) Once all 238 gems are covered, then run `rubocop` project wide and fix the remaining offenses.
d) Finally, run `rubocop` by default on the CI pipeline to catch offenses on PRs.

What do you think? Does this sound good enough?

**Comment by mullermp** [comment]
That sounds like a good path forward. We'd be interested in taking Rubocop defaults where possible and add exceptions on a case by case basis. I would start with code generation of service gems in the build_tools/ directory, then do hand written gems like aws-sdk-core, aws-sigv4, and aws-eventstream.

**Comment by utkarsh2102** [comment]
Great, so I'll make a PR to get things started as set a default configuration.
And then take them one-by-one.

**Comment by mullermp** [comment]
Sure thing. Again, the generated gems are probably the easiest low hanging fruit. I suspect that method/class length and complexity will be offenses that we would probably make exceptions for.

**Comment by mullermp** [comment]
Closing issue. We plan to use Rubocop more strictly for future versions of the SDK.
