### ISSUE TITLE
Update documentation describing CloudWatch `put_metric_alarm` behavior for create vs update operations

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2408]
`Aws::CloudWatch::Client#put_metric_alarm` supports a `tags` field, but it only works when the alarm does not already exist. The tags field is ignored when updating the alarm.

To update tags on an existing alarm, `Aws::CloudWatch::Client#tag_resource` and `Aws::CloudWatch::Client#untag_resource` are required

The documentation should be updated to reflect that `tags` are not updated when the alarm already exists.

**Comment by mullermp** [comment]
I recreated this ticket in a different repo. It's owned by a cross-SDK open source support team that is responsible for driving service API improvements.

**Comment by ajredniwja** [comment]
@phene, changes were made in the documentation.

See: https://github.com/aws/aws-sdk/issues/27#issuecomment-760555988
