### ISSUE TITLE
Incomplete sentence in visibility_timeout documentation

### ISSUE THREAD

**Issue by gardner** [aws/aws-sdk-ruby#2410]
Thanks for providing a ruby SDK. 👍 

The documentation as published [here](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/QueuePoller.html) contains an incomplete sentence. _"By default, the queue's"_

The suspense is nearly unbearable. 😄 

The offending line is here: 
https://github.com/aws/aws-sdk-ruby/blob/df7ab18229ab6aa4ba13558a627898ce7cfc4863/gems/aws-sdk-sqs/lib/aws-sdk-sqs/queue_poller.rb#L293

Kind regards,
  Gardner

**Comment by mullermp** [comment]
Thanks, fixed in https://github.com/aws/aws-sdk-ruby/commit/b586c38461c9aa69c48a4deb7058816abd5460d1
