### ISSUE TITLE
Aws::MedaConvert::Client#create_job creating Invalid JSON (another one)

### ISSUE THREAD

**Issue by rai-hi** [aws/aws-sdk-ruby#2418]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
Very similar to this reported bug:

https://github.com/aws/aws-sdk-ruby/issues/2385

When creating a MediaConvert job in ruby, it's normal to load the job settings from a JSON file. However, there is very little information on what the hash of job settings should look like. Some keys from the job settings are expected to be camel case. Some others are kebab case. 

I initially encountered the issue referenced above. Now, when attempting to add an MP3 output, I got the following:

`unexpected value at params[:settings][:output_groups][1][:outputs][0][:audio_descriptions][0][:codec_settings][:mp3_settings]`

According to this API reference, the key expected is 'mp3Settings'. However, I was only able to make a successful request by converting 'mp3Settings' to 'mp_3_settings'.

There seems to be very little guidance on how to format the job settings keys in Ruby. I believe the SDK should convert all possible keys to the correct format, or have a standardised format. The previous issue poster's technique of symbolizing the keys from JSON works for the majority of keys, but not all, as shown by this and the previous issue.

In the end, in order to ascertain what key the SDK was actually expecting, I had to add logging to `aws-sdk-core-3.109.0/lib/aws-sdk-core/param_validator.rb` and `/aws-sdk-core-3.109.0/lib/seahorse/model/shapes.rb`, and print out `@members.keys` to ascertain that it should be `mp_3_settings`.

There should be a better way of loading job template JSON files for use with the Ruby SDK!

**Comment by mullermp** [comment]
Hi @rai-hi, you can view the information about what the job settings hash should look like by looking at the [`create_job` documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/MediaConvert/Client.html#create_job-instance_method). All of the possible keys are included in the sample request on the documentation page (`mp_3_settings` is there), so you shouldn't need to add any logging to figure out what the keys are called. The API definition is defined as `[Mp3Settings](https://github.com/aws/aws-sdk-ruby/blob/master/apis/mediaconvert/2017-08-29/api-2.json#L6307)`. Our [underscore method](https://github.com/aws/aws-sdk-ruby/blob/master/build_tools/aws-sdk-code-generator/lib/aws-sdk-code-generator/underscore.rb#L14) in our build tools package will correctly convert `Mp3Settings` to `mp_3_settings`, however, the API definition should have defined the field as `MP3Settings`, and doing so would result in the correct `mp3_settings`. Changing this field would be breaking for customers. I realize this is less than ideal and converting to snakecase in Ruby will differ across implementations. If you wanted to load a json file and convert the keys, you could convert them with similar logic to our underscore package.

**Comment by rai-hi** [comment]
Hi @mullermp - that's super helpful, not sure how I missed that info in the method documentation but I appreciate you taking the time to help!

All the best!
