### ISSUE TITLE
Determine the correct global region for a given region/partition

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2420]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

What is the best way to determine the correct "global" region for a given partition, non-global region. For example, in the `aws` partition, I would want to determine that I should use `us-east-1` for some clients, even though my code is running in the `us-west-2` region.  In `aws-gov`, I may need `us-gov-west-1` when running in `us-gov-east-1`. 

There isn't a clear way to do this based on what's currently provided by `Aws::Partitions`. Normally, I'd see something like `aws-global` or `aws-us-gov-global`, but I can't derive a proper region name from those. Any suggestions?

**Comment by mullermp** [comment]
Hey @phene, what is your use case? My understanding is that "aws-global" is a pseudo-region. Historically "us-east-1" was the "global region" for services (S3, STS, etc) prior to being modeled as "aws-global". You can initialize clients using "aws-global" as a region if the service supports it, and if not, fall back to "us-east-1". The data for the partitions gem comes from the service [partitions.json](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-partitions/partitions.json). The global region's credential scope is used as the underlying region (i.e "aws-global" maps to "us-east-1" in most cases).

**Comment by phene** [comment]
OK, I think my confusion came from the fact that `aws-global` and `aws-us-gov-global` are not universally supported region identifiers in all API clients. It appears they work for IAM, Organizations, and Route53, but not for EC2 or CostExplorer, among others. 

I had found the partitions.json, but there's not a simple way to get `us-gov-west-1` from `aws-us-gov-global` without doing some weird things with the `EndpointProvider`

**Comment by mullermp** [comment]
You are correct, not all services model it as a pseudo region. You shouldn't need to get "us-gov-west-1" from "aws-us-gov-global", because using "aws-us-gov-global" as a region will automatically resolve to that region on your behalf.
