### ISSUE TITLE
Method describe_instance_types not found for EC2 Client

### ISSUE THREAD

**Issue by renatomdg** [aws/aws-sdk-ruby#2423]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

SDK Version: 2

Following [that  doc](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/EC2/Client.html#describe_instance_types-instance_method) i got this error:

```yaml
NoMethodError: undefined method `describe_instance_types' for #<Aws::EC2::Client>
Did you mean?  describe_instances
               describe_instance_status
```

In case of this error i literally just copied the doc example
I'd also tried to fulfill the parameters for my context and it got the same error

I'd tried using the same client for other operations like **describe_instances** and it's working.

this option is actually available? 

[]'s

**Comment by ajredniwja** [comment]
Hey @renatomdg thanks for opening the issue, I see you are using the version 2 of the SDK which has been deprecated as mentioned [here](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/). 

I was not able to replicate the issue with the gem `aws-sdk-ec2-1.200.0`, I would suggest you to switch to the version 3 of the SDK and try to run the same code again and let us know if the problem still persists. 

Closing this issue now, please reach out if you have any other questions.
