### ISSUE TITLE
IAM Role function "list_roles" incorrectly returning nil for "role_last_used"

### ISSUE THREAD

**Issue by Bensign** [aws/aws-sdk-ruby#2433]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
The IAM function of [list_roles](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IAM/Client.html#list_roles-instance_method) states in the documentation that each role will have a "resp.roles[0].role_last_used.last_used_date" returned. However, role_last_used always returns nil even with IAM Roles that have activity associated with them. 

<img width="1025" alt="Screen Shot 2020-11-17 at 9 34 54 AM" src="https://user-images.githubusercontent.com/223348/99403214-36001280-28b8-11eb-983c-ee06bb40b81b.png">

I've confirmed in the AWS web console that a subset of my roles have activity on them - so this appears to be a bug with the Ruby client. 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk 3.0.1 and aws-sdk-iam 1.46.0

**Version of Ruby, OS environment**
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**To Reproduce (observed behavior)**
Ensure you have an IAM Role with activity in your AWS account then do the following:

```
iam_client = Aws::IAM::Client.new({
  region: "us-east-1",
  credentials: credentials 
})

# Replace n with the index of the role with activity on it. Should be returning a struct including the datetime of when the role was last used. Instead, it returns nil
iam_client.list_roles[:roles][n][:role_last_used] => nil

# View all role role_last_used data:
# => [nil, nil, nil......nil]
iam_client.list_roles[:roles].map{|x| x[:role_last_used]} 
```

**Expected behavior**
Return a struct of the activity associated with the role as described in the documentation. 

**Additional context**
I should mention that the credentials associated my API call are done via a Cross Account IAM Role with the AWS managed policy of ReadOnlyAccess which should theoretically have permissions to view this data.

**Comment by mullermp** [comment]
Related to https://github.com/aws/aws-sdk-ruby/issues/2360 .. this is not a Ruby SDK bug unfortunately, and a limitation + documentation issue with IAM :/

**Comment by Bensign** [comment]
@mullermp Thanks for the response - not sure how this didn't come up when I searched issues related to this so apologies for the noise.

**Comment by mullermp** [comment]
No worries. Can you actually raise hell by replicating this issue on https://github.com/aws/aws-sdk/issues ? It's a new repo setup specifically for service API issues across all SDKs (which this issue certainly is).

**Comment by Bensign** [comment]
@mullermp It would be my pleasure.

**Comment by mullermp** [comment]
Thanks. I'm sorry about this. At a bare minimum, the documentation should be fixed to comment around these gaps and limitations of their API. When I talked internally to someone on their team a while back, there were technical reasons that they couldn't populate certain data that the API was modeled to do so.
