### ISSUE TITLE
Aws::S3::Errors::AccessDenied: Access Denied

### ISSUE THREAD

**Issue by vinaymehta** [aws/aws-sdk-ruby#2435]
Hey there! 

I am trying to access one bucket objects containing csv files. I am able to access those files via AWS CLI but not via Ruby SDK and receiving error Aws::S3::Errors::AccessDenied: Access Denied. Also via Ruby SDK I am able to access all the buckets present using the keys and region but can't access objects inside a particular object.

This is how my configuration is
```
credentials = Aws::Credentials.new('AWS_KEY_ID', 'AWS_Secret_KEY')
s3 = Aws::S3::Client.new( region: 'eu-west-1', credentials: credentials, logger: Logger.new('s3output.txt'), http_wire_trace: true)
resp = s3.list_objects(bucket: 'BUCKET_NAME')
```

Getting error as **Aws::S3::Errors::AccessDenied: Access Denied**

Please help

**Comment by mullermp** [comment]
Hi @vinaymehta, have you seen this guide here? https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-aws-sdk/

In short, check if the credentials you are using are the same. If you have an ~/.aws/config or ~/.aws/credentials file, and have credentials in a profile, you can use it in the Client: `Aws::S3::Client.new(profile: 'my_profile', ....)`

**Comment by vinaymehta** [comment]
Hi @mullermp 
I had got this issue fixed with AWS Team and they suggested to add prefix '/' always while listing objects in bucket or within folder in bucket.
It was weird that I was able to list objects in AWS CLI without prefix but was giving error in SDK for same.
Thanks for the help.

**Comment by mullermp** [comment]
@vinaymehta Hey, that's weird. I don't need to use a prefix to list objects in a bucket. Is your bucket DNS compatible? Could you enable `http_wire_trace: true` for your Client and share the debug?

**Comment by tonytonyjan** [comment]
@vinaymehta  I feel extremely hard to know the reason from the error message "Access Denied". Unlike aws cli, it would tell what credential is using what action to access what resource and prints all corresponding ARNs.

Can't we do the same thing in `aws-sdk-ruby` by providing more detai to the error message. Any idea?
