### ISSUE TITLE
Add information on core functionality

### ISSUE THREAD

**Issue by laurawadden** [aws/aws-sdk-ruby#2438]
I don't get an immediate sense from the readme what this gem *does* and am forced to know a lot of the context in order to understand it.

It would make the gem much more accessible if someone writes a features list or a short description of how this gem works and what it provides.

**Comment by mullermp** [comment]
Hi @laurawadden, this repository contains multiple gems. You simply need to install any of the service gems (`aws-sdk-<service>`) such as `aws-sdk-s3` or `aws-sdk-ec2`. Each of them depends on `aws-sdk-core`. All of the related core options are available on service clients and are documented in the constructor.

They're listed here: https://rubygems.org/search?query=aws-sdk-

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/
