### ISSUE TITLE
Net::HTTPFatalError not being retried

### ISSUE THREAD

**Issue by allcentury** [aws/aws-sdk-ruby#2439]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

I have set the following environment vars:

```
AWS_RETRY_MODE: "standard"
AWS_MAX_ATTEMPTS: "10"
```

I have a client:

```ruby
client = Aws::SageMakerRuntime::Client.new(
  region: config[:region],
  logger: Rails.logger,
)
```

I see logs that look like this (note I have configured 10 retries but it shows 0 here):

```
"[Aws::SageMakerRuntime::Client 0 30.005846 0 retries] invoke_endpoint(endpoint_name:\"endpoint_name\",body:\"[FILTERED]\",content_type:\"application/json\") Net::HTTPFatalError 504 \"Gateway Time-out\"
```

```ruby
irb(main):017:0> Aws::Plugins::RetryErrors.resolve_max_attempts(nil)
=> 10
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

I think this effects all of them (I see errors for sqs, s3 and sagemakerruntime)

**Version of Ruby, OS environment**

2.6.3

**To Reproduce (observed behavior)**

See above

**Expected behavior**

Setting the environment variable `AWS_MAX_ATTEMPTS` should set a global retry count for all clients, it does not appear to be that way.

**Additional context**

I could be completely misunderstanding how the ENV vars work here but I can't find any docs on this configuration.

**Comment by mullermp** [comment]
Hi @allcentury, I need to double check, but I believe that "0 retries" is the current number of retries on the request, not the configured maximum.

When you say "I see errors for sqs, s3" are you specifically seeing a Ruby error or just this logging behavior?

**Comment by allcentury** [comment]
@mullermp thanks for the quick reply.  I agree, `0` is the current number and I don't see any additional logs for more retries.  

I can see the config is set:

```ruby
irb(main):003:0> client.config.max_attempts
=> 10
```

> When you say "I see errors for sqs, s3" are you specifically seeing a Ruby error or just this logging behavior?

Yes, I just updated the log above - we're getting the occasional error for SQS (`send_message`), SagemakerRuntime and S3.

```
 Net::HTTPFatalError 504 \"Gateway Time-out\"
```

Would I get a log line for each retry?  It seems like yes but I'm not seeing them.

relevant stacktrace of one of them:

```ruby
Net::HTTPFatalError: 504 "Gateway Time-out"
  from net/http/response.rb:122:in `error!'
  from net/http/response.rb:131:in `value'
  from net/http.rb:969:in `connect'
  from net/http.rb:930:in `do_start'
  from net/http.rb:925:in `start'
  from delegate.rb:83:in `method_missing'
  from seahorse/client/net_http/connection_pool.rb:300:in `start_session'
  from seahorse/client/net_http/connection_pool.rb:99:in `session_for'
  from seahorse/client/net_http/handler.rb:123:in `session'
  from seahorse/client/net_http/handler.rb:75:in `transmit'
  from seahorse/client/net_http/handler.rb:49:in `call'
  from seahorse/client/plugins/content_length.rb:17:in `call'
  from seahorse/client/plugins/request_callback.rb:85:in `call'
  from aws-sdk-core/json/error_handler.rb:10:in `call'
  from aws-sdk-core/plugins/signature_v4.rb:68:in `call'
  from aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
  from aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
  from aws-sdk-core/plugins/retry_errors.rb:229:in `call'
  from aws-sdk-core/plugins/http_checksum.rb:18:in `call'
  from aws-sdk-core/plugins/endpoint_pattern.rb:31:in `call'
  from aws-sdk-core/rest/handler.rb:10:in `call'
  from aws-sdk-core/plugins/user_agent.rb:13:in `call'
  from aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
  from seahorse/client/plugins/endpoint.rb:47:in `call'
  from aws-sdk-core/plugins/param_validator.rb:26:in `call'
  from aws-sdk-core/plugins/logging.rb:41:in `call'
  from seahorse/client/plugins/raise_response_errors.rb:16:in `call'
  from aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
  from aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
  from aws-sdk-core/plugins/param_converter.rb:26:in `call'
  from seahorse/client/plugins/request_callback.rb:71:in `call'
  from aws-sdk-core/plugins/response_paging.rb:12:in `call'
  from seahorse/client/plugins/response_target.rb:24:in `call'
  from seahorse/client/request.rb:72:in `send_request'
  from aws-sdk-sagemakerruntime/client.rb:447:in `invoke_endpoint'
```

**Comment by mullermp** [comment]
Yes I do believe you should see log statements for each retry attempt. It seems that the error thrown here is not being retried. We check for server errors (504 included) here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb#L118 so I'm not sure what's going on. Can you configure your Client with `http_wire_trace: true` and see what's going on? The SDK uses Net::HTTP and that library is failing to send a request somehow.. perhaps your network is misconfigured?

**Comment by mullermp** [comment]
Please get back to me with any wire trace information when you can so I can confirm if this is a bug or not.

**Comment by mullermp** [comment]
@allcentury I prepared a change to fix this https://github.com/aws/aws-sdk-ruby/pull/2440 Please confirm that you're using a proxy, and any wire trace logs would be helpful too.

**Comment by allcentury** [comment]
@mullermp - thanks for digging into this.  We do indeed use a proxy for cross-region traffic and that is what appears to be failing here.  Thanks for putting together the PR and for the timely responses it is much appreciated

**Comment by mullermp** [comment]
@allcentury No problem. I tested the change with unit tests but I need to do a real-world test. I can do that later unless you wanted to checkout my pull request and give it a try with your configuration. Once merged, it would be released with tomorrow's release.

**Comment by mullermp** [comment]
There is no planned release today for SDKs in re:Invent's schedule
