### ISSUE TITLE
ElasticLoadBalancingV2::Types::LoadBalancer does not support tags

### ISSUE THREAD

**Issue by fawaf** [aws/aws-sdk-ruby#2447]
**Is your feature request related to a problem? Please describe.**
when using the `ElasticLoadBalancingV2` client to describe ELBs, there is no way to view tags currently.

**Describe the solution you'd like**
support viewing load balancer tags using the sdk

**Describe alternatives you've considered**
N/A

[ ] :wave: I may be able to implement this feature request

**Additional context**

**Comment by mullermp** [comment]
Did you look at `describe_tags`?

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ElasticLoadBalancingV2/Client.html#describe_tags-instance_method

**Comment by fawaf** [comment]
ahh, did not know about that. though it would still be a nice "feature" to have the `Type` support directly query tags.

**Comment by mullermp** [comment]
Hey, I'm not quite sure what you're asking. Could you explain what you mean?

**Comment by fawaf** [comment]
basically something like how many of the other `Types` have it. e.g. https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Types/Instance.html#tags-instance_method. one can directly `Aws::EC2::Types::Instance.tags` for a particular ec2 instance.

**Comment by mullermp** [comment]
I see what you're saying. `Types` are generated from the service model for each service. The EC2 `Instance` type is defined here: https://github.com/aws/aws-sdk-ruby/blob/08a85cd0c37d490c512cfeddff24005d0ec02216/apis/ec2/2016-11-15/api-2.json#L17786-L17982 and it explicitly adds the `tags` on a response with this structure. This seems like a decision that the EC2 service team made and most services do not do this.

If you want to know how many other EC2 types have this method, you could find that with something like this:

```
Aws::EC2::Types.constants.select { |c| Aws::EC2::Types.const_get(c).members.include?(:tags) }
```
