### ISSUE TITLE
Argument Error from S3 EncryptionV2 Client

### ISSUE THREAD

**Issue by arothian** [aws/aws-sdk-ruby#2449]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Using the following gem versions
```
aws-sdk-core 3.109.3
aws-sdk-s3 1.86.0
aws-sdk-kms 1.20.0
```

Calling `get_object` using a new `Aws::S3::EncryptionV2::Client` results in `ArgumentError: unexpected value at params[:key_id]`. 

Updating `aws-sdk-kms` to the latest version resolves the error without any other changes. I suspect that the V2 client needs newer features in the KMS gem, but it indicates loose `aws-sdk-kms ~> 1` constraint. 

**Version of Ruby, OS environment**
`ruby 2.7.1p83`

**To Reproduce (observed behavior)**
Gem versions and method indicated above.

**Expected behavior**
The item is pulled and decrypted from S3.

**Comment by alextwoods** [comment]
Thanks for submitting this.  I've put out a PR to fix: #2450 which should go out tomorrow.
