### ISSUE TITLE
aws-sdk-core-3.110.0/lib/seahorse/client/h2/connection.rb throws /http/2/compressor.rb:333:in `initialize': wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by rgaufman** [aws/aws-sdk-ruby#2455]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

This is my code:
```
require 'aws-sdk'
require 'net-http2'

Aws.config.update(
  credentials: Aws::Credentials.new('REMOVED', 'REMOVED')
)

async_client = Aws::TranscribeStreamingService::AsyncClient.new(
  region: 'eu-west-2',
)
```

It throws the following exception:
```
$ ruby transcribe.rb
/opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/compressor.rb:333:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/connection.rb:79:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/connection.rb:79:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/client.rb:28:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.110.0/lib/seahorse/client/h2/connection.rb:45:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.110.0/lib/seahorse/client/h2/connection.rb:45:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.110.0/lib/seahorse/client/async_base.rb:16:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.110.0/lib/seahorse/client/async_base.rb:16:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-transcribestreamingservice-1.24.0/lib/aws-sdk-transcribestreamingservice/async_client.rb:235:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.110.0/lib/seahorse/client/base.rb:102:in `new'
	from transcribe.rb:9:in `<main>'
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk version 3.2.3

**Version of Ruby, OS environment**
```
Romans-MacBook-Pro-2.local ➜  bin  ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
```

**To Reproduce (observed behavior)**
Provided steps above to reproduce - it seems like net-http2 made some API changes?

**Expected behavior**
It shouldn't throw an exception

**Comment by rgaufman** [comment]
Seems this is possibly an issue with Ruby3 compatibility? - filed a bug here: https://github.com/ostinelli/net-http2/issues/44

**Comment by ostinelli** [comment]
> Seems this is possibly an issue with Ruby3 compatibility? - filed a bug here: [ostinelli/net-http2#44](https://github.com/ostinelli/net-http2/issues/44)

Please note that aws-sdk-ruby doesn't use https://github.com/ostinelli/net-http2, rather https://github.com/igrigorik/http-2.

**Comment by rgaufman** [comment]
Ah, my bad, filed the bug in the correct place: https://github.com/igrigorik/http-2/issues/158

**Comment by HoneyryderChuck** [comment]
In case it helps, I've [forked http-2 more than one year ago](https://gitlab.com/honeyryderchuck/http-2-next), and have kept it API-compatible and up-to-date (it supports ruby 3 for 3/4 weeks).

The reasons for having forked it are outlined [here](https://gitlab.com/honeyryderchuck/httpx/-/issues/60). It's also a transitive dependency of [httpx](https://gitlab.com/honeyryderchuck/httpx), which also supports streaming.

**Comment by rgaufman** [comment]
Ah, interesting, we recently switched to Faraday which seems to be well supported, is there an argument to switch from http-2 to faraday?

**Comment by HoneyryderChuck** [comment]
It's apples and oranges in this case, `http-2` and `faraday` are two different things. `http-2` is just a parser, and can't do much by itself. `faraday` is a "wrapper" on top of multiple http clients, which in theory allows you to choose the client library performing the actual calls (and if you're not, you're using `net-http`).

Back to the original thread, which is the `aws-sdk-core` issue you're complaining about: this sdk ships with its own "wrapper" implementation for `net-http`, except for async clients (I guess you're using kinesis perhaps?), which are using `http-2`, as the APIs are probably HTTP/2 only(?). Given that `http-2` isn't a direct dependency and you might have had to install, I'd suggest you try installing `http-2-next` and add the following snippet:

```ruby
require "http/2/next"
HTTP2 = HTTP2Next
```

and see if that fixes your problem.

**Comment by alextwoods** [comment]
A new version of [http-2](https://rubygems.org/gems/http-2) has been published that resolves this issue.
