### ISSUE TITLE
is necessary 'body_digest' option in 'presign_url' method?

### ISSUE THREAD

**Issue by kbs4674** [aws/aws-sdk-ruby#2463]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

at first, I tried to access a file in AWS S3 by entering the code below as specified in the [AWS Sigv4 document].
```
html_url = "https://#{ENV["BUCKET"]}.s3.#{ENV["REGION"]}.amazonaws.com/2021-01-10/appliance_3432u8ededjde.png"
signer = Aws::Sigv4::Signer.new(
  service: "s3",
  region: AwsManager::REGION_NAME,
  access_key_id: ENV["ACCESS_KEY_ID"],
  secret_access_key: ENV["SECRET_ACCESS_KEY"]
)

signer.presign_url(
  http_method: 'GET',
  url: html_url,
  expires_in: 30
).to_s
```
but I saw this error: "SignatureDoesNotMatch" and I was unable to access it.

So, after adding the body digest option by referring to someone else's code, I entered the URL where the result came out, and I was able to see the result of the S3 file well.
```
## after code
url = "https://#{ENV["BUCKET"]}.s3.#{ENV["REGION"]}.amazonaws.com/2021-01-10/appliance_3432u8ededjde.png"
...
signer.presign_url(
  http_method: 'GET',
  url: html_url,
  body_digest: 'UNSIGNED-PAYLOAD',
  expires_in: 30
).to_s
```

Is 'body_digest' an essential option in presign_url?
If it is correct, I think it will need to be modified README.md.

[AWS Sigv4 document]: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#sign_request-instance_method

**Comment by mullermp** [comment]
Hey @kbs4674 thanks for opening an issue.

I'm curious to know why you're using the SigV4 gem directly to access S3 - we have an [S3 presigner utility class](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/presigner.rb) that you can use:

```
signer = Aws::S3::Presigner.new # will infer ENV["REGION"]
url = signer.presigned_url(:get_object, bucket: "bucket", key: "key")
```

As for `body_digest`, it's a documented optional option here: https://github.com/aws/aws-sdk-ruby/blob/0070c0660e5130518f981caa40d44106eff57736/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L356-L364

**Comment by kbs4674** [comment]
Thanks for answer!
you bring to me better code!!
