### ISSUE TITLE
retry_errors#resolve_max_attempts is getting String from Shared_Config#max_attempts

### ISSUE THREAD

**Issue by tarcinil** [aws/aws-sdk-ruby#2464]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

> While attempting to build up retry_logic with a default profile, SharedConfig is returning String for max_attempts where retry_errors#resolve_max_attempts expects it to be an Integer. 

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
> aws-sdk-core 3.111.0

**Version of Ruby, OS environment**
-paste the output of ruby -v
> ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]

**To Reproduce (observed behavior)**

While trying to build up an S3 Client object with the following config:

```
[default]
max_attempts=6
retry_mode=standard
output=text
region=us-east-1
```

```
credentials = Aws::Credentials.new(access_key, secret_key)
@s3_client = Aws::S3::Client.new(
  region: REGION,
  credentials: credentials
)
```

Returns:
```
/Users/REDACTED/.rvm/gems/ruby-2.6.6/gems/aws-sdk-core-3.111.0/lib/aws-sdk-core/plugins/retry_errors.rb:184:in `resolve_max_attempts': Must provide a positive integer for max_attempts profile option or for ENV['AWS_MAX_ATTEMPTS'] (ArgumentError)

```

The method used by `lib/aws-sdk-core/plugins/retry_errors.rb#resolve_max_attempts` calls into  `Aws.shared_config.max_attempts(profile: cfg.profile)` and this method is correctly return the value from the config file on the system, but it is returning it as a String rather than an Integer, which causes the next section of the resolve_max_attempts method to raise an ArgumentError.

```
[2] pry(Aws::Plugins::RetryErrors)> Aws.shared_config.max_attempts(profile: cfg.profile) 
=> "6"
[3] pry(Aws::Plugins::RetryErrors)> Aws.shared_config.max_attempts(profile: cfg.profile).class
=> String
```

**Expected behavior**

```
[2] pry(Aws::Plugins::RetryErrors)> Aws.shared_config.max_attempts(profile: cfg.profile) 
=> 6
[3] pry(Aws::Plugins::RetryErrors)> Aws.shared_config.max_attempts(profile: cfg.profile).class
=> Integer
```

**Screenshots**

N/A

**Additional context**

> I was able to cast the return to an Integer in retry_errors via `Aws.shared_config.max_attempts(profile: cfg.profile).to_i` and have everything work as expected in retry_errors.  I was also able to set the ENV for `ENV['AWS_MAX_ATTEMPTS']` and have everything work as expected.  It only seems to hit this condition when I am reading from a profile from `.aws/config`.

**Comment by mullermp** [comment]
Related to https://github.com/aws/aws-sdk-ruby/pull/2319. Looking

**Comment by mullermp** [comment]
Thanks for reporting this. I've made a PR at #2465 if you are interested.
