### ISSUE TITLE
Ruby 3.0 and error message - "wrong number of arguments (given 3, expected 2)"

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#2480]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Using the sdk with Ruby 3.0 is printing a message - **_"wrong number of arguments (given 3, expected 2)"_**

The functionality is not really affected, but the messages are printed for every call. This may be due to the keyword passing changes in Ruby 3.0?

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-ec2 (1.224.0)
This is not gem specific. Should probably happen with any of the sdk gems.

**Version of Ruby, OS environment**
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

**To Reproduce (observed behavior)**
`[2] pry(main)> ec2_client  = Aws::EC2::Client.new
=> #<Aws::EC2::Client>

[3] pry(main)> ec2_client.describe_instances

"wrong number of arguments (given 3, expected 2)"
"wrong number of arguments (given 3, expected 2)"
"wrong number of arguments (given 3, expected 2)"
"wrong number of arguments (given 3, expected 2)"

=> #<struct Aws::EC2::Types::DescribeInstancesResult`

**Comment by mullermp** [comment]
Hey, I'm not able to reproduce this.. 

```
[1] pry(Aws)> ec2.describe_instances
[Aws::EC2::Client 200 0.728059 0 retries] describe_instances()  
=> #<struct Aws::EC2::Types::DescribeInstancesResult reservations=[], next_token=nil>
[2] pry(Aws)> RUBY_VERSION
=> "3.0.0"
```

**Comment by mullermp** [comment]
Are you sure this isn't from code that you own? Or inserted handlers? Are you configuring logging levels? If you are able to get a stack trace, that helps too.

**Comment by pchaganti** [comment]
Will double check if it is something we are inserting in the handlers.

thanks!

**Comment by pchaganti** [comment]
Created a completely new environment and not getting this message. Closing this ticket.

thanks!
