### ISSUE TITLE
[aws-sdk-lambda] raises Aws::Errors::MissingCredentialsError when invoking lambda functions under load spike

### ISSUE THREAD

**Issue by guillaumedenece** [aws/aws-sdk-ruby#2481]
We are using the `aws-sdk-lambda` to invoke lambda functions synchronously from our ruby code running on Elastic Beanstalk.
Here is our code:
```
invocation_response = ::Aws::Lambda::Client.new(region: 'eu-west-1')
  .invoke(
    function_name: {{function_name}},
    invocation_type: 'RequestResponse',
    payload: {{payload}}
  )
```

At 23:00UTC every day, we have a spike in the traffic and go from less than 300 invocations per 5 minutes to more than 7.5k in 5 minutes. Out of those 7.5k invocations, more than 100 of them raise the following error: `Aws::Errors::MissingCredentialsError (unable to sign request without credentials set)`.

The SDK uses the credentials of the role attached to the ec2 instance where it is running.

**Gem name**
aws-sdk-lambda, v1.59.0

**Version of Ruby, OS environment**
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**Comment by alextwoods** [comment]
Do you have any way of caching/re-using the Lambda Client between requests (note: our Service Clients are fully thread safe)?

When creating the client, the credentials resolution chain will attempt to get the EC2 credentials from the link local EC2 IMDS service - I'm guessing the surge in requests causes that to fail for some requests, which results in credential resolution not finding credentials.

**Comment by guillaumedenece** [comment]
Hi @alextwoods and thank's a lot for the reply.

> Do you have any way of caching/re-using the Lambda Client between requests (note: our Service Clients are fully thread safe)?

I am not very sure how we could do that.

Here is a a bit more context on how we use the Lambda Client:
1. Our rails server receives a `GET /account?user_id=<user_id>` HTTP request.
2. We invoke a lambda function using the code above and wait for the response.
3. We return the response to the request received at step 1.

Our rails server runs in Elastic Beanstalk with a puma server, so I expect it to maintain a pool of connections to the AWS lambda service.

Is there anything extra that you would advice us to get done here?

**Comment by mullermp** [comment]
On your Rails controller action, are you creating a new Lambda client? @alextwoods is saying that you may want to create the client and store it elsewhere, and on your controller action, use it, without having to create a new one each time. Because each time you create the client, you're attempting to get credentials (which may check EC2)

**Comment by guillaumedenece** [comment]
Hey @mullermp / @alextwoods,

I have stored the client in a singleton and this solved the issue.

Here is the code I implemented:
```
require 'singleton'

class AwsLambdaClient
  include ::Singleton

  attr_accessor :client

  def self.invoke(function_name:, payload:)
    instance.client ||= ::Aws::Lambda::Client.new
    instance.client.invoke(
      function_name: function_name,
      invocation_type: 'RequestResponse',
      payload: payload
    )
  end
end
```


Thank you very much for your help!
