### ISSUE TITLE
copy_to and move_to on Aws::S3::Object don't work with access point ARNs

### ISSUE THREAD

**Issue by roccoblues** [aws/aws-sdk-ruby#2482]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
`copy_to` and `move_to` on `Aws::S3::Object` don't work with access point ARNs.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3

**Version of Ruby, OS environment**
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**To Reproduce (observed behavior)**
```ruby
client = Aws::S3::Client.new(
  region:            ENV['AWS_REGION'],
  access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
)

bucket_arn = "arn:aws:s3:#{ENV['AWS_REGION']}:#{ENV['AWS_ACCOUNT_ID']}:accesspoint/#{ENV['AWS_ACCESS_POINT']}"
key = 'foo'
new_key = 'bar'

object = Aws::S3::Object.new(bucket_arn, key, client: client)
object.exists?
object.move_to("#{bucket_arn}/#{new_key}")
```
```
irb(main):040:0> object = Aws::S3::Object.new(bucket_arn, key, client: client)
=> #<Aws::S3::Object:0x00000000090191f0 @bucket_name="arn:aws:s3:eu-central-1:0000000:accesspoint/images", @key="preview_PIWRiV1BwPEq-zmn1g...
irb(main):041:0> object.exists?
=> true
irb(main):042:0> object.move_to("#{bucket_arn}/#{new_key}")
Traceback (most recent call last):
        1: from (irb):42
ArgumentError (Missing ARN accesspoint name.)
```
**Expected behavior**
No ArgumentError should be raised and the `copy_to` / `move_to` operation should succeed.

**Comment by mullermp** [comment]
Thanks for opening up an issue. I'm taking a look. As a general FYI, Resource models are "deprecated" because they're buggy and code generated around hand-maintained definition file that in itself has limitations.

Have you tried with the [client API copy_object](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#copy_object-instance_method) method?

**Comment by alextwoods** [comment]
Additionally - you can pass `bucket` and `key` to the `copy_to` method and those should work.  The underying issue is that we don't have support for parsing the arbitrary `/` in both bucket and key in our Object Copier.

This should work:
```ruby
object.move_to(bucket: bucket_arn, key: new_key)
```

**Comment by mullermp** [comment]
Please try the workarounds (client API with no resource model usage or passing bucket to `move_to`). This is unfortunately marked as "wontfix" because fixing resource models involves extensive monkey patching and other potentially breaking hacks.

**Comment by roccoblues** [comment]
Thanks for the fast response!

@alextwoods I tried your suggestion but it then fails with:
```
Aws::S3::Errors::InvalidArgument (Invalid resource in copy source ARN)
```

I guess the  `Aws::S3::Object.new` also can't handle a bucket ARN.

Unfortunately I can't easily switch to the client API because the higher level library we use in a legacy project (https://github.com/sorentwo/carrierwave-aws) is build around the resource model.
But I'll see if I can come up with a PR for them or if I can convince our ops people to go without an accesspoint.

Again, thanks for you fast help. Feel free to close this issue.

**Comment by mullermp** [comment]
Actually, I think you can still use resource models for this, provided you initialize `Bucket` and not `Object`. Here is the code for [Bucket initialize](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/bucket.rb#L15). Are you able to create an instance of bucket with the bucket name as the ARN, and then fetch the object from there? Bucket names are used for the host name, and object is just a path. Try `Aws::S3::Bucket.new(arn, client: client)`. Example usage in [a test is here](https://github.com/aws/aws-sdk-ruby/blob/203aaba7242357884fe182be8f2d36f77428b8a7/gems/aws-sdk-s3/spec/bucket/url_spec.rb#L53-L62).

If this doesn't work, I would agree, either not use accesspoint with resource models or somehow find a way to use the official client API.

Just a bit of background, S3 was insistent on making this a client side feature. Our Client APIs handle this behavior through our plugin system but the [hand written resource API models](https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/resources-1.json) do not handle these kinds of abstractions. You can see bucket.rb above as a monkey patch.

**Comment by roccoblues** [comment]
Hi @mullermp, the bucket version also doesn't work:

```
bucket = Aws::S3::Bucket.new(bucket_arn, client: client)
object = bucket.object(key)
irb(main):014:0> object.exists?
=> true
irb(main):015:0> object.move_to(bucket: bucket_arn, key: new_key)
Traceback (most recent call last):
        1: from (irb):15
Aws::S3::Errors::InvalidArgument (Invalid resource in copy source ARN)
```

Anyway, we have switched to a version without accesspoint now and everthing is working as expected.

**Comment by alextwoods** [comment]
@roccoblues  - Sorry that was still not working and that you had to switch to a version without accesspoint.  

When I test locally I the code that I suggested was working:
```ruby
bucket_arn = 'arn:aws:s3:us-west-2:123456789012:accesspoint/myendpoint'
key = 'foo'
new_key = 'bar'

object = Aws::S3::Object.new(bucket_arn, key, client: client)
object.exists?
object.move_to(bucket: bucket_arn, key: new_key)
```

This results in the following SDK calls:
```
[Aws::S3::Client 200 0.009667 0 retries] copy_object(bucket:"arn:aws:s3:us-west-2:123456789012:accesspoint/myendpoint",key:"bar",copy_source:"arn:aws:s3:us-west-2:123456789012:accesspoint/myendpoint/foo")  
[Aws::S3::Client 200 0.00053 0 retries] delete_object(bucket:"arn:aws:s3:us-west-2:123456789012:accesspoint/myendpoint",key:"foo")  
```

Do you have any more sample code or any other differences?
