### ISSUE TITLE
Specifying region `fips-aws-global` does not provide a fips endpoint.

### ISSUE THREAD

**Issue by phene** [aws/aws-sdk-ruby#2486]
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution

## Summary

Specifying the `fips-aws-global` region for clients like Route53 causes client to be created with non-FIPS endpoint.

## Expected Behavior

```ruby
client = Aws::Route53::Client.new(region: 'fips-aws-global')
client.config.endpoint # => #<URI::HTTPS https://route53-fips.amazonaws.com>
```

## Actual Behavior

```ruby
client = Aws::Route53::Client.new(region: 'fips-aws-global')
client.config.endpoint # => #<URI::HTTPS https://route53.amazonaws.com>
```

## Explanation / Root-Cause

I believe the bug is caused by `Aws::Partitions::EndpointProvider#endpoint_for` [where it checks if the service is regionalized and changes the region if it is not](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-partitions/lib/aws-partitions/endpoint_provider.rb#L80). This causes `fips-aws-global` to be replaced with `aws-global`, thereby [causing the non-FIPS endpoint to be returned.](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-partitions/lib/aws-partitions/endpoint_provider.rb#L84)

This _does_ work correctly for regional endpoints:

```ruby
client = Aws::CloudFormation::Client.new(region: 'us-west-2-fips')
client.config.endpoint # => #<URI::HTTPS https://cloudformation-fips.us-west-2.amazonaws.com>
```

## Additional Thoughts

Specifying FIPS endpoints using an alternate region is _very_ cumbersome. I tried to write a method to tell me if a FIPS endpoint is even available (and what the corresponding region is). Maybe something like this could be included in `Aws::Partitions`.  All of the `Aws::Partitions::Partition` objects strip FIPS region details away and never show up in lists or lookups.

```ruby
    def fips_region_if_exists(client, region)
      client_id = client.identifier.to_s
      %W[
        #{region}-fips
        fips-#{region}
      ].find do |fips_region|
        # This works because every FIPS endpoint has a corresponding `credentialScope` that specifies the 
        # non-FIPS version of the region. Otherwise, the original value is returned.
        Aws::Partitions::EndpointProvider.signing_region(fips_region, client_id) != fips_region 
      end || region
    end

    fips_region_if_exists(Aws::Route53::Client, 'aws-global') # => "fips-aws-global"
    fips_region_if_exists(Aws::CloudFormation::Client, 'us-west-2') # => "us-west-2-fips"
    fips_region_if_exists(Aws::EBS::Client, 'us-west-2') # => "fips-us-west-2"
```

**Comment by mullermp** [comment]
Thanks for opening this issue. I will take a look at this. I will also say that SDK teams are currently in talks about FIPS and what it means for features such as S3 access points. The whole situation is not ideal because they're not modeled very well (they're still referred to as "pseudo regions") and they also are inconsistently modeled ("fips" is a prefix AND a suffix in some cases).

**Comment by phene** [comment]
> they also are inconsistently modeled ("fips" is a prefix AND a suffix in some cases).

**Comment by mullermp** [comment]
> Hence my implementation of fips_region_if_exists

Yes. I am not critiquing your method, just pointing it out as a pain point on our side.

**Comment by mullermp** [comment]
Also for reference, there's a public doc with all of the endpoints - https://aws.amazon.com/compliance/fips/

**Comment by mullermp** [comment]
So, I started diving into this issue and unfortunately it's much bigger than just the Ruby SDK. I checked around with some of the other SDKs (PHP, JS v2, Go v1/v2, etc) and they have the same correct, but broken, behavior.

We have some internal documentation for how SDKs should be resolving endpoints from regions. Ruby SDK region resolution follows it almost exactly. Specifically there's a line that states:

```
If the service being requested has a partitionEndpoint and isRegionalized is set to false, then use the endpoint named in the partitionEndpoint attribute of the service.
```

I believe this is where FIPS modeling is breaking, as you pointed out in the first post. So in short, I believe most of the SDKs are doing the correct thing here, but the service endpoint modeling is wrong! A workaround for now would be to use the FIPS endpoints directly into the client.

That said, this needs to be fixed, and unfortunately I don't think I can make a fix to the Ruby SDK just yet - the greater SDK team will need to formalize and agree on some changes, either in the SDK, in the partitions json, or likely both.

**Comment by mullermp** [comment]
I've created a PR https://github.com/aws/aws-sdk-ruby/pull/2489 with a proposed change - I want to get it "ratified" by the other language SDK teams first.

Regarding your feature request about FIPS detection, I think it it something we can honor. I'm sure you are aware, but the FIPS regions are not included in the partition's region list. Your method seems correct.

**Comment by mullermp** [comment]
This should be released tomorrow. I've created a backlog item for each SDK to audit their behavior and push a similar fix.

**Comment by mullermp** [comment]
Re-opening as a feature request for determining if a FIPS endpoint is available. This falls under the larger problem of modeling FIPS..

**Comment by phene** [comment]
I'm happy to open that up as a new issue. I can provide some specific requirements that would make working with fips regions easier.

**Comment by mullermp** [comment]
That's even better. Thank you.
