### ISSUE TITLE
Some emails cannot receive an email through ActionMailer using delivery_method amazon_ses 

### ISSUE THREAD

**Issue by DrSayre** [aws/aws-sdk-ruby#2497]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
Using rails v4.2.11.1 and aws-sdk v2.11.378
action_mailer settings:
```
> Rails.application.config.action_mailer
=> {:delivery_method=>:amazon_ses, :perform_deliveries=>true, :default_url_options=>{:host=>"xxxxxxxx.xxxxxxxx.net"}, :assets_dir=>"/home/app/rails/public", :javascripts_dir=>"/home/app/rails/public/javascripts", :stylesheets_dir=>"/home/app/rails/public/stylesheets", :show_previews=>false, :asset_host=>nil, :relative_url_root=>nil}
```
For almost all emails, there's a 200 response and we get a message id in this format (010001785fc5b97a-783ac7c5-e3de-4c09-a036-9a52bb9f7a23-000000@email.amazonses.com) that shows the email has been sent, with the send_raw_email call in the logs:
```
> ReverificationMailer.reverification_email(report: 'Test', summary: 'This is a test email, you can ignore it.').deliver_now
I, [2021-03-23T15:48:16.987521 #4746]  INFO -- [rails]: [AWS SimpleEmailService 200 0.1572 0 retries] send_raw_email(:destinations=>["goodemail@mail.com"],:raw_message=>{:data=>#<String "Date: Tue, 23 Mar 2021 15:48:16 +0000\r\nFrom: no-reply@state.XXXXXXXX.net\r\nReply-To: no-reply@ state.XXXXXXXX.net\r\nTo: goodemail@mail.com\r\nMessage-ID: <605a0dc0ca205_128a2ad948b965bc7656e@localhost.mail>\r\nSubject: Subject Reverification Results\r\nMime-Version: 1.0\r\nContent-Type: multipart/mixed;\r\n boundary=\"--==_mimepart_605a0dc0bf302_128a2ad948b965bc764a5\";\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n\r\n----==_mimepart_605a0dc0bf302_128a2ad948b965bc764a5\r\nContent-Type: text/plain;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\nThis is a test email, you can ignore it.\r\n----==_mimepart_605a0dc0bf302_128a2ad948b965bc764a5\r\nContent-Type: text/csv;\r\n charset=UTF-8;\r\n filename=reverification_results.csv\r\nContent-Transfer-Encoding: base64\r\nContent-Disposition: attachment;\r\n filename=reverification_results.csv\r\nContent-ID: <605a0dc0ca6cd_128a2ad948b965bc766fe@mi-rails-675c65448c-4758f.mail>\r\n\r\nVGVzdA==\r\n\r\n----==_mimepart_605a0dc0bf302_128a2ad948b9" ... (1013 bytes)>})

=> #<Mail::Message:47112829115080, Multipart: true, Headers: <Date: Tue, 23 Mar 2021 15:48:16 +0000>, <From: no-reply@state.XXXXXXXX.net>, <Reply-To: no-reply@state.XXXXXXXX.net>, <To: ["goodemail@mail.com"]>, <Message-ID: 010001785fc5b97a-783ac7c5-e3de-4c09-a036-9a52bb9f7a23-000000@email.amazonses.com>, <Subject: Subject Reverification Results>, <Mime-Version: 1.0>, <Content-Type: multipart/mixed; boundary="--==_mimepart_605a0dc0bf302_128a2ad948b965bc764a5"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>>
```

However, when the email does not send, we do not get a 200 response, and the object returned doesn't look like something from Amazon SES:
```
> ReverificationMailer.reverification_email(report: 'Test', summary: 'This is a test email, you can ignore it.').deliver_now
=> #<Mail::Message:47112835179140, Multipart: true, Headers: <Date: Tue, 23 Mar 2021 15:48:36 +0000>, <From: no-reply@state.XXXXXXXX.net>, <Reply-To: no-reply@state.XXXXXXXX.net>, <To: ["bademail@mail.com"]>, <Message-ID: <605a0dd41cdb4_128a2ad948b965bc76871@localhost.mail>>, <Subject: Subject Reverification Results>, <Mime-Version: 1.0>, <Content-Type: multipart/mixed; boundary="--==_mimepart_605a0dd436f0_128a2ad948b965bc76772"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>>
```

Whats weird is calling `send_raw_email` using the bad email does actually send to the address.  Talking to AWS Support, there is no logs of trying to send to the bad email address (except when using send_raw_email directly).  That kinda makes me think its something specific using amazon_ses through ActionMailer.  Is there some reason why the email would be stopped before actually being sent with `send_raw_email`?

**Comment by alextwoods** [comment]
Yeah - thats a bit weird - to me this looks like its likely `ActionMailer` behavior.  What makes the email "bad" in these cases?  Is there a difference in content or send address that could be causing some part of ActionMailer to fail?  

Its interesting that the `message-id` on the failed send has `@localhost.mail` - is it possible you're setting `delivery_options` or `delivery_method` in the Mailer? Or changing the config somewhere else to use a different delivery method?

**Comment by DrSayre** [comment]
Not sure what makes the email bad.  From what I can tell from AWS Support there is nothing preventing sending to the email.  They could not find it in the logs where we attempt to send and could actually send to the email calling using `send_raw_email` directly.  Did try another mailer and got the same issue.

Only using amazon_ses for delivery_method.  For example, if I call delivery_method on the mailer before and after I send, I get AWS::SimpleEmailService:
```
> mail = ReverificationMailer.reverification_email(report: 'Test', summary: 'This is a test email, you can ignore it.')
=> #<Mail::Message:47340431225620, Multipart: true, Headers: <From: no-reply@state.XXXXXXXX.net>, <Reply-To: no-reply@state.XXXXXXXX.net>, <To: ["bademail@mail.com"]>, <Subject: Subject User Reverification Results>, <Mime-Version: 1.0>, <Content-Type: multipart/mixed; boundary="--==_mimepart_605a9c5f88ea1_51312b0e46dc05bc277a7"; charset=UTF-8>>
> mail.delivery_method
=> <AWS::SimpleEmailService>
> mail.deliver_now
=> #<Mail::Message:47340431225620, Multipart: true, Headers: <Date: Wed, 24 Mar 2021 01:57:07 +0000>, <From: no-reply@state.XXXXXXXX.net>, <Reply-To: no-reply@state.XXXXXXXX.net>, <To: ["bademail@mail.com"]>, <Message-ID: <605a9c7366bdd_51312b0e46dc05bc278c6@localhost.mail>>, <Subject: Subject User Reverification Results>, <Mime-Version: 1.0>, <Content-Type: multipart/mixed; boundary="--==_mimepart_605a9c5f88ea1_51312b0e46dc05bc277a7"; charset=UTF-8>, <Content-Transfer-Encoding: 7bit>>
> mail.delivery_method
=> <AWS::SimpleEmailService>
```

The mailer used has no special `delivery_options` specific to it.  It does feel like the `delivery_method` is being changed somewhere with the emails Ive had trouble with. Problem is, so far I cant track it down in the `ActionMailer` code and the `aws-sdk` code where that can happen.

**Comment by mullermp** [comment]
Are you using `aws-sdk-rails`? Should this issue belong in https://github.com/aws/aws-sdk-rails?

That namespace, `AWS::SimpleEmailService` is part of Ruby SDK v1 and is deprecated and not guaranteed to work: https://docs.aws.amazon.com/sdk-for-ruby/v1/api/AWS/SimpleEmailService.html
