### ISSUE TITLE
Aws::Sigv4::Signer presign_url expires_in option not supported for SQS url presigning?

### ISSUE THREAD

**Issue by sybohy** [aws/aws-sdk-ruby#2498]
We're pre-signing URL's for a resource to poll a specific SQS queue. The `expires_at` option does not seem to be respected for SQS. 

We tried setting the `expires_in` to 1 day, 10 seconds, 5 days...etc. Each time, the URL is issued correctly but only lasts for 15 mins (the default). 

## Signer

Upon inspecting the AWS-sigv4 lib, the `presign_url` appears to be doing the right thing when looking at the [generated params](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L397). The example below is for `expires_in=10`:

```ruby
puts params
{"X-Amz-Algorithm"=>"AWS4-HMAC-SHA256", "X-Amz-Credential"=>"<cred_removed>/20210325/<aws_region_removed>/sqs/aws4_request", "X-Amz-Date"=>"20210325T185128Z", "X-Amz-Expires"=>"10", "X-Amz-SignedHeaders"=>"host"}
```

Yet despite `"X-Amz-Expires"=>"10"`, the resulting URL will still last for 15 mins. 

## Steps to Reproduce

```ruby
signer = Aws::Sigv4::Signer.new(
  service: "sqs",
  region: <your_aws_region>,
  access_key_id: <your aws access key>,
  secret_access_key: <your secret key>
)

presigned_url = signer.presign_url(
  http_method: "get",
  url: <url to your sqs queue with action Action=ReceiveMessage and MessageId set to what you wish to poll>,
  body: nil,
  expires_in: 10
)
```

## Additional Info

gem version: `aws-sigv4-1.2.2` 

Ruby version:
```shell
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
```

please let me know if you need more details. 

edit: changed `Action=SendMessage` to `Action=ReceiveMessage`

**Comment by alextwoods** [comment]
Just want to confirm a few things - I don't believe the `SendMessage` Action should be used for polling (I believe it would be `Action=ReceiveMessage`.

How are you constructing the url?  I was able to create a presigned url with: `https://sqs.<region>.amazonaws.com/<id>/<name>?Action=ReceiveMessage`.

Can you also confirm that in the generated url that `X-Amz-Date` and `X-Amz-Expires` are set correctly?

**Comment by alextwoods** [comment]
I was able to reproduce this issue locally and confirmed that `X-Amz-Date` and `X-Amz-Expires` were set correctly, but that the `X-Amz-Expires` value was ignored by the service.  I'm contacting the SQS team to see if this is a bug on their end or something they don't support.

**Comment by sybohy** [comment]
@alextwoods I apologize for the typo; I meant for my bug report to be about `Action=ReceiveMessage` and not `SendMessage` as I originally indicated. To be clear, I did do all the testing/bug-hunting with `Action=ReceiveMessage`. Looking forward to hearing back from the SQS team.

**Comment by alextwoods** [comment]
I'm still speaking with the SQS team, but It looks like the service itself likely doesn't support the `X-Amz-Expires` header (ie, `expires_in`).  

A few possible workarounds:
1. Generate the presigned url within 15 minutes of when it will be used.
2. Front this with a simple API Gateway/Lambda that just `receive_messages` and returns the results. This would give you an always available url (though of course lacking any expiration).
3. Create a role w/ limited access permissions and give whatever other application needs to receive messages ability to assume role.

**Comment by alextwoods** [comment]
I've confirmed that SQS doesn't support presigned url parameters including `expires`.  I've left it as a feature request to them, but for now you'll need to use one of the other workarounds.
