### ISSUE TITLE
Create zip archives using AWS Lambda with files from S3

### ISSUE THREAD

**Issue by tchukuchuk** [aws/aws-sdk-ruby#2503]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**

Hi,

I would like to create zip archives using AWS Lambda with files from S3.
I have to limit usage of memory and disk space allocated because of some limitations with Lambda, so I want to use streams.

I try this :

```ruby
     require 'aws-sdk-s3'
     require 'zip'

    object.upload_stream do |write_stream|
      Zip::OutputStream.write_buffer(write_stream) do |zio|
        files.each do |file|
          zio.put_next_entry("folder/#{File.basename(file['url'])}")
          uri = URI(file['url'])
          Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
            request = Net::HTTP::Get.new(uri)
            http.request(request) do |response|
              response.read_body { |chunk| zio.write(chunk) }
            end
          end
        end
      end
    end
```

But I have this error (IO class doesn't implement seek) :

```
/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.83.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:94:in `abort_upload': multipart upload failed: Illegal seek (Aws::S3::MultipartUploadError)
        from /Users/jbiard/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.83.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:83:in `upload_parts'
        from /Users/jbiard/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.83.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in `upload'
        from /Users/jbiard/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.83.2/lib/aws-sdk-s3/customizations/object.rb:273:in `upload_stream'
```

Do you know how I can do this ?

Regards.

**Comment by alextwoods** [comment]
I believe the fundamental issue here is that the `IO.pipe` used by the SDK to stream uploads does not allow seek, but it looks like `Zip::OutputStream.write_buffer` needs to be able to seek within its stream.   

I believe you may need to use a different Zip library - it looks like `zip_trick` may support what's needed here: https://github.com/WeTransfer/zip_tricks
