### ISSUE TITLE
Aws::S3::Errors::SlowDown after upgrading aws-sdk-s3 to 1.92.0

### ISSUE THREAD

**Issue by tylercallahan** [aws/aws-sdk-ruby#2504]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
~35 minutes after deploying changes to production on Tue 3/30 we started to see `Aws::S3::Errors::SlowDown` errors in a number of places throughout our application. We rolled back the deploy and the errors stopped.

The deploy included an upgrade to the `aws-sdk-s3` gem from 1.91.0 -> 1.92.0 and the `aws-partitions` gem from 1.433.0 -> 1.434.0. We don't see any other changes that might be related to S3 or file access.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-s3` 1.92.0

**Version of Ruby, OS environment**
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**To Reproduce (observed behavior)**
Deployed changes including gem upgrade to `aws-sdk-s3` 1.92.0

**Expected behavior**
No `Aws::S3::Errors::SlowDown` errors, unless our AWS request traffic increased considerably.

**Additional context**
The deploy happened at 9:31am PT. Errors started at 10:08am and stopped at 10:21am when we rolled back.

Looking at our logs around that period, we don't see any change in AWS request rate that would trigger the `SlowDown` error. In the graph below, the first vertical marker is when the deploy happened, and the gray region on the right is when we encountered `SlowDown` errors. During the entire period it looks like we stayed around ~30-40 requests/sec, peaking around 70 requests/sec (well below the limits of 3500 PUT/COPY/POST/DELETE and 5500 GET/HEAD requests/sec mentioned [here][1]).

![image](https://user-images.githubusercontent.com/19316275/113361296-84123180-9300-11eb-9363-427dfcb5ec87.png)

Any thoughts on whether any change in the gem may have contributed to this error, or ideas about what else we could check?

Thanks!

[1]: https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/

**Comment by mullermp** [comment]
Hey. Thanks for opening an issue. `Aws::S3::Errors::SlowDown` is certainly a service side issue. `aws-sdk-s3` version 1.92.0 included changes that support S3 object lambdas. Are you by chance using an ARN as input to the bucket parameter? Are you also configuring a retry mode?

**Comment by tylercallahan** [comment]
Thanks Matt. We aren't using an ARN or a retry mode (or the S3 Object Lambda feature). (I did see a `retry_limit` parameter in the logs set to 3, but per the docs [here](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/S3/Client.html) I think that's just the default.)

Let us know if you think of anything else we can check, and otherwise we'll update here if we find anything.

**Comment by mullermp** [comment]
Thanks for getting back to us. If you aren't using an ARN for input, then, in theory, there shouldn't have been a change in `aws-sdk-s3` that would cause this issue. Are you sure that rolling back to the previous gem version really changed anything? More specifically, have you isolated the change and rollback to just the S3 gem upgrade and not any other changes to your application? The only difference between the S3 version is some new model updates + ARN logic, and there are no changes to how requests and responses are handled.

Regarding the retry mode, if you are not configuring it, then you are defaulting to `legacy`. The [retry options are documented here](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L314-L327) and perhaps you should try the `standard` mode and see if you get improvements with retry backoff?

Ultimately, if you're not changing anything in your application, this might be an issue with the S3 service. By chance have you created a customer support ticket?

**Comment by mockdeep** [comment]
Okay, I guess this can probably be closed. We contacted support and they weren't able to provide a lot of information either. They did ask for a request id, which doesn't appear to be in our logs anywhere. If we configure a `logger` will that display the request id for us? Or is there another way we can get at it when an error happens?

**Comment by mullermp** [comment]
For an S3 call, I think the best way to access the request ID is to do `resp.context.http_response.headers['x-amz-request-id']` where `resp = s3.list_buckets` or some other operation. You can configure a log formatter pattern with `http_response_headers` if you wanted to log it automatically. In whatever logger you are using, you might be better off logging the request ID at the debug level.

I'll close this for now but feel free to re-open with new information.
