### ISSUE TITLE
Higher default multipart threshold for S3 uploads

### ISSUE THREAD

**Issue by dbelling** [aws/aws-sdk-ruby#2505]
**Is your feature request related to a problem? Please describe.**

I recently went through a frustrating exercise with an, arguably dated [`1.8.0`](https://rubygems.org/gems/aws-sdk/versions/1.8.0), version of the sdk involving the [`upload_file`](https://github.com/aws/aws-sdk-ruby/blob/a82c8981c95a8296ffb6269c3c06a4f551d87f7d/gems/aws-sdk-s3/spec/object/upload_file_spec.rb) function. This particular function was used as part of an ETL pipeline where batched file exports were previously less than 15MB, and became larger than 15 MB (but still less than 100 MB) through some refactoring. Due to the underlying default here - we experienced hung jobs when uploads became multiparted. Fortunately, the support for the options hash to set this value directly allowed us to squash these particular hangups.

**Describe the solution you'd like**

From the [AWS documentation](https://aws.amazon.com/s3/faqs/#:~:text=Individual%20Amazon%20S3%20objects%20can,using%20the%20Multipart%20Upload%20capability.):
> Q: How much data can I store in Amazon S3?
> The total volume of data and number of objects you can store are unlimited. Individual Amazon S3 objects can range in size from a minimum of 0 bytes to a maximum of 5 terabytes. The largest object that can be uploaded in a single PUT is 5 gigabytes. For objects larger than 100 megabytes, customers should consider using the Multipart Upload capability.

Given this guidance, I think a more sensible default for the multipart threshold would be 100 MB instead of 15 MB.

**Describe alternatives you've considered**

There is a workaround, to [set this value directly in the options hash](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method) - but I think keeping the library in parity with the guidance from the documentation could save future developers the frustration that I experienced.

- [X] :wave: I may be able to implement this feature request

**Additional context**

This seems like a pretty trivial change, and with the maintainer's blessing - I'd be happy to make this particular change to bump the default to 100 MB.

**Comment by mullermp** [comment]
Hey. Thanks for opening an issue. I would be open to changing the default and generally encourage it. However I think this could break a large number of unit tests for depending packages.. We would really need to consider the implications of that.

**Comment by dbelling** [comment]
> Hey. Thanks for opening an issue. I would be open to changing the default and generally encourage it. However I think this could break a large number of unit tests for depending packages.. We would really need to consider the implications of that.

Understood. Is there any documentation regarding semantic versioning the sub packages of the sdk to make this change in the most conservative way possible?

**Comment by dbelling** [comment]
I took a stab at this in [#2506](https://github.com/aws/aws-sdk-ruby/pull/2506) - from what I could tell, the `aws-sdk-s3control` and `aws-sdk-s3outposts` packages were the only libraries that I could find which have a dependency on the core functionality in `aws-sdk-s3`. These test suites (along with the core test suite) appear to be passing now.

Please let me know if there's anything else I should be aware of with proposing this change. Thanks!

**Comment by alextwoods** [comment]
The individual service gems follow standard semantic versioning - breaking changes would require a major version upgrade, which we in general would only do w/ a new version of the SDK.

I think the possible risk in changing the default here is that many non-AWS packages depend on this functionality, and this change to default behavior may break their tests (or actual behavior) and we don't have control over any of those codebases.  We're having an internal discussion to determine the risk and possible impact and should have an answer by EOW.

**Comment by dbelling** [comment]
@alextwoods - thanks for the clarity and update!
