### ISSUE TITLE
validation Error detected by using  Aws::S3::Client#write_get_object_response

### ISSUE THREAD

**Issue by Haresaku** [aws/aws-sdk-ruby#2508]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Validation error when running `write_get_object_response` on s3 Object Lambda endpoint in Ruby Lambda.

```
{
    "errorMessage": "1 validation error detected: Value '{Accept=*/*, Accept-Encoding=, Content-Type=, X-Amz-Content-Sha256=UNSIGNED-PAYLOAD, X-Amz-Date=20210412T092330Z, X-Amz-Request-Route=io-cell002, X-Amz-Request-Token={REQUEST_TOKEN}, X-Amz-Security-Token={SECURITY_TOKEN}, x-amzn-cipher-suite=ECDHE-RSA-AES128-GCM-SHA256, x-amzn-tls-version=TLSv1.2}' at 'metadata' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 3000, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: ^.*$]",
    "errorType": "Function<Aws::S3::Errors::ValidationError>",
    "stackTrace": [
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'",
        "/var/runtime/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'",
        "/var/runtime/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/dualstack.rb:36:in `call'",
        "/var/runtime/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.113.1/lib/seahorse/client/request.rb:72:in `send_request'",
        "/var/runtime/gems/aws-sdk-s3-1.93.0/lib/aws-sdk-s3/client.rb:13897:in `write_get_object_response'",
        "/var/task/lambda_function.rb:7:in `lambda_handler'"
    ]
}
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3

**Version of Ruby, OS environment**
- Ruby 2.7 (Lambda Runtime)

**To Reproduce (observed behavior)**
- Create a Lambda function with Ruby 2.7 runtime
- Give the execution role `s3-object-lambda:WriteGetObjectResponse`.
- Write and deploy the following code
- Create an Object Lambda AccessPoint from s3
- Set up and execute the deployed function in Lambda.

```ruby
require 'json'
require 'aws-sdk-s3'

def lambda_handler(event:, context:)
    get_obj_context = event['getObjectContext']

    client = Aws::S3::Client.new(region: 'ap-northeast-1')
    client.write_get_object_response({
        request_route: get_obj_context['outputRoute'],
        request_token: get_obj_context['outputToken'],
        status_code: 403,
        error_code: 'MissingToken',
        error_message: 'some error message'
    })
end
```

**Comment by mullermp** [comment]
I'm taking a look at this. I am guessing that S3 does not like the empty content-type and accept-encoding headers used by the Ruby SDK..

**Comment by mullermp** [comment]
As expected, S3 Object Lambdas is validating that the Metadata has values of at least length 1. Content-Type and Accept-Encoding are of length 0. The Ruby SDK does this because Net::HTTP sets some default values that do not work well with AWS services. I'm working with S3 to relax this validation to accommodate for Ruby SDK's legacy code. I am also investigating ways to remove that legacy code in a safe and backwards compatible way.

You can work around this for now by adding a custom plugin to set the content type:
```
require 'json'
require 'aws-sdk-s3'

class AddContentType < Seahorse::Client::Plugin
  class Handler < Seahorse::Client::Handler
    def call(context)
      context.http_request.headers['content-type'] = 'text/plain'
      context.http_request.headers['accept-encoding'] = '**/*'
      @handler.call(context)
    end
  end
  handler(Handler, step: :sign)
end

def lambda_handler(event:, context:)
    get_obj_context = event['getObjectContext']

    Aws::S3::Client.add_plugin(AddContentType)

    client = Aws::S3::Client.new(region: 'us-east-1')
    client.write_get_object_response({
        request_route: get_obj_context['outputRoute'],
        request_token: get_obj_context['outputToken'],
        body: "HELLO!"
    })
end
```

**Comment by mullermp** [comment]
In `us-east-1` I was able to confirm that this works without a plugin. Other regions should eventually have the fix.
