### ISSUE TITLE
Does the ruby sqsClient have the equivalent of javas connectionTTL

### ISSUE THREAD

**Issue by JacobJohansen** [aws/aws-sdk-ruby#2509]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html) : Couldn't find equivalent
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers: Community closed my question without answering it [StackOverflow Question](https://stackoverflow.com/questions/67182932/does-ruby-aws-sqs-client-have-an-equivalent-to-javas-connection-ttl)

**Describe the question**
Does the ruby sqsClient have the equivalent of javas connectionTTL?

our logstash servers seem to have their connections pointing to stale servers with no data even though the SQS interface show available messages and restarting the indexer solves the problem; setting the `connectionTTL` in java solved a similar problem that occurred in our java clients in the past. 

Thanks

**Comment by alextwoods** [comment]
I'm not familiar with exactly what Java's connectionTTL does, but ruby supports 3 http parameters you may be able to tweak: `http_open_timeout`(default 15), `http_idle_timeout`(5), and `http_read_timeout` (60), see the [Client#Initialize](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/Client.html#initialize-instance_method) documentation for details.

**Comment by JacobJohansen** [comment]
it give the connection in the client http pool a max time to live; so even if its not idle, it will reap the connection and put a new one in the pool giving it fresh connection metadata (potentially sticky session to an sqs nodes)

**Comment by alextwoods** [comment]
Try setting the `:http_idle_timeout`, it's used in the [connection pool](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L284) to set Net::Https `keep_alive_timeout` on the connections.

**Comment by JacobJohansen** [comment]
Sorry, i was just looking through the code you pointed me to, that will still leave the session in the pool

I believe the [Session](https://github.com/aws/aws-sdk-ruby/blob/a82c8981c95a8296ffb6269c3c06a4f551d87f7d/gems/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L321) would need a new attribute extension `attr_reader :created_at` and initialized at initialization

a new option in the [connection pool](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L26) class possibly called `http_connection_ttl`

and another connection [clean](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L313) check to see if the session is past its TTL

``` ruby
if session.created_at.nil? or now - session.created_at > http_connection_ttl * 1000
   session.finish
   true
end
```

**Comment by alextwoods** [comment]
Ah I see, so you're looking to reap active, but older connections?

What code are you using to poll SQS?

**Comment by JacobJohansen** [comment]
its a logstash pluggin that currently stops pulling messages from time to time

**Comment by alextwoods** [comment]
Adding `http_connection_ttl` may make sense - I'd like to spend a little more time considering and understanding what other SDKs do here as well.

In the meantime, does setting `http_idle_timeout` to `0` potentially address your issue?

**Comment by JacobJohansen** [comment]
well the connections are always polling, its just that they keep going to servers with no data on them currently... I believe it has something to do with a node migration behind the scenes. 

the client is also ran from a project that has a very low deployment frequency.

**Comment by alextwoods** [comment]
I believe setting `http_idle_timeout` to `0` should still address that (though it effectively disables the connection pool) - connections will not be re-used at all.
