### ISSUE TITLE
Error "multipart upload failed: File too large - sendfile"

### ISSUE THREAD

**Issue by lphm** [aws/aws-sdk-ruby#2510]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I have a bug when I upload a big file (2GB) on Amazon S3 service via activestorage

```
"multipart upload failed: File too large - sendfile"
multipart upload failed: File too large - sendfile
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:94:in `abort_upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:83:in `upload_parts'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/customizations/object.rb:279:in `upload_stream'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/service/s3_service.rb:122:in `upload_with_multipart'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/service/s3_service.rb:33:in `block in upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'
/home/test/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/test/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/service.rb:155:in `instrument'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/service/s3_service.rb:27:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/app/models/active_storage/blob.rb:253:in `upload_without_unfurling'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/attached/changes/create_one.rb:28:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/core_ext/object/try.rb:15:in `public_send'
/home/test/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/core_ext/object/try.rb:15:in `try'
/home/test/vendor/bundle/ruby/2.7.0/gems/activestorage-6.1.3.1/lib/active_storage/attached/model.rb:77:in `block in has_one_attached'
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3

**Version of Ruby, OS environment**
2.7.2 Mac OS

**To Reproduce (observed behavior)**
When I put a Tar Gzip file with below code :
model.remote_file.attach(io: File.open(backup_file.path), filename: "#{self.label.to_slug}_backup.tar.gz")

**Expected behavior**
"multipart upload failed: File too large - sendfile"

Changing *multipart_threshold* parameter in storage.yml don't change anything.
```
remote_backups_amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: eu-west-3
  bucket: test
  upload:
    multipart_threshold: <%= 100.megabytes %>
```

**Comment by mullermp** [comment]
Thanks for opening the issue. I think this may be an issue with ActiveStorage and not the SDK. I was not able to reproduce this by only using the SDK functionality. I did the following:

Created a 2G test file with `mkfile 2G 2g_file`. When using the upload stream, I used [similar code to ActiveStorage](https://github.com/rails/rails/blob/e56a5146cf176ed752008dbbeb2cba7d43d9b333/activestorage/lib/active_storage/service/s3_service.rb#L119):
```
o = Aws::S3::Object.new(bucket_name: bucket_name, key: 'large-file')
MAXIMUM_UPLOAD_PARTS_COUNT = 10000
MINIMUM_UPLOAD_PART_SIZE   = 5 * 1024 * 1024 # don't have access to 5.megabytes
io = File.open("~/workplace/aws-sdk-ruby/2g_file")
part_size = [ io.size.fdiv(MAXIMUM_UPLOAD_PARTS_COUNT).ceil, MINIMUM_UPLOAD_PART_SIZE ].max

o.upload_stream(part_size: part_size) do |out|
  IO.copy_stream(io, out)
end
```

The result is a 2G file in my bucket as expected. I omitted multipart threshold config because it defaults to 100 megabytes. Perhaps see if changing multipart threshold to a number larger than 2G will work? That would force a single put object call. You may need to open an issue with rails/activestorage.

**Comment by lphm** [comment]
Same error :
Aws::S3::MultipartUploadError: multipart upload failed: File too large - sendfile
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:94:in `abort_upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:83:in `upload_parts'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/customizations/object.rb:279:in `upload_stream'

**Comment by mullermp** [comment]
That's strange. If multipart_threshold is > 2G then it shouldn't be attempting to multipart upload. Is your top level key "remote_backups_amazon" working with ActiveStorage as expected? The [docs expect :amazon](https://edgeguides.rubyonrails.org/active_storage_overview.html) but it may only need to match `config.active_storage.service`. From the SDK perspective, everything is working as intended.

**Comment by lphm** [comment]
Ok, I have made many tests and it works nicely when size of file < 5G. But when file is > 5G, single upload cannot be made and "Aws::S3::MultipartUploadError: multipart upload failed: File too large - sendfile" is raised.
I don't understand why this error appears...

**Comment by mullermp** [comment]
Just to clarify: a 2GB file is working for you now, and you're having difficulty uploading a >5GB file?

**Comment by mullermp** [comment]
That error is strange. Using the SDK (and the code above, similar to what ActiveStorage is doing) I was able to successfully upload a 6G file. If you're still having trouble, perhaps raise an issue in the Rails github repo?

**Comment by lphm** [comment]
I don't understand problem. I create a rake test as below :
```
desc "test big file"
  task test: :environment do
    o = Aws::S3::Object.new(
      bucket_name: 'test-remote-backup',
      key: 'large-file',
      region: 'eu-west-3',
      access_key_id: Rails.application.credentials.dig(:aws, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:aws, :secret_access_key),
    )
    MAXIMUM_UPLOAD_PARTS_COUNT = 10000
    MINIMUM_UPLOAD_PART_SIZE = 5 * 1024 * 1024 # don't have access to 5.megabytes
    io = File.open("/tmp/2g_file")
    part_size = [io.size.fdiv(MAXIMUM_UPLOAD_PARTS_COUNT).ceil, MINIMUM_UPLOAD_PART_SIZE].max

    o.upload_stream(part_size: part_size) do |out|
      IO.copy_stream(io, out)
    end
  end
```

Same error : 
Aws::S3::MultipartUploadError: multipart upload failed: File too large - sendfile
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:94:in `abort_upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:83:in `upload_parts'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/customizations/object.rb:279:in `upload_stream'
/home/test/lib/tasks/active_storage.rake:24:in `block (2 levels) in <main>'

**Comment by lphm** [comment]
I think it is not link to a Rails/ActiveStorage problem. Maybe a missing / malform configuration on my S3 bucket ?

**Comment by mullermp** [comment]
That's strange. You might be right. Try creating a new bucket with default settings. Maybe also try a different file? I used the `mkfile` command to generate a dummy file - but I was not able to reproduce what's going on.

**Comment by lphm** [comment]
Same error. I created bucket in new region, different file made with another tool, etc.
Does multipart upload requires permissions on Amazon S3 instance ?

**Comment by lphm** [comment]
It works perfectly with AWS Cli...

**Comment by mullermp** [comment]
Could you enable `http_wire_trace: true` in the client to see if "File too large - sendfile" is returned by S3?

**Comment by mullermp** [comment]
I'm not able to reproduce this, I don't know why, either. It works just fine for me.

**Comment by lphm** [comment]
I enable `http_wire_trace` and error is throw after "DELETE" call, maybe when file is transfered ?! I don't understand why a DELETE command is sent.

<- "DELETE /large-file?uploadId=zaqUkmzX49dupiujDwPe_hWrRQWx3s91r4g_pFsMs13Y_uDExab1hG.2GWZ4gS0jdnsbBPhFc_h5WGhiIgkNuj6u3mAsH0MlihMOlxB57skKWx5Cl27ejU5JVHhzpTFq HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.114.0 ruby/2.7.2 x86_64-linux aws-sdk-s3/1.93.1\r\nHost: test-remote-backup.s3.eu-west-3.amazonaws.com\r\nX-Amz-Date: 20210427T072528Z\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=[redacted]/20210427/eu-west-3/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=7966d3526a0910a5148c2d6b7b7bdc0daea32b50695435d55b7c9e4e1c0c9af7\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 100 Continue\r\n"
-> "\r\n"
-> "HTTP/1.1 204 No Content\r\n"
-> "x-amz-id-2: ZAVKm4wERHC/A5i9wB8/ErYc9mAtbua+M/sgpsoRn23Bg1wJhWBxKTfcI5ImfVOnzqRssTPxbLY=\r\n"
-> "x-amz-request-id: SHN43SKKYG5S1F1M\r\n"
-> "Date: Tue, 27 Apr 2021 07:25:29 GMT\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
Conn keep-alive
rake aborted!
Aws::S3::MultipartUploadError: multipart upload failed: File too large - sendfile
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:94:in `abort_upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:83:in `upload_parts'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/multipart_stream_uploader.rb:45:in `upload'
/home/test/vendor/bundle/ruby/2.7.0/gems/aws-sdk-s3-1.93.1/lib/aws-sdk-s3/customizations/object.rb:279:in `upload_stream'
/home/test/lib/tasks/active_storage.rake:27:in `block (2 levels) in <main>'
/home/test/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/test/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/home/test/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => active_storage:test
(See full trace by running task with --trace)
-> "HTTP/1.1 200 OK\r\n"
-> "x-amz-id-2: cy3wlye+doOmu4rsJpkRLQZraqjeWm1HKGCYDxajgQUVO8kigtP2MyNg64j32zs7yte1mjP8bP4=\r\n"
-> "x-amz-request-id: SHNDS6EVTA8X4CNR\r\n"
-> "Date: Tue, 27 Apr 2021 07:25:29 GMT\r\n"
-> "ETag: \"5f363e0e58a95f06cbe9bbc662c5dfb6\"\r\n"
-> "Content-Length: 0\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
reading 0 bytes...

**Comment by mullermp** [comment]
The `DELETE` call is from `abort_multipart_upload` which is expected and called right before raising the error: https://github.com/aws/aws-sdk-ruby/blob/882aa1033c79bc9506b3da9631a55e16a0ab6ce5/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_stream_uploader.rb#L88-L94 At this point, there was already an issue uploading a part.

The `abort_upload` method is called when `errors` array is not empty. That errors array (containing "File too large - sendfile") is passed to MultipartUploadError. I can't find anything useful about "File too large - sendfile" on the web. Is there anything further up in the wire trace logs that can help?

What happens if you change the part size, to something larger, like 10MB?

**Comment by lphm** [comment]
No change if I pass on 10MB part size. Attached details log with 5MB part size and 2G file
[aws_log.txt](https://github.com/aws/aws-sdk-ruby/files/6386469/aws_log.txt)

**Comment by mullermp** [comment]
This is a very weird edge case. I don't see any failures in the log file. Maybe threading is an issue? Could you also try changing the thread count to 1?

**Comment by mullermp** [comment]
This may be a long shot, but are you using IO anywhere in your app? `sendfile` is a system command. Perhaps IO needs to be flushed somewhere somehow?

**Comment by lphm** [comment]
My test code is just a rake test, so no.

> This may be a long shot, but are you using IO anywhere in your app? `sendfile` is a system command. Perhaps IO needs to be flushed somewhere somehow?

My test code is just a rake task, so no :

desc "test big file"
  task test: :environment do

    o = Aws::S3::Object.new(
      bucket_name: 'sociatex-remote-backup',
      key: 'large-file',
      region: 'eu-west-3',
      access_key_id: Rails.application.credentials.dig(:aws, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:aws, :secret_access_key),
      http_wire_trace: true,
      #upload:{
      #  multipart_threshold: 2000.megabytes
      #}
    )
    MAXIMUM_UPLOAD_PARTS_COUNT = 10000
    MINIMUM_UPLOAD_PART_SIZE = 10 * 1024 * 1024 # don't have access to 5.megabytes
    io = File.open("/tmp/2g_file")
    part_size = [io.size.fdiv(MAXIMUM_UPLOAD_PARTS_COUNT).ceil, MINIMUM_UPLOAD_PART_SIZE].max
    puts part_size
    o.upload_stream(part_size: part_size, thread_count: 1) do |out|
      IO.copy_stream(io, out)
    end
  end

**Comment by lphm** [comment]
> This may be a long shot, but are you using IO anywhere in your app? `sendfile` is a system command. Perhaps IO needs to be flushed somewhere somehow?

My test code is just a rake task, so no :

desc "test big file"
  task test: :environment do

    o = Aws::S3::Object.new(
      bucket_name: 'test-remote-backup',
      key: 'large-file',
      region: 'eu-west-3',
      access_key_id: Rails.application.credentials.dig(:aws, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:aws, :secret_access_key),
      http_wire_trace: true,
      #upload:{
      #  multipart_threshold: 2000.megabytes
      #}
    )
    MAXIMUM_UPLOAD_PARTS_COUNT = 10000
    MINIMUM_UPLOAD_PART_SIZE = 10 * 1024 * 1024 # don't have access to 5.megabytes
    io = File.open("/tmp/2g_file")
    part_size = [io.size.fdiv(MAXIMUM_UPLOAD_PARTS_COUNT).ceil, MINIMUM_UPLOAD_PART_SIZE].max
    puts part_size
    o.upload_stream(part_size: part_size, thread_count: 1) do |out|
      IO.copy_stream(io, out)
    end
  end

**Comment by lphm** [comment]
> This is a very weird edge case. I don't see any failures in the log file. Maybe threading is an issue? Could you also try changing the thread count to 1?

No changes...
Is it as :
   .... o.upload_stream(part_size: part_size, thread_count: 1) do |out| ....

**Comment by mullermp** [comment]
I think the issue is in [`copy_stream`](https://ruby-doc.org/core-2.6.3/IO.html#method-c-copy_stream) which uses `sendfile`. It states "Specialized mechanisms, such as sendfile system call, may be used on appropriate situation." Rails will use copy_stream for multipart uploads, which we are recreating here in your rake task.

**Comment by mullermp** [comment]
I think we're approaching Ruby stdlib territory here. The [man page for sendfile](https://man7.org/linux/man-pages/man2/sendfile.2.html) suggests that maybe the error is `EOVERFLOW`

**Comment by mullermp** [comment]
This is probably wacky, but have you tried using a different host?

**Comment by lphm** [comment]
No, I can't, too complicated for me. And on my development host, I'm behing on a slow Internet connection.
Maybe you think the problem is on Ruby stdlib ?

**Comment by lphm** [comment]
I test with another S3 like service (IBM cloud storage) and I have same error for big files.
Aws::S3::MultipartUploadError: multipart upload failed: File too large - sendfile

**Comment by mullermp** [comment]
Yeah. I think the usage of `copy_stream` is the problem for you. Both myself and a co-worker cannot reproduce your issue. I am thinking it might be OS/host related because it is failing on what appears to be the `sendfile` system call. Rails is using `copy_stream` for multipart uploads, so there is no avoiding it. I am willing to bet that if you try using the normal `upload_file` command, it will work for you. Try doing:

```
o = Aws::S3::Object.new(...)
o.upload_file('/tmp/2g_file')
```

**Comment by mullermp** [comment]
Just checking in, were you able to diagnose this? I am sorry that we couldn't find the root cause, but I don't believe this to be an SDK issue, it appears to be Ruby's (and then Rails) use of `copy_stream` (sendfile) on your machine.

**Comment by lphm** [comment]
Sorry for response delay. I have made another test with IBM cloud storage and all is right : no error appears with multipart_threshold: <%= 1000.megabytes %>. I think Amazon has a limitation...

**Comment by mullermp** [comment]
There are limitations to multipart upload, documented here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html but none of these apply in this case..

**Comment by mullermp** [comment]
Did you try the `upload_file` method above?

**Comment by lphm** [comment]
no I did'nt try this. But I switch finally to IBM CS. So ticket can be closed for me.
