### ISSUE TITLE
Support for S3:UploadPart presigned URL

### ISSUE THREAD

**Issue by josegomezr** [aws/aws-sdk-ruby#2511]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement multipart uploads on rails using direct storage. However I've found it very difficult to sign the `S3:UploadPart` URL endpoints. I can get `S3:PutObject` signed urls, but if I try the same method aka:

```
# obj is an S3::Object
> obj.presigned_url(:upload_part)
ArgumentError (unknown operation "upload_part_object")
```

**Describe the solution you'd like**
Can the `S3::Object` class expose `Aws::S3::Presigner#presigned_request` so I can pass `upload_part` and get signed urls for multipart?

Or Maybe support for `upload_part` for `S3::Object#presigned_url` method.

**Describe alternatives you've considered**
As a quick patch for my experiments, I've injected this in my WIP code (shamelessly copying it from `presigner.rb`):

```ruby
module Aws
  module S3
    class Object
      def presigned_request(http_method, params = {})
        presigner = Presigner.new(client: client)
        presigner.presigned_request(
          http_method,
          params.merge(bucket: bucket_name, key: key)
        )
      end
    end
  end
end
```

and made it work, but it doesn't feel right to be monkeypatching classes around ;)

- [x] :wave: I may be able to implement this feature request

**Additional context**

**Comment by mullermp** [comment]
Thanks for opening an issue. The Resource models contain many issues and aren't really maintained much - There are many, many instances of monkey patching for S3 resource models in the SDK. We're open to pull requests. However, you should be able to do this easily by constructing a `Presigner` object directly and avoiding resource models entirely (recommended).

```
presigner = Aws::S3::Presigner.new(client: obj.client) # you can get the client from a resource model, or pass your own
presigner.presigned_url(:upload_part, ... params ... )
```

**Comment by josegomezr** [comment]
I'll follow your advice!

Thanks for the reply!

**Comment by mullermp** [comment]
No problem. Please re-open if there is concern or if you wish to open a PR.

**Comment by josegomezr** [comment]
I've made a small PR for this case, thought it was gonna be more complicated 😅
