### ISSUE TITLE
FATAL: Seahorse::Client::NetworkingError: execution expired  -  aws sdk secrets manager

### ISSUE THREAD

**Issue by prat23k** [aws/aws-sdk-ruby#2516]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

I am trying to access the secrets manager from the cross account i got the following issue

**Gem name : 'aws-sdk-secretsmanager'
Version:   aws-sdk-secretsmanager-1.46.0

**Version of Ruby, OS environment**
chef_version=16.4.41
  platform=redhat
  platform_version=7.9
  ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
  program_name=/bin/chef-client
  executable=/opt/chef/bin/chef-client

**To Reproduce (observed behavior)**
Steps to reproduce the behavior 👍 
1. Trying to access secrets manager from the cross accounts using instance profile
region_name = 'eu-west-1'
secret_name_test ='xxxx'
   22:  client = Aws::SecretsManager::Client.new(
   23:   region: region_name,
   24:    credentials: Aws:: InstanceProfileCredentials.new()
   25:  )
   26:
   27>> resp = client.get_secret_value(secret_id: secret_name_test)

**Expected behavior**
Able to fetch secrets string without any isssues

Actual behaviour:

 FATAL: Seahorse::Client::NetworkingError: execution expired

**Comment by mullermp** [comment]
Thanks for opening an issue. Can you try passing `http_wire_trace: true` option to your Client and share the network logs?
