### ISSUE TITLE
iam list_user_tags

### ISSUE THREAD

**Issue by flah00** [aws/aws-sdk-ruby#2522]
I am unable to successfully iterate over user tags, when using max_items

## Successful call

I see all of the tags associated with my user (in my case it's 4)

`iam.list_user_tags(user_name: 'u').tags.count == 4`

## Unexpected results

When I try using the enumerator I only get one user back. Using this same idiom with list_users works as expected.

`iam.list_user_tags(max_items: 1, user_name: 'u').map{|r| r.tags}.flatten.count == 4`

This assertion fails for me

## Expected 

I would've expected the count to be the same as the un-enumerated output

## Gems

```
$ bundle show | grep aws
  * aws-eventstream (1.1.1)
  * aws-partitions (1.456.0)
  * aws-sdk-core (3.114.0)
  * aws-sdk-ec2 (1.114.0)
  * aws-sdk-iam (1.52.0)
  * aws-sigv4 (1.2.3)
```

## Gem env

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-darwin20]
  - INSTALLATION DIRECTORY: /Users/pc/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/pc/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/pc/.rbenv/versions/2.6.6/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/pc/.rbenv/versions/2.6.6/bin
  - SPEC CACHE DIRECTORY: /Users/pc/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/pc/.rbenv/versions/2.6.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-20
  - GEM PATHS:
     - /Users/pc/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
     - /Users/pc/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
```

## OS

```
$ uname -a
Darwin host 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

**Comment by mullermp** [comment]
Hey there, I'm not sure exactly what issue you are having. `max_items` will give you 1 tag. `iam.list_user_tags(max_items: 1, user_name: 'u').map{|r| r.tags}.flatten.count` should give you 1 tag, not 4.

I am also not sure why you are mapping the tags to a new array and then flattening it. `iam.list_user_tags(user_name: 'u').tags` should give you a list of Tag structures.

**Comment by flah00** [comment]
My intention is to simulate paging, by controlling `max_items`. My understanding is that using an `Enumerator` on a response allows code to read all paginated data. So, when I `map` a response from `list_user_tags`, I should be retrieving all available data, not just 1 tag.

A paginated response would return a 2 dimensional array. I am flattening the results because I don't care about the dimensionality of the response. This allows me to iterate over all paginated objects more simply.

In the following examples I'll skip `flatten`.

When I simulate paging for `list_users`, I get the results I would expect, ie

```
> i=Aws::IAM::Client.new
> i.list_users(max_items: 1).map{|r| r.users}.count
=> 66
> i.list_users().users.count
=> 66
```

This is not the case for user tags, ie

```
> i=Aws::IAM::Client.new
> i.list_user_tags(user_name: 'u').tags.count
2
> i.list_user_tags(max_items: 1, user_name: 'u').map{|r| r.tags}.count
1
```

This seems to be because the enumerator for user tags has a bug. Unless I'm misunderstanding something? 

```
> i.list_user_tags user_name: 'u'
=> #<struct Aws::IAM::Types::ListUserTagsResponse
 tags=
  [#<struct Aws::IAM::Types::Tag key="tag1", value="value1">,
   #<struct Aws::IAM::Types::Tag key="tag2", value="value2">],
 is_truncated=false,
 marker=nil>
> i.list_user_tags(max_items: 1, user_name: 'u').map{|r| r.tags}
=> [[#<struct Aws::IAM::Types::Tag key="tag1", value="value1">]]
```

**Comment by mullermp** [comment]
Interesting.. I think that `list_user_tags` is working as expected but `list_users` is not. Enumerable responses have [redefined unsafe methods](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/pageable_response.rb#L144) such as `count` so that it only counts the data returned, it prevents N API calls. If you enable `http_wire_trace: true` in your Client, I would assume that you are doing 66 calls to IAM. For `list_users` I would expect `count` to return 1.

**Comment by mullermp** [comment]
I agree something fishy is going on here. I'm taking a closer look.

**Comment by mullermp** [comment]
I think I see the problem. `resp = list_user_tags(max_items: 1)` will return a response with `is_truncated=true` but `resp.next_page?` returns false. For `list_users`, `resp.next_page?` correctly returns true, so pagination works as expected.

**Comment by mullermp** [comment]
aaaaand here's the problem. `list_user_tags` is not modeled as a paginated API. https://github.com/aws/aws-sdk-ruby/blob/bd0bda64c02566b313785e906b7c402896b95ffd/gems/aws-sdk-iam/lib/aws-sdk-iam/client_api.rb#L3452-L3476

This would affect all SDKs not just Ruby. I'm surprised this went unreported, then again, with `max_items` defaulting to 100, I seriously doubt there are users with over 100 tags on them.

**Comment by flah00** [comment]
I agree, 100+ user tags is an edge case

I'm writing a script in which I assume the admins creating crazy users ... and wanted to verify my pagination assumptions... so here we are : )

**Comment by mullermp** [comment]
The pagination change would be:
```
    "ListUserTags": {
      "input_token": "Marker",
      "limit_key": "MaxItems",
      "more_results": "IsTruncated",
      "output_token": "Marker",
      "result_key": "Tags"
    },
```

I verified that `iam.list_user_tags(user_name: user_name, max_items: '1').map.count` returns 2 tags (expected).

**Comment by mullermp** [comment]
To fix this, IAM needs to do a service release. It may take a while to round up the service team to prepare that. I've drafted a code review internally. In the mean time, it's probably best not to use `max_items` of 1..

**Comment by flah00** [comment]
> It may take a while to round up the service team

👍 

> it's probably best not to use max_items of 1

agreed, max_items 1 was only for testing, my script lets default max_items do its thing

**Comment by mullermp** [comment]
I've gotten the changes merged upstream and a release is staged for tomorrow.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/blob/9abf2be62392139e4442e8d52b317529a78e93be/gems/aws-sdk-iam/lib/aws-sdk-iam/client_api.rb#L3460-L3466

**Comment by mullermp** [comment]
It should work now. Re-open if there's still concern.
