### ISSUE TITLE
Issue updating gem aws-partitions on Ubuntu 18.04

### ISSUE THREAD

**Issue by jhundley9109** [aws/aws-sdk-ruby#2525]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution

Running a "gem update" fails on aws-partitions since May 17th, 2021 

The output is:
Updating installed gems
Updating aws-partitions
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 4, expected 1)

ruby -v produces:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

gem -v produces:
2.7.6

gem list produces this version that was properly installed on May 14th
aws-partitions (1.456.0)

lsb_release -a produces:
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by mullermp** [comment]
This is a strange error. On my machine (MacOS) `gem update` runs just fine. Is this problem actually limited to "aws-partitions" or is it because it happens to be the first gem to be updated? Perhaps try updating your rubygems version to the latest 3.2.17.

**Comment by jhundley9109** [comment]
Thank you for the feedback, as I dig into this a little deeper it does appear to be a general error with ruby gems being able to update, it just so happened this gem was the first in the list to attempt to be updated. I'll have to figure out what broke the ruby installation here.

Thanks!
