### ISSUE TITLE
content type is not set when upload files .ics

### ISSUE THREAD

**Issue by WoLkErSs** [aws/aws-sdk-ruby#2528]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Medata does not set `content-type` for ics format after upload by Aws::S3::Object or Aws::S3::Resource.new

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
 - gem 'aws-sdk-s3', '~> 1.90'

**Version of Ruby, OS environment**
- ruby 2.7.2
- ubuntu 18.04

**To Reproduce (observed behavior)**
s3obj = Aws::S3::Object.new("backet_name", 'test.ics', client: Aws::S3::Client.new(etc))
s3obj.upload_file('test.ics', acl: 'public-read')

![Снимок экрана от 2021-06-03 01-11-01](https://user-images.githubusercontent.com/37914720/120558754-9d228600-c408-11eb-9256-4a26f7248a49.png)

**Expected behavior**
content-type have to be set automatic
![Снимок экрана от 2021-06-03 01-11-49](https://user-images.githubusercontent.com/37914720/120558914-d824b980-c408-11eb-8eab-633feff1cb94.png)

**Comment by mullermp** [comment]
Thanks for opening an issue. The `Content-Type` is not automatically determined for the object. When uploading the file, use the `content_type` param to set it to what you expect (`text/calendar`).

**Comment by WoLkErSs** [comment]
Thanks!
