### ISSUE TITLE
LexModelsV2: Implement Waiters

### ISSUE THREAD

**Issue by jessedoyle** [aws/aws-sdk-ruby#2530]
**Is your feature request related to a problem? Please describe.**
Some Lex V2 API calls return a `bot_status` field that may be one of a number of different enumeration values (i.e. `Creating`, `Available`, etc.). See [1].

**Describe the solution you'd like**
It would be great if waiters were defined for the LexModelsV2 APIs that return a status field so that the calls may be treated in a synchronous manner.

**Describe alternatives you've considered**
I imagine the implementation of this request requires a change to the [API definition files](https://github.com/aws/aws-sdk-ruby/tree/version-3/apis). How are these files generated? And is that process open-source? I'd be happy to attempt a contribution if so!

It looks like all the AWS SDKs use similar definition files, it would be great if waiters could be defined in a single location for all the SDKs.

- [x] :wave: I may be able to implement this feature request

**Additional context**
[1]: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/LexModelsV2/Client.html#create_bot-instance_method

**Comment by mullermp** [comment]
Thanks for opening a feature request. Those API definition files come from an upstream source internally. If you want to implement those waiters JSON definitions, you can share them with me here, and I can commit them upstream. You can code generate the waiters in the Ruby SDK by making a `waiters-2.json` file with the definitions, and run `rake build:aws-sdk-lexmodelsv2` in aws-sdk-ruby/ root. That should let you test the waiters. Also let me know how you are testing them so I could help verify them. I will also get someone from the service team to sign off on it.

**Comment by mullermp** [comment]
EC2 has similar waiters that work based on a status, you can use it as inspiration.

**Comment by jessedoyle** [comment]
Thanks @mullermp! I'll give it a shot!

**Comment by mullermp** [comment]
Waiters have been shipped!

https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/models.lex.v2/2020-08-07/waiters-2.json
