### ISSUE TITLE
Unable to initialize client using profile that uses multiple levels of assume_role

### ISSUE THREAD

**Issue by tmccombs** [aws/aws-sdk-ruby#2531]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When I have a profile that has a source_profile that is itself a profile using source_profile and role_arn, then I can't create an EC2 client with that profile. Instead I get an exception about "undefined method `[]` for nil"

The full stack trace is as follows:

```
irb(main):003:0> Aws::EC2::Client.new(profile: 'utility', region: 'us-east-1')
Traceback (most recent call last):
       16: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:207:in `value_at'
       15: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
       14: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:59:in `each'
       13: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:59:in `each'
       12: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
       11: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/seahorse/client/configuration.rb:72:in `call'
       10: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/plugins/credentials_configuration.rb:70:in `block in <class:CredentialsConfiguration>'
        9: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
        8: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
        7: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
        6: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/credential_provider_chain.rb:72:in `static_profile_assume_role_credentials'
        5: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/credential_provider_chain.rb:172:in `assume_role_with_profile'
        4: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/shared_config.rb:117:in `assume_role_credentials_from_config'
        3: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/shared_config.rb:208:in `assume_role_from_profile'
        2: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/shared_config.rb:253:in `resolve_source_profile'
        1: from /var/lib/gems/2.7.0/gems/aws-sdk-core-3.114.1/lib/aws-sdk-core/shared_config.rb:277:in `assume_role_process_credentials_from_config'
NoMethodError (undefined method `[]' for nil:NilClass)
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-core: 3.114.1
aws-sdk-ec2: 1.240.0

although I think it would impact any service. 

**Version of Ruby, OS environment**
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**To Reproduce (observed behavior)**
Create an an ~/.aws/credentials file like:

```
[base]
aws_access_key_id = <ACCESS KEY>
aws_secret_access_key = <SECRET KEY>

[profile1]
source_profile = base
role_arn = <ROLE ARN 1>

[profile2]
source_profile = profile1
role_arn = <ROLE ARN 2>
```
then run `Aws::EC2::Client.new(profile: 'profile2', region: 'us-east-1')

**Expected behavior**
It should be able to initialize the EC2 client without throwing an unhelpful error.

**Additional context**
It appears that `@parsed_config` is never set (because the `config_enabled` option isn't set to true).

**Comment by mullermp** [comment]
Thanks for reporting this. I think this is indeed a bug. My understanding is that it should be chaining.

**Comment by mullermp** [comment]
To clarify some findings - this is not truly a bug, but the assume role chaining feature just seems to be missing. Other SDKs do support this behavior and we do not. The proposed set of changes for SDKs date back to 2017. I took at the look at the scope of work and it's not a simple feature to add. We will work on implementing this. In the mean time, a work around is to use only one layer source profile (use profile1) if possible.

**Comment by tmccombs** [comment]
It seems like it is at least a bug that the error doesn't give an indication of what the actual problem is. Although I'm not sure how difficult it would be to add better diagnostics.

Unfortunately in my case, a single layer doesn't work, as the different levels are all in different accounts. I was able to sort of  work around  it by using multiple AssumeRoleCredentials.
