### ISSUE TITLE
[aws-sdk-personalize] `Types::DescribeFilterResponse#filter` unexpected return value

### ISSUE THREAD

**Issue by ytkg** [aws/aws-sdk-ruby#2534]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
Hi.
Is this intentional?
```ruby
client = Aws::Personalize::Client.new(region: 'ap-northeast-1')

describe_filter_response = client.describe_filter(filter_arn: 'masked value')
#=> #<struct Aws::Personalize::Types::DescribeFilterResponse
 filter=
  #<struct Aws::Personalize::Types::Filter
   name="exclude-effectived-filter",
   filter_arn="masked value",
   creation_date_time=2021-06-08 20:00:30 47317/131072 +0900,
   last_updated_date_time=2021-06-08 20:01:01 231211/262144 +0900,
   dataset_group_arn="masked value",
   failure_reason=nil,
   filter_expression="EXCLUDE ItemID WHERE Interactions.event_type IN (\"effectived\")",
   status="ACTIVE">>

describe_filter_response.filter
#=> #<Enumerator: ...>
```

```ruby
# I expected:

#=> #<struct Aws::Personalize::Types::Filter
 name="exclude-effectived-filter",
 filter_arn="masked value",
 creation_date_time=2021-06-08 20:32:35 2302673/4194304 +0900,
 last_updated_date_time=2021-06-08 20:33:11 1639973/2097152 +0900,
 dataset_group_arn="masked value",
 failure_reason=nil,
 filter_expression="EXCLUDE ItemID WHERE Interactions.event_type IN (\"effectived\")",
 status="ACTIVE">
```

**Version**
- Ruby: 2.7.2
- aws-sdk-personalize: 1.26.0

**Comment by alextwoods** [comment]
Thanks for filing this - I believe this is a name conflict between the enumerable methods that get added by [PageableResponse](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/pageable_response.rb) (which include `filter`) and the delegation we do in the [Response](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/response.rb#L7).

I'll look into how we can solve this, but in the meantime you can use either `resp[:filter]` or `resp.data.filter`.

**Comment by ytkg** [comment]
Thanks!

**Comment by alextwoods** [comment]
Unfortunately, we aren't able to resolve this naming conflict without making a breaking change as users rely on both the delegation and the PageableResponse (Enumerable) methods that are added on all responses.  I've opened a PR to at least address the documentation for these methods: #2535
