### ISSUE TITLE
AWS S3 GetBucketLocation XML Parser Fails with Stubbed Responses

### ISSUE THREAD

**Issue by agrare** [aws/aws-sdk-ruby#2536]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When using stubbed responses for get_bucket_location location_constraint the XML parsing fails to correctly parse the region.

`aws-sdk-s3` version `1.96.0`
`aws-sdk-core` version `3.114.2`

This issue was introduced in `aws-sdk-core` version `3.114.1` with https://github.com/aws/aws-sdk-ruby/pull/2527

**Version of Ruby, OS environment**
```
$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux-gnu]
```

**To Reproduce (observed behavior)**
```
>> require 'aws-sdk-s3'
=> true
>> Aws.config[:s3] = {stub_responses: {get_bucket_location: {location_constraint: "us-east-1"}}}
=> {:stub_responses=>{:get_bucket_location=>{:location_constraint=>"us-east...
>> Aws::S3::Client.new.get_bucket_location(:bucket => "test")
=> #<struct Aws::S3::Types::GetBucketLocationOutput location_constraint="<LocationConstraint>us-east-1">
>> Aws::S3::Client.new.get_bucket_location(:bucket => "test").location_constraint
=> "<LocationConstraint>us-east-1"
```

**Expected behavior**
`get_bucket_location(bucket: "test").location_constraint` should return `"us-east-1"` not `"<LocationConstraint>us-east-1"`

**Additional Context**
Reverting https://github.com/aws/aws-sdk-ruby/pull/2527 or updating the regex [here](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/get_bucket_location_fix.rb#L14) both resolve the issue.

**Comment by mullermp** [comment]
Thanks for reporting this. This does look like broken behavior.
