### ISSUE TITLE
Seahorse::Client::H2::Connection#connect appears to assume TLS without checking endpoint URI for scheme

### ISSUE THREAD

**Issue by aarontc** [aws/aws-sdk-ruby#2542]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
While developing integration tests using localstack, which must either use non-TLS connections or be able to trust self-signed TLS certificates, I encountered difficulty using an async Kinesis client with a non-TLS (http://localstack:4566) endpoint URI.

I believe the source of the problem is within the Seahorse::Client::H2::Connection#connect method, where an OpenSSL socket is instantiated regardless of the scheme used by the endpoint.

https://github.com/aws/aws-sdk-ruby/blob/38453eae14cf83848accf64688c744772ddca5d0/gems/aws-sdk-core/lib/seahorse/client/h2/connection.rb#L83

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-core` version 3.114.0

**Version of Ruby, OS environment**
`ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]`

**To Reproduce (observed behavior)**
```ruby
require 'aws-sdk-kinesis'
c = Aws::Kinesis::AsyncClient.new(endpoint: 'http://localhost:4566')
c.subscribe_to_shard(...)
```
Observe debug messages including `starting TLS for localhost:4566 ...` followed by error message `Seahorse::Client::NetworkingError SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)` as the SDK is attempting to use TLS for a plaintext endpoint.

**Expected behavior**
Seahorse::Client::H2::Connection#connect should inspect `endpoint.scheme` to determine if TLS is in use, and assign `@socket` appropriately instead of assuming TLS unconditionally.

**Comment by alextwoods** [comment]
Thanks for submitting this and for the clear description/reproduction steps - I was able to reproduce this.  

I've put up a PR with a proposed fix: #2543 which I believe is reasonable, but need to further test it. 

An alternative approach could be to expose the `ssl_verify_peer` option as config on the `AsyncClient` - I've tested with that set to false with localstack and appears to work as well, but feels more like a hack.
