### ISSUE TITLE
Cannot copy S3 objects with UTF-8 keys

### ISSUE THREAD

**Issue by CliveMillerTR** [aws/aws-sdk-ruby#2545]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I can perform a `head_object` on an object whose key name contains UTF-8 characters, but when I try to `copy_object` and the `copy_source` has a UTF-8 character, the HTTP request encoding is incorrect and it fails with `404 Not Found Aws::S3::Errors::NoSuchKey`

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
Using aws-sdk-s3 1.95.1

**Version of Ruby, OS environment**
ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-linux]

**To Reproduce (observed behavior)**
* Create an object with a key name containing a UTF-8 character
* Try to copy that object using it as a source_object

**Expected behavior**
The object should be copied

**Screenshots**
```
irb(main):020:0> fn1
=> "1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKSTÄTTE_13h38.mp4"

irb(main):033:0> client.head_object(bucket: s3.archive_bucket_name, key: fn1)
opening connection to prod-editorial-video-archive.s3.eu-west-1.amazonaws.com:443...
opened
starting SSL for prod-editorial-video-archive.s3.eu-west-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "HEAD /1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST%C3%84TTE_13h38.mp4 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.114.0 ruby/2.6.7 x86_64-linux aws-sdk-s3/1.95.1\r\nHost: prod-editorial-video-archive.s3.eu-west-1.amazonaws.com\r\nX-Amz-Date: 20210624T075257Z\r\nX-Amz-Content-Sha256: ...\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amz-id-2: ...\r\n"
-> "x-amz-request-id: ...\r\n"
-> "Date: Thu, 24 Jun 2021 07:53:17 GMT\r\n"
-> "Last-Modified: Mon, 02 Dec 2019 13:41:55 GMT\r\n"
-> "ETag: \"d1c1148ecfa787df00d1716d4beaa831-23\"\r\n"
-> "x-amz-storage-class: STANDARD_IA\r\n"
-> "Accept-Ranges: bytes\r\n"
-> "Content-Type: video/mp4\r\n"
-> "Content-Length: 473428489\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
Conn keep-alive
=> #<struct Aws::S3::Types::HeadObjectOutput delete_marker=nil, accept_ranges="bytes", expiration=nil, restore=nil, archive_status=nil, last_modified=2019-12-02 13:41:55 +0000, content_length=473428489, etag="\"d1c1148ecfa787df00d1716d4beaa831-23\"", missing_meta=nil, version_id=nil, cache_control=nil, content_disposition=nil, content_encoding=nil, content_language=nil, content_type="video/mp4", expires=nil, expires_string=nil, website_redirect_location=nil, server_side_encryption=nil, metadata={}, sse_customer_algorithm=nil, sse_customer_key_md5=nil, ssekms_key_id=nil, bucket_key_enabled=nil, storage_class="STANDARD_IA", request_charged=nil, replication_status=nil, parts_count=nil, object_lock_mode=nil, object_lock_retain_until_date=nil, object_lock_legal_hold_status=nil>

irb(main):034:0> client.copy_object(bucket: s3.archive_bucket_name, copy_source: "/#{s3.archive_bucket_name}/#{fn1}", key: "#{OUTGOING_PREFIX}#{fn1}", storage_class: 'STANDARD_IA')
opening connection to prod-editorial-video-archive.s3.eu-west-1.amazonaws.com:443...
opened
starting SSL for prod-editorial-video-archive.s3.eu-west-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "PUT /berlin_orig/1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST%C3%84TTE_13h38.mp4 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.114.0 ruby/2.6.7 x86_64-linux aws-sdk-s3/1.95.1\r\nX-Amz-Copy-Source: /prod-editorial-video-archive/1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST\u00C4TTE_13h38.mp4\r\nX-Amz-Storage-Class: STANDARD_IA\r\nHost: prod-editorial-video-archive.s3.eu-west-1.amazonaws.com\r\nX-Amz-Date: 20210624T075331Z\r\nX-Amz-Content-Sha256: ...\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 404 Not Found\r\n"
-> "x-amz-request-id: ...\r\n"
-> "x-amz-id-2: ...\r\n"
-> "Content-Type: application/xml\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Date: Thu, 24 Jun 2021 07:53:49 GMT\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
-> "12a\r\n"
reading 298 bytes...
-> "<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST??TTE_13h38.mp4</Key><RequestId>8TDH8X538ZARJHCH</RequestId><HostId>9AMETCUcvM/6mZ32EWRGQ9Q85bV4D+ex6J0Jgfpt7k4C8CJJBwJ8MdBKR81aPc31ipF0FeDkETM=</HostId></Error>"
read 298 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn keep-alive
Traceback (most recent call last):
        1: from (irb):34
Aws::S3::Errors::NoSuchKey (The specified key does not exist.)
```

**Additional context**
As can be seen above, 
`1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKSTÄTTE_13h38.mp4` is correctly encoded as 
`1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST%C3%84TTE_13h38.mp4` in the first line of the HTTP message, but incorrectly encoded as 
`1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST\u00C4TTE_13h38.mp4` in the `X-Amz-Copy-Source` header.

**Comment by CliveMillerTR** [comment]
![Screenshot 2021-06-24 092203](https://user-images.githubusercontent.com/58516624/123228890-baa9b380-d4cd-11eb-9ec6-6cb9d94ab2c1.png)

**Comment by CliveMillerTR** [comment]
Updated to latest version, `1.96.1` and the problem remains.

**Comment by mullermp** [comment]
Thanks for opening this. I think you're right that this is a bug. The [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestParameters) say that `x-amz-copy-source` should be URL encoded, and it seems in this case it is not.

**Comment by mullermp** [comment]
Thanks for opening an issue. At first I thought this was a bug, but it's actually intended behavior. As far as I'm aware, HTTP headers do not support UTF-8. The [S3 API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestParameters) and the [Ruby SDK docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#copy_object-instance_method) say that the `copy_source` value "must be URL encoded". You should use `CGI.escape()` on your `copy_source` parameter. I verified that it does work in this case.

**Comment by CliveMillerTR** [comment]
Hi Matt,
Thank you so much for looking into this. Yes, of course, you're absolutely right. I've inserted `CGI.escape()` and my request now looks correct:
```
<- "PUT /1059/1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST%C3%84TTE_13h38.mp4 HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.115.0 ruby/2.6.7 x86_64-linux aws-sdk-s3/1.96.1\r\nX-Amz-Copy-Source: %2Fprod-editorial-video-archive%2Fberlin_fixed%2F1059%2F1059_2019-12-02_HD_Berlin-DEUTSCHLAND-GEDENKST%C3%84TTE_13h38.mp4\r\nX-Amz-Storage-Class: STANDARD_IA\r\nHost: prod-editorial-video-archive.s3.eu-west-1.amazonaws.com\r\nX-Amz-Date: 20210625T081519Z\r\nX-Amz-Content-Sha256: ...\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
```
and has worked as expected.
