### ISSUE TITLE
How to tell within which regions a service is available

### ISSUE THREAD

**Issue by ag-TJNII** [aws/aws-sdk-ruby#2548]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

For a given service I need to know which regions the service is available in.  For example, some services like AlexaForBusiness are only available in a very small number of regions.  In the [Java SDK docs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html#region-selection-query-service) they mention a `.serviceMetadata().regions()` call which will return the available regions for the service.  I'm unable to find a corresponding API in the Ruby SDK.  Does it exist?

**Comment by alextwoods** [comment]
We don't have a higher level abstraction for accessing the regions that a service is available in.  However, AWS Systems Manager allows you to query for that (along with a lot of other related queries), see:  [some example SSM Queries](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/).

Here is some example Ruby code to get all of the regions for Athena:

```ruby
service = 'athena'
ssm = Aws::SSM::Client.new
regions = []
# get_parameters_by_path is paginated, so loop through all of the pages and collect the regions
ssm.get_parameters_by_path(path: "/aws/service/global-infrastructure/services/#{service}/regions").each do |page|
  page.parameters.each do |p|
    regions << p.value
  end
end

# regions will now be: ["ap-northeast-1", "ap-south-1", "ap-southeast-1", "cn-north-1", "eu-north-1", "eu-south-1", "us-east-1", "us-east-2", "us-gov-east-1", "us-west-2", "af-south-1", "ap-east-1", "ap-northeast-2", "ap-southeast-2", "ca-central-1", "cn-northwest-1", "eu-central-1", "eu-west-3", "us-gov-west-1", "us-west-1", "eu-west-1", "eu-west-2", "me-south-1", "sa-east-1"]
```

**Comment by mullermp** [comment]
You can use `aws-partitions` to select a region and enumerate available regions: https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-partitions/lib/aws-partitions.rb#L85-L101
