### ISSUE TITLE
ArgumentError (invalid configuration option `:dynamodb') thrown when using custom DynamoDB endpoint

### ISSUE THREAD

**Issue by spachari-im** [aws/aws-sdk-ruby#2554]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
ArgumentError (invalid configuration option `:dynamodb') error is thrown when using AWS SDK with a custom endpoint for DynamoDB.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
From Gemfile.lock
```
aws-sdk (~> 3)
aws-sdk-s3 (~> 1)
aws-sdk-dynamodb (1.60.0)
```

**Version of Ruby, OS environment**
ruby 2.5.3p105 (2018-10-18 revision 65156)

**To Reproduce (observed behavior)**
Start Docker instances of S3, SQS and DynamoDB for testing. In the Ruby app set the custom Dynamo DB, S3 and SQS endpoint like this:
```
Aws.config.update({:s3 => {
  :endpoint => 'http://localhost:41001', :force_path_style => true
}}) 

Aws.config.update({:sqs => {
  :endpoint =>'http://localhost:41002'
}}) 
Aws.config.update({:dynamodb => {
  :endpoint => 'http://localhost:41000'
}}) 
```

Then when calling a S3 operation, I see the error.
```
F, [2021-07-09T18:48:15.195773 #13176] FATAL -- :   
F, [2021-07-09T18:48:15.195924 #13176] FATAL -- : ArgumentError (invalid configuration option `:dynamodb'):
F, [2021-07-09T18:48:15.196004 #13176] FATAL -- : 
```

**Expected behavior**
This error should not happen. The custom DynamoDB configuration (endpoint) should be accepted.

**Screenshots**

**Additional context**

**Comment by mullermp** [comment]
Thanks for reporting this issue. This seems like a regression from V2. Because V3 is modularized, there is not a good way to get all of the possible service names.

You should be able to pass these endpoints/configuration directly into the Client constructor. This is preferable to global state. Are you able to do this?

**Comment by mullermp** [comment]
After some investigation, this IS supported, however, services must be loaded/required before using `Aws.config[identifier]`. If you must use global configuration, ensure that S3, SQS, and DynamoDB gems are loaded and required. Otherwise, configure your clients on construction.

**Comment by alextwoods** [comment]
Just to expand a little on @mullermp's answer:

In general we recommend NOT doing this - avoid global configuration and configure your clients on construction (or if you need some sort of application configuration with a different lifecycle, we'd recommend managing that yourself).

But, as @mullermp  mentioned - If you MUST use the Aws.config for service configuration, ensure that ALL services you have configured have been loaded/required first.  If you are using the `aws-sdk-resources` gem, it lazy loads service clients and you'll need to explicitly load them first.

**Comment by spachari-im** [comment]
@mullermp  @alextwoods 

I want to proceed with global configuration for now (to avoid extensive code changes). Can you please give an example of explicitly loading the Clients?

I tried loading the gems like this in the script before configuring the custom URL:  

```
require 'aws-sdk'
require 'aws-sdk-dynamodb'
require 'aws-sdk-s3'
```

This fixed the 'dynamo' issue.

Is this the best way to load them?

**Comment by mullermp** [comment]
Other than `aws-sdk` yes that appears correct. Load the service gems `aws-sdk-sqs` etc.

For client construction, it is easy:
```
Aws::SQS::Client.new(endpoint: 'http://localhost:41002')
```
