### ISSUE TITLE
aws-sdk-s3 fails when downloading file of exactly 5242881 bytes from S3 bucket

### ISSUE THREAD

**Issue by RemcodM** [aws/aws-sdk-ruby#2561]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When obtaining an object of exactly 5242881 bytes from an S3 bucket, the download will fail with the error `Aws::S3::Errors::InvalidRange: The requested range is not satisfiable`.

Gem: **`aws-sdk-s3` 1.96.1**

**Version of Ruby, OS environment**
```
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
```
But this is also reproducible under Linux with the same Ruby version and Gem version.

**To Reproduce (observed behavior)**
 1. Upload a file of exactly 5242881 bytes to an S3 bucket.
 2. Using the gem, build and S3 object and download the file:
 ```
s3_obj = s3_bucket.object(object_name)
s3_obj.download_file(path)
```
 3. See the error.

**Expected behavior**
I expect the S3 Gem to be able to download the file completely.

**Additional context**
I did some debugging and it seems related to how the request for a file download is processed by the gem. By default, the gem will try to download the file in multiple ranges simultaneously for a fast download, however, the chunks the file is devided into seem a bit odd:
```
["bytes=0-5242880", "bytes=5242881-5242881"]
```
In other words, the first 5242880 bytes are downloaded as 1 part, and the final byte as a separate part. The calculation of these chunks happens in [file_downloader.rb](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb#L81):
```ruby
      def construct_chunks(file_size)
        offset = 0
        default_chunk_size = compute_chunk(file_size)
        chunks = []
        while offset <= file_size
          progress = offset + default_chunk_size
          chunks << "bytes=#{offset}-#{progress < file_size ? progress : file_size}"
          offset = progress + 1
        end
        chunks
      end
```
The `default_chunk_size` is set to `5242880` causing the function to return `["bytes=0-5242880", "bytes=5242881-5242881"]`.

The `default_chunk_size` is calculated by `compute_chunk` in [file_downloader.rb](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb#L93):
```
      def compute_chunk(file_size)
        if @chunk_size && @chunk_size > file_size
          raise ArgumentError, ":chunk_size shouldn't exceed total file size."
        else
          @chunk_size || [(file_size.to_f / MAX_PARTS).ceil, MIN_CHUNK_SIZE].max.to_i
        end
      end
```
In our scenario, `@chunk_size` equals `nil`, causing the `chunk_size` to be calculated using `[(file_size.to_f / MAX_PARTS).ceil, MIN_CHUNK_SIZE].max.to_i`. Since the file is 5242881 bytes and `MAX_PARTS` > 1, the `MIN_CHUNK_SIZE` is used, which is exactly 5242880 bytes.

The download eventually fails when doing the request for the last single byte, chunk `"bytes=5242881-5242881"`. This results in de S3 gem returning `The requested range is not satisfiable (Aws::S3::Errors::InvalidRange)`.

It seems that a single byte range is invalid, but since this is all calculated within the code of the gem, this seems to be a bug.

**Comment by mullermp** [comment]
Thanks for reporting this. We are working to get a fix.
