### ISSUE TITLE
Use of *ca-bundle.crt in code and impact of delelting it

### ISSUE THREAD

**Issue by aggarwalShivani** [aws/aws-sdk-ruby#2570]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**: How is the file ca-bundle.crt used in aws-skd-ruby gem on runtime? What is the impact if the file does not exist?

-  _Context_ -  I install td-agent (in docker) and that by default installs aws-sdk-ruby gem as well. The gem brings along a cert file **ca-bundle.crt** which is a bundle of 140+ well-known CAs. This cacert file gets read in  use_bundled_cert method in the code in [aws-sdk-core.rb](https://github.com/aws/aws-sdk-ruby/blob/a82c8981c95a8296ffb6269c3c06a4f551d87f7d/gems/aws-sdk-core/lib/aws-sdk-core.rb#L145)
  The method explains in comments that -  _# The SDK ships with a ca certificate bundle to use when verifying SSL peer certificates. By default, this cert bundle is *NOT* used. The SDK will rely on the default cert available to OpenSSL. This ensures the cert provided by your OS is used._

- Requirement - I have a security requirement that the docker image must not contain any default ssl certs or key files and so I intend to remove this particular ca-bundle.crt as well - /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.112.0/ca-bundle.crt.
- Query: What would be the impact of deleting this file? If the default ca cert bundle file doesn't exist, will it fail to use aws-sdk-core gem on runtime?

Any insights would be appreciated! Thanks.

**Comment by mullermp** [comment]
Thanks for opening an issue (sorry I didn't get to this sooner). The bundled cert is not used by default. I think it should be fine to delete it - it should not fail at runtime unless you call `Aws.use_bundled_cert!` anywhere in your code (or any applications that may call it).
