### ISSUE TITLE
Can no longer create RDS snapshot using argument "destination_region"

### ISSUE THREAD

**Issue by Faust85** [aws/aws-sdk-ruby#2571]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Upon upgrading to Ruby2.7 for all of our lambdas we began experiencing failures with our automated lambda deployments that were trying to create snapshots. See Sentry logs below:

![image](https://user-images.githubusercontent.com/15644727/129106728-b18b8035-82fc-407e-b544-8cdad5f60ca8.png)
![image](https://user-images.githubusercontent.com/15644727/129108277-30787819-62df-4d00-a9a5-47a7794ac60b.png)

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk

**Version of Ruby, OS environment**
![image](https://user-images.githubusercontent.com/15644727/129106853-5ddb5b68-772b-494b-9e1a-44c42fdec148.png)

**To Reproduce (observed behavior)**
```
require "aws-sdk-rds"
rds = Aws::RDS::Client.new(region: ${Region}, profile: ${ProfileForCreds})
rds.copy_db_cluster_snapshot({destination_region: "us-west-2", source_db_cluster_snapshot_identifier: ${db_snapshot}, target_db_cluster_snapshot_identifier: 'foo'})
```

**Expected behavior**
An RDS snapshot to be created and the function to exit successfully.

**Screenshots**

**Additional context**
Upon trying to replicate the issue locally, a slightly different error was thrown: `ArgumentError (unexpected value at params["destination_region"])`

This was tested with ruby versions 2.5.0, 2.6.0, 2.7.0, 2.7.2, 2.7.4 and the error message above was only encountered for the latter 2 versions with the rest exiting gracefully.

**Comment by mullermp** [comment]
Hey. Thanks for opening an issue. Just wondering why this was closed - what was the issue?
