### ISSUE TITLE
S3 upload_file integrity check

### ISSUE THREAD

**Issue by fcecagno** [aws/aws-sdk-ruby#2572]
The official docs mention that AWS will verify integrity of the file or part using `content_md5`. However, I couldn't find in the source code `content_md5` being passed on both modes, single part or multipart.
So my question is the following: should the developer using the SDK implement the integrity check and pass `content_md5`, or is it safe to rely on the SDK implementation of upload_file and don't use the integrity check provided by the API?
Thanks!

Reference: https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

**Comment by mullermp** [comment]
Thanks for opening an issue. The developer should not need to calculate MD5 unless you feel the need to do so. The SDK will calculate MD5 for all operations modeled with "httpChecksumRequired" in the API ([example](https://github.com/aws/aws-sdk-ruby/blob/9ea0b2b110b54ef65fba8ae02def383069484d29/apis/s3/2006-03-01/api-2.json#L682)). For S3, the SDK additionally will do "PutObject" and "UploadPart" ([plugin](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/md5s.rb)) and can be disabled with `compute_checksums` set to false.

**Comment by fcecagno** [comment]
Thank you very much for your information, I'm sure this information will help other developers in the future.
