### ISSUE TITLE
Use of DAX in rails application

### ISSUE THREAD

**Issue by deepakdash** [aws/aws-sdk-ruby#2579]
Hi there,

I want to use AWS DAX with DynamoDB in a Rails application. I have the aws-sdk installed. I found that the aws-sdk-dax is the ruby gem to be used for using the dax. However, I am not getting any document on using it inside the Rails application. Appritiate for your help.

**Comment by alextwoods** [comment]
The DAX team has unfortunately not provided a DynamoDB drop-in DAX client ([supported DAX clients](http://dax-sdk.s3-website-us-west-2.amazonaws.com)).  The AWS SDK For Ruby supports only the control plane operations for DAX (eg, create cluster).  This is a long standing feature request, see #1845.  I'll note this as a feature request and send the request to the service team.

**Comment by deepakdash** [comment]
> 
> 
> The DAX team has unfortunately not provided a DynamoDB drop-in DAX client ([supported DAX clients](http://dax-sdk.s3-website-us-west-2.amazonaws.com)). The AWS SDK For Ruby supports only the control plane operations for DAX (eg, create cluster). This is a long standing feature request, see #1845. I'll note this as a feature request and send the request to the service team.

Can we use other services like elastic search or redis with it?
