### ISSUE TITLE
Signature does not match when request has Content-Length header

### ISSUE THREAD

**Issue by phuongdh** [aws/aws-sdk-ruby#2581]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
`PUT` request to presigned URL returns 403 if including `Content-Length` header

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk (3.0.1)`

**Version of Ruby, OS environment**
```
RUBY_VERSION
=> "2.6.6"
[x86_64-linux-gnu]
```

**To Reproduce (observed behavior)**
I have an API Gateway integrated with S3 for uploading files.  I'm using the following code to generate a presigned URL
```
signer = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'us-west-2',
  # static credentials
  access_key_id: '<redacted>',
  secret_access_key: '<redacted>'
)

url = signer.presign_url(
  http_method: 'PUT',
  url: 'https://<app_id>.execute-api.us-west-2.amazonaws.com/<stage>/<bucket_name>/test.mp4',
)
```

The resulting `url` works in Postman (PUT) if I don't send a `Content-Length` header, but if I do, I got the following error: `The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been...`

**Expected behavior**
According to the [SDK doc](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#presign_url-instance_method) I expect the presigned URL to work with any non-Amazon header. In fact it does work if I send any other non-Amazon header, except for `Content-Length`.

**Screenshots**

**Additional context**

**Comment by mullermp** [comment]
Thanks for opening an issue. I am assuming you are adding headers like so: `signer.presign_url(... , headers: { 'Content-Length' => 123 })`

Could you describe your use case and what you are trying to do? I need more information to reproduce this.

In our S3 Presigner, `Content-Length` is considered an unsigned header. Could you try this?

```
signer = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'us-west-2',
  unsigned_headers: ['content-length'],
  # static credentials
  access_key_id: '<redacted>',
  secret_access_key: '<redacted>'
)
```

**Comment by phuongdh** [comment]
> Thanks for opening an issue. I am assuming you are adding headers like so: `signer.presign_url(... , headers: { 'Content-Length' => 123 })`
> 
> Could you describe your use case and what you are trying to do? I need more information to reproduce this.

Hi Matt, 

As seen in the code above, I don't add any header when generating the presigned URL. I'm only adding headers when making requests with Postman.

The use case workflow is:
1. Client asks us for an upload URL
2. We generate a presigned URL (without knowing how large the file will be, hence no `Content-Length`)
3. Client sends `PUT` request to the presigned URL *with* a `Content-Length` header

> 
> In our S3 Presigner, `Content-Length` is considered an unsigned header. Could you try this?
> 
> ```
> signer = Aws::Sigv4::Signer.new(
>   service: 'execute-api',
>   region: 'us-west-2',
>   unsigned_headers: ['content-length'],
>   # static credentials
>   access_key_id: '<redacted>',
>   secret_access_key: '<redacted>'
> )
> ```

I tried this, it didn't work because we weren't including the header in the signature to begin with. Please let me know if you need more context. Thanks!

**Comment by mullermp** [comment]
Thanks. This is being looked at by the service team, premium support, and myself.

**Comment by mullermp** [comment]
I am thinking that API Gateway is expecting `Content-Length` to be signed when it's provided, but the pre-signed URL only signs the `host` header.

**Comment by mullermp** [comment]
I verified that our signing only signs the `host` header, both as `X-Amz-SignedHeaders` and in the actual signed canonical request.

**Comment by phuongdh** [comment]
> I am thinking that API Gateway is expecting `Content-Length` to be signed when it's provided, but the pre-signed URL only signs the `host` header.

Is this something that's unique to API Gateway? S3 seems to [explicitly avoid signing](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#presign_url-instance_method) `Content-Length` header, and `Aws::Sig4::Signer.presign_url` says [non-Amazon headers are optional](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L353-L356).

**Comment by alextwoods** [comment]
@phuongdh  - I'm trying to understand the use case a bit more.  As you've mentioned, S3 does have a special case that does allow you to create a presigned URL without the `Content-Length` header to support presigned URLS for `PutObject` with out content length being known ahead of time.   The documentation on presigned urls I think is misleading - non-amazon headers are optional except when required by the service/operation.

Is there a reason you cannot use an S3 presigned URL if you need to allow end users to put objects to s3 without content length being known ahead of time?  

One other thing you can try - try forcing it to use `UNSIGNED-PAYLOAD` - this may allow the service to validate a signature without the content length being signed (and without the contents of the body being signed).  

```ruby
url = signer.presign_url(
              http_method: 'PUT',
              url: 'https://<app_id>.execute-api.us-west-2.amazonaws.com/<stage>/<bucket_name>/test.mp4',
              body_digest: 'UNSIGNED-PAYLOAD',
          )
```

**Comment by phuongdh** [comment]
@alextwoods the reason we need to go through API Gateway is because S3 responds with a 200 code, while our clients expect a 201. So our API Gateway integration intercepts and modifies the response code from 200 to 201.

I tried using `body_digest: 'UNSIGNED-PAYLOAD'` with no success.

**Comment by alextwoods** [comment]
With `body_digest: 'UNSIGNED-PAYLOAD`, can you try do the PUT with chunked encoding (and not sending a content-length)?

**Comment by phuongdh** [comment]
> With `body_digest: 'UNSIGNED-PAYLOAD`, can you try do the PUT with chunked encoding (and not sending a content-length)?

Unfortunately our clients must send a `content-length` header. Even if they didn't, from my testing the file will end up being an empty object in S3, seems like S3 needs this header for uploading.

**Comment by mullermp** [comment]
I'm sorry to say this, but it's seeming like this use case is not supported by API Gateway. From the Ruby SDK perspective, if the service is rejecting the request, I don't know what else we can do about it. If another SDK works with this use case, we can explore differences in the pre-signed URLs. You may need to use S3 pre-signed URLs directly and add some lambda function to change the response code.

My understanding is that you have a support case open for this correct? I think it makes sense to push on them to support your use case.

**Comment by mullermp** [comment]
Marking this as closing soon. I'm sorry that we never got to the root cause of this. API Gateway team is aware of this and I will make sure that they have this feature request in their queue.

**Comment by phuongdh** [comment]
Thank you for the updates, we have pivoted to a non-Gateway solution for now.
