### ISSUE TITLE
The list_tags_for_resource method in organisation client in returning an undefined method

### ISSUE THREAD

**Issue by hariharan-chandrasekar** [aws/aws-sdk-ruby#2582]
require 'aws-sdk'
sts = Aws::STS::Client.new(region: 'us-east-1')
token  = sts.assume_role({duration_seconds: 900,role_arn: "arn:aws:iam::xxxx:role/xxx", role_session_name:"AHA"})
org_client = Aws::Organizations::Client.new(region: 'us-east-1',access_key_id: token[:credentials][:access_key_id], secret_access_key: token[:credentials][:secret_access_key], session_token: token[:credentials][:session_token])
list_tags = org_client.list_tags_for_resource({resource_id: "xxx",})
puts list_tags

I have tagged one of my child accounts with a tag that will me filter out some other information. But when i use the list_tags_for_resource API call it is returning an undefined method error 

Error_Message: iam.rb:5:in `<main>': undefined method `list_tags_for_resource' for #<Aws::Organizations::Client> (NoMethodError)
Did you mean?  list_targets_for_policy

**Comment by mullermp** [comment]
This is a strange error. The latest `Aws::Organizations::Client` client has the `list_tags_for_resource` API and should most definitely exist. Are you somehow using an older version? What version of the gem are you using?

Could you call `Aws::Organizations::Client.new.operation_names` and see if `list_tags_for_resource` is there?

**Comment by hariharan-chandrasekar** [comment]
@mullermp You were right. The instance I tested this on was an old instance and the gem used for organizations was an old one. I installed the latest one and this fixed the issue. I raised a query here because even the support team found it bizarre that we got this error. 
Ps: I'm a little embarrassed it was a simple fix and I should of thought of it before. Thanks for the time :)
