### ISSUE TITLE
EC2 waiters: "snapshot_completed" does not consider "error" as a terminal state

### ISSUE THREAD

**Issue by lenon** [aws/aws-sdk-ruby#2586]
**Is your feature request related to a problem? Please describe.**

Hi! I have a snapshot of an EBS volume that has reached an "error" state. In my code, I have something like the following:

```ruby
ec2 = Aws::EC2::Client.new(region: 'ca-central-1')
ec2.wait_until(:snapshot_completed, { snapshot_ids: ['snap-abcd'] }, max_attempts: 120, delay: 60)
```

Eventually, the waiter stops, and this error is raised:

```
... stopped waiting after 120 attempts without success (Aws::Waiters::Errors::TooManyAttemptsError)
```

The problem with this waiter is that it does not consider "error" as a terminal state, only "completed", so it will keep waiting until max attempts are reached. `TooManyAttemptsError` will be raised after 2 hours in this case, but since the snapshot is in a state that it can't transition out of, an error could be raised much earlier.

**Describe the solution you'd like**

I think it would be nice to change the waiter to consider "error" as a terminal state and make it fail earlier with the `Aws::Waiters::Errors::FailureStateError`. It would also be conformant with the behavior of other waiters in the SDK.

**Describe alternatives you've considered**

I was able to use `before_wait` like this as an workaround:

```ruby
before_wait = lambda do |_, response|
  if response.snapshots[0] && response.snapshots[0].state == 'error'
    throw :failure
  end
end
ec2.wait_until(:snapshot_completed, { snapshot_ids: ['snap-abcd'] }, max_attempts: 120, delay: 60, before_wait: before_wait)
```

[x] :wave: I may be able to implement this feature request

**Comment by mullermp** [comment]
Thanks for opening an issue. I see you're interested in fixing this - in theory this is simple to fix. Waiter acceptors are defined as JSON in the API folder: https://github.com/aws/aws-sdk-ruby/blob/b6f6164248dce3f2121682f8bdeb08736830029c/apis/ec2/2016-11-15/waiters-2.json#L369 Once defined, the ec2 gem can be regenerated with `rake build:aws-sdk-ec2` and then tested.

If you are willing to come up with new acceptors for the waiter, I can get them merged upstream and can coordinate with ec2 to make a release.

**Comment by lenon** [comment]
@mullermp thanks for the guidance! I opened this PR here to fix the issue https://github.com/aws/aws-sdk-ruby/pull/2587

**Comment by mullermp** [comment]
Still waiting on this to be deployed.

**Comment by mullermp** [comment]
This has been shipped: https://github.com/aws/aws-sdk-ruby/blob/8ef583acccd8420771713e797af3e2dc684f0ec3/apis/ec2/2016-11-15/waiters-2.json#L380-L385

Thanks for your contribution!
