### ISSUE TITLE
Add waiter for IGW Exists

### ISSUE THREAD

**Issue by dishcandanty** [aws/aws-sdk-ruby#2589]
internet_gateway_exists

There isn't a waiter for `internet_gateway_exists`. When creating, then immediately tagging a gateway I've been intermittently seeing issues where the gateway doesn't exist yet. 

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Waiters.html

```
 igw = resource.create_internet_gateway

# Wait for Exist / No Waiter...
# Ec2.client.wait_until(:internet_gateway_exists, group_ids: [igw.id])

igw.create_tags(tags: [ key: 'Name', value: gateway_name }])
```

**Comment by mullermp** [comment]
Thanks for opening a feature request. Would you be interested in implementing and testing it? Waiter definitions are listed here as JSON: https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/ec2/2016-11-15/waiters-2.json

**Comment by mullermp** [comment]
This has been shipped! https://github.com/aws/aws-sdk-ruby/blob/5d4ab84a8fadffd4aedc4ccebaeee21c1f38ce8f/apis/ec2/2016-11-15/waiters-2.json#L284
