### ISSUE TITLE
aws-sdk 3.0.1 throwing error for ffi requires Ruby version >= 2.3

### ISSUE THREAD

**Issue by sdy15** [aws/aws-sdk-ruby#2591]
How suddenly aws-sdk 3.0.1 throwing error for ffi? Which was working perfectly with ruby 2.1.0 still last month.Now I am getting below error
Error installing aws-sdk:
ffi requires Ruby version >= 2.3

Also if I try to install lower version of ffi. It throws below error
 /opt/puppetlabs/puppet/bin/gem install ffi:1.12.2
Fetching: ffi-1.12.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    /opt/puppetlabs/puppet/bin/ruby extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/puppetlabs/puppet/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:1061:in `block in have_header'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:912:in `block in checking_for'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:911:in `checking_for'
	from /opt/puppetlabs/puppet/lib/ruby/2.1.0/mkmf.rb:1060:in `have_header'
	from extconf.rb:10:in `system_libffi_usable?'
	from extconf.rb:34:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/ffi-1.12.2 for inspection.
Results logged to /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/ffi-1.12.2/gem_make.out

**Comment by mullermp** [comment]
The Ruby SDK no longer supports Ruby versions 1.9 to 2.2 as of recently. Is that the issue?

**Comment by sdy15** [comment]
@mullermp  No. The issue is when I am trying to install aws-sdk 3.0.1 using ruby 2.1.0 ,its throwing me ......
"ffi requires Ruby version >= 2.3" . It was working fine in last month.

Also if I try to lock ffi as per ruby 2.1.0 compatible  ,its throwing me ERROR: Failed to build gem native extension.

As I tested ,Its only working if I downgrade aws-sdk to V2.Which I don't want.

**Comment by mullermp** [comment]
I'm not sure what's going on. Where is FFI coming from?

Also, have you considered moving away from `aws-sdk` and instead use the modularized service gems such as `aws-sdk-s3`? You might not run into that issue.

**Comment by sdy15** [comment]
@mullermp Thanks for your reply. I am also not sure from where suddenly ffi is coming.
Yes.I tried with `aws-sdk-resources` ,its also throwing same error for me.This is the below error.

Fetching: ffi-1.15.4.gem (100%)]# Fetching: ffi-1.15.4.gem
ERROR:  Error installing aws-sdk-resources:
	ffi requires Ruby version >= 2.3.

**Comment by mullermp** [comment]
`aws-sdk` depends on `aws-sdk-resources` which depends on every service gem. Apart from deploying every service gem, it's incredibly slow to download and install. I recommend only depending on the services you need.

Have you considered updating your Ruby version? 2.1 is extremely end of life. If you are using your "system" Ruby, I would recommend against that and to use a Ruby version manager like rbenv, chruby, or rvm.

**Comment by sdy15** [comment]
@mullermp For now updating ruby is painful.Because I am using ruby which is bundle with puppet agent.Replacing ruby means,I need to change the puppet agent and all corresponding codes now.

Is there any way I can get rid of ffi and install aws-sdk v3  for now, specifically 3.0.1 or 3.0.0 which is ruby 2.1.0 compatible .

**Comment by mullermp** [comment]
I'm not sure where FFI is coming from. We do not directly depend on it anywhere as far as I'm aware.
