### ISSUE TITLE
put_lifecycle_configuration using an and: gives a MalformedXML response

### ISSUE THREAD

**Issue by weedySeaDragon** [aws/aws-sdk-ruby#2596]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I want to put a lifecycle_configuration to an S3 bucket with a rule that **uses a filter with multiple tags and a prefix.**

I can successfully `put_lifecycle_configuration` if the filter uses _only one tag or one prefix,_ but I get a `Aws::S3::Errors::MalformedXML (The XML you provided was not well-formed or did not validate against our published schema)` response from AWS if I try to use an `and:` to combine multiple tags _or_ a tag and a prefix.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
- aws-sdk-core 3.109.1
- aws-sdk-s3 1.103.0

**Version of Ruby, OS environment**
-paste the output of ruby -v
ruby 2.6.6

**To Reproduce (observed behavior)**
Here is my rule:
```
aws_s3_backup_prefix = "production_backup" # this is fetched from ENV in real life

rule_expire_yearly_after_10y = {
        id: "Expire 1 January backups after 10 years",
        filter: {
          and: {
            prefix: aws_s3_backup_prefix,
            tags: [
              { key: 'date-month-day', value: '1'},
              { key: 'date-month-num', value: '1'}
            ]
          }
        },
        status: 'Enabled',
        expiration: {
          days: 3650
        }
      }
```

And here is how I use it to put the lifecycle configuration:
```
# aws_client is a valid Aws::S3::Client
# I have access to aws_s3_backup_bucket_name
# I can get and put a simple lifecycle_configuration (no 'and:') with this client and bucket

aws_client.put_bucket_lifecycle_configuration({
          bucket: aws_s3_backup_bucket_name,
          lifecycle_configuration: {
            rules: [ rule_expire_yearly_after_10y ]
          }
        })
```

I've also submitted a question on SO with this same info:
https://stackoverflow.com/questions/69579127/how-can-i-update-a-lifecycle-configuration-with-a-filter-based-on-both-prefix-an

**Expected behavior**
The lifecycle_configuration should be valid and the put_lifecycle_configuration should be successful.

**Screenshots**
n/a

**Additional context**
(none)

**Comment by mullermp** [comment]
This is kind of funny, but I think this bug was fixed in version 3.109.2 with this change, just shy of your 3.109.1 version: https://github.com/aws/aws-sdk-ruby/commit/6ca1851522c36a29108928453486de62241ef2f5#diff-76b3a26d1c7fcce659f02509fef1b5ab43093ef04d54e9b88c9a3bb51d4a57f2

I was able to reproduce the issue with your version, and it appears to work after 3.109.2 and with the current version. You'll need to upgrade your core and s3 versions.
