### ISSUE TITLE
Add start_from_head option to GetLogEventsRequest

### ISSUE THREAD

**Issue by Timothyjb** [aws/aws-sdk-ruby#2599]
**Is your feature request related to a problem? Please describe.**
It would be really great if we could include an option in `FilterLogEventsRequest` to sort results by newest to oldest.

**Describe the solution you'd like**
Including the option `start_from_head` similar to `GetLogEventsRequest`.

**Describe alternatives you've considered**
I can definitely sort the results in my application. The issue is when dealing with the pagination. I could just request a smaller start/end_time and work my way back in time rather then paginating with `limit`+`next_page`. So there are work arounds, just not a very convenient one. 

- [x] :wave: I may be able to implement this feature request

**Comment by mullermp** [comment]
Thanks for opening a feature request. If I understand your use case, this appears to be a service team request and not an SDK. Can you open this in https://github.com/aws/aws-sdk/issues?

**Comment by mullermp** [comment]
Also I'm not sure what service you're talking about. I'm assuming CloudWatchLogs because it defines `FilterLogEventsRequest`.

**Comment by Timothyjb** [comment]
@mullermp Hi, That make sense! I wasn't sure where this type of request should go. I can report elsewhere.
