### ISSUE TITLE
Stacktrace being thrown from aws-sdk-core-3.121.4 about undefined method `signing_service`

### ISSUE THREAD

**Issue by komealy** [aws/aws-sdk-ruby#2603]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Get a stack trace when trying to read from DynamoDB, but this stack trace got thrown from `aws-sdk-core`, so it likely affects multiple classes and functions.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-core-3.121.4

**Version of Ruby, OS environment**
`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`

**To Reproduce (observed behavior)**
1. use `Aws::AssumeRoleCredentials.new` to assume a role in aws
2. use `Aws::DynamoDB::Client.new` to setup a dynamo db client
3. use `.get_item()` function to lookup an item
4. stacktrace:

**Expected behavior**
No stacktrace, and return the value from the `get_item` call.

**Additional context**
Stacktrace:
```
/root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/aws-sdk-core/plugins/signature_v4.rb:16:in `block in <class:SignatureV4>': undefined method `signing_service' for Aws::Partitions::EndpointProvider:Class (NoMethodError)
--
910 | Did you mean?  signing_region
911 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:72:in `call'
912 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
913 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:59:in `each'
914 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:59:in `each'
915 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
916 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:207:in `value_at'
917 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:191:in `block in resolve'
918 | from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/set.rb:328:in `each_key'
919 | from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/set.rb:328:in `each'
920 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:191:in `resolve'
921 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
922 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/configuration.rb:152:in `build!'
923 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/base.rb:65:in `build_config'
924 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/base.rb:22:in `initialize'
925 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/aws-sdk-sts/client.rb:332:in `initialize'
926 | from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.121.4/lib/seahorse/client/base.rb:102:in `new'
927 | from /codebuild/output/src739443017/src/github.com/komealy/test-repo/get_release_version.rb:15:in `<main>'
```

**Comment by alextwoods** [comment]
Thanks for opening this - I pushed a change (#2602) yesterday that added the `signing_service` method into partitions but forgot to bump the minimum dependencies.

You can resolve this by using the latest `aws-partitions` gem (>= 1..520.1) and I'll work on a fix.

**Comment by komealy** [comment]
It does look like updating `aws-partitions` gem does indeed get past this. I ran locally with that updated as well to `1.520.1`, and it looks to work.

Specifically the version that did not work and threw the stack trace is `aws-partitions-1.520.0`:

```
[Container] 2021/10/28 19:14:37 Running command gem install --no-document aws-sdk-core aws-sdk-dynamodb aws-sdk-ec2
--
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.520.0
Successfully installed aws-eventstream-1.2.0
Successfully installed aws-sigv4-1.4.0
Successfully installed aws-sdk-core-3.121.4
Successfully installed aws-sdk-dynamodb-1.64.0
Successfully installed aws-sdk-ec2-1.273.0
7 gems installed
```

**Comment by alextwoods** [comment]
Thanks for the verification and sorry you ran into this!  

I've got a RR out to fix this: #2604

**Comment by komealy** [comment]
This issue no longer happens with `aws-sdk-core-3.121.5` and `aws-partitions-1.521.0`.

This set of gems was successful:

```
[Container] 2021/11/01 17:55:23 Running command gem install --no-document aws-sdk-core aws-sdk-dynamodb aws-sdk-ec2
--
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.521.0
Successfully installed aws-eventstream-1.2.0
Successfully installed aws-sigv4-1.4.0
Successfully installed aws-sdk-core-3.121.5
Successfully installed aws-sdk-dynamodb-1.64.0
Successfully installed aws-sdk-ec2-1.275.0
7 gems installed
```

I'll go ahead and close this issue since this new set of versions resolves the problem.

**Comment by alextwoods** [comment]
Thanks for the verification!
