### ISSUE TITLE
Better error/guidance for no SSO session

### ISSUE THREAD

**Issue by laupow** [aws/aws-sdk-ruby#2605]
**Is your feature request related to a problem? Please describe.**
In [`read_cached_token`](https://github.com/aws/aws-sdk-ruby/blob/9d29a70cd90482d34b4ecf1e0800a7f0ac1035f4/gems/aws-sdk-core/lib/aws-sdk-core/sso_credentials.rb#L92-L105) there's a good attempt to provide users with a helpful error message for SSO session errors.

One edge case I ran into is after somebody runs `aws sso logout` the file is deleted. This causes an different type of error that isn't handled well.

**Describe the solution you'd like**
1. Human runs `aws sso logout` to destroy files in `~/.aws/sso/cache`
2. Human runs application (locally) that consumes SSO tokens
3. App throws a helpful error: `raise Errors::MissingSSOCredentials` or perhaps `MissingOrInvalidSSOCredentials`

**Describe alternatives you've considered**
no alternatives considered at this time; open to ideas

[ ] :wave: I may be able to implement this feature request

**Additional context**

An example stacktrace after I ran `aws sso logout`

```
         2: from /Users/mlauer/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.121.3/lib/aws-sdk-core/sso_credentials.rb:79:in `initialize'
         1: from /Users/mlauer/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.121.3/lib/aws-sdk-core/sso_credentials.rb:93:in `read_cached_token'
/Users/mlauer/.rvm/gems/ruby-2.7.4/gems/aws-sdk-core-3.121.3/lib/aws-sdk-core/sso_credentials.rb:93:in `read': No such file or directory @ rb_sysopen - /Users/mlauer/.aws/sso/cache/54a89a65629a8395caba118b506fd9ec00d9e59b.json (Errno::ENOENT)
```

**Comment by alextwoods** [comment]
Hey - thanks for submitting this request - agree we should have better error messages for that situation!  I'll take a look at a fix.

**Comment by mullermp** [comment]
Wow, such bug report, many bugs!
