### ISSUE TITLE
Aws::STS::Presigner forces regional endpoint regardless of client config

### ISSUE THREAD

**Issue by rittneje** [aws/aws-sdk-ruby#2607]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

When using Aws::STS::Presigner to generate a presigned url for GetCallerIdentity, the resulting url always has a regional endpoint for the hostname, even if you set `sts_regional_endpoints` to "legacy", or forcibly set `endpoint` to "https://sts.amazonaws.com" in the Aws::STS::Client constructor.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-core 3.121.6

**Version of Ruby, OS environment**

2.6.3

**Comment by rittneje** [comment]
I found the root cause of the bug.
https://github.com/aws/aws-sdk-ruby/blob/9e16f6d3c5c1a8e2fba982ba07f93b164b3b4406/gems/aws-sdk-core/lib/aws-sdk-sts/presigner.rb#L55-L57

That needs to be changed to:
```ruby
url = req.context.config.endpoint.to_s
```

**Comment by mullermp** [comment]
Thanks for reporting this. It was fixed as part of this PR that will be merged today: https://github.com/aws/aws-sdk-ruby/pull/2553/files

Relevant section:
https://github.com/aws/aws-sdk-ruby/blob/415d9ac0157973ae5db2d5da59e2c1ff5d28d126/gems/aws-sdk-core/lib/aws-sdk-sts/presigner.rb#L55-L63
