### ISSUE TITLE
Pinning aws-sdk-secretsmanager to version 1.48.0 now requires Ruby version >= 2.3

### ISSUE THREAD

**Issue by stevenyongezypay** [aws/aws-sdk-ruby#2612]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
We previously install aws-sdk-secretsmanager by pinning its version to 1.48.0 as this is the last version that does not require Ruby version >= 2.3.

It works but a few days ago we have got this error:

gem install --version 1.48.0 --no-user-install --no-document aws-sdk-secretsmanager", "msg": "ERROR:  Error installing aws-sdk-secretsmanager:\n\taws-partitions requires Ruby version >= 2.3."

We also previously pin the version of aws-partitions to 1.493.0 and it works until recently.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-secretsmanager 1.48.0

**Version of Ruby, OS environment**
-paste the output of ruby -v

2.0.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

    - gem:
        name: aws-partitions
        version: 1.493.0
        user_install: no
      tags:
        - build        

    - gem:
        name:  aws-sigv4
        version: 1.2.4
        user_install: no
      tags:
        - build             

    - gem:
        name: aws-sdk-core
        version: 3.119.1
        user_install: no
      tags:
        - build           

    - gem:
        name: aws-sdk-secretsmanager
        version: 1.48.0
        user_install: no
      tags:
        - build

**Expected behavior**
Able to install aws-sdk-secretsmanager by pinning the version using older Ruby version

**Screenshots**

**Additional context**

**Comment by mullermp** [comment]
Thanks for opening an issue. Are you able to use Bundler? It should be able to resolve this correctly.

**Comment by mullermp** [comment]
Just curious, what is blocking you from upgrading your Ruby version?

**Comment by alextwoods** [comment]
I confirmed that in Ruby 2.2, bundler (with a Gemfile/`bundle install`) will correctly install `aws-sdk-secretsmanager` version `1.48.0`.  

It looks like rubygems builds the list of transient dependencies based on the latest resolved versions that match: https://rubygems.org/gems/aws-sdk-secretsmanager/versions/1.48.0/dependencies.  So I believe the other option if you can't upgrade ruby versions and can't use bundler is to use something like the `--conservative` option. Eg: 
```
gem install --no-user-install --no-document aws-partitions:1.483.0 aws-eventstream:1.1.1 aws-sigv4:1.2.4 aws-sdk-core:3.119.0 aws-sdk-secretsmanager:1.47.0 --conservative
```

**Comment by stevenyongezypay** [comment]
> Just curious, what is blocking you from upgrading your Ruby version?

We are using Centos 7 and the latest version of Ruby seems to be 2.0.

**Comment by stevenyongezypay** [comment]
We later got this resolved by adding `force: yes`:

    - gem:
        name: aws-sdk-secretsmanager
        version: 1.48.0
        force: yes

Force gem to install, bypassing dependency checks.

As the other alternatives suggested by @alextwoods using `--conservative` is not available in the Ansible options, yet.

https://github.com/ansible/ansible/issues/18925

Happy for this to be closed.
