### ISSUE TITLE
Slow Aws::InstanceProfileCredentials.new when not running under EC2

### ISSUE THREAD

**Issue by shaicoleman** [aws/aws-sdk-ruby#2617]
Aws::InstanceProfileCredentials.new tries to do network calls when not on AWS, this causes initializing objects to be extremely slow, for no obvious reason, e.g.

Example code:
```
# Unset environment variables to reliably reproduce the issue
ENV['AWS_PROFILE'] = nil
ENV['AWS_ACCESS_KEY_ID'] = nil
ENV['AWS_SECRET_ACCESS_KEY'] = nil
ENV['AWS_SESSION_TOKEN'] = nil

require 'aws-sdk-core'
Aws::InstanceProfileCredentials.new
```

This can be triggered by initializing unrelated objects, which was quite difficult to track down, e.g.
```
require 'aws-sdk-lambda'
Aws::Lambda::Client.new(endpoint: 'http://localhost:8080') # takes 3 seconds [edited]
```

This happens because if the client doesn't find credentials via the environment variables, it falls back to trying to get the credentials from the instance. When not running under AWS, it performs a network request to 169.254.169.254, and then waits for it to time out.

It should only try to do network requests if it detects if it's running under AWS, e.g. as documented here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html

aws-sdk-core version 3.123.0 (November 23, 2021)

Workaround [edited]:
```
unless File.readable?('/sys/devices/virtual/dmi/id/board_asset_tag') &&
       File.read('/sys/devices/virtual/dmi/id/board_asset_tag').match?(/\Ai-[0-9a-z]{8,32}\s*/)
  ENV['AWS_EC2_METADATA_DISABLED'] = 'true'
end
```

**Comment by mullermp** [comment]
Thanks for opening an issue. You are correct that `InstanceProfileCredentials` does attempt to make network calls to EC2 Metadata service.

When initializing a client, the SDK needs credentials. It is not an unrelated object - when the client is initialized, it looks in multiple locations for credentials, [using the credential provider chain](https://github.com/aws/aws-sdk-ruby/blob/7a76dd6e99d5d5b6008df110f9222d1e5ff280be/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L21-L41). There are far more locations than just ENV variables. See [this guide](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html) for more information on configuring credentials.

In the chain, `InstanceProfileCredentials` is the last location looked at. You can avoid this by configuring any of the other credential types first, and if so, the SDK will exit the chain. If using `InstanceProfileCredentials.new` and passing `:credentials` to the client manually, you can override the options for `retries`, `http_open_timeout`, and `http_read_timeout`.

On the link you provided, it says the only definitive and verified method is to check the instance identity document (which requires network call to EC2 metadata service). At the time of this credential's implementation, system UUID method may have not existed. It looks like this method is not always accurate - there are multiple files to consider and multiple formats. The little endian format doesn't have "Ec2" in the string either. I can ask around internally about this, but likely we need to continue considering the EC2 local address only as it is guaranteed accurate.

**Comment by mullermp** [comment]
That said, can I ask what your use case is and what you are trying to do? Or is this just an intended bug report?

**Comment by shaicoleman** [comment]
@mullermp, mainly, I wasted a couple of hours to figure out why things were so slow on development and testing. Creating a new instance of an object shouldn't take a couple of seconds.

I consider it to be a bug.

Also, it's unexpected that creating an instance of an unrelated object would trigger network requests.

This was also causing our specs to run slow, as the client was initialized, but the actual call was stubbed.

My use case is developing and testing lambdas offline while called from our main app. I'm trying to use `Aws::Lambda::Client` to call a dockerized lambda function, as detailed here: [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html)

I've got it working by monkeypatching the `Aws::Partitions::EndpointProvider.resolve` method to handle local endpoints.

**Comment by mullermp** [comment]
That makes sense, I'm sorry that it was frustrating. I can investigate whether the UUID approach will work. There may be backwards compatibility concerns with it. I am also exploring options for lazy loading credentials (same issue but pushed to operation calls instead of client initialization) and ping/query endpoint before attempting to fetch credentials.

>This was also causing our specs to run slow, as the client was initialized, but the actual call was stubbed.

For your specs, are you using a stubbed client? (`stub_responses: true`) because it does provide mocked credentials.

>I've got it working by monkeypatching the Aws::Partitions::EndpointProvider.resolve method to handle local endpoints.

Can you explain more about why you did this? The `Client` can take an `endpoint` option and it should skip resolving any endpoints. I'm not certain why `EndpointProvider` is of concern with `InstanceProfileCredentials`, unless this is a separate issue?

**Comment by mullermp** [comment]
Another thing worth mentioning is that you can disable EC2 Metadata credentials by setting `AWS_EC2_METADATA_DISABLED=true`

**Comment by shaicoleman** [comment]
> you can disable EC2 Metadata credentials by setting `AWS_EC2_METADATA_DISABLED=true`

Thanks, that's useful, I didn't come across that in the docs.

> Can you explain more about why you did this [monkeypatching]? The Client can take an endpoint option and it should skip resolving any endpoints.

I think the Aws::Lambda::Client documentation was a bit misleading: "To construct a client, you need to configure a :region and :credentials.", when it should have said either :region or :endpoint. A few more usages examples would also be helpful.

**Comment by mullermp** [comment]
Region is required for SigV4 signing, while the endpoint can be changed/overridden. When endpoint is not provided, it is derived using the region. This makes endpoint entirely optional and region required.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/commit/47651cf95447f2ec28f13aca936e9cb6fe85b3d9 Added some documentation for disabling EC2 metadata in the credential chain.

**Comment by mullermp** [comment]
What type of examples were you looking for?
