### ISSUE TITLE
S3::Object::upload_file does not allow thread_count param when file less than multipart threshold.

### ISSUE THREAD

**Issue by dedman** [aws/aws-sdk-ruby#2628]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
When using S3::Object::upload_file('/file.txt', thread_count: 1) and 'file.txt' is less than 100mb (the default multipart threshold) then I get

```param_validator.rb:35:in `validate!': unexpected value at params[:thread_count] (ArgumentError)```

However using S3::Object::upload_file('/file.txt', thread_count: 1) when 'file.txt' is larger than 100mb then it uploads the file as expected.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3 (1.111.0)

**Version of Ruby, OS environment**
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**To Reproduce (observed behavior)**

Create a file that is less than a 100mb, and set the path in `file_to_upload`
```
file_to_upload = '/1mb.file'
credentials = Aws::Credentials.new(ENV['ACCESS_KEY'], ENV['SECRET_KEY'])
s3 = Aws::S3::Resource.new(region: ENV['REGION'], credentials: credentials)
new_s3_object = s3.bucket(ENV['BUCKET_NAME']).object(File.basename(file_to_upload))
new_s3_object.upload_file(file_to_upload, thread_count: 1)


-- Causes error
validate!': unexpected value at params[:thread_count] (ArgumentError)
```

**Expected behavior**
File should be uploaded regardless of it size. Thread count should be ignored if the file size is less than the multipart threshold (as stated in the documentation https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L418-L420).

**Screenshots**
NA

**Additional context**
We have a mix of large and small files to upload with limited memory, so setting the thread_count to 1 is to help reduce memory usage. The uploads have no urgency to them.

Related issues https://github.com/aws/aws-sdk-ruby/pull/2133 and https://github.com/aws/aws-sdk-ruby/issues/2120

**Comment by alextwoods** [comment]
Thanks for opening this - I'm looking into possible solutions.

**Comment by mullermp** [comment]
I'm pretty sure we just need to unpack `thread_count` here: https://github.com/aws/aws-sdk-ruby/blob/82da029b0bc9dc2317e3b0c7a42628a22f048d3d/gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb#L436

with
```
          thread_count: uploading_options.delete(:thread_count),

```

**Comment by dedman** [comment]
Awesome, thanks Alex!
