### ISSUE TITLE
`RubyVM.stat[:global_constant_state]` changed by `ResponsePaging`

### ISSUE THREAD

**Issue by michalbugno** [aws/aws-sdk-ruby#2634]
Hey y'all,

If I did my debugging right the code responsible for paginating response is changing `RubyVM.stat[:global_constant_state]` by calling `resp.extend(PageableResponse)`

https://github.com/aws/aws-sdk-ruby/blob/a82c8981c95a8296ffb6269c3c06a4f551d87f7d/gems/aws-sdk-core/lib/aws-sdk-core/plugins/response_paging.rb#L10-L16

This is not ideal because it can affect performance significantly, the `global_constant_state` should remain more or less constant throughout application lifetime.

**Comment by alextwoods** [comment]
Hey - thanks for raising this issue.  I agree with your assessment that the `ResponsePaging` plugin is causing the `:global_constant_state` to increase (specifically by one per request made) and that specifically its the `resp.extend(PageableResponse)` that is causing the increase.

Having a plugin that dynamically has all non-async responses extend `PageableResponse` was an unfortunate design decision and something we are planning on fixing in a future major version.  However, for now I don't believe it's possible to change this behavior without a breaking change to SDK users.

**Comment by michalbugno** [comment]
@alextwoods Yeah, I noticed the design was different in v2.

Is there any way to disable this plugin completely at a cost of pagination not working or is it something you wouldn't recommend?

**Comment by alextwoods** [comment]
Great question - yes you can!  The PageableResponse does add some methods to each response object (mostly enumerable methods) - so removing it *could* break your application if you use those methods. Otherwise, it is reasonable to do so.  There are a number of ways to do it - but all of them involve using the `remove_plugin`/`add_plugin` on the Client classes - these would need to be done during application initialization (note: in future major versions we are working to make this more flexible).

```ruby
# remove it from a single service
Aws::S3::Client.remove_plugin(Aws::Plugins::ResponsePaging)
s3 = Aws::S3::Client.new
resp = s3.list_buckets
resp.kind_of?(PageableResponse) # resp will no longer extend PageableResponse

# Remove it for ALL services
Aws.constants.each do |c|
  m = Aws.const_get(c)
  if m.is_a?(Module) && m.const_defined?(:Client) &&
    m.const_get(:Client).superclass == Seahorse::Client::Base
    m.const_get(:Client).remove_plugin(Aws::Plugins::ResponsePaging)
  end
end

# Add a custom plugin that will make responses only for pageable operations pageable
class CustomResponsePaging < Seahorse::Client::Plugin
  class Handler < Seahorse::Client::Handler
    def call(context)
      context[:original_params] = context.params
      resp = @handler.call(context)
      if context.operation[:pager]
        resp.extend(PageableResponse)
        resp.pager = context.operation[:pager]
      end
      resp
    end
  end
  handle(Handler, step: :initialize, priority: 90)
  # Note - you could also apply this only to certain operations via
  # handle(Handler, step: initialize, priority: 90, operations: [:list_buckets, :list_objects])
end
Aws::S3::Client.remove_plugin(Aws::Plugins::ResponsePaging)
Aws::S3::Client.add_plugin(CustomResponsePaging)
resp = s3.list_objects(bucket: bucket)
resp.kind_of?(PageableResponse) # true
resp = s3.get_object(bucket: bucket, key: key).kind_of?(PageableResponse) # false
```

**Comment by michalbugno** [comment]
Wow, thanks for that! Good stuff, this will probably be Good Enough™ for me :)
