### ISSUE TITLE
Unsupported option: foo_starts_with after upgrading aws-sdk-s3 from 1.111.1 to 1.111.2

### ISSUE THREAD

**Issue by henrik** [aws/aws-sdk-ruby#2636]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

After upgrading aws-sdk-s3 from 1.111.1 to 1.111.2 we got ArgumentErrors saying "Unsupported option: content_type_starts_with". Our code effectively does

    Aws::S3::Resource.new.bucket("the-name").presigned_post({ …, content_type_starts_with: "image/" })

This worked fine before. I see the diff for this upgrade touches on "starts_with", so it must have introduced a regression.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-s3 1.111.2

**Version of Ruby, OS environment**
-paste the output of ruby -v

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

**Comment by alextwoods** [comment]
Hey - sorry you're running into this.  I introduced this in a recent cleanup - I'll have a fix out shortly.

**Comment by henrik** [comment]
Thank you, @alextwoods! :)
