### ISSUE TITLE
Stubbing behavior for SQS queue's url not returning valid URL

### ISSUE THREAD

**Issue by rgates-fieldwire** [aws/aws-sdk-ruby#2640]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

When the stub_responses flag is set too true when creating a new queue or getting the queue url. The returned value for queue_url is 'string' rather than a valid URL.  

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-sqs (1.38.0)
      aws-sdk-core (~> 3, >= 3.112.0)
      aws-sigv4 (~> 1.1)

**Version of Ruby, OS environment**

ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

Aws.config.update({ :access_key_id => 'FAKE', :secret_access_key => 'FAKE' })
    Aws.config.update(stub_responses: true)

@SQSClient = Aws::SQS::Client.new()
    queueUrl = @SQSClient.get_queue_url(queue_name: ENV['BIM_SQS_QUEUE_NAME']).queue_url

**Expected behavior**

Should return a valid URL, like: https://sqs.us-Stub.amazonaws.com/1/MyQueue

**Actual behavior**
Returns:
{:queue_url=>"String"}

**Comment by alextwoods** [comment]
Hey - the stub defaults are "dumb" (and based only on the types) - to stub the method to return an expected queue you need to stub the expected response, eg:

```ruby
@SQSClient.stub_responses(:get_queue_url, {queue_url: 'https://sqs.us-Stub.amazonaws.com/1/MyQueue'})
queueUrl = @SQSClient.get_queue_url(queue_name: ENV['BIM_SQS_QUEUE_NAME']).queue_url
```

Note, you can also use dynamic behvaior by providing a block - for an overview, see:[ Client Stubbing](https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/).

**Comment by rgates-fieldwire** [comment]
I used the AWS config stubbing to inject a proper URL.

```
Aws.config[:sqs] = {
      stub_responses: {
        get_queue_url: { queue_url: "https://sqs.us-Stub.amazonaws.com/1/MyQueue" }
      }
    }
```

Which unblocked me. However I was also using the S3 stubbing functionality and it returned a valid URL when I got the public_url for a S3 object. The difference in behavior made me think it was a bug.
