### ISSUE TITLE
Passing filenames to Aws::S3::Client#put_object

### ISSUE THREAD

**Issue by grncdr** [aws/aws-sdk-ruby#2646]
**Describe the issue with documentation**

Examples in [the documentation for `put_object`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#put_object-instance_method) often pass a filename as the `:body` parameter. However, when I try this, I end up with an object containing the filename as it's content.

**To Reproduce (observed behavior)**
Here is an example from the documentation:

```rb
# The following example creates an object. If the bucket is versioning enabled, S3 returns version ID in response.

resp = client.put_object({
  body: "filetoupload", 
  bucket: "examplebucket", 
  key: "objectkey", 
})
```

And here's a small test script:

```rb
require 'aws-sdk-s3'

client = Aws::S3::Client.new

bucket = ARGV[0]

expected_content = "expected content\n"
File.write('test.txt', expected_content)
client.put_object(body: 'test.txt', bucket: bucket, key: 'test.txt')

response = client.get_object(bucket: bucket, key: 'test.txt')

actual_content = response.body.read

if actual_content == expected_content
  puts 'Found expected content'
else
  puts "#{actual_content.inspect} != #{expected_content.inspect}"
  exit 1
end
```

Running the above script produces the following output:

```
$ ruby s3_test.rb a-very-unique-bucket-name
"test.txt" != "expected content\n"
$ cat test.txt
expected content
$
```

**Expected behavior**

I opened this as a documentation issue because it's unclear to me if the above is _supposed_ to work, or maybe worked in previous versions of the SDK. The docs include multiple examples of filenames being passed to the `:body` param.

**Additional context**

Versions:

```
aws-sdk-s3 (1.111.3)
      aws-sdk-core (~> 3, >= 3.125.0)
      aws-sdk-kms (~> 1)
```

**Comment by grncdr** [comment]
It's also very strange to me that the filename is stored with surrounding quotes in the S3 object. I've been unable to determine at which step of parameter parsing that occurs.

**Comment by alextwoods** [comment]
Thanks for opening this - the documentation is unclear!  The `body` parameter is not expected to work as a file name (it can be either the body contents as a String/StringIO or it can be a File object) and the parameter documentation is: `:body (String, StringIO, File) — Object data.`.  However, I agree the examples are very confusing and make it look like the body parameter should accept a file name rather than just the object data.   Those examples are owned by the S3 team and are just codegened into our documentation.  I'll raise this issue to them and see if we can get those updated to be a bit more clear.

**Comment by grncdr** [comment]
Thanks @alextwoods, I have been refactoring a bunch of S3-related code recently and when I saw the examples in the docs my first thought was "that's pretty magical... but would make my life so much easier..." too bad it doesn't work. 🤷 

If I could ask for one more clarification. I noticed some code that seems like it closes files after reading them. Is that documented somewhere? It would be nice to write `object.put(body: File.open(...))` instead of `File.open(...) { |f| object.put(body: f) }` but I'm not sure if the first style will leave open file descriptors around until the next garbage collection.

**Comment by alextwoods** [comment]
Yeah - It would be nice if that worked, but I don't believe theres a generic way we could distinguish between file names and actual body text.

Note - the [`Object#upload_file`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method) method *does* take a string path and will manage opening the file and closing it (it also will handle splitting larger files and using multipart upload).  

In general the SDK will not close files opened by users so you should ensure the file is closed in your code.  (The exception to this is cases where the SDK is the one opening the file, as in `Object#upload_file` above).

**Comment by grncdr** [comment]
> Note - the [Object#upload_file](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method) method does take a string path and will manage opening the file and closing it (it also will handle splitting larger files and using multipart upload).

Ah that's exactly what I was looking for. Thank you!
