### ISSUE TITLE
Attempting to use `Aws::SharedCredentials` with no `~/.aws/credentials` file fails in an unexpected way

### ISSUE THREAD

**Issue by haines** [aws/aws-sdk-ruby#2654]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

If I give a non-existent profile to `Aws::SharedCredentials.new`, I normally get a `Aws::Errors::NoSuchProfileError`. However, if the `~/.aws/credentials` and `~/.aws/config` files don't exist, then instead of an error I get a `Aws::SharedCredentials` instance that returns `nil` for `credentials`.

This causes somewhat cryptic failures later when trying to use the `Aws::SharedCredentials` instance, for example

```
gems/aws-sigv4-1.4.0/lib/aws-sigv4/signer.rb:690:in `credentials_set?': undefined method `access_key_id' for nil:NilClass (NoMethodError)
```

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-core 3.126.0

**Version of Ruby, OS environment**

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21]

**To Reproduce (observed behavior)**

(with existing `~/.aws/credentials` and `~/.aws/config` files)

```console
$ ruby -r aws-sdk-core -e 'p Aws::SharedCredentials.new(profile_name: "wat").credentials'
Traceback (most recent call last):
	4: from -e:1:in `<main>'
	3: from -e:1:in `new'
	2: from /Users/andrew/.gem/ruby/2.7.5/gems/aws-sdk-core-3.126.0/lib/aws-sdk-core/shared_credentials.rb:42:in `initialize'
	1: from /Users/andrew/.gem/ruby/2.7.5/gems/aws-sdk-core-3.126.0/lib/aws-sdk-core/shared_config.rb:103:in `credentials'
/Users/andrew/.gem/ruby/2.7.5/gems/aws-sdk-core-3.126.0/lib/aws-sdk-core/shared_config.rb:372:in `validate_profile_exists': Profile `wat' not found in /Users/andrew/.aws/credentials or /Users/andrew/.aws/config (Aws::Errors::NoSuchProfileError)
```

(without existing `~/.aws/credentials` and `~/.aws/config` files)

```console
$ ruby -r aws-sdk-core -e 'p Aws::SharedCredentials.new(profile_name: "wat").credentials'
nil
```

**Expected behavior**

`Aws::Errors::NoSuchProfileError` is also raised when the profile does not exist because the shared config files do not exist.

**Comment by mullermp** [comment]
Thanks for opening an issue. I need to investigate all the possible cases, but on the surface, I agree that an error should probably be raised here.
