### ISSUE TITLE
S3 Direct Upload to a key

### ISSUE THREAD

**Issue by resistorsoftware** [aws/aws-sdk-ruby#2655]
I have a configuration where I direct upload to S3 using Rails 7. My configuration is simple:

    amazon:
      service: S3
      access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
      secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
      region: us-east-1
      bucket: "my-bucket"

My problem is, I setup my access token and security so that the file should be placed in the bucket and key such as:

      mybucket/my-special-folder

So now when I do CORS, that passes for https://mydomain.test, but then the actual PUT fails on permissions since there is no indication of the key "my-special-folder". 

How do I inform the AWS S3 Ruby gem to send uploads to a special key like that?

**Comment by mullermp** [comment]
Is this ActiveStorage usage? If so, consider opening an issue in rails/rails. Unless you're using the SDK directly, I don't know if I can help you here.
