### ISSUE TITLE
SNS Message Validator Errors when sending to FIFO Topic

### ISSUE THREAD

**Issue by xjcoan** [aws/aws-sdk-ruby#2661]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to send a message to an SNS topic that will fanout to SQS queues. The queues and topic are FIFO, so I understand that I need a `message_group_id` and `message_deduplication_id` in my message body. When I try including those two keys in the message parameters that I send using an SNS Client, I get errors from the message validator that there is an unexpected value present for `params[:message_group_id]` and `params[:message_deduplication_id]`

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-sns`, version `1.52.0`

**Version of Ruby, OS environment**
-paste the output of ruby -v
`ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]`

**To Reproduce (observed behavior)**
Following the documentation for [Aws::SNS::Client](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SNS/Client.html)

- I have an IAM user with the AWS default `sns full access` policy applied
- I have a topic created, along with a FIFO queue to receive it. The queue is subscribed to the topic and I can manually send a message via the AWS console to the topic, which shows up in the sqs queue.

I'm trying to send a message like so:

```ruby
credentials = Aws::Credentials.new("my-access-key-id", "my-secret-access-key")

client = Aws::SNS::Client.new(region: "us-west-2", credentials: credentials)

client.publish({
  topic_arn: "my-topic-arn",
  body: "{\"foo\": \"bar\"}",
  message_group_id: "event-test-1",
  message_deduplication_id: "event-test-1",
})
```

This produces the following error:
```
ArgumentError (parameter validator found 2 errors:)
  - unexpected value at params[:message_group_id]
  - unexpected value at params[:message_deduplication_id]
 ```

If I send a message without the Group and Deduplication IDs, the following happens:

```ruby
client.publish({
  topic_arn: "my-topic-arn",
  body: "{\"foo\": \"bar\"}",
})

Aws::SNS::Errors::InvalidParameter (Invalid parameter: The MessageGroupId parameter is required for FIFO topics)
```

**Expected behavior**
The message validator should recognize `message_group_id` and `message_deduplication_id`, allowing the message to be passed to the SNS Topic

**Comment by alextwoods** [comment]
Can you provide the value of `Aws::SNS::GEM_VERSION` in your environment?

In the code you have, the `body` parameter isn't supported - I believe it should be `message` instead.  Changing, `body` to `message` in your example, I am able to make the request without validation raising for unexpected parameters.  (Also a side note, the documentation you linked is for V2 of the SDK, rather than V3.  The [V3 SNS client docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SNS/Client.html#publish-instance_method))

**Comment by xjcoan** [comment]
@alextwoods Thanks for the response!

`Aws::SNS::GEM_VERSION` was reading as `1.24.0` instead of the `1.52.0` I have installed. After reloading, it's showing `1.52.0` correctly.

I'm not sure where I got `body` from, but I was using `message` in my original testing. But now that the gem updated correctly, I got a successful publish response this time.

**Comment by alextwoods** [comment]
Great! I'm going to close this issue then - feel free to reopen if you're still running into issues.
