### ISSUE TITLE
Aws::Errors::NoSuchProfileError if only using environment variables for credentials

### ISSUE THREAD

**Issue by kingfai** [aws/aws-sdk-ruby#2665]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
In release 3.126.2, this patch https://github.com/aws/aws-sdk-ruby/pull/2662 seems to cause an error if
1. You do not have any files under ~/.aws
2. You are using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` for credentials
3. You call `Aws::SharedCredentials.new().credentials`

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3 3.126.2

**Version of Ruby, OS environment**
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]

**To Reproduce (observed behavior)**
1. Make sure you have valid credentials in  `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
2. `~/.aws` should be empty or non existant

Gemfile
```
source 'https://rubygems.org' do
  gem 'aws-sdk-s3', '~> 1'
end
```

credentials.rb
```
require 'aws-sdk'

shared_credentials = Aws::SharedCredentials.new().credentials
puts shared_credentials.inspect
```

Here's my output
```
$ export AWS_ACCESS_KEY_ID=XXXXXXX
$ export AWS_SECRET_ACCESS_KEY=XXXXX
$  ruby credentials.rb
/Users/aso/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/shared_config.rb:367:in `validate_profile_exists': Profile `default' not found in /Users/aso/.aws/credentials or /Users/aso/.aws/config (Aws::Errors::NoSuchProfileError)
	from /Users/aso/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/shared_config.rb:103:in `credentials'
	from /Users/aso/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.126.2/lib/aws-sdk-core/shared_credentials.rb:42:in `initialize'
	from credentials.rb:3:in `new'
	from credentials.rb:3:in `<main>'
```
**Expected behavior**
The code should return a credentials object and print out the access_key_id
```
ruby credentials.rb
#<Aws::Credentials access_key_id="XXXXXXX">
```

**Comment by mullermp** [comment]
Agh.. I'm sorry. This looks like a regression.

**Comment by mullermp** [comment]
So taking a closer look, while this is a regression, **this is actually expected behavior.** Before patch #2662, the reproduced behavior would return nil. Shared credentials only loads credentials from either ~/.aws/config or ~/.aws/credentials files and is not responsible for loading credentials via ENV (other than `AWS_PROFILE`).

```
[1] pry(Aws)> ENV['AWS_ACCESS_KEY_ID'] = 'XX'
=> "XX"
[2] pry(Aws)> ENV['AWS_SECRET_ACCESS_KEY'] = 'XX'
=> "XX"
[3] pry(Aws)> Aws::SharedCredentials.new().credentials
=> nil
```

**Comment by mullermp** [comment]
Might I ask what your use case is and how you ran into this behavior?

**Comment by kingfai** [comment]
Hi @mullermp ,

We're using this in CI. It looks like our code expects a nil from `SharedCredentials.new().credentials` if ~/.aws/conf or ~/.aws/credentials are not found:

```
@shared_creds = Aws::SharedCredentials.new().credentials
# SharedCredentials may contain a blank credentials object if there are no credentials on the system
@shared_creds = Aws::Credentials.new(nil, nil) if @shared_creds.nil?
```

**Comment by mullermp** [comment]
I see. The new expected behavior is that the error message is raised. Returning nil was not appropriate. You should rescue from the error instead:

```
begin
  @shared_creds = Aws::SharedCredentials.new().credentials
rescue Aws::Errors::NoSuchProfileError
  @shared_creds = Aws::Credentials.new(nil, nil)
end
```

**Comment by mullermp** [comment]
I apologize for needing to change, but I can't backtrack on this decision and checking ENV for access key/secret access key is not in scope for shared credentials (from config/credential files).
