### ISSUE TITLE
`object.exists?` raises `Aws::S3::Errors::Forbidden` when object doesn't exist

### ISSUE THREAD

**Issue by vfonic** [aws/aws-sdk-ruby#2669]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**

This is my policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::bucket-name/*"
        }
    ]
}
```

As explained by AWS S3 UI itself:
> BucketName | string like | bucket-name, ObjectPath | string like | All

However, if the `key` does not exist, instead of getting `false`, `Aws::S3::Errors::Forbidden` error is raised.

Changing the policy to this one, fixes the issue:

```diff
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
-            "Resource": "arn:aws:s3:::bucket-name/*"
+            "Resource": "arn:aws:s3:::bucket-name*"
        }
    ]
}
```

This is not the same policy! In fact, this policy can have potential security issues as this is what it matches:
> BucketName | string like | bucket-name*

It matches any bucket that starts with `bucket-name`!

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**

aws-sdk-s3 (1.113.0)

**Version of Ruby, OS environment**
-paste the output of ruby -v

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]

**Comment by mullermp** [comment]
Related issue might help? https://github.com/aws/aws-sdk-ruby/issues/1338

**Comment by vfonic** [comment]
That could be it. I didn't have the mentioned permission, but I also had `s3:*` at some point so I'm not 100% sure. I don't have the time to confirm now. 

I'll close this issue, but feel free to double check.

**Comment by mullermp** [comment]
Based on the previous issue, I think it's just a consequence of the API/permissions. Even if we could change this, I couldn't, for backwards compatibility reasons. It was still fair to call this out.
