### ISSUE TITLE
undefined method `http_checksum=' for #<Seahorse::Model::Operation:0x00000000058c17c0>

### ISSUE THREAD

**Issue by M-Phansa** [aws/aws-sdk-ruby#2671]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
I'm using chef to install the aws-sdk-s3 gem and getting a compile error of 

"undefined method `http_checksum=' for #<Seahorse::Model::Operation:0x00000000058c17c0>"

my chef recipe has :
chef_gem 'aws-sdk-s3' do
  action :install
  compile_time true
end
require 'aws-sdk-s3'
and I saw all the dependencies got installed

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-s3'

**Version of Ruby, OS environment**
-paste the output of ruby -v
  System Info:
  ------------
  chef_version=16.5.77
  platform=amazon
  platform_version=2
  ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**To Reproduce (observed behavior)**
create a recipe with the following code
chef_gem 'aws-sdk-s3' do
  action :install
  compile_time true
end
require 'aws-sdk-s3'

All versions of what chef installed ->
Using aws-eventstream 1.2.0
Using aws-partitions 1.563.0
Using aws-sdk-core 3.128.0
Using aws-sigv4 1.4.0
Using jmespath 1.6.0
Using aws-sdk-kms 1.55.0
Using aws-sdk-s3 1.113.0

Seems related to this change ->
https://github.com/aws/aws-sdk-ruby/commit/7a6a0b41713825f351ddc61e36214339709920ba

I've tried downgrading the versions of the aws-sdk-s3 and aws-sdk-core and still am getting the issue.

I also tried uninstalled all the relevant gems from /opt/chef/embedded/bin/gem and reinstalling through chef via this
chef_gem 'aws-sdk-s3' do
  action :install
  compile_time true
end
require 'aws-sdk-s3'

Some package versions now with same failure
aws-sdk-s3-1.113.0
aws-sdk-core-3.128.0

On the instance I'm able to run my script via the ruby script directly as well using what chef installed
/opt/chef/embedded/bin/ruby aws-test.rb

The script is a simple s3 get object
```
require 'aws-sdk-s3'
client = Aws::S3::Client.new(<region>)
resp = client.get_object(
  response_target: '<target>',
  bucket: '<bucket>',
  key: "<key>",
)
```

Also another issue when running the ruby code
```
STDERR: /opt/chef/embedded/lib/ruby/2.7.0/delegate.rb:87:in `method_missing': undefined method `checksum' for #<Seahorse::Client::Response:0x00000000028ce298> (NoMethodError)
	from /tmp/s3_download.rb:13:in `<main>'
```

doing
```
if resp.checksum.checksum_sha256 != checksum_value
```

**Comment by alextwoods** [comment]
For the first error - I wasn't able to reproduce the issue with those versions - can you provide the output of the following when running the script with the error?
```
puts Aws::S3::GEM_VERSION
puts  Aws::CORE_GEM_VERSION
```
Was there any stack/trace information for that error?  


For the second error, I believe the code should be:
```
if resp.checksum_sha256 != checksum_value
```

It looks like you may also need to pass in `checksum_mode: 'ENABLED'` to the [`get_object`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#get_object-instance_method).

**Comment by M-Phansa** [comment]
I added the checksum_mode enabled and got a blank string for the checksum response (but it compiled).
```
resp = client.get_object(
  response_target: '<target>',
  bucket: '<bucket>',
  key: "<key>",
   checksum_mode: 'ENABLED'
)
puts resp.checksum_sha256 -> output is blank string
```

Versions ->
Aws::S3::GEM_VERSION - 1.113.0
Aws::CORE_GEM_VERSION - 3.128.0

Still getting an issue with this block re added

```
chef_gem 'aws-sdk-s3' do
  action :install
  compile_time true
end
require 'aws-sdk-s3'
```

**Comment by alextwoods** [comment]
When you did the `put_object` call for that object, did you set the `checksum_algorithm: 'SHA256'`? 

I'm not all that familiar with Chef, but the following Gemfile, which sets the versions to those you mentioned works for me.
```
source 'https://rubygems.org'

gem 'aws-sdk-s3', '1.113.0'
gem 'aws-sdk-core', '3.128.0'
```

Based on the error - it looks like you may be getting a different version of S3 and Core than those at require.

In the sample you provided above, what line is failing? and do you get any stacktrace?

**Comment by M-Phansa** [comment]
For the chef errors Setting this explicitly didn't help
```
chef_gem 'aws-sdk-core' do
 action :install
 compile_time true
 source 'https://rubygems.org'
 version '3.128.0'
end
chef_gem 'aws-sdk-s3' do
 action :install
 compile_time true
 source 'https://rubygems.org'
 version '1.113.0'
end
require 'aws-sdk-s3'
```

One thing about the chef stuff is installing those correct versions (which is what the program is reading from) but cannot resolve the requires statement. As far as I can tell chef is correctly installing the packages and versions but something in the Chef requires logic is breaking or broken now. For testing that block do you now anyone who has this set up?
https://docs.aws.amazon.com/opsworks/latest/userguide/cookbooks-101-opsworks-s3-vagrant.html
The chef code there
```
gem_package "aws-sdk ~> 3" do
  action :install
end
```
can be changed to `aws-sdk-s3` to match what I set up (there is a similar requires statement there too)


For the cide issue I'm using the get_object so it didn't accept the checksum_algorithm
argument.

There isn't a failure or stacktrace of the output here. This is the bulk of the script (up to failure point)
```
require 'aws-sdk-s3'
client = Aws::S3::Client.new(region: 'us-gov-west-1')
resp = client.get_object(
 response_target: '<target>',
 bucket: '<bucket>',
 key: "<key>",
 checksum_mode: 'ENABLED'
)
puts resp.checksum_sha256
```

The puts line just has a blank string

On the resp object I see this ->
```
:checksum_crc32=>nil, :checksum_crc32c=>nil, :checksum_sha1=>nil, :checksum_sha256=>nil,
```

**Comment by alextwoods** [comment]
I'm still trying to reproduce the issue with chef and require, but haven't been able to get any examples setup yet.

Before the require statement, can you print out the $LOAD_PATH, eg: `puts $LOAD_PATH`?

For the checksum_sha256 - the checksum value will only be set on an object when you upload it with the checksum to start (so you need to call `put_object` and set the `checksum_algorithm` parameter). See: https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/

**Comment by M-Phansa** [comment]
For checksum I didn't upload it with the checksum option so makes sense. For the checksum algorithm/caculation is supposed to be different than sha256sum function output?

~/Desktop ❯ sha256sum < test.txt
b58f34e73579dcfb700daacadd50fa7503f1e4c6c881cb4d720fe84a57be306d  -

AWS s3 sha256 checksum on console for test.txt
tY805zV53PtwDarK3VD6dQPx5MbIgctNcg/oSle+MG0=

**Comment by alextwoods** [comment]
The AWS/s3 computed checksum is base64 encoded - but they should be equal:

```
Base64.decode64('tY805zV53PtwDarK3VD6dQPx5MbIgctNcg/oSle+MG0=').unpack("H*")
# gives b58f34e73579dcfb700daacadd50fa7503f1e4c6c881cb4d720fe84a57be306d
```

**Comment by M-Phansa** [comment]
The checksum code worked as expected for me thanks.

**Comment by mullermp** [comment]
Is this resolved?

**Comment by M-Phansa** [comment]
No the chef gem issue is still open
```
chef_gem 'aws-sdk-s3' do
action :install
compile_time true
end
require 'aws-sdk-s3'
```

I was able to use the SDK outside of the require line not working. Was a fix pushed for that? I can re try running chef

**Comment by alextwoods** [comment]
I still have not been able to reproduce the issue with chef - I suspect something is getting the wrong versions (and while they may be installed, the correct versions may not all be getting used at the time you call `require`).  

Can you do the following:

```ruby
chef_gem 'aws-sdk-s3' do
  action :install
  compile_time true
end
puts $LOAD_PATH
require 'aws-sdk-core' # this should load
puts $LOADED_FEATURES.select { |p| p.include? 'aws-sdk-core.rb' }

require 'aws-sdk-s3'

```

**Comment by M-Phansa** [comment]
You are correct the require is pulling in a version of AWS CORE SDK we set in another cookbook. 
Output of the loaded features on aws-sdk-core
`[2022-03-11T20:28:21+00:00] INFO: ["/var/chef/cache/cookbooks/xgen-prometheus/files/default/vendor/gems/aws-sdk-core-3.112.0/lib/aws-sdk-core.rb"]`

Pulling from "xgen-prometheus" which has the library copied. Its not using the version in the /opt/embedded directory where the correct version is.

I will fix this on my own / its not a sdk issue thanks for the help.
