### ISSUE TITLE
describe_db_clusters for an aurora serverless DB not returning the VPC it is running in

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#2672]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
describe_db_clusters for an aurora serverless DB is not returning the VPC it is running in. Is this by design or just something missing in the API?

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk-rds

**Version of Ruby, OS environment**
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]

**To Reproduce (observed behavior)**
```Ruby
resp = client.describe_db_clusters({db_cluster_identifier: "MyCluster"}).db_clusters[0]
pp resp.to_h

{:allocated_storage=>1,
 :availability_zones=>["us-east-2b", "us-east-2c", "us-east-2a"],
 :backup_retention_period=>1,
 :database_name=>"test_db",
 :db_cluster_identifier=>"testdb",
 :db_cluster_parameter_group=>"default.aurora5.6",
 :db_subnet_group=>"default-vpc-23rtet0da18b1",
 :status=>"available",
 :earliest_restorable_time=>"2022 - 03 - 06 07 : 08 : 02.437 UTC",
 :endpoint=>"testdb.cluster-ssfsfsfwphx.us-east-2.rds.amazonaws.com",
 :multi_az=>false,
 :engine=>"aurora",
 :engine_version=>"5.6.10a",
 :latest_restorable_time=>"2022 - 03 - 07 13 : 44 : 51.164 UTC",
 :port=>3306,
 :master_username=>"xxxxxxx",
 :preferred_backup_window=>"06:58-07:28",
 :preferred_maintenance_window=>"sat:07:41-sat:08:11",
 :read_replica_identifiers=>[],
 :db_cluster_members=>[],
 :vpc_security_groups=>[{:vpc_security_group_id=>"sg-aaaaaaaaa", :status=>"active"}, {:vpc_security_group_id=>"sg-aaaaaaa", :status=>"active"}],
 :hosted_zone_id=>"XXXXXXXX",
 :storage_encrypted=>true,
 :kms_key_id=>"arn:aws:kms:us-east-2:",
 :db_cluster_resource_id=>"cluster-XXXX",
 :db_cluster_arn=>"arn:aws:rds:us-east-2:",
 :associated_roles=>[],
 :iam_database_authentication_enabled=>false,
 :cluster_create_time=>"2022 - 02 - 17 14 : 29 : 15.755 UTC",
 :capacity=>0,
 :engine_mode=>"serverless",
 :scaling_configuration_info=>{:min_capacity=>2, :max_capacity=>16, :auto_pause=>true, :seconds_until_auto_pause=>300, :timeout_action=>"RollbackCapacityChange", :seconds_before_timeout=>300},
 :deletion_protection=>false,
 :http_endpoint_enabled=>true,
 :activity_stream_status=>"stopped",
 :copy_tags_to_snapshot=>true,
 :cross_account_clone=>false,
 :domain_memberships=>[],
 :tag_list=>[],
 :auto_minor_version_upgrade=>false}
         
```

**Comment by peterwoodworth** [comment]
Hey @pchaganti,

I've reached out to the RDS service team about this. I'll provide updates for you when I have them 🙂 

Tracking: P60992552

**Comment by osdrv** [comment]
Hey @pchaganti, many thanks for the report. We might need some extra information if possible.

Firstly: is this cluster created with `PubliclyAccessible=true`? Could you please share your create-db-cluster command or a parameter set that were used in the SDK?

Secondly, could you please indicate the expected behavior? I.e. what is expected to be observed in the output: it will simplify our understanding of whether this is a legitimate behavior or not.

Thank you.

**Comment by pchaganti** [comment]
The cluster was created using the AWS console. It is a PubliclyAccessible cluster. Expected behavior is that the describe_db_clusters returns the VPC that the cluster is in. It returns the vpc sec groups, so the vpc information must already be available and just not surfaced?

**Comment by osdrv** [comment]
@pchaganti thank you for the clarification. Indeed, `DescribeDBClusters` contains no `VpcId`: it returns `DBSubnetGroup` instead. The subnet group is supposed to serve the aggregation role in relation chain `DBCluster <-> DBSubnetGroup <-> VPC`, hence it is not a part of `DescribeDBClusters` output. The corresponding DB subnet group object contains the `VpcId` this cluster is in. Hope it makes sense.

**Comment by peterwoodworth** [comment]
Thanks a bunch @osdrv !
