### ISSUE TITLE
Massive data loss caused by object.put with just content type

### ISSUE THREAD

**Issue by KieranP** [aws/aws-sdk-ruby#2684]
### Describe the bug

We needed to update the content type of a bunch of files. So we ran:

```
object.put(content_type: '....')
```

on all of the files returned by bucket.objects.

Initially it seemed to work fine. However, after the script completed running, we found that all the files (638) of them, had been completely zero'd out, blank, 0 bytes.

This has resulted in massive data loss. I would understand this if we had passed `body: nil` to the put command, but we did not. Only updated the content type.

### Expected Behavior

It should update only the content type, not clear the document contents

### Current Behavior

It updates the content type, but also clears the file

### Reproduction Steps

`object.put(content_type: 'application/pdf')`

### Possible Solution

Either allow partial updates properly, or throw an error when updating in this way would clear the S3 file content

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 version 3

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.5, OS Ubuntu

**Comment by mullermp** [comment]
I am very sorry you encountered data loss. Unfortunately S3's put_object is exactly that, a PUT request for Object, and not PATCH for partial update. Body is nil by default because empty objects are valid. When you mentioned it seemed to work fine, did you try this command on a small set of files to confirm that it worked as intended? Are you able to recover your data (from versioning or other means)?

To update the content type as you are describing, you would first need to call get_object (`get` on the Resource's object) and rewrite all of the fields on `put`, including the body, content_type, acl, checksums, permissions, etc.

**Comment by alextwoods** [comment]
I'm also extremely sorry you ran into that data loss - I agree the documentation/method name here is confusing.

Just to add to @mullermp's recommendation (and for anyone coming across this) - you can use the [S3#copy_object ](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#copy_object-instance_method)method to avoid having to call get_object and getting the data locally.

**Comment by KieranP** [comment]
@mullermp

> Unfortunately S3's put_object is exactly that, a PUT request for Object, and not PATCH for partial update
> Body is nil by default because empty objects are valid

This is not clearly indicated by the documentation. In the absence of any patch/update method, I wouldn't be surprised if others run into this issue in the future trying to update files.

I would recommend making body a required attribute to avoid this sort of thing happening. That way, people must explicitly pass `body: nil`, rather than defaulting to that.

> did you try this command on a small set of files to confirm that it worked as intended

We had and it appeared to have worked properly before we ran it on the rest of them. When we were debugging this, we ran the put request on a single object and the file size in the UI appeared to remain unchanged even though the content type was reflecting correctly, until a minute later, when we refreshed and file size was 0. So it's possible that some sort of caching on AWS end resulted in the wrong file size reported for a short while after an object put request.

> Are you able to recover your data (from versioning or other means)?

Unfortunately not. The data came from user uploads and versioning was off on this bucket (we have since turned it on), so we've had to reach out to the affected users and ask them to re-upload.

@alextwoods 

> you can use the S3#copy_object method to avoid having to call get_object and getting the data locally

This seems like a rather obtuse way of updating a file. I take it then that AWS API does not include a way to directly update a files metadata such as content type. I'd also recommend that this alternative should be clearly communicated at the top of the put method documentation as a warning so others don't fall into the same trap.

**Comment by mullermp** [comment]
We cannot make body a required attribute. The required-ness of API members comes from the API model, and doing so to S3 would be a majorly breaking change. I can forward this to the S3 doc writing team and see if they can add a clause that can avoid this issue (and it would be reflected across all AWS SDK products).

**Comment by mullermp** [comment]
I've opened a ticket with the docs team. They've mentioned that this is already (mostly) covered in the put_object documentation:

"Amazon S3 never adds partial objects; if you receive a success response, Amazon S3 added the entire object to the bucket."

But they agreed they can add some more warning and clarification around what a "partial object" means. They should have a new docs change in the coming few weeks.
