### ISSUE TITLE
SigV4 sign_request method ALWAYS appends SHA256 hash to the end of canonical request

### ISSUE THREAD

**Issue by yutveg** [aws/aws-sdk-ruby#2695]
### Describe the bug

The Aws::Sigv4::Signer sign_request method will always append the SHA256 value to the end of the canonical request. But AWS is returning an error which implies this last string in the canonical request should be different than the SHA256.

You can see this logic in the following method:

```ruby
# https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sigv4/lib/aws-sigv4/signer.rb
 def canonical_request(http_method, url, headers, content_sha256)
        [
          http_method,
          path(url),
          normalized_querystring(url.query || ''),
          canonical_headers(headers) + "\n",
          signed_headers(headers),
          content_sha256
        ].join("\n")
      end
```

### Expected Behavior

I can't say what the intended function should be without knowing how AWS internal Selling Partner API is working, but if we assume it is working as intended then my error message indicates the private `canonical_request` function has a bug.

### Current Behavior

Here is the response I'm receiving from the Selling Partners API.

```
The Canonical String for this request should have been
'GET
/asdf123

host:sandbox.sellingpartnerapi-na.amazon.com
x-amz-access-token:xxxxxxx
x-amz-content-sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
x-amz-date:20220425T190929Z
x-amz-security-token:xxxxxxx

host;x-amz-access-token;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' # <- appended SHA256 hash
```

Please note that the `x-amz-content-sha256` value is different than the SHA256/hash shown at the end of the canonical request string.

### Reproduction Steps

Can't really provide a reproducible example because there's a lot of context in the IAM user/roles. But in short, I'm using STS to get temporary credentials for a role that can use the Selling Partner API. I then pass the temporary STS credentials into the Signer class, and when I sign the request and attach the headers I get the above response.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

gem 'aws-sdk-core', '~> 3'

### Environment details (Version of Ruby, OS environment)

Ruby 2.7, Ubuntu 20.04, SAM local-api

**Comment by mullermp** [comment]
Thanks for opening an issue. Is this the product you are referring to? https://aws.amazon.com/quickstart/architecture/amazon-selling-partner-api/

The Sigv4 signer class is intended to be used with services that are onboarded to AWS SDKs. This looks entirely different. We will have to take a look and see what the requirements are to make a request to that API.

**Comment by yutveg** [comment]
That is indeed the product, they mention in their docs that [they use Signature V4 and that you can use an SDK to handle signing](https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-4-create-and-sign-your-request), though their example uses Java specifically.

**Comment by mullermp** [comment]
Can you share how you're using the sigv4 signer to generate signatures and append headers to the request? Are there additional headers that are being added by whatever HTTP client you are using?

**Comment by alextwoods** [comment]
Its a bit hard to know without more details on the code you're using to create the signature and request, but, there are a number of options when creating a signer, you may need to change those to meet the expectations of the service: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html#initialize-instance_method

Are you providing the x-amz-content-sha256 header value?  

Its possible the selling partner API is not correct, the canonical request must have the computed hash value for the payload of the request last, see: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Comment by yutveg** [comment]
Hey apologies for the delay, here's the relevant code. 

```ruby
def get_session_credentials
  response =
    @sts_client.assume_role(
      {
        role_arn: 'arn:aws:iam::XXXXXXXXXX:role/SellingPartnerAPIRole',
        role_session_name: 'assumeRoleSessionTest'
      }
    )
  return response.to_h[:credentials]
end
  
def get_request_signature(uri, method, body, access_token, credentials)
  signer =
    Aws::Sigv4::Signer.new(
      service: 'execute-api',
      region: 'us-east-1',
      access_key_id: credentials[:access_key_id],
      secret_access_key: credentials[:secret_access_key],
      session_token: credentials[:session_token]
    )

  signature =
    signer.sign_request(
      url: @base_endpoint + uri,
      headers: {
        'x-amz-access-token' => access_token
      },
      http_method: method,
      body: body.to_json
    )

  return signature
end

def create_request(uri:, method:, headers: {}, body: {})
  # Getting session credentials and access token
  credentials = get_session_credentials
  access_token = @sp_authorizer.get_access_token

  signature =
    get_request_signature(uri, method, body, access_token, credentials)

  response =
    HTTParty.public_send(
      method.downcase.to_sym,
      @base_endpoint + uri,
      headers: {
        'host' => signature.headers['host'],
        'x-amz-access-token' => access_token,
        'x-amz-security-token' => signature.headers['x-amz-security-token'],
        'x-amz-date' => signature.headers['x-amz-date'],
        'x-amz-content-sha256' => signature.headers['x-amz-content-sha256'],
        'authorization' => signature.headers['authorization']
      },
      timeout: 60
    )
  puts response.body
end
  ```
I've omitted some of the class but hopefully this is sufficient for you guys to see what's going on. STS is providing temporary credentials for a role [that has the following policy attached](https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities#step-3-create-an-iam-policy) which allows it to invoke the SP-API. This is what is [recommended in their docs](https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities), and while I'm waiting to confirm with support whether our configuration is correct, I have a pretty high amount of certainty that it is for what that's worth.

The temporary credentials are passed into the signer, and I attach the headers to the httparty request. I've previously examined the request with wireshark and can't recall it adding any additional headers, though httparty does capitalize headers Like-This. Even monkeypatching that to keep them downcased does not have an effect.

And to respond to Alex, that is my concern. Worst case if you guys think it may help I can provide some more info about the request from Wireshark, but it is pretty odd that the hashes don't match up from the API response. It could just be that they mistakenly send back the exact `x-amz-content-sha256` that YOU sent even if it's wrong, but if so it makes debugging difficult. I have messaged their team through support about this

**Comment by alextwoods** [comment]
I'm not familiar with `HTTParty`, but how are you sending the body in that request?  eg:
```
  response =
    HTTParty.public_send(
      method.downcase.to_sym,
      @base_endpoint + uri,
      headers: {
        'host' => signature.headers['host'],
        'x-amz-access-token' => access_token,
        'x-amz-security-token' => signature.headers['x-amz-security-token'],
        'x-amz-date' => signature.headers['x-amz-date'],
        'x-amz-content-sha256' => signature.headers['x-amz-content-sha256'],
        'authorization' => signature.headers['authorization']
      },
      timeout: 60
    )
```

I don't see body being passed into this.  Additionally - I see you're doing `body: body.to_json` when creating the signature.  It could be that sending the body later does a different serialization (ie, if different json libraries or parameters are used you could end up with slightly different characters).  I'd consider serializing body to a string before signing and sending and only using that.

**Comment by yutveg** [comment]
> I don't see body being passed into this. Additionally - I see you're doing `body: body.to_json` when creating the signature. It could be that sending the body later does a different serialization (ie, if different json libraries or parameters are used you could end up with slightly different characters). I'd consider serializing body to a string before signing and sending and only using that.

Welp looks like that was the issue. Good catch- was sending a GET request so blanked on adding a body. Thanks
