### ISSUE TITLE
Where is the QLDB Driver?

### ISSUE THREAD

**Issue by mathieujobin** [aws/aws-sdk-ruby#2705]
### Describe the issue

API Doc on QLDBSession recommend using the QLDB Driver instead

was that ever made?

where can I find it ? 

### Links

https://github.com/aws/aws-sdk-ruby/blob/a3250201da9bc7802ee723fde821a8d40a1fc1ee/gems/aws-sdk-qldbsession/lib/aws-sdk-qldbsession/client.rb#L366-L375

**Comment by mullermp** [comment]
This documentation comes directly from the service API. I don't believe QLDB supports this for Ruby. https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started-driver.html. Additionally there is no Ruby Ion support, though it's backlogged by the Ion team. I imagine you can use QLDB without it, and possibly see how the driver works in other languages.

**Comment by mathieujobin** [comment]
We are working on a MiniDriver with basic functionality which includes some Ion support as well.

Thank you

**Comment by mullermp** [comment]
Closing because the documentation links to the "getting started" page which unfortunately does not list Ruby. Leaving label as "blocked"
