### ISSUE TITLE
SES Keepalive for Sending Many Messages

### ISSUE THREAD

**Issue by DavidAllison** [aws/aws-sdk-ruby#271]
It would be great to get a way to enable keepalive for API requests when using the AWS SES gem to send emails through ActionMailer. 

This could be particularly useful for users who do not have their servers located in the US-East region, since SES is only located in that region, and establishing a connection to US-east's SES servers can take time (sometimes several hundred milliseconds) from other regions.

**Comment by rainerborene** [comment]
@trevorrowe Sorry for bringing this up again. But I can't find any examples of this feature being used. How I would use it with Sidekiq for example?

**Comment by trevorrowe** [comment]
@rainerborene I'm not sure what you are asking. The `aws-sdk` gem uses Net::HTTP as the default http handler. It also manages a pool of persistent connections, and these connections rely on Net::HTTP's support of keep alive.

**Comment by rainerborene** [comment]
Take for example this piece of code. How many connections the pool will hold?

```ruby
class MailWorker
  def perform
    @ses = Aws::SES::Client.new
    @ses.send_raw_email(...)
  end
end

10.times do |new|
  MailWorker.new.perform
end
```

What I am asking is how to ensure that persistent connections are being used by other threads in my application? How do I configure these pool of connections?

**Comment by trevorrowe** [comment]
@rainerborene Exactly one connection. If you replaced the `10.times` block with something using threads to make requests concurrently, then there would be 10 connections. The internal pool is shared across clients and will grow to match the number of concurrent requests.
