### ISSUE TITLE
File's content type not set properly while uploading a file to S3

### ISSUE THREAD

**Issue by AnkurVyas-BTC** [aws/aws-sdk-ruby#2714]
### Describe the bug

Recently we updated the gem version from `1.67.0` to `1.113.0`.

When we upload a PDF file via `Aws::S3::Object#upload_file` method, the `content_type` is not set properly. See code below

```ruby
S3_BUCKET = Aws::S3::Resource.new.bucket(bucket_name)
local_file = "#{@order.number}.pdf" # any pdf file
S3_BUCKET.object("edi/#{document_label}").upload_file(local_file)
```

Now when we upload a pdf file via the above method, the "content-type" is not set by AWS S3. And when we click on the object URL it downloads the file instead of opening it in a new tab. 

While in our previous version `1.67.0` the file's content type was set as `application/pdf` automatically when we uploaded it using the `Aws::S3::Object#upload_file` method.

### Expected Behavior

The file's content type should be set automatically like it used to be in previous versions!

### Current Behavior

The file's content type is not set properly

### Reproduction Steps

We can test with the following ruby code

```ruby
S3_BUCKET = Aws::S3::Resource.new.bucket(bucket_name)
local_file = "#{@order.number}.pdf" # any pdf file
S3_BUCKET.object("edi/#{document_label}").upload_file(local_file)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.5, Linux

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm not able to reproduce this. I'm fairly sure that content type is not supposed to be set automatically. The content type for that old version is set as **content_type="binary/octet-stream"**.

```
irb(main):001:0> require 'aws-sdk-s3'
=> true
irb(main):002:0> S3_BUCKET = Aws::S3::Resource.new.bucket('[redact]')
=> #<Aws::S3::Bucket:0x00007fa9f98a09d0 @name="[redact]", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @arn=nil>
irb(main):003:0> S3_BUCKET.object("old-test.pdf").upload_file("/path/to/sample.pdf")
=> true
irb(main):004:0> Aws::S3::GEM_VERSION
=> "1.67.0"
irb(main):005:0> S3_BUCKET.object("old-test.pdf").get
=> #<struct Aws::S3::Types::GetObjectOutput body=#<StringIO:0x00007fa9f8aef9d0>, delete_marker=nil, accept_ranges="bytes", expiration=nil, restore=nil, last_modified=2022-06-13 14:27:44 +0000, content_length=3028, etag="\"4b41a3475132bd861b30a878e30aa56a\"", missing_meta=nil, version_id="null", cache_control=nil, content_disposition=nil, content_encoding=nil, content_language=nil, content_range=nil, content_type="binary/octet-stream", expires=nil, expires_string=nil, website_redirect_location=nil, server_side_encryption=nil, metadata={}, sse_customer_algorithm=nil, sse_customer_key_md5=nil, ssekms_key_id=nil, storage_class=nil, request_charged=nil, replication_status=nil, parts_count=nil, tag_count=nil, object_lock_mode=nil, object_lock_retain_until_date=nil, object_lock_legal_hold_status=nil>
```

**Comment by mullermp** [comment]
I'm not certain how it was PDF in your application before. S3 recommends setting your content type explicitly. If you know that you are going to be working with PDF, you can pass `content_type: 'application/pdf'` into `upload_file`.

**Comment by AnkurVyas-BTC** [comment]
@mullermp: Yes passing `content-type` certainly works, see below.

```ruby
S3_BUCKET = Aws::S3::Resource.new.bucket(bucket_name)
local_file = "#{@order.number}.pdf" # any pdf file
S3_BUCKET.object("edi/#{document_label}").upload_file(local_file, { content_type: "application/pdf" })
```

Above works like a charm. Thanks, @mullermp :+1: 

I have checked the file uploaded by the older version and the new version

### Metadata for the old version

![S3 old version](https://user-images.githubusercontent.com/7837010/173385322-ab10305f-a9f6-46ae-af0c-895852ed7807.png)

This was opening the PDF in the new tab ( and not downloading it )

### Metadata for the new version
![S3 new version](https://user-images.githubusercontent.com/7837010/173385396-0b4a6bec-2f0c-49b5-bcbf-3724dd68a26c.png)

This is not opening the PDF in a new tab and downloading it instead.

I think it was working before because the `content-type` was set as blank by AWS S3 ?? :thinking: 

And now in the new version as the metadata is set as **content_type="binary/octet-stream"**, so it is downloading it.

**Comment by mullermp** [comment]
Ah yeah, the blank content type makes sense. The "type" (not the same thing) is still picked up as pdf. Was that file from 2019 uploaded 3 years ago or did you try uploading that same file again recently?

From my output above, even with the old version, S3 defaulted to octet-stream as a content type. Adding that default content type may have been a behavior change from S3. There wouldn't have been any change in the Ruby SDK that could affect that.

I'm glad using content type explicitly works for you.

**Comment by AnkurVyasAce** [comment]
@mullermp - No that file was uploaded 3 years ago. And in changes history, I see below

Old (16 months ago)

```ruby
    aws-sdk-s3 (1.67.0)
      aws-sdk-core (~> 3, >= 3.96.1)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.1)
```

Now 

```ruby
    aws-sdk-s3 (1.113.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
```

And I also have a strong feeling that S3 defaults have got changed in between. Thank you so much for the help and clarification, we will make sure to pass explicit `content_type` from now :+1:
