### ISSUE TITLE
Performance regression in `aws-sigv4` 1.5.0

### ISSUE THREAD

**Issue by johnduhart** [aws/aws-sdk-ruby#2729]
### Describe the bug

While doing performance profiling of our application which manually performs AWS SigV4 signing (for Amazon Neptune), we noticed a measurable amount of time being spent in [`Signer.use_crt?`](https://github.com/aws/aws-sdk-ruby/blob/8ee8aa05acddca285817e2c7a2b26282687744ff/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L835). 

![image](https://user-images.githubusercontent.com/113642/179433096-3fcf741c-bde9-4b35-8b5c-d5ebe900e1d0.png)

Looking closer, it appears to be calling `require` on each invocation.

![image](https://user-images.githubusercontent.com/113642/179433556-76c41269-46c7-4f4a-9672-f039cff01113.png)

We deployed a build with `aws-sigv4` rolled back to `1.4.0`, and we noticed a large improvement on the lower latency percentiles for calls to Amazon Neptune (latency includes signing, the HTTP request, and serialization).

| `aws-sigv4` version | `1.4.0` | `1.5.0` |
| --------------------- | ------ | ------- | 
| P25 | 5ms | 16ms |
| P50 | 5ms | 17ms |
| P75 | 6ms | 19ms |
| P90 | 7ms | 22ms |

Memoizing the `use_crt?` call would fix this issue. Installing and using the AWS CRT might also improve things, but given it's labeled as a [developer preview](https://github.com/awslabs/aws-crt-ruby), we decided to just rollback for now.

### Expected Behavior

The same performance characteristics as 1.4.0

### Current Behavior

Worsened performance.

### Reproduction Steps

Benchmark the performance of `sign_request` between 1.4.0 and 1.5.0.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sigv4

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.6, Linux

**Comment by alextwoods** [comment]
Thanks for the detailed report - I'll work on a fix!
