### ISSUE TITLE
"Profile `default' not found in ~/.aws/credentials" in version 3.130 

### ISSUE THREAD

**Issue by anuragatgoldcast** [aws/aws-sdk-ruby#2734]
### Describe the bug

'default' profile exists both in `~/.aws/credentials` and `~/.aws/config` files as follows

```
--------------  ~/.aws/credentials ------------------
[default]
aws_access_key_id = XXXXX
aws_secret_access_key = XXXXX
```

```
--------------  ~/.aws/config ------------------
[profile default]                (Tried [default] also)
region = us-east-1
output=json
```

I am using the fluent-plugin-kinesis and `td-agent.conf` is as follows

```
<match a.b.c>
  @type copy
  <store>
      @type stdout
  </store>
  <store>
    @type kinesis_streams
    stream_name XXXXXXX
    region us-east-1
    <buffer>
      chunk_limit_size 1m
      flush_interval 5s
      flush_thread_count 2
    </buffer>
    <shared_credentials>
      path         ~/.aws/credentials
      profile_name       default
    </shared_credentials>  
  </store>
</match>
```

Some changes were made recently in regard to the shared credentials as seen in the PR [here](https://github.com/aws/aws-sdk-ruby/pull/2662). It seems like there could be a bug in the code because when I downgraded the `aws-sdk-core` from  3.130 to 3.125, it worked, and there is no error.

### Expected Behavior

`default` profile credentials should be read without any errors if the information in `~/.aws/credentials` and `~/.aws/config` files is correct.

### Current Behavior

An error is thrown saying "Profile `default' not found in ~/.aws/credentials"

### Reproduction Steps

1. Install td-agent in MAC via [dmg](https://docs.fluentd.org/installation/install-by-dmg)
2. Install the fluent-plugin-kinesis 
```
sudo /opt/td-agent/usr/sbin/td-agent-gem  install fluent-plugin-kinesis
```
3. Add the config to tail a log file
```
<source>
  @type tail
  <parse>
    @type json
  </parse>
  path /var/log/XXXX.log
  tag a.b.c
</source>

<match a.b.c>
  @type copy
  <store>
      @type stdout
  </store>
  <store>
    @type kinesis_streams
    stream_name XXXX
    region us-east-1
    <buffer>
      chunk_limit_size 1m
      flush_interval 5s
      flush_thread_count 2
    </buffer>
    <shared_credentials>
      path         ~/.aws/credentials
      profile_name       'default'
    </shared_credentials>  
  </store>
</match>
```
4. start the td agent
```
sudo /opt/td-agent/usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --use-v1-config --under-supervisor --verbose 
```

### Possible Solution

Review the validate method which has been added recently

```
    def validate_profile_exists(profile)
      unless (@parsed_credentials && @parsed_credentials[profile]) ||
             (@parsed_config && @parsed_config[profile])
        msg = "Profile `#{profile}' not found in #{@credentials_path}"\
              "#{" or #{@config_path}" if @config_path}"
        raise Errors::NoSuchProfileError, msg
      end
    end
```    
    

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core 3.130

### Environment details (Version of Ruby, OS environment)

Mac OS Big Sur

**Comment by mullermp** [comment]
Closed as this is duplicate.
