### ISSUE TITLE
Issue after release #2747

### ISSUE THREAD

**Issue by robertino** [aws/aws-sdk-ruby#2748]
### Describe the bug

When ENV['_X_AMZN_TRACE_ID'] is not set, new code is failing (where it did not)

### Expected Behavior

It seems like it should be backwards compatible, i.e. still working without ENV['_X_AMZN_TRACE_ID'] being set, as before

### Current Behavior

When `ENV['_X_AMZN_TRACE_ID']` is not set the call:
https://github.com/aws/aws-sdk-ruby/commit/b4171593cb8920592fa3fdde6c05de50fb23424d#diff-0a5092116efdc0d37df6db19c9f65f496de3e1a485f3a77f5ff028eeb47b9cdcR23
fails:
`header_value.chars`
as `header_value` is `nil`

### Reproduction Steps

we've run into it while running lambda, however I believe if could manifest itself in multiple scenarios

### Possible Solution

PR:
https://github.com/aws/aws-sdk-ruby/pull/2749

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

all

**Comment by robertino** [comment]
PR with fix: https://github.com/aws/aws-sdk-ruby/pull/2749

**Comment by alextwoods** [comment]
Thanks for the fix!  I've approved and it should be released today.
