### ISSUE TITLE
Aws::AutoScaling::Client#describe_auto_scaling_groups: filtering works inconsistently

### ISSUE THREAD

**Issue by mrchucho** [aws/aws-sdk-ruby#2753]
### Describe the bug

Using `#describe_auto_scaling_groups` to filter by tags works, but only sometimes. When it fails to find matching ASGs, I am able to run the equivalent command with the CLI and get matches.

### Expected Behavior

`#describe_auto_scaling_groups` should return the same results as the CLI when filtering on tags.

### Current Behavior

No errors, just no matches -- when matches exist.

### Reproduction Steps

Difficult to reproduce because the SDK works for some ASGs but not others. It is not clear why some work and others don't (as all work fine w/ the CLI). ASGs in question are identically created / provisioned via the same CloudFormation template.

```ruby
2.6.6p146 :006 > Aws::AutoScaling::Client.new.describe_auto_scaling_groups(filters: [{name: "tag:client", values: %w(client)}]).auto_scaling_groups.count
 => 0 
2.6.6p146 :007 > Aws::AutoScaling::Client.new.describe_auto_scaling_groups(filters: [{name: "tag:client", values: %w(different-client)}]).auto_scaling_groups.count
 => 50 
```

```
$ aws autoscaling describe-auto-scaling-groups --filters Name=tag:client,Values=client --query "length(AutoScalingGroups)"
20
$ aws autoscaling describe-auto-scaling-groups --filters Name=tag:client,Values=different-client --query "length(AutoScalingGroups)"
50
```

### Additional Information/Context

```
aws --version    
aws-cli/2.4.3 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core (3.146.0) aws-sdk-autoscaling (1.80.0)

### Environment details (Version of Ruby, OS environment)

ruby 2.6.6

**Comment by mullermp** [comment]
I think the simple answer is that DescribeAutoScalingGroups is paginated, and the CLI is paginating all values on your behalf. Count will also only report what has been returned on that first page. You can call .to_a on the response and it should collect all of the tags.

**Comment by mrchucho** [comment]
> I think the simple answer is that DescribeAutoScalingGroups is paginated, and the CLI is paginating all values on your behalf. Count will also only report what has been returned on that first page. You can call .to_a on the response and it should collect all of the tags.

Unfortunately, it looks like `#describe_auto_scaling_groups` is returning nothing:

```ruby
2.6.6p146 :002 > Aws::AutoScaling::Client.new.describe_auto_scaling_groups(filters: [{name: "tag:client", values: %w(client)}]).auto_scaling_groups.to_a
 => [] 
```

I was just using count as an easy way to show that sometimes there are zero results.

**Comment by alextwoods** [comment]
The first page of results may be empty (even if there are more results).  Can you check the response and see if there is a next_token set? 

As @mullermp  suggested, try calling `to_a` on the response before trying to get the tags.

**Comment by mrchucho** [comment]
Ah, yep, there was a `next_token` and paging through the results gave me the expected results. I've been using the AWS SDK for Ruby for years and that's the first time I've encountered that, 😅 

Thanks for the guidance!

**Comment by mullermp** [comment]
The tagging features on services need to be ultra quick, so they'll return sparse responses, and promise to give you more through pagination. It's a bit weird but understandable for latency. The Ruby SDK should have an option to disable pagination and collect all results IMO.
