### ISSUE TITLE
attributes not being sent start_outbound_voice_contact

### ISSUE THREAD

**Issue by AnassKartit** [aws/aws-sdk-ruby#2764]
### Describe the bug

 response = client.start_outbound_voice_contact({
 destination_phone_number: 'REDACTED',
  contact_flow_id: 'REDACTED',
  instance_id: 'REDACTED',
  source_phone_number: 'REDACTED',
  attributes: {
    "AttributeName" => "AttributeValue",
  }
  
})

### Expected Behavior

to send the attributes and see them in cloud watch

### Current Behavior

not visible and not sent in cloudwatch.
Test is successful though using Postman and REST API.
{
 
   "ContactFlowId": "REDACTED",
   "InstanceId": "REDACTED",
    "SourcePhoneNumber":"REDACTED",
   "DestinationPhoneNumber": "REDACTED",
   "Attributes": {
      "AttributeName" : "AttributeValue"
   }
}

### Reproduction Steps

send attributes using ruby v3 and  gem aws connect sdk 1.77.0

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-connect -v 1.77.0

### Environment details (Version of Ruby, OS environment)

macos ruby 3.0.0

**Comment by alextwoods** [comment]
When I make a call using the SDK, it looks like the attributes are correctly serialized on the request to me.  The request body ends up as:

```json
{
	"DestinationPhoneNumber": "REDACTED",
	"ContactFlowId": "REDACTED",
	"InstanceId": "REDACTED",
	"ClientToken": "7aeeb6c9-874a-4587-887e-1df00a016ab4",
	"SourcePhoneNumber": "REDACTED",
	"Attributes": {
		"AttributeName": "AttributeValue"
	}
}
```

Is the JSON you pasted above exactly what you used for successful calls with postman?  Can you enable wirelogging in the SDK and provide the output (note, it won't include the serialized body, but will include a lot of other low level information).  You can so do when creating the client with the `http_wire_trace` config option: `Aws::Connect::Client.new( http_wire_trace: true)`

**Comment by AnassKartit** [comment]
opening connection to connect.eu-central-1.amazonaws.com:443...
opened
starting SSL for connect.eu-central-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "PUT /contact/outbound-voice HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.158.0 ruby/3.0.0 x86_64-darwin21 aws-sdk-connect/1.77.0\r\nContent-Type: application/json\r\nHost: connect.eu-central-1.amazonaws.com\r\nX-Amz-Date: 20221006T154829Z\r\nX-Amz-Content-Sha256: abcd\r\nAuthorization: AWS4-HMAC-SHA256 Credential=AAAA/20221006/eu-central-1/connect/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=fe6faa494f295288fa8365bb42e459e64daf2e3c927ef980797a0a06780c9afb\r\nContent-Length: 284\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Date: Thu, 06 Oct 2022 15:48:30 GMT\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 52\r\n"
-> "Connection: keep-alive\r\n"
-> "x-amzn-RequestId: 638923a6-f993-4274-a462-5376650ed5dd\r\n"
-> "Access-Control-Allow-Origin: *\r\n"
-> "Access-Control-Allow-Headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token\r\n"
-> "x-amz-apigw-id: ZlvQJEuJFiAFlAA=\r\n"
-> "Access-Control-Allow-Methods: GET,OPTIONS,POST\r\n"
-> "Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType\r\n"
-> "X-Amzn-Trace-Id: Root=1-633ef8cd-47863ccb7bc7207d49812977\r\n"
-> "\r\n"
reading 52 bytes...
-> "{\"ContactId\":\"000-c8cf-4347-9f7b-000\"}"
read 52 bytes
Conn keep-alive

**Comment by AnassKartit** [comment]
any way to construct the payload using json instead of seahorse and compare by directly sending PUT TO REST API endpoint? @alextwoods

**Comment by alextwoods** [comment]
Theres not really a way to construct the payload manually as that would break signing.  To print out the payload being sent, you can do:

```ruby
class LogRequestBody < Seahorse::Client::Plugin
  def add_handlers(handlers, cfg)
    handlers.add(Handler, step: :sign, priority: 1)
  end
  class Handler < Seahorse::Client::Handler
    def call(context)
      puts context.http_request.body.read
      context.http_request.body.rewind
      @handler.call(context)
    end
  end
end
Aws::Connect::Client.add_plugin(LogRequestBody)
client = Aws::Connect::Client.new(...)
client.start_outbound_voice_contact(...)
```

**Comment by mullermp** [comment]
Are you still seeing this issue? Any new information? I agree with Alex that the SDK is currently serializing all of the members to JSON correctly.

**Comment by AnassKartit** [comment]
we can close this

**Comment by mullermp** [comment]
Thanks for reaching back out. Do you mind sharing the issue/solution, for anyone that might come across this?

**Comment by AnassKartit** [comment]
The issue is that the attributes are not shown in cloudwatch unless explicitly set by the callflow task pointing to the exact attribute
