### ISSUE TITLE
SIP Media Application create call missing SipHeaders in lambda event

### ISSUE THREAD

**Issue by Aeramor** [aws/aws-sdk-ruby#2765]
### Describe the bug

SipHeaders are not available in lambda after invoking client.create_sip_media_application_call from ruby.

### Expected Behavior

Expected to see events populated with sipheaders as per documentation

### Current Behavior

Have checked all events and non contain the sip headers passed in. 
```
"event": {
    "SchemaVersion": "1.0",
    "Sequence": 1,
    "InvocationEventType": "NEW_OUTBOUND_CALL",
    "CallDetails": {
      "TransactionId": "8fcbb2e8-ca5b-4865-b450-2db75024b16c",
      "AwsAccountId": "xxx",
      "AwsRegion": "us-east-1",
      "SipMediaApplicationId": "<sip_app_id>",
      "Participants": [
        {
          "CallId": "f27891d7-1f24-4c54-92db-72b9118401a6",
          "ParticipantTag": "LEG-A",
          "To": "+xxx",
          "From": "+xxx",
          "Direction": "Outbound",
          "StartTimeInMilliseconds": "1665392668105"
        }
      ]
    }
  }
```

### Reproduction Steps

```
@client = Aws::Chime::Client.new(region: REGION)
    call_params = {
      from_phone_number: from_number, # E164PhoneNumber - required
      to_phone_number: to_number, # E164PhoneNumber - required
      sip_media_application_id: SIP_MEDIA_APP_ID, # required
      sip_headers: { "x-test": "test"}
    }
    resp = @client.create_sip_media_application_call(call_params)
```

### Possible Solution

// Edit
Incase anyone finds this in the future I'm getting around this limitation by doing:
```
resp2 = @client.update_sip_media_application_call({ # https://docs.aws.amazon.com/chime-sdk/latest/dg/update-sip-call.html
      sip_media_application_id: SIP_MEDIA_APP_ID,
      transaction_id: resp.sip_media_application_call.transaction_id, # required
      arguments: sip_headers # the original headers I wanted in the call.
    })
```
### Additional Information/Context

```
<- "POST /sip-media-applications/<sip_app_id>/calls HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.159.0 ruby/2.7.6 x86_64-linux aws-sdk-chime/1.68.0\r\nContent-Type: application/json\r\nHost: chime.us-east-1.amazonaws.com\r\nX-Amz-Date: 20221010T090427Z\r\nX-Amz-Security-Token: <omit> X-Amz-Content-Sha256: e29cd1263116a3593a78f1da059af4449a401960cccf4a5ce7b1e75553476d4a\r\nAuthorization: AWS4-HMAC-SHA256 Credential=<omit>/20221010/us-east-1/chime/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=bb2eafcf842e1ae85ff17fc59f7c284483415f5798c1d620743547ed6e7fdb98\r\nContent-Length: 145\r\nAccept: */*\r\n\r\n"
23:04:27 web.1  | <- "{\"FromPhoneNumber\":\"+<sipnumber>\",\"ToPhoneNumber\":\"+<tonumber>\",\"SipHeaders\":{\"x-seq\":\"\",\"x-meeting_id\":\"8a2b0c1f-be06-4100-8942-93020b3c0706\"}}"
23:04:27 web.1  | -> "HTTP/1.1 201 Created\r\n"
23:04:27 web.1  | -> "x-amzn-RequestId: 8e55a7d3-3743-4f32-bb78-9132e0dd9da9\r\n"
23:04:27 web.1  | -> "Content-Type: application/json\r\n"
23:04:27 web.1  | -> "Content-Length: 84\r\n"
23:04:27 web.1  | -> "Date: Mon, 10 Oct 2022 09:04:27 GMT\r\n"
23:04:27 web.1  | -> "\r\n"
23:04:27 web.1  | reading 84 bytes...
23:04:27 web.1  | -> ""
23:04:27 web.1  | -> "{\"SipMediaApplicationCall\":{\"TransactionId\":\"8fcbb2e8-ca5b-4865-b450-2db75024b16c\"}}"
```
You can see here that it is sending SipHeaders but on the receiving end:
```
"event": {
    "SchemaVersion": "1.0",
    "Sequence": 1,
    "InvocationEventType": "NEW_OUTBOUND_CALL",
    "CallDetails": {
      "TransactionId": "8fcbb2e8-ca5b-4865-b450-2db75024b16c",
      "AwsAccountId": "942004899649",
      "AwsRegion": "us-east-1",
      "SipMediaApplicationId": "9e2b4bba-1c2f-4625-8f08-7985dc361293",
      "Participants": [
        {
          "CallId": "f27891d7-1f24-4c54-92db-72b9118401a6",
          "ParticipantTag": "LEG-A",
          "To": "+<to>",
          "From": "+<from>",
          "Direction": "Outbound",
          "StartTimeInMilliseconds": "1665392668105"
        }
      ]
    }
  }
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-chime

### Environment details (Version of Ruby, OS environment)

ruby "2.7.6", Linux (ubuntu) 22.04

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm not certain the Ruby SDK is at fault here - it looks like we correctly add "SipHeaders" field in the JSON body and send to the service.

I am assuming that, after making the call from the Ruby SDK, Chime publishes an event that your lambda function is subscribed to? And if I understand correctly, the event does not include the SipHeaders field?

If that's true, I think maybe the Chime team will need to fix this - I can try to raise this internally with them and find out more information. One thing I notice is that SipHeaders key and value are modeled as sensitive strings. It is likely that it's not available in Lambda by design.

**Comment by mullermp** [comment]
You may have better luck submitting this issue to AWS support, too.

**Comment by Aeramor** [comment]
@mullermp thanks. I'm going to update with my workaround incase anyone hits this issue in the interim but both the chime and aws documentation says these strings will be passed to the lambda function.

**Comment by mullermp** [comment]
Could you please share where you found that information and also the work around?

**Comment by Aeramor** [comment]
## SIP Docs
https://docs.aws.amazon.com/chime-sdk/latest/dg/sip-headers.html
>You must prefix your custom SIP headers with x-. The headers are exposed in the AWS Lambda function and received as part of a NEW_INBOUND_CALL event during an inbound call. You can also include these headers in outbound call legs when triggering a [CallAndBridge](https://docs.aws.amazon.com/chime-sdk/latest/dg/call-and-bridge.html) action or the [CreateSipMediaApplicationCall](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateSipMediaApplicationCall.html) API.

[From CreateSipMediaApplicationCall ](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateSipMediaApplicationCall.html)

>[SipHeaders](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateSipMediaApplicationCall.html#API_CreateSipMediaApplicationCall_RequestSyntax)
The SIP headers added to an outbound call leg.

## Workaround
(still working on the writeup) but it's by updating the call and passing the args through every single call to get to the end where I need it - https://docs.aws.amazon.com/chime-sdk/latest/dg/update-sip-call.html

**Comment by mullermp** [comment]
Ah interesting. I have no experience setting up conferencing infrastructure, but that documentation seems to indicate that SipHeaders would be on a `NEW_INBOUND_CALL` event in Lambda, but in your sample, it was a `NEW_OUTBOUND_CALL`. I think it's saying that you can use the SipHeaders for your outbound call (using `create_sip_media_application_call`) however they aren't exposed in Lambda. Are you possibly subscribed to the wrong Lambda event?

If you haven't already, I strongly recommend making an AWS support ticket case - you'll likely get a better answer. Typically the github issues are for SDK issues (issues with making requests, parsing responses, client side feature requests).

**Comment by yenfryherrerafeliz** [comment]
Hi @Aeramor, we contacted chime team regarding this and here is the answer we got them:
>This is the correct behavior - SIP headers are added to the outbound call leg, not sent to the Lambda:
>SipHeaders
> - The SIP headers added to an outbound call leg.

>If the Lambda was invoked by a SIP call rather than the API(https://docs.aws.amazon.com/chime-sdk/latest/ag/understand-sip-data-models.html), the Lambda would get the SIP headers from the call

Please let me know if have any questions.

Thanks!

**Comment by Aeramor** [comment]
@yenfryherrerafeliz 
Thanks for the response. Shame that they intentionally don't send the SIP headers. 
Incase anyone finds this in the future I'm getting around this limitation by doing:
```
resp2 = @client.update_sip_media_application_call({ # https://docs.aws.amazon.com/chime-sdk/latest/dg/update-sip-call.html
      sip_media_application_id: SIP_MEDIA_APP_ID,
      transaction_id: resp.sip_media_application_call.transaction_id, # required
      arguments: sip_headers
    })
```
