### ISSUE TITLE
Error when providing checksum_algorithm to object.stream_upload

### ISSUE THREAD

**Issue by normelton** [aws/aws-sdk-ruby#2769]
### Describe the bug

The AWS S3 documentation implies that I can specify a ChecksumAlgorithm when starting a streaming upload, and that the SDK will automagically calculate the checksum of uploaded data, and provide it to S3 at the completion of the upload:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#trailing-checksums

And in fact I see references to this in the `gems/aws-sdk-s3/CHANGELOG.md` file, but am having trouble getting it to work. I tried:

```
object.upload_stream({checksum_algorithm: "CRC32"}) do |s3_stream|
```

But I get back: **Aws::S3::Errors::InvalidRequest The upload was created using a crc32 checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.**

### Expected Behavior

Streaming uploads should support a trailing checksum as per AWS documentation.

### Current Behavior

Aws::S3::Errors::InvalidRequest The upload was created using a crc32 checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.

### Reproduction Steps

object = bucket.object("my-bucket-name")
object.upload_stream(:checksum_algorithm => "CRC32") do |s3_stream|
    s3_stream.upload "a bunch of data"
end

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by alextwoods** [comment]
Thanks for opening this - I'm investigating now.

My initial guess is that we need to apply the same changes from #2668 to the [MultipartStreamUploader](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_stream_uploader.rb)

**Comment by normelton** [comment]
Thanks @alextwoods, that seems to work!!
