### ISSUE TITLE
throw EISDIR error in response_target.rb whth fastlane match

### ISSUE THREAD

**Issue by narusejyunnichi** [aws/aws-sdk-ruby#2778]
### Describe the bug

i use fastlane match to singing certification with S3 storage
but since last week, there throw error when load some files. 

i find the problem is for first path, get a empty string as params
so there throw EISDIR at response_target.rb line 67
`ManagedFile.new("#{target}", 'w+b')`

i can change the local file and skip create file when the params is directory.
but since this path params get from real S3 folder by SDK. i don't know how to fix it when i using CI or some automatic shell that it will load new SDK every time when it start

### Expected Behavior

skip create file when the params is directory
or
filter empty string in S3 response path list

### Current Behavior

throw error create file when the params is directory

### Reproduction Steps

user fastlane match store certification and profile files in S3
and get those file by SDK

### Possible Solution

skip create file when the params is directory
or
filter empty string in S3 response path list

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

ruby2.6.2

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm not certain I understand what's going on. What do you mean by "params is directory" - are you referring to `ManagedFile` taking an empty string? `ManagedFile` inherits from `File`. Can you share more code snippets for how you are using the SDK?

**Comment by narusejyunnichi** [comment]
Thanks for reply.
Sure. actually i not use this SDK. i used Match. this is a plugin for Fastlane. that is a auto build tools for mobile.

And in this plugin, it use this SDK to pares params from S3. those params look like path from S3 that it stored some files when build the mobile package needed.

Cause i use Fastlane and Match (Match include this SDK ), that both SDK too. so don't know what happed actually, i just see those thing
1、don't change any code, but it work fine before (because this i thought maybe there is something updated but i don't know in S3 config)
2、the path in params from S3 response (the first item in params is a empty string like "")
3、SDK file response_target.rb line 67 throw this error (because ManagedFile need a file path not  directory as parameter)

So i think maybe some config updated but i don't know from S3,  or this SDK need add some logic to keep this method more safety when the parameter is a wrong type.

Can you help me to figure out how to fix this situation,  to update some S3 config? or add a guard code in this method（response_target.rb line 67）when the parameter is a wrong type. what i can do?

Thank you 🙏

**Comment by mullermp** [comment]
I think maybe you should open an issue with Match or Fastlane instead of the SDK. A full stack trace would be helpful to see where in their stack it fails. Their repo is here: https://github.com/fastlane/fastlane

**Comment by narusejyunnichi** [comment]
hello. i find the deep reason about this problem
when i user `find_bucket!(bucket_name)` by using aws-sdk-s3

and the return object is a array with file path. like [s3_object_prefix/xxx/xxx1.doc, s3_object_prefix/xxx/xxx2.doc, xxx/xxx/xxx3.doc, xxx/xxx/xxx4.doc]
but now, i see inside the return object is [s3_object_prefix/, s3_object_prefix/xxx/xxx1.doc, s3_object_prefix/xxx/xxx2.doc, xxx/xxx/xxx3.doc, xxx/xxx/xxx4.doc]

is there something changed?

**Comment by narusejyunnichi** [comment]
finally, i find out why.

i don't know why there is a file named "xxxxx/" in xxxxx/. because the file and the directory has same name.so i not realize that a reason about this problem

so there the story

`find_bucket!(bucket_name)` get all file in my s3_object_prefix directory like [xxxx/, file1, file2, file3]
`ManagedFile.new("#{target}", 'w+b')` think the first item named "xxxx/" is a directory

i still don't know why there have a file named "xxxx/". maybe someone's mistake in our team or something.

thinks for help
