### ISSUE TITLE
Occurs FrozenError when getting S3 bucket properties

### ISSUE THREAD

**Issue by meap** [aws/aws-sdk-ruby#2782]
### Describe the bug

When upgrading to the latest version, a FrozenError exception occurs when retrieving S3 bucket properties.

### Expected Behavior

Returns a public URL for this bucket.

### Current Behavior

Raises an exception

```
FrozenError: can't modify frozen Aws::Endpoints::Condition: #<Aws::Endpoints::Condition:0x00007fcdaf37f530 @fn=#<Aws::Endpoints::Function:0x00007fcdaf37f4e0 @fn="substring", @argv=[#<Aws::Endpoints::Reference:0x00007fcdaf37f260 @ref="Bucket">, 49, 50, true]>, @assign="hardwareType", @assigned={}>
from /Users/meap/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.166.0/lib/aws-sdk-core/endpoints/condition.rb:21:in `match?'
```

### Reproduction Steps

```ruby
Aws::S3::Bucket.new(name: 'xyz-bucket-name').url
```

### Additional Information/Context

```
aws-sdk-s3 (1.117.1)
aws-sdk-core (~> 3, >= 3.165.0)
aws-sdk-kms (~> 1)
aws-sigv4 (~> 1.4)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

1.117.1

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.6, OSX 12.6

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm not able to reproduce this:

```
[1] pry(Aws)> Aws::S3::Bucket.new(name: 'xyz-bucket-name').url
=> "https://xyz-bucket-name.s3.us-west-2.amazonaws.com"
[2] pry(Aws)> Aws::S3::GEM_VERSION
=> "1.117.1"
[3] pry(Aws)> Aws::CORE_GEM_VERSION
=> "3.166.0"
```

Could I get some exact gem version numbers that you are using?

**Comment by meap** [comment]
```ruby
[2] pry(main)> Aws::S3::GEM_VERSION
=> "1.117.1"
[3] pry(main)> Aws::CORE_GEM_VERSION
=> "3.166.0"
[4] pry(main)>
```

**Comment by mullermp** [comment]
Strange.. Those are the same versions. Could you please provide a larger stack trace?

What is your KMS version by chance? Try blowing away your Gem lockfile and getting the latest there.
