### ISSUE TITLE
Retries on AWS::EC2::Errors::InsufficientInstanceCapacity (regression)

### ISSUE THREAD

**Issue by grosser** [aws/aws-sdk-ruby#2786]
### Describe the bug

same as https://github.com/aws/aws-sdk-ruby/issues/568 (regression)
when capacity is not available it should stop and not retry forever

### Expected Behavior

it fails

### Current Behavior

it retries forever

### Reproduction Steps

see original issue

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-ec2 (1.285.0)

### Environment details (Version of Ruby, OS environment)

3.1.2

**Comment by alextwoods** [comment]
It looks like this change in behavior likely goes back to the earliest days of V2/V3 of the SDK (this [commit](https://github.com/aws/aws-sdk-ruby/commit/72945ae4dca8e2900259539a5203c2207d4b13e9) added the initial ErrorInspector which did not have the special casing for skipping retry of `InsufficentInstanceCapacity` errors) - so this was likely V1 only behavior.  

I'll look into adding back in a special case to check for this error and avoid retrying - I'm discussing with other SDKs if this is something that should apply for them as well.

**Comment by alextwoods** [comment]
We've discussed this with EC2 and they've indicated that the `InsufficentInstanceCapacity` should be retired - there may be changes in the availability of pools that would result in a retry succeeding - so, while the V1 sdk had this behavior, we shouldn't add a new special case into the newer SDKs.

If the retry of `InsufficentInstanceCapacity` is impacting you, you can change the retry settings on the client (in particular reduce the number of retires).
