### ISSUE TITLE
Overriding client endpoint no longer works

### ISSUE THREAD

**Issue by jcoetzee** [aws/aws-sdk-ruby#2791]
### Describe the bug

In `aws-sdk-dynamodb` versions before 1.78 it was possible to override the endpoint on a client object (`client.config.endpoint = '<URL>'`). We use this in local testing. From version 1.78 this is no longer honoured and requests are sent to the public regional endpoint. I'm assuming this is a similar issue to #2776 with changes to resolve endpoints from model file.

If there is a migration path to allow is to override on an existing client then that's also fine.

### Expected Behavior

`client.config.endpoint = 'http://localhost:8000'` should direct requests to localhost.

### Current Behavior

Requests are still sent to standard public endpoint for region.

### Reproduction Steps

```
$ gem install --user-install --version 1.77 aws-sdk-dynamodb
$ irb
irb(main):001:0> require 'aws-sdk-dynamodb'
=> true
irb(main):002:0> client = Aws::DynamoDB::Client.new(region: 'eu-west-1')
=> #<Aws::DynamoDB::Client>
irb(main):003:0> client.list_tables
=> #<struct Aws::DynamoDB::Types::ListTablesOutput table_names=["region_ddb"], last_evaluated_table_name=nil>
irb(main):004:0> client.config.endpoint = 'http://localhost:8000'
=> "http://localhost:8000"
irb(main):005:0> client.list_tables
=> #<struct Aws::DynamoDB::Types::ListTablesOutput table_names=["local_ddb"], last_evaluated_table_name=nil>
```

```
$ gem install --user-install --version 1.78 aws-sdk-dynamodb
$ irb
irb(main):001:0> require 'aws-sdk-dynamodb'
=> true
irb(main):002:0> client = Aws::DynamoDB::Client.new(region: 'eu-west-1')
=> #<Aws::DynamoDB::Client>
irb(main):003:0> client.list_tables
=> #<struct Aws::DynamoDB::Types::ListTablesOutput table_names=["region_ddb"], last_evaluated_table_name=nil>
irb(main):004:0> client.config.endpoint = 'http://localhost:8000'
=> "http://localhost:8000"
irb(main):005:0> client.list_tables
=> #<struct Aws::DynamoDB::Types::ListTablesOutput table_names=["region_ddb"], last_evaluated_table_name=nil>
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-dynamodb 1.78

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.6, MacOS 12.6.1

**Comment by mullermp** [comment]
Recent versions of SDK core have a new rules-based way to resolve endpoints and it's done at **operation time** instead of client creation time. The client config endpoint is now "immutable" for an existing client. I think this was intended behavior unfortunately. Admittedly, we had test cases that did the same as you, and we had to change those.

The path forward I think is to create a second client for your localhost endpoint. You can also use `region: 'local'` and rules should resolve to that endpoint instead of specifying it directly.

```
[1] pry(Aws)> Aws::DynamoDB::Client.new(region: 'local').list_tables
opening connection to localhost:8000...
```
