### ISSUE TITLE
Unable to use Multi-Region access point on a rails project

### ISSUE THREAD

**Issue by sastromskis** [aws/aws-sdk-ruby#2794]
### Describe the bug

Accessing multi-region access point requires the aws-crt gem. After looking through available resources online i found that a similar problem was reported earlier:
https://github.com/aws/aws-sdk-ruby/issues/2630

However, following the instructions in the thread did not solve the problem. Those match with the official docs:
https://github.com/awslabs/aws-crt-ruby

running a `rails console` crashes with the following error:
locally on an M1 mac: `Could not open library 'libaws-crt-ffi.dylib'`
docker on ruby:2.7.2-alpine: `Could not open library 'libaws-crt-ffi.so': Error loading shared library libaws-crt-ffi.so: No such file or directory`

### Expected Behavior

I'd expect that adding these gems to a Gemfile
```
gem 'aws-sdk-s3'
gem 'aws-sigv4', '1.4.1.crt'
```
would allow to use Multi-Region access points via `Aws::S3::Client`

### Current Behavior

M1 Mac
/Users/s/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/s/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-crt-0.1.6-arm64-darwin/bin/arm/libaws-crt-ffi.dylib': dlopen(/Users/s/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-crt-0.1.6-arm64-darwin/bin/arm/libaws-crt-ffi.dylib, 0x0005): tried: '/Users/s/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/aws-crt-0.1.6-arm64-darwin/bin/arm/libaws-crt-ffi.dylib' (no such file), '/usr/local/lib/libaws-crt-ffi.dylib' (no such file), '/usr/lib/libaws-crt-ffi.dylib' (no such file). (LoadError)

ruby:2.7.2-alpine docker:
Could not open library 'libaws-crt-ffi.so': Error loading shared library libaws-crt-ffi.so: No such file or directory
Error loading shared library libaws-crt-ffi: No such file or directory.
LoadError: Could not open library '/usr/local/bundle/gems/aws-crt-0.1.6-x86_64-linux/bin/x86_64/libaws-crt-ffi.so': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/aws-crt-0.1.6-x86_64-linux/bin/x86_64/libaws-crt-ffi.so).

### Reproduction Steps

Add the following lines to a Gemfile:
```
gem 'aws-sdk-s3'
gem 'aws-sigv4', '1.4.1.crt'

```
run
`rails console`

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sigv4

### Environment details (Version of Ruby, OS environment)

ruby 2.7.2, rails 6.1.4.6, macOS Monterey 12.2, ruby:2.7.2-alpine docker

**Comment by mullermp** [comment]
Thanks for opening an issue. It looks like it's an issue with compatibility - alpine I don't think is supported by CRT yet. Potential related issue - https://github.com/awslabs/aws-crt-ruby/issues/43. Could you please add details or a new issue in aws-crt-ruby instead?

If you try a different architecture, try installing the latest `aws-crt` gem and the latest `aws-sigv4` gem - do not use the CRT version of `aws-sigv4` (developer preview version only - it's been merged into the latest `aws-sigv4`)
