### ISSUE TITLE
aws-sdk-quicksight generates very large documentation files

### ISSUE THREAD

**Issue by fcheung** [aws/aws-sdk-ruby#2801]
### Describe the bug

As of 1.72.0 Running `gem install aws-sdk-quicksight` took 471 seconds to install documentation (core i9 2019 macbook pro) and generates best part of 50Mb of ri documentation

The issue seems to be the new methods for creating analyses, dashboards etc. through the api and the recursive expanding of those data structures when generating examples. For example the example given for Aws::QuickSight::Client#create_analysis is about 29000 lines long

### Expected Behavior

Documentation behaviour shouldn't be extremely slow, generated examples should be concise enough to be useful

### Current Behavior

Multiple documentation files are very large, several (describe_template_definition, describe_analysis_definition, describe_dasboard_definition are all ~ 3 MB)

### Reproduction Steps

gem install aws-sdk-quicksight -v 1.72.0
ri Aws::QuickSight::Client#create_analysis

### Additional Information/Context

This creates further downstream problems, eg [tapioca](https://github.com/Shopify/tapioca) takes an extremely long time to run because it also (optionally) operates on rdoc tags

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-quicksight 1.72.0

### Environment details (Version of Ruby, OS environment)

ruby 3.1.2, macos 12.6.1, rubygems 3.3.7, rdoc 6.4

**Comment by mullermp** [comment]
I'm sorry you ran into this. We're aware of quicksight blowing up. Their new API updates were massive and made huge examples. I fixed the issue last week in the repo but I think we need to do a no-op release for the gem. Please use an earlier version or wait until later today for a new version.

**Comment by mullermp** [comment]
https://github.com/aws/aws-sdk-ruby/commit/ca04edb62f89a5386b0c301be782a9e6b44a76b5 commit should bump the version in our next release cycle (11 AM PST).
