### ISSUE TITLE
Slow upload speed in Apple Virtualization Framework VMs on M1

### ISSUE THREAD

**Issue by liamnichols** [aws/aws-sdk-ruby#2803]
### Describe the bug

We've used the aws-sdk-s3 gem for months on virtualised Apple Silicon (Bitrise) without a hitch, but starting at some time around 2022-11-18, uploads of ~30mb files that previously took a matter of seconds would start to take anywhere between 30m and 2h30m.

Possibly Related: aws/aws-sdk#469

### Expected Behavior

Uploads using `Aws::S3::Client` `put_object` on virtualized Apple Silicon using Apple's Virtualization Framework should not take longer than uploads made outside of virtualization (factoring in network differences)

### Current Behavior

Uploads using `Aws::S3::Client` `put_object` are taking considerably longer when made in a virtualized environment on Apple Silicon using Apple's Virtualization Framework.

For example, an ~8mb file:

Host Machine|VM
---|---
0m 11.514s|4m 47.306s
0m 10.530s|6m 16.938s
0m 11.371s|6m 1.333s

### Reproduction Steps

This is a tricky one to reproduce, but I have been able to reproduce it locally on my own personal M1 Mac (in a VM) to confirm that the issue does not relate to networking problems with Bitrise. 

I'll take you through the steps involved using a 2021 MacBook Pro with Apple M1 Max (64GB RAM) (but it should reproduce using any Apple Silicon machine, Bitrise uses M1 Mini's)...

1. Download [VirtualBuddy](https://github.com/insidegui/VirtualBuddy/releases/tag/1.2.2) version 1.2.2
2. Setup a VM using an image of macOS 13.0.1
3. Once the OS is installed, using terminal install [Homebrew](https://brew.sh)
4. Follow the instructions to setup Homebrew in Terminal
5. Install rbenv with `brew install rbenv`
6. Follow the instructions to setup rbenv
7. Install Ruby 3.0.3 using `rbenv install 3.0.3`
8. Set Ruby 3.0.3 as the global version using `rbenv global 3.0.3`
9. Download and extract the contents of [Sample.zip](https://github.com/aws/aws-sdk-ruby/files/10170646/Sample.zip) into a directory
10. Modify the `key` and `region` variables in **aws-debug.rb**
11. Ensure that the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables are set
12. In terminal, `cd` into the directory
13. Run `sh script.sh`
14. Observe the output and compare the statistics printed by `time` by running steps 3-13 on the host machine as well

<details>
<summary><b>Host Machine</b></summary>

```
Starting at Tue  6 Dec 2022 23:11:58 CET


System Profile...
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,4
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      System Firmware Version: 8419.41.10
      OS Loader Version: 7459.141.1
      Serial Number (system): REDACTED
      Hardware UUID: REDACTED
      Provisioning UDID: REDACTED
      Activation Lock Status: Disabled



Network Quality...
==== SUMMARY ====                                                                                         
Upload capacity: 18.115 Mbps
Download capacity: 89.496 Mbps
Upload flows: 20
Download flows: 20
Responsiveness: Low (71 RPM)
Base RTT: 19
Start: 06/12/2022, 23:11:58
End: 06/12/2022, 23:12:19
OS Version: Version 12.6.1 (Build 21G217)


Creating Sample (8mb)...
1+0 records in
1+0 records out
8388608 bytes transferred in 0.034268 secs (244794210 bytes/sec)


Gemfile dependencies...
Warning: the running version of Bundler (2.2.22) is older than the version that created the lockfile (2.2.32). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.32`.
Using aws-eventstream 1.2.0
Using aws-partitions 1.672.0
Using aws-sigv4 1.5.2
Using jmespath 1.6.2
Using aws-sdk-core 3.168.3
Using aws-sdk-kms 1.60.0
Using aws-sdk-s3 1.117.2
Using bundler 2.2.22
Using racc 1.6.1
Using nokogiri 1.13.9 (arm64-darwin)
Bundle complete! 2 Gemfile dependencies, 10 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.


Starting Upload (ruby)...
Opening file...
Loaded file. Uploading...
opening connection to s3.amazonaws.com:443...
opened
starting SSL for s3.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "PUT /research-sandbox.us-east-1/liam-bitrise-debug/ruby/1670364739_Sample.bin HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.168.3 ruby/3.0.2 arm64-darwin21 aws-sdk-s3/1.117.2\r\nContent-Type: application/octet-stream\r\nExpect: 100-continue\r\nContent-Md5: HuC6mfxuQLMR6DYyqUjPfg==\r\nHost: s3.amazonaws.com\r\nX-Amz-Date: 20221206T221220Z\r\nX-Amz-Content-Sha256: 9dd7da3948c468cd04924c27a33c6c76ca1f380f87d3ca01184f33c9074f1e71\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20221206/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=b2cedf6f0d4d5de2c373aafc06a060ec09054278d3388902a6ab9ead098f5579\r\nContent-Length: 8388608\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 100 Continue\r\n"
-> "\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amz-id-2: Mu9SqHgk48tyKLQpYDv1ObVc6bbUZRBiPPdDxfq0CwBpch9S3ROtBF/beUzba3NVe59xzs4saH8=\r\n"
-> "x-amz-request-id: GEDH15VS30M338RX\r\n"
-> "Date: Tue, 06 Dec 2022 22:12:21 GMT\r\n"
-> "ETag: \"1ee0ba99fc6e40b311e83632a948cf7e\"\r\n"
-> "Server: AmazonS3\r\n"
-> "Content-Length: 0\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn keep-alive
D, [2022-12-06T23:12:30.563157 #10468] DEBUG -- : [Aws::S3::Client 200 10.593935 0 retries] put_object(bucket:"research-sandbox.us-east-1",key:"liam-bitrise-debug/ruby/1670364739_Sample.bin",body:#<File:1670364739_Sample.bin (8388608 bytes)>,content_type:"application/octet-stream")  


real	0m11.101s
user	0m0.423s
sys	0m0.138s
```

</details>

<details>
<summary><b>Virtual Machine</b></summary>

```
Starting at Tue  6 Dec 2022 23:13:32 CET


System Profile...
Hardware:

    Hardware Overview:

      Model Name: Apple Virtual Machine 1
      Model Identifier: VirtualMac2,1
      Model Number: VM0001B/A
      Chip: Apple M1 Max (Virtual)
      Total Number of Cores: 5
      Memory: 32 GB
      System Firmware Version: 8419.41.10
      OS Loader Version: 8419.41.10
      Serial Number (system): REDACTED
      Hardware UUID: REDACTED
      Provisioning UDID: REDACTED
      Activation Lock Status: Disabled



Network Quality...
==== SUMMARY ====
Uplink capacity: 25.922 Mbps (Accuracy: High)
Downlink capacity: 120.499 Mbps (Accuracy: High)
Responsiveness: Low (103 RPM) (Accuracy: High)
Idle Latency: 187.458 milli-seconds (Accuracy: High)
Interface: en0
Uplink bytes transferred: 39.984 MB
Downlink bytes transferred: 409.324 MB
Uplink Flow count: 20
Downlink Flow count: 12
Start: 06/12/2022, 23:13:32
End: 06/12/2022, 23:14:00
OS Version: Version 13.0.1 (Build 22A400)


Creating Sample (8mb)...
1+0 records in
1+0 records out
8388608 bytes transferred in 0.012687 secs (661197131 bytes/sec)


Gemfile dependencies...
Using aws-eventstream 1.2.0
Using aws-partitions 1.672.0
Using aws-sigv4 1.5.2
Using jmespath 1.6.2
Using aws-sdk-core 3.168.3
Using aws-sdk-kms 1.60.0
Using aws-sdk-s3 1.117.2
Using bundler 2.2.32
Using racc 1.6.1
Using nokogiri 1.13.9 (arm64-darwin)
Bundle complete! 2 Gemfile dependencies, 10 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.


Starting Upload (ruby)...
Opening file...
Loaded file. Uploading...
opening connection to s3.amazonaws.com:443...
opened
starting SSL for s3.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "PUT /research-sandbox.us-east-1/liam-bitrise-debug/ruby/1670364840_Sample.bin HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.168.3 ruby/3.0.3 arm64-darwin22 aws-sdk-s3/1.117.2\r\nContent-Type: application/octet-stream\r\nExpect: 100-continue\r\nContent-Md5: xYlmhyrVEiV+3q2VU2cOgg==\r\nHost: s3.amazonaws.com\r\nX-Amz-Date: 20221206T221401Z\r\nX-Amz-Content-Sha256: 0c5867f44751f4cbc4752033068ce4f8000fa9d79bb807b0ff5cdec5dbbabda1\r\nAuthorization: AWS4-HMAC-SHA256 Credential=REDACTED/20221206/us-east-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;x-amz-content-sha256;x-amz-date, Signature=02f8aa279f39a3a37f5fe0066c6510eca8189e0b3b7608dd54d5d61d8a264b26\r\nContent-Length: 8388608\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 100 Continue\r\n"
-> "\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "x-amz-id-2: Bb8JxAe4bmJZyi7cVNRKVS9P3zAQFBFgdD9s0mqQMqzTPzr8C7NXst9p3up9wqBEbDdW1TEDtaU=\r\n"
-> "x-amz-request-id: 8X59141WAFXX4PX6\r\n"
-> "Date: Tue, 06 Dec 2022 22:14:03 GMT\r\n"
-> "ETag: \"c58966872ad512257edead9553670e82\"\r\n"
-> "Server: AmazonS3\r\n"
-> "Content-Length: 0\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn close
D, [2022-12-06T23:19:52.556706 #93910] DEBUG -- : [Aws::S3::Client 200 350.824353 0 retries] put_object(bucket:"research-sandbox.us-east-1",key:"liam-bitrise-debug/ruby/1670364840_Sample.bin",body:#<File:1670364840_Sample.bin (8388608 bytes)>,content_type:"application/octet-stream")  


real	5m51.659s
user	0m0.664s
sys	0m0.400s
```

</details>

### Possible Solution

N/A

### Additional Information/Context

I've tried this in a lot of configurations, particularly on Bitrise and the issue seems to persist on macOS 12 and 13. I've also tried on both Ruby 3.0.x and 3.1.x but see the same issue.

Everything I am seeing points towards some kind of issue with virtualization, but what I also don't understand is why the issue suddenly appeared around 2022-11-18. It's also suspicious that aws/aws-sdk#469 seems to have appeared at around the same time although my understanding is that these are two entirely different implementations? 

One possible thing to note is that at around the same time, Bitrise updated the VM image for their M1 Macs where a diff of installed tools can be seen here - https://github.com/bitrise-io/bitrise.io/commit/e08a863595299bbb9e78b219344b0f9d790d7de5. Initially I did think that it might be related since the `awscli` was updated, but 1) the previous version is the version mentioned in the bug report above anyway and 2) I can also reproduce the issue outside of Bitrise.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

macOS 12.5 or 13.0.1 using Ruby 2.7.7, 3.0.3 or 3.1.3 within Apple Virtualization Framework

**Comment by alextwoods** [comment]
Thanks for reporting this and sorry you're running into it.

Its suspicious that it seems to be happening for both CLI and Ruby SDK - these share no common implementation.  Looking at the [S3/Changelog](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md), there don't appear to be any changes around 2022-11-18.  

What version(s) of the `aws-sdk-s3` and `aws-sdk-core` gems are you using?  Could you repeat your tests with earlier versions of both (from prior to 11-18)?  That will help us narrow down if there are SDK related changes that may be causing this.

**Comment by liamnichols** [comment]
Thanks for such a quick reply @alextwoods. I agree that the link between the two tools seems odd given the nature of the issue especially. 

Initially when the issue first appeared, we were using the following versions:

- aws-sdk-core (3.160.0)
- aws-sdk-s3 (1.114.0)

A couple of days later Dependabot bumped them to the following: 

- aws-sdk-core (3.168.1)
- aws-sdk-s3 (1.117.1)

I did already try with 3.160.0/1.114.0 and it made no difference, but I didn’t try an even earlier version which might be worth a shot. I’ll try going back further tomorrow 👍🏼

It’s also worth noting that on very few one-off occasions, I’ve seen the upload complete in a regular time while in a virtualized environment (just from re-running as a test)… not sure if that helps or not

**Comment by liamnichols** [comment]
I looked back at our Gemfile.lock from when we switched to M1 Macs on our CI back in July and matched the versions up but am faced with the same issue.

For reference:

```
Gemfile dependencies...
Using aws-eventstream 1.2.0
Using aws-partitions 1.602.0
Using aws-sigv4 1.5.0
Using jmespath 1.6.1
Using aws-sdk-core 3.131.2
Using aws-sdk-kms 1.57.0
Using aws-sdk-s3 1.114.0
Using bundler 2.2.32
Using racc 1.6.0
Using nokogiri 1.13.6 (arm64-darwin)
```

So I guess that eliminates changes to the SDK itself?

**Comment by mullermp** [comment]
Can you roll back M1 Mac versions (not entirely sure how these are versioned..) to see if that might be the culprit?

**Comment by liamnichols** [comment]
@mullermp: Hmm good point... The version of macOS inside virtualisation never actually changed when the issue first surfaced in my particular case (we had been on macOS 12.5) but during my investigation, I have reproduced the issue on macOS 12.4, 12.5 and 13.0 on Bitrise and on macOS 13.0.1 using a local VM.

However I guess it might well be related to the OS version of the host machine. In my case locally, this is macOS 12.6.1 (21G217). One possible theory is that a recent macOS update installed on the host machine could have included a newer version of Apple's Virtualization Framework that has the regression.

I will check in with my Bitrise support contact to see if there were any changes to the barebones machines themselves that might be related

**Comment by mullermp** [comment]
That sounds like a good idea. I'm going to set this issue to "closing soon" as it appears to not be a Ruby SDK issue, but we will happily investigate if there is new evidence. Feel free to also update your findings here for others if you'd like! :D

**Comment by liamnichols** [comment]
Sounds good, thanks again fro the help! 

Bitrise confirmed to me that there had been a change to the virtualization framework deployed on 2022-11-17, but are running tests to confirm if this was the cause or not. They can't share specifics with me, but told me that they'd announce it on their blog if an issue was confirmed. 

In the meantime, I also filed a Feedback with Apple as FB11858528 since I can reproduce it locally too.

**Comment by mullermp** [comment]
Ah! Seems very suspicious. Thanks for the update.
