### ISSUE TITLE
Multipart uploads often fail

### ISSUE THREAD

**Issue by fschwahn** [aws/aws-sdk-ruby#2811]
### Describe the bug

When uploading large files (> 10GB) multipart uploads are often canceled due to upload errors happening.

### Expected Behavior

Multipart uploads of large files should complete.

### Current Behavior

Multipart uploads often abort. Errors we are running into:

```
Aws::S3::MultipartUploadError: multipart upload failed: stream closed in another thread; 503 Service Unavailable

/app/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.117.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:103 in abort_upload
/app/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.117.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:92 in upload_parts
/app/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.117.2/lib/aws-sdk-s3/multipart_stream_uploader.rb:49 in upload
/app/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.117.2/lib/aws-sdk-s3/customizations/object.rb:371 in upload_stream 
```

The error messages vary slightly:
- `multipart upload failed: stream closed in another thread; 503 Service Unavailable`
- `multipart upload failed: 503 Service Unavailable`
- `multipart upload failed: 502 Bad Gateway`
- `multipart upload failed: stream closed in another thread; 502 Bad Gateway`

### Reproduction Steps

I cannot provide exact reproduction steps, we are roughly doing:
```
disposition = ActionDispatch::Http::ContentDisposition.format(disposition: "attachment", filename: filename)
object.upload_stream disposition: disposition, content_type: content_type do |write_stream|
  write_stream.binmode

  # stream builds a ZIP-file chunk by chunk
  stream do |chunk|
    write_stream << chunk
  end
end
```

This mainly happens when the files are really large, but I suspect this just increases the likelihood of running into the problem.

### Possible Solution

It's unclear to me if uploading is retried if uploading of a single part fails - that could help?

### Additional Information/Context

We are running on Heroku, so upload goes from EC2 to S3 (I guess), though regions probably differ.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 (1.117.2)

### Environment details (Version of Ruby, OS environment)

Ruby 3.0.5, Linux

**Comment by mullermp** [comment]
Thanks for opening an issue. Normally most errors are retryable. The multipart stream uploader (used by `object.upload_stream`) will call the `upload_part` operation and should be retrying individual parts.  Server errors like 502 and 503 are not really expected for S3 - but this is likely some networking issue in your environment, like perhaps a proxy. It's possible that `upload_part` is retried and fails multiple times. Are you by chance using a custom S3 implementation/endpoint or are you using actual S3 service? You should also try `http_wire_trace: true` option in the client to see the http wire logs and see if anything seems suspicious.

**Comment by alextwoods** [comment]
Agree with @mullermp - the SDK will retry those errors for each individual part (though errors like 502 and 503 should generally be rare for s3).  

Do you have any options set on the S3 client used by `object`? You could consider adjusting the retry parameters on the [client](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method) - consider potentially setting the `retry_mode` to `:adaptive` (see [Retry modes](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method) for some more details).

**Comment by fschwahn** [comment]
> Are you by chance using a custom S3 implementation/endpoint or are you using actual S3 service?

I'm using the actual S3 service, region is `eu-west-1`.

> Do you have any options set on the S3 client used by object

No options are passed besides the region.

> You should also try http_wire_trace: true option in the client to see the http wire logs and see if anything seems suspicious.
> consider potentially setting the retry_mode to :adaptive

I'll try both of these option to see if I can find anything.

**Comment by mullermp** [comment]
Did you find any new information?

**Comment by fschwahn** [comment]
Of course this hasn't happened since setting `http_wire_trace: true`, while it occurred regularly before - I didn't change the retry_mode yet, as I wanted to have a log of the actual error.

**Comment by mullermp** [comment]
No worries. It may also have been a region outage. Has this happened multiple days or just a few times in a few hours time span? If it happens again and you're able to capture logs, please re-open the ticket.

**Comment by julik** [comment]
@mullermp I don't know whether this is useful (and it's been some time ago), but: I bumped into something similar and I don't think it has to do with outages. The problem is that the `stream` method actually retries any errors that happens inside the block that writes into the multipart upload buffer. Exceptions that get raised from inside that block will not get reported correctly, in that they will be masked by the multipart upload error about the stream. But if you look at accumulated array of errors in the multipart upload code, you can see that it is not something going wrong with the socket or the IO infra, but something more mundane like a `BadRequest` when `read`ing another S3 object inside the block. I suspect it is the matter of surfacing those original errors better. Error handling with blocks can be tricky, but even if the order of errors would be reversed (the error occurring first would be presented to the user, along with something like `Afterwards, the following exceptions were raised: ...`) this would be very helpful.

**Comment by mullermp** [comment]
Thank you. That is good feedback. I can take a closer look at this. Even better if you'd like to open a PR to start.

**Comment by julik** [comment]
I would love to, but have too much on my plate at the moment. Just wanted to leave this here if others find this issue. I fought with rescues-retries in "raises from a block" scenarios and they are always tricky. Sorry I can't be of more help with this, at least now.
