### ISSUE TITLE
XML Parsing error

### ISSUE THREAD

**Issue by limjinsun** [aws/aws-sdk-ruby#2820]
### Describe the issue

When you try to get all object't key in the S3 buckets. It returns error. 

```
2.7.0 :022 > Aws::S3::Bucket.new('my_bucket').objects.collect(&:key)
Traceback (most recent call last):
        3: from (irb):21
        2: from (irb):22:in `rescue in irb_binding'
        1: from (irb):22:in `collect'
Aws::Xml::Parser::ParsingError (xmlParseCharRef: invalid xmlChar value 1)
```

### Links

No link

**Comment by alextwoods** [comment]
Hey - I haven't been able to reproduce this yet.

What versions of the aws-sdk-s3 and aws-sdk-core gem are you using?

Can you enable wirelogging and provide the results?
```
client = Aws::S3::Client.new(http_wire_trace: true)
Aws::S3::Bucket.new('my_bucket', client: client).objects.collect(&:key)
```

**Comment by mullermp** [comment]
Also which parser is being used? Rexml, nokogiri, ox?
