### ISSUE TITLE
s3: Lost metadata after copy_to with multipart_copy option

### ISSUE THREAD

**Issue by bgwilson87** [aws/aws-sdk-ruby#2821]
### Describe the bug

When copying an object with multipart_copy, metadata is not carried over to the copied file.

### Expected Behavior

Metadata should be preserved.

### Current Behavior

Metadata is lost.

### Reproduction Steps

```
file = bucket.object('videos/original.mp4')

file.content_type
# "video/mp4"

file.cache_control
# "max-age=123456"

file.copy_to('my_bucket/videos/copy.mp4', {multipart_copy: true})

copy = bucket.object('videos/copy.mp4')

copy.content_type
# "binary/octet-stream"

copy.cache_control
# nil
```

When not using multipart_copy, it works as expected:

```
file.copy_to('my_bucket/videos/copy2.mp4')

copy2 = bucket.object('videos/copy2.mp4')

copy2.content_type
# "video/mp4"

copy2.cache_control
# "max-age=123456"
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

3.0.4

**Comment by alextwoods** [comment]
Hey - thanks for submitting this and sorry you're running into it.  I've been able to reproduce and agree its a bug - it looks like we are not correctly setting the metadata when creating the multipart upload.  I'll investigate a fix.
