### ISSUE TITLE
Accept-Encoding=identity instead of empty value

### ISSUE THREAD

**Issue by rpembry** [aws/aws-sdk-ruby#2831]
### Describe the feature

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/net_http/handler.rb#L184

Please consider explicitly using the value 'identity' here instead of assuming the.server will correctly infer identity is desired.

### Use Case

When presented with Accept-Encoding empty, Hitachi HCP S3 server responds with a **400** error indicating:

<?xml version='1.0' encoding='UTF-8'?>\n<Error>\n  <Code>InvalidArgument</Code>\n  <Message>**Unsupported Accept-Encoding specified**</Message>\n  <RequestId>...</RequestId>\n  <HostId>...</HostId>\n</Error> \n\n

HCP behaves as expected with Accept-Encoding set to ‘identity’.

### Proposed Solution

headers = { 'accept-encoding' => 'identity' }

at

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/net_http/handler.rb#L184

### Other Information

rfc2616 states: "If the Accept-Encoding field-value is empty, then only the “identity" encoding is acceptable.”

rcf9110 states this more verbosely: "An Accept-Encoding header field with a field value that is empty implies that the user agent does not want any content coding in response. If a non-empty Accept-Encoding header field is present in a request and none of the available representations for the response have a content coding that is listed as acceptable, the origin server SHOULD send a response without any content coding unless the identity coding is indicated as unacceptable."

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

aws-sdk-core-3.170.0

### Environment details (OS name and version, etc.)

ALL

**Comment by alextwoods** [comment]
I'm a bit concerned that some AWS services may expect the current behavior - I'll investigate what other SDKs are doing.

**Comment by alextwoods** [comment]
It looks like in general other SDKs do NOT send `accept-encoding: identity`.  

Based on my reading of the RFCs, it looks like sending empty indicates that `identity` is acceptable and that the server in this case should respond with that.  I'm not familiar with Hitachi  HCP S3, but this seems like something it should handle.
