### ISSUE TITLE
Kinesis streaming from large feeds - out of memory errors

### ISSUE THREAD

**Issue by jpaulgs** [aws/aws-sdk-ruby#2832]
### Describe the bug

My kinesis feed consumers are streaming data from each shard of a kinesis feed and processing each record when it is available.

General gist is streaming from a feed where the consumer starts at the trim horizon with substantial amounts of data to consume or where your consumer isn't keeping up, results in data getting buffered without limits. Resulting in OOM errors.

### Expected Behavior

I would expect some configurable upper limit on the amount of data being buffered.

### Current Behavior

Each `Aws::Kinesis::AsyncClient` pulls down data as fast as the network allows.  Data is only drained as fast as the handler allows resulting in out-of-memory errors.  In my case the consumers were consuming faster than the data being produced but starting at the trim horizon very quickly kills the process.  I've attached a stack trace from a heap profile.  I'll agree that is not particularly illustrative but it does show data being stored in strings

[heap_analysis_from_shopify_heap_profiler.txt](https://github.com/aws/aws-sdk-ruby/files/10890521/heap_analysis_from_shopify_heap_profiler.txt)

### Reproduction Steps

I don't have time right now to create the smallest possible self contained correct example.  I'll hopefully have time to get onto that during the week.

### Possible Solution

I've listed the bug as being in the aws-sdk-kinesis gem but to be fair it is probably in the Seahorse client within aws-sdk-core.

https://github.com/aws/aws-sdk-ruby/blob/cfd0f0d05ad5e56cb00eee1dc81a244ca4c695f4/gems/aws-sdk-core/lib/seahorse/client/h2/connection.rb#L109

Short is there is no back pressure there, the thread consuming data from the socket will do so until it is closed or the process runs out of memory.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-kinesis (1.45.0), aws-sdk-core (3.170.0)

### Environment details (Version of Ruby, OS environment)

Ruby 3.1.3, Debian bullseye-slim 11.6, Kubernetes

**Comment by alextwoods** [comment]
Sorry you're running into this!  A minimal example would be great, but in the meantime, can you provide some details on how the producers/consumers are structured - eg, are these multiple threads in a single application?

**Comment by jpaulgs** [comment]
Yeah I'm sorry about not getting a minimal example up, we have found it difficult to produce one so far...

We currently have 8 active shards in the kinesis feed (4 were split) this is being processed by 4 ruby workers (individual processes running on different kubernetes pods) each consuming 2 shards.  These workers are run on kubernetes with 2GB of RAM.  This works fine until a burst of data comes through or the consumers slow down (even a little bit) at which point memory usage spikes and the pods get reaped.

**Comment by alextwoods** [comment]
Yeah - creating examples for these is hard.  I'm also working on trying to reproduce this...

How are you creating async clients on the workers? Are you sharing a single async client per worker?

Each async client should have a single H2::Connection, which should have only a single socket thread which is reading from the socket - and that thread is what runs any event handlers.  So if your event handlers slow down, it should effectively slow down the reads from that socket.  

How are you processing events? Can you provide any details?

**Comment by jpaulgs** [comment]
We spawn a thread for each shard (2 per worker).  Within each of these threads we create an async client and subscribe that thread scoped AsyncClient to consume from 1 shard. We are processing each event as it arrives by passing a block to `AsyncClient#subscribe_to_shard`.

each thread blocks using `async_resp.wait`.  When that wait step unblocks we allow the thread to die and create a new one.

We have played around with creating a single AsyncClient and passing it to each thread.  That change did not stop our kubernetes pods being reaped with memory exceeding 2GB

**Comment by alextwoods** [comment]
Thanks for description - that sounds pretty reasonable.  I've been working on creating some similar small test case and was able to do a bit of memory profiling.  I'm not 100% confident that this will fix your issue, but it does significantly reduce the number of large string allocations that are being done: #2834  and overall reduces the memory used (as long as you are not setting `http_wire_log` to `true`, which I assume you aren't for a production application....).

**Comment by mullermp** [comment]
@jpaulgs Are you seeing this issue again with the latest version of kinesis and aws-sdk-core 3.170.1?

**Comment by jpaulgs** [comment]
@mullermp we'll bump to using that version tomorrow but we are currently keeping up with records in prod so it'll take a little while to confirm.

**Comment by mullermp** [comment]
Thanks, just let us know. Re-open the ticket if it auto closes and it's still not resolved.
