### ISSUE TITLE
Aws::S3::Presigner #presigned_url to allow a custom hostname

### ISSUE THREAD

**Issue by pekevski** [aws/aws-sdk-ruby#2845]
### Describe the feature

Generating a PUT presigned_url for an s3 object should allow for a custom proxy hostname to be used in the generated url. Currently we proxy direct upload requests to an s3 location by a whitelisted hostname. 

As its currently implemented I believe the bucket name is returned as the presigned url hostname and this could be customised?

### Use Case

It would be a general requirement to have a whitelisted hostname that enables clients to directly upload content to a presigned url. The fact that it defaults to the buckets name as the hostname means that the "bucket named" hostname would need to be whitelisted as well?

### Proposed Solution

There could be an option for a `proxy_hostname` just like the `virtual_host` option param

eg:
```
url = signer.presigned_url(:get_object, bucket: "bucket", key: "key", proxy_hostname: "myapp.com/upload")

# url => https://myapp.com/upload/<bucket_name>/<key>/<signature_headers>
```

### Other Information

Could the `Aws::Sigv4::Signer#presigned_url` method handle a custom url parameter for this usecase?
If so, then maybe the S3 bucket interface could be extended to handle a custom hostname?
Alternatively, this can be achieved by lower level api methods that I am unaware of - I would love to know!

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.120

### Environment details (OS name and version, etc.)

Mac OSX Ventura 13.2.1

**Comment by mullermp** [comment]
It seems like you're needing a custom endpoint and not actually a proxy. `Aws::S3::Presigner` takes a `client` option where you can pass a new instance of `Aws::S3::Client` that can be configured with a custom `:endpoint` option, and additionally `:http_proxy` if you really need proxy behavior.

**Comment by pekevski** [comment]
@mullermp Thanks for the reply. 

I did test with a `Aws::S3::Client` with an `endpoint` and it still contained the bucketname in the host name in v1.120. Would there be a way where the bucketname doesn't belong to the presigned url at all?

**Comment by mullermp** [comment]
@pekevski I think you may need to set the `force_path_style: true` option on the client, so that the bucket is on the path and not the host. Is that what you mean?
