### ISSUE TITLE
aws-sdk-s3 fails when downloading file of exactly 20971524 bytes from S3 bucket bug 

### ISSUE THREAD

**Issue by cmaion** [aws/aws-sdk-ruby#2859]
### Describe the bug

Hi,

Using FileDownloader's multithreaded download, downloading a file that is exactly 20971524 bytes long results in an `Aws::S3::Errors::InvalidRange` (The requested range is not satisfiable) exception.

The issue comes from what looks like a off-by-one error, resulting in that case in an invalid range for that last chunk.

### Expected Behavior

File should obviously be downloadable without an exception due to incorrect math/logic :)

### Current Behavior

```
[Aws::S3::Client 206 12.824679 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=0-5242880")  
[Aws::S3::Client 206 12.635049 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=5242881-10485761")  
[Aws::S3::Client 206 15.445052 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=10485762-15728642")  
[Aws::S3::Client 206 11.991756 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=15728643-20971523")  
[Aws::S3::Client 416 0.804207 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=20971524-20971524") Aws::S3::Errors::InvalidRange The requested range is not satisfiable
```

The last chunk is empty/non existant, resulting in the exception.

### Reproduction Steps

Any 20971524 bytes long file should show the error, using default `download_file` options.

### Possible Solution

From my understanding, instead of downloading chunks that are MIN_CHUNK_SIZE (= 5242880 bytes) long, the code currently downloads chunks that are MIN_CHUNK_SIZE+1 long.

A file that is 20971524 bytes long should be downloaded as 4 5242880-bytes parts + a last 4-bytes part (20971524 = 5242880 * 4 + 4): 5 parts in total.
However, as the code downloads 5242880+1 bytes parts, we currently have 4*5242881 parts plus a final... 0-byte part (which is invalid).

Possible solutions:
- avoid building empty chunks
- fix `construct_chunks` to build `default_chunk_size` long parts instead of `default_chunk_size+1` (then, also check that a file that is exactly 4*5242880 bytes long gets downloaded in 4 parts w/o a final empty part)

### Additional Information/Context

See also https://github.com/aws/aws-sdk-ruby/issues/2561

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

Ruby 3.1, 3.2, Linux

**Comment by mullermp** [comment]
Thanks for opening an issue. This looks similar to https://github.com/aws/aws-sdk-ruby/issues/2561

**Comment by cmaion** [comment]
@mullermp indeed, but the fix made at that time isn't complete/fully correct

**Comment by mullermp** [comment]
I think the fix is as simple as (in construct_chunks):
```
          progress = offset + default_chunk_size - 1
```
This seems to work:
```
[Aws::S3::Client 206 0.414002 0 retries] head_object(bucket:"mamuller-us-west-2",key:"2859",part_number:1)  
[Aws::S3::Client 206 0.377534 0 retries] get_object(bucket:"mamuller-us-west-2",key:"2859",range:"bytes=20971520-20971524")  
[Aws::S3::Client 206 1.582501 0 retries] get_object(bucket:"mamuller-us-west-2",key:"2859",range:"bytes=0-5242879")  
[Aws::S3::Client 206 3.269059 0 retries] get_object(bucket:"mamuller-us-west-2",key:"2859",range:"bytes=15728640-20971519")  
[Aws::S3::Client 206 3.289127 0 retries] get_object(bucket:"mamuller-us-west-2",key:"2859",range:"bytes=5242880-10485759")  
[Aws::S3::Client 206 3.975748 0 retries] get_object(bucket:"mamuller-us-west-2",key:"2859",range:"bytes=10485760-15728639")  
```

**Comment by mullermp** [comment]
I think there's some other logic here that is funky. I will investigate.

**Comment by cmaion** [comment]
Thanks for looking into this.

A better/cleaner fix might be (IMHO):
```
      def construct_chunks(file_size)
        offset = 0
        default_chunk_size = compute_chunk(file_size)
        chunks = []
        while offset < file_size
          progress = offset + default_chunk_size
          progress = file_size if progress > file_size
          chunks << "bytes=#{offset}-#{progress - 1}"
          offset = progress
        end
        chunks
      end
```

Notes:
- the last chunk should stop at `file_size - 1`, not `file_size` (as bytes are numbered starting at 0)
- for the same reason, the while loop should thus proceed until `offset == file_size`, not `offset > file_size` (hence, `<` instead of `<=`)

I didn't test all cases, but that works for me here for a few different cases (resulting file size & sha1sum are good).

In the case of the 20971524 bytes file, this builds the following correct chunks (all exactly 5 * 1024 * 1024 bytes long + that last remaining 4 bytes):
```
[Aws::S3::Client 206 0.509849 0 retries] head_object(bucket:"xxx",key:"yyy.jpeg",part_number:1)  
[Aws::S3::Client 206 1.04149 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=0-5242879")  
[Aws::S3::Client 206 2.909884 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=5242880-10485759")  
[Aws::S3::Client 206 1.415331 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=10485760-15728639")  
[Aws::S3::Client 206 1.416281 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=15728640-20971519")  
[Aws::S3::Client 206 0.60983 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=20971520-20971523")  
```

**Comment by mullermp** [comment]
Something's off with that proposed change. For a file of size 5242881, I'm seeing these ranges (notice a 1 byte range):
```
[Aws::S3::Client 206 0.377988 0 retries] get_object(bucket:"mamuller-us-west-2",key:"boundary_plus_1",range:"bytes=5242880-5242880")  
[Aws::S3::Client 206 1.318815 0 retries] get_object(bucket:"mamuller-us-west-2",key:"boundary_plus_1",range:"bytes=0-5242879") 
```

**Comment by cmaion** [comment]
Yes, that looks absolutely correct to me: that file is exactly 1 full chunk (5 * 1024 * 1024 bytes) + 1 remaining byte.
S3 doesn't seem to have an issue with that 1 byte long range, just verified that live.

I guess the issues you had previously with the 1 byte range was not because it's not supported by S3, it's because you were requesting a final byte that was past the end of the file (due to the off-by-one error at the end of the final range).
(which also means that the `chunk_size -= 1 if file_size % chunk_size == 0` hack in commit 654624e811b3040ee4664ef21ae49f6d9c70cb78 is probably not needed with that proposed fix)

**Comment by cmaion** [comment]
BTW, a possible optimization exists if the last final chunk size ends up under a given threshold: just extend the last 5 * 1024 * 1024 chunk to go all the way to the end of the file (eg, no need to build a final <1024 bytes chunk, we may as well extend the last one in that case).

Something along:
```
progress = file_size if progress > file_size - THRESHOLD
```

**Comment by mullermp** [comment]
Interesting! 1 byte ranges do work. I don't know if that's a new change or not. In our tests (specs), the comment is to the contrary. Your proposed change does work and it does allow me to remove that hack. Thanks for pointing this out.

**Comment by cmaion** [comment]
Oh ok I wasn't aware that the spec goes against 1 byte ranges.

I would thus suggest that a threshold (eg, a few kB or even up to 1MB) is added (as per https://github.com/aws/aws-sdk-ruby/issues/2859#issuecomment-1572147185) to avoid ridiculously small final chunks? That would eliminate that 1 byte range issue/question.

**Comment by mullermp** [comment]
(Sorry, our test files, not the s3 specification)

**Comment by mullermp** [comment]
Weirdly, `get_object`s output has a content range of `content_range="bytes 10485760-15728639/15728640"` - the byte range is zero indexed but the file's size is 15728640. I would expect it to be 15728639. That would really imply 15728640 + 1 bytes are available to be read. When reading a range of `bytes=10485760-15728640` (chunk size + 1), I get back a body that has 1 chunk of size. I guess maybe this is some null character.

**Comment by cmaion** [comment]
Looks good to me, this matches the http specification for the Content-Range header.
Total file size is indeed 15728640, but the last range is *nnn*-15728639.

See https://httpwg.org/specs/rfc7233.html#header.content-range. I quote:
```
The following are examples of Content-Range values in which the selected representation contains a total of 1234 bytes:

    The first 500 bytes:

      Content-Range: bytes 0-499/1234

    The second 500 bytes:

      Content-Range: bytes 500-999/1234

    All except for the first 500 bytes:

      Content-Range: bytes 500-1233/1234

    The last 500 bytes:

      Content-Range: bytes 734-1233/1234

```

**Comment by mullermp** [comment]
Perfect. I've updated the PR and with tests if you would like to view/approve it.

**Comment by cmaion** [comment]
Great, thanks @mullermp!
