### ISSUE TITLE
Feature: Support `stub_responses:` kwarg in InstanceProfileCredentials

### ISSUE THREAD

**Issue by adi-pen** [aws/aws-sdk-ruby#2862]
### Describe the feature

Allow  stubbing of InstanceProfileCredentials by supporting `stub_responses` kwarg added by https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html#stub_responses-instance_method

### Use Case

Unit testing code that involves using `InstanceProfileCredentials` will be easier and the syntax to create client stubs will be easier.

I encountered https://github.com/aws/aws-sdk-ruby/issues/2617 as specifying `Aws::InstanceProfileCredentials(stub_responses: true)` did not do what I intended and had to spend a trivial amount of time to figure out `stub_responses` is not supported by this object from the documentation.

Since, this syntax is supported in a lot of other objects in the SDK it would be easier to use stubbing if the same kwarg is supported here.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

Release v2.11.632 - 2020-11-20

### Environment details (OS name and version, etc.)

Linux

**Comment by mullermp** [comment]
Thanks for opening an issue. Can you share your testing use case on why you need to test InstanceProfileCredentials? If you are stubbing a client, credentials are stubbed too.

**Comment by adi-pen** [comment]
I was trying to test a behavior that relied on a verbose method that had an instance of `Aws::InstanceProfileCredentials` outside a client.

```ruby
def s3
  # Fetch credentials
  credentials = Aws::InstanceProfileCredentials.new

  # STS client
  sts_client = Aws::STS::Client.new(region: 'us-east-1', credentials: credentials)

  # Assume role
  role_credentials = Aws::AssumeRoleCredentials.new(client: sts_client, role_arn: "somerole")

  #s3 client
  ...
end
```

On second thoughts, I think I can live even without this feature!

**Comment by mullermp** [comment]
Yes I wouldn't recommend a stub_responses for this class. I see you're also using v2 of the Ruby SDK which is deprecated - any update I make would not reach you. I think you can do this with a test double:

```
credentials = double('InstanceProfileCredentials')
expect(Aws::InstanceProfileCredentials).to receive(:new).and_return(credentials)
stubbed_sts = Aws::STS::Client.new(stub_responses: true)
expect(Aws::STS::Client).to receive(:new).with(credentials: credentials).and_return(stubbed_sts)
```
You could apply a double similarly to AssumeRoleCredentials.
