### ISSUE TITLE
Need WorkerId in Mturk Event 

### ISSUE THREAD

**Issue by lakshmicode** [aws/aws-sdk-ruby#2864]
### Describe the feature

The current Mturk Event has EventType, EventTimestamp, HITId, AssignmentId and HITTypeId. 

Since the AssignmentId is reused multiple times for when workers returning/abandoning assignments, We could not determine which event belongs to which worker and events forwarded to SQS message are not always in same created order. 

So we need WorkerId data inside Mturk event data. 

### Use Case

Since the AssignmentId is reused multiple times for when workers returning/abandoning assignments, We could not determine which event belongs to which worker and events forwarded to SQS message are not in same created order always. 

Sometimes we are facing issues with assignments worker doing the survey which has re-assigned AssignmentId. 
 

### Proposed Solution

We need WorkerId data inside Mturk event data to handle the events effectively.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by mullermp** [comment]
Were you able to resolve your issue? I see that you also opened a discussion.
