### ISSUE TITLE
Stub response_target

### ISSUE THREAD

**Issue by tke578** [aws/aws-sdk-ruby#2898]
### Describe the issue

I am trying to stub the `response_target` in the `get_object` function call.
I currently have this setup in my test suite
```
Aws.config[:s3] = {
                     stub_responses: {
                       list_buckets: {
                         buckets: [name: 'bucket_name'
                       },
                       list_objects_v2: {
                         contents: [{key: "some_key"}]
                       },
                       get_object: {
                         body: "lorem ipsum",
                         response_target: "trying_to_stub/this"
                       }

                     }
                   }
```
I get a `ArgumentError: unexpected value at params[:response_target]`
I don't see any documentation on this.
If I remove the `response_target` key, it will try to create the file(which i don't want)

### Links

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html

**Comment by mullermp** [comment]
`response_target` isn't a member of the API so it's not something that can be stubbed. Are you using rspec? You should be able to mock that with `expect(File).to receive(:write)...` or something equivalent. I can look to see if we can add an easier way to do this.

**Comment by tke578** [comment]
@mullermp that makes sense then. It looks like its handed by the Seahorse client. 

As a temp solution, I was able to have the file exist(file fixture) in my test suite so something like `rails_root_project/test/fixtures/files/the_name_of_the_file` and making sure that `$the_name_of_the_file` is the same name in my test suite(response_target)

No, I am not using Rspec.
Thanks!

**Comment by mullermp** [comment]
Just curious, how are you testing if not with rspec? With mini test?

You can also consider Tempfile somehow, but I'm not sure what your current test setup and logic looks like.

**Comment by tke578** [comment]
Apologies. Yes, minitest.
That could also work.

**Comment by tke578** [comment]
@mullermp Should I close this issue since its outside the scope of this gem?

**Comment by mullermp** [comment]
Yes. Thank you. Sorry that you ran into this, but I do believe mocking is correct for this feature.
