### ISSUE TITLE
SDK throw ArgumentError when the "workgroup_name" input is valid in Aws::RedshiftDataAPIService::Client

### ISSUE THREAD

**Issue by ch0ngxian** [aws/aws-sdk-ruby#2903]
### Describe the bug

I trying to call Redshift data API from my API server. But keep getting the ArgumentError stating "unexpected value at params[:workgroup_name]" while the workgroup_name string is valid. 

I had tried to use the same params in AWS cli and it successfully return the result without throwing error.

### Expected Behavior

Expected to be returning response of databases list in JSON format just like in AWS cli.
<img width="982" alt="Screenshot 2023-08-26 at 7 24 19 PM" src="https://github.com/aws/aws-sdk-ruby/assets/110162475/ccc0e526-e03c-42cf-83d8-04d9b14309c9">

### Current Behavior

Current is getting ArgumentError
<img width="530" alt="Screenshot 2023-08-26 at 7 29 33 PM" src="https://github.com/aws/aws-sdk-ruby/assets/110162475/e7683550-db0d-41dd-9841-6bd945c2d45b">

### Reproduction Steps

```ruby
    client = Aws::RedshiftDataAPIService::Client.new(
      region: 'ap-southeast-1',
      credentials: Aws::Credentials.new(
        Rails.application.credentials.config[:aws_redshift_key],
        Rails.application.credentials.config[:aws_redshift_secret]
      )
    )

    response = client.list_databases(
      database: "dev",
      workgroup_name: "arn:aws:redshift-serverless:ap-southeast-1:xxxx:workgroup/xxxx-xxx-xx-xx-xx"
    )
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-redshiftdataapiservice

### Environment details (Version of Ruby, OS environment)

Ruby version: 3.1.2. OS: Ubuntu 18.04.6 LTS

**Comment by mullermp** [comment]
Are you using the most recent version of the gem? 1.31.0

**Comment by ch0ngxian** [comment]
Thanks for the reply. Just noticed originally I using older version of aws-sdk-redshiftdataapiservice gem. Upgrading to latest version solved the issue.
