### ISSUE TITLE
CognitoIdentityCredentials is not including the logins set when getting credentials, making all requests unauthenticated

### ISSUE THREAD

**Issue by ja6lee** [aws/aws-sdk-ruby#2941]
### Describe the bug

When using CognitoIdentityCredentials, the `logins` passed in in the initializer are not used when getting credentials from AWS, so the request appears as unauthenticated. Unless I am misunderstanding what this class does, it should be including those logins with the requests to get credentials.

If instead you do almost exactly what `CognitoIdentityCredentials` is doing except including logins:
```
 identity_id = @client.get_id(identity_pool_id: <IDENTITY_POOL_ID>).identity_id
 credentials = @client.get_credentials_for_identity(
   identity_id: identity_id,
     logins: {
       "accounts.google.com" => <id_token_from_google>
     }
 )
```
It successfully fetches credentials.

### Expected Behavior

The logins passed in are included with the call to `get_credentials_for_identity`.

### Current Behavior

The logins are not passed in when calling `get_credentials_for_identity` so you receive the following error:
```
Unauthenticated access is not supported for this identity pool.
```

### Reproduction Steps

Steps to reproduce:
1. Setup an identity pool on AWS that only accepts 3rd party logins (eg. Google). No guest access. 
2. Create a `CognitoIdentityCredentials`  provider and include `logins`. Eg:
```
    Aws::CognitoIdentity::CognitoIdentityCredentials.new(
      identity_pool_id: <IDENTITY_POOL_ID>,
      logins: {
        "accounts.google.com" => <id_token_from_google>
      }
    )
```
3. Receive an error from AWS: `Unauthenticated access is not supported for this identity pool.`

### Possible Solution

Add `logins` to the refresh function here: 
https://github.com/aws/aws-sdk-ruby/blob/903cfb08e01e439c8d115ad8f6428a7539f7b142/gems/aws-sdk-cognitoidentity/lib/aws-sdk-cognitoidentity/customizations/cognito_identity_credentials.rb#L122C20-L122C20

eg. 
```
resp = @client.get_credentials_for_identity(
  identity_id: identity_id,
  custom_role_arn: @custom_role_arn,
  logins: @logins
)
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-cognitoidentity (1.49.0)

### Environment details (Version of Ruby, OS environment)

Ruby 3.2.2, OS: Mac OSX

**Comment by jterapin** [comment]
Thank you for reaching out to us! I will be taking a look.

**Comment by jterapin** [comment]
This is in our internal queue and we will release a fix.

**Comment by mullermp** [comment]
This was fixed in https://github.com/aws/aws-sdk-ruby/pull/2944

**Comment by mullermp** [comment]
1.49.1 (2023-11-15)
