### ISSUE TITLE
`Aws::BedrockRuntime::Types::<X>` doesn't have `event_type=`

### ISSUE THREAD

**Issue by elijahkim** [aws/aws-sdk-ruby#2942]
### Describe the bug

When AWS returns an error to the bedrock runtime client when streaming, it raises 
```
undefined method `event_type=' for #<struct Aws::BedrockRuntime::Types::ThrottlingException message="Too many requests, please wait before trying again. You have sent too many requests. Wait before trying again.">
``` 

### Expected Behavior

To be able to handle it with `handler.on_error_event`

### Current Behavior

it raises 
```
undefined method `event_type=' for #<struct Aws::BedrockRuntime::Types::ThrottlingException message="Too many requests, please wait before trying again. You have sent too many requests. Wait before trying again.">
``` 

### Reproduction Steps

```
body =  {  
  "prompt" => "Instructions: This is a test. Respond confirming a successful response\n\nHuman: (Taps, mic...) Is this thing on?\n\nAssistant: ",
  "temperature": 0.7,
  "max_tokens_to_sample": 1000000
}

Aws::BedrockRuntime::Client.new().invobe_model_with_response_stream({body: body.to_json, model_id: "anthropic.claude-v2})
```

### Possible Solution

Give all the `Aws::BedrockRuntime::Types::<X>` `event_type=` method 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-bedrockruntime (1.1.0)

### Environment details (Version of Ruby, OS environment)

Ruby 3.0, macOS

**Comment by jterapin** [comment]
Thanks for reaching out! We will be taking a look.

**Comment by mullermp** [comment]
I've put out a PR for the fix, it will probably be reviewed Monday morning and hopefully released Monday or Tuesday. In the mean time, you can probably monkey patch the event_type member to the structure.
