### ISSUE TITLE
[aws-sdk-sqs] Aws::SQS::Types::SendMessageBatchResult#failed returns nil

### ISSUE THREAD

**Issue by RyosukeNishi** [aws/aws-sdk-ruby#2957]
### Describe the bug

`Aws::SQS::Types::SendMessageBatchResult#failed` is supposed to return `Array<[Types::BatchResultErrorEntry]` ([ref](https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/SQS/Types/SendMessageBatchResult.html#failed-instance_method))  but returns nil.

### Expected Behavior

Returns `Array<[Types::BatchResultErrorEntry]`.

### Current Behavior

Returns nil.

### Reproduction Steps

```
res = sqs_client.send_message_batch({ queue_url: some_queue_url, entries: some_entries })
puts res.failed.inspect
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-sqs (1.67.0)

### Environment details (Version of Ruby, OS environment)

3.2.2, Debian 10

**Comment by mullermp** [comment]
Thanks for opening an issue. SQS changed its underlying protocol. Which version of aws-sdk-core are you using?

**Comment by RyosukeNishi** [comment]
I'm using `aws-sdk-core (3.186.0)`.

**Comment by mullermp** [comment]
Please upgrade to at least 3.187.1. I believe it should fix your issue.

**Comment by RyosukeNishi** [comment]
@mullermp 
Just in case, does downgrading to 1.65 still work?

**Comment by RyosukeNishi** [comment]
Confirmed that I can avoid the issue by downgrading aws-sdk-sqs to 1.65.
I have yet to check if the issue is resolved by upgrading aws-sdk-core to 3.187.1.

**Comment by jdelStrother** [comment]
Just to confirm, at least in our case these upgrades fixed the issue:

```diff
-    aws-sdk-core (3.187.0)
+    aws-sdk-core (3.188.0)
-    aws-sdk-sqs (1.67.0)
+    aws-sdk-sqs (1.68.0)
```

**Comment by mullermp** [comment]
I will go ahead and close this issue, please reopen if there's an issue with the latest versions.
