### ISSUE TITLE
aws-sdk-sesv2 API :next_token Symbol key literal doesn't work as expected (but String key does)

### ISSUE THREAD

**Issue by johnnyshields** [aws/aws-sdk-ruby#2958]
### Describe the bug

This is tested on latest release:

```
aws-sdk-sesv2 (1.42.0)
aws-sdk-core (3.188.0)
```

Given the following code:

```ruby
client = ::Aws::SESV2::Client.new(region: @region, credentials: @credentials)
response = client.list_suppressed_destinations(@query)
response2 = client.list_suppressed_destinations({ next_token: response.next_token })
```

The 3rd line will raise `InvalidNextTokenException` because the key literal `:next_token =>` is given as a Symbol and not a String `"next_token" =>`. The following works around the issue:

```ruby
response2 = client.list_suppressed_destinations({ "next_token" => response.next_token })
```

**For clarity:** This issue is in reference to the **KEY** literal in the arg Hash. The **VALUE** is a String either way.

### Expected Behavior

`:next_token` key literal should be possible to use as either a String or a Symbol, with identical behavior either way.

### Current Behavior

Using a String literal as the key works as expected. If Symbol is used, it raises `InvalidNextTokenException`.

### Reproduction Steps

See above

### Possible Solution

`:next_token` key literal should be possible to use as either a String or a Symbol, with identical behavior either way.

### Additional Information/Context

I believe this was working properly on older versions and may have broken recently.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-sesv2 (1.42.0), aws-sdk-core (3.188.0)

### Environment details (Version of Ruby, OS environment)

Ruby 3.2, Debian GNU/Linux 11 (bullseye)

**Comment by mullermp** [comment]
Thanks for opening an issue. I don't mind taking a deeper look into this, but is there a reason you aren't using the `response.next_page?` and `response.next_page` methods? These methods will handle pagination for you.

**Comment by johnnyshields** [comment]
@mullermp because I didn't know about it :) I'll try it now

**Comment by mullermp** [comment]
I'm also not able to reproduce this. Using Ruby 3.2 and the latest SDK clients.

```
resp = sesv2.list_suppressed_destinations(page_size: 1)
```
returns me one item, with a `next_token` that is a long string. I can then use it this way:

```
resp = sesv2.list_suppressed_destinations(page_size: 1, next_token: resp.next_token)
```
and my second item is returned. I'm using a keyword arg.

Maybe try removing the hash params `{}` and try with keyword arguments? I tried both ways and both work.

Were you able to get it working using `next_page`?
