### ISSUE TITLE
presigned_url always adds content-type to signed headers

### ISSUE THREAD

**Issue by xanderman** [aws/aws-sdk-ruby#3027]
### Describe the bug

Starting in aws-sdk-core 3.192.0, the behavior of `presigned_url` changed to always add `content-type` as a signed header even when it is not specified in the params. We don't know ahead of time what type of file will be uploaded, so need to allow anything. I don't even know what content-type is expected, since I didn't specify one in the `presigned_url` call. This breaks our uploads, and is preventing me from upgrading aws-sdk gems.

### Expected Behavior

Prior to 3.192.0, `presigned_url(:put, { acl: 'bucket-owner-full-control', server_side_encryption: 'AES256', expires_in: 600 }` would return a URL with `X-Amz-SignedHeaders=host`.

### Current Behavior

Starting with 3.192.0, `presigned_url(:put, { acl: 'bucket-owner-full-control', server_side_encryption: 'AES256', expires_in: 600 }` returns a URL with `X-Amz-SignedHeaders=content-type;host`.

### Reproduction Steps

`presigned_url(:put, { acl: 'bucket-owner-full-control', server_side_encryption: 'AES256', expires_in: 600 }`

### Additional Information/Context

I've tried setting various values for `content_type:` in the params hash (`nil`, `''`, `'*'`) but none of them remove content-type from the signed headers, or allow arbitrary uploads.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

Ruby 3.2.2. I'm on an M1 Mac, but this also happens in our docker image which is slim-bookworm.

**Comment by mullermp** [comment]
Thanks for opening an issue. Are you using the latest aws-sdk-s3? I believe that gem was updated to remove content type for presigned url in this case.

https://github.com/aws/aws-sdk-ruby/blob/version-3/gems%2Faws-sdk-s3%2Flib%2Faws-sdk-s3%2Fpresigner.rb#L202

**Comment by xanderman** [comment]
You are absolutely right. Thanks for your help, and sorry for the pointless bug report. I have too many dependabot PRs. I could have sworn I ran my tests in all of them, but obviously I missed the one with the aws-sdk-s3 update, because it works in that one. Thanks!
