### ISSUE TITLE
Access to the credit_notes?

### ISSUE THREAD

**Issue by craighawkes** [aws/aws-sdk-ruby#3052]
### Describe the feature

Can we add access to the credit notes as per:
https://developers.maxio.com/docs/api-docs/a4b4ed8882287-list-credit-notes

### Use Case

We are trying to reconcile and post into a GL, but without credit notes things don't balance?

### Proposed Solution

I think we just need to add in new controller and access via the client? 
I think I maybe able to do this, but it looks like a lot of the code is auto generated? so makes sense for it to be a part of that if that's possible?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.0

### Environment details (OS name and version, etc.)

any

**Comment by mullermp** [comment]
Hello. I am not quite sure what you're asking. How does this partain to the AWS SDKs?

**Comment by craighawkes** [comment]
oh - sorry I've posted this against the wrong repo.
