### ISSUE TITLE
Days is a required parameter in S3 restore_object

### ISSUE THREAD

**Issue by mullermp** [aws/aws-sdk-ruby#3134]
Original issue: https://github.com/aws/aws-sdk-ruby/issues/2380

For S3's restore object, the docs state:

```
Objects in the GLACIER and DEEP_ARCHIVE storage classes are archived. To access an archived object, you must first initiate a restore request. This restores a temporary copy of the archived object. **In a restore request, you specify the number of days that you want the restored copy to exist.** After the specified period, Amazon S3 deletes the temporary copy but the object remains archived in the GLACIER or DEEP_ARCHIVE storage class that object was restored from.
```

"Days" cannot be set to required because the request might not be for GLACIER or DEEP_ARCHIVE.

The Ruby SDK sends valid XML

```
"<RestoreRequest xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"/>\n
```

The service responds with unhelpful text `The XML you provided was not well-formed or did not validate against our published schema`

The error message thrown here should be friendlier, such as "Days is missing"

**Comment by kellertk** [comment]
P126357524

**Comment by mullermp** [comment]
Thank you!

**Comment by zshzbh** [comment]
Hey there,

I'm closing this ticket as I have submitted a feature request to the service team. The updates will be posted on package release info and aws blogs. 

Thanks!
Maggie
