### ISSUE TITLE
How to send an APN alert message with a sound using SNS mobile push notifications?

### ISSUE THREAD

**Issue by goleador** [aws/aws-sdk-ruby#336]
This is not working:

AWS.sns.client.publish :message => { :aps => { :alert => params[:message]}}.to_json, :target_arn => target

I can send a message just fine. But if I try to structure the JSON it doesn't work.

**Comment by Sailias** [comment]
@jmstone617, your solution works for me.  

Double to_json, and sound: 'default' seems to do it.

**Comment by jayd3e** [comment]
I'm use the AWS Java SDK, and this thread really helped me.  Apparently all SNS SDKs require the platform-specific payload to be a string and not a nested object.  Encoding my JSON twice fixed the issue.
