### ISSUE TITLE
Publishing SNS message to topic not working

### ISSUE THREAD

**Issue by goleador** [aws/aws-sdk-ruby#346]
Here is the request and response:

[AWS SNS 400 0.799616 0 retries] publish(:message=>"{\"APNS_SANDBOX\":\"{\\"aps\\":{\\"alert\\":\\"678978698\\",\\"sound\\":\\"default\\"}}\"}",:message_structure=>"json",:subject=>"789579",:target_arn=>"arn:aws:sns:us-east-1:208143138780:new-workouts-topic") 

AWS::SNS::Errors::InvalidParameter Invalid parameter: Message Structure - No default entry in JSON message body

Completed 500 Internal Server Error in 5446ms

AWS::SNS::Errors::InvalidParameter (Invalid parameter: Message Structure - No default entry in JSON message body):

**Comment by nenetto** [comment]
I leave the [doc info](http://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.publish) here for future visits: 

> be a syntactically valid JSON object; and
contain at least a top-level JSON key of "default" with a value that is a string.
You can define other top-level keys that define the message you want to send to a specific transport protocol (e.g., "http").
