### ISSUE TITLE
AWS::S3::Errors::BadRequest when calling S3Object#exists?

### ISSUE THREAD

**Issue by gjastrab** [aws/aws-sdk-ruby#460]
Using 1.32.0, ruby 1.9.3-p484

Doesn't seem like calling <code>exists?</code> on an object should be raising an error like this?

Portion of the backtrace included:
- ".../shared/bundle/ruby/1.9.1/gems/aws-sdk-1.32.0/lib/aws/core/client.rb:368:in `return_or_raise`'", 
- ".../shared/bundle/ruby/1.9.1/gems/aws-sdk-1.32.0/lib/aws/core/client.rb:469:in `client_request`'", "(eval):3:in `head_object'",
- ".../shared/bundle/ruby/1.9.1/gems/aws-sdk-1.32.0/lib/aws/s3/s3_object.rb:293:in `head`'",
- ".../shared/bundle/ruby/1.9.1/gems/aws-sdk-1.32.0/lib/aws/s3/s3_object.rb:270:in `exists?`'"</pre>

**Comment by s2t2** [comment]
FYI on gem version 2.0.41 a call to `bucket.exists?` throws `rescue in exists?': Aws::S3::Errors::BadRequest` only if the bucket exists. The bucket in question was created using `bucket = resource.bucket(BUCKET_NAME)`. Please advise.

**Comment by trevorrowe** [comment]
@s2t2 Its not clear to me what you mean.  Using v2.0.41 I tried the following:

```ruby
# bucket I own, returns 200
S3::Bucket.new('aws-sdk').exists? #=> true

# bucket I do not own, returns 403, but still exists
S3::Bucket.new('demo').exists? #=> true

# non-existent bucket, returns 404, does not exist
S3::Bucket.new('asdfasdfasdfasdfasdfa1111').exists? #=> false
```

Can you give me a code example of what fails?

**Comment by s2t2** [comment]
Thanks for your fast reply. I was using the following code, which is now behaving differently than it was yesterday, in that yesterday it was throwing error when checking for existence of an **existing** bucket, whereas now its sometimes returning `true` and sometimes throwing an error when checking for existence of a **non-existent** bucket. And `resource.create_bucket` was working yesterday but now is attempting to create the bucket in the wrong region.

```` rb
creds = Aws::Credentials.new(KEY_ID, KEY_SECRET)
resource = Aws::S3::Resource.new(:credentials => creds, :endpoint => ENDPOINT, :region => REGION)
bucket = resource.bucket(BUCKET_NAME)
resource.create_bucket(:bucket => BUCKET_NAME) unless bucket.exists? #=> Aws::S3::Errors::BadRequest
````

Using the code you suggested, I'm getting the following...

```` rb
S3::Bucket.new(BUCKET_NAME)
=> NameError: uninitialized constant S3
Aws::S3::Bucket.new(BUCKET_NAME)
=>  Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
bucket = Aws::S3::Bucket.new(BUCKET_NAME, :region => REGION)
=> #<Aws::S3::Bucket name="testt">
bucket.exists?
=> Aws::S3::Errors::Http301Error
bucket = Aws::S3::Bucket.new(BUCKET_NAME, :credentials => creds, :endpoint => ENDPOINT, :region => REGION)
=> #<Aws::S3::Bucket name="testt">
bucket.exists?
=> Aws::S3::Errors::BadRequest
````

I may just be using the gem wrong, so any guidance you can give is appreciated.

**Comment by trevorrowe** [comment]
@s2t2 Sorry, I was running my examples from pry inside the `Aws` module with a globally configured region.

The Http301Error indicates that you have received a permanent redirect. Would you open this as a new issue. It looks like there are some bucket dns redirect issues to resolve.

**Comment by MicTech** [comment]
I have a same problem.

version `1.65.0`

**policy**

```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::bucketname",
                "arn:aws:s3:::bucketname/*"
            ]
        }
    ]
}
```

```
s3 = AWS::S3.new(:access_key_id => 'xxx', :secret_access_key => 'xxx')
bucket = s3.buckets['bucketname']
```

```
puts bucket.objects[source_key].acl
AWS::S3::Errors::NoSuchKey: No Such Key

puts bucket.objects[source_key].exists?
AWS::S3::Errors::BadRequest: AWS::S3::Errors::BadRequest
```

**Comment by awood45** [comment]
I think upgrading to version 2 of the SDK is the best path forward for that. We've dealt with these issues in V2 in a more thorough way. Plus, V1 is essentially deprecated, so I don't see non-critical work happening on it going forward.

**Comment by MicTech** [comment]
@awood45 That's correct and I agree with that, but unfortunately [Paperclip](https://github.com/thoughtbot/paperclip) doesn't support v2, at least not yet.

**Comment by awood45** [comment]
I'd encourage them to upgrade, if there are any blocking issues we're happy to look in to them.

**Comment by anoldguy** [comment]
I realize this is an old issue, but I found that being explicit about the region to fix the problem for us.

We were getting the `AWS::S3::Errors::BadRequest` for every call to `.exist?`. Our bucket was in us-east-2, and was somehow working without specifying the region. Once we passed region into the S3 client, all was well.

**Comment by ghost** [comment]
### I solved by changing my time zone (wich wasn't the correct one)

**Comment by iqre8** [comment]
It was the folder permission for me.
