### ISSUE TITLE
AWS::S3::Errors::Forbidden on calling content_length immediately after a successful copy_to on the same S3Object

### ISSUE THREAD

**Issue by gjastrab** [aws/aws-sdk-ruby#466]
I'm back with another odd (and probably rare) error just like #460 

This has been running across multiple servers for days without error since you shipped v.1.34.0 but just hit an odd bug:

Same setup/scenario as in #460 but another spot in the code is copying from this bucket into a different bucket and then updates an entry in our DB so that a model with a paperclip attribute will use this newly copied object.

<pre>
...
# assume file below is some model that has been created with a paperclip attribute called 'data'
filename = File.basename(node.key)
obj = node.object
begin
  obj.copy_to("files/data/#{file.id}/original/#{filename}", bucket_name: "OTHERBUCKET", acl: :public_read)
rescue AWS::Errors::Base => err
  @logger.fatal "Error copying #{obj.key} to 'files/data/#{file.id}/original/#{filename}'"
  raise err
end
file.update_attributes(data_file_size: obj.content_length, data_file_name: filename, data_content_type: obj.content_type)
...
</pre>

In one instance this crashed on the last line in this snippet when calling `obj.content_length`.  It doesn't make sense why this operation would ever be forbidden when the `obj.copy_to` just succeeded the line above in the begin...rescue.

Unfortunately I didn't have wire tracing enabled since 1.34.0 fixed my other issue, but in the log you see the `copy_to` response was 200 and the `content_length` one was 403:

<pre>[INFO] [AWS S3 200 0.088554 0 retries] copy_object(:acl=>:public_read,:bucket_name=>"OTHERBUCKET",:copy_source=>"BUCKETNAME/KEY/PATH",:key=>"KEY/PATH",:metadata_directive=>"COPY",:storage_class=>"STANDARD")  

[INFO] [AWS S3 403 0.906879 0 retries] head_object(:bucket_name=>"BUCKETNAME",:key=>"KEY/PATH") AWS::S3::Errors::Forbidden AWS::S3::Errors::Forbidden</pre>

Stacktrace below:

<pre>
# &lt;AWS::S3::Errors::Forbidden: AWS::S3::Errors::Forbidden&gt;
[".../aws-sdk-1.34.0/lib/aws/core/client.rb:374:in `return_or_raise'", 
".../aws-sdk-1.34.0/lib/aws/core/client.rb:475:in `client_request'", "(eval):3:in `head_object'", 
".../aws-sdk-1.34.0/lib/aws/s3/s3_object.rb:293:in `head'", 
".../aws-sdk-1.34.0/lib/aws/s3/s3_object.rb:317:in `content_length'"
</pre>

**Comment by trevorrowe** [comment]
Closing this stale issue, without further information I am unable to help debug the issue. Please re-open if you are able to reproduce with extra information.
