### ISSUE TITLE
AWS::S3::PresignV4 ignores `use_ssl?` when generating URLs

### ISSUE THREAD

**Issue by samwgoldman** [aws/aws-sdk-ruby#494]
I recently had an issue generating URLs for a presigned PUT request where S3 rejected the PUT request. I ultimately noticed the generated URL looked like http://host:443/path.

I was able to fix the issue by passing `{ secure: true }` with the options in PresignV4's constructor, but I believe that this configuration should be defaulted based on the implicit S3 config object or the client's generated Http::Request object, both of which have a use_ssl? property.

**Comment by vireshas** [comment]
Thanks a lot for that update @samwgoldman!
