### ISSUE TITLE
Stack level too deep error for RDS DB Instance termination

### ISSUE THREAD

**Issue by caerulean** [aws/aws-sdk-ruby#506]
My code uses the client library for RDS (V20130515) and it looks like this: 
```
AWS.rds.client.delete_db_instance(db_instance_identifier: rds_instance_vo.id, skip_final_snapshot: true)"
```
I get this intermittent error from time to time that results with this:
```
SystemStackError: stack level too deep
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-1.38.0/lib/aws/core/data.rb:194
```
I've looked at the file and it doesn't really make sense that the Cast method is throwing this error at me. Is this caused by a problem in the SDK or in my code?

**Comment by trevorrowe** [comment]
No plans to change the behavior in the v1 SDK at this time. The v2 SDK has a new implementation for stubbing responses that does not rely on a Core::Data pattern that should play nicely with factory girl.
