### ISSUE TITLE
Links generated by aws-sdk are not compatible with the iPad

### ISSUE THREAD

**Issue by gotoAndBliss** [aws/aws-sdk-ruby#513]
Thus so far, this works in all browsers ( IE7+, Safari, Chrome, Firefox, Opera, FF ), except for the iPad's Safari.

I create my links like so with the `aws-sdk-ruby` gem ( Version 1.38.0 ) ->

```ruby
      AWS.config S3Config::S3_CONFIG
      bucket = AWS.s3.buckets[S3Config::S3_CONFIG[:bucket]]
      s3_obj = bucket.objects[ 'quizzes/' + section.id.to_s + '/story.html']
      url    = s3_obj.url_for(:read).to_s
```

Which produces "something" like this. I redacted the actual passed params for security reasons ->

```html
https://s3.amazonaws.com/my_named_bucket/quizzes/10/story.html?AWSAccessKeyId=secretsecretsecret&Expires=1397053885&Signature=secretsecretsecret
```

If I put this URL directly into any browser, it works. If I view it through iPad's Safari, I get this ->

```ruby
SignatureDoesNotMatchThe request we calculated does not match the signature you provided. Check your key and signing method. 
```
This error is followed by some sort of hex code prepended to some 100 character long string prepended to "/my_named_bucket/quizzes/10/story.html" followed by a snippet of my AWS Key.

**Comment by trevorrowe** [comment]
Closing stale issue. This does not appear to be an SDK issue.
