### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by nonsense** [aws/aws-sdk-ruby#517]
I had a working project until recently, when this error started appearing:

```
NoMethodError: undefined method `each' for nil:NilClass
        from /home/vagrant/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.38.0/lib/aws/core/client.rb:719:in `define_client_methods'
        from /home/vagrant/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.38.0/lib/aws/ec2/client.rb:89:in `<class:V20130815>'
        from /home/vagrant/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.38.0/lib/aws/ec2/client.rb:88:in `<class:EC2>'
        from /home/vagrant/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.38.0/lib/aws/ec2/client.rb:15:in `<module:AWS>'
        from /home/vagrant/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.38.0/lib/aws/ec2/client.rb:14:in `<top (required)>'
```

I figured this might be due to wrong credentials, so I created new ACCESS_KEY and SECRET_ACCESS_KEY from the AWS Management Console.

Basically I run:

```
rails c
AWS.config(access_key_id: "xxx", secret_access_key: "xxx", region: "us-west-1")
AWS.ec2
```

And AWS.ec2 throws the error. Any ideas what I might be doing wrong? As you can see, I am using ruby 2.1.1 and aws-sdk-1.38.0.

The last time my project was working was with aws-sdk-1.32.0 if that makes any difference. I am not sure about the intermediate versions.

Thanks,
Anton

**Comment by mfamilia** [comment]
see safe_yaml gem documentation about configuration options since deserializing symbols is turned off by default.

https://github.com/dtao/safe_yaml
