### ISSUE TITLE
Document IAM policies for S3 operations

### ISSUE THREAD

**Issue by lsegal** [aws/aws-sdk-ruby#533]
Based on a conversation with [@crichardson (Twitter)](https://twitter.com/crichardson/status/464485089875750912), we should be documenting which IAM policy permissions are needed for each API call in the S3 docs.

**Comment by trevorrowe** [comment]
I've passed the request along to the team that maintains the Amazon S3 API reference documentation. Thanks for the feature request.

**Comment by cer** [comment]
Cool. You are welcome!
