### ISSUE TITLE
DynamoDB Local?

### ISSUE THREAD

**Issue by phstc** [aws/aws-sdk-ruby#549]
Hi

I'm trying to use [DynamoDB Local](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html), but I couldn't find a way to make it work with the ruby sdk.

``` ruby
AWS.config(
  access_key_id:          '...',
  secret_access_key:      '...',
  region:                 'us-east-1',
  dynamo_db_endpoint:     'localhost',
  dynamo_db_port:         8000
  }
)
```

I've also tried `AWS.config(access_key_id: '...', secret_access_key:  '...', base_url: 'http://localhost:8000')` but none of these options seem to be working.

PS: My DynamoDB local is up & running:

``` shell
$ java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory
2014-05-27 19:43:57.424:INFO:oejs.Server:jetty-8.1.12.v20130726
2014-05-27 19:43:57.454:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8000
```

**Comment by ttp** [comment]
have problems with connection to 'http://locahost:8000',
resolved by changing it to 'http://127.0.0.1:8000'
