### ISSUE TITLE
Retries on AWS::EC2::Errors::InsufficientInstanceCapacity

### ISSUE THREAD

**Issue by ab** [aws/aws-sdk-ruby#568]
Is it expected that run_instances would retry on `AWS::EC2::Errors::InsufficientInstanceCapacity`? My experience is that this is a condition that does not go away on the order of seconds or minutes, so it's surprising when these requests are retried for a long time before re-raising.

**Comment by grosser** [comment]
@trevorrowe this is broken again on at least `aws-sdk-ec2 >= 1.285.0` (it retries)

**Comment by grosser** [comment]
submitted https://github.com/aws/aws-sdk-ruby/issues/2786 to track it
