### ISSUE TITLE
EC2::Subnet does not support mapPublicIpOnLaunch

### ISSUE THREAD

**Issue by dantman** [aws/aws-sdk-ruby#580]
Looking at the documentation I see no property/method to view and control the mapPublicIpOnLaunch/MapPublicIpOnLaunch setting on VPC Subnets, which is exposed by the API.

**Comment by trevorrowe** [comment]
Closing this issue as there are no plans to expand the v1 SDK at this time. Feel free to use `AWS::EC2::Client` or the v2 Ruby SDK.
