### ISSUE TITLE
AWS.config, when used in chef (ruby_block), does not seem to honor credentials set in node['foo']['bar'] attributes

### ISSUE THREAD

**Issue by zerowolfgang** [aws/aws-sdk-ruby#594]
Howdy, not sure if this is the right place to raise this, but I need to start somewhere. That begin said I hope this is not a chef-thing but if it is perhaps you can clarify that.
I'm going on the assumption that you're/someone is familiar enough with chef and aws-sdk to shed some light on what I'm seeing :) I realize this issue I'm opening is Very chef-shaped, but please bare with me.

The short of it is if I set my AWS credentials in chef node attributes and try to access them
with a recipe to setup up AWS.config, the values are somehow not getting set ( and the recipe errors out). Example:

AWS.config(access_key_id: node[:my_id], secret_access_key: node[:my_key], region: 'eu-west-1')

I've also tried node['my_id'], node[:my_id] as well as node['some_attr']['some_other_attr'] variations as well, but no joy. In all these cases I get a:

```
AWS::S3::Errors::InvalidAccessKeyId
-----------------------------------
The AWS Access Key Id you provided does not exist in our records.
```
Using Chef::log.info to log node attribute values reports the credentials as correct:

Chef::Log.info "AWS CREDS: #{AWS.config.access_key_id} #{AWS.config.secret_access_key} #{AWS.config.region}"

[2014-07-30T13:15:23+00:00] INFO: AWS CREDS: my_access_key_id my_secret_access_key eu-west-1

Of course the standard incantation works as expected:

AWS.config(access_key_id: 'my_id', secret_access_key: 'my_key', region: 'eu-west-1')

Interestingly enough, the node attributes Are accessible when I setup AWS.config in a pry session as is hopefully evidenced here:

https://gist.github.com/zerowolfgang/f4e72e1abbd351603f5d

So what am I missing ? I've found anecdotal evidence on the interwebs that this Should work, http://lists.opscode.com/sympa/arc/chef/2013-01/msg00391.html , but I stumped.
At this point even abusive and berating criticism would be welcome :)

aws-sdk gem rev is 1.48.1

Regards,

@zerowolfgang

**Comment by trevorrowe** [comment]
I'm going to go ahead and close this issue for now. Its been stale for a while and it does not appear to be an issue with `aws-sdk`.

**Comment by zerowolfgang** [comment]
Roger that. It's more likely to be a derp on my part.
