### ISSUE TITLE
Route53 and Resource records

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#620]
We are in the process of switching over to the aws-sdk-core, but in the interim, are using this sdk for some things. How does one get a list of all the resource records in a zone? We prefer to use the client instead of the higher level resources. Have looked through the docs, but unable to find out how to do this. 

``` Ruby
r53.client.list_resource_record_sets({:hosted_zone_id => thezone})
```

That will return 100 resource records. We have over a 1000 records in one zone. Not sure how to incorporate the marker into this to page through the results from the client response. Anyone have any pointers?

thanks!

**Comment by jzajac2** [comment]
I'm having a hard time getting this to work. Am I supposed to use both of these `list_resource_record_sets` calls to get all results?:
```
# with pagingation, continues until all records have been returned
r53.client.list_resource_record_sets({:hosted_zone_id => thezone}).each do |resp|
  # ...
end

# all response objects are `PageableResponse` objects and know how to get the next page
resp = r53.client.list_resource_record_sets({:hosted_zone_id => thezone})
resp.last_page?
resp = resp.next_page until resp.last_page?
```

Or is just one of the calls sufficient? And if just the first one is sufficient (the one with the .each do loop, what goes in the `# ... ` ? Seems like I would need to append to a variable (or the resp object).

**Comment by srchase** [comment]
@jzajac2, 

Assuming you're using the current version of the SDK, pagination for that resource is handled by the SDK and documented here: [Paging Response Data](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/paging-responses.html).

The examples in the documentation show how to let the SDK handle paging through a built-in enumerator and how to manually page the results.
