### ISSUE TITLE
Regression: S3 library generating invalid policy for pre-signed url with custom conditions

### ISSUE THREAD

**Issue by BRMatt** [aws/aws-sdk-ruby#641]
When I generate a presigned URL for a bucket using "custom conditions", the `:secure` option is [passed through to a refined version of the pre-signed presigned URL generator](https://github.com/aws/aws-sdk-ruby/blob/4817e18dca12e6acc0326ffb5341955c753b0ba5/lib/aws/s3/presigned_post.rb#L375-L386), and [interpreted as an arbitrary HTTP header](https://github.com/aws/aws-sdk-ruby/blob/4817e18dca12e6acc0326ffb5341955c753b0ba5/lib/aws/s3/presigned_post.rb#L201-L204) that can be passed through to S3 (see #250 for more details).

When attempting to use this URL to upload files the API endpoint returns the following error:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy Condition failed: ["eq", "$Secure", "true"]</Message><RequestId>30AA79D6536CDF54</RequestId><HostId>O0Wc+rZomoc+0oONlJfNlQepoxP7X0gXdJ1gvXLvYIjfssPhYtr8WlSaOtgsArojhaBefNeuqU4=</HostId></Error>
```

[Here's a reproducible example of the problem](https://gist.github.com/BRMatt/11c5cdc66b18756f4c22).

I don't have time to make a PR at the moment, but it looks like the easiest fix would be to add `:secure` to `SPECIAL_FIELDS`.

**Comment by dsmithco** [comment]
Just to clarify I put..

  AWS::S3::PresignedPost::SPECIAL_FIELDS << :secure

inside my aws.rb

  # config/initializers/aws.rb
  require 'aws-sdk'
  AWS::S3::PresignedPost::SPECIAL_FIELDS << :secure
