### ISSUE TITLE
Documentation for doing "Parallel Scan" operations in DynamoDB

### ISSUE THREAD

**Issue by findchris** [aws/aws-sdk-ruby#643]
I was reading the [AWS docs on issuing a "Parallel Scan" in DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#QueryAndScanParallelScan), and it mentions the `Segment` and `TotalSegments` parameters, which I don't see in the `aws-sdk` [docs](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/DynamoDB/Client.html#scan-instance_method).  Am I missing something, or is this functionality not implemented?

Thanks.

**Comment by trevorrowe** [comment]
This functionality exists when using AWS::DynamoDB::Client::V20120810.
