### ISSUE TITLE
Tip on hash merging

### ISSUE THREAD

**Issue by baweaver** [aws/aws-sdk-ruby#647]
I've noticed this pattern a lot around the code:

```ruby
@ec2.key_pairs.inject({}) do |hash, key_pair|
  hash[key_pair.name] = key_pair.fingerprint
  hash
end
```

It could be written as:

```ruby
@ec2.key_pairs.reduce({}) { |hash, key_pair|
  hash.merge! key_pair.name => key_pair.fingerprint
}
```

Minor, yes, but it can save a few lines on occasion and relieve the need to explicitly put hash at the end as the implied return as ``merge`` returns the hash. I use ``merge!`` for a minor memory / speed gain, considering the accumulator (hash) is being returned that way either way.

**Comment by trevorrowe** [comment]
Thanks for the tip. In the v2 SDK I've been using the following (not 1.8.7 compat) as an inject replacement:

```ruby
source.each.with_object({}) do |(key,value), hash|
  hash[key] = value
end
```
