### ISSUE TITLE
AWS::Record::HashModel

### ISSUE THREAD

**Issue by cxhamilton** [aws/aws-sdk-ruby#651]
Is there a v2 functional equivalent for AWS::Record::HashModel that is in aws-sdk-v1?

**Comment by trevorrowe** [comment]
There is not one yet. That said, we are considering adding this as a separate gem built on the v2 SDK. I can not comment on timelines though. Thanks for the suggestions.

**Comment by sebhtml** [comment]
+1

**Comment by fedenusy** [comment]
+1

**Comment by awood45** [comment]
Sorry for not updating in this thread, but we have this feature in developer preview now.

Check out [aws-record](https://github.com/awslabs/aws-sdk-ruby-record) and give us feedback!

There's also an [introductory blog post](http://ruby.awsblog.com/post/TxEPQTRSEPJ2X8/Introducing-the-Aws-Record-Developer-Preview) that you may find interesting.

**Comment by joshmosh** [comment]
+1
