### ISSUE TITLE
Question: asynchronous SQS client?

### ISSUE THREAD

**Issue by blanchma** [aws/aws-sdk-ruby#652]
Is the ruby AWS SDK supporting asynchronous SQS client like described here: http://aws.amazon.com/blogs/aws/amazon-sqs-long-polling-batching/ ?

**Comment by trevorrowe** [comment]
There is no such feature for the Ruby SDK at this time. If one is added, it would be added to the v2 Ruby SDK which will be 2.0 stable shortly.
