### ISSUE TITLE
Documentation to_h returning AWS::Core::Data, not Hash

### ISSUE THREAD

**Issue by chenkirk** [aws/aws-sdk-ruby#653]
Was using ObjectMetadata's [to_h method](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/ObjectMetadata.html#to_h-instance_method) which says it should return Hash, I am getting an AWS::Core::Data object

```` 
2.0.0-p481 :260 > file.metadata.to_h.class
 => AWS::Core::Data 
2.0.0-p481 :261 > file.metadata.class
 => AWS::S3::ObjectMetadata 
````

Not too big of a deal, but it was a bit annoying when I tried to output it in a `"#{file.metadata.to_h}"`

````
2.0.0-p481 :265 > puts file.metadata.to_h
#<AWS::Core::Data:0x0000000155e898>
 => nil 
````

I actually have to to_h twice.

````
2.0.0-p481 :266 > puts file.metadata.to_h.to_h
{"uploaded-at"=>1413942635}
 => nil 
````

**Comment by trevorrowe** [comment]
This has been resolved in the v2 SDK (which will be 2.0 stable shortly). There are no plans to change this behavior in v1.
