### ISSUE TITLE
Plus "+" character on S3Object key

### ISSUE THREAD

**Issue by aliismayilov** [aws/aws-sdk-ruby#654]
It seems like there's some problem on `AWS::S3::S3Object#public_url`. `+` is being encoded. In fact the file location is:
* https://s3.amazonaws.com/bucket_name/files/document+copy.pdf
* NOT https://s3.amazonaws.com/bucket_name/files/document%2Bcopy.pdf

```ruby
[8] pry(main)> bucket = AWS::S3.new.buckets['bucket_name']
=> #<AWS::S3::Bucket:core_development>
[9] pry(main)> s3_object = bucket.objects['files/document+copy.pdf']
=> <AWS::S3::S3Object:bucket_name/files/document+copy.pdf>
[10] pry(main)> s3_object.public_url
=> #<URI::HTTPS:0x007feed60cbaf8 URL:https://s3.amazonaws.com/bucket_name/files/document%2Bcopy.pdf>
[11] pry(main)> s3_object.public_url.path
=> "/bucket_name/files/document%2Bcopy.pdf"
```

**Comment by trevorrowe** [comment]
This is correct behavior. You are specifying the key of the object as "document+copy.pdf".  To create a public_url that is equivalent they key should be "document copy.pdf" (no plus sign).

```ruby
bucket = AWS::S3.new.buckets['bucket_name']
s3_object = bucket.objetcs['files/document copy.pdf']
s3_object.public_url
#=> #<URI::HTTPS:0x007fa0b88f2040 URL:https://s3.amazonaws.com/bucket_name/files/document%20copy.pdf>
```

Notice the `%20`, not `%2B`. The 2B is a URL encoded plus sign character, whereas 20 is a space character.
