### ISSUE TITLE
What has changed from 1.57.0 to 1.58.0?

### ISSUE THREAD

**Issue by igrep** [aws/aws-sdk-ruby#660]
I often have difficulty with see the change log of this gem when I try to update.
Especially this update disables us from seeing what's changed at a glance.
I guess there're no breaking changes, but I always want to know what changes before installing a newer version on my production system.
So, could you tell or update the change log?

**Comment by trevorrowe** [comment]
We've adopted a CHANGELOG for v2 of the SDK:
https://github.com/aws/aws-sdk-core-ruby/blob/master/CHANGELOG.md

Currently the v1 SDK is on feature lock and only receives API updates and bug fixes. You point is however valid. I will add a CHANGELOG for any maintenance releases from now on.

**Comment by igrep** [comment]
> Currently the v1 SDK is on feature lock and only receives API updates and bug fixes. You point is however valid. I will add a CHANGELOG for any maintenance releases from now on.

@trevorrowe I got it. Thank you! :+1:
