### ISSUE TITLE
IAM Access key missing user 

### ISSUE THREAD

**Issue by pwolanin** [aws/aws-sdk-ruby#677]
Example code:

```
    name = "peter.test11"
    group = iam.groups['ops']
    iamuser = iam.users.create(name)
    group.users.add(iamuser)
    puts iamuser.access_keys.user.name.inspect
    key = iamuser.access_keys.create
    puts iam.access_keys[key.id].user_name.inspect
    sleep 10
    iam2 = AWS::IAM.new({ :access_key_id => key.id, :secret_access_key => key.secret })
    puts iam2.access_keys[key.id].user_name.inspect
    puts iam2.client.get_user[:user][:user_name]
    puts iam2.users[name].access_keys[key.id]
```

outputs:
```
"peter.test11"
nil
nil
peter.test11
#<AWS::IAM::AccessKey:0x007f9f2ca00190>
```

expected:
```
"peter.test11"
peter.test11
peter.test11
peter.test11
#<AWS::IAM::AccessKey:0x007f9f2ca00190>
```
So the key is associated with the user (as expected, and also can be seen in the console), but depending on how the access key is instantiated it may be missing the user

So - this seems like a bug, or at least a bug in the documentation at:
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/IAM/AccessKey.html

The docs/code comments say the user will be present unless this is a root key

So the code should probably lazy-load the user if it's not present
https://github.com/aws/aws-sdk-ruby/blob/master/lib/aws/iam/access_key.rb

**Comment by trevorrowe** [comment]
This is a result of the IAM API. When indexing access keys from the root IAM object you get the access keys for the "current user", which is either the root account or the iam user the configured credentials are scoped to. This is behavior as defined by the API.

For this reason, the SDK can only know the user for access keys when constructed with a user.

The following produces what you expect.

```ruby
iam.users['username'].access_keys['akid'].user.name
#=> 'username'
```
