### ISSUE TITLE
Connection options passed to AWS::EC2 constructor are not set in HTTP ConnectionPool, but AWS.config() global options are.

### ISSUE THREAD

**Issue by askreet** [aws/aws-sdk-ruby#679]
Passing options like :http_open_timeout, :http_read_timeout and :max_retries into `AWS::EC2` does not have the expected effect:

```
2.1.5 :034 >   ec2 = AWS::EC2.new(:region => 'us-east-1', :ec2_endpoint => 'ec2.us-east-1.amazonaws.com:7777', :max_retries => 1, :http_open_timeout => 1, :http_read_timeout => 1)
 => <AWS::EC2>
2.1.5 :035 > ec2.client.describe_instances
Net::OpenTimeout: execution expired  **(<-- This takes ~30 seconds)**
2.1.5 :037 >   ec2.client.config.http_open_timeout
 => 1
2.1.5 :038 > ec2.client.config.http_read_timeout
 => 1
2.1.5 :039 > ec2.client.config.max_retries
 => 1
2.1.5 :040 > ec2.config.http_open_timeout
 => 1
```

However, using the following code does work:
```ruby
AWS.config(:max_retries => 1, :http_open_timeout => 1, :http_read_timeout => 1)
```

**Comment by trevorrowe** [comment]
I ran the following code in the REPL:

```ruby
AWS> ec2 = AWS::EC2.new(:region => 'us-east-1', :max_retries => 1, :http_open_timeout => 1, :http_read_timeout => 0.01); ec2.client.describe_instances
[AWS EC2 200 1.308121 1 retries] describe_instances() Net::ReadTimeout Net::ReadTimeout
Net::ReadTimeout: Net::ReadTimeout
from /Users/trevrowe/.rbenv/versions/2.0.0-p598/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
AWS> 
```

Notice that I modified the read timeout to a very short 0.01 seconds to force a failure. The call returned nearly instantly with the expect error. 

I notice that you are configuing the ec2 endpoint to ec2.us-east-1.amazonaws.com:7777. I wonder if this is causing an issue. There is a separate :ec2_port option that you can try. I'm wondering if this is causing a DNS lookup issue that is not related to the HTTP timeouts.

**Comment by trevorrowe** [comment]
Closing stale issue. Please re-open if you have additional information.
