### ISSUE TITLE
AWS::ELB::LoadBalancerCollection only provides access to 400 ELBs?

### ISSUE THREAD

**Issue by jrab89** [aws/aws-sdk-ruby#680]
According the console, the AWS account I'm working with has 451 ELBs.

However I'm not able to see all of them from Ruby:

```ruby
AWS.elb.load_balancers.count # => 400
AWS.elb.load_balancers.to_a.count # => 400
AWS.elb.load_balancers.each_batch { |batch| puts batch.count} # => 400
```
But I can access them all individually, but the newly created ones don't show up when I enumerate over all of them:

```ruby
AWS.elb.load_balancers['jeffs-elb-1'].exists? # => true
AWS.elb.load_balancers['jeffs-elb-2'].exists? # => true
AWS.elb.load_balancers.select { |elb| elb.name.include? 'jeffs-elb'} # => []
```

Any ideas what could be going on here? Thanks!

**Comment by trevorrowe** [comment]
I did some digging. It appears that the underlying API call for DescribeLoadBalancers requires pagination. I'll add a fix to cause the SDK to paginate.

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_DescribeLoadBalancers.html
