### ISSUE TITLE
S3 bucket policy is not being respected by aws-sdk-ruby

### ISSUE THREAD

**Issue by weyus** [aws/aws-sdk-ruby#682]
Ruby 1.8.7
aws-sdk-ruby 1.60.2

I created an IAM user and a S3 bucket. I applied the following bucket policy to the bucket:

    {
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::my_user_id:user/my_user_name"
			},
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::my_bucket",
				"arn:aws:s3:::my_bucket/*"
			]
		}
	]
    }

What I expect is that an authenticated request (e.g. with access_key_id and secret_access_key credentials provided as to the AWS.config method) will be allowed to write to this bucket. That works fine.

However, if I don't call AWS.config at all, I can still write into this bucket. 

It's behaving as though my bucket policy is opening the bucket up for the entire world, even though I am specifying a principal. 

I have verified that there are no credentials available to the client when AWS.config is not called.

I can replicate this behavior in another, completely separate and unrelated AWS account.

What can explain this behavior?

Wes

**Comment by weyus** [comment]
This issue was caused by my Rails.root/config/aws.yml file being present. Even thought I was not calling AWS.config, and even though the format of my aws.yml file was _different_ than database.yml, the keys and values were still being picked up. I've since removed my call to AWS.config altogether since it isn't necessary.

**Comment by trevorrowe** [comment]
The SDK, when loaded inside Rails will automatically load credentials from Rails.root/config/aws.yml. This behavior is being removed from the SDK as of v2.
