### ISSUE TITLE
Preferred OpenSSL ciphers

### ISSUE THREAD

**Issue by mikhailov** [aws/aws-sdk-ruby#683]
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS for Rails 3.2/Ruby 2.0 app shows the following settings:

```
{
  :ssl_version=>"SSLv23", 
  :verify_mode=>1, 
  :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA"
}
```

I believe that SSL 2/3 is not secure and TLSv1_2 should be used instead. RC4 is not recommended as well. 

What are the aws-sdk preferred settings for S3 endpoint communication? Can you recommend best performant ciphers? I also need to use SSL session caching to avoid extra CPU load. Is that possible to communicate efficient to AWS S3 service endpoint?

**Comment by trevorrowe** [comment]
The SDK does not attempt to override Ruby defaults as used by Net::HTTP. I do not know the Amazon S3 prefered settings. Might I suggest posting this question to the Amazon S3 forums here?:
https://forums.aws.amazon.com/forum.jspa?forumID=24

**Comment by mikhailov** [comment]
AWS S3 SSL settings are aweful, overall rating is C https://www.ssllabs.com/ssltest/analyze.html?d=s3-eu-west-1.amazonaws.com&s=54.231.132.8

**Comment by trevorrowe** [comment]
I'm going to close this issue for now. I don't believe there is any change the SDK should be making to the default SSL context for now.

**Comment by mikhailov** [comment]
Sorry, you are right, there is nothing SDK can make any change with server-side. Don't you know how long SSLv3 remain to be open on AWS S3 endpoints?

**Comment by trevorrowe** [comment]
I'm sorry, but I do not know.

**Comment by mikhailov** [comment]
AWS S3 settings are going to be changed as of 12:00 AM PDT April 30, 2015 https://forums.aws.amazon.com/thread.jspa?threadID=178739
