### ISSUE TITLE
S3::Object upload_file content_type option not recognized

### ISSUE THREAD

**Issue by cmather** [aws/aws-sdk-ruby#684]
The s3 object `upload_file` method fails when uploading a ~16MB file using multi-part upload when I set a `content_type: 'video/mp4'` option on the `upload_file` method. The error is:

```
Aws::S3::MultipartUploadError: multipart upload failed: unexpected value at params[:content_type]
```

Also see attached screenshot.

The upload works correctly, even with the `content_type` option, if I use the `put` method instead.

![screen shot 2015-01-12 at 8 54 50 pm](https://cloud.githubusercontent.com/assets/262179/5716218/ed1a422e-9a9d-11e4-84a1-8c4b984e69d8.png)

**Comment by trevorrowe** [comment]
Thanks for reporting the issue. I've applied a fix that should go out with this week's release.

**Comment by cmather** [comment]
Sweet!

**Comment by KranthiKishore** [comment]
Am getting `Aws::S3::Errors::InvalidArgument: Argument format not recognized` error when uploading file  if I give `grant_read` option. Can you tell me why is this?

`irb(main):084:0> object
=> #<Aws::S3::Object bucket_name="test_development", key="test_sample_file.csv">
irb(main):085:0> object.upload_file('/home/kranthi/projects/hubkit/example_output.csv', grant_read: 'test_sample_file.csv')
Aws::S3::Errors::InvalidArgument: Argument format not recognized`

**Comment by trevorrowe** [comment]
@KranthiKishore the `grant_read` option expects a value formatted to match the 'x-amz-grant-read' header. You can reference the Amazon S3 api docs for more information on the expected format. That said, it looks like what you really want is to make the object publicly readable. You can do this using the 'public-read' canned acl:

Try the following:

```ruby
object.upload_file('/home/kranthi/projects/hubkit/example_output.csv', acl: 'public-read')
```

**Comment by fatuhoku** [comment]
What's the syntax then?
```
    obj.put(file_name, zip, {}, "authenticated-read")   # save zip file to S3
