### ISSUE TITLE
Redshift::Client.describe_clusters only returns one tag

### ISSUE THREAD

**Issue by zepplen** [aws/aws-sdk-ruby#685]
I am using the aws-sdk-v1 1.60.2 gem, and making the describe_clusters call on the Redshift Client object. 

The result set I get back looks to be squashing multiple tags into a single tag result.

```yaml
:tags:
  :tag:
    :value: Testing Again
    :key: SecondName
```
This cluster also has a tag named Name, which is not being displayed in the result. My assumption is that this data structure should look more like:

```yaml
:tags:
  - :value: Testing
    :key: Name
  - :value: Testing Again
    :key: SecondName
```

**Comment by trevorrowe** [comment]
The AWS::Redshift::Client API was not updated, so what you are seeing is the default parsing behavior. I'm going to update the model shortly, and that should resolve this issue.
