### ISSUE TITLE
Record stubed responses.

### ISSUE THREAD

**Issue by eloyesp** [aws/aws-sdk-ruby#686]
Using `AWS.stub!` is great for testing, but I cannot find a way to check which interactions have been stubbed.

It would be awesome recording the interactions somewhere, to have something like:

~~~ruby
prepare do
  AWS.stub!
end

test 'archive a file in S3' do
  s3 = AWS::S3.new
  bucket = s3.buckets['samplebucket']
  obj = bucket.objects['sample_file.txt']
  obj.write "something"
  assert_equal AWS.stubbed_interactions.last, 
    'PUT https://samplebucket.s3.amazon.com/sample_file something'
end
~~~

Can something like that be implemented?

**Comment by trevorrowe** [comment]
Have you tried the following:

```ruby
assert_equal s3.client.stub_for(:put_object)
```

**Comment by trevorrowe** [comment]
Closing this issue for now. We are not currently doing feature work in the v1 SDK. We can consider this as a feature request for v2.
