### ISSUE TITLE
[Question] After creating and subscribing to a topic, can I confirm the subscription?

### ISSUE THREAD

**Issue by dandunckelman** [aws/aws-sdk-ruby#688]
I can't seem to find out where to get the "token" needed for the `#confirm_subscription` command.

Here's what I have:

    class Notification                                                          
      def initialize(config)                                                    
        @config = config                                                        
        @client = AWS::SNS::Client.new                                          
      end                                                                       
                                                                                
      def create_and_subscribe                                                  
        topic = create                                                          
        subscription = subscribe(topic)                                         
        binding.pry                                                             
        exit                                                                    
        confirm_subscription(subscription, topic)                               
      end                                                                       
                                                                                
      private                                                                   
                                                                                
      def create                                                                
        @client.create_topic({ :name => @config['topic']['topic_name'] })          
      end                                                                       
                                                                                
      def subscribe(topic)                                                      
        @client.subscribe({                                                     
          :topic_arn  => topic.data[:topic_arn],                                
          :protocol   => @config['subscription']['protocol'],                   
          :endpoint   => @config['subscription']['endpoint']                    
        })                                                                      
      end                                                                       
                                                                                
      def confirm_subscription(subscription, topic)                             
        @client.confirm_subscription({                                          
          :topic_arn                    => topic.data[:topic_arn],              
          :token                        => "", # TODO how do I get the token that's sent through the subscribe command?
          :authenticate_on_unsubscribe  => "false"                              
        })                                                                      
      end                                                                       
    end

I was assuming the response for `subscribe` would include that token.  What am I missing?

Thanks for the help.

**Comment by trevorrowe** [comment]
Sorry for the slow response. We've been very busy with the recent update to v2.  The token is sent to the endpoint. For email endpoints, a link is generated. Other endpoints have different formats.

**Comment by dandunckelman** [comment]
@trevorrowe not a problem.  I just moved a script over to v2 yesterday w/o much issue, so thanks for all the hard work on the new version.

So, my goal was to automatically confirm the subscription, but based on what you're telling me:  because the endpoint is an email, I can't programmatically confirm the subscription (outside of reading/parsing the email).  Is that correct?

**Comment by trevorrowe** [comment]
@dandunckelman That is my understanding.
