### ISSUE TITLE
MaxResults combined with a filter gives inconsistent results

### ISSUE THREAD

**Issue by wernerb** [aws/aws-sdk-ruby#689]
Using max_results with filters is allowed in some cases, and when allowed produces weird results. When using a filter that uses wildcards it returns a token for next results, even though no results were returned. When using no wildcards no next_token is returned.
When the tag value is exact (no wildcards) and produces results (I have an instance tagged with Name = o) it yields an error.

	2.1.5 :025 > Aws::EC2::Client.new.describe_instances(max_results: 5, :filters => [{:name=>"tag:Name", :values => ["Nonexisting value tag*"]}])
	 => #<struct
	 reservations=[],
	 next_token=
	  "eyJ2IjoiMSIsImMiOiI0d3p5bTMydDR2NC9VUERYY3dBb3lVd3RtSDlCZmhkaG0vZ1o1bHRyOGNPamI1UWY0T051THV5SERJcVFxak1WZFppYzc5Tk1kWFdBY3E2THkra1N5QUtSVCtNUDZ4aGh3b0ZwRmJHU29LdEdjams0d1pvaUhBdzE0MUF5ZXg5NnZBSGw5NHM5UHF6TGV6RWdwTUU3MUhURkVqL0VqQlNLUmpENlk4ZWxTTkE9IiwiaSI6IjVzNE1jUWhpRWdCNElBMmZobDRQS3c9PSIsInMiOiIxIn0=">

	2.1.5 :026 > Aws::EC2::Client.new.describe_instances(max_results: 5, :filters => [{:name=>"tag:Name", :values => ["Nonexisting value tag"]}])
	 => #<struct  reservations=[], next_token=nil>

	2.1.5 :027 > Aws::EC2::Client.new.describe_instances(max_results: 5, :filters => [{:name=>"tag:Name", :values => ["o"]}])
	Aws::EC2::Errors::InvalidParameterCombination: The parameter 'maxResults' cannot be used with tag filters in the parameter 'filterSet'. Remove either the tag filters from 'filterSet' or the 'maxResults' parameter and try again.

**Comment by trevorrowe** [comment]
Closing in favor of https://github.com/aws/aws-sdk-core-ruby/issues/196.
