### ISSUE TITLE
CloudFront 2014-11-06 API removed

### ISSUE THREAD

**Issue by dgoodlad** [aws/aws-sdk-ruby#692]
In 5ee6403ad8f2ad235ba4ec96c6b4b53d6aa5607e (released in [1.59.1](https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md#1591-2014-12-03)), the 2014-11-06 version of the CloudFront API was removed, and replaced with the older 2014-10-21 API. The commit description doesn't offer any insight as to why, other than that it was supposed to correct an "incorrect API version".

I couldn't find an issue specifically talking about this change; can anyone shed some light on why this version was removed?

cc @trevorrowe since you authored the commit :grinning:

**Comment by trevorrowe** [comment]
I need to follow up on this. At the time, it was at the request of the service team.

**Comment by trevorrowe** [comment]
I've added it back now and it should go out with the next release.
