### ISSUE TITLE
Support for requester pays enabled buckets

### ISSUE THREAD

**Issue by Irishsmurf** [aws/aws-sdk-ruby#694]
Hey,

Currently the S3Client doesn't have a switch to include the Request Payer header for downloads as defined here: 

http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html

**Comment by trevorrowe** [comment]
You are correct. We plan to expand the S3 client to support requester pays as a parameter, but until this happens, you can use a custom handler to add this functionality.

```ruby

class RequesterPays < Seahorse::Client::Plugin
  handler(step: :initialize) do |context|
    if context.params.delete(:requester_pays)
      context.http_request.headers['x-amz-request-payer'] = 'requester'
    end
    @handler.call(context)
  end
end

# do this once, and all s3 clients will now accept `:requester_pays` to all operations
Aws::S3::Client.add_plugin(RequesterPays)

s3 = Aws::S3::Client.new
s3.put_object(bucket:'name', key:'key', body:'data', requester_pays:true)
```

```

**Comment by sheldonh** [comment]
Perfect, thanks!

**Comment by trevorrowe** [comment]
The 88edf93 commit should add support to all of the appropriate object operations that support requester pays. This should go out with our next release.
