### ISSUE TITLE
Error in docs: Aws::PageableResponse

### ISSUE THREAD

**Issue by smeyfroi** [aws/aws-sdk-ruby#697]
Example text at http://docs.aws.amazon.com/sdkforruby/api/Aws/PageableResponse.html uses ```each``` to enumerate over pages, but the API doc says ```each_page```.

**Comment by trevorrowe** [comment]
It may not be very clear, but the API reference documentation lists `#each` as an alias for `#each_page`:
http://docs.aws.amazon.com/sdkforruby/api/Aws/PageableResponse.html#each_page-instance_method

I prefer `#each`, but `#each_page` exists for consistency with the other methods such as `#last_page?`, and `#next_page`. I'm going to go ahead and swap the methods so the documented method is `#each` and `#each_page` is the alias.
