### ISSUE TITLE
Some xxx.api.json files seem incomplete, missing error structure and httpStatusCode

### ISSUE THREAD

**Issue by lisabien** [aws/aws-sdk-ruby#698]
Noticed some inconsistencies in the aws-sdk-core/apis files.

For example, for CloudFormation:
https://github.com/aws/aws-sdk-core-ruby/blob/master/aws-sdk-core/apis/CloudFormation.api.json#L19-L59

For the `errors` array associated with an operation, each element contains both the shape and an `error` structure listing the `code` and `httpStatusCode`, among other things. This is very useful to us.

However, for example, here for OpsWorks (and other services), there is no `error` structure nor status codes listed:
https://github.com/aws/aws-sdk-core-ruby/blob/master/aws-sdk-core/apis/OpsWorks.api.json#L11-L29

They do not include the `error` structure nor anything about what `httpStatusCode` these shapes relate to.

We were wondering, is an oversight in the AWS metadata that some responses are missing the `error` structure and `httpStatusCode`? Or, are these intentionally missing?

We'd be happy to contribute a pull request, perhaps filling in some of the missing info, but wanted to check first. Thanks!

**Comment by trevorrowe** [comment]
Normally we do not accept pull requests or changes against the *.api.json models. These are extracted from other documents internally and changes would be clobbered unless the changes are made upstream. The other *.*.json documents, such as pagainators, waiters, and resources and hand-maintained and we gladly accept changes here.

To address the inconsistent error information. Each of the AWS SDKs use the error information present differently. For Java and .NET, these are used to create error classes for the documented error types. All other errors returned by the service are raised as a generic service error. The Ruby SDK does not use this information at runtime, but only to generate API reference documentation to show what errors might be raised.

I agree additional information here would be useful, but the Ruby SDK only vendors the API models, it does not "own" them.  I can definitely pass feedback along to the service teams that own the APIs.

**Comment by trevorrowe** [comment]
I'm going to mark this as closed. Please feel free to re-open if you have any additional questions. Feel free also to ask questions in our gitter channel: http://gitter.im/aws/aws-sdk-ruby
