### ISSUE TITLE
[Question] Is there intent to support generation of signed CloudFront URLs?

### ISSUE THREAD

**Issue by dandunckelman** [aws/aws-sdk-ruby#700]
Currently, we use this tool:  https://github.com/dylanvaughn/aws_cf_signer

But I was just curious if this operation is something the SDK would do at some point?

Thanks

**Comment by trevorrowe** [comment]
I haven't given it much consideration to this point. I would be generally in favor of supporting this feature, but I am unable to comment on timeline. I'd have to see where this fits into our priorities.

**Comment by dandunckelman** [comment]
@trevorrowe sounds good!
