### ISSUE TITLE
Suggestions for handling Aws::CloudFormation::Errors::Throttling inside resource collections.

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#705]
Specifically in the enumerators returned by Stack#events and Stack#resource_summaries 
I can obviously put delays in the iterator blocks to try and avoid throttling but this doesn't prevent issues caused by external consumption of the api rate limit.

**Comment by trevorrowe** [comment]
Good question. Self throttling can prevent a single process from browning out access to these APIs. Another thing to consider is checking if the new AWS Config service returns information about stack summaries or events. I'm not sure if this has been added, but it might be a good solution. Lastly, you could possibly reduce to a single process that polls for information periodically caching it locally.

I don't personally use the CloudFormation API much, so I may not be the best resource. I can also suggestion posting your question on the CF forum: https://forums.aws.amazon.com/forum.jspa?forumID=92

Something else to note, the AWS SDK for Ruby will automatically retry throttling errors up to 3 times before raising the throttling error. They do this with a default small exponential backoff. You can increase the number of retries and the backoff:

```ruby
cf = Aws::CloudFormation::Resource.new({
  retry_limit: 10,
  retry_backoff: Proc.new { |attemps| sleep(2 ** attempts) }
})
```

Hope this helps!

**Comment by lwoggardner** [comment]
Thanks.  I think the RetryErrors plugin will be my solution, but from a quick test it looks like the retry_limit needs to be set explicitly for the plugin to be used.   If this is supposed to be defaulted to 3 automatically then perhaps that is bug.  I'll do some more testing.

**Comment by trevorrowe** [comment]
The retry limit defaults to 3. Unless set otherwise, this should enable the default handler. 

```ruby
cf = Aws::CloudFormation::Client.new
cf.build_request(:list_stacks).handlers.map(&:name).grep /retry/i
#=> ["Aws::Plugins::RetryErrors::Handler"]
```

Are you experiencing something specifically that indicates the retry handler is not applied or working?

**Comment by lwoggardner** [comment]
Confirmed working as expected. My error setting the retry_limit in the config.
