### ISSUE TITLE
Aws::Lambda::Client does not find credentials in ENV

### ISSUE THREAD

**Issue by awendt** [aws/aws-sdk-ruby#707]
This works:

    lambda = Aws::Lambda::Client.new(
      region: 'eu-west-1',
      access_key_id: ENV['AWS_ACCESS_KEY'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    )
    lambda.invoke_async(
      function_name: 'foo',
      invoke_args: '{}',
    )

while this fails:

    lambda = Aws::Lambda::Client.new(
      region: 'eu-west-1',
    )
    lambda.invoke_async(
      function_name: 'foo',
      invoke_args: '{}',
    )

with the following message:

    E, [2015-02-15T23:01:16.804771 #39322] ERROR -- : unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)
    /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.24/lib/aws-sdk-core/plugins/request_signer.rb:91:in `require_credentials'

I've triple-checked the `ENV` in both cases: `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY` are both set.

**Comment by trevorrowe** [comment]
You've got the wrong ENV var for the id. Instead of `AWS_ACCESS_KEY`, try `AWS_ACCESS_KEY_ID`

```
lambda = Aws::Lambda::Client.new(
  region: 'eu-west-1',
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
)
```

**Comment by simonmorley** [comment]
:+1:
