### ISSUE TITLE
s3 presigned url regressions :content_length no longer supports a range

### ISSUE THREAD

**Issue by modosc** [aws/aws-sdk-ruby#719]
i just upgraded to v2 and found a few issues when generating a presigned url for an s3 object:

    - expected params[:content_length] to be an integer

previously you could pass a ruby range object into ```:content_length``` to set min/max sizes for a file: http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/PresignedPost.html#content_length-instance_method

**Comment by trevorrowe** [comment]
This sounds related to #720. The v2 client, `Aws::S3::Client`, does not have a content_length parameter for #put. Neither the v1 or v2 client have a pre-signed post implementation. Only v1 provides a pre-signed post class, and this does not exist in v2. Please provide some more context in the other issue.
