### ISSUE TITLE
s3 presigned url regressions - :success_action_status 

### ISSUE THREAD

**Issue by modosc** [aws/aws-sdk-ruby#720]
i just upgraded to v2 and found a few issues when generating a presigned url for an s3 object:

    - unexpected value at params[:success_action_status]

```:success_action_status``` doesn't seem to be supported anymore - this means that getting xml info back about the file after an upload won't work (see http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html)

**Comment by trevorrowe** [comment]
The v2 SDK does not provide a pre-signed POST utility at this time. Can you give a code example of what you are doing that generates this error?

**Comment by modosc** [comment]
previously we were doing something like this:

        @s3_presigned_post ||= S3_BUCKET.presigned_post
           key: s3_key,
           success_action_status: 201,
           acl: 'bucket-owner-full-control'.to_sym,
           expires: ::S3_PRESIGNED_POST_EXPIRATION,
           content_length: (0..::S3_MAX_FILE_SIZE),
           content_type: get_content_type

to adapt to v2 i changed the code like so:

        @s3_object ||= Aws::S3::Object.new bucket_name: S3_BUCKET, key: s3_key
        @s3_presigned_post ||= @s3_object.presigned_url :put,
           success_action_status: 201,
           acl: 'bucket-owner-full-control'.to_sym,
           expires: ::S3_PRESIGNED_POST_EXPIRATION,
           content_length: (0..::S3_MAX_FILE_SIZE),
           content_type: get_content_type

when i try this i get the errors from #719 and this bug. commenting out the ```:success_action_status``` and ```:content_length``` lines will make the code work.

**Comment by trevorrowe** [comment]
The `#presigned_post` method has no equivalent in the v2 SDK. I'm going to mark this as a feature request. Until this has been ported to the v2 SDK, you can continue using the v1 presigned post utility. You can use v1 and v2 in the same application.

**Comment by trevorrowe** [comment]
@modosc I've just submitted a pull-request to the main repository that adds pre-signed post support in v2. I would be interested in feedback: aws/aws-sdk-ruby#752
