### ISSUE TITLE
How can I mock/stub Aws::S3::Resource.new ?

### ISSUE THREAD

**Issue by Davidslv** [aws/aws-sdk-ruby#724]
Hi,

I'm having a hard time following your documentation, I wish there was proper examples, I've spent the last 5 hours trying to figure out how I could mock/stub `Aws::S3::Resource.new`

```ruby
r = Aws::S3::Resource.new(region: 'ap-southeast-1', stub_responses: true)
=> nil

r.bucket('my-bucket)
     NoMethodError:
       undefined method `bucket' for nil:NilClass
```

How can I basically mock it so I have an object that is not nil and has that bucket?

Thank you

**Comment by trevorrowe** [comment]
The first line should never return nil:

```ruby
r = Aws::S3::Resource.new(region: 'ap-southeast-1', stub_responses: true)
=> #<Aws::S3::Resource>
```

What do you have in your Gemfile and how are you loading the aws-sdk gem?

**Comment by trevorrowe** [comment]
Closing this as a non-issue with the SDK. I suspect there is an issue in your environment, perhaps some other gem or code is interfering with the SDK. The code you use above is verified by quite a few users.

**Comment by Davidslv** [comment]
Seems that I ended up doing something in the meantime and that example actually returns something else

```
r.bucket('131')
=> #<Aws::S3::Bucket name="131">
```

Although I followed a different path which ended up like this:

```
    s3_double        = double
    bucket_double    = double
    s3_object_double = double
    aws_url          = 'amazon.url'

    file = Tempfile.new 'file'

    s3_object_double.stub(:upload_file).with(kind_of(Tempfile), acl: 'public-read')
    s3_object_double.stub(:public_url).and_return(aws_url)

    bucket_double.stub(:object).with(kind_of(String)).and_return(s3_object_double)
    s3_double.stub(:bucket).with(BUCKET).and_return(bucket_double)
    Aws::S3::Resource.stub(:new).with(region: REGION).and_return(s3_double)
```

**Comment by trevorrowe** [comment]
The purpose of the AWS SDK for Ruby `:stub_responses => true` feature is to eliminate the need for you to stub each of these individual classes. The SDK will exercise the entire code-base up-to but not including the HTTP request. It then returns an empty response.
