### ISSUE TITLE
Anon authentication to AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by russau** [aws/aws-sdk-ruby#725]
I don't see a way to do the anon auth that is needed for AssumeRoleWithWebIdentity

There are similar issues here for boto:
https://github.com/boto/boto/issues/1556
https://github.com/boto/botocore/issues/206

I can do the post_form myself.  Anon auth would be a nice feature for the ruby sdk.

Thanks,
Russ

**Comment by russau** [comment]
My mistake, I has a typo in my role access policy.  AssumeRoleWithWebIdentity is working fine now.

Russ

**Comment by russau** [comment]
Okay, changing my mind again.  Once I fixed my policy I could see the SDK is now using my .aws/credentials file.  Is anon auth possible via the ruby sdk?

**Comment by trevorrowe** [comment]
The commit above will now send AssumeRoleWithWebIdentity calls without authentication.
