### ISSUE TITLE
get_object encoding

### ISSUE THREAD

**Issue by anazar** [aws/aws-sdk-ruby#728]
Is there a way to get the object with the original encoding?

I'm running into issues where the returned file can't be parsed because of encoding issues.

```s3.get_object({ bucket: AWS_S3_BUCKET, key: s3_key }, target: file_path)```

The resulting file at file_path is different from the original file.

**Comment by trevorrowe** [comment]
Can you provide more information about how the file was uploaded? I suspect that is where the encoding was modified. The snippet of code you listed above should download to a new file using binary mode, e.g.:

```ruby
File.open(file_path, 'wb') { |file| file.write(...) }
```

**Comment by anazar** [comment]
Looks like I was writing the file incorrectly. Sorry about posting in error.

**Comment by trevorrowe** [comment]
No problem!
