### ISSUE TITLE
Broken paging for SQS client?

### ISSUE THREAD

**Issue by Sjeanpierre** [aws/aws-sdk-ruby#733]
Hey Trevor and company, 
I really appreciate the work that you have put into this gem and look forward to using it more in the future.

I've been having a hard time with the SQS client in regards to paging and determining if there are items still in the queue. It looks like there is an issue with the [ PageableResponse](http://docs.aws.amazon.com/sdkforruby/api/Aws/PageableResponse.html). The `next_page?` and `last_page?` methods seem to be returning lies :disappointed: 

My test code is below, please tell me I am doing something wrong and failed to R[TFM](http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html)

```ruby
#!/usr/bin/env ruby
require 'aws-sdk' #aws-sdk-core 2.0.29

sqs = Aws::SQS::Client.new(:region => 'us-east-1')


queue_url = sqs.create_queue(:queue_name => "test_queue-#{srand.to_s[0..6]}").queue_url
puts "Queue URL: #{queue_url}"
puts 'Adding 20 items to queue'
20.times do |i|
  sqs.send_message(:queue_url => queue_url, :message_body => "Queue Item #{i}")
end

puts "\n"
puts 'Test case #1 - Retrieve messages one at a time and attempt to page through'
puts 'Attempting to retrieve messages'
received = sqs.receive_message(:queue_url => queue_url)

puts "Number of messages retrieved? #{received.messages.count}"
puts "Any more pages? #{received.next_page?}"
puts "Last Page? #{received.last_page?}"
puts "\n"
puts 'Test case #2 - get messages 5 at a time and process'
received = sqs.receive_message(:queue_url => queue_url,:max_number_of_messages => 5)
puts "Number of messages retrieved? #{received.messages.count}"
puts "Any more pages? #{received.next_page?}"
puts "Last Page? #{received.last_page?}"


puts "\n"
puts 'Deleting queue'
sqs.delete_queue(:queue_url => queue_url)
```

**Comment by trevorrowe** [comment]
Paging is only applied on operations that allow you to enumerate a list of resources without side-effects. Receiving messages from a queue has side-effects, removing messages from the queue. The only pageable operation in Aws::SQS::Client is `#list_queues`: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/SQS.paginators.json

Currently, every operation is decorated with the pageable response. In theory, this allows customers to code against list operations that aren't pageable yet. Service teams could add paging and customers would start reaping benefits straightway.

In practice, I'm not sure this is worth the confusion, especially in this scenario. Receive messages is not a candidate for paging support.

**Comment by Sjeanpierre** [comment]
In that case what is the best way to pull all items off of the queue using this client?

Sent from my iPhone

On Mar 7, 2015, at 12:08 PM, Trevor Rowe <notifications@github.com<mailto:notifications@github.com>> wrote:


Paging is only applied on operations that allow you to enumerate a list of resources without side-effects. Receiving messages from a queue has side-effects, removing messages from the queue. The only pageable operation in Aws::SQS::Client is #list_queues: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/SQS.paginators.json

Currently, every operation is decorated with the pageable response. In theory, this allows customers to code against list operations that aren't pageable yet. Service teams could add paging and customers would start reaping benefits straightway.

In practice, I'm not sure this is worth the confusion, especially in this scenario. Receive messages is not a candidate for paging support.

-

**Comment by trevorrowe** [comment]
You can call `#receive_messages` in a loop.  Eventually, the response will contain no results.

**Comment by trevorrowe** [comment]
I should also add, that I've been considering building a SQS queue polling abstraction, but I don't know when it would be completed.

**Comment by Sjeanpierre** [comment]
Thanks for the information Trevor. let me know if I can do anything to help with the polling abstraction.
