### ISSUE TITLE
last_modified while iterating through a bucket requires unnecessary round-trip

### ISSUE THREAD

**Issue by lexelby** [aws/aws-sdk-ruby#734]
I ran across this issue while using logstash's s3 input to read cloudwatch logs:  https://github.com/logstash-plugins/logstash-input-s3/issues/14#issuecomment-77650249

In short, when you iterate through a bucket (by prefix or not), s3 Objects are returned.  Calling `last_modified` on them does a round-trip to fetch the last modification date rather than using the one returned from the ListBucket call, which is almost certainly what the programmer wants.

**Comment by trevorrowe** [comment]
What version of `aws-sdk-resources` are you using? This was a limitation of older versions, but not in the current version. Enumerating objects in a bucket should yield `ObjectSummary` objects that are populated with all of the information returned in the list objects call.

**Comment by trevorrowe** [comment]
To give an example, the following is from the `aws.rb` REPL. Notice there is only a single API request made to `#list_objects`, and no follow-up HEAD object requests.

```ruby
Aws> s3 = Aws::S3::Resource.new
Aws> s3.bucket('aws-sdk').objects.limit(5).each { |obj| puts obj.last_modified }
[Aws::S3::Client 200 1.127641 0 retries] list_objects(bucket:"aws-sdk",encoding_type:"url")  
2015-01-20 22:04:03 UTC
2012-12-06 18:32:58 UTC
2012-12-06 18:32:58 UTC
2012-12-06 18:32:59 UTC
2012-12-06 18:32:59 UTC
```

Please feel free to re-open this issue if you feel there is still an error, but I suspect you just need to update.

**Comment by DanielRedOak** [comment]
What version was this issue addressed in?  The Logstash plugins are still on the v1 branch, latest release I believe they use is 1.61

**Comment by lexelby** [comment]
Ah, glad to hear this is fixed, thanks.

**Comment by trevorrowe** [comment]
@DanielRedOak The fix is part of the v2 SDK, not v1. Short of upgrading from v1 to v2, might I recomend using `AWS::S3::Client` from the v1 SDK instead of the mid-level abstraction. This will ensure the are not n+1 calls being made.

**Comment by DanielRedOak** [comment]
Thanks for clarifying, I just went ahead and re-wrote the Logstash plugin to use v2 of the SDK :smile:

**Comment by trevorrowe** [comment]
@DanielRedOak Good to hear. Would you mind sharing some of you experience upgrading from v1 to v2, publicly or privately?

**Comment by DanielRedOak** [comment]
Sure, did you want me to post here or somewhere else?

**Comment by trevorrowe** [comment]
Here would be fine.
