### ISSUE TITLE
Add EC2::Snapshot#wait_until_completed waiter

### ISSUE THREAD

**Issue by amw** [aws/aws-sdk-ruby#735]
It's currently possible to use `Aws::EC2::Client.new.wait_until(:snapshot_completed, snapshot_ids: [snapshot.id])`, I think it would be convenient to also be able to call `snapshot.wait_until_completed`.

**Comment by trevorrowe** [comment]
Thanks for the suggestion. This should be part of the next release.

**Comment by sandstrom** [comment]
Is this supposed to work?

```
irb(main):375:0> snapshot
=> #<struct Aws::EC2::Types::Snapshot data_encryption_key_id=nil, description="test snapshot, safe to del", encrypted=false, kms_key_id=nil, owner_id="773190852875", progress="", snapshot_id="snap-05a0bf6432567996a", start_time=2020-08-07 14:24:29 UTC, state="pending", state_message=nil, volume_id="vol-086363c9646c92e4a", volume_size=1, owner_alias=nil, tags=[]>

irb(main):376:0> snapshot.wait_until_completed
NoMethodError: undefined method `wait_until_completed' for #<Seahorse::Client::Response:0x000056256a69e8e0>
```

**Comment by alextwoods** [comment]
The [Snapshot#wait_until_completed](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Snapshot.html#wait_until_completed-instance_method) method is defined only for the Resource snapshot - it looks like you have the snapshot response from a Client call - its confusing and a weakness of the current way we do Resources (the object oriented model for interacting with services).

To use the [Resource](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Resource.html) snapshot you can do something like:
```ruby
resource = Aws::EC2::Resource.new(region: 'us-west-2')
snapshot = resource.create_snapshot(create_snapshot_opts) # this snapshot will now be an Aws::EC2::Snapshot object and NOT a Aws::EC2::Types::Snapshot
snapshot.wait_until_completed 

# Alternative
snapshot = Aws::EC2::Snapshot.new(id: snapshot_id)
snapshot.wait_until_completed
```

**Comment by sandstrom** [comment]
Alright, thanks for explaining! 

After reading up on it this is mentioned in the readme/docs, though I must admit it wasn't super-obvious.

Perhaps you can use some `method_missing` trickery to display a more useful warning message in case the attempted method does *not* exist on the client call response, but *does* exist on the equivalent resource. That should be fairly easy to implement across all resources and would go a long way in usability.

Anyway, thanks for helping out! ⭐

**Comment by alextwoods** [comment]
Yeah - using `method_missing` is a good idea.  I'll add that to our backlog - also happy to accept a PR for it!
