### ISSUE TITLE
Can I pre-sign url to upload file to bucket?

### ISSUE THREAD

**Issue by hakunin** [aws/aws-sdk-ruby#743]
Hi guys,
can I do a pre-signed direct file upload with the gem version 2?

From the info I dug up it almost seems like its not supported?

I am trying to do this and I get `SignatureDoesNotMatch`, but now it seems like the problem is that `put` copies the file, so I want `post`, which is... not supported?

How would I go about generating a pre-signed post url using this gem if I forked it?

    client = Aws::S3::Client.new(
      region: 'eu-central-1', 
      credentials: Aws::Credentials.new(ENV['S3_KEY'], ENV['S3_SECRET'])
    )
    presigner = Aws::S3::Presigner.new(client: client)

    params = {
      bucket: ENV['S3_BUCKET'],
      acl: 'public-read',
      key: 'autak.jpg',
    }
    
    @s3_direct_post = presigner.presigned_url(:put_object, params)

**Comment by trevorrowe** [comment]
The version 2 SDK currently supports pre-signed PUT but not pre-signed POST. If you want to do a direct upload using a browser, you need a presigned POST. This functionality does exist in version 1 of the SDK. You can use both v1 and v2 together in the same application making it pretty easy to continue using the old-presigned POST utility.

The presigned POST docs from v1 are here: http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/PresignedPost.html

Just add the `aws-sdk-v1` gem to your project and then `require 'aws-sdk-v1'`

**Comment by trevorrowe** [comment]
I should also add that porting the presigned post to v2 is on our backlog.

https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#amazon-s3-presigned-post
