### ISSUE TITLE
Config Endpoints & Ports & SSL 

### ISSUE THREAD

**Issue by reiz** [aws/aws-sdk-ruby#746]
How can I configure the S3 Endpoint & Port and `use_ssl`? In the 1.X branch I could do it like this: 

```
AWS.config(:s3_endpoint => 'localhost', :s3_port => 4567, :use_ssl => false ) 
``` 

Unfortunately this doesn't work anymore with the current version! But that's pretty important for my tests! 
Any input is highly appreciated!

**Comment by trevorrowe** [comment]
In the v2 SDK, there is a single `:endpoint` option for configuring all three.

```ruby
Aws[:s3] = { endpoint: 'http://localhost:4567' }
```

If you prefer to not use the global default config, you can pass the same option to the S3 client or resource constructors:

```ruby
s3 = Aws::S3::Client.new(endpoint: 'http://localhost:4567')
s3 = Aws::S3::Resource.new(endpoint: 'http://localhost:4567')
```

**Comment by reiz** [comment]
@trevorrowe Awesome! Thanks for the fast response!

**Comment by trevorrowe** [comment]
No problem!
