### ISSUE TITLE
Is this gem thread safe?

### ISSUE THREAD

**Issue by armanm** [aws/aws-sdk-ruby#748]
I can only find [this information by Loren Segal](https://ruby.awsblog.com/post/Tx16QY1CI5GVBFT/Threading-with-the-AWS-SDK-for-Ruby) about thread safety of this gem but his eager_loading method is no longer available on version 2 of this Gem.

I'm trying to upload files with multiple threads simultaneously using V2 and wanted to know if that's all good?

**Comment by trevorrowe** [comment]
Loren's blog post is relevant only to version of the `aws-sdk` gem. Version 2 is built on a different code base, and it does not support Ruby 1.8.7 where autoloading was a thread safety issue. 

The gem is thread safe and you should feel confident uploading file simultaneously using the v2 SDK. If you encounter any issues, we would treat it as a bug.
