### ISSUE TITLE
Problem setting the maintenance period when restoring a redshift cluster

### ISSUE THREAD

**Issue by CallumD** [aws/aws-sdk-ruby#750]
Please see the following example of trying to set the `preferred_maintenance_window` when calling restore_from_cluster_snapshot:
```ruby
[1] pry(#<TaskLogic::Redshift::ReadReplica>)> create_params
=> {:cluster_identifier=>"dev-1",
 :snapshot_identifier=>"snapshot-44444444-4444-4444-4444-444444444444",
 :availability_zone=>"us-east-1c",
 :preferred_maintenance_window=>"mon:07:00-mon:07:30"}
[2] pry(#<TaskLogic::Redshift::ReadReplica>)> AwsRedshiftHelper.get_client
=> #<AWS::Redshift::Client::V20121201>
[3] pry(#<TaskLogic::Redshift::ReadReplica>)> AwsRedshiftHelper.get_client.restore_from_cluster_snapshot(create_params)
ArgumentError: unexpected option preferred_maintenance_window
from aws-sdk-1.39.0/lib/aws/core/option_grammar.rb:588:in `block in validate'
```
However according to http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Redshift/Client/V20121201.html#restore_from_cluster_snapshot-instance_method preferred_maintenance_window is a legitimate option.

**Comment by trevorrowe** [comment]
I was able to run your example without error. It looks like from the stack trace that you are using v1.39.0 of the `aws-sdk`. The linked documentation is for v1.63.0. If you upgrade to the latest version within the major version 1, then this should work.

**Comment by CallumD** [comment]
Confirmed works with the latest version. Thanks!
