### ISSUE TITLE
Aws::EC2::Instance#public_dns_name is returning nil

### ISSUE THREAD

**Issue by sylvainkalache** [aws/aws-sdk-ruby#751]
The documentation mention "This name is not available until the instance enters the running state."

Even when the instance passed is running and passed system_status_ok, public_dns_name will return empty string.

**Comment by trevorrowe** [comment]
Are you seeing `Instance#state` return the running state name or are you seeing this state from some other source, such as the console? Also, are you reloading the `Instance` object? I'm just trying to get a picture of how this scenario plays out.

**Comment by trevorrowe** [comment]
I suspect this is simply an eventual consistency issue (which is common). Please update the issue with more information if you continue to run into unexpected issues.
