### ISSUE TITLE
Weirdness when setting default options for v2

### ISSUE THREAD

**Issue by itsmrwave** [aws/aws-sdk-ruby#753]
I think the documentation around setting default credentials can be improved, it very confusing at the moment as it only mentions how it is accessed but not how to set. For version 2 it should be as simple as ...

```ruby
Aws.config.update({
  access_key_id: "something",
  region: "region",
  secret_access_key: "something"
})
```

Since AWS.config is [no longer a method in v2, it is now a simple hash][1]. This should be explicitly stated in my opinion to ease the transition from the v1 mindset.

Another issue I'm having is that the docs say that credentials are loaded from `Aws.config[:credentials]`. Which I did set as an array of the access key and secret key. Only to get an `undefined method 'session_token'` error when making calls ...

It's only when I set the values as shown above did the errors go away ... but even so, the value of `Aws.config[:credentials]` is `nil` ... which is weird and unexpected behaviour. 

[1]: http://stackoverflow.com/a/28734593/2184155

**Comment by trevorrowe** [comment]
In the project README under [Credentials](https://github.com/aws/aws-sdk-ruby#credentials) it gives a list of the accepted credential object classes with links to their documentation.

I'll take a stab at clarifying the README and see about adding a more helpful error message for when credentials are not configured properly.

**Comment by itsmrwave** [comment]
@trevorrowe Thanks! And yeah I saw that ... it's probably correct. My problem was in some weird behaviour/errors (probably due to my misinterpretation the docs). Lemme provide some context ...

Please note that I'm using this in a Rails context and usually I prefer to use the initialiser files to configure gems ... which means that I create a file ... `config/initializers/aws.rb` ... and it contains this ...

```ruby
Aws.config[:credentials] = [ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY']]
```

So that didn't work ... and my call kept spewing session token errors so I figured that the gem isn't picking my credentials from the initialiser (at least when setting through the `:credentials` key) ... and so when I googled around I found [someone on SO][1] someone who provided an alternative way of setting the credentials ... which is like so ...

```ruby
Aws.config.update(
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
)
```

The README section you referenced mentions accessing from `Aws.config[:credentials]`. Which I guess is why I tried to set it that way the first time round.

So maybe a little clarification on specifically that part I guess. And a big part of the confusion is that I'm coming from a v1 mindset (where I used to assign defaults in an initialiser).

And just for clarity sake, it seems to me that all I had to do is set `AWS_ACCESS_KEY_ID ` and `AWS_SECRET_ACCESS_KEY` variables??? :-) ...

[1]: http://stackoverflow.com/a/28734593/2184155

**Comment by trevorrowe** [comment]
Thank you for your clarification. I'll push shortly an update that should help clarify configuration. Please check it out and let me know if you think it lacks something. There is a difficult balance between brevity/clarity and completeness. 

Yes, all you have to do is set those two environment variables, and then you don't have to configure credentials at all.

**Comment by itsmrwave** [comment]
Ah, @trevorrowe you've nailed it :8ball: It's perfectly clear now! :+1:

**Comment by trevorrowe** [comment]
Thank you for the feedback. Writing documentation isn't always an easy task when you are familiar with the tool. Its easy to forget what someone does and does not know.

**Comment by itsmrwave** [comment]
One last thing I'd like to comment on is the consistency of the environment variables that are in use ... for example on Elastic Beanstalk environment properties config panel ... there's an entry for `AWS_ACCESS_KEY_ID ` and `AWS_SECRET_KEY` that's there by default. One can't remove them and so I'd bet that most people using EB stick to these names for the key ID and secret key.

![screen shot 2015-03-30 at 8 49 50 pm](https://cloud.githubusercontent.com/assets/703786/6904011/663ab654-d71e-11e4-8365-81cb03cac746.png)

Then ... this gem's documentation mentions that it checks for `AWS_ACCESS_KEY_ID ` and `AWS_SECRET_ACCESS_KEY ` (the latter is different). If someone relied or assumed that there's a consistency to how these variables are named/used by AWS across the different libraries and services you can imagine that they'd be getting errors occasionally. And the difference is a bit subtle to notice.

In this repo [a quick search for][1] `AWS_ACCESS_KEY_ID ` shows that the gem does check for this throughout. That's good.

Then [search for][2] `AWS_SECRET_KEY` yields some results ... and [search for][3] `AWS_SECRET_ACCESS_KEY ` yields even more results ... yet they are meant to be the same thing. o_O

This is why I prefer to explicitly configure credentials than trust the gem :-)

_Ps: This doesn't impact the functionality of the gem, just more feedback._

[1]: https://github.com/aws/aws-sdk-ruby/search?utf8=✓&q=AWS_ACCESS_KEY_ID&type=Code
[2]: https://github.com/aws/aws-sdk-ruby/search?utf8=✓&q=AWS_SECRET_KEY&type=Code
[3]: https://github.com/aws/aws-sdk-ruby/search?utf8=✓&q=AWS_SECRET_ACCESS_KEY&type=Code

**Comment by trevorrowe** [comment]
@itsmrwave The SDK intentionally favors `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY`. These two ENV variables are what all of the AWS SDKs (Java, .NET, PHP, JavaScript, Ruby and CLI) have standardized around. If you use these, you will be golden. This is what is documented and preferred.

Those same names are using inside the shared credentials file at `~/.aws/credentials`, just without the prefix:

* `access_key_id`
* `secret_access_key`

As far as I know, those two are the only supported pairs for all of our SDKs again.

Any other possible combinations, of which there are many, are not guaranteed to work. A few are called out in the default credential provider chain.  These are:

* `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
* `AWS_ACCESS_KEY` and `AWS_SECRET_KEY`

These are there for compatibility with some of the legacy CLI tools, those pre-dating the newer unified CLI. Clearly there isn't support for ElasticBeanstalk's pair of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY`.  While we could add that pair, I suspect there are still others that we'd be missing.

It might be worth a minor refactor to have the credential provider chain search for the access key and secret key separably, instead of as a named pair, allowing more combinations. This would be an additive change and shouldn't affect any existing users negatively.

**Comment by itsmrwave** [comment]
@trevorrowe I think your explanation captures it all well. Thanks a lot for your time and attention.

**Comment by trevorrowe** [comment]
@itsmrwave I've made the change that will allow for alternative paris of the ENV variables: https://github.com/aws/aws-sdk-ruby/commit/d61484bd732fbba4bb16f0d124bb1e6df618e7fe

**Comment by itsmrwave** [comment]
@trevorrowe :+1: :+1: :+1:
