### ISSUE TITLE
aws::s3::encryption::materials docs and impl appear to be different

### ISSUE THREAD

**Issue by mhat** [aws/aws-sdk-ruby#754]
Documentation for `Aws::S3::Encryption::Materials` refers to a bunch of options: 
- `:encryption_key`
- `:materials_description`
- `:materials_location`
- `:instruction_file_suffix`

However the implementation of initialize acts on options `:key` and `:description`.

**Comment by trevorrowe** [comment]
Thanks for reporting the documentation issue. I've removed the documentation for the non-existing features and corrected the names for `:key` and `:description`.
