### ISSUE TITLE
v1 Kinesis PutRecords support

### ISSUE THREAD

**Issue by onyxraven** [aws/aws-sdk-ruby#760]
The service config `.yml` for Kinesis shows you support `Kinesis_20131202`, but there is no PutRecords call support

http://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

Could this be added to v1?  (it looks like it is in v2)

**Comment by trevorrowe** [comment]
I've updated the client class with PutRecords support and this has been released with v1.64.0.
