### ISSUE TITLE
Trailing slash on key is lost

### ISSUE THREAD

**Issue by emil-rb** [aws/aws-sdk-ruby#762]
#### Problem
When using a trailing slash in the key the slash gets lost.
```
s3client = Aws::S3::Client.new(...)
s3client.put_object(key: 'path/with/trailing/slash/', bucket: 'bucket', body: '')
```
#### Actual behavior
An empty object with key `path/with/trailing/slash` is created.
#### Expected behavior
Create an empty object with key `path/with/trailing/slash/` (note the trailing slash).

#### Use case
The use case for this is s3fs. It uses empty objects with trailing slashes to mark directories. Due to this issue objects created with this sdk are unusable from s3fs.

#### Debugging
I managed to track down the problematic piece of code.
`aws-sdk-core/lib/seahorse/client/plugins/endpoint.rb`, [line 61](https://github.com/aws/aws-sdk-ruby/blob/9a6426abd6183a16901942552324dd6244f30970/aws-sdk-core/lib/seahorse/client/plugins/endpoint.rb#L61):
```
param.split('/').map{ |value| escape(value) }.join('/')
```

This split-then-join loses the trailing slash.

**Comment by trevorrowe** [comment]
Thank you for the bug report and the pointer to the cause. I've put together a fix and added a test to cover the expected behavior. This should go out with the next release shortly.
