### ISSUE TITLE
v2.0.35 appears to have issues loading internal JSON files

### ISSUE THREAD

**Issue by jszwedko** [aws/aws-sdk-ruby#765]
Received this error:

`/home/admin/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.0.35/lib/seahorse/util.rb:28:in 'initialize': No such file or directory @ rb_sysopen - /home/admin/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.0.35/apis/ec2/2014-10-01/api-2.json (Errno::ENOENT)`

Reproduce:
```ruby
#!/usr/bin/env ruby
require 'aws-sdk'
ec2 = Aws::EC2::Client.new(region: 'us-east-1')
```

**Comment by jszwedko** [comment]
Fixed by 8d3c543e0f42c1864ae629784ee8c01d49d1ebf8

**Comment by trevorrowe** [comment]
Sorry for the inconvenience. There was a build issue with 2.0.35. It was fixed and patched shortly after release.

**Comment by jszwedko** [comment]
No worries!
