### ISSUE TITLE
About EC2::Client describe_<resource> method filters

### ISSUE THREAD

**Issue by egvalentejr** [aws/aws-sdk-ruby#767]
This is not so much of an issue as it is a question about the current API.  I am working closely with security groups, but while exploring the API I noticed that the list of filters varies (see  http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_security_groups-instance_method vs http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_snapshots-instance_method)
In particular I am interested in filtering security groups by the tag:Key=Value filter.  This does not seem to be available for security groups as it is for snapshots.  

Is this just a matter of time before the tag filter is added to the describe_security_groups method?

Thank you
p.s. If there is a more appropriate place for questions such as these please let me know.

**Comment by trevorrowe** [comment]
Looking at the API reference documentation for Amazon EC2, you appear to be correct. There is no Filter by tag:Key=Value.  

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSecurityGroups.html

This is a limitation of the API, but not the SDK. Might I suggest you open a question in the Amazon EC2 forum? https://forums.aws.amazon.com/forum.jspa?forumID=30
