### ISSUE TITLE
Aws::SQS::QueuePoller / Seahorse expects queue_url to be a string, not a struct?

### ISSUE THREAD

**Issue by pickhardt** [aws/aws-sdk-ruby#773]
I think there may be a bug in Aws SQS QueuePoller.

When I run the following, I get an error saying that queue_url is expected to be a string:

```
Aws.config.update({
    access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    region: ENV['AWS_REGION'] || 'us-east-1'
})
sqs_client = Aws::SQS::Client.new(logger: nil)
queue_url = sqs_client.get_queue_url(queue_name: ENV['AWS_QUEUE'])

count = 0
poller = Aws::SQS::QueuePoller.new(queue_url)
poller.poll(skip_delete: true) do |message|
  puts message.body
  poller.delete_message(message)

  count += 1

  if count > 10
    break
  end
end

# This gives the error:
# ArgumentError: expected params[:queue_url] to be a string
# from gems/ruby-2.1.2/gems/aws-sdk-core-2.0.37/lib/seahorse/client/param_validator.rb:24:in `validate!'
```

I investigated it and poller.queue_url is a struct #<struct 
 queue_url=
  "https://sqs.us-east-1.amazonaws.com...">
  
However, if you first do...

```
poller.instance_variable_set(:@queue_url, poller.queue_url.queue_url)
```

...before running poller.poll, then it works as expected.

Is this a bug?

**Comment by trevorrowe** [comment]
This is working as intended.  Calling `Aws::SQS::Client#get_queue_url` is documented to return a response object that has a `#queue_url` method. This pattern allows the SDK to support additional values when they are added by the service team. If the service team were to add the queue ARN to the response, the structure allows us to add an additional property in a backwards compatible manor.

You just need to adjust your code to do the following:

```ruby
sqs_client = Aws::SQS::Client.new(logger: nil)
resp = sqs_client.get_queue_url(queue_name: ENV['AWS_QUEUE'])
queue_url = resp.queue_url
```

**Comment by pickhardt** [comment]
Thanks.
