### ISSUE TITLE
Not work properly with capistrano

### ISSUE THREAD

**Issue by islue** [aws/aws-sdk-ruby#779]
```
$ ruby --version
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 25.40-b25 on 1.8.0_40-b27 +jit [darwin-x86_64]
$ bundle show capistrano
~/.rvm/gems/jruby-9.0.0.0.pre1/gems/capistrano-3.4.0
$ bundle show aws-sdk
~/.rvm/gems/jruby-9.0.0.0.pre1/gems/aws-sdk-2.0.38
```

```
$ cat failed.rb
# in Capfile
require 'capistrano/all'
require 'capistrano/setup'
# in other files
require 'aws-sdk'
Aws::EC2::Client.new
```
The sample code above will throw error:
Aws::Resources::Errors::DefinitionError: unable to define method Aws::EC2::DhcpOptions#delete, method already exists

Someone on the internet gives a workaround like this:
```
$ cat successful.rb
require 'aws-sdk'
Aws::EC2::Resource

require 'capistrano/all'
require 'capistrano/setup'
Aws::EC2::Client.new
```
I'm not sure if this is an issue of aws-sdk or cap.
Can you have a look at it?

**Comment by trevorrowe** [comment]
This is a known issue that has been resolved here: https://github.com/aws/aws-sdk-ruby/commit/c02b5e7646319034e91fb9d9eca6c80d900ae214. This fix should be released shortly.
