### ISSUE TITLE
paperclip plugin for v2

### ISSUE THREAD

**Issue by eniskonuk** [aws/aws-sdk-ruby#781]
There currently is no Paperclip plugin for v2 of the SDK.

**Comment by trevorrowe** [comment]
Thank you for the feature request. I've added it to the public backlog here: https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#paperclip-integration

**Comment by davetchen** [comment]
There is already a pull request for doing the v2 upgrade

https://github.com/thoughtbot/paperclip/issues/1764

Do you think it is on the right track? Thanks!
-dave
