### ISSUE TITLE
SSLv3 and S3

### ISSUE THREAD

**Issue by gammons** [aws/aws-sdk-ruby#783]
Hi there,

We recently got an email about AWS disabling SSLv3 at the end of this month, and they are encouraging clients to use TLS instead.   We specifically got an email about S3.   Does the aws-sdk gem already use TLS for connecting?

**Comment by trevorrowe** [comment]
The `aws-sdk` gem does not attempt to control the SSL version used by Net::HTTP. As far as I know, open ssl should negotiate TLS during the handshake.
