### ISSUE TITLE
Error in EC2 waiter `:volume_deleted`

### ISSUE THREAD

**Issue by ms-ati** [aws/aws-sdk-ruby#789]
When waiting for an EBS volume to be deleted, the SDK is raising an exception when the volume is finally deleted:

```
aws-sdk-core-2.0.33/lib/aws-sdk-core/waiters/waiter.rb:111:in `block in poll': stopped waiting due to an unexpected error: The volume 'vol-c9981bd3' does not exist. (Aws::Waiters::Errors::UnexpectedError)
```

Since this is the expected outcome, this error should not be raised. Obviously this is not hard to work around, but equally it should be easy to fix in the SDK.

**Comment by trevorrowe** [comment]
Thank you for reporting this issue. I'll try to take a look at this shortly.
