### ISSUE TITLE
Remove region requirement when creating Route53 client

### ISSUE THREAD

**Issue by mrlamroger** [aws/aws-sdk-ruby#791]
Correct me if I'm wrong. The R53 console doesn't require a region selection but the Aws::Route53::Client does. Is this necessary?

**Comment by trevorrowe** [comment]
The AWS SDK for Ruby requires a region for all services. This is necessary to prevent issues when services that have a single global endpoint regionalize. You can set the region once with `Aws.config` so that you don't need to pass a region to the client constructor.

```ruby
Aws.config[:rotue53] = { region: 'us-east-1' }
```

**Comment by mrlamroger** [comment]
Makes sense. Thanks!
