### ISSUE TITLE
Feature Request: ElasticLoadBalancing waiter for instance deregistration

### ISSUE THREAD

**Issue by machadolab** [aws/aws-sdk-ruby#793]
It would be nice if there was a waiter that waited for an instance to be OUT of a loadbalancer, so during a rolling deploy, for example, you could be sure that instance has finished serving all active requests before doing something drastic to the instance.

**Comment by trevorrowe** [comment]
Do you know what API operation to poll in this case to verify when an instance it out of a load balancer?

**Comment by machadolab** [comment]
According to http://docs.aws.amazon.com/cli/latest/reference/elb/describe-instance-health.html#output it would be OutOfService, which is what I usually see for a while, and then it stops showing up in the list. So maybe wait on both states.

**Comment by trevorrowe** [comment]
Added the waiter. This should go out with the next release. Thanks for your patience.
