### ISSUE TITLE
SignatureDoesNotMatch - Unable to upload file of zero bytes using version 2 AWS SDK for Ruby

### ISSUE THREAD

**Issue by vikas027** [aws/aws-sdk-ruby#795]
Hi,

I have found a small bug in Ruby SDK Version v2.0.41. When I try to upload file of zero bytes it generates below error. 

```bash
/usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)
```

I believe it's worth to look at it, or at least generate some meaningful error (above is too misleading).

Regards,
Vikas

**Comment by trevorrowe** [comment]
Can you please share an example of what you are doing that is triggering this error. I attempted to reproduce this with Amazon S3 and did not produce the failure:

```ruby
s3 = Aws::S3::Client.new(signature_verison: 'v4')
s3.put_object(bucket:'aws-sdk', key:'empty', body:'')
s3.put_object(bucket:'aws-sdk', key:'empty', body:nil)
```

**Comment by vikas027** [comment]
Sure. This is my short script (without my keys) and the error(s) as well on my CentOS 6.6 x86_64 machine.

<pre>vikas@reachvikas:~# cat s3_file_upload_V2.rb
#!/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby

require 'aws-sdk'
require 'aws-sdk-core'

bucket_name = 'vikas-bucket/vikas'
file_name = ARGV[0]

s3 = Aws::S3::Resource.new(
	credentials: Aws::Credentials.new('MY_ACCESS_KEY', 'MY_SECRET_KEY'),
	region:'us-west-1'
)

puts "Uploading #{file_name} of #{File.size(file_name)} byte(s) to #{bucket_name} ...\n"
obj = s3.bucket(bucket_name).object(file_name)
obj.upload_file(file_name)
vikas@reachvikas:~#</pre>

This works fine as the size of the file is greater than 0 bytes.
<pre>vikas@reachvikas:~# ls -l abc123/zz.txt
-rw-r--r-- 1 root root 1024 Apr 29 03:32 abc123/zz.txt
vikas@reachvikas:~# ./s3_file_upload_V2.rb abc123/zz.txt
Uploading abc123/zz.txt of 1024 byte(s) to vikas-bucket/vikas ...
vikas@reachvikas:~#</pre>

But, I try to upload a file size of zero bytes, I get below error(s).
<pre>vikas@reachvikas:~# > abc123/zz.txt
vikas@reachvikas:~# ls -l abc123/zz.txt
-rw-r--r-- 1 root root 0 Apr 29 03:33 abc123/zz.txt
vikas@reachvikas:~# ./s3_file_upload_V2.rb abc123/zz.txt
Uploading abc123/zz.txt of 0 byte(s) to vikas-bucket/vikas ...
/usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The request signature we calculated does not match the signature you provided. Check your key and signing method. (Aws::S3::Errors::SignatureDoesNotMatch)
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.0.41/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `block in put_object'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/services/s3/object.rb:102:in `upload_file'
	from ./s3_file_upload_V2.rb:16:in `<main>'
vikas@reachvikas:~#</pre>

**Comment by trevorrowe** [comment]
Hmm... thats curious. I ran the following in my terminal

```
$ touch empty
```

And then the following from ruby:

```ruby
S3::Object.new('aws-sdk', 'empty-file').upload_file('./empty')
```

And I received no error. Can you modify your application to rescue the error? I'd like to see the expanded error message and some of the request/response context:

```ruby
begin
  obj.upload_file(file_name)
rescue => e
  puts e.code
  puts e.message
  puts e.context.http_response.body_contents.inspect
  puts e.context.http_request.headers.inspect
  puts e.context.http_request.body_contents.inspect
end
```

**Comment by vikas027** [comment]
Hi Trevor,

I am sorry, I do not know how to use <b>rescue</b> in my shell script. Can you please help me to do so ?

Additionally, I have checked on a freshly installed CentOS 6.6 x86_64 machine with latest version of ruby (v 2.2.1) and AWS Ruby SDK (v 2.0.41), the issue still persists.

Regards,
Vikas

**Comment by trevorrowe** [comment]
Simply replace the following line your shell script with the snippet above:

```ruby
obj.upload_file(file_name)
```

**Comment by vikas027** [comment]
Here you are. Please note that I have replaced my access key with text 'MY_ACCESS_KEY'

```bash
vikas@reachvikas:~# touch abc123/empty
vikas@reachvikas:~# ./s3_file_upload_V2.rb abc123/empty
Uploading abc123/empty of 0 byte(s) to vikas-bucket/vikas ...
SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>MY_ACCESS_KEY</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256\n20150429T163001Z\n20150429/us-west-1/s3/aws4_request\n20f867df1a645adf595430ea5dcb4f04db0316d38e170460f6aab0d198f6ca2b</StringToSign><SignatureProvided>52d4087f909047eaee0f311f053b466f370748ab2a4c103afc4e1bc967767a82</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 31 35 30 34 32 39 54 31 36 33 30 30 31 5a 0a 32 30 31 35 30 34 32 39 2f 75 73 2d 77 65 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 32 30 66 38 36 37 64 66 31 61 36 34 35 61 64 66 35 39 35 34 33 30 65 61 35 64 63 62 34 66 30 34 64 62 30 33 31 36 64 33 38 65 31 37 30 34 36 30 66 36 61 61 62 30 64 31 39 38 66 36 63 61 32 62</StringToSignBytes><CanonicalRequest>PUT\n/vikas-bucket/vikas/abc123/empty\n\nhost:s3-us-west-1.amazonaws.com\nuser-agent:aws-sdk-ruby2/2.0.41 ruby/2.1.5 x86_64-linux resources\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20150429T163001Z\n\nhost;user-agent;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest><CanonicalRequestBytes>50 55 54 0a 2f 76 69 6b 61 73 2d 62 75 63 6b 65 74 2f 76 69 6b 61 73 2f 61 62 63 31 32 33 2f 65 6d 70 74 79 0a 0a 68 6f 73 74 3a 73 33 2d 75 73 2d 77 65 73 74 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 75 73 65 72 2d 61 67 65 6e 74 3a 61 77 73 2d 73 64 6b 2d 72 75 62 79 32 2f 32 2e 30 2e 34 31 20 72 75 62 79 2f 32 2e 31 2e 35 20 78 38 36 5f 36 34 2d 6c 69 6e 75 78 20 72 65 73 6f 75 72 63 65 73 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 31 35 30 34 32 39 54 31 36 33 30 30 31 5a 0a 0a 68 6f 73 74 3b 75 73 65 72 2d 61 67 65 6e 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35</CanonicalRequestBytes><RequestId>5D7E73297A927D2C</RequestId><HostId>xXgSzmXfPk22SeLfqSsF+JxNg3OCpcnF044vUUrDZdnp/9/uktV9H/S5iQj+C4QU0s3Tf0zlooo=</HostId></Error>"
{"user-agent"=>"aws-sdk-ruby2/2.0.41 ruby/2.1.5 x86_64-linux resources", "x-amz-date"=>"20150429T163001Z", "host"=>"s3-us-west-1.amazonaws.com", "x-amz-content-sha256"=>"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "authorization"=>"AWS4-HMAC-SHA256 Credential=MY_ACCESS_KEY/20150429/us-west-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=52d4087f909047eaee0f311f053b466f370748ab2a4c103afc4e1bc967767a82", "content-length"=>"0"}
""
vikas@reachvikas:~#
```

**Comment by trevorrowe** [comment]
So I think I know what the issue may be. The bucket name you are using in your example is given as `vikas-bucket/vikas`. I realized that this is not a valid bucket name outside the classic region and you are using `us-west-1` which requires bucket names to be DNS compatible. This prohibits the use of forward-slashes.

I suspect if you change your `bucket_name` variable to `vikas-bucket` and your object key can contain the `vikas` prefix and as many slashes as you need.

The signature error happens as the SDK has to put the non-dns compatible bucket name into the path instead of as a subdomain. Amazon S3 computes a different canonical request which causes the error. At this point, the only way the SDK could deal with this is if attempted to validate the `:bucket` param for clients outside `us-east-1`.

**Comment by vikas027** [comment]
Thanks Trevor, this works now. But, I am still not too sure why it only affects zero byte files. Anyways, I am glad that I have a workaround. <a href="https://gist.github.com/vikas027/be1010dd13f70ecd2f5e#file-s3_file_upload_ruby_sdk_v2-rb">Here</a> is my final script, may be useful for someone who bumps here. I am closing this issue.
Thanks again for your time on this.
