### ISSUE TITLE
S3 delete_objects silently fails with object names containing characters in the 0x00-0x1F range

### ISSUE THREAD

**Issue by eniskonuk** [aws/aws-sdk-ruby#797]
The aws-java-sdk has a similar issue outstanding. Here is a link to it. https://github.com/aws/aws-sdk-java/issues/333

The workaround is to iterate on the objects using delete_object.

Any way to get this fixed?

Thx
Enis

**Comment by trevorrowe** [comment]
Looking at the linked issue, it appears that this is a limitation of Amazon S3, and not the SDK. Is my understanding correct? Similar to how you can request that the keys be URI encoded in a list objects response, you would need to specify the keys are URI encoded in a delete objects batch request so that S3 knows to decode them server-side.

I can follow up with the Java team and see if they have raised this issue/question with Amazon S3.

**Comment by eniskonuk** [comment]
It does appear to be an S3 API issue but I'm not sure. I don't think it's an encoding issue as it works fine using the delete_object API call but not when you use delete_objects. The trouble is that it silently fails. Is there something that can be done in the SDK so there is an actual failure?

Thx
Enis

**Comment by trevorrowe** [comment]
The difference between `Aws::S3::Client#delete_object` and `#delete_objects` is that the key is sent in the request uri for the former and in the request body XML for the latter. The request uri is encoded allowing the special character to be correctly identified by Amazon S3. 

These particular characters are not valid in XML and seem to be omitted service side. The list object response has the same issue. To work around this, Amazon S3 provides a request parameter for list objects that indicates the keys should be URI encoded inside the XML. The Ruby SDK in-fact does this for EVERY list object request and then decode the keys before returning them to the user. This ensures the XML parser will not raise.

I'm using `Builder` from stdlib to build the XML. As far as I know, there are no valid xml entities for these special characters. The only known work-around at this time is to not send them in a delete objects request and use delete object instead. I spoke with the Java SDK engineers and they indicated this is still an outstanding issue. I can raise it with Amazon S3 and see what they suggest.

> The trouble is that it silently fails. Is there something that can be done in the SDK so there is an actual failure?

Have you checked the response to see if these keys are listed in the errors list? I suspect they are not, but it would be worth looking at. My guess is that Amazon S3 is ignoring these invalid XML characters and that results in a different key, potentially to an object that does not exist.

The only way I can think of to detect this client-side would be to generate a list of special characters to scan for and send them individually.  Thoughts?

**Comment by eniskonuk** [comment]
The response errors list is empty. It does look like S3 just ignores the request. The other issue is that if the list has multiple objects and only one has invalid XML characters, the whole list is ignored. Your workaround is what we've implemented right now but that potentially increases the number of API calls by the number of objects. If nothing can be done, then we can close this issue.

**Comment by trevorrowe** [comment]
I think the best case scenario is that Amazon S3 adds the ability for API users to indicate they have encoded the keys, similar to the list objects solution. As mentioned, I'll raise this with them.

**Comment by summera** [comment]
Is there a way around this issue with `delete_objects`? I think we're running into the same thing.
