### ISSUE TITLE
Bring back s3_object.exists?

### ISSUE THREAD

**Issue by itsmrwave** [aws/aws-sdk-ruby#798]
In version 1 we used to have `s3_object.exists?` method ... In understand we have `client.head_object` but still ... it would be nice if we just had something that returns true or false.

Then we can avoid stuff like this ...

```ruby
begin
  client.head_object(
    bucket: 'bucket_name',
    key: 'key'
  )
  return true
rescue
  return false
end
```

**Comment by trevorrowe** [comment]
This exists in v2 on `Aws::S3::Object`.

```ruby
s3 = Aws::S3::Resource.new
obj = s3.bucket('name').object('key')
obj.exists?
#=> true/false
```

**Comment by itsmrwave** [comment]
@trevorrowe I see! Forgot about Resource. Thanks. When I got into v2 I didn't quite understand the two methods of access ... I have dabbled with the other side more than I have with Resource. Thanks.

**Comment by itsmrwave** [comment]
Hey @trevorrowe, this isn't a bug or anything but just general feedback.

When I started using V2 [all][1], [the][2], [documentation][3] points to (or at least mentions explicitly) the `aws-sdk` gem (this). Naturally, one would go to the API documentation of the said gem for more information (and assume incorrectly that everything is there).

I do remember coming across mentions of using `Resources` (there is after all a simple example on the README) ... I kinda got lost (and gave up looking for it so decided to use the more complex alternative).

Now months later, after you replied to this issue it finally hits me that the documentation is probably in the API documentation of the other gem. Which I found here ...

http://www.rubydoc.info/gems/aws-sdk-resources/

[1]: http://aws.amazon.com/sdk-for-ruby/
[2]: https://github.com/aws/aws-sdk-core-ruby#aws-sdk-for-ruby---v2
[3]: http://docs.aws.amazon.com/sdkforruby/api/index.html

**Comment by itsmrwave** [comment]
Oh and my point was, I think it would be helpful for others if a link in the README was added to point to the API documentation of the resource interfaces. Explicitly. I started on a pull request but realised that you guys don't use rubydoc.info to host your documentation so my link would be the unofficial link.
