### ISSUE TITLE
Change default :next_token to nil when using stub_responses

### ISSUE THREAD

**Issue by jkanywhere** [aws/aws-sdk-ruby#804]
Please change the default value of `:next_token` to `nil` when using `stub_responses` to provide a better default experience by avoiding apparent duplication of responses when using the `Resource` interface.

When I stub a `describe_instances` response to contain 1 ec2 instance, for example, it is confusing to get back two from `Aws::Resource::EC2#instances`. 

Recommended by @trevorrowe 
See https://github.com/jkanywhere/aws-ruby-sample/commit/189dadf4290a57450afabd5a1e031449641c6ca7 and https://github.com/awslabs/aws-ruby-sample/pull/3 for context.

If you point me at the correct class or file that handles this feature I am happy to try my hand at resolving this.

**Comment by trevorrowe** [comment]
I've added this to my backlog and this will hopefully be part of the 2.1 release.
