### ISSUE TITLE
IAM and pageable responses

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#805]
Retrieving a list of all AWS managed policies available to the account. The AWS console lists 122 available policies. The following API call only gets back 100. There does not seem to be a next_page to iterate over. Is this the right way to page through?

```Ruby
      iam_client.list_policies.each do |response|
        response.policies.each do |d|
          print d.policy_name
        end
      end
```

thanks!

**Comment by trevorrowe** [comment]
Thanks for reporting this issue. The client pagination configuration was missing an entry for the ListPolicies API operation. The commit above adds this and should be released later this week.

**Comment by trevorrowe** [comment]
And yes, after the update, your code should correctly enumerate all policies.
