### ISSUE TITLE
Latest version of AWS SDK v1 (1.64) on rubygems.org does not match v1.64.0 tag

### ISSUE THREAD

**Issue by philipmw** [aws/aws-sdk-ruby#807]
rubygems.org advertises version 1.64.0 as the latest version of _aws-sdk-v1_ and major version 1 of _aws-sdk_.

However, the version published to rubygems.org is missing the top-level `aws-sdk.rb` file. This causes consumers of `aws-sdk ~> 1` to raise an exception on `require 'aws-sdk'`.

In contrast, [tag v1.64.0 on Github does have this file](https://github.com/aws/aws-sdk-ruby/tree/v1.64.0/lib).

Would you please update the gem published to rubygems.org to be current with tag v1.64.0 on Github?

**Comment by trevorrowe** [comment]
I was able to `gem install aws-sdk --version=1.64.0` and then from IRB require the library via `require 'aws-sdk'` and alternatively via `require 'aws-sdk-v1'`.  I then downloaded the gem file from RubyGems.org to see if the file is missing.  This is what I did:

```
$ mkdir tmp && cd tmp
$ wget https://rubygems.org/downloads/aws-sdk-v1-1.64.0.gem
$ tar xzvf aws-sdk-v1-1.64.0.gem 
$ tar xzvf data.tar.gz
$ ls lib/
aws		aws-sdk-v1.rb	aws.rb
```

As far as I can tell, the public gem artifact for v1.64.0 is not missing this file. Can you share what you are doing that causes this error?

**Comment by philipmw** [comment]
So in `lib`, there's `aws-sdk-v1.rb`, but no `aws-sdk.rb`, which would be necessary to `require 'aws-sdk'`.

In contrast, tag v1.64.0 does have `lib/aws-sdk.rb`.

**Comment by trevorrowe** [comment]
That is intentional. The `lib/aws-sdk.rb` is only available in v1.64.0 of the `aws-sdk` gem, not in the `aws-sdk-v1` gem.

This is what makes it possible to load v1 and v2 in the same process. If you replace your dependency on `aws-sdk < 2.0` with `aws-sdk-v1` your require statement needs to be `require 'aws-sdk-v1'`.

**Comment by trevorrowe** [comment]
See the relevant line in the gemspec:
https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/aws-sdk-v1.gemspec#L25

**Comment by philipmw** [comment]
ok, thanks for clarifying.
