### ISSUE TITLE
Aws::EC2::Resource

### ISSUE THREAD

**Issue by rustyautopsy** [aws/aws-sdk-ruby#809]
Can you please give me hand with the following...

resource = Aws::EC2::Resource.new(client: connection)
    instance = resource.create_instances(
        {
            image_id: image_id,
            key_name: "rubysdk-key",
            max_count: 1,
            min_count: 1,
            instance_type: "t2.micro",
            subnet_id: subnet_id,
            iam_instance_profile: {"name" => "test"},
......

What do I pass to iam_instance_profile?

Docs say it is a hash ":iam_instance_profile (Hash) — The IAM instance profile."

What values make up the hash?

Thanks in advance.

**Comment by trevorrowe** [comment]
There is a backlog item to improve these docs, but the option is documented in the client method linked to from the see also tags below: http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#run_instances-instance_method

You pass a hash with a single entry, either `:name` or `:arn`. This is the IAM instance profile name or profile arn.

**Comment by rustyautopsy** [comment]
Awesome! Thanks.
