### ISSUE TITLE
Aws::CloudFormation::Client throws ArgumentError when returning response

### ISSUE THREAD

**Issue by rdark** [aws/aws-sdk-ruby#810]
The below code throws an ArgumentError when getting a response - though the
actual (cloud) stack creation works successfully and resources are created as
expected. I started to trace through the stack trace to try and pinpoint where
this was originating from but the stack is pretty deep and I'm not that
familiar with the code..

Really simple example:

    module ExampleBootStrap
      class AWSCloudFormation
    
        attr_reader :profile, :credentials, :region, :client
    
        def initialize(profile=ENV['AWS_PROFILE'],region=ENV['AWS_REGION'])
          @profile = profile
          @region  = region
          @credentials = Aws::SharedCredentials.new(:profile_name => profile)
          @client = Aws::CloudFormation::Client.new(
            :region      => @region,
            :credentials => @credentials
          )
        end
    
        def create_stack(stack_name,template_body,client=@client)
          client.create_stack(
            :stack_name    => stack_name,
            :template_body => template_body
          )
        end
    
      end
    end

Called with, for e.g:

    stack_name = "stack-name"
    stack_json = "{ "foo" : "bar" }" # valid cloudformation template/json string
    cloudform = ExampleBootStrap::AWSCloudFormation.new()
    response = cloudform.create_stack(stack_name,stack_json)

Stack Trace:

    /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser/stack.rb:20:in `attr': wrong number of arguments (1 for 2) (ArgumentError)
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser/engines/rexml.rb:29:in `block in tag_start'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser/engines/rexml.rb:28:in `each'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser/engines/rexml.rb:28:in `tag_start'
        from /home/rdark/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rexml/parsers/streamparser.rb:24:in `parse'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser/engines/rexml.rb:19:in `parse'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/xml/parser.rb:28:in `parse'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/query/handler.rb:36:in `parse_xml'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/query/handler.rb:13:in `block in call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/response.rb:43:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/response.rb:43:in `block in on'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:137:in `block in on_success'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:164:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:164:in `block in listener'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:128:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:128:in `on_done'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/http/response.rb:135:in `on_success'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/response.rb:42:in `on'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/response.rb:51:in `on_success'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/query/handler.rb:11:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/endpoint.rb:31:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/response_target.rb:18:in `call'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/request.rb:70:in `send_request'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/vendor/bundle/ruby/2.0.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
        from /home/rdark/.gitrepos/ops_example/example-bootstrap/tmp/lib/coreosbootstrap/aws_cloudformation.rb:20:in `create_stack'
        from ./bin/cloudify.rb:47:in `block in <main>'
        from ./bin/cloudify.rb:45:in `each'
        from ./bin/cloudify.rb:45:in `<main>'

**Comment by trevorrowe** [comment]
I was looking into this and unable to reproduce this error. Can you do me a favor an enable HTTP wire logging so I can see the XML response that is not being parsed properly?

```ruby
@client = Aws::CloudFormation::Client.new(
  :region      => @region,
  :credentials => @credentials,
  :http_wire_trace => true
)
```

**Comment by rdark** [comment]
opening connection to cloudformation.eu-west-1.amazonaws.com:443...
    opened
    starting SSL for cloudformation.eu-west-1.amazonaws.com:443...
    SSL established
    <- "POST / HTTP/1.1\r\nAccept: */*\r\nAccept-Encoding: \r\nAuthorization: AWS4-HMAC-SHA256 Credential=ACCESS_KEY_REDACTED/20150515/eu-west-1/cloudformation/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=437eda00c6b5b55e4cbeeb39c5f4205d3023ca63425f94b14cb162ca4e86b07a\r\nContent-Length: 29642\r\nContent-Type: application/x-www-form-urlencoded; charset=utf-8\r\nHost: cloudformation.eu-west-1.amazonaws.com\r\nUser-Agent: aws-sdk-ruby2/2.0.42 ruby/2.0.0 x86_64-linux\r\nX-Amz-Content-Sha256: a9722ebd2afe1b7036a120c38c5d2d1f4552d0b45b9e6ff5805701b5fac7f29b\r\nX-Amz-Date: 20150515T083825Z\r\n\r\n"
    -> "HTTP/1.1 200 OK\r\n"
    -> "x-amzn-RequestId: c08d757f-fadd-11e4-aba0-bd7dba9b773b\r\n"
    -> "Content-Type: text/xml\r\n"
    -> "Content-Length: 388\r\n"
    -> "Date: Fri, 15 May 2015 08:38:25 GMT\r\n"
    -> "\r\n"
    reading 388 bytes...
    -> "<CreateStackResponse xmlns=\"http://cloudformation.amazonaws.com/doc/2010-05-15/\">\n  <CreateStackResult>\n    <StackId>arn:aws:cloudformation:eu-west-1:ACCOUNT_NUMBER_REDACTED:stack/cont-cros-uact-001/c0a235d0-fadd-11e4-8882-5088487db896</StackId>\n  </CreateStackResult>\n  <ResponseMetadata>\n    <RequestId>c08d757f-fadd-11e4-aba0-bd7dba9b773b</RequestId>\n  </ResponseMetadata>\n</CreateStackResponse>\n"
    read 388 bytes
    Conn keep-alive

**Comment by trevorrowe** [comment]
I've attempt to recreate this failure locally and I've had no luck. Do you have an environment where this error is reproducible? If so, would be willing to sync up with me over Google hangouts to debug this together?

**Comment by rdark** [comment]
Hi Trevor,

Thanks for the offer! To save you the effort I'll play around with a few things and maybe knock up a Vagrantfile at some point this weekend to try get a reproducible environment for you.

Cheers,
Richard

**Comment by rdark** [comment]
So this one was pretty fun to track down - turns out that it was a namespacing issue.

My project had a Util module also, and there were three calls to Seahorse::Util methods that were not qualified. The above commit fixes this issue - will open a PR if the above commit is OK by you?

**Comment by rdark** [comment]
Issue turned out to be in a gem that I was using for cloudformation template generation (lono) that was extending/overriding core methods of the Hash object.. 

Thanks for your help and sorry for the red herring..

**Comment by trevorrowe** [comment]
That is curious that it would match up to your Util module. My understanding is that it should have found Util inside Seahorse::Util first. If this were not the case, I would need to use fully-qualified namespaces everywhere to avoid possible name conflicts.

I'll take a stab a reproducing this. Thank you for the update.

**Comment by rdark** [comment]
Hi Trevor - not sure if you saw my last message, but the issue turned out not to be in aws-sdk, but in another gem that I was using in my project that was polluting core Hash methods.

**Comment by trevorrowe** [comment]
@rdark See that now. I'm glad you were able to resolve it!

**Comment by tongueroo** [comment]
@rdark I ran into the same error and did not know it was coming from lono.  Sorry about that! I've removed the extension as it no longer needed since ruby sorts the output of a the generated json now.
