### ISSUE TITLE
ECS port_mappings host_port should be optional

### ISSUE THREAD

**Issue by andykent** [aws/aws-sdk-ruby#812]
I think this is a bug in the Ruby libs.

The docs for `register_task_definition` state

> The port number on the container instance to reserve for your container. You can specify a non-reserved host port for your container port mapping, or you can omit the hostPort while specifying a containerPort and your container will automatically receive a port in the 49153 to 65535 port range.

Trying the method with a `container_port` set to `8080` but without `host_port` set (or set to `0` or `nil`) returns the following error...

    Aws::ECS::Errors::InvalidParameterException: A host port mapping for the container port 8080 is required.

My understanding is that you need to be able to specify a container_port with a dynamic host_port for ELB support to work correctly so this is currently a blocker to making that work for me.

**Comment by andykent** [comment]
Hmm, I think this might have been premature. it seems like it's actually maybe needed for ELB support? 

So maybe it's functionally correct but the docs are just quite unclear here?

**Comment by trevorrowe** [comment]
The SDK documentation is pulled directly from the ECS API reference documentation. Might I recomend you leave feedback with the ECS documentation? There are "Did this page help you links" on all of the API reference documentation. Any changes made there will trickle down to the Ruby SDK reference docs.
