### ISSUE TITLE
Improve the documentation on filters under EC2 Resource

### ISSUE THREAD

**Issue by chenkirk** [aws/aws-sdk-ruby#813]
I was having a lot of trouble figuring out the filter format for EC2 Resource snapshots method reading the documentation here.

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html#snapshots-instance_method

Eventually I found a similar issue on here https://github.com/aws/aws-sdk-ruby/issues/732

From the issue I found filters were well documented for EC2 Client. For example, the same method (called `describe_snapshots` for the client version) had great formatted examples:

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#describe_snapshots-instance_method

It would be tremendous help to have the Resource documentation share the same clear explanation provided by the Client documentation.

**Comment by trevorrowe** [comment]
That is an excellent suggestion. I'm currently working on a major update to the reference documentation. I'll see what I can do about created syntax/formatting examples for the resource interfaces as well.
