### ISSUE TITLE
EC2 import_instance is not able to import VMware instance into EC2

### ISSUE THREAD

**Issue by sauravhaloi** [aws/aws-sdk-ruby#814]
I am trying to use ec2#import_instance method to import my VMDK as an EC2 instance in AWS, but seems like the method is not working properly. It successfully accepts the conversion task, returns a conversion task id, but the task remains in active/pending state forever without reporting any errors or exceptions. The steps followed are as below:

1. Upload the VMDK into a s3 bucket
2. Create a signed-url for the VMDK uploaded in step-1 for GET method
3. The actual import_instance logic is as below:
<snippet>
    begin
        resp = @ec2.import_instance({
          description: 'VMwareAWS',
          launch_specification: {
              architecture: "x86-64",
              instance_type: "t2.small",
          },
          disk_images: [
              {
                  image: {
                      # required
                      format: 'VMDK',
                      # required
                      bytes: 446726656,
                      # required
                      import_manifest_url: "signed_url_here",
                  },
                  description: "disk-image",
                  volume: {
                      # required, the size of the volume in GB
                      size: 16,
                  },
              },
          ],
          # required
          platform: "Linux",
        })
        resp = resp.next_page until resp.last_page?
        conv_task_id = resp.conversion_task.conversion_task_id
        puts "Now waiting for conversion task #{conv_task_id} to finish..."
        
        begin
            @ec2.wait_until(:conversion_task_completed, conversion_task_ids: ["#{conv_task_id}"]) do |w|
                one_hour_later = Time.now + 3600
                w.before_wait do |n, response|
                    throw :failure, 'waited too long' if Time.now > one_hour_later
                end
            end
        rescue Aws::Waiters::Errors::WaiterFailed => error
            puts "Waiter for conversion task id #{conv_task_id}: #{error.message}"
        end

    rescue => e
        puts e.backtrace
        raise e
    end
</snippet>

4. After step 3, I get a conversion_task_id which runs forever and never completes. The 'BytesConverted' is always zero, status is always active and status message is pending. The JSON for the conversion task is shown below:

{
    "ConversionTasks": [
        {
            "ConversionTaskId": "<TASK_ID>",
            "ImportInstance": {
                "InstanceId": "<INSTANCE-ID>",
                "Description": "VMwareAWS",
                "Volumes": [
                    {
                        "Status": "active",
                        "AvailabilityZone": "us-west-2c",
                        "Description": "disk-image",
                        "Image": {
                            "Size": 446726656,
                            "ImportManifestUrl": "<SIGNED-URL>",
                            "Format": "VMDK"
                        },
                        "Volume": {
                            "Size": 16
                        },
                        "BytesConverted": 0,
                        "StatusMessage": "Pending : Downloaded 0"
                    }
                ]
            },
            "ExpirationTime": "2015-05-21T06:05:46Z",
            "State": "active",
            "StatusMessage": "Pending"
        }
    ]
}

If I do a manual import_instance through the ec2 command lines, the import instance is successful.

**Comment by sauravhaloi** [comment]
Some of the fields such as URL, instance id etc has been removed from the snippet for privacy reasons

**Comment by trevorrowe** [comment]
Have you raised this issue with support or on the Amazon EC2 forums? This does not appear to be an AWS SDK for Ruby issue.

EC2 forums:
https://forums.aws.amazon.com/forum.jspa?forumID=30
