### ISSUE TITLE
Error installing aws-sdk: invalid gem: package is corrupt

### ISSUE THREAD

**Issue by grantspilsbury** [aws/aws-sdk-ruby#817]
When I run the command on my rails app
gem install aws-sdk

I get the following error:
ERROR:  Error installing aws-sdk:
invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/grantspilsbury/.rvm/gems/ruby-2.2.1/cache/aws-sdk-core-2.0.43.gem
I am trying to use Amazon's S3 storage service.

My gemfile includes

ruby "2.2.1"
gem 'rails', '4.2.1'

**Comment by trevorrowe** [comment]
I just ran the following command locally:

```bash
$ gem install aws-sdk --version=2.0.43
Fetching: aws-sdk-core-2.0.43.gem (100%)
Successfully installed aws-sdk-core-2.0.43
Fetching: aws-sdk-resources-2.0.43.gem (100%)
Successfully installed aws-sdk-resources-2.0.43
Fetching: aws-sdk-2.0.43.gem (100%)
Successfully installed aws-sdk-2.0.43
3 gems installed
```

It sounds like there was an issue while downloading the gem. Have you tried removing all of the files and then run gem install again?

**Comment by trevorrowe** [comment]
I've received no other reports of a corrupt gem. I'm going to close this issue. Please feel free to re-open if you have additional information or if you can reproduce this.
