### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer

### ISSUE THREAD

**Issue by pamio** [aws/aws-sdk-ruby#819]
I'm trying to upload a file of 9MB to s3 and it throws this error. I;m doing this through a rake task. 
Here is the trace

`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/http/connection_pool.rb:330:in `request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/http/net_http_handler.rb:61:in `block in handle'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/http/connection_pool.rb:129:in `session_for'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/http/net_http_handler.rb:55:in `handle'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:244:in block in `make_sync_request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:280:in `retry_server_errors'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:240:in `make_sync_request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:502:in block (2 levels) `in client_request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:382:in `log_client_request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:468:in block in `client_request'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:364:in return_or_raise'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/core/client.rb:467:in client_request'
`(eval):3:in `put_object'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/s3/s3_object.rb:1715:in `write_with_put_object'
`/home/pamio/.rvm/gems/ruby-2.1.1/gems/aws-sdk-1.27.0/lib/aws/s3/s3_object.rb:607:in write'
`/home/pamio/dev/rails_apps/local/valutme-storefront/lib/tasks/backup.rake:22:in block (2 levels) in` `<top (required)>
`/home/pamio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in eval'
`/home/pamio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in <main>'

As suggested here http://www.cyberciti.biz/faq/linux-tcp-tuning/ I did change the config file trying to understand if its ubuntu issue but I dont think this solves as the file size is just 9MB. 

Thanks

**Comment by trevorrowe** [comment]
Can you share a code example that reproduces the error? Also, can you share how you have configured your S3 client?

**Comment by pamio** [comment]
@trevorrowe, I solved the issue by creating a bucket manually on s3 and then it worked. Thanks for the reply.

**Comment by trevorrowe** [comment]
@pamio So the bucket did not exist and creating it allowed the upload file to work? If that is the cause, I'm suprised you didn't just get a 404 BucketNotFound error.

**Comment by pamio** [comment]
@trevorrowe, thats exactly what happened. Here's what happened. 
I was creating the bucket from my script. 

    s3 = AWS::S3.new
    if !s3.buckets['gs-db-backups'].exists?
       bucket = s3.buckets.create('backups')
     end
     file_name = "dump-#{DateTime.now.strftime('%Y-%m-%d-%H-%M')}.zip"
     files = Dir["dump/**/*"].map { |file| file }
     `zip #{file_name} #{files.join(" ")}`
      file = File.open(file_name, "rb")
      obj = bucket.objects[file_name.split(".").first]
      obj.write(file: file)

Now, the above script always threw the above said error until I created a bucket manually on s3 by logging into s3 console. After I did that It was successfully uploading the file on s3.

**Comment by trevorrowe** [comment]
It looks like you are checking for the existance of one bucket, and creating a different one when it does not exist:

```ruby
if !s3.buckets['gs-db-backups'].exists?
   bucket = s3.buckets.create('backups')
end
```

You reference `gs-db-backups` and `backups`. Is that intentional?

**Comment by pamio** [comment]
Sorry - my bad. I had corrected that already!  And posted my reply. BTW the issue is resolved now. After I corrected the name of the bucket, I was still getting the error. As I said, creating a bucket manually solved my problem.
