### ISSUE TITLE
Client#put_object does not support grant_write

### ISSUE THREAD

**Issue by nate** [aws/aws-sdk-ruby#827]
In [Client#put_object](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#put_object-instance_method) the options `grant_full_control`, `grant_read`, `grant_read_acp`, and `grant_write_acp` are available, but not `grant_write`. This despite [the api](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) supporting it via the `x-amz-grant-write` header.

I can't figure out where this is defined so I can fix it an make a pull request.

**Comment by nate** [comment]
Actually, [I think I found it](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/s3/2006-03-01/api-2.json#L3488-L3507). The [contribution guidelines](https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md#what-you-should-keep-in-mind) say I should submit an issue for this. Should I put together a pull request, too?

**Comment by nate** [comment]
I think it's missing a few other places in that file as well.

**Comment by trevorrowe** [comment]
Looking at the S3 API documentation, I don't believe grant write is supported for PUT object:

> x-amz-grant-write Not applicable. This applies only when granting permission on a bucket.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

There is though x-amz-grant-write-acp, settable via `:grant_write_acp`.

**Comment by trevorrowe** [comment]
As discussed on gitter, this is an API limitation.
