### ISSUE TITLE
Inline comments break SharedCredentials parsing

### ISSUE THREAD

**Issue by miketheman** [aws/aws-sdk-ruby#837]
Took me an hour to figure this out.

Repro:
Use this ini mock:
```ini
[default] # this is my default
aws_access_key_id = ACCESS_KEY_0 
aws_secret_access_key = SECRET_KEY_0
aws_session_token = TOKEN_0
```

The resulting credentials will no longer have a `default`.

`awscli` handles this correctly, the [ini_parse](https://github.com/aws/aws-sdk-ruby/blob/3406c0fb9309f11b2405c2cc722b7cbca90bbc2e/aws-sdk-core/lib/aws-sdk-core/shared_credentials.rb#L85-L102) method currently does not.

**Comment by trevorrowe** [comment]
Thank you for reporting this issue. I'll take a look at this shortly.

**Comment by trevorrowe** [comment]
Thank you for reporting this. The fix will go out with the next release.

**Comment by miketheman** [comment]
:+1: Thanks!
