### ISSUE TITLE
Should returned DynamoDB SS, NS, and BS types be Sets or Arrays?

### ISSUE THREAD

**Issue by mrlamroger** [aws/aws-sdk-ruby#838]
I ran into an issue converting a response into JSON because a StringSet returned a Set object and the Set class doesn't have a to_json method.

http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html Describes NS, SS and BS as arrays in the contents section but also says "The multi-valued attribute is a set" in the paragraph above.

**Comment by trevorrowe** [comment]
The SDK uses Set for two primary reasons:

* It semantically enforces unique values in the same way DynamoDB does
* It is not ambiguous when compared to the DynamoDB list type

The first difference is convenient, but the 2nd reason is actually quite important. If item values received from DynamoDB were represented as arrays, it would not be possible to round-trip those values to the service and keep their current value. Using array for both lists, and binary/string/number sets would leave the SDK unable to know where those should end up when making a `#put_item` request. The current implementation guarantees no loss of precision for all data types (this is why we use BigDecimal for numeric attribute values) and the ability to get and put without changing the representation on the remote end.

Its curious that the JSON library does not implement `#to_json` for Sets. I suspect this might be an oversight? Here are some of the current extensions:

https://github.com/ruby/ruby/tree/2e4f0af00f85ca228bcf5fa919882359411c652a/ext/json/lib/json/add

**Comment by mrlamroger** [comment]
Thank you for the quick reply. Makes sense for a Ruby SDK to use Set for sets.
I opened a Ruby Issue for those interested in following up with the Set `#to_json`. https://bugs.ruby-lang.org/issues/11241
