### ISSUE TITLE
Error #exists? is not implemented for Aws::IAM::User

### ISSUE THREAD

**Issue by bilus** [aws/aws-sdk-ruby#840]
`bundle update`

```
Installing aws-sdk-core 2.1.0 (was 2.0.31)
Installing aws-sdk-resources 2.1.0 (was 2.0.31)
Installing aws-sdk 2.1.0 (was 2.0.31)
```

```ruby
iam = Aws::IAM::Client.new(region: 'eu-central-1')
user = Aws::IAM::User.new(name: 'xxxxx', client: iam)
user.exists?
```

=> `#exists? is not implemented for Aws::IAM::User`

**Comment by trevorrowe** [comment]
The resource classes require a waiter they can poll once to determine if the resource exists. There were no waiters defined for Aws::IAM, so I added a user exists waiter to meet this need.

**Comment by bilus** [comment]
Thanks!
