### ISSUE TITLE
Kinesis::Client#put_record configurable timeouts

### ISSUE THREAD

**Issue by lblackburn** [aws/aws-sdk-ruby#844]
I've seen put_record calls take over 60 seconds, would love to be able to configure max number of retries and request timeout. I tried finding the location this request is happening but the "seahorse" layer completely lost me.

**Comment by trevorrowe** [comment]
You can configure a :http_read_timeout which flows though. It is documented here http://docs.aws.amazon.com/sdkforruby/api/Aws/Kinesis/Client.html#initialize-instance_method

**Comment by trevorrowe** [comment]
There is also a :retry_limit option.
