### ISSUE TITLE
CloudFormation Parameter Validation Incorrect

### ISSUE THREAD

**Issue by jonaf** [aws/aws-sdk-ruby#848]
Hi there,

It appears that the validation implementation for CloudFormation parameters is incorrect. If I try to create a stack and provide a parameter whose value is not a string, for example if I use an integer, then the client throws a validation error and does not proceed, although this is technically correct (my parameter is of type = Number, not String).

```ruby
#!/usr/bin/env ruby
require 'aws-sdk'

cfn = Aws::CloudFormation::Client.new()

# throws an ArgumentError 
stack = cfn.create_stack({
    stack_name: 'my-stack',
    template_body: template_body,
    parameters: [{parameter_key: "key", parameter_value: 1}]
})

# however, this works just fine:
stack = cfn.create_stack({
    stack_name: 'my-stack',
    template_body: template_body,
    parameters: [{parameter_key: "key", parameter_value: "1"}]
})
```

The actual error is:

```
ArgumentError: expected params[:parameters][0][:parameter_value] to be a string
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/aws-sdk-core/param_validator.rb:26:in `validate!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/lib/ruby/gems/2.0.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from (irb):4
	from /usr/local/bin/irb:12:in `<main>'
```

I believe the SDK should consider the provided parameter Type and validate against *that*, rather than assuming all parameter values must be strings.

Addendum: the workaround is to initialize the client with validation disabled. Sadly, this disables *all* validation for all parameters as well, and I would rather keep the validation, except it should work correctly or as expected. I would rather not coerce every value into a string (the other alternative to disabling validation, which has the same effect of making the validation far less useful).

```ruby
cfn = Aws::CloudFormation::Client.new(validate_params: false)
```

**Comment by trevorrowe** [comment]
The SDK users a model of the service API that is similar to a sort of WSDL. This document declares that parameter of type string which is correct for the given schema. The SDK does not attempt to perform any contextual translation from non-string values to strings. I'm not super familiar with cloud front, but I suspect that context can only be gained by reading and understanding the template. This is currently out of scope for what the SDK is aiming to provide for API compatibility. This sort of feature would be better served as a library that is built on top of the client.

**Comment by jonaf** [comment]
Why have an option to validate parameters if you do not have the context to validate them properly? It would be much more fruitful to either (a) remove the option altogether, thereby implying that such validation should be done (purely) by whomever is using the SDK; or (b) support fully and sensibly the notion of validating parameters. If you must do it the current way, it would make more sense to `try` to re-cast the value as a String, and only throw a validation error if casting fails.

Ultimately, the CloudFormation API will perform validation on the parameter value (and will do this conversion to a string) anyway, so the context is important for complete validation based on the template, but all parameters will be converted to Strings first... So it would be fine if you validate everything as a string as you currently do, but instead of validate, just convert the type (if possible, and only throw an error if it's not possible). Since CloudFormation will convert all inputs to Strings and then validate them as whatever is the acceptable type (i.e., a "Number" type may be an integer or float), I think it would be OK for the SDK to behave identically: coerce the type into a String (if not possible, `raise` a value error) and then simply pass it along to the CloudFormation API to perform real validation. In that case, the `validate_params` option is obsolete.

**Comment by trevorrowe** [comment]
Parameter validation is very important to eliminate the common errors in how request parameters are structured and typed. The validate params option is not unique to CloudFormation or specific to template params. It validates all request input parameters. It gives useful contextual information. For example:

```ruby
s3 = Aws::S3::Client.new
s3.put_object(bucket_name:'abc', key:'abc', body:123)
#=> raises ArgumentError: parameter validator found 3 errors:
  - missing required parameter params[:bucket]
  - unexpected value at params[:bucket_name]
  - expected params[:body] to be a string or IO object
```

This provides a layer of type-safety to the SDK. It can be disabled primarily for performance reasons. I suspect there is some confusion based on the name. It is not unique to template parameters.
