### ISSUE TITLE
s3 object #copy_from raises ArgumentError: missing required parameter params[:copy_source]

### ISSUE THREAD

**Issue by gregburek** [aws/aws-sdk-ruby#849]
When using aws-sdk (2.1.0):

```
s3 = Aws::S3::Resource.new(region: ENV['AWS_REGION'])
first = s3.bucket('example').object('source')
second = s3.bucket('example').object('dest')
second.copy_from(first)
ArgumentError: missing required parameter params[:copy_source]
from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.1.0/lib/aws-sdk-core/param_validator.rb:26:in `validate!'
```

Based on https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#copy_from-instance_method, it appears that the case statement is against the `source`, not the `source.class`, which leads to an empty `:copy_source` param. 

Manually setting `:copy_source` as the intended case branch does in the above link works:

```
>second.copy_from(first, copy_source: "/#{first.bucket.name}/#{first.key}")
=> {
    :copy_object_result => {
                 :etag => "\"0bdef96bff3e420d51cdaa2374f689a5\"",
        :last_modified => 2015-06-21 07:33:52 UTC
    }
}
```

**Comment by trevorrowe** [comment]
It appears you are linking to documentation for v1 of the `aws-sdk` gem but are using v2. The documentation for `#copy_from` in v2 can be found here:

http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#copy_from-instance_method

You should be able to invoke this like so:

```ruby
s3 = Aws::S3::Resource.new(region: ENV['AWS_REGION'])
s3.bucket('example').object('dest').copy_from(copy_source: "example/source")
```

**Comment by dirkdk** [comment]
you are wrong I am afraid, the OP is linking to the right v2 documentation

**Comment by trevorrowe** [comment]
@dirkdk The URL is for the v1 documentation, and if you scroll to the top of the linked page, it is the v1 documentation as highlighted in red.

**Comment by dirkdk** [comment]
Sure.

I upgraded from 2.1.0 to 2.1.9, and now works for me:

````
temp_object = S3_BUCKET.object(temp_key)
target_object = S3_BUCKET.object(target_key)
temp_object.copy_to(target_object) 
````

**Comment by trevorrowe** [comment]
This works now because that feature was added as part of version 2.1.14:
https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md#2114-2015-08-12
