### ISSUE TITLE
Route Table used by a Subnet

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#851]
Using the plain EC2 client, the describe_subnets API call does not return the route table associated with the subnet. Is there any way to find out the route table associated with a given subnet? Is this just missing from the API itself, or is there a different way to get this information?

thanks!

**Comment by trevorrowe** [comment]
Have you tried `#describe_subnets`?

```ruby
ec2 = Aws::EC2::Client.new
ec2.describe_route_tables(filters:[{name:'association.subnet-id', values:['subnet-id']}])
```

**Comment by pchaganti** [comment]
Tried that. That will only work if there is an explicit association between the subnet and a route table. but if the subnet is using the default route table, there is no explicit association between the two and the above API call will not return any route table.

**Comment by pchaganti** [comment]
```Ruby
2.1.1 :009 > ec2.describe_route_tables(filters:[{name:'association.subnet-id', values:['subnet-fa0a80d1']}])
 => #<struct Aws::EC2::Types::DescribeRouteTablesResult route_tables=[]>
2.1.1 :010 >
```
![screen_shot_2015-06-22_at_10_33_44_pm](https://cloud.githubusercontent.com/assets/6500/8297844/0557bafa-192f-11e5-9e6f-576c0a19e7bb.png)

**Comment by awood45** [comment]
From the SDK perspective, we're returning the service response correctly.

I think you have the right understanding, however. My guess is that, if that call returns nothing when you're specifying an association, the subnet uses the default route table.

I'm going to raise this with our documentation team and follow up.

**Comment by awood45** [comment]
Hi, just to follow up: If no explicit subnet is returned, you can assume that it will be using the default route table. I believe they will be updating their docs to more clearly reflect this behavior.
