### ISSUE TITLE
Undefined method "first" for nil in region_detection.rb:47

### ISSUE THREAD

**Issue by thebravoman** [aws/aws-sdk-ruby#853]
This just occurred with version 1.64.0 of aws-sdk. (I can not use version 2 because of the  uninitialized constant Paperclip::Storage::S3::AWS (http://stackoverflow.com/questions/28374401/nameerror-uninitialized-constant-paperclipstorages3aws)).

This is the full stacktrace:
NoMethodError - undefined method `first' for nil:NilClass:
  aws-sdk-v1 (1.64.0) lib/aws/s3/region_detection.rb:47:in `region_from_location_header'
  aws-sdk-v1 (1.64.0) lib/aws/s3/region_detection.rb:29:in `detect_region_and_retry'
  aws-sdk-v1 (1.64.0) lib/aws/s3/region_detection.rb:13:in `retry_server_errors'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:249:in `make_sync_request'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:511:in `block (2 levels) in client_request'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:391:in `log_client_request'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:477:in `block in client_request'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:373:in `return_or_raise'
  aws-sdk-v1 (1.64.0) lib/aws/core/client.rb:476:in `client_request'
  (eval):3:in `put_object'
  aws-sdk-v1 (1.64.0) lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
  aws-sdk-v1 (1.64.0) lib/aws/s3/s3_object.rb:611:in `write'
  paperclip (4.3.0) lib/paperclip/storage/s3.rb:359:in `block in flush_writes'
  paperclip (4.3.0) lib/paperclip/storage/s3.rb:330:in `flush_writes'
  paperclip (4.3.0) lib/paperclip/attachment.rb:240:in `save'
  paperclip (4.3.0) lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
  activesupport (4.1.11) lib/active_support/callbacks.rb:443:in `block in make_lambda'
  activesupport (4.1.11) lib/active_support/callbacks.rb:224:in `block in halting_and_conditional'
  activesupport (4.1.11) lib/active_support/callbacks.rb:503:in `block in call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.11) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.1.11) lib/active_record/persistence.rb:103:in `save'
  activerecord (4.1.11) lib/active_record/validations.rb:51:in `save'
  activerecord (4.1.11) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.1.11) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  activerecord (4.1.11) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.11) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.11) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  activerecord (4.1.11) lib/active_record/transactions.rb:268:in `block in save'
  activerecord (4.1.11) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  activerecord (4.1.11) lib/active_record/transactions.rb:267:in `save'
  app/models/episode.rb:233:in `create_new_episode'
  app/controllers/episodes_controller.rb:61:in `create'
  actionpack (4.1.11) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.11) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.11) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.11) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.11) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.11) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.11) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.11) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.11) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.11) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.11) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.11) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.11) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.11) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.11) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.11) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.11) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.11) lib/action_dispatch/routing/route_set.rb:692:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
   () home/kireto/.rvm/gems/ruby-2.2.2/bundler/gems/hydra_attribute-b17875a46560/lib/hydra_attribute/middleware/identity_map.rb:9:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.11) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.11) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.11) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.11) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.11) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.11) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  rack-timeout (0.2.4) lib/rack/timeout.rb:108:in `call'
  railties (4.1.11) lib/rails/engine.rb:514:in `call'
  railties (4.1.11) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/kireto/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by thebravoman** [comment]
Turned out it is an issue with the regions. If the region is in Europe your are close to doomed with "other things you should do". Removed the bucket and created it in Oregon.

**Comment by trevorrowe** [comment]
@thebravoman Btw, you should be able to upgrade and start using the version 2 SDK in the same application.  If you change your gem dependencies to look like this:

```
# bring in both gems
gem 'aws-sdk-v1'
gem 'aws-sdk', '~>2'
```

Now you simply need to require both gems:

```
require 'aws-sdk-v1'
require 'aws-sdk'
```

Now you have both versions running in the same application. Paperclip should continue working as normal.

**Comment by trevorrowe** [comment]
You can get more information here: http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2

**Comment by babakgh** [comment]
I am using version 1.66.0, have same problem only with region `ap-northeast-2`. unfortunately upgrading to version 2 is not an option right now
