### ISSUE TITLE
AWS_DEFAULT_REGION vs AWS_REGION

### ISSUE THREAD

**Issue by farski** [aws/aws-sdk-ruby#857]
The docs in `regional_endpoint.rb` say 

> Defaults to `ENV['AWS_DEFAULT_REGION']`. Also checks `AWS_REGION` and `AMAZON_REGION`.

but the code right below it has `keys = %w(AWS_REGION AMAZON_REGION AWS_DEFAULT_REGION)`, so it looks like `AWS_REGION` gets priority.

**Comment by trevorrowe** [comment]
The implementation is correct, the docs are incorrect. Thanks!
