### ISSUE TITLE
Aws::Waiters::Errors::NoSuchWaiterError:  ElastiCache waiters

### ISSUE THREAD

**Issue by reppard** [aws/aws-sdk-ruby#858]
Aws::Waiters::Errors::NoSuchWaiterError: no such waiter :replication_group_available; valid waiter names are: 

Aws::ElastiCache::Client#wait_until method not finding waiters.  waiter_names returns empty array

**Comment by trevorrowe** [comment]
I am unable to reproduce this:

```ruby
 $ aws.rb
Aws> Aws::VERSION
=> "2.1.2"
Aws> elasticache.waiter_names
=> [:cache_cluster_available, :cache_cluster_deleted, :replication_group_available, :replication_group_deleted]
```

I was then able to invoke the `:replication_group_available` without issue. What version of the SDK are you using?

**Comment by reppard** [comment]
Should have updated sooner.  Was running a 2.0.x version of the gem.  I blasted my Gemfile.lock and bundle installed and all was well.  Thanks!

**Comment by reppard** [comment]
I did want to add a little feedback in regards to wait_until on the replication groups.  I've got the max retry and delay set to the maximum allowed values and it still hits the limit.  I'm creating just 2 small cluster nodes and calling wait_until before I create my route53 entry to point at the replication group.  Maybe the max retries could be increased for :replication_group_available?

**Comment by trevorrowe** [comment]
Those are simply defaults. You can set that to whatever values you prefer, including `nil` which disables them completely (poll forever, not recommended unless you customize the backoff via callbacks). Looking at the API reference documentation I can certainly understand why that would be non-obvious. Would you mind opening an issue to track an update to the wording to be more clear?

**Comment by reppard** [comment]
I don't mind at all.  Thanks for the help!
