### ISSUE TITLE
Aws::ElastiCache::Client#wait_until Documentation

### ISSUE THREAD

**Issue by reppard** [aws/aws-sdk-ruby#860]
http://docs.aws.amazon.com/sdkforruby/api/Aws/ElastiCache/Client.html#wait_until-instance_method

This could just be me but the documentation and more specifically the table at the bottom of the page led me to believe that in regard to these waiters, the maxium allowed delay is 15 and the maxium allowed attempts is 40.  Turns out these are just the defaults.  Any chance the docs can specify that these are default values and list any constants if any?

Thanks for the great work!

**Comment by awood45** [comment]
I can see where there could be confusion here, will take a look at how we can word this.

**Comment by awood45** [comment]
Thanks for bringing this to our attention. I've added the "Default" label to the table headers directly, and that will be reflected in the documentation after our next release.
