### ISSUE TITLE
First call to Aws::ElasticLoadBalancing::Client.describe_instance_health Always Returns inService on First Try

### ISSUE THREAD

**Issue by richardboydii** [aws/aws-sdk-ruby#868]
I've spent the past hour playing around with this and can reliably reproduce. I think this may not necessarily be a problem with the Ruby SDK but it's how I found it.

Given: 
* Several instances that are exposed by 1 or more ELBs
* Health checks on each instance using an HTTP endpoint
* At least one instance failing a health check and marked Out of Service in the Web Console

When the describe_instance_health is run the first time against the ELB (after instantiating the client), the return always lists state='InService' for every Instance, even the one that is OutOfService. If you make a second call to describe_isntance_helath with the same ELB Client object, it will return the OutOfService status correctly.

**Comment by awood45** [comment]
Can you provide a wire trace for this? That should tell us if the service is returning these values, or if something is going on with the SDK.

**Comment by richardboydii** [comment]
After doing serveral series of wire traces I'm flummoxed but happy to report that I cannot reproduce. I'm going to close the ticket.
