### ISSUE TITLE
EMR Streaming job

### ISSUE THREAD

**Issue by robert2d** [aws/aws-sdk-ruby#875]
I want to be able to use a streaming job via the AWS Ruby SDK. It looks as though the current implementation is very old.. The python cli we use in bash is very different from the ruby sdk when it comes to 'add-steps'.

Currently we are using the python CLI but trying to migrate to the ruby SDK for our jobflows by creating a shared gem with common EMR interactions. This is currently written in Bash and is not great for the team to work with. We have used the json steps file configuration:
```bash
aws --region ${EMR_REGION} emr add-steps --cluster-id $cluster_id --steps file://./streaming_steps.json)
```

```json
  // streaming_steps.json
  {
    "Name": "Basic reports gzip to lzo",
    "Args": [
      "-mapper",
      "grep -v Date",
      "-input",
      "${S3_TEMP_FOLDER}/basic/*.gz",
      "-output",
      "${S3_TEMP_FOLDER}/basic/mapped/",
      "-jobconf",
      "mapred.output.compress=true",
      "-jobconf",
      "mapred.output.compression.codec=com.hadoop.compression.lzo.LzopCodec"
    ],
    "ActionOnFailure": "CANCEL_AND_WAIT",
    "Type": "STREAMING"
  },
```

I want to know wether there are plans to upgrade the Ruby SDK? or if there is any alternative we can use  to get something more similar to the current python cli?

**Comment by awood45** [comment]
The AWS CLI command you're using is a higher-level abstraction included in the CLI that wraps the `#add_job_flow_steps` API: http://docs.aws.amazon.com/sdkforruby/api/Aws/EMR/Client.html#add_job_flow_steps-instance_method

We don't have plans currently to add this hand-written abstraction to the Ruby SDK, but can look at it as a feature request.

That said, in my personal experience, you shouldn't have much trouble translating that to an API call, and if you do, feel free to let us know here as I have some experience using the API directly.

**Comment by robert2d** [comment]
Thanks for getting back to me. I ended landing on https://github.com/rslifka/elasticity which provides an interface the the modern emr API via Ruby. Cheers
