### ISSUE TITLE
booleans in MachineLearning Predict API

### ISSUE THREAD

**Issue by syedmusamah** [aws/aws-sdk-ruby#878]
I have a few boolean variables in my binary model. I was doing:
``` Ruby
prediction_params = {
      ml_model_id: machine_learning_model["aws_model_id"],
      record: {   
              bool_variable_1: value_1.to_s, # "true",
              bool_variable_2: value_2.to_s, # "false",
              category_id: item.category_id.to_s
          },
      predict_endpoint: machine_learning_model["prediction_endpoint_url"]
}
client.predict(prediction_params)
```

The API responded back with the same `predicted_scores` no mater what values I set in the `record`.
The fix was to convert the boolean string values from "true" or "false" to "1" or "0". 

It would be great to see support for native ruby booleans (`true` and `false`). At the very least, the SDK should be able to convert `"true"` into `"1"` itself, or throw a validation error.

[related AWS forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=651416&#651416)

**Comment by trevorrowe** [comment]
Sorry for the confusion. The SDK expects the record to be a hash of string keys and string values. This is based on the expected values of the service. It could be possible to provide a client-side conversion of booleans to their appropriate string representation.

**Comment by trevorrowe** [comment]
I've moved this to our feature request list.

**Comment by syedmusamah** [comment]
Thanks!
