### ISSUE TITLE
2.1.9 raising Aws::CognitoIdentity::Errors::MissingAuthenticationTokenException on every CognitoSync API Call

### ISSUE THREAD

**Issue by eniskonuk** [aws/aws-sdk-ruby#882]
Upgrading to 2.1.9 has introduced this error on a valid list_identity_pools API call.

cogs = Aws::CognitoSync::Client.new(
        :region => region, :credentials => @aws_cred, :logger => @aws_logger
      )
respp = cogi.list_identity_pools( :max_results => MaxResults )
RAISE

Thx
Enis

**Comment by trevorrowe** [comment]
Thank you for reporting this. I'm guessing that you meant that `Aws::CognitoIdentity::Client#list_idenity_pools` raises. The change that caused this regression comes from this pull-request:
https://github.com/aws/aws-sdk-ruby/pull/862

The following operations were white-listed to be sent as unsigned requests:

* GetCredentialsForIdentity
* GetId
* GetOpenIdToken
* ListIdentityPools
* UnlinkDeveloperIdentity
* UnlinkIdentity

I tested a few of these, but not all. Each of them do state quite clearly in their public API documentation the following:

> This is a public API. You do not need any credentials to call this API.

I've gone back and tested all operations and found two of them that do require authentication despite the claims in the API reference:

http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_ListIdentityPools.html
http://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_UnlinkDeveloperIdentity.html

I've corrected the code for these two operations and added integration tests to test these against live endpoints. Thank you for bringing this to our attention. I'll have a patch release out shortly.

**Comment by eniskonuk** [comment]
Thanks @trevorrowe. Really appreciate the fast response.

**Comment by trevorrowe** [comment]
I forgot to update, but 2.1.10 was released earlier today wight the patch.

**Comment by eniskonuk** [comment]
Yes. I saw it and tested already. We will deploy as soon as we can.

Enis Konuk
enis@qwiklab.com
978-760-0732

**Comment by trevorrowe** [comment]
Also worth noting, the API reference documentation has been corrected as well.
