### ISSUE TITLE
S3 pre-signed URL Canonical Request missing port number

### ISSUE THREAD

**Issue by JumpyKitten** [aws/aws-sdk-ruby#883]
It appears when composing the Canonical Request for presigned URL, the Ruby SDK is missing the port number in the signed Host header:

In aws-sdk-core/signers/v4.rb:
def sign(req)
...
req.headers['Host'] = req.endpoint.host

Here, req.endpoint.host does not include port number even if it is specified. This is not a problem if default port is used, but for servers that doesn't use default port, this will cause SignatureDoesNotMatch.

**Comment by trevorrowe** [comment]
Thank you for reporting this limitation. This should go out with the next release.

**Comment by JumpyKitten** [comment]
That was quick. Thanks.
