### ISSUE TITLE
API Gateway Support

### ISSUE THREAD

**Issue by darylrobbins** [aws/aws-sdk-ruby#884]
Any plans to support API Gateway? Right now, it seems like the only SDK available for it is the awslabs for Java version.

**Comment by pchaganti** [comment]
:+1:

**Comment by eniskonuk** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by vddgil** [comment]
Any release date for that feature ?

**Comment by verlinden** [comment]
+1 👍

**Comment by trevorrowe** [comment]
Just a heads up. I've been working on adding support for API Gateway. This is coming, but I can not comment on when it will be ready.

**Comment by trevorrowe** [comment]
Good news! We were able to release support for API gateway today!

**Comment by eniskonuk** [comment]
Thanks Trevor. Saw that a few minutes ago. We're starting work using it immediately.

On another note, the SSM API change broke our existing code. I'm hoping an upgrade to 2.1.32 will automagically fix everything.

Thx
Enis Konuk
enis@qwiklab.com
978-760-0732

**Comment by trevorrowe** [comment]
Do you mean that a service change to the SSM API caused your application to
break before upgrading the SDK? If so thats a bit concerning and should
probably be escalated.

**Comment by eniskonuk** [comment]
My initial assessment was yes but after debugging this, it turns out the issue is not related to the API change but to the new AWS-* documents in SSM that are not deletable. 

Thx
Enis Konuk
enis@qwiklab.com
978-760-0732
