### ISSUE TITLE
`Aws::EC2::NetworkInterfaceAssociation` doesn't implement `#load`.

### ISSUE THREAD

**Issue by MrJoy** [aws/aws-sdk-ruby#890]
This causes most of the accessors on it to fail, if you get an instance -- for example -- via a `Aws::EC2::VpcAddress`.

**Comment by MrJoy** [comment]
To add a hair more detail, calling `Aws::EC2::Resource#vpc_addresses` surfaces the issue:

```ruby
ec2
  .vpc_addresses
  .to_a
  .map(&:association)
  .map(&:public_ip) # Chokes hard with the exception mentioned in the issue title.
```

**Comment by MrJoy** [comment]
Any word on this?

**Comment by trevorrowe** [comment]
Sorry for the slow response on this. It took a bit of digging to find out how I could load the details of a NetworkInterfaceAssociation given only its association ID. This should go out with the next release.
