### ISSUE TITLE
Missing description field in IAM list_policies

### ISSUE THREAD

**Issue by rlister** [aws/aws-sdk-ruby#894]
Policy objects returned from a call to `Aws::IAM::Client.list_policies()` have `description` of `nil`. If the policy is retrieved with `Aws::IAM::Client.get_policy()` then `description` _is_ populated.

```
irb(main):018:0> Aws::VERSION
=> "2.1.13"

irb(main):009:0> iam=Aws::IAM::Client.new
=> #<Aws::IAM::Client>

irb(main):010:0> p = iam.list_policies.policies.find{|p|p.policy_name.match(/logstash/i)}
=> #<struct Aws::IAM::Types::Policy policy_name="Logstash-SQS", policy_id="XXXXXXXXXXXXXXXXXXXXX", arn="arn:aws:iam::123456789000:policy/Logstash-SQS", path="/", default_version_id="v2", attachment_count=3, is_attachable=true, description=nil, create_date=2015-05-20 03:20:57 UTC, update_date=2015-05-20 17:39:30 UTC>

irb(main):011:0> g = iam.get_policy(policy_arn: p.arn)
=> #<struct Aws::IAM::Types::GetPolicyResponse policy=#<struct Aws::IAM::Types::Policy policy_name="Logstash-SQS", policy_id="XXXXXXXXXXXXXXXXXXXXX", arn="arn:aws:iam::123456789000:policy/Logstash-SQS", path="/", default_version_id="v2", attachment_count=3, is_attachable=true, description="Allow logstash routers to write logs to SQS.", create_date=2015-05-20 03:20:57 UTC, update_date=2015-05-20 17:39:30 UTC>>
```

**Comment by trevorrowe** [comment]
I did some looking into this. I enabled a HTTP wire trace to see what was going on.

```ruby
iam = Aws::IAM::Client.new(http_wire_trace:true)
iam.list_policies()
iam.get_policy(policy_arn:"arn:aws:iam::aws:policy/AWSDirectConnectReadOnlyAccess")
```

IAM is only returning the description in the describe call. Is is not returned from the service in the list call. There is no flag that I am aware of that would cause it to be returned in both cases. I can raise this issue with the service team, but isn't anything that I can do from the SDK without sending a follow-up request which is not a suitable solution.

**Comment by trevorrowe** [comment]
The IAM API reference documentation and the SDK documentation both mention that these values are only included in the output from a GetPolicy call:

http://docs.aws.amazon.com/IAM/latest/APIReference/API_Policy.html
http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Types/Policy.html#description-instance_method
