### ISSUE TITLE
Intermittent 403 POST Error - "Invalid according to Policy: Policy expired."

### ISSUE THREAD

**Issue by gnitnuj** [aws/aws-sdk-ruby#895]
So I keep getting this error seemingly randomly, and have tried just about everything unsuccessfully. I'm using v1 of the gem, and I'm thinking that this is a time drift issue from when the policy expiration is set. I'd be eternally grateful if someone could point me in the right direction. Thanks!

**Comment by trevorrowe** [comment]
Can you provide some additional context to the issue. What service and operation are you making requests against? Can you share the policy?

**Comment by gnitnuj** [comment]
@trevorrowe, I actually figured out my problem and just fixed it. My policy expiration was hitting the 1 hour default, so I passed `signature_expiration: 5.days.from_now.utc` so the policy expiration is far longer than I would ever need it to be. It took a bit of digging through the docs to get the right parameter for the `.presigned_post` method though since there are multiple other expire options.
