### ISSUE TITLE
documentation for return type of s3 body misleading

### ISSUE THREAD

**Issue by stan3** [aws/aws-sdk-ruby#898]
Perhaps I'm not the most familar with the api docs but to me http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Types/GetObjectOutput.html#body-instance_method indicates the return type of body is IO,File.  This looks a bit like returning an IO and File object as as Array, where as the return type appears to just be an IO object.  Perhaps it would be better documented as just returning an IO object?

**Comment by trevorrowe** [comment]
The original intention was to show that the return value might be an IO object or a File object. When it returns an array a different notation is used like:

```
Returns:
* (Array<String>) - Description of return value.
```

That said, I understand how this is not obvious or clear. I think I'll simply remove the File from the possible return types given that a File is considered an IO object.
