### ISSUE TITLE
Documentation: should state that all connections are made through SSL 

### ISSUE THREAD

**Issue by tonatiuh** [aws/aws-sdk-ruby#901]
In the AWS documentation is stated that "you should transmit your requests using Secure Sockets Layer (SSL) by using HTTPS." (http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html#why-requests-are-signed), which makes sense and in my case is a requirement; in order to find if this client is connecting through SSL I needed to check a lot in the code and internet until I found: https://github.com/aws/aws-sdk-ruby/blob/v2.1.7/aws-sdk-core/lib/seahorse/client/net_http/connection_pool.rb#L262 and https://gitter.im/aws/aws-sdk-ruby?at=550202d0338c496703ffb9cb. 

So, I think the fact SSL is enabled by default should be stated in the documentation since IMO that's an important feature.

**Comment by trevorrowe** [comment]
I added a note to the README to address this. Thanks for the suggestion.
