### ISSUE TITLE
Best way to determine if an exception should be retried?

### ISSUE THREAD

**Issue by tmornini** [aws/aws-sdk-ruby#905]
Hello. Wondering how to determine if a particular exception should be considered retryable?

Ideally, I'd like to be able to write

```
def query client, method, request
  client.send method, request
rescue Aws::Errors::RetryableError
  sleep_exponentially
  retry
end
```

**Comment by trevorrowe** [comment]
The SDK has built in retry logic for 500 server errors and throttling errors. Are you encountering errors that you feel should have been retried but are not? Or perhaps are they not backing-off enough, or with sufficient number of retires?

**Comment by tmornini** [comment]
@trevorrowe Oh, apologies, made a bad assumption that it was my responsibility.
