### ISSUE TITLE
Unable to stub S3 client responses

### ISSUE THREAD

**Issue by mitchless** [aws/aws-sdk-ruby#906]
While attempting to follow the instructions posted here (https://ruby.awsblog.com/post/Tx15V81MLPR8D73/Client-Response-Stubs) for stubbing AWS responses the `Client` appears to be requiring credentials. This is the sequence I use in the Rails console:
```ruby
> stubbed_s3_client = Aws::S3::Client.new(stub_responses: true)
> stubbed_s3_client.stub_responses(:head_bucket, {}, 'NotFound')
> stubbed_s3_client.head_bucket(bucket: 'my_bucket')
Aws::Errors::MissingCredentialsError: unable to sign request without credentials set
from /usr/local/rvm/gems/ruby-2.1.5/gems/aws-sdk-core-2.1.3/lib/aws-sdk-core/plugins/request_signer.rb:94:in `require_credentials'
```

Is there a step I'm missing here?

**Comment by trevorrowe** [comment]
I am unable to reproduce this locally. Can you try updating the the latest version and seeing if this persists? Also, what does the following produce?

```ruby
stubbed_s3_client = Aws::S3::Client.new(stub_responses: true)
stubbed_s3_client.config.credentials
```

**Comment by mitchless** [comment]
Even after updating to 2.1.15, the command sequence results in the same error.

Here are the credentials returned:
```ruby
> stubbed_s3_client = Aws::S3::Client.new(stub_responses: true)
=> #<Aws::S3::Client>
> stubbed_s3_client.config.credentials
=> #<Aws::Credentials access_key_id="">
```

Is it possible that `aws.yml` is interfering?

**Comment by trevorrowe** [comment]
I'm little confused here. Do you mean when running the v2 SDK from within a Rails application, the precense of a RAILS_ROOT/config/aws.yml file causes `stub_responses: true` to stop working? As far as I know, the v2 SDK does not ever source these credentials.

**Comment by mitchless** [comment]
Sorry for the confusion. I meant to come back and update this further but failed to amidst the myriad task swapping of my day.

This appears to be a self-caused problem in our Rails application. We pre-fill the credentials of our app from `aws.yml` and for our development profile those are empty strings. If the file is removed, we do not create the credentials object and update `Aws.config`.

It appears that if a credentials object is specified, `Aws` will attempt to use it regardless of whether `stub_responses: true` is present. This probably isn't a big deal, but did catch me by surprise.

**Comment by trevorrowe** [comment]
This is correct. When credentials are present, they will be used to sign. I'm glad you were able to resolve this.

**Comment by ritec** [comment]
Just ran into this same issue, took forever to find out what was going on.

**Comment by mullermp** [comment]
What version of the SDK are you using?

**Comment by ritec** [comment]
I am using `3.136.0`, I ended up using the regular vanilla stubbing approach with `allow_any_instance` instead. There is some weird interaction between `stub_responses` and Credentials that I was not able to troubleshoot properly under my current deadline.

```
response = @sqs_client.receive_message(
  queue_url: queue_url,
  max_number_of_messages: MAX_NUMBER_OF_MESSAGES
)
Aws::Errors::MissingCredentialsError: unable to sign request without credentials set
from /Users/ri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.136.0/lib/aws-sdk-core/plugins/signature_v4.rb:69:in `sign_request'
```

**Comment by mullermp** [comment]
Hmm weird. When you enable `stub_responses: true`, we use stubbed credentials:

```
Aws::SQS::Client.new(stub_responses: true).config.credentials
=> #<Aws::Credentials access_key_id="stubbed-akid">
```

You can use the `#stub_responses` method on the client to mock service calls, rather than the vanilla rspec stubbing approach (not necessarily supported).
