### ISSUE TITLE
arabic text not showing properly when open the csv file in s3

### ISSUE THREAD

**Issue by vishnurkrishnan** [aws/aws-sdk-ruby#909]
I have been uploading csv data to s3 and it works fine, but the issue is, when i download that file into my system, or open that file in s3 it shows the arabic content as gibberish, this is what i am trying

     s3 = AWS::S3.new
      my_bucket = s3.buckets[ENV['S3_BUCKET_NAME']]
     // here the data encoding name is UTF-8
      my_bucket.objects.create(filename, data)
    // here the data encoding name is ASCII-8BIT
      object = my_bucket.objects[filename]
      puts "READ FROM S3 #{object.read}" // here its show the exact arabic letters

 and also i am using this code

     object.url_for(:read, { expires: Exp::EXP, response_content_type: "text/csv",   response_content_disposition: "attachment;filename=#{filename}.csv"}).to_s
to compose the download url, is there any workaround to get that data as the exact one?

**Comment by trevorrowe** [comment]
You probably need to specify one or more of the response headers for content encoding. See the following blog post for more information. You can specify these values when you create the presigned url.

http://www.bennadel.com/blog/2696-overriding-content-type-and-content-disposition-headers-in-amazon-s3-pre-signed-urls.htm
