### ISSUE TITLE
How does one create a S3 resource for website endpoint?

### ISSUE THREAD

**Issue by BanzaiMan** [aws/aws-sdk-ruby#915]
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region has a list of endpoints for S3 website endpoints. How does one create a resource to upload to this?

The document suggests

```ruby
api = ::Aws::S3::Resource.new region: 'us-east-1', credentials: creds, endpoint: 'http://s3-website-us-east-1.amazonaws.com'
```

but this raises `Aws::S3::Errors::NotFound` when it's time to upload.

On the other hand, 

```ruby
api = ::Aws::S3::Resource.new region: 'us-east-1', credentials: creds # without endpoint
```

and

```ruby
api = ::Aws::S3::Resource.new region: 'us-east-1', credentials: creds, endpoint: 'http://s3.amazonaws.com'# with S3 endpoint
```

both work.

Is this the correct way to do it? Is this documented anywhere? If so, I must have missed it!

**Comment by trevorrowe** [comment]
When using the `aws-sdk` you should configure the region and your AWS credentials. The SDK will construct the correct endpoint for making API calls.  The S3 website endpoints are for using via the web, not the SDK. If you have a bucket website configuration, then you can use the web endpoint to access objects in your bucket via a normal browser.

**Comment by BanzaiMan** [comment]
@trevorrowe Great. Thanks for the clarification!
