### ISSUE TITLE
Presigner: undefined method `credentials` for nil:NilClass

### ISSUE THREAD

**Issue by kholbekj** [aws/aws-sdk-ruby#918]
Using the aws-sdk gem 2.1.18, I'm running into a strange error when trying to sign a url:
```
s3 = Aws::S3::Resource::new(region: region)
      s3.bucket(bucket).object(path).presigned_url(:get, expires_in: 604800)
```
```
     NoMethodError:
       undefined method `credentials' for nil:NilClass
     # ./app/v1/models/job_file.rb:30:in `presigned_url'
```
A similar issue recently on SO (http://stackoverflow.com/questions/32199954/awss3presigner-undefined-method-credentials-for-nilnilclass-in-ruby) seems to point at presigner, where there's a call to `config.credentials` but I can't really figure out why this is exploding. It works in my other app, but not in my api where i just added the aws-sdk.

**Comment by trevorrowe** [comment]
I responded to the stackoverflow issue. In short, you have not configured credentials. If you had made a request then it would have given a more helpful error message. 

    s3 = Aws::S3::Resource::new(
      region: region,
      credentials: Aws::Credentials.new('access-key-id', 'secret-access-key')
    )
    s3.bucket(bucket).object(path).presigned_url(:get, expires_in: 604800)

**Comment by kholbekj** [comment]
Ah, thank you so much! Thought it might be a bug due to the SO timing, but there ya go.

**Comment by SubhaPrince** [comment]
I am getting this error where the given region is correct

<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>
Error parsing the X-Amz-Credential parameter; the region 'us-east-1' is wrong; expecting 'eu-west-2'
</Message>
<Region>eu-west-2</Region>
<RequestId>0A19A991D5C2440C</RequestId>
<HostId>
mqt64amJyBH4Vz/0c68v08GCtMq3OY5k21TGzBuYlxKY9Qt9o1nKpxZnJm9vnYB5xIdg7l1cJMI=
</HostId>
</Error>
