### ISSUE TITLE
How do I check when all instances exist in an autoscaling group?

### ISSUE THREAD

**Issue by juliantai** [aws/aws-sdk-ruby#919]
I saw that this post [https://ruby.awsblog.com/post/Tx2I4U7QAOJYNDY/Ruby-SDK-Version-2-and-Memoization](https://ruby.awsblog.com/post/Tx2I4U7QAOJYNDY/Ruby-SDK-Version-2-and-Memoization) described a ```#refresh!``` method for response objects. 

    auto_scaling_client.describe_auto_scaling_groups({
      auto_scaling_group_names: [launch_configuration_name],
    })
    .auto_scaling_groups.each do |asg|
    
        asg.instances.each do |instance_struct|
          # it doesn't always have instances
        end
    end

How would I check for instances without a waiter available in the new sdk? Do I call ```#describe_auto_scaling_groups``` over and over?

**Comment by trevorrowe** [comment]
What is your end goal? The refresh method is only for resource objects, not data objects returned by client operations. Can you describe what you are trying to accomplish?

**Comment by juliantai** [comment]
I want to grab all the instance ids once the machines have booted and add them to the load balancers after they are healthy.

**Comment by trevorrowe** [comment]
From looking at the API for Auto Scaling, it looks like you would need to describe your auto scaling group, grab the list of instance IDs and wait until they are healthy. Looking at your initial question, it seems that for a period of time the `#describe_auto_scaling_groups` may return with an empty list of instances. Is this correct?

**Comment by juliantai** [comment]
Yeah that's exactly it

**Comment by trevorrowe** [comment]
You can probably do something like the following. Be warned, I have not tested this myself:

```ruby
as = Aws::AutoScaling::Client.new
group_name = 'name'

# Wait until the auto scaling group has a list of instances and
# all of the instances are in the desired state
# TODO : Needs a terminal case to prevent infinite loop
begin
  resp = as.describe_auto_scaling_groups(auto_scaling_group_names:[group_name])
  instances = resp.auto_scaling_groups.first.instances
end while instances.empty? || instances.any? { |i| i.health_status != 'expected-status' }
```

Seems like a waiter would be helpful. I imagine something like the following:

```ruby
as = Aws::AutoScaling::Client.new
as.wait_until(:instances_healthy, auto_scaling_group_names:['group-name'])
```

I can add this to our backlog, but I can't comment on when we could get to it. We do accept pull requests for waiters if you'd like to take a stab at one.

**Comment by juliantai** [comment]
That looks like what I was thinking about adding. I'll take a look at waiters if I get some time. Thanks a bunch for helping me out and saving me some effort.

**Comment by trevorrowe** [comment]
I'm going to close this issue now. Please feel free to re-open or create a new issue if you run into trouble.
