### ISSUE TITLE
Elastic Transcoder not sending a message to the corresponding Simple Notification Service topic

### ISSUE THREAD

**Issue by amazonuser** [aws/aws-sdk-ruby#920]
Elastic Transcoder has set up to send a message to the corresponding Simple Notification Service topic. It does complete the job but stopped sending the confirmation after installing the latest AWS SDK update. This code/feature was working perfectly before installation. nothing has changed in the code or setting of ET other than replacing AWSClientFactory.CreateAmazonSimpleNotificationServiceClient(RegionEndpoint.GetBySystemName(awsRegion)  with  Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient(RegionEndpoint.GetBySystemName(awsRegion)) as AWSClientFactory is no longer supported in newer version of SDK.  Please review this issue. many thanks in advance.

**Comment by trevorrowe** [comment]
It looks like you opened the issue against the wrong repository. If you are using .NET then you should open an issue here: https://github.com/aws/aws-sdk-net
