### ISSUE TITLE
v1 Deprecation?

### ISSUE THREAD

**Issue by maclover7** [aws/aws-sdk-ruby#924]
Hi! I come from the [Paperclip](https://github.com/thoughtbot/paperclip) file attachment library. Currently Paperclip supports both aws-sdk v1 and v2. We were wondering if there was any plan for deprecating v1 of aws-sdk? We were planning on releasing a major version of Paperclip soon, and dropping v1 of aws-sdk would be a breaking change.

**Comment by trevorrowe** [comment]
For quite a while now, all feature work has been for version 1 of the SDK. We no longer update version 1 with new services, API updates for existing services, and we are not adding any additional functionality. We continue to accept and fix bugs and security issues. We do not currently have a date for when security and bug fixes will stop. **I will start the conversation internally on picking an end of life date for version 1.**

That said, we took a lot of effort to ensure that version 1 and version 2 could be used in the same project allowing users to upgrade at gradually and at will.

**Comment by maclover7** [comment]
:+1:

**Comment by awood45** [comment]
Update/Clarification: V1 of the SDK is deprecated (and has been for some time in a de-facto state), though we will release any future security updates that are needed. Official announcements will be posted later in the appropriate channels.

**Comment by awood45** [comment]
Going to close this out as this is definitely deprecated. Any future releases will only be for security issues when and if they arise.
