### ISSUE TITLE
Feature request: Checking for Service Availability in an AWS Region

### ISSUE THREAD

**Issue by keviny22** [aws/aws-sdk-ruby#926]
As a developer I would like to have the ability to programmatically determine what region a specific service is available in. Currently the region list would need to be hardcoded. We cannot assume that when a new region is added, all services are initially enabled.

Ideally I would like following methods:
* pass the service name; return a list of supported regions
* pass a region; return a list of supported services.
* pass service_name and region; return true/false if region supports that service

This feature would be an interface for the information provided here http://docs.aws.amazon.com/general/latest/gr/rande.html#ct_region

There is existing precedence for this feature in the Java SDK

REF: http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-region-selection.html#region-selection-query-service

**Comment by eniskonuk** [comment]
:+1:  We would also benefit from this.

**Comment by trevorrowe** [comment]
As discussed in the gitter channel, we are actively looking into this. I can't comment on a timeline, but I'm inclined to add this functionality.

**Comment by trevorrowe** [comment]
I've moved this to our feature request backlog. I also wanted to provide an update. We have been working on this internally. I'm fairly confident this feature will materialize. We are still trying to determine what the best mechanism would be to track the regions and keep the list current with each SDK release.
