### ISSUE TITLE
Destination region breaks auto pre-signed URL in snapshot_copy

### ISSUE THREAD

**Issue by rambler** [aws/aws-sdk-ruby#928]
When you copy a snapshot from one region to another using `#copy_snapshot`, the `EC2CopyEncryptedSnapshot` plugin is automatically applied (this is awesome when it works).

However,

A) It's not clear from the documentation for `#copy_snapshot` that this plugin will be invoked or how to use it (i.e. the client needs to be one for the destination region).

B) The plugin doesn't work if the `destination_region` option is supplied. In the two code snippets below, the first one fails but the second one succeeds.

Fails:
```ruby
            copy_snap_id = @ec2_alt.copy_snapshot(
                {
                    source_region: @default_region,
                    source_snapshot_id: snap_id,
                    destination_region: @alt_region,
                    description: "Copy of #{@default_region} snapshot #{snap_id} of volume #{vol_id}",
                    encrypted: true,
                }
            ).snapshot_id
```

Succeeds:
```ruby
            copy_snap_id = @ec2_alt.copy_snapshot(
                {
                    source_region: @default_region,
                    source_snapshot_id: snap_id,
                    description: "Copy of #{@default_region} snapshot #{snap_id} of volume #{vol_id}",
                    encrypted: true,
                }
            ).snapshot_id
```

**Comment by trevorrowe** [comment]
As a status update, I've added some actual examples to the API reference documentation showing how to copy encrypted snapshots. I have not yet addressed removing the `:destination_region` from the documentation, or the behavior swap.

**Comment by trevorrowe** [comment]
I just pushed a commit which fixes how the SDK was disabling pre-signing the copy-snapshot operation when the `:destination_region` was set. It looks like it was using that parameter keep from applying the copy_snapshot URL in a recursive loop (it calls #copy_snapshot to generate a presigned url).

I believe the last step to improve this is to remove the `:destination_region` and `:presigned_url` parameters from the API reference documentation.

**Comment by trevorrowe** [comment]
The updated documentation should go out with our next release, likely tomorrow.
