### ISSUE TITLE
EC2::Instance#state is not stubbed properly

### ISSUE THREAD

**Issue by platzhirsch** [aws/aws-sdk-ruby#932]
As observed on aws-sdk-core (2.1.20). When writing tests and using AWS's stubbing as follows:

```ruby
Aws.config.update(
  region: 'eu-central-1',
  credentials: Aws::Credentials.new(access, secret),
  stub_responses: true
)
```
Then an invocation to `Aws::EC2::instance.new(id).state` results in the following error
```
NoMethodError: undefined method `[]' for nil:NilClass
	from /home/user/.rvm/gems/ruby-2.2.1/gems/aws-sdk-resources-2.0.38/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
```
Currently, I need to `#stub` state myself. Shouldn't the AWS gem take care of this?

**Comment by trevorrowe** [comment]
The `:stub_responses` option causes the clients to empty responses. It does not attempt to setup fake state for AWS resources. If you desire the client to return a specific set of values, then you have to provide the values they should return:

```ruby
Aws.config[:ec2] = {
  stub_responses: {
    describe_instances: {
      reservations:[{instances:[{state:{code:123, name:'name'}}]}]
    }
  }
}

Aws::EC2::Instance.new('id').state
#=> #<struct Aws::EC2::Types::InstanceState code=123, name="name">
```

This level of response stubbing is most useful for applications or libraries that deal directly with the client classes. You are probably better off stuff the `Aws::EC2::Instance#state` yourself if that is the interface you are working with.
