### ISSUE TITLE
Aws::S3::Errors::InternalError when using object.copy_to with multipart across S3 regions

### ISSUE THREAD

**Issue by mattcook** [aws/aws-sdk-ruby#933]
Hi, we are receiving an `Aws::S3::Errors::InternalError:` when using `object.copy_to` with `multipart_copy: true` across regions. The specific regions that affect us are copying an object from a bucket in `eu-west-1` into a bucket in `us-east-1`. The version of the sdk is aws-sdk (2.1.23) but also tested in (2.1.14) and it gives a Malformed XML error instead. Our short term fix is to not use the multipart_copy option as majority of our files are under 5gb.

Example code with `source_object` being an S3 object in eu-west-1
```
      source_object.copy_to( { bucket: 'sample-bucket' , key: 'output' } , { multipart_copy: true, server_side_encryption: 'AES256' })
```

Stack trace:
```
Aws::S3::Errors::InternalError: We encountered an internal error. Please try again.
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/seahorse/client/request.rb:70:in `send_request'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-core-2.1.23/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/services/s3/object_multipart_copier.rb:75:in `copy_part'
    from /Users/test/.rvm/gems/ruby-2.2.3@alchemist/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/services/s3/object_multipart_copier.rb:63:in `block in copy_part_thread’
```

**Comment by trevorrowe** [comment]
The Aws::S3::Errors::InternalError error indicates the service responded with a 500 status code. The SDK automatically retries these errors. It sounds like an object that generates this error will consistently generate this error. Is this correct? If you have a reproducible error case, then I would love to pair on debugging this. I have not seen this particular error myself.

**Comment by trevorrowe** [comment]
@mattcook Thanks for for helping to reproduce the issue. I've got the wire log you sent me. Were you able to open an issue with Amazon S3?

**Comment by mattcook** [comment]
@trevorrowe Thanks for all your help with debugging this issue. On a whim I tested the issue again today and noticed that the issue has been resolved. :+1:

**Comment by trevorrowe** [comment]
Thats awesome. To be honest, I did not have a chance to raise the issue with S3. They must have seen the 500 errors coming from their service and resolved the issue. I'm going to close this issue, but please feel free to re-open if the issue persists.
