### ISSUE TITLE
v2 SDK DynamoDB Client requires region, even if endpoint set

### ISSUE THREAD

**Issue by felixbuenemann** [aws/aws-sdk-ruby#934]
I'm trying to connecto to a local DynamoDB instance on localhost port 8000 using the v2 SDK (aws-sdk-core-2.1.23), but the connection requires the region to be specified, which doesn't make sense if the endpoint is already specified:
```ruby
ddb = Aws::DynamoDB::Client.new(endpoint: 'http://127.0.0.1:8000')
Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
from /Users/felix/.rvm/gems/ruby-2.2.3/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/regional_endpoint.rb:30:in `after_initialize'
# Specify a bogus region
ddb = Aws::DynamoDB::Client.new(endpoint: 'http://127.0.0.1:8000', region: 'us-east-1')
=> #<Aws::DynamoDB::Client>
```

**Comment by trevorrowe** [comment]
The `:region` option is necessary for more than endpoint construction. DynamoDB requires version 4 signatures for authentication. A version 4 signature requires the region name. Its part of the canonical request, the derived key, and more. This validation message is intentional.
