### ISSUE TITLE
Document is misleading for the zip_file option of Aws::Lambda::Client#update_function_code

### ISSUE THREAD

**Issue by ShikChen** [aws/aws-sdk-ruby#942]
The document says:
> :zip_file (IO, String) — Based64-encoded .zip file containing your packaged source code.

But in fact you should **not** encode your zip file in Base64. The raw string of zip file just works.

**Comment by pchaganti** [comment]
You do not need to encode to base64. We are using 

```Ruby
IO.read(path_to_zip)  
```

**Comment by trevorrowe** [comment]
Thank you for reporting this issue. Currently we generate our API documentation from the same source as the service API reference. This means that sometimes HTTP wire-level documentation sneaks into the SDK documentation.  The SDK will automatically base64 encode data that is to be treated as a binary blob.

I'll see what we can do about improving the SDK documentation to not mention the encoding.
