### ISSUE TITLE
Getting incompletesignature errors when querying AWS::IAM

### ISSUE THREAD

**Issue by trekr5** [aws/aws-sdk-ruby#943]
Hi,

I'm hoping that someone can help me...

I'm trying to extract users in AWS using the following code:-

     require 'aws-sdk-v1'
     require 'aws-sdk'
     require 'yaml'
     require 'set'

    profile_name = "default"

    credentials = Aws::SharedCredentials.new(profile_name: profile_name)
    AWS::IAM::Client.new(credentials: credentials)
	iam = AWS::IAM::Client.new

	Aws.use_bundled_cert!

	users_list = iam.list_users.to_hash
	users = users_list[:users]
	list_of_users = Set.new()

	users.sort_by do |user|
		list_of_users.add user[:user_name].downcase
	end

      p list_of_users
However I receive the following error when I run my code:-
     c:/Users/test/.gem/ruby/1.9.1/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in      `return_or_raise': '/20151001/us-east-1/iam/aws4_request' not a valid key=value pair (missing
equal-sign) in Authorization header (AWS::IAM::Errors::IncompleteSignature)
 
I have regenerated my security credentials and created my credentials using aws configure.

Can anyone tell me why I'm getting this error? (I'm running ruby 193 on a Windows 8 os)

**Comment by trevorrowe** [comment]
While not necessarily related to your issue or question, I notice that you are mixing usage for the version 1 SDK with version 2. Is this intentional? Version 1 uses `AWS` while version 2  uses `Aws`. You should be able to do the following:

```ruby
require 'aws-sdk'

# This should be called first; Clients constructed before calling
# this method will not use the bundled certificate
Aws.use_bundled_cert!

# Version 2 will automatically load the shared credentials
# from the default profile, no configuration needed
iam = Aws::IAM::Client.new

user_names = []
iam.list_users.each do |response|
  user_names += response.users.map(&:user_name)
end
puts user_names.sort_by(&:downcase)
```

Or, you could use the resource interface, which will managing paging responses for you:

```ruby
require 'aws-sdk'

Aws.use_bundled_cert!

iam = Aws::IAM::Resource.new
user_names = iam.users.map(&:name)
puts user_names.sort_by(&:downcase)
```

**Comment by trevorrowe** [comment]
I am unable to reproduce your issue. The error message seems to indicate that the `Authorization` header is sending only the credential scope string. Try the example that I gave. If the problem persists, please feel free to re-open.
