### ISSUE TITLE
Aws::RDS Migrate snapshot to Aurora 

### ISSUE THREAD

**Issue by jmccarty3** [aws/aws-sdk-ruby#951]
Currently there does not seem to be any support built into the sdk to allow a user to migrate a db snapshot into an aurora instance like there is through the web interface. 

Using restore_db_cluster_from_snapshot with the snapshot_identifier set to a db_instance_snapshot results in an error being thrown. 

Is there any intention of this feature being added?

**Comment by trevorrowe** [comment]
Just to clarify, what version of the SDK are you using?

The latest version of the SDK does support the full RDS API. I am not very familiar with the RDS API, so I can not comment if there is some other mechanism to load a snapshot into Aurora instance. It might be worth asking your question in the RDS forum: https://forums.aws.amazon.com/forum.jspa?forumID=60&start=0

**Comment by jmccarty3** [comment]
SDK Gem info:
aws-sdk (2.1.29, 2.1.7, 2.0.48)
aws-sdk-core (2.1.29, 2.1.7, 2.0.48)
aws-sdk-resources (2.1.29, 2.1.7, 2.0.48)

I will check the the RDS forums as well. It could be a bummer if the migrate feature wasn't scriptable through the SDK though.

**Comment by trevorrowe** [comment]
You are running the latest version. Please feel free to re-open if you believe this is an SDK issue, and not just a limitation of the API.
