### ISSUE TITLE
Problems using the method .put_metric_data with Cloudwatch API

### ISSUE THREAD

**Issue by trekr5** [aws/aws-sdk-ruby#953]
Hi,

I'm trying to use the following method to  insert data into my Cloudwatch metric:

This is my code:-

    require 'yaml'
    require 'aws-sdk'
    require 'aws-sdk-v1'

    Aws.use_bundled_cert!

    cloudwatch = Aws::CloudWatch::Client.new(
	:region => ENV["AWS_REGION"],
       :access_key_id => ENV["AWS_ACCESS_KEY_ID"],
       :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]
	)

     resp = cloudwatch.put_metric_data({
      namespace: "Logstash Redis",
      metric_data: [{
      metric_name: "Dev",
      dimensions: [{ name: "Messages", value: "1.0" }],
      }],
       statistic_values: {
        sample_count: 1.0, # required
         sum: 1.0, # required
         minimum: 1.0, # required
         maximum: 1.0, # required
      },
    })

    p resp

    C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/aws-sdk-core    /param_validator.rb:26:in `validate!': unexpected value at params[:statistic_values] (ArgumentError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/seahorse/client/request.rb:70:in `send_request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.1.26/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from redis_logstash_queue.rb:48:in `<main>'

Can anyone please tell me the correct syntax to use this?
Many thanks

**Comment by trevorrowe** [comment]
You are close. The statistic_values option should have been nested inside the metric data.  For example:

```ruby
cloudwatch = Aws::CloudWatch::Client.new

resp = cloudwatch.put_metric_data({
  namespace: "Logstash Redis",
  metric_data: [
    {
      metric_name: "Dev",
      dimensions: [
        { name: "Messages", value: "1.0" },
      ],
      statistic_values: {
        sample_count: 1.0,
        sum: 1.0,
        minimum: 1.0,
        maximum: 1.0,
      },
    },
  ]
})
```
From the docs: http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudWatch/Client.html#put_metric_data-instance_method

Also worth noting, the SDK will automatically pull the region from `ENV['AWS_REGION']` and credentials from `ENV['AWS_ACCESS_KEY_ID']` and `ENV['AWS_SECRET_ACCESS_KEY']`. You should be able to construct your client without any options if those environment variables are set.

**Comment by trekr5** [comment]
Many thanks!
