### ISSUE TITLE
stubbing QueuePoller to get into the poll block

### ISSUE THREAD

**Issue by genslein** [aws/aws-sdk-ruby#959]
I have tried following documentation to stub the SQS QueuePoller to no avail and need help on understanding what I'm doing wrong. Below is the sample test I've tried to create to process the messages read from the queue and I'm trying to pass in a fake array of messages to process to the ```:poll``` method. I am using 2.1.28 of the gem.

```ruby
    before(:each) do
      Aws.config[:stub_responses] = true
      Aws.config[:sqs] = {
          stub_responses: {
              receive_message: [
                  { messages: [{message_id:'id1', receipt_handle:'rh1', body:json_string}] }
              ]
          }
      }
    end
    it 'creates a QueuePoller client' do
      expect(wrapper.poll_from_queue).to be_an_instance_of(Thread)
    end
```
my poller code is as follows:
```ruby
    Thread.new{
      poller = Aws::SQS::QueuePoller.new($aws_sqs_read, {:client => sqs})
      poller.poll do |msg|
        my_log_function("params being pulled from sqs: #{msg.body}")
        my_function(msg.body)
      end
    }
```
The error I get is as follows:
     Failure/Error: poller.stub_responses(:poll, msgs)
     NoMethodError:
       undefined method `stub_responses' for #<Aws::SQS::QueuePoller:0x007fd94632f240>

I have also used the link from the forum [here](https://forums.aws.amazon.com/message.jspa?messageID=652048) to no avail as setting this overrides trying to use the generic 
```Aws.config[:stub_responses] = true``` in my spec_helper giving me a missing credential error.

**Comment by trevorrowe** [comment]
I'm unable to reproduce the error you are experiencing. I ran the following code and it worked as expected:

```ruby
json_string = '{}'

Aws.config[:sqs] = {
  stub_responses: {
    receive_message: [
      { messages: [{message_id:'id1', receipt_handle:'rh1', body:json_string}] }
    ]
  }
}

sqs = Aws::SQS::Client.new

poller = Aws::SQS::QueuePoller.new('http://queue.url', client: sqs)
poller.poll do |msg|
  puts '----'
  puts msg.body
end
```

Please note, you do not need to set `Aws.config[:stub_responses] = true` and `Aws.config[:sqs] = { stub_responses: ... }`. It doesn't hurt, it just isn't needed unless you want every service to stub with empty responses and SQS to stub with non-empty responses.

Can you provide a full stack trace so I can get some more information about the error?

**Comment by genslein** [comment]
I think you are getting hung up on the error, the issue is you can't reach inside the poller.poll block with the given methodology. It's as you said the credential error went away from a configuration issue that was unrelated. I have tried changing the poller.poll test to do one of each of the following:
```ruby
      messages = [{message_id:'id1', receipt_handle:'rh1', body:json_string}]
      poller = Aws::SQS::QueuePoller.new(stub_responses: {
              poll: messages
              })
      allow_any_instance_of(Aws::SQS::QueuePoller).to receive(:new).with(any_args).and_return poller
```
alternatively
```ruby
      allow_any_instance_of(Aws::SQS::QueuePoller).to receive(:poll).with(any_args).and_return messages
```

The stub_responses method according to what I've dug for is only available on clients, and QueuePoller is a resource that has a client passed in, hence the method not found. Subsequently, passing the parameter to the function also doesn't do anything for the same reason. So the only stacktrace I get is:
```
NoMethodError: undefined method `stub_responses' for #<Aws::SQS::QueuePoller:0x007fa9db1ac430>
./spec/unit/AWSWrapper_spec.rb:52:in `block (3 levels) in <top (required)>'
/Users/genslein/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide.rb:86:in `debug_load'
/Users/genslein/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide.rb:86:in `debug_program'
```

**Comment by trevorrowe** [comment]
It was not clear from your previous code examples, but it looks like you are attempting to stub poller responses. You are correct, that response stubbing is only for `Aws::*::Client` classes. Your choices are to:

* Use the client to generate stubbed responses and let the poller operate on those. This is more of a functional test that exercises more of the system, but harder to write.
* Use your testing library (looks like rspec) to stub the public interface of the queue poller to yield the messages or raise errors as you desire. You can still use the client to generate stub data using `#stub_data`.

**Comment by genslein** [comment]
In my first post code block, the first bullet point is what I tried having the Aws.config block handle manipulating the SQS client under the hood so ```poller.poll``` would operate as if normal parameters were met. I expected it to let me into the code block normally to test my code operating on the messages which it does not. If I missed something on that block that would be helpful since I would like to avoid your 2nd bullet point

**Comment by trevorrowe** [comment]
I'm still not seeing the issue. Here is something I put together and ran through rspec:

```ruby

before(:each) do
  # you might want to define these in some sort of test fixture file
  Aws.config[:sqs] = {
    stub_responses: {
      receive_message: [
        {
          messages: [
            { message_id:'id1', receipt_handle:'rh1', body: '{}'}
          ]
        },
        { messages: [] }
      ]
    }
  }
end

after(:each) do
  # ensure no state leak between tests
  Aws.config.clear
end

it 'processes queue messages' do
  logger = double('logger')
  expect(logger).to receive(:info).with('{}')
  poller = Aws::SQS::QueuePoller.new('https://queue.url')
  poller.poll(idle_timeout:0.5) do |msg|
    logger.info(msg.body)
  end
end
```
