### ISSUE TITLE
How to copy a specified version of an object?

### ISSUE THREAD

**Issue by christiangenco** [aws/aws-sdk-ruby#969]
The [Amazon REST API Documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) cites the following:

> ### Sample Request: Copying a specified version of an object
> 
> The following request copies the key my-image.jpg with the specified version ID and copies it into the bucket bucket and gives it the key my-second-image.jpg.
> 
> ```
> PUT /my-second-image.jpg HTTP/1.1
> Host: bucket.s3.amazonaws.com
> Date: Wed, 28 Oct 2009 22:32:00 GMT
> x-amz-copy-source: /bucket/my-image.jpg?versionId=3/L4kqtJlcpXroDTDmJ+rmSpXd3dIbrHY+MTRCxf3vjVBH40Nr8X8gdRQBpUMLUo
> Authorization: authorization string
> ```

I see the [copy_from](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/object.rb#L44) and [copy_to](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/object.rb#L85) methods in `Aws::S3::Object`, but I can't for the life of me figure out how to specify a `versionId` in either of these requests.

Am I missing something painfully obvious, or should I resort to a raw REST request?

**Comment by christiangenco** [comment]
Here's one of the more probable things I've tried:

```ruby
source_object = Aws::S3::ObjectVersion.new({
  bucket_name: "source_bucket",
  object_key: "test.txt",
  id: "WYIIJB3UpKixITFbqLP6nVbAJsa5Ul5F",
  client: Aws::S3::Bucket.new(name: "source_bucket").client # there's probably an easier way to get a client object
})

destination_object = Aws::S3::Bucket.new("destination_bucket").object("test.txt")

source_object.copy_to(destination_object) 
# NoMethodError: undefined method `copy_to' for #<Aws::S3::ObjectVersion:0x007fb7f9052d88>

destination_object.copy_from(source_object) 
# ArgumentError: expected source to be an Aws::S3::Object, Hash, or String
# from .rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/services/s3/object_copier.rb:44:in `copy_source'
```

**Comment by christiangenco** [comment]
Looks like that didn't work because `S3::ObjectCopier#copy_source` doesn't support `S3::ObjectVersion` as a possible argument (and unlike [version 1](https://github.com/aws/aws-sdk-ruby/tree/aws-sdk-v1), `S3::ObjectVersion` is not a subclass of `S3::Object`).

I thought the `#copy_source` method might be monkey patched to fix this:

```ruby
module Aws
  module S3
    class ObjectCopier
      def copy_source(source)
        case source
        when String then escape(source)
        when Hash then "#{source[:bucket]}/#{escape(source[:key])}"
        when S3::Object then "#{source.bucket_name}/#{escape(source.key)}"
        when S3::ObjectVersion then "#{source.bucket_name}/#{escape(source.key)}?versionId=#{escape(source.id)}"
        else
          msg = "expected source to be an Aws::S3::Object, AWS::S3::ObjectVersion, Hash, or String"
          raise ArgumentError, msg
        end
      end
    end
  end
end
```

but now `destination_object.copy_from(source_object)` throws:

```
NotImplementedError: #load not defined for Aws::S3::ObjectVersion
from .rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.30/lib/aws-sdk-resources/resource.rb:150:in `load'
```

I can't find an actual definition for `Aws::S3::ObjectVersion` (it looks like it's being dynamically created from `Aws::Resources::Resource`?), so I'm not sure how to implement this mysterious `#load` method. It might just be assigning a `LoadOperation`, but I'm in over my head at this point.

I'll start down the road of submitting a raw REST request, though figuring out [how to sign requests](http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html#sigv4_signing-steps-summary) outside of this gem looks like it might be just as difficult.

**Comment by trevorrowe** [comment]
This is currently a limitation of the `#copy_from` and `#copy_to` methods. As a workaround you use the Aws::S3::Client#copy_from method directly:

```ruby
s3 = Aws::S3::Client.new
s3.copy_from({
  bucket: 'target-bucket',
  key: 'target-key',
  copy_source: "source-bucket/source-key?versionId=123456789..."
})
```

You need to ensure the source key is correctly escaped. You can call `Seahorse::Util.uri_path_escape(key)` to ensure the key is correctly escaped. You don't have to worry about the bucket name, S3 limits bucket names to characters that do not require escaping. You might have to call `Seahorse::Util.uri_escape` on the version id value. I don't know what characters might appear in the version ID, but escaping the ID should be perfectly reasonable. 

I'll mark this issue as a feature request to add support for copying versioned IDs to the resource interfaces as a feature request.

**Comment by christiangenco** [comment]
Ahh perfect! Thank you so much :smile: 

For anyone else walking down this path, check out the [full documentation on that `Aws::S3::Client#copy_object` method](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#copy_object-instance_method).

Also, it looks like [you just added `Seahorse::Util#uri_path_escape`](https://github.com/aws/aws-sdk-ruby/commit/d0661e756042dfebd6053c425d25c748c7ad70ac) and it hasn't been published to rubygems yet, so I just patched it in an init script:

```ruby
if !defined? Seahorse::Util.uri_path_escape
  module Seahorse
    module Util
      class << self
        def uri_path_escape(path)
          path.gsub(/[^\/]+/) { |part| uri_escape(part) }
        end
      end
    end
  end
end
```

Those are some nifty helper methods - URI escaping is always strangely confusing in Ruby. It'd be lovely if you could just do `String#escape` or `String#escape_url`, but I digress.

**Comment by awood45** [comment]
Added this to the feature request backlog.

**Comment by lwoggardner** [comment]
Not sure how to "vote" for feature requests, so I'll just "me too" here.

**Comment by mullermp** [comment]
Reopening - deprecating usage of Feature Requests backlog markdown file.
