### ISSUE TITLE
Request ID Not Present in Response

### ISSUE THREAD

**Issue by abhaykumar** [aws/aws-sdk-ruby#971]
We are upgrading our AWS SDK stack from version 1.42.0 to version 2.1.32.
In the response structure of AWS SES after sending email in version1 both message id as well as request id was present.

However in version 2 only message id is present in response.

How can I get request id after sending email in version 2?
Is this intentional?

**Comment by awood45** [comment]
This is still available to you in V2. Try this:
```ruby
client = Aws::SES::Client.new
resp = client.send_email(options)
resp.context[:request_id]
```

**Comment by abhaykumar** [comment]
WOW!
Super awesome
that works great

**Comment by awood45** [comment]
Glad to hear. From V1 to V2 the way we store some metadata has changed, I think that's what you were seeing. Let me know if you have more questions.

**Comment by abhayathem** [comment]
Wrote a post with sample code.
http://www.hackpundit.com/amazon-ses-request-id-sdk-version2/
Hope it help others and save their time.
