### ISSUE TITLE
`Aws::AutoScaling::Client`: size/length methods off by one

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-ruby#972]
Proof:

![screen shot 2015-10-28 at 03 47 22](https://cloud.githubusercontent.com/assets/1162994/10778453/c36e1fe2-7d26-11e5-83c0-7174c124aa2b.png)

...I'm new to the SDK but this doesn't seem to make a lot of sense.

Using 2.1.31.

**Comment by awood45** [comment]
If you take a look at the [documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/AutoScaling/Client.html#describe_auto_scaling_groups-instance_method), you will see that the response is actually a struct.

The length is the number of response attributes, which can vary from operation to operation. Example:
```ruby
resp = autoscaling.describe_lifecycle_hook_types
```
Will return: `=> #<struct Aws::AutoScaling::Types::DescribeLifecycleHookTypesAnswer lifecycle_hook_types=["autoscaling:EC2_INSTANCE_LAUNCHING", "autoscaling:EC2_INSTANCE_TERMINATING"]>`
```ruby
resp.length # => 1
```
When you're accessing the [0] value of that array, you're fetching the same value you'd get if you called:
```ruby
resp.auto_scaling_groups
```
When you're accessing the [1] value of that array, you're fetching the `next_token` part of the response, which is `nil` (indicating the response wasn't paginated.

If you have multiple auto scaling groups, you can array access them like so:
```ruby
resp.auto_scaling_groups[0]
resp.auto_scaling_groups[1]
# or
resp.auto_scaling_groups.each { |group| puts group.auto_scaling_group_name }
```

Hope this helps, we document the response structure for every operation in our [documentation](http://docs.aws.amazon.com/sdkforruby/api/).
