### ISSUE TITLE
uninitialized constant Aws::Log::ParamFilter::Set in Aws::Log::Formatter.default

### ISSUE THREAD

**Issue by rbroemeling** [aws/aws-sdk-ruby#977]
There is an auto-loading error in aws-sdk that manifests if there is an attempt to use `Aws::Log::Formatter.default` before using any of the larger services.  After using the larger services (i.e. `Aws::S3` or similar), the utility classes are correctly auto-loaded and the error goes away.  This bites us because we try to initialize `Aws.config` before instantiating any services. For example, code like this will demonstrate the problem (we do this to remove the newline from the default aws-sdk log format):

```ruby
require 'aws-sdk'
Aws.config.update({
  log_formatter: Aws::Log::Formatter.new(Aws::Log::Formatter.default.pattern.chomp),
  log_level: :info
})
```

We've worked around it by simply doing `Aws::S3` before we use `Aws::Log::Formatter.default`, but this is obviously not really desirable.  More specifically, the issue is very replicable by including aws-sdk and then referencing `Aws::Log::Formatter.default`:

```
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> Aws::VERSION
=> "2.1.32"
irb(main):003:0> Aws::Log::Formatter
=> Aws::Log::Formatter
irb(main):004:0> Aws::Log::Formatter.default
NameError: uninitialized constant Aws::Log::ParamFilter::Set
	from ~/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.32/lib/aws-sdk-core/log/param_filter.rb:16:in `initialize'
	from ~/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.32/lib/aws-sdk-core/log/formatter.rb:89:in `new'
	from ~/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.32/lib/aws-sdk-core/log/formatter.rb:89:in `initialize'
	from ~/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.32/lib/aws-sdk-core/log/formatter.rb:203:in `new'
	from ~/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.32/lib/aws-sdk-core/log/formatter.rb:203:in `default'
	from (irb):4
	from ~/.rbenv/versions/2.1.4/bin/irb:11:in `<main>'
irb(main):005:0> Aws::S3 unless defined?(Aws::Log::ParamFilter::Set)
=> Aws::S3
irb(main):006:0> Aws::Log::Formatter.default
=> #<Aws::Log::Formatter:0x007ff406250498 @pattern="[:client_class :http_response_status_code :time :retries retries] :operation(:request_params) :error_class :error_message\n", @param_formatter=#<Aws::Log::ParamFormatter:0x007ff406250448 @max_string_size=1000>, @param_filter=#<Aws::Log::ParamFilter:0x007ff406250420 @filters=#<Set: {:admin_contact, :artifact_credentials, :auth_code, :base_32_string_seed, :copy_source_sse_customer_key, :new_password, :old_password, :password, :plaintext, :private_key, :qr_code_png, :registrant_contact, :secret_access_key, :shared_secret, :sse_customer_key, :ssekms_key_id, :tech_contact, :username}>>>
irb(main):007:0> Aws::S3 unless defined?(Aws::Log::ParamFilter::Set)
=> nil
```

**Comment by awood45** [comment]
I'm able to recreate this, thanks for the report. Will take a deeper look.

**Comment by awood45** [comment]
I've found the issue, we just need to ensure that we've run `require 'set'` before we attempt to create a ParamFilter. This happens by coincidence when you create a service client (or do various other things), but should just be explicit in the file. Writing a quick fix that will go out with the next release.

If you need a fix sooner, just ensure you do a require ahead of the config call, like so:
```ruby
require 'aws-sdk'
require 'set'
Aws.config.update({
  log_formatter: Aws::Log::Formatter.new(Aws::Log::Formatter.default.pattern.chomp),
  log_level: :info
})
```

Sorry for the oversight, and thanks for reporting this.
