### ISSUE TITLE
What is the purpose of Seahorse::Util.uri_escape?

### ISSUE THREAD

**Issue by vinhboy** [aws/aws-sdk-ruby#980]
Hi,

I am using a [gem](https://github.com/winebarrel/faraday_middleware-aws-signers-v4) which uses the `Aws::Signers::V4` module to sign requests to AWS.

However, if the URI has a `+` plus symbol in it, the request fails: `The request signature we calculated does not match`

I noticed in aws-sdk-ruby, there is a specific method to address this problem:

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/seahorse/util.rb#L23

Can you guys explain why you've implemented this? Is it because Ruby URI encodes spaces as `+` and aws expects `%20`? Do you escape all URI this way?

Thanks.

**Comment by trevorrowe** [comment]
Yes and yes. This is what is expected, and we use the same escape in all cases.

**Comment by vinhboy** [comment]
Thanks!
