### ISSUE TITLE
SQS QueuePoller not receiving all messages

### ISSUE THREAD

**Issue by tomderham** [aws/aws-sdk-ruby#981]
Hi

We are implementing the SQS QueuePoller per below code snippet (which is almost identical to the sample). Our SQS receives notifications from an S3 bucket when files are added/deleted.
When adding/deleting files (from S3 console), we find that in many cases we do not receive/log the SQS notification. On uploading/deleting a single file, quite often (50% of time?) we receive no notification at all. On uploading/deleting several files, we receive notification for only a fraction (30%?) of the files.
SQS CloudFront analytics show the expected number of messsages received/sent, so the backend seems fine. 

Could this be a bug, or are there any implementation issues we should be aware of?
Many thanks...

	sqs_client = Aws::SQS::Client.new(
	  region: Rails.configuration.aws_region,
	  access_key_id: Rails.configuration.aws_access_key_id,
	  secret_access_key: Rails.configuration.aws_secret_access_key
	)

	queue_url = sqs_client.get_queue_url(queue_name: Rails.configuration.aws_sqs_s3_events).queue_url

	sqs_poller = Aws::SQS::QueuePoller.new(queue_url, client: sqs_client)

	Thread.new do
		sqs_poller.poll do |msg|
			log_msg = "SQS message received: message #{msg.body}"
			Rails.logger.info(log_msg)
			p log_msg
                        # do work
		end
	end

**Comment by awood45** [comment]
I'll take a look at this.

Keep in mind that at the end of the block, messages are automatically deleted, so if you're accessing from multiple places, there could be a contention issue (not that your code indicates this per se).

I'll try to see if I can reproduce this.

**Comment by tomderham** [comment]
Many thanks Alex.
Actually your response gave us the hint we needed to solve this - we had another test VM (forgotten about) that was running another instance of the worker, and so "stealing" some of the messages.
Having disabled that, everything is working fine.
Is there any alternative way to deal with this kind of scenario, or we just need to definitively ensure there is only a single consumer worker?

**Comment by awood45** [comment]
I'm relieved to hear that!

I'd personally recommend using a separate queue for any testing.

An option does exist to not automatically delete messages after the block completes, but figuring out how to apply that properly for testing would be a lot of complexity. Best to have a "test queue" which can, for example, have test messages sent to it to test whatever behavior you want to trigger.

Let me know if you have any more questions.
