### ISSUE TITLE
Example Scripts for Amazon IoT

### ISSUE THREAD

**Issue by dwalkes** [aws/aws-sdk-ruby#982]
Hi,
Thanks for putting together the very well documented and useful Ruby SDK!

I've created some ruby scripts in the repository at https://github.com/dwalkes/amazon_iot_scripts which automate some of the steps in the [AWS IoT Quickstart](http://docs.aws.amazon.com/iot/latest/developerguide/iot-quickstart.html).  I'm not sure if you would like code like this merged with the aws-sdk-ruby repository or if you would prefer not to include it.  If you have any interest I could do a cleanup/documentation pass and create a pull request along with any changes you'd like included.  Just let me know where you'd like it in the repo and if there are any specific changes you know you'd like me to make.

If you'd prefer not to include this code that's fine as well, I just thought I'd offer to contribute.

**Comment by awood45** [comment]
Thanks for this, looks interesting!

We're looking at some ways to include examples like this, so we may take you up on this soon. Going to leave this open for a bit, because right now there isn't a perfect place fit for this yet. Watch this space.

**Comment by awood45** [comment]
We now have a [developer guide](https://github.com/aws/aws-sdk-ruby/tree/master/developer_guide) that you can contribute to, if you would like.

We would welcome example contributions to that guide, and would be happy to help with crafting a PR. Thanks!
