### ISSUE TITLE
Presigned URLs can not have `expires_in: ` option of more than a week.

### ISSUE THREAD

**Issue by m-krull** [aws/aws-sdk-ruby#983]
The limit is set in `aws-sdk-core/s3/presigner.rb`.

To me this limit seems somewhat random as it is also not explained in the documentation or comments. Is that a limit set by the Amazon API? If it is, why is it handled in the presigner explicitly instead of using the failed request? If it is not, why is it enforced in the presigner?

**Comment by trevorrowe** [comment]
This is a limitation of sigv4 presigned URLs. It is handled in the presigned as the error messages received from the api can be hard to decipher and frequently are consumed by users that did not generate the url.

**Comment by awood45** [comment]
The presigner enforces the limit because that sigv4 limitation would otherwise cause errors (you could see this if you tried to manually generate a presigned request with a different limit.
