### ISSUE TITLE
How to download a big file from s3 ? 

### ISSUE THREAD

**Issue by ahmad-alkheat** [aws/aws-sdk-ruby#990]
Currently ```s3.get_object``` is freezing and not returning anything because the file is too big, is there a way to go around this? 

Thanks

**Comment by awood45** [comment]
You can work around this by making ranged requests to the large object and reassembling the parts.

Here's one example:

```ruby
client = Aws::S3::Client.new
part = "bytes=0-4999"
resp = client.get_object(bucket: bucket, key: key, range: part)
```

This will get 5000 bytes of the object, and you could do this (with larger blocks) sequentially for the full size of the object.

That's the workaround, I'm also working on putting something like this together as an SDK feature that compliments multipart uploads.

**Comment by ahmad-alkheat** [comment]
@awood45  Thanks a bunch, that makes sense.
