### ISSUE TITLE
Param checker could be friendlier

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-ruby#991]
What it prints:

`expected params[:pipeline_objects][1][:fields][5][:string_value] to be a string`

What it should print:

`expected params[:pipeline_objects][1][:fields][5][:string_value] to be a string, got instead the value 2 (class: Fixnum)`

Cheers - Victor

**Comment by awood45** [comment]
That sounds like a good idea, I'll see if there's any reason not to do that. If you'd like, feel free to open a pull request for this as well.

**Comment by awood45** [comment]
I've added this to the feature request list, let me know if you have any other questions or ideas!
