### ISSUE TITLE
A note about stubbing

### ISSUE THREAD

**Issue by MarkMurphy** [aws/aws-sdk-ruby#992]
It would be really helpful to add some documentation to the readme regarding how we can stub the client for testing.

For example, from the docs here: 
http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html

Can I add 
```ruby
RSpec.configure do |config|
  ...
  Aws.config.update(stub_responses: true)
end
``` 
to enable stubbed responses across the board?

**Comment by awood45** [comment]
The example you gave will work, yes. (It will return empty responses if you don't further specify response content - not necessarily valid, but stubbed.)

We appreciate the suggestion, and are currently working on a developer guide that will include information about testing.
