### ISSUE TITLE
How do I enable logging to the console?

### ISSUE THREAD

**Issue by MarkMurphy** [aws/aws-sdk-ruby#993]
I'm using this is a rails project and I'd like to see logging shown on my terminal window. Is there a way to enable that by setting a value in Aws.config.update({...}) or something?

**Comment by MarkMurphy** [comment]
Got it:

```ruby
Aws.config.update({
  logger: Logger.new($stdout)
})
```

**Comment by trevorrowe** [comment]
Another option is to use the `aws-sdk-rails` gem. This gem will automatically log to the `Rails.logger`. It will also add support for sending emails with Amazon SES.
