### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by amedeiros** [aws/aws-sdk-ruby#995]
We are seeing this error across several different service clients. I noticed several other tickets for a few different services having this same issue. It seems like its possibly a SDK wide issue. Below is a list of the services that we are seeing the problem with on SDK version `2.1.34`. This is greatly impacting our customer base.

```
EC2
S3
RDS
IAM
ElasticLoadBalancing
DirectConnect
```

**Comment by awood45** [comment]
Can you tell me a bit more about the operations you're performing where these issues are happening? It will help quite a bit to be able to reproduce what you're seeing.

**Comment by amedeiros** [comment]
A api call examples below which are describe or list calls. We have tried to recreate the issues with no luck. It is at random and is also intermittent.

```
EC2#describe_security_groups
RDS#describe_db_instances
ELB#describe_load_balancers
DirectConnect#describe_virtual_gateways
S3#list_buckets
IAM#list_server_certificates
```

**Comment by awood45** [comment]
Where are you running these? Are you using EC2 instance profiles?

**Comment by amedeiros** [comment]
They are running on EC2 instances. We use the IAM role attached to the instance then we are assuming role on our customer accounts. Then we make the calls on behalf of the customer via the third party assumed role.

**Comment by awood45** [comment]
Are you using the Aws::AssumeRoleCredentials class? If so, are you using EC2 Instance Credentials to call this, or static credentials?

We can take this discussion off GitHub if that's a sensitive question, but I'd like to investigate if this implies a bug in AssumeRoleCredentials.

**Comment by amedeiros** [comment]
We use the role on the EC2 instance that gives us the privileges to do assume role. We then do STS#AssumeRole from the SDK. The returned session is then cached and reused for 50 minutes because a session is good for 60 minutes. So we time out the session 10 minutes prior to what STS does. Then wether or not the credentials come back from the cache or directly from a new STS call we build a `Aws::Credentials` object then we pass that to the client `Aws::EC2::Client.new(credentials: Aws::Credentials, region: public_cloud_region)`. We do that for all our clients. In the past we were just passing the session credentials as a hash to the clients but were having this same problem with that as well.

**Comment by amedeiros** [comment]
@awood45 any updates on this currently?

**Comment by johnathanludwig** [comment]
@awood45 Here is the http request that is logged with the error. Keep in mind this is happening for multiple services and regions.

```
Aws::ElasticLoadBalancing::Errors::SignatureDoesNotMatch The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:elasticloadbalancing.sa-east-1.amazonaws.com
user-agent:aws-sdk-ruby2/2.1.36 ruby/2.2.3 x86_64-linux-gnu
x-amz-content-sha256:23<stripped>4a
x-amz-date:20151118T182331Z
x-amz-security-token:AQ<stripped>==

content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token
23<stripped>4a'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151118T182331Z
20151118/sa-east-1/elasticloadbalancing/aws4_request
ff<stripped>e5'
 
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/plugins/raise_response_errors.rb:15 call
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/plugins/param_converter.rb:20 call
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core/plugins/response_paging.rb:26 call
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/plugins/response_target.rb:21 call
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/request.rb:70 send_request
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.36/lib/seahorse/client/base.rb:207 block (2 levels) in define_operation_methods
```

**Comment by awood45** [comment]
I'll take a look at this with the new information - especially if this is intermittent it would usually indicate credential expiration, but I'll try and reproduce.

**Comment by johnathanludwig** [comment]
Yeah on our end the credentials are always coming from the IAM role attached to the EC2 instance. As @amedeiros said we only use the session from assuming the role for 50 minutes before getting a new one.

Could there be something else that causes the session to get expired early?

Also is there anyway to know what all the different types of access errors there are? They all seem dynamic and undocumented. We've gotten all of these exceptions that look related and have the same stack trace. Some of them don't give the full output like the example above and instead say

> The security token included in the request is invalid.

- Aws::Route53::Errors::InvalidClientTokenId
- Aws::EC2::Errors::AuthFailure
- Aws::RDS::Errors::InvalidClientTokenId
- Aws::S3::Errors::InvalidAccessKeyId
- Aws::ElasticLoadBalancing::Errors::SignatureDoesNotMatch
- Aws::DirectConnect::Errors::UnrecognizedClientException

**Comment by johnathanludwig** [comment]
Ok I was able to catch it while it was happening and test using the cached session and compare with a new session. It did seem to work fine with a new session. So we are going to have to add all these errors to be rescued and get a new session... Still leaves us with those two questions.

These sessions definitely are intermittently expiring sooner then they should. I was in the middle of using one testing with one that was working and then it expired with 13 minutes remaining. 

Also it would be great if there was consistent naming for errors. It seems very likely this issue will resurface under a new exception name.

**Comment by awood45** [comment]
I can see the frustration with the error names - it can vary by service, and if there were a way to model this in a unified way (for example, a common ancestor exception class) that could be helpful. I can explore if there is a sensible way to do that.

I'm going to explore with the service teams why these sessions are expiring earlier than you're expecting. I'll share whatever I can find.

**Comment by awood45** [comment]
Can you tell me a bit more about how you're caching the credentials on your end? Expiration of the credentials should be giving you a different error.

@johnathanludwig - what error did you get for the case where you say "These sessions definitely are intermittently expiring sooner then they should. I was in the middle of testing with one that was working and then it expired with 13 minutes remaining."? Was it these assorted signature errors, or a token expiration error?

**Comment by johnathanludwig** [comment]
I _want_ to say it was an EC2 AuthFailure, but I unfortunately didn't make a note of which one it was.

This is the logic for our caching code. The `@credentials` are what get passed to the clients we build. You can see that we set a redis ttl based on the expiration that comes back from the `assume_role`. We don't have any other code that touches the expiration so it shouldn't get changed once set. We unfortunately aren't saving the original expiration, but I have looked at the remaining ttl on redis for keys when they fail and there are often times 10+ minutes remaining. 

```ruby
if redis.exists(key)
  build_credentials(redis.hgetall(key))
else
  role = Aws::STS::Client.new(region: @region).assume_role(@keys)
  ttl  = ((role.credentials.expiration.to_i - 10.minutes.to_i) - Time.now.to_i).to_i
  build_credentials(role.credentials)
  redis.hsetnx(key, :session_token,     credentials.session_token)
  redis.hsetnx(key, :access_key_id,     credentials.access_key_id)
  redis.hsetnx(key, :secret_access_key, credentials.secret_access_key)
  redis.expire(key, ttl)
end

def build_credentials(credentials)
  @credentials = Aws::Credentials.new(credentials['access_key_id'],
                                      credentials['secret_access_key'],
                                      credentials['session_token'])
end
```

I have used the sessions that were failing to manually build different clients and try different api calls. I never got the "ExpiredToken" which is what we previously expected. For example, I took one that was throwing `Aws::RDS::Errors::SignatureDoesNotMatch` and tried to use that session to make an EC2 describe regions call. The result of the `describe_regions` was:

> Aws::EC2::Errors::AuthFailure: AWS was not able to validate the provided access credentials

Requesting a new session for the given role and making the same call would work.

**Comment by awood45** [comment]
So, if you're getting this brand of error is is most likely that your access key and secret key do not match.

(Disclaimer: I am not a Redis expert.) It seems possible that, since you're accessing each component of the credential separately, that you could have race conditions in your caching. I would be curious to see what happens if you serialized the 3 credential components into a single stored object, and deserialized it together.

If that fixes the problem, then a synchronization issue is the culprit.

**Comment by johnathanludwig** [comment]
We have some redis locking code around the code I posted above. I was looking at to see how it works and I believe you are correct. It looks to me like there is a possible race condition where they could both fall into the `else` at the same time and go through the set calls. 

We have already put the rescue code in on our end, plus we have another change where the caching happens up front in a single call so the race condition shouldn't happen anymore.

Either way, we should be able to replace the `hsetnx` with `hmset` so they all get set in a single call. That way if they do get overwritten they at least stay lined up correctly.

@awood45 Thank you for the help!

**Comment by awood45** [comment]
Glad to hear we might be on to something - please let me know if you have any more questions, happy to help further if I can.
