### ISSUE TITLE
Get signing request failing with signature error due to Content-Length

### ISSUE THREAD

**Issue by atiro** [aws/aws-sdk-ruby#996]
We are trying to send GET signed requests using Seahorse to AWS, but it is failing with a "request signature does not match the signature you provided". It seems to be due to the Content-Length header which is being forced on us because the build_net_request function in seahorse/client/net_http/handler.rb sets the request body to body_stream, instead of body; this then makes the net/http library assume the request should have some body content so only works if a content length is sent (in send_request_with_body_stream)

Commenting out this line works for a GET but will no doubt break a POST. Should this be set depending on the http method ?

**Comment by awood45** [comment]
Could you tell me a bit more about the request you're making? Would help me give a more complete answer.

**Comment by atiro** [comment]
Sure, we are trying to get some data from our Amazon Elasticsearch endpoint. We following the python work through to generate the signed request and this worked fine, the only difference with the ruby request was the added Content-Length header which returns the error:

"{\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'GET\\n\\n\\ncontent-length:\\n[...]

which doesn't match the header the library sends (content-length:0). But we can't not send the header because body_stream is set in the seahorse handler.

**Comment by awood45** [comment]
I think I see what you're getting at - it would help if you could give me more detailed reproduction steps to create the error on my end (I can spin up an ES cluster of my own as needed to do this).

**Comment by atiro** [comment]
Sure (apologies, new to ruby so terminology is not great!). Am using the example code adapted for ES like follows (replacing with your own ES ENDPOINT):

```
require 'aws-sdk-core'
require 'uri'
require 'net/http'
 
region = 'eu-west-1'
prefix= 'es'
endpoint = URI.parse(ES ENDPOINT)
 
# setup required configuration options for the NetHttp::Handler
config = Seahorse::Client::Configuration.new
Seahorse::Client::NetHttp::ConnectionPool::OPTIONS.each_pair do |name, default|
  config.add_option(name, default)
end
 
# these are the default options you would get by calling
# the `Configuration.build!` method without options
config = config.build!({
  http_proxy: nil,
  http_open_timeout: 15,
  http_read_timeout: 60,
  http_idle_timeout: 5,
  http_continue_timeout: 1,
  http_wire_trace: false,
  logger: nil,
  ssl_verify_peer: true,
  ssl_ca_bundle: nil,
  ssl_ca_directory: nil,
  ssl_ca_store: nil,
})
 
 
# build the http request
context = Seahorse::Client::RequestContext.new(config: config)
context.http_request.endpoint = endpoint
context.http_request.http_method = "GET"
context.http_request.headers["x-amz-date"] = Time.now.utc.strftime("%Y%m%dT%H%M%SZ")
context.http_request.headers["host"] = ES ENDPOINT


# sign the http request
credentials = Aws::Credentials.new('','')
Aws::Signers::V4.new(credentials, prefix, region).sign(context.http_request)

# send the http request
Seahorse::Client::NetHttp::Handler.new.call(context)
 
# inspect the http response
p context.http_response.status_code
p context.http_response.headers
p context.http_response.body.read
p context.http_response.error # populated when network error encountered
```

This won't work, failing with the Signature does't match error (because for some reason the content-length header has lost its value when the signature calculated on AWS side, not sure why). Anyway, content-length isn't needed for the GET, so if we stop content-length being sent it works, but we can only do this if  we stop using body_stream. This is hard-coded in build_net_request though.

**Comment by awood45** [comment]
I think this is related to #929 and #1014 - investigating.

**Comment by awood45** [comment]
So, if content-length is added after signing, then your request should work. Locally, my default handler order has content-length headers added after signing, which is why I can't recreate this locally.

What I'd like to see is your handler ordering and priority, to see if your handler order differs from mine. Can you give me the output of:
```ruby
client = Aws::CloudSearchDomain::Client.new(opts) # However you normally construct it.
client.handlers.entries.each { |h| puts "#{h.class}: #{h.step} #{h.priority}" }; nil
```

This will help me debug.

**Comment by awood45** [comment]
Based on other output I've seen, don't worry about my last ask. We believe that what you're seeing is a server-side issue around signing, specifically around the content-length header, and are continuing to investigate.

**Comment by awood45** [comment]
Pull request #1026 would resolve this issue by preventing any signing of the content-length header, even before this is fixed server side.

That fix will go out with our next release.
