### ISSUE TITLE
RDS snapshots being returned with a nil time for creation

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#997]
When we describe RDS snapshots, we are getting some back with a snapshot creation time of nil. There should really never be a snapshot creation time that is nil. The snapshot was successfully completed, so it should have a time. This seems to have started happening only with a recent SDK release. Any ideas?

```Ruby
#<struct Aws::RDS::Types::DBSnapshot 
db_snapshot_identifier="db-rds-west2-2015-11-12-06-30-10utc-daily", 
snapshot_create_time=nil, 
engine="mysql", 
source_region="us-west-2", 

```

thanks

**Comment by awood45** [comment]
Can you provide a stack trace for this call? I would suspect you're not getting this value back from the service, as I don't know of any SDK customizations that would do this.

**Comment by pchaganti** [comment]
Using sdk version 2.1.33. Could you please clarify what info you need?

```Ruby
rds.describe_db_snapshots(db_instance_identifier: dbinstance)
```

**Comment by awood45** [comment]
Just need to see what's going over the wire. You can do this by setting the `http_wire_trace` parameter when creating the client. So:
```ruby
rds = Aws::RDS::Client.new(http_wire_trace: true)
rds.describe_db_snapshots(db_instance_identifier: dbinstance)
```
Feel free to trim out identifying details, but my guess is that we aren't altering the service response in any way.

**Comment by pchaganti** [comment]
When a db snapshot API call is made, does the snapshot have the create time assigned immediately, or is that time assigned when the creation is complete. In our case we are making the API call to create snapshot, and then listing all the snaps. Maybe that is why the snap create time is nil? Cant really tell from the docs when the time is assigned.

thanks!

**Comment by awood45** [comment]
I am not sure off-hand, but that explanation sounds plausible. I can forward that question to the RDS team.

**Comment by awood45** [comment]
You're correct in observing that the API is returning the time that the snapshot creation completed. Nothing has changed on the SDK side, we're just presenting the result of the API call to the service. You could try repeating the call until the snapshot creation is completed or fails (which sounds like a new waiter that could be added).

Closing this now, let me know if you have more questions.
